### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jhautefeuille** [bettercap/bettercap#1000]
* bettercap v2.32.0
* Ubuntu 22.04 LTS
* go version go1.19 linux/amd64

bettercap v2.32.0 (built for linux amd64 with go1.19) [type 'help' for a list of commands]

panic: runtime error: index out of range [0] with length 0
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd2064f]

goroutine 1 [running]:
github.com/bettercap/bettercap/session.(*Session).Close(0xc0000fee00)
	/tmp/bettercap/session/session.go:190 +0xef
panic({0x11513c0, 0xc00003b5d8})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/bettercap/bettercap/routing.update()
	/tmp/bettercap/routing/update_linux.go:40 +0x5e5
github.com/bettercap/bettercap/routing.Update()
	/tmp/bettercap/routing/tables.go:19 +0x7c
github.com/bettercap/bettercap/routing.Gateway({0x11b5914, 0x4}, {0xc000a0f6b0, 0xf})
	/tmp/bettercap/routing/tables.go:23 +0x6b
github.com/bettercap/bettercap/network.FindGateway(0xc00021d200)
	/tmp/bettercap/network/net_gateway.go:10 +0x3c
github.com/bettercap/bettercap/session.(*Session).Start(0xc0000fee00)
	/tmp/bettercap/session/session.go:254 +0x2ce
main.main()
	/tmp/bettercap/main.go:49 +0x458

**Comment by Lolozendev** [comment]
same error here after doing basic operation as root:
```
    1  apt update
    2  apt install golang git build-essential libpcap-dev libusb-1.0-0-dev libnetfilter-queue-dev
    3  git clone https://github.com/bettercap/bettercap.git
    4  cd bettercap
    5  make build
    6  make install
    7  bettercap
```
bettercap v2.32.0 (built for linux amd64 with go1.19.5) [type 'help' for a list of commands]

panic: runtime error: index out of range [0] with length 0
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd2108f]

goroutine 1 [running]:
github.com/bettercap/bettercap/session.(*Session).Close(0xc000039180)
	/home/zzz/Téléchargements/bettercap/session/session.go:190 +0xef
panic({0x11526a0, 0xc0001329d8})
	/usr/lib/go-1.19/src/runtime/panic.go:884 +0x212
github.com/bettercap/bettercap/routing.update()
	/home/zzz/Téléchargements/bettercap/routing/update_linux.go:40 +0x5e5
github.com/bettercap/bettercap/routing.Update()
	/home/zzz/Téléchargements/bettercap/routing/tables.go:19 +0x7c
github.com/bettercap/bettercap/routing.Gateway({0x11b6cb4, 0x4}, {0xc0005ffc68, 0x5})
	/home/zzz/Téléchargements/bettercap/routing/tables.go:23 +0x6b
github.com/bettercap/bettercap/network.FindGateway(0xc000274f00)
	/home/zzz/Téléchargements/bettercap/network/net_gateway.go:10 +0x3c
github.com/bettercap/bettercap/session.(*Session).Start(0xc000039180)
	/home/zzz/Téléchargements/bettercap/session/session.go:254 +0x2ce
main.main()
	/home/zzz/Téléchargements/bettercap/main.go:49 +0x458

**Comment by johnkravicz** [comment]
Having exactly the same problem here.

Fixed using https://github.com/bettercap/bettercap/pull/1005/commits/44e24204e589721bf2f03ca803c4887a6f39646a

```
$ sudo bettercap 
bettercap v2.32.0 (built for linux amd64 with go1.18.1) [type 'help' for a list of commands]

panic: runtime error: index out of range [0] with length 0
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd06d2f]

goroutine 1 [running]:
github.com/bettercap/bettercap/session.(*Session).Close(0xc000198fc0)
	/home/user/programmes/bettercap/session/session.go:190 +0xef
panic({0x112f760, 0xc0008141b0})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
github.com/bettercap/bettercap/routing.update()
	/home/user/programmes/bettercap/routing/update_linux.go:40 +0x5dc
github.com/bettercap/bettercap/routing.Update()
	/home/user/programmes/bettercap/routing/tables.go:19 +0x7c
github.com/bettercap/bettercap/routing.Gateway({0x1192b8f, 0x4}, {0xc0009073a2, 0x9})
	/home/user/programmes/bettercap/routing/tables.go:23 +0x6b
github.com/bettercap/bettercap/network.FindGateway(0xc000233200)
	/home/user/programmes/bettercap/network/net_gateway.go:10 +0x3c
github.com/bettercap/bettercap/session.(*Session).Start(0xc000198fc0)
	/home/user/programmes/bettercap/session/session.go:254 +0x2ab
main.main()
	/home/user/programmes/bettercap/main.go:49 +0x458
```
