### ISSUE TITLE
When i use bettercap after arp.spoof.on the target lost Internet connection why?

### ISSUE THREAD

**Issue by XooooXx** [bettercap/bettercap#1003]
When i use bettercap after arp.spoof.on the target lost Internet connection why?
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by ChillVibesMushroom** [comment]
Check router settings make sure you break them down to low try resetting the target router and then try again
