### ISSUE TITLE
hstshijack not working on mac m1

### ISSUE THREAD

**Issue by pvpkiran** [bettercap/bettercap#1007]
I am using bettercap on mac m1. version v2.32.0

I am trying the hstshijack caplet. I am doing the following 

```
net.probe on
net.recon on
set arp.spoof.fullduplex true
set arp.spoof.targets <MyTargetWindowsMachine>
arp.spoof on
set net.sniff.local true
net.sniff on
```

and then I run the hstshijack caplet.

Everything is running without error. However When I try to open any website like stackoverflow.com or linkedin.com on my target machine https version of the webpage is loaded. I have all my browser data, cache cleared before testing. 

Any idea why https is loading and not http ?

**Comment by DanielSpindler** [comment]
Got the same problem on M1. And also on my Windows 10 PC.

Sadly nobody is reacting in issues etc. Same with this case. On Both Physical and VM devices  hstshijack doesnt strip the ssl
