### ISSUE TITLE
invalid flag in #cgo LDFLAGS (bug in some Go versions while compiling statically)

### ISSUE THREAD

**Issue by okiwoki** [bettercap/bettercap#101]
### Prerequisites

* [ X] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ X] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [X] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [X] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

Unable to build bettercap

### Environment

Please provide:

* OS version and architecture you are using.
Kali Linux x64
* Go version if building from sources.
1.10

### Steps to Reproduce

1. install go lang and libpcap-dev:
apt-get install golang
apt-get install libpcap-dev

2. Add GOPATH to PATH:
export GOPATH=$(go env GOPATH)
export PATH=$PATH:$GOPATH/bin

3. Grab bettercap
go get github.com/bettercap/bettercap 

**Expected behavior:** *What you expected to happen*
Get da bettercap

**Actual behavior:** *What actually happened*
Error:
go build github.com/bettercap/gopacket/pcap: invalid flag in #cgo LDFLAGS: /usr/lib/x86_64-linux-gnu/libpcap.a
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by wcrigger** [comment]
I'm getting a libpcap issue on go get -u bettercap.  I'll troubleshoot and
report in the morning if it persists.

**Comment by jreastman** [comment]
Same issue on Archlinux, 
$go get github.com/bettercap/bettercap
$gcc: error: /usr/lib/x86_64-linux-gnu/libpcap.a: No such file or directory)

**Comment by melissa200** [comment]
Same here on Android 7.1.1 through Termux with go environment set up:
$ go get github.com/bettercap/bettercap
clang-5.0: error: no such file or directory: '/usr/lib/x86_64-linux-gnu/libpcap.a'

**Comment by wcrigger** [comment]
OSX 13.3.3:
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

warren$ go get -u github.com/bettercap/bettercap
# github.com/bettercap/gopacket/pcap
clang: error: no such file or directory: '/usr/local/Cellar/libpcap/1.7.4/lib/libpcap.a'

warren$ brew search libpcap
Apple distributes libpcap with OS X, you can find it in /usr/lib.

**Comment by blshkv** [comment]
FYI, it might be something to do with go version. It compiles fine with dev-lang/go-1.9.4 (Gentoo)

**Comment by jreastman** [comment]
@blshkv 

`go version` has me at `go version go1.10 linux/amd64`

**Comment by blshkv** [comment]
well, I did not follow the ```official``` way and did not run the magic ```go get```.
Apparently, I pulled gopacket from the official google repository, as required by many bettercap/modules/*go.

So it might be something to do with the follow commit: https://github.com/bettercap/gopacket/commit/260e0ff5a473aab765aae31f22cf6e7b673bcf4b

**Comment by blshkv** [comment]
@evilsocket please try to avoid forks unnecessary and use stable releases, i.e.  v1.1.14 which google released not long time ago. You should push any changes back to them if required (static linking as a wild guess)

That last commit is a hack and the path is different in my system.

**Comment by peterhellberg** [comment]
I was able to build *bettercap* under macOS by changing `github.com/bettercap/gopacket` like so:

```diff
diff --git a/pcap/pcap.go b/pcap/pcap.go
index 2166635..5db93f9 100644
--- a/pcap/pcap.go
+++ b/pcap/pcap.go
@@ -14,7 +14,7 @@ package pcap
 #cgo freebsd LDFLAGS: -lpcap
 #cgo openbsd LDFLAGS: -lpcap
 #cgo netbsd LDFLAGS: -lpcap
-#cgo darwin LDFLAGS: /usr/local/Cellar/libpcap/1.7.4/lib/libpcap.a
+#cgo darwin LDFLAGS: /usr/local/Cellar/libpcap/1.8.1/lib/libpcap.a
 #cgo windows CFLAGS: -I C:/WpdPack/Include
 #cgo windows,386 LDFLAGS: -L C:/WpdPack/Lib -lwpcap
 #cgo windows,amd64 LDFLAGS: -L C:/WpdPack/Lib/x64 -lwpcap
```

**Comment by evs-pn** [comment]
Same here. Unable to build arch package..."libpcap.a" not found. Any major changes to bettercap/gopacket or why not use the google one?

**Comment by blshkv** [comment]
There is a proper way of doing it (which can be suggested to be pushed back to google).
See https://github.com/OpenAutomationTechnologies/openPOWERLINK_V2/issues/187
(using pcap-config in short).

**Comment by evilsocket** [comment]
This is a known bug of some Go versions, if you're using 1.9.4 downgrade to 1.9.3, I had to do the same to fix the build on Travis https://github.com/bettercap/bettercap/commit/f0e74685b26ffe3ac37c128ae7a7e67f544f40db

As for the bug -> https://github.com/golang/go/issues/23739

**Comment by blshkv** [comment]
@evilsocket so can you avoid forking gopackage ? I'm sure you don't want to maintain a well maintained package.

**Comment by evilsocket** [comment]
@blshkv I'll be happy to drop our fork if I manage to find a way to build it statically against libpcap.a instead of libpcap.so without changing `pcap/pcap.go` cgo arguments ¯\_(ツ)_/¯

Compiling with the original version will result in bettercap linking dynamically against the version of libpcap.so that is installed on the build machine, meaning if you have a different version [this will happen](https://github.com/bettercap/bettercap/issues/98). While if we compile statically (as we do after I forked gopacket and modified it), there are no runtime dependencies.

**Comment by evilsocket** [comment]
I will reopen this until we find a proper way to compile this thing, as reference.

**Comment by blshkv** [comment]
FYI: https://github.com/shadowmint/go-static-linking

**Comment by evilsocket** [comment]
@blshkv FYI: https://github.com/shadowmint/go-static-linking/blob/master/demo/src/bridge/bridge.go.in#L6

this is exactly what I'm doing in my gopacket fork

**Comment by blshkv** [comment]
sorry, not an expert, learn it together with you.
https://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo
Could it be -L option?
```
// #cgo CFLAGS: -I.
// #cgo LDFLAGS: -L. -lpcap
```

**Comment by evilsocket** [comment]
@blshkv dude, I know what option it is, which is the one I'm already using, please stop throwing random non-solutions here, ok? :)

Again, the current version builds fine on our build system and being build statically will not depend on specific `.so` files anymore.

**Comment by evs-pn** [comment]
Is it useful to open an issue in the google repos?! I think this "problem" can / should not be solved by google.

https://github.com/google/gopacket/issues/424

**Comment by evilsocket** [comment]
@evs-pn yes totally! Meanwhile I've created [this Wiki page](https://github.com/bettercap/bettercap/wiki/Known-Compilation-Issues), will close this issue, thanks to all the people involved :) <3

**Comment by blshkv** [comment]
@evilsocket the current version fails to build on my system where the libpcap.a path is different. Also, I do not want to have it compiled statically.

@evs-pn that was the main reason why evilsocket forked it, so I point finger to the upstream. Let's see if they are willing to fix it

**Comment by evilsocket** [comment]
@blshkv if you want to compile from source, I'm quite confident you know how to patch that path yourself for the time being, again, compiling statically has too many pros to drop it, and this is the only way I can do it as long as gopacket's folks do not fix their repo.

**Comment by blshkv** [comment]
yeah, I guess I'll patch it to use google's version ;-) That's the best option for me regardless of their discussion to fix that bug or not

**Comment by evilsocket** [comment]
`find . -name "*.go" | xargs sed -i "s/bettercap\/gopacket/google\/gopacket/" && make deps` :)

**Comment by evilsocket** [comment]
Another fix is to:

`export CGO_LDFLAGS_ALLOW=".*\.a"`

before compiling :)

**Comment by okiwoki** [comment]
Awesome, thanks everyone! :)
