### ISSUE TITLE
Installation fails w unrecognized import path "embed"

### ISSUE THREAD

**Issue by AGenchev** [bettercap/bettercap#1011]
Installation fails with: package embed: unrecognized import path "embed" (import path does not begin with hostname)

### Environment

OS: Ubuntu 20.04.5 LTS

The commands to install it were executed per the manual section "Linux Deploy Method Debian based (like Ubuntu)":

```
sudo apt install golang git build-essential libpcap-dev libusb-1.0-0-dev libnetfilter-queue-dev
go get -u github.com/bettercap/bettercap
```
The last command failed with:
`package embed: unrecognized import path "embed" (import path does not begin with hostname)`

### Steps to Reproduce
The installation steps above.

Expected behavior: I expected the installation to complete with  a binary in ./go/bin/bettercap

Actual behavior: I got the already cited error message.

**Comment by alegrey91** [comment]
Hi @AGenchev,
this is probably due to the **go** version that you are using to compile the binary.
You need at least go 1.16 to use the `embed` functionality.
Hope this will solve your issue.

**Comment by d3k4-k3rb3r0s** [comment]
solution doesnt help
