### ISSUE TITLE
The server is running on a different IP

### ISSUE THREAD

**Issue by MekoNix** [bettercap/bettercap#1012]
I want to use the GUI outside of my machine. But when run
`sudo bettercap -caplet http-ui`
Then it starts at 127.0.0.0
  _`http.server starting on http://127.0.0.1:80`_
In **/usr/local/share/bettercap/caplets/https-ui.cap**
I specified my local IP on the network as described here
https://www.bettercap.org/usage/webui/#remote-ui
I also changed _set api.rest.address_ and restarted the machine but everything was useless
But it's still 127.0.0.0
![image](https://user-images.githubusercontent.com/64309709/213491779-6174a331-3894-4017-aa57-8d85dd01ec39.png)

**Comment by chr0n1x** [comment]
@MekoNix did you resolve your issue? I've tried using `set ui.address 0.0.0.0` and `set ui.address <lan ip>` to try to get the http server to bind to the right device but nothing is working
