### ISSUE TITLE
When ı arp.spoof.target, target device can't load pages 

### ISSUE THREAD

**Issue by MigthyLizard** [bettercap/bettercap#1015]
I am having this isues agin and again. did anybody lived this issue. 

![index](https://user-images.githubusercontent.com/125580330/219881478-f662d019-6dd6-4b29-9ee2-c1962afc49f6.png)

**Comment by MagicAc3** [comment]
Same here. Pretty sure it means that the gateway you are spoofing has ARP spoof protection though.
