### ISSUE TITLE
ble.recon on has no response on MacOS

### ISSUE THREAD

**Issue by huanchilin** [bettercap/bettercap#1026]
* Bettercap version: bettercap v2.32.0 (built for darwin amd64 with go1.17.2)
* OS version: MacOS Monterey 12.4
* Command line argument: `ble.recon on`

### Steps to Reproduce
1. `sudo bettercap`
2. `ble.recon on`

**Expected behavior:** *What you expected to happen*
BLE recon should start, and should start scanning

**Actual behavior:** *What actually happened*
bettercap hangs with no response

**Comment by gogobd** [comment]
I have the same issue, 
bettercap v2.32.0 (built for darwin amd64 with go1.17.2)
MacOS Monterey 12.7.4
» ble.recon on
