### ISSUE TITLE
no supported devices available when ble.recon on

### ISSUE THREAD

**Issue by huanchilin** [bettercap/bettercap#1027]
*Description of the bug or feature request*
no supported devices available when ble.recon on

### Environment
* bettercap v.2.32.0 (built for linux amd64 with go1.19.8)
* OS; 5.16.0-kali7-amd64
* `ble.recon on`

### Steps to Reproduce

1. `sudo bettercap`
2. `ble.recon on`

**Expected behavior:** *What you expected to happen*
BLE turned on and started scanning

**Actual behavior:** *What actually happened*
Shows `[sys.log] [err] no supported device available`

**Comment by RanitPradhan** [comment]
Facing same issue !

**Comment by joshdumoulin** [comment]
> Follow #970 Worked for me on Ubuntu 22.04 OS

I have the same problem and this unfortunately did not work for me.

**Comment by RanitPradhan** [comment]
> I have the same problem and this unfortunately did not work for me.

Have you followed this? 
https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500

**Comment by RanitPradhan** [comment]
> > > I have the same problem and this unfortunately did not work for me.
> > 
> > 
> > Have you followed this? [#970 (comment)](https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500)
> 
> Yeah but I think it has something to do with the virtual machine.

Probably. Better to try without VM.
