### ISSUE TITLE
Installation instructions useless currently?

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [bettercap/bettercap#1032]
Won't install.

Ras pi os arm64

Honestly I've tried every single install method that exists on the internet and nothing will install bettercap. Downloads fine. But not interactive, won't run, won't open. System says it doesn't exist. 

I've been using bettercap for a while and never had this issue before?

**Comment by merwin-asm** [comment]
> Won't install.
> 
> Ras pi os arm64
> 
> Honestly I've tried every single install method that exists on the internet and nothing will install bettercap. Downloads fine. But not interactive, won't run, won't open. System says it doesn't exist.
> 
> I've been using bettercap for a while and never had this issue before?

tryed using the docker one ? .. the go one (is old ver ig)

**Comment by shaunisdom** [comment]
The go version from source is the only way to get any of the ui to work on Kali that I've found. I am not sure about raspberry, but if you're talking about the terminal and the majority of caplets, they are missing if you install it most of the ways that are posted everywhere.
