### ISSUE TITLE
Trouble Finding/Installing Bettercap on Windows 10

### ISSUE THREAD

**Issue by darias08** [bettercap/bettercap#1035]
# Prerequisites

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).  => 
* OS version and architecture you are using. => Windows 10
* Go version if building from sources. => go version go1.20.4 windows/amd64
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

I am trying to install bettercap on my windows 10, but I am not able to find any installation for windows 10. I have tried downloading the `bettercap_windows_installer_v2.31.1` but the .exe file doesn't do anything. Is there anything else I can do to fix this problem? Thank you!

**Actual behavior:** *What actually happened*
I want bettercap to be run on my Windows 10.
--

**Comment by SocksAndStuff** [comment]
This is a nightmare to set up. It amazes me that people can create such amazing projects while be utterly incapable of making them accessible.

**Comment by evilsocket** [comment]
use docker, it's not hard

**Comment by jasmohan-narula** [comment]
@evilsocket Give all the steps to use with docker?

**Comment by buffermet** [comment]
https://www.bettercap.org/installation/#using-docker

**Comment by jasmohan-narula** [comment]
> https://www.bettercap.org/installation/#using-docker


@buffermet 
Based on the docker link, provided, I've run the following commands:-
![Image](https://github.com/user-attachments/assets/27176cf8-c62f-4059-9ca5-9b1865a5d3ac)
`
docker pull bettercap/bettercap
docker run -it --privileged --net=host bettercap/bettercap -h
`
The commands listed on the website don't work.
![Image](https://github.com/user-attachments/assets/cc7a0e7c-88b9-478b-9559-da6211417c14)



> This is a nightmare to set up. It amazes me that people can create such amazing projects while be utterly incapable of making them accessible.
@SocksAndStuff I totally agree with you. They don't care about documentation or making it easier for people to use.

I had previously asked for help on installing it using 'go', they shared the same docker link which doesn't work..
https://github.com/bettercap/bettercap/issues/1178

**Comment by buffermet** [comment]
> docker run -it --privileged --net=host bettercap/bettercap -h ` The commands listed on the website don't work. ![Image](https://github.com/user-attachments/assets/cc7a0e7c-88b9-478b-9559-da6211417c14)
> 
It clearly works, judging by your screenshot.

**Comment by buffermet** [comment]
@jasmohan-narula I see you rephrased your issue but you're not providing any debug logs or anything we can work with.

We need full debug logs.

**Comment by jasmohan-narula** [comment]
@buffermet I'm running Windows 11 24H2
Docker Desktop 4.39.0 (184744)
Docker Engine - v28.0.1
with WSL 2

I ran the two commands listed, and get this output suggesting that bettercap ran successfully
![Image](https://github.com/user-attachments/assets/b4e75a35-cf6e-4e4e-b3c4-296e4c90ad0f)

But, I can see that the container stopped working after view seconds
![Image](https://github.com/user-attachments/assets/986f444d-f166-4e7f-9566-57e7178ab3cf)

I'm unable to get the Docker debug logs as I don't have a Docker Pro subscription
![Image](https://github.com/user-attachments/assets/4c5769ee-a25d-44fd-a3df-f88da3caa607)

Is there any other way to get you the information required?

**Comment by buffermet** [comment]
But you are just doing the `-h` help menu? It's supposed to just quit if you add the `-h` flag.

**Comment by jasmohan-narula** [comment]
> But you are just doing the `-h` help menu? It's supposed to just quit if you add the `-h` flag.

@buffermet 
Without the `h` flag in the command, it works. 
![Image](https://github.com/user-attachments/assets/8a1be7ea-8514-4ae6-a251-43d66ce6bcd3)

I can get it to run in the background with `-d` flag. But there are no clear instructions on the website to get the Web-UI working on the website.

There is a discussion in an issue from 5 years back, but no clear instructions or documentation.
https://github.com/bettercap/bettercap/issues/590

**Comment by buffermet** [comment]
Please read the manual... It clearly says what you have to do and you are simulating Linux with docker...

https://www.bettercap.org/usage/webui/

**Comment by jasmohan-narula** [comment]
> Please read the manual... It clearly says what you have to do and you are simulating Linux with docker...
> 
> https://www.bettercap.org/usage/webui/

This is the only manual - which is barely even 2 lines:-
![Image](https://github.com/user-attachments/assets/91ae9919-6925-4afa-a1f1-54aa86ed4e18)

**Comment by jasmohan-narula** [comment]
> Please read the manual... It clearly says what you have to do and you are simulating Linux with docker...
> 
> https://www.bettercap.org/usage/webui/

@buffermet 
And the reason I'm simulating Linux with docker is because when I tried installing bettercap natively on Windows with go; you closed my issue and instructed me to use Docker.
https://github.com/bettercap/bettercap/issues/1178

So what should I do?

**Comment by buffermet** [comment]
Dude we can go back and forth all day but if you don't just do what the manual says and show us exactly what output you see I cannot help.

Just do what the manual says. This whole time it seems everything is working just fine...

**Comment by buffermet** [comment]
> > Dude we can go back and forth all day but if you don't just do what the manual says and show us exactly what output you see I cannot help.
> > Just do what the manual says. This whole time it seems everything is working just fine...
> 
> According to manual, the eval ui flag is set to on `sudo bettercap -eval "ui on"`
> 
> I am unable to run the above Linux command on Windows. So, I'm passing it in the docker command:- `docker run -it --privileged --net=host bettercap/bettercap -eval "ui on"`
> 
> This is the output I'm getting- ![Image](https://github.com/user-attachments/assets/ee5b2720-33b2-4ff9-81fe-cae2820abea7)
> 
> According to the output, the Web UI was successfully started on localhost:- `http://127.0.0.1:8080/`
> 
> But I'm unable to access the Web-UI from the host windows machine- ![Image](https://github.com/user-attachments/assets/8869b316-f800-49cf-acc0-7cb00343de5c)
> 
> If I check with curl command inside the docker container, I can see that the UI is giving back a response. ![Image](https://github.com/user-attachments/assets/9422012a-a630-48ae-ac59-db54804d6d7a)
> 
> [@buffermet](https://github.com/buffermet) Can you share any other manual or commands which can help me in getting the WebUI working on Windows 11 with Docker?

Ok so the UI is working but you can't access it from Windows because you're running it in a dockerized container. You need to configure your network settings differently, there should be an issue explaining how to do this.

**Comment by jasmohan-narula** [comment]
> Ok so the UI is working but you can't access it from Windows because you're running it in a dockerized container. You need to configure your network settings differently, there should be an issue explaining how to do this.

@buffermet If you can help narrow down the issue on GitHub and provide some steps, that will be great. I'll keep looking from my side as well.

Since I'm starting from a fresh installation of Windows 11 and Docker, the final steps could be documented.

**Comment by buffermet** [comment]
Follow baiconwaifu's instructions: https://github.com/bettercap/bettercap/issues/590#issuecomment-548161175

**Comment by jasmohan-narula** [comment]
> Follow baconwaifu's instructions: [#590 (comment)](https://github.com/bettercap/bettercap/issues/590#issuecomment-548161175)

@buffermet I've mentioned this before
> 
> There is a discussion in an issue from 5 years back, but no clear instructions or documentation. [#590](https://github.com/bettercap/bettercap/issues/590)
> 
> The are instructions are only for Linux. https://www.bettercap.org/usage/webui/

They did not solve the issue for Windows. They only solved it for Linux/MacOS

**Comment by jasmohan-narula** [comment]
When I tried using port forwarding/publishing ports, I'm still unable to access the Web-UI on Windows
`docker run -it --privileged -p 8080:8080 -p 8081:8081 bettercap/bettercap -eval "set api.rest.username admin; set api.rest.password admin; ui on"`

![Image](https://github.com/user-attachments/assets/fe4b0273-9f8f-4b5a-84eb-0499ce3d6ef6)

**Comment by buffermet** [comment]
This is a Windows/docker issue, not a bettercap issue. I suggest you use Linux.

**Comment by jasmohan-narula** [comment]
@buffermet As far as I'm understanding, bettercap does not work with Windows. As the native installation with go is not happening and Docker is unable to setup network in Windows as Docker does not have direct access to network interfaces.

**Comment by buffermet** [comment]
You can also install Linux on Windows. You shouldn't need docker.
