### ISSUE TITLE
Odd problem

### ISSUE THREAD

**Issue by almas1206** [bettercap/bettercap#1037]
I have been attempting to install and run Bettercap on Ubuntu within the Windows 10 environment. The initial setup appeared to proceed without any issues, but I encountered a problem when I received the following error message:

![image](https://github.com/bettercap/bettercap/assets/136647289/a75c281d-3fa2-4b69-a988-8bdcbdd329b8)

Despite my efforts, I have been unable to find a solution for this issue by searching online. I would greatly appreciate any assistance or guidance that anyone can provide to help me resolve this problem

**Comment by shaunisdom** [comment]
The only thing that has worked, especially if all caplets and modules are to work correctly and install with the http-ui/https-ui accessible and not broken upon login with only a blank screen and two headers for what would be menu options is to build it with fetch from the go language.

**Comment by emreakdag-ifbb** [comment]
Hello,
I am using kali in Virtual Machine. Bettercap sniffs the computer without any problems, but it does not sniff when you enter the Android phone IP address.
dns 8.8.8.8 > Computer Name: wpad.local is Non-Existent Domain
he is writing. How to fix it. Please help me.
