### ISSUE TITLE
How to write script to call ble.enum on every BLE address?

### ISSUE THREAD

**Issue by jsmif** [bettercap/bettercap#1038]
### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).:  bettercap v2.31.1 (built for linux arm with go1.16.2) (latest available for ARM)
* OS version and architecture you are using.: Raspbian 10 Bullseye
* Command line arguments you are using.: sudo ./bettercap -script ./ble_scan.js

### Steps to Reproduce

I have the following javascript in ble_scan.js as my starting point:

```
run('ble.recon on');

onEvent('ble.device.new', function(event) {
  // Introspection
//  var fieldNames1 = Object.keys(event);
//  console.log('Available Fields1:', fieldNames1);
  //event contains: tag,time,data

  var data = event.data;
  // Introspection
//  var fieldNames2 = Object.keys(data);
//  console.log('Available Fields:', fieldNames2);
 //data contains: services,last_seen,name,connectable,flags,mac,alias,vendor,rssi

  console.log('data.mac:', data.mac);
  console.log('data.vendor:', data.vendor);
  console.log('data.connectable:', data.connectable);

});
```

What I want to do is effectively call "ble.enum" on every data.mac value. But I'm not really a javascript person (but ChatGPT is ;)) and I don't see a mapping of go functions to javascript functions that I can point ChatGPT at in order to try and get it to continue the process.

I can see [here]() that I probably need to call some connect() function (how, is what I'm asking), and then listen for events like ble.device.connected or ble.connection.timeout.

And then I need to call some sort of GATT enumeration function (how, is what I'm asking), and then listen for ble.device.service.discovered and ble.device.characteristic.discovered.

Though I am wondering whether bettercap actually supports reading characteristics too (since there's no CLI way to do it AFAICT)?

**Expected behavior:** *What you expected to happen*

I would be able to get ChatGPT to figure out how to write the script for me.

**Actual behavior:** *What actually happened*

I have to post a ticket asking how to write BLE scripts, since there is no documentation anywhere :-/

Thank you in advance!

**Comment by shaunisdom** [comment]
I have been a little confused as to how to set up the iface for ble... let alone scripts. Unfortunately it is usually a painfully obvious lapse in knowledge that somehow few mention. Why building bettercap with go language install instructions are not clear in the first place breaking most of the caplets and ui is strange to me when so many people use kali.

**Comment by evilsocket** [comment]
@shaunisdom the problems you mentioned all depends on how Kali badly packaged bettercap, not on bettercap itself.
