### ISSUE TITLE
Web Ui

### ISSUE THREAD

**Issue by bleedingedge121** [bettercap/bettercap#1042]
I was just trying the Web Ui and after setting it up on the latest version, following the steps listed on the website under usage>Web Ui but after logging (http-ui.cap) in nothing shows up even after waiting for few min it just becomes blank

**Comment by gonzalu** [comment]
Same here :( Looking everywhere and none of the proposed solutions work

**Comment by 00xBAD** [comment]
same here, 404 not found

**Comment by keldnorman** [comment]
I made an install/compile helper script that will make it work using the latest version: 

https://github.com/keldnorman/bettercap2.32.0
