### ISSUE TITLE
Gpg signatures instead of sha256

### ISSUE THREAD

**Issue by Ahmed3457** [bettercap/bettercap#1046]
# GPG signature > sha256
i think it's better to have [**GPG**](https://www.gnupg.org/) signatures packed in the .zip containing the binary and having the public key in the [readme](readme.md), since it's more reliable to use [**GPG**](https://www.gnupg.org/) signatures over sha256, this ensures that the file hasn't changed in any kind of way.

**Comment by axelsimon** [comment]
GPG signatures are essentially never checked and GPG keys have their own set of issues (how do you properly confirm public key X belongs to person Y?).

It would make more sense in this day an age to start signing with something like [Sigstore](https://sigstore.dev).
