### ISSUE TITLE
 could not find spoof targets MacOS

### ISSUE THREAD

**Issue by confusionhill** [bettercap/bettercap#1047]
*Description of the bug or feature request*

### Environment
- MacOS m1 Ventura 13.2.1
- bettercap v2.32.0 (built for darwin arm64 with go1.19.4)

Hello, I wanted to intercept my tcp connection (log it) as I am currently on a a research for my university final project. 
I wanted to try to log all of my local pc tcp connection.

Here are the list of command that I have performed
- sudo sysctl -w net.inet.ip.forwarding=1
- net.probe on
- set net.sniff.local true
- set arp.spoof.targets {my IP address}
- arp.spoof on

and the result are not what I expected :

```
 » [18:48:51] [sys.log] [war] arp.spoof could not find spoof targets
» [18:48:51] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 targets.
» [18:48:52] [sys.log] [war] arp.spoof could not find spoof targets
```

what did I do wrong to be exact? thank you

**Comment by satheshshiva** [comment]
facing the same issue. +1

**Comment by apertureless** [comment]
Why are you trying to arp.spoof yourself? This does not make much sense.
If you have two workstations `192.168.0.11` and `192.168.0.22` and you are running bettercap on the `192.168.0.11` machine you can set the target to `192.168.0.22` to intercept the traffic between `192.168.0.22` and the router. 

If you want to see your local tcp traffic you can just tcpdump / wireshark / net.sniff it without arp poisining.
