### ISSUE TITLE
Installation issue with latest version (missing libpcap.a file -- possibly from gopacket/pcap)

### ISSUE THREAD

**Issue by naltun** [bettercap/bettercap#105]
### Description

```
$ go get github.com/bettercap/bettercap
# github.com/bettercap/gopacket/pcap
gcc: error: /usr/lib/x86_64-linux-gnu/libpcap.a: No such file or directory
$ echo $?
2
```
This is the devel library, correct? I don't believe my environment changed significantly since I downloaded the latest version from yesterday. I suppose this file wasn't specifically needed until a recent commit?

It seems that the problem arises with `github.com/bettercap/gopacket/pcap`.

### Environment
Antergos, x86_64
go version go1.10 linux/amd64
Command line arguments you are using 

### Steps to Reproduce

`go get github.com/bettercap/bettercap`

**Expected behavior:** *What you expected to happen*

Successful installation
**Actual behavior:** *What actually happened*

Failed installation

--

**Comment by naltun** [comment]
_Preemptively saying_, if a recent commit requires `libpcap.a` to work, we should add that to the documentation in the `How to Install` section.

**Comment by evilsocket** [comment]
Check conversation here https://github.com/bettercap/bettercap/issues/101
