### ISSUE TITLE
Where is precompiled binaries for v2.32.0

### ISSUE THREAD

**Issue by Drjacky** [bettercap/bettercap#1053]
There are no pre-compiled binaries for version 2.32.0: https://github.com/bettercap/bettercap/releases/tag/v2.32.0

**Comment by zygithub-single** [comment]
You can use brew install bettercap on macbook silicon (like m1) terminal to install bettercap.

**Comment by Drjacky** [comment]
https://formulae.brew.sh/formula/bettercap

**Comment by p1r473** [comment]
@zygithub-single what about us Linux (Debian) Pi users?
