### ISSUE TITLE
Docker build fails - libpcap.a error

### ISSUE THREAD

**Issue by Tin-Voyager** [bettercap/bettercap#106]
### Prerequisites

* [ x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already

I downloaded official 2.0.0 release and latest from GitHub. 

Docker image build -t bettercap:latest .

The build process gets to ‘make deps’ and fails with a gcc error relating to libpcap.a. 

I’ve seen other posts regarding the libpcap.a but lack the understanding of how to fix this. 

### Environment

Please provide:

* Ubuntu 16.04.3 x64
* docker ce 17.12
* Using your dockerfile 

### Steps to Reproduce

1. Download bettercap source
2. Run: docker build image -t bettercap:latest .

**Expected behavior:** *What you expected to happen*

I get a docker image which has bettercap installed. 

**Actual behavior:** *What actually happened*

Build image process failed. 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by JacobReynolds** [comment]
I'm seeing the same, here's the failed output.

```
Step 9/12 : RUN make deps
 ---> Running in bb3e5bb504fd
# github.com/bettercap/gopacket/pcap
gcc: error: /usr/lib/x86_64-linux-gnu/libpcap.a: No such file or directory
make: *** [Makefile:28: deps] Error 2
The command '/bin/sh -c make deps' returned a non-zero code: 2
```

It looks like alpine linux dumps libpcap.a into `/usr/lib/` not `/usr/lib/x86_64-linux-gnu/`. Potential solution is updating the file path here https://github.com/bettercap/gopacket/blob/master/pcap/pcap.go#L14. 

But there might be other reasoning for why that file path is set.

**Comment by evilsocket** [comment]
Updating that path is not a solution as it would break the build elsewhere.

**Comment by Tin-Voyager** [comment]
@JacobReynolds - thank you filling in the missing details.

**Comment by evilsocket** [comment]
Fix is on the way

**Comment by Tin-Voyager** [comment]
Thank you.

**Comment by evilsocket** [comment]
(the noob me is now trying to understand how to push the updated Docker container to the hub .... lol)

**Comment by evilsocket** [comment]
Done ^_^
