### ISSUE TITLE
Can't use "ble.recon on" on mac os

### ISSUE THREAD

**Issue by ttzuesf** [bettercap/bettercap#1065]
When I use `ble.recon on` to find Bluetooth, the `ble.recon on` enters the loop.

<img width="639" alt="Screenshot 2023-12-25 at 12 35 40 AM" src="https://github.com/bettercap/bettercap/assets/19250401/50561f04-4ead-4757-aae6-b5ae0f9d67eb">

**Comment by hmeine** [comment]
Duplicate (see #74, #1026, …)
