### ISSUE TITLE
Please update the URL to github.com/bettercap/bettercap/v2 for Golang servers to pick it up

### ISSUE THREAD

**Issue by yurivict** [bettercap/bettercap#1066]
### Description

For Golang servers to pick up the project its URL needs to have a suffix /vN, where N is a major part of the version.

Could you please update the URL ?

Thanks,
Yuri

**Comment by evilsocket** [comment]
what do you mean with golang servers?

**Comment by evilsocket** [comment]
Duplicate https://github.com/bettercap/bettercap/issues/727
