### ISSUE TITLE
bash: /usr/bin/bettercap: No such file or directory

### ISSUE THREAD

**Issue by TheTommylongIsHeree** [bettercap/bettercap#1069]
# Prerequisites

### Description
So I can't get Pwnagotchi to work on my Raspberry Pi Zero W 2 so I tried the manual install instead.
I am stuck on this error message (-bash: /usr/bin/bettercap: No such file or directory)
I do tried so many things like running it again, as root, rebooting but nothing have worked out for me.

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). (2.31.0 in the releases link because I can't really run bettercap)
* OS version and architecture you are using. 
(cat /etc/os-release:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
**installed** Raspberry Pi OS (64 bit Legacy Lite))

* Go version if building from sources. (not building from sources)
* Command line arguments you are using. (no arguments at all)
* Caplet code you are using or the interactive session commands. 
(code and commands on Pwnagotchi tutorial site
wget https://github.com/bettercap/bettercap/releases/download/v2.31.0/bettercap_linux_armhf_v2.31.0.zip
unzip bettercap_linux_armhf_v2.31.0.zip
sudo mv bettercap /usr/bin/
try to run bettercap {errors}
)

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ). (can't run the command)

### Steps to Reproduce

1. Install Raspberry Pi OS Legacy 64bit Lite
2. Run the above commands
3. Run bettercap and get stuck there

**Expected behavior:** *the command need to run with at least no errors or some output*

**Actual behavior:** *can't run the command*

--

**Comment by dmilosevic** [comment]
Check if your unzipped bettercap file was actually moved to /usr/bin/ (like intended) by running `ls /usr/bin/bettercap`
If you see it there, it's possible that it's missing execute permissions. Add them with `sudo chmod +x /usr/bin/bettercap` and try running the program again.
