### ISSUE TITLE
Add automated builds on Docker Hub

### ISSUE THREAD

**Issue by JacobReynolds** [bettercap/bettercap#107]
### Description

**Feature request:**
Add automated build integration with Docker Hub. I was having trouble getting the tcp proxy to work with the current Docker image and realized that's because the image was created before the tcp proxy functionality was implemented.

Relevant documentation: https://docs.docker.com/docker-hub/builds/

### Environment

* https://hub.docker.com/r/bettercap/bettercap

### Steps to Reproduce

N/A

**Expected behavior:** 
New commits to Github will trigger an automated update of the docker images on https://hub.docker.com/r/bettercap/bettercap.

**Actual behavior:** 
New commits to Github do no update the docker image.

**Comment by evilsocket** [comment]
Anyone who wants to send a PR for this is welcome, I personally don't know Docker enough.

**Comment by JacobReynolds** [comment]
I could add this for you, but it requires access to the account on https://hub.docker.com. The setup itself should be just linking [Github <-> Docker Hub](https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service) and telling Docker Hub to [build on every deploy](https://docs.docker.com/docker-hub/builds/#create-an-automated-build). Not a priority by any means though.

**Comment by evilsocket** [comment]
oh if that doesn't require any change to the Dockerfile I can do it, let me see :D

**Comment by evilsocket** [comment]
I think I did it ... https://hub.docker.com/r/bettercap/dev/

**Comment by JacobReynolds** [comment]
That did it, thanks so much!

**Comment by alexmozzhakov** [comment]
@evilsocket I see your HTML, eww
