### ISSUE TITLE
net.show doesn't show all devices

### ISSUE THREAD

**Issue by masihbeta** [bettercap/bettercap#1086]
i am runnig kali linux with vmware and when i use bettercap's net.show it only shows eth0 and gateway and it doesnt show the devices connected to the network, i did try turning net.probe on and i changed the vm settings to bridging but it still doesnt work,
any ideas?

**Comment by VirusFriendly** [comment]
Check to make sure the network is setup for Promiscious Mode
https://communities.vmware.com/t5/VMware-Workstation-Pro/Allow-promiscuous-mode-vmware-Allow-promiscuousModePolicy/td-p/2296421
