### ISSUE TITLE
wifi.* interface monitoring channel isn't changing on macOS 

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#109]
From #61 looks like I haven't tested it good enough. Not channel hopping nor `set wifi.recon.channel` seem to actually do it. My interface is stuck on monitoring my wifi channel if connected. I've tried disconnecting from wifi, but I only added wifi from channel 1. `set wifi.recon.channel` doesn't work not even while disconnected.

**Comment by mlinton** [comment]
I can confirm this behaviour on 2016 MBP.

**Comment by evilsocket** [comment]
Fixed! For some reason `--channel N` doesn't work but `-cN` does ¯\\\_(ツ)\_/¯

<img width="1000" alt="schermata 2018-03-06 alle 12 08 29" src="https://user-images.githubusercontent.com/86922/37029425-b5f8daa2-2137-11e8-943f-45225dc2fd37.png">

**Comment by alexmozzhakov** [comment]
```
Macbook:~ alex$ sudo airport en1 -cN 2
channel: 1
Macbook:~ alex$ sudo airport en1 -cN 3
channel: 1
Macbook:~ alex$ sudo airport en1 -cN 4
channel: 1
```

Are you sure? It still doesn't work for me
