### ISSUE TITLE
Channel hopping/setting no longer works on macOS Sonoma 14.4.1+

### ISSUE THREAD

**Issue by jsonpoindexter** [bettercap/bettercap#1090]
Channel hopping/setting no longer works on macOS Sonoma 14.4.1+ due to `airport` being deprecated

### Environment
* Bettercap version: v2.32.0 (built for darwin arm64 with go1.21.1)
* OS version and architecture: macOS Sonoma 14.4.1 / ARM64

### Steps to Reproduce
NOTE: assumes the last channel set was anything other than the channel used in this example (6) as this is to show that channels cannot be changed.

1. Start `bettercap` with proper interface
```bash
sudo ./bettercap -iface en0 
```

2. Set the wireless channel to 6
```bash
wifi.recon.channel 6
```

3. Start wireless recon
```bash
wifi.recon on
```

**Expected behavior:** Channel should be set to '6'

**Actual behavior:** The channel is not changed to '6' and is still on the previous channel (in my example '1')
![image](https://github.com/bettercap/bettercap/assets/5003899/c58c2333-06fc-4736-a3a1-f96eb058eb1f)

### Analysis 
[net_darwin.go](https://github.com/bettercap/bettercap/blob/924ff5753dd8eaca14018be3ab8e3362057e4b67/network/net_darwin.go#L14) for macOS systems relies on the use of `airport` command to [set the interface's channel](https://github.com/bettercap/bettercap/blob/924ff5753dd8eaca14018be3ab8e3362057e4b67/network/net_darwin.go#L23).

As of macOS Sonoma 14.4.1  the `airport` command has been deprecated, is none-functional, and will only return a warning when attempting to run any commands.

The command used to set an interface's channel via [this line](https://github.com/bettercap/bettercap/blob/924ff5753dd8eaca14018be3ab8e3362057e4b67/network/net_darwin.go#L30)
Example:
```
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -c6
```
will now not change the interface's channel and will instead only return the warning message:
```
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
```

**Comment by sofakng** [comment]
macOS is quite frustrating.

Are there any solutions?

**Comment by sudo-nano** [comment]
I've reproduced this bug on an M1 Macbook Air, MacOS Sonoma 14.4.

**Comment by VladislavGatsenko** [comment]
I was looking for a solution to a different problem, but maybe this will help with a another solution. To fix airport deprecated status you can try this. Just execute in the console:

system_profiler SPAirPortDataType

**Comment by evilsocket** [comment]
work in progress working on it https://github.com/bettercap/bettercap/pull/1100
