### ISSUE TITLE
enabling forwarding is not showing after arp.spoof on, dns.spoof on commands

### ISSUE THREAD

**Issue by vikky1701** [bettercap/bettercap#1093]
*Description of the bug or feature request*
after writing arp.spoof on or dns.spoof on enabling forwarding is not showing up

### Environment
ubuntu dual boot with windows

Please provide:

* Bettercap version
*  ( v2.32.0 ).
* OS version and architecture you are using.
* ubuntu 22.04.4 LTS x86_64 amd 64
* Go version if building from sources.
* go1.22.1 linux amd64
* Command line arguments you are using.
* arp.spoof on,dns.spoof on
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. net.probe on
2. net.show
3. set arp.spoof.targets (victim's IP)
4. arp.spoof on
5. 

**Expected behavior:** *What you expected to happen*
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets[00:44:54] [endpoint.lost] endpoint 192.168.29.5 fa:6a:8b:58:9e:87 lost.
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets[00:44:56] [endpoint.lost] endpoint 192.168.29.174 b4:8c:9d:12:f8:6b lost.
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets 192.168.29.12
192.168.29.0/24 > 192.168.29.142  » arp.spoof on
192.168.29.0/24 > 192.168.29.142  » [00:45:30] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 targets.
                                                                             [sys.log][inf] enabling forwarding

**Actual behavior:** *What actually happened*
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets[00:44:54] [endpoint.lost] endpoint 192.168.29.5 fa:6a:8b:58:9e:87 lost.
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets[00:44:56] [endpoint.lost] endpoint 192.168.29.174 b4:8c:9d:12:f8:6b lost.
192.168.29.0/24 > 192.168.29.142  » set arp.spoof.targets 192.168.29.12
192.168.29.0/24 > 192.168.29.142  » arp.spoof on
192.168.29.0/24 > 192.168.29.142  » [00:45:30] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 target

**Comment by evilsocket** [comment]
that happens when bettercap detects that forwarding is already enabled in your system
