### ISSUE TITLE
Not working on kali nethunter like on kali on laptop

### ISSUE THREAD

**Issue by dr1408** [bettercap/bettercap#1094]
### Environment

Please provide:

* Bettercap version you are using ( 2.32.0 ).
* OS version and architecture you are using :kali nethunter 2024.1
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. Net.probe on 2.net.show 3.set arp.spoof.targets ip, gateway ip 4.arp.spoof on 5.net.sniff2. 

**Expected behavior: it works like kali on my laptob but there is 2 major difference in kali on vmware  1-it says gateway monitor started .. nethunter= could not find mac for 
2-in kali on vmware it says enabling forwarding , while on nethunter no message like this
**Actual behavior:** arp spoof and net sniff not working and somtimes it stop the internet on thr target phone*

![010ABE10-25D7-4E3D-B964-6B29374D0B0A](https://github.com/bettercap/bettercap/assets/39735654/d56b5160-75fe-4551-8542-449cfac654ef)

![B649050B-572D-4B28-A223-1BBE9E558485](https://github.com/bettercap/bettercap/assets/39735654/ec2340d6-4e0d-48a8-b3ad-36c501c23b07)

**Comment by hkmulderhk** [comment]
Hello dr1408, I have the same problem. How do you solve it?
Thanks.
