### ISSUE TITLE
bettercap runs itself as root in the background. explain.

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [bettercap/bettercap#1101]
I dont have a bug and dont care about the "official form" you can close this if you want. I just want a direct answer for why bettercap consistently spawns in the background as root and does random shit it shouldnt be doing?

Before all the silly questions:

Various machines, various OS, fresh installs, blah blah blah. Bettercap runs itself as root on whatever system you install it on. why?

**Comment by evilsocket** [comment]
What the actual f are you talking about? bettercap runs with whatever privilege YOU run it. if you find it running, either someone executed it, or it was installed as a system service ... how the hell am i supposed to know?

Some bettercap's features require root privileges (instrumenting the system firewall for instance), what is your problem?

**Comment by sktt** [comment]
I think he refers to the systemd bettercap.service that gets installed and enabled by for example the debian package. it will run
```/usr/bin/bettercap -no-colors -eval "set events.stream.output /var/log/bettercap.log; api.rest on"```

It seems strange that it does. It can be removed by doing 
```systemctl disable bettercap.service```

**Comment by evilsocket** [comment]
The .service was never meant to be installed, some distros decided to but nowhere in the documentation it is said that a systemd service is required.
