### ISSUE TITLE
Bettercap scannig other ips 

### ISSUE THREAD

**Issue by Silenthack3r** [bettercap/bettercap#1103]
bettercap is sniffing other ips other than i specified and not sniffing the ip that i specified.
![Screenshot_2024-06-15_10_55_14](https://github.com/bettercap/bettercap/assets/108166146/82775366-ecd7-450b-a14a-50644e12544b)

**Comment by evilsocket** [comment]
mDNS = multicast DNS, go check how it works, it's using broadcast ips
