### ISSUE TITLE
error while running caplet http-ui: caplet http-ui.cap not found

### ISSUE THREAD

**Issue by thaythayt0722** [bettercap/bettercap#1104]
#sudo bettercap -caplet http-ui
\\bettercap v2.32.0 (built for linux amd64 with go1.19.8) [type 'help' for a list of commands]

10.0.2.0/24 > 10.0.2.15  » \[17:59:57] [sys.log] [inf] gateway monitor started ...
10.0.2.0/24 > 10.0.2.15  » \[17:59:57] [sys.log] [err] error while running caplet http-ui: caplet http-ui.cap not found
10.0.2.0/24 > 10.0.2.15  »

**Comment by thaythayt0722** [comment]
i use parrot os amd64

**Comment by thaythayt0722** [comment]
idk of this means anyting any.proxy > not running
       api.rest > not running
      arp.spoof > not running
             c2 > not running
        caplets > not running
    dhcp6.spoof > not running
      dns.spoof > not running
  events.stream > running
            hid > not running
     http.proxy > not running
    http.server > not running
    https.proxy > not running
   https.server > not running
    mac.changer > not running
    mdns.server > not running
   mysql.server > not running
      ndp.spoof > not running
      net.probe > not running
      net.recon > not running
      net.sniff > not running
   packet.proxy > not running
       syn.scan > not running
      tcp.proxy > not running
         ticker > not running
             ui > not running
         update > not running
           wifi > not running
            wol > not running

**Comment by MrAyoub909** [comment]
Hi this worked for me 
`sudo bettercap -eval "caplets.update; ui.update; q"`

**Comment by amanrathi2005** [comment]
> sudo bettercap -eval "caplets.update; ui.update; q"

worked for me also thanks

**Comment by evilsocket** [comment]
everyone having problems with the UI, check this out https://www.evilsocket.net/2024/09/13/Introducing-bettercap-2-4-0-CAN-bus-hacking-WiFi-bruteforcing-and-builtin-web-UI/
