### ISSUE TITLE
Build fails with Go 1.23

### ISSUE THREAD

**Issue by stefanb** [bettercap/bettercap#1106]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ): 2.32.0
* OS version and architecture you are using: Ubuntu Linux/amd64, MacOS/arm64
* Go version if building from sources: 1.23rc1 (works with 1.22)
* Command line ~arguments~ you are using: `make`
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. Install Go 1.23 rc1 (per [instructions](https://groups.google.com/g/golang-announce/c/8ciOP5ve_CM))
2. get the source code
3. Try building with Go 1.23 (adjust Makefile to use the new Go binary)

**Expected behavior:**

Build to succeed.

**Actual behavior:** 
Build fails with
````
  # github.com/bettercap/bettercap
  link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
  make: *** [build] Error 1
````

It seems that in referenced package `golang.org/x/net/internal/socket` there is a now forbidden `//go:linkname` reference to `syscall.recvmsg`.

See related:
* Build attempt https://github.com/Homebrew/homebrew-core/pull/175310
* Formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/b/bettercap.rb
* Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* Go 1.23 release notes: https://tip.golang.org/doc/go1.23#linker
* Proposal: https://github.com/golang/go/issues/67401

Please tag a release after this is resolved and tested, preferably before Go 1.23 is released in August.

**Comment by stefanb** [comment]
Build is still failing with Go 1.23 rc2

**Comment by evilsocket** [comment]
@stefanb  see my comment on the PR
