### ISSUE TITLE
unable to finish compilation - Error 1

### ISSUE THREAD

**Issue by stanyjol** [bettercap/bettercap#1108]
I'm unable to finish compilation of bettercap on android device LineageOS 21 (xiaomi redmi5) in Termux.

**Compilation finish with:** make: *** [Makefile:9: build] Error 1

*Packages installed and requirements seems fulfilled:*
golang is already the newest version (3:1.22.3).
git is already the newest version (2.45.2).
libpcap is already the newest version (1.10.4).
libusb is already the newest version (1.0.27).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
~/bettercap $ uname -a; go version
Linux localhost 4.19.315-perf-g1fa3f38d0b16 #1 SMP PREEMPT Thu Jun 27 09:02:03 UTC 2024 aarch64 Android
go version go1.22.3 android/arm64
~/bettercap $ go env GOPATH GOROOT && echo $PATH && sudo mount | grep ' / '
/data/data/com.termux/files/home/go
/data/data/com.termux/files/usr/lib/go
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/lib/go/bin:/data/data/com.termux/files/home/go/bin
/dev/block/dm-0 on / type ext4 (rw,seclabel,relatime)
~/bettercap $ ls -ld /home/builder/.termux-build/_cache/18-arm-21-v2/bin/ /home/builder/.termux-build/_cache/18-arm-21-v2/bin/arm-linux-androideabi-pkg-config /data/data/com.termux/files/home/go/bin
drwx------ 2 u0_a190 u0_a190 3452 Jul  3 13:59 /data/data/com.termux/files/home/go/bin
drwxr-xr-x 2 root    root    4096 Jul  3 10:54 /home/builder/.termux-build/_cache/18-arm-21-v2/bin/
lrwxrwxrwx 1 root    root      46 Jul  3 10:54 /home/builder/.termux-build/_cache/18-arm-21-v2/bin/arm-linux-androideabi-pkg-config -> /data/data/com.termux/files/usr/bin/pkg-config
~/bettercap $ pwd
/data/data/com.termux/files/home/bettercap
~/bettercap $ go get -u github.com/bettercap/bettercap
~/bettercap $ make build
go build -o bettercap .
#github.com/chifflier/nfqueue-go/nfqueue
#[pkg-config --cflags  -- libnetfilter_queue]
Package libnetfilter_queue was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnetfilter_queue.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnetfilter_queue' found
make: *** [Makefile:9: build] Error 1
~/bettercap $

**Comment by evilsocket** [comment]
install libnetfilter_queue as per documentation
