### ISSUE TITLE
http-ui not working, 404 page not found

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [bettercap/bettercap#1110]
*Description of the bug or feature request*

### Environment

Please provide:

* bettercap version
bettercap v2.32.0 (built for linux amd64 with go1.22.5)
* os
endeavourOS latest release, x86_64
* command
sudo bettercap -caplet http-ui
* Caplet code you are using or the interactive session commands.
default caplets, no commands
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

```
⮚ sudo bettercap -caplet http-ui -debug
bettercap v2.32.0 (built for linux amd64 with go1.22.5) [type 'help' for a list of commands]

```
[18:19:56] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
[18:19:56] [sys.log] [dbg] creating capture for 'wlan0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
[18:19:56] [sys.log] [dbg] gateway is 192.168.181.135[3e:66:ed:68:0a:ad]
[18:19:56] [sys.log] [inf] gateway monitor started ...
[18:19:56] [sys.log] [dbg] [gw] ipv4=192.168.181.135(3e:66:ed:68:0a:ad) ipv6=()
[18:19:56] [mod.started] events.stream
[18:19:56] [mod.started] api.rest
192.168.181.0/24 > 192.168.181.228  » [18:19:56] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.181.0/24 > 192.168.181.228  » [18:19:56] [mod.started] http.server
192.168.181.0/24 > 192.168.181.228  » [18:19:56] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.181.0/24 > 192.168.181.228  » [18:20:01] [sys.log] [dbg] gateway is 192.168.181.135[3e:66:ed:68:0a:ad]
192.168.181.0/24 > 192.168.181.228  » [18:20:01] [sys.log] [dbg] [gw] ipv4=192.168.181.135(3e:66:ed:68:0a:ad) ipv6=()
192.168.181.0/24 > 192.168.181.228  » [18:20:05] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/
192.168.181.0/24 > 192.168.181.228  » [18:20:06] [sys.log] [dbg] gateway is 192.168.181.135[3e:66:ed:68:0a:ad]
192.168.181.0/24 > 192.168.181.228  » [18:20:06] [sys.log] [dbg] [gw] ipv4=192.168.181.135(3e:66:ed:68:0a:ad) ipv6=()
192.168.181.0/24 > 192.168.181.228  » [18:20:11] [sys.log] [dbg] gateway is 192.168.181.135[3e:66:ed:68:0a:ad]
192.168.181.0/24 > 192.168.181.228  » [18:20:11] [sys.log] [dbg] [gw] ipv4=192.168.181.135(3e:66:ed:68:0a:ad) ipv6=()
192.168.181.0/24 > 192.168.181.228  » [18:20:16] [sys.log] [dbg] gateway is 192.168.181.135[3e:66:ed:68:0a:ad]
192.168.181.0/24 > 192.168.181.228  » [18:20:16] [sys.log] [dbg] [gw] ipv4=192.168.181.135(3e:66:ed:68:0a:ad) ipv6=()
192.168.181.0/24 > 192.168.181.228  » ^C
Are you sure you want to quit this session? y/n y
[18:20:18] [mod.stopped] api.rest
```

```

### Steps to Reproduce
just launch the webUI and open the browser

**Expected behavior:** for the web UI to work

**Actual behavior:** web UI not working, only returning the error 404 page not found

**Comment by SteinGaming** [comment]
Hi, I'm on Arch Linux and I fixed it by changing `set http.server.path /usr/local/share/bettercap/ui` to `set http.server.path /usr/share/bettercap/ui` in `/usr/share/bettercap/caplets/http-ui.cap`.
As you use an Arch-flavoured OS, this might work for you.

**Comment by 4rtemis-4rrow** [comment]
that worked, thanks

also, turns out that the bettercap-caplets-git package already has that patch
