### ISSUE TITLE
net.probe on no show

### ISSUE THREAD

**Issue by SvartePettern** [bettercap/bettercap#1118]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). bettercap v2.32.0
* OS version and architecture you are using. Windows 11 Version	10.0.22631 Build 22631
* Go version if building from sources.
* Command line arguments you are using. net.probe on
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).   
* arp.spoof arp cache restoration after spoofing enabled
* creating capture for 'lo' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
* [war] Could not find mac for
*  events.stream

### Steps to Reproduce

1. sudo bettercap
2. net.probe on
3. 
**Expected behavior:** probing

**Actual behavior:** could not fint mac

--

**Comment by evilsocket** [comment]
you are not specifying the correct network interface with the '-iface Name' argument

**Comment by SvartePettern** [comment]
> * ode

what is this nazi germany im just looking for some help ffs

**Comment by SvartePettern** [comment]
> you are not specifying the correct network interface with the '-iface Name' argument

what do you mean

**Comment by evilsocket** [comment]
i mean RTFM https://www.bettercap.org/usage/interactive/#-iface-interface

**Comment by SvartePettern** [comment]
> i mean RTFM https://www.bettercap.org/usage/interactive/#-iface-interface

how do i go about fixing this?

**Comment by SvartePettern** [comment]
i try to use the -iface argument with my mac adress but it says no interface mathing xxx found

**Comment by evilsocket** [comment]
try to use the interface name
