### ISSUE TITLE
net.show not showing any devices

### ISSUE THREAD

**Issue by LVFK04** [bettercap/bettercap#1123]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
My version: v2.32.0

* OS version and architecture you are using.
My OS: Kali Linux

### Steps to Reproduce

1. sudo bettercap
2. net.recon on
3. net.probe on
4. net.show

**Expected behavior:** *What you expected to happen*
A table of all the the devices in the network

**Actual behavior:** *What actually happened*
A table containing only the eth0 and the gateway

**Comment by evilsocket** [comment]
this happens when there's IP isolation - also: i need debug logs to understand the issue, which you did not provide.

**Comment by LVFK04** [comment]
@evilsocket I'm sorry for the question, but how do I get the debug logs? I am new to bettercap and Kali Linux.

**Comment by evilsocket** [comment]
You run the same command line and add the "-debug" argument, then paste here the output. But i'm telling you, if net.recon and net.probe are on and you only see your IP and the gateway, there's IP isolation going on. You see it often in hotels, schools and public networks

**Comment by LVFK04** [comment]
Okay, but I did the testing on my home-network. Also, is there any way to see work around the IP isolation using bettercap?

**Comment by evilsocket** [comment]
can't tell without the logs

**Comment by LVFK04** [comment]
[14:39:18] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
[14:39:18] [sys.log] [dbg] creating capture for 'eth0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
[14:39:18] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:ac:0e:57]
[14:39:18] [sys.log] [inf] gateway monitor started ...
[14:39:18] [mod.started] events.stream
[14:39:18] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:ac:0e:57) ipv6=()

**Comment by LVFK04** [comment]
The logs are above. Sorry for the long delay @evilsocket

**Comment by LVFK04** [comment]
Pinging @evilsocket

**Comment by evilsocket** [comment]
dude, you are running from a virtual machine, possibly configured not to forward traffic on your network, i already told you that from the logs everything is normal except IP are isolated. Please learn to configure your VM instead of spamming this repo with issues.
