### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by strunz983** [bettercap/bettercap#1126]
My OS Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux

Hello i got this message
┌──(root💀kali)-[~/Desktop/bettercap-2.4.0]
└─# make build
make[1]: Entering directory '/root/Desktop/bettercap-2.4.0/modules/ui/ui'
make[1]: *** No rule to make target 'build'.  Stop.
make[1]: Leaving directory '/root/Desktop/bettercap-2.4.0/modules/ui/ui'
make: *** [Makefile:19: modules/ui/ui/dist/ui/index.html] Error 2
and
go build                                     
modules/ui/ui.go:15:13: pattern ui/dist/ui: no matching files found

Thank you

**Comment by jorensc** [comment]
Try 
`git clone --recurse-submodules https://github.com/bettercap/bettercap.git`
Works for me.

**Comment by strunz983** [comment]
Thank you jorensc 👍 !!!!!
