### ISSUE TITLE
Version number of release 2.4 is lower than the previous 2.33

### ISSUE THREAD

**Issue by fvcr** [bettercap/bettercap#1127]
Hello,

I noticed that the recent version of Bettercap, version 2.4, has a lower version number than the previous version, 2.33.
This seems to be a regression in version numbering.

Could you please let me know if this is intentional or if there are plans to correct this discrepancy?

Best regards.

**Comment by evilsocket** [comment]
Hi @fvcr, it was a mistake as others fortunately pointed out! I just retagged v2.40.0 that makes slightly more sense :D
