### ISSUE TITLE
Cannot enter web ui.

### ISSUE THREAD

**Issue by NinjaXility** [bettercap/bettercap#1129]
it says i cant connect to my api, but its started. no other plugins run on 8081 (the port the api runs on). i have the correct credentials.![jzfEnQd.png](https://github.com/user-attachments/assets/b35a3f52-c777-4758-9154-a7b620eaf65e)
![pSOrMS1.png](https://github.com/user-attachments/assets/b44f7f5c-2b09-4730-b052-5f212c7205ac)

![FTsYMmd.png](https://github.com/user-attachments/assets/3e085e1b-b24a-4907-958d-9e59fa7fe536)

![vQdbDRz.png](https://github.com/user-attachments/assets/d483f5d6-9262-4953-8c43-026bf0f2197d)

first 2 images i checked if any other plugins are using 8081.
4th image i provided login screen, 3rd is me checking if the api is up.

**Comment by evilsocket** [comment]
as the error message says, something is already using port 80. Port 8081 is for the API, but you seem to have set port 80 for the http-ui. Also read this https://www.evilsocket.net/2024/09/13/Introducing-bettercap-2-4-0-CAN-bus-hacking-WiFi-bruteforcing-and-builtin-web-UI/#Builtin-Web-UI ... the http-ui caplet is deprecated.
