### ISSUE TITLE
Compilation error on Rapsberry Pi 5

### ISSUE THREAD

**Issue by M3ro20j1** [bettercap/bettercap#1132]
# Prerequisites

When a try to compil the latest version i have this error : 

 19% building 78/91 modules 13 active ...onents/advanced/advanced.component.scssDeprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

  ╷
2 │ ┌   &:after {
3 │ │     content: '';
4 │ │     display:table;
5 │ │     clear:both;
6 │ │   }
  │ └─── nested rule
7 │     width:30px;
  │     ^^^^^^^^^^ declaration
  ╵
    stdin 7:3  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
2   │ ┌   &:after {
3   │ │     content: '';
4   │ │     display:table;
5   │ │     clear:both;
6   │ │   }
    │ └─── nested rule
... │
8   │     display:table-cell;
    │     ^^^^^^^^^^^^^^^^^^ declaration
    ╵
    stdin 8:3  root stylesheet

# Patch

Change the file [bettercap/modules/ui/ui/src/app/components/signal-indicator/signal-indicator.component.scss](http://github.com/bettercap/bettercap/modules/ui/ui/src/app/components/signal-indicator/signal-indicator.component.scss)

To : 

  .signal-indicator--wrapper {
  &:after {
    content: '';
    display:table;
    clear:both;
  }
  & {
  width:30px;
  display:table-cell;
  }
  .signal-indicator--step {
    display:inline-block;
    background-color:#32383e;
    width:5px;
    transition: height .2s ease-in-out;
    margin-right:3px;
    margin-bottom: 4px;
    vertical-align: bottom;
    &:last-child {
      margin-right:0;
    }
    &.signal-indicator__step1{
      height:2px;
    }
    &.signal-indicator__step2{
      height:5px;
    }
    &.signal-indicator__step3{
      height:10px;
    }
    &.signal-indicator__step4{
      height:15px;
    }
  }
  &.step__1{
    .currentStep {
      background-color:red;
    }
  }
  &.step__2{
    .currentStep {
      background-color:yellow;
    }
  }
  &.step__3{
    .currentStep {
      background-color:yellowgreen;
    }
  }
  &.step__4{
    .currentStep {
      background-color:green;
    }
  }
}

And now it's work

**Comment by evilsocket** [comment]
i'm not sure i understand, the UI is [already compiled](https://github.com/bettercap/ui/tree/master/dist/ui) and included as [git submodule](https://github.com/bettercap/bettercap/tree/master/modules/ui). There's no compilation needed other than what explained here https://www.bettercap.org/installation/ ... what are you trying to do exactly?
