### ISSUE TITLE
"go install" is pulling the incorrect version 

### ISSUE THREAD

**Issue by greentea47** [bettercap/bettercap#1135]
hi, "go install" is pulling the incorrect version , maybe the 'latest' tag is pointing to the wrong version?

$ go install github.com/bettercap/bettercap@latest 

go: finding module for package github.com/evilsocket/islazy/str
go: finding module for package github.com/bettercap/readline
go: finding module for package github.com/bettercap/recording
go: finding module for package github.com/evilsocket/islazy/data
go: finding module for package github.com/evilsocket/islazy/log
go: finding module for package github.com/evilsocket/islazy/ops
go: finding module for package github.com/evilsocket/islazy/tui
go: finding module for package github.com/gorilla/websocket
go: finding module for package github.com/gorilla/mux
go: finding module for package github.com/dustin/go-humanize
go: finding module for package github.com/evilsocket/islazy/fs
go: finding module for package github.com/malfunkt/iprange
go: finding module for package github.com/bettercap/gatt
go: finding module for package github.com/evilsocket/islazy/zip
go: finding module for package github.com/google/gopacket
go: finding module for package github.com/google/gopacket/layers
go: finding module for package github.com/google/gopacket/pcap
go: finding module for package github.com/mdlayher/dhcp6
go: finding module for package github.com/mdlayher/dhcp6/dhcp6opts
go: finding module for package github.com/gobwas/glob
go: finding module for package github.com/antchfx/jsonquery
go: finding module for package github.com/google/go-github/github
go: finding module for package github.com/adrianmo/go-nmea
go: finding module for package github.com/tarm/serial
go: finding module for package github.com/bettercap/nrf24
go: finding module for package github.com/google/gousb
go: finding module for package github.com/elazarl/goproxy
go: finding module for package github.com/evilsocket/islazy/plugin
go: finding module for package github.com/inconshreveable/go-vhost
go: finding module for package github.com/jpillora/go-tld
go: finding module for package github.com/robertkrimen/otto
go: finding module for package github.com/hashicorp/mdns
go: finding module for package github.com/google/gopacket/pcapgo
go: finding module for package github.com/chifflier/nfqueue-go/nfqueue
go: finding module for package github.com/evilsocket/islazy/async
go: finding module for package github.com/miekg/dns
go: finding module for package golang.org/x/net/html
go: found github.com/evilsocket/islazy/str in github.com/evilsocket/islazy v1.11.0
go: found github.com/evilsocket/islazy/tui in github.com/evilsocket/islazy v1.11.0
go: found github.com/evilsocket/islazy/log in github.com/evilsocket/islazy v1.11.0
go: found github.com/bettercap/readline in github.com/bettercap/readline v0.0.0-20210228151553-655e48bcb7bf
go: found github.com/dustin/go-humanize in github.com/dustin/go-humanize v1.0.1
go: found github.com/evilsocket/islazy/data in github.com/evilsocket/islazy v1.11.0
go: found github.com/evilsocket/islazy/fs in github.com/evilsocket/islazy v1.11.0
go: found github.com/evilsocket/islazy/ops in github.com/evilsocket/islazy v1.11.0
go: found github.com/bettercap/recording in github.com/bettercap/recording v0.0.0-20190408083647-3ce1dcf032e3
go: found github.com/gorilla/mux in github.com/gorilla/mux v1.8.1
go: found github.com/gorilla/websocket in github.com/gorilla/websocket v1.5.3
go: found github.com/malfunkt/iprange in github.com/malfunkt/iprange v0.9.0
go: found github.com/bettercap/gatt in github.com/bettercap/gatt v0.0.0-20240808115956-ec4935e8c4a0
go: found github.com/evilsocket/islazy/zip in github.com/evilsocket/islazy v1.11.0
go: found github.com/google/gopacket in github.com/google/gopacket v1.1.19
go: found github.com/google/gopacket/layers in github.com/google/gopacket v1.1.19
go: found github.com/google/gopacket/pcap in github.com/google/gopacket v1.1.19
go: found github.com/mdlayher/dhcp6 in github.com/mdlayher/dhcp6 v0.0.0-20190311162359-2a67805d7d0b
go: found github.com/mdlayher/dhcp6/dhcp6opts in github.com/mdlayher/dhcp6 v0.0.0-20190311162359-2a67805d7d0b
go: found github.com/gobwas/glob in github.com/gobwas/glob v0.2.3
go: found github.com/antchfx/jsonquery in github.com/antchfx/jsonquery v1.3.5
go: found github.com/google/go-github/github in github.com/google/go-github v17.0.0+incompatible
go: found github.com/adrianmo/go-nmea in github.com/adrianmo/go-nmea v1.10.0
go: found github.com/tarm/serial in github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: found github.com/bettercap/nrf24 in github.com/bettercap/nrf24 v0.0.0-20190219153547-aa37e6d0e0eb
go: found github.com/google/gousb in github.com/google/gousb v1.1.3
go: found github.com/elazarl/goproxy in github.com/elazarl/goproxy v0.0.0-20240909085733-6741dbfc16a1
go: found github.com/evilsocket/islazy/plugin in github.com/evilsocket/islazy v1.11.0
go: found github.com/inconshreveable/go-vhost in github.com/inconshreveable/go-vhost v1.0.0
go: found github.com/jpillora/go-tld in github.com/jpillora/go-tld v1.2.1
go: found github.com/robertkrimen/otto in github.com/robertkrimen/otto v0.4.0
go: found github.com/hashicorp/mdns in github.com/hashicorp/mdns v1.0.5
go: found github.com/google/gopacket/pcapgo in github.com/google/gopacket v1.1.19
go: found github.com/chifflier/nfqueue-go/nfqueue in github.com/chifflier/nfqueue-go v0.0.0-20170228160439-61ca646babef
go: found github.com/evilsocket/islazy/async in github.com/evilsocket/islazy v1.11.0
go: found github.com/miekg/dns in github.com/miekg/dns v1.1.62
go: found golang.org/x/net/html in golang.org/x/net v0.29.0
go: finding module for package github.com/google/go-querystring/query
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/kr/binarydist
go: found github.com/kr/binarydist in github.com/kr/binarydist v0.1.0
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found github.com/google/go-querystring/query in github.com/google/go-querystring v1.1.0

$ ./bettercap 
bettercap v2.24.1 (built for linux amd64 with go1.23.1) [type 'help' for a list of commands]

expected behavior-
bettercap v2.40.0

**Comment by derekkddj** [comment]
yes, something is wrong

**Comment by hslatman** [comment]
I think that is the expected behavior, with the module path being `github.com/bettercap/bettercap` it would try to obtain the `latest` from that module (resulting in `v2.24.1`, supposedly that was the last version not using the new import path). But somewhat recently the module path was updated to `github.com/bettercap/bettercap/v2`, so it should become `go install github.com/bettercap/bettercap/v2@latest`.

However, with installing that `v2`, it results in this error: `go/pkg/mod/github.com/bettercap/bettercap/v2@v2.40.0/modules/ui/ui.go:15:13: pattern ui/dist/ui: no matching files found`. That makes sense as the non-Go files won't be pulled in by `go install` (without additional work on that part). Haven't looked into the actual changes, but I did see that some work was done to include the UI by default, so it seems related. If building from source, that is solved by fetching the submodule, but `go install` doesn't do that.

@evilsocket if the `go install` command is expected to work as it does for other Go commands some tweaks may be required. One example for including a built web app embedded in a Go module that I know of is https://github.com/riverqueue/riverui with the import path `riverqueue.com/riverui`, which includes the web app resources to be distributed. Here's a blog describing how it works: https://riverqueue.com/blog/river-ui-module-http-handler. A similar approach might work in this case. Other options might exist, of course.

**Comment by evilsocket** [comment]
oh man what a mess! i'm still trying to wrap my head around this v2 thing ... thanks for reporting, will try to find a decent solution to this

**Comment by evilsocket** [comment]
@hslatman thanks for the info, i think the main problem is that the precompiled UI assets are included as a git submodule here https://github.com/bettercap/bettercap/tree/master/modules/ui

**Comment by evilsocket** [comment]
Fixed by embedding the ui assets directly, go install github.com/bettercap/bettercap/v2@master works and latest will work with the next release.

**Comment by hslatman** [comment]
@evilsocket Awesome! Thanks for the swift fix! 😄

**Comment by Twilightsdrop** [comment]
> go install github.com/bettercap/bettercap/v2@master

this is the only thing that worked for me  atm on fedora can you put something on the website or github readme so new users arent banging there heads lol im kind of noob and almost gave up trying to add this until i looked at this thread

**Comment by anthraxx** [comment]
@evilsocket thank you very much for working on this project. May I kindly request to consider a soonish release? I'm hitting issues related to the previous submodule during distro packaging and would highly appreciate a release containing these adjustments. Thank you.

**Comment by evilsocket** [comment]
@anthraxx i got you! :D just released v2.41.0

**Comment by hslatman** [comment]
> go install github.com/bettercap/bettercap@latest

You have to run `go install github.com/bettercap/bettercap/v2@latest`. Otherwise it'll use the `latest` version of "v1", which in this case is actually tagged with a `v2.x.x.`, but generally would've been a `v1.x.x.`.

**Comment by sagisar1** [comment]
@hslatman I succeeded now to install the latest version in the method you wrote, however, I suggest to the maintainer of the project to fix this in the docs:
[https://www.bettercap.org/installation/](https://www.bettercap.org/installation/)

because it's written there:

> go install github.com/bettercap/bettercap@latest

**Comment by sagisar1** [comment]
@hslatman - Awesome, saw that it changed, thank you, I hope this would help future users :)
