### ISSUE TITLE
i cant see wifis and ipv4 gateway: could not find mac for 192.168.1.1

### ISSUE THREAD

**Issue by Rauins** [bettercap/bettercap#1138]
*Error getting ipv4 gateway: could not find mac for 192.168.1.1*

### Environment

Please provide:

* V2.33.0
* Kali Linux
* set wifi.interface wlan0
* bettercap -caplet http-ui

### Steps to Reproduce

1. *bettercap -caplet http-ui*
2. *set wifi.interface wlan0*
3. *wifi.recon on*

**Expected behavior: See wifi's*

**Actual behavior: "IPV6 Gateway changed: 
error getting ipv4 gateway: could not find mac for 192.168.1.1

--

**Comment by buffermet** [comment]
Please show all debug output as requested in the template you removed
