### ISSUE TITLE
Feature: ability to remove session event listeners in session scripts.

### ISSUE THREAD

**Issue by buffermet** [bettercap/bettercap#1139]
In session scripts we are missing the option to remove session event listeners. If we have a function like `removeEventListener(tickerName, func)` then we won't get a buildup of unused session event listeners.

Example:

```js
var myFunc = function() {
    // do stuff
}

onEvent('ticker.myTicker', myFunc)

// later we could decide to remove this listener like so:
removeEventListener('ticker.myTicker', myFunc)
```

**Comment by evilsocket** [comment]
@buffermet done! let me know if you find any issues with how this works
