### ISSUE TITLE
Could not detect gateway 

### ISSUE THREAD

**Issue by dr1408** [bettercap/bettercap#1142]
### Environment

Please provide:

* Bettercap version you are using ( `latest 2.40 build with go` ).
* OS version and architecture you are using. (Kali nethunter arm64)
* Go version if building from sources. Go 1.23
* Command line arguments you are using. Bettercap wlan0
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

```
└─# bettercap -debug
bettercap v2.40.0 (built for linux arm64 with go1.23.2) [type 'help' for a list of commands]
                                                                                                                                                          192.168.1.0/24 > 192.168.1.67  » [06:43:25] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
192.168.1.0/24 > 192.168.1.67  » [06:43:25] [sys.log] [dbg] creating capture for 'wlan0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
192.168.1.0/24 > 192.168.1.67  » [06:43:25] [sys.log] [dbg] exec=/usr/bin/netstat args=[-r -n -4 -6] ret_err=<nil> ret_out=Kernel IP routing table        Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref  Use If
::/0                           ::                         !n   -1  1 129328 lo
fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan0
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0                                                                        fe80::/64                      ::                         U    256 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0                                                                        ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 129328 lo
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1                                                                  ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0                                                                        fe80::/64                      ::                         U    1024 1      0 wlan0
ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 129328 lo                                                                            ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
fe80::/64                      ::                         U    256 1      0 dummy0                                                                        ::/0                           ::                         U    1024 1      0 dummy0
::/0                           ::                         !n   -1  1 129328 lo
fe80::/64                      ::                         U    256 3     39 rmnet_data0
::/0                           fe80::1dcc:e22d:8776:b0c9  UGDAe 1024 1      0 rmnet_data0
::/0                           ::                         !n   -1  1 129328 lo
fc17:0:72:f7a2::/64            ::                         UA   256 1      0 rmnet_data1
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1                                                                  fe80::/64                      ::                         U    256 1      0 rmnet_data1
::/0                           fe80::905e:2501:1d1a:6f2e  UGDAe 1024 3     10 rmnet_data1
::/0                           ::                         !n   -1  1 129328 lo                                                                            ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::1/128                        ::                         Un   0   10     83 lo                                                                           fc17:0:72:f7a2:eb9c:301b:c989:26c0/128 ::                         Un   0   4      5 rmnet_data1
fdd8:2918:e2b8:c900:2f73:40cc:7828:9017/128 ::                         Un   0   2      0 wlan0
fdd8:2918:e2b8:c900:847e:56ff:febd:b303/128 ::                         Un   0   2      0 wlan0                                                            fe80::1b68:4d7e:1a8f:a6ba/128  ::                         Un   0   4     24 rmnet_data0
fe80::847e:56ff:febd:b303/128  ::                         Un   0   2      0 wlan0                                                                         fe80::b882:dbff:fe62:a4be/128  ::                         Un   0   2      0 dummy0
fe80::eb9c:301b:c989:26c0/128  ::                         Un   0   3      1 rmnet_data1
ff00::/8                       ::                         U    256 9   1308 dummy0
ff00::/8                       ::                         U    256 6     12 rmnet_data0
ff00::/8                       ::                         U    256 4     10 rmnet_data1                                                                   ff00::/8                       ::                         U    256 7     28 wlan0
::/0                           ::                         !n   -1  1 129328 lo

192.168.1.0/24 > 192.168.1.67  » [06:43:25] [sys.log] [dbg] FindGateway(wlan0): nothing found :/
192.168.1.0/24 > 192.168.1.67  » [06:43:25] [sys.log] [war] Could not detect gateway.
192.168.1.0/24 > 192.168.1.67  » [06:43:25] [mod.started] events.stream
192.168.1.0/24 > 192.168.1.67  »
```

### Steps to Reproduce

1. Run bettercap wlan0 

**Expected behavior:** *arp spoof attack to work*

**Actual behavior:** *could not detect gateway*

![8437CB29-DCA7-43DA-995F-F3BCBADDC8F0](https://github.com/user-attachments/assets/a7fbabf0-20da-4d28-9f5f-31ec4a775285)

i tried the tool on laptop and i like alot and appreciate this great project .. 2 differences happens in nethunter and i guess that what tdosent make it work .. it dosent detect gateway .. then when i run arp.spoof on .. it dosent show ip forwading enabled message .. i hope you can guide me .. have a great day sir 🙏🏼

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by dr1408** [comment]
Now im connected to network through adapter wlan1 also .. i need to be connected to same network with wlan0 which is mobile internet and throught adapter .. now gateway monitor working but ip forwarding didn showafter enabling arp spoof .. internet stop on victim side .. i used these commands sudo bettercap + set arp.spoof.targets to my target ip 


![DBAF17CB-B719-4F7B-93E7-3C5468340B44](https://github.com/user-attachments/assets/514ad15d-519e-4a56-9500-351629ed87d7)
![A5F6783D-DAB0-4A9B-BF8A-5A671D6D61D4](https://github.com/user-attachments/assets/a5277e10-586f-4f8f-929b-195f428fbb84)

here are some logs after gateway monitor enabled :


[07:37:52] [sys.log] [dbg] gateway is 192.168.1.1[d8:29:18:e2:b8:c9]
[07:37:52] [sys.log] [dbg] exec=/usr/bin/netstat args=[-r -n -4 -6] ret_err=<nil> ret_out=Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan1
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref  Use If
::/0                           ::                         !n   -1  1 141739 lo
fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan0
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0
fe80::/64                      ::                         U    256 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0
ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 141739 lo
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan1
fe80::/64                      ::                         U    256 1      0 wlan1
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0
ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
fe80::/64                      ::                         U    256 1      0 dummy0
::/0                           ::                         U    1024 1      0 dummy0
::/0                           ::                         !n   -1  1 141739 lo
fe80::/64                      ::                         U    256 3     39 rmnet_data0
::/0                           fe80::1dcc:e22d:8776:b0c9  UGDAe 1024 1      0 rmnet_data0
::/0                           ::                         !n   -1  1 141739 lo
fc17:0:72:f7a2::/64            ::                         UA   256 1      0 rmnet_data1
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1
fe80::/64                      ::                         U    256 1      0 rmnet_data1
::/0                           fe80::905e:2501:1d1a:6f2e  UGDAe 1024 3     10 rmnet_data1
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::/0                           ::                         !n   -1  1 141739 lo
::1/128                        ::                         Un   0   10     83 lo
fc17:0:72:f7a2:eb9c:301b:c989:26c0/128 ::                         Un   0   4      5 rmnet_data1
fdd8:2918:e2b8:c900:83d:857d:5580:62a7/128 ::                         Un   0   2      0 wlan0
fdd8:2918:e2b8:c900:3e52:a1ff:fee2:52fa/128 ::                         Un   0   3      2 wlan1
fdd8:2918:e2b8:c900:847e:56ff:febd:b303/128 ::                         Un   0   2      0 wlan0
fe80::1b68:4d7e:1a8f:a6ba/128  ::                         Un   0   4     24 rmnet_data0
fe80::3e52:a1ff:fee2:52fa/128  ::                         Un   0   3      3 wlan1
fe80::847e:56ff:febd:b303/128  ::                         Un   0   2      0 wlan0
fe80::b882:dbff:fe62:a4be/128  ::                         Un   0   2      0 dummy0
fe80::eb9c:301b:c989:26c0/128  ::                         Un   0   3      1 rmnet_data1
ff00::/8                       ::                         U    256 9   1308 dummy0
ff00::/8                       ::                         U    256 6     12 rmnet_data0
ff00::/8                       ::                         U    256 4     10 rmnet_data1
ff00::/8                       ::                         U    256 2     19 wlan1
ff00::/8                       ::                         U    256 3      2 wlan0
::/0                           ::                         !n   -1  1 141739 lo



[08:01:56] [sys.log] [dbg] arp.spoof sending 60 bytes of ARP packet to 192.168.1.58:b2:67:18:fa:9d:fd.                                                    [08:01:57] [sys.log] [dbg] exec=/usr/sbin/ip args=[neigh] ret_err=<nil> ret_out=192.168.1.2 dev wlan1 lladdr cc:2d:21:61:71:58 STALE                      192.168.1.23 dev wlan0 lladdr 6a:40:cc:c1:81:bf STALE                                                                                                     192.168.1.58 dev wlan0 lladdr b2:67:18:fa:9d:fd REACHABLE                                                                                                 192.168.1.1 dev wlan0 lladdr d8:29:18:e2:b8:c9 REACHABLE                                                                                                  192.168.1.2 dev wlan0 lladdr cc:2d:21:61:71:58 STALE                                                                                                      fe80::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE
fe80::1 dev wlan0 lladdr d8:29:18:e2:b8:c9 router STALE                                                                                                   fdd8:2918:e2b8:c900::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE                                                                                    
[08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.2 dev wlan1 lladdr cc:2d:21:61:71:58 STALE  192.168.1.2 wlan1 cc:2d:21:61:71:58]                   [08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.23 dev wlan0 lladdr 6a:40:cc:c1:81:bf STALE  192.168.1.23 wlan0 6a:40:cc:c1:81:bf]                 [08:01:57] [sys.log] [dbg]   192.168.1.23 = 6a:40:cc:c1:81:bf
[08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.58 dev wlan0 lladdr b2:67:18:fa:9d:fd REACHABLE  192.168.1.58 wlan0 b2:67:18:fa:9d:fd]             [08:01:57] [sys.log] [dbg]   192.168.1.58 = b2:67:18:fa:9d:fd                                                                                             [08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.1 dev wlan0 lladdr d8:29:18:e2:b8:c9 REACHABLE  192.168.1.1 wlan0 d8:29:18:e2:b8:c9]               [08:01:57] [sys.log] [dbg]   192.168.1.1 = d8:29:18:e2:b8:c9
[08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.2 dev wlan0 lladdr cc:2d:21:61:71:58 STALE  192.168.1.2 wlan0 cc:2d:21:61:71:58]                   [08:01:57] [sys.log] [dbg]   192.168.1.2 = cc:2d:21:61:71:58                                                                                              [08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [fe80::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE  fe80::1 wlan1 d8:29:18:e2:b8:c9]
[08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [fe80::1 dev wlan0 lladdr d8:29:18:e2:b8:c9 router STALE  fe80::1 wlan0 d8:29:18:e2:b8:c9]                    [08:01:57] [sys.log] [dbg]   fe80::1 = d8:29:18:e2:b8:c9
[08:01:57] [sys.log] [dbg] ARP TABLE MATCH: [fdd8:2918:e2b8:c900::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE fdd8:2918:e2b8:c900::1 wlan1 d8:29:18:e2:b8:c9]                                                                                                                                                 [08:01:57] [sys.log] [dbg] arp.spoof sending 60 bytes of ARP packet to 192.168.1.58:b2:67:18:fa:9d:fd.
[08:01:58] [sys.log] [dbg] exec=/usr/sbin/ip args=[neigh] ret_err=<nil> ret_out=192.168.1.2 dev wlan1 lladdr cc:2d:21:61:71:58 STALE
192.168.1.23 dev wlan0 lladdr 6a:40:cc:c1:81:bf STALE                                                                                                     192.168.1.58 dev wlan0 lladdr b2:67:18:fa:9d:fd REACHABLE
192.168.1.1 dev wlan0 lladdr d8:29:18:e2:b8:c9 REACHABLE
192.168.1.2 dev wlan0 lladdr cc:2d:21:61:71:58 STALE                                                                                                      fe80::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE
fe80::1 dev wlan0 lladdr d8:29:18:e2:b8:c9 router STALE                                                                                                   fdd8:2918:e2b8:c900::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE                                                                                    
[08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.2 dev wlan1 lladdr cc:2d:21:61:71:58 STALE  192.168.1.2 wlan1 cc:2d:21:61:71:58]                   [08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.23 dev wlan0 lladdr 6a:40:cc:c1:81:bf STALE  192.168.1.23 wlan0 6a:40:cc:c1:81:bf]
[08:01:58] [sys.log] [dbg]   192.168.1.23 = 6a:40:cc:c1:81:bf
[08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.58 dev wlan0 lladdr b2:67:18:fa:9d:fd REACHABLE  192.168.1.58 wlan0 b2:67:18:fa:9d:fd]             [08:01:58] [sys.log] [dbg]   192.168.1.58 = b2:67:18:fa:9d:fd
[08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.1 dev wlan0 lladdr d8:29:18:e2:b8:c9 REACHABLE  192.168.1.1 wlan0 d8:29:18:e2:b8:c9]
[08:01:58] [sys.log] [dbg]   192.168.1.1 = d8:29:18:e2:b8:c9                                                                                              [08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [192.168.1.2 dev wlan0 lladdr cc:2d:21:61:71:58 STALE  192.168.1.2 wlan0 cc:2d:21:61:71:58]
[08:01:58] [sys.log] [dbg]   192.168.1.2 = cc:2d:21:61:71:58
[08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [fe80::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE  fe80::1 wlan1 d8:29:18:e2:b8:c9]                    [08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [fe80::1 dev wlan0 lladdr d8:29:18:e2:b8:c9 router STALE  fe80::1 wlan0 d8:29:18:e2:b8:c9]
[08:01:58] [sys.log] [dbg]   fe80::1 = d8:29:18:e2:b8:c9
[08:01:58] [sys.log] [dbg] ARP TABLE MATCH: [fdd8:2918:e2b8:c900::1 dev wlan1 lladdr d8:29:18:e2:b8:c9 router STALE fdd8:2918:e2b8:c900::1 wlan1 d8:29:18:e2:b8:c9]
^C                                                                                                                                                                                                                                                                                                                  Stopping modules and cleaning session state ...
[08:01:58] [sys.log] [war] Got SIGTERM                                                                                                                    [08:01:58] [session.closing] {session.closing 2024-10-12 08:01:58.502703342 +0000 UTC m=+109.426183141 <nil>}
[08:01:58] [mod.stopped] arp.spoof
[08:01:58] [sys.log] [inf] arp.spoof waiting for ARP spoofer to stop ...                                                                                  [08:01:58] [sys.log] [inf] arp.spoof restoring ARP cache of 1 targets.
[08:01:58] [sys.log] [dbg] arp.spoof sending 60 bytes of ARP packet to 192.168.1.58:b2:67:18:fa:9d:fd.





Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface                                                                            0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan1                                                                            Kernel IPv6 routing table                                                                                                                                 Destination                    Next Hop                   Flag Met Ref  Use If
::/0                           ::                         !n   -1  1 141905 lo                                                                            fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan0                                                                         fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0                                                                        fe80::/64                      ::                         U    256 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0                                                                        ff00::/8                       ::                         U    1024 1      0 wlan0                                                                        ::/0                           ::                         !n   -1  1 141905 lo                                                                            fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1
::/0                           ::                         !n   -1  1 141905 lo                                                                            ::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo                                                                            ::/0                           ::                         !n   -1  1 141905 lo                                                                            ::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo
fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan1                                                                         fe80::/64                      ::                         U    256 1      0 wlan1
::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo                                                                            fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0
ff00::/8                       ::                         U    1024 1      0 wlan0                                                                        ::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo                                                                            ::/0                           ::                         !n   -1  1 141905 lo                                                                            ::/0                           ::                         !n   -1  1 141905 lo
fe80::/64                      ::                         U    256 1      0 dummy0                                                                        ::/0                           ::                         U    1024 1      0 dummy0                                                                       ::/0                           ::                         !n   -1  1 141905 lo                                                                            fe80::/64                      ::                         U    256 3     39 rmnet_data0
::/0                           fe80::1dcc:e22d:8776:b0c9  UGDAe 1024 1      0 rmnet_data0                                                                 ::/0                           ::                         !n   -1  1 141905 lo
fc17:0:72:f7a2::/64            ::                         UA   256 1      0 rmnet_data1
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1                                                                  fe80::/64                      ::                         U    256 1      0 rmnet_data1
::/0                           fe80::905e:2501:1d1a:6f2e  UGDAe 1024 3     10 rmnet_data1                                                                 ::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo
::/0                           ::                         !n   -1  1 141905 lo                                                                            ::1/128                        ::                         Un   0   10     83 lo
fc17:0:72:f7a2:eb9c:301b:c989:26c0/128 ::                         Un   0   4      5 rmnet_data1
fdd8:2918:e2b8:c900:83d:857d:5580:62a7/128 ::                         Un   0   2      0 wlan0
fdd8:2918:e2b8:c900:3e52:a1ff:fee2:52fa/128 ::                         Un   0   3      2 wlan1
fdd8:2918:e2b8:c900:847e:56ff:febd:b303/128 ::                         Un   0   2      0 wlan0
fe80::1b68:4d7e:1a8f:a6ba/128  ::                         Un   0   4     24 rmnet_data0
fe80::3e52:a1ff:fee2:52fa/128  ::                         Un   0   3      3 wlan1
fe80::847e:56ff:febd:b303/128  ::                         Un   0   2      0 wlan0
fe80::b882:dbff:fe62:a4be/128  ::                         Un   0   2      0 dummy0
fe80::eb9c:301b:c989:26c0/128  ::                         Un   0   3      1 rmnet_data1
ff00::/8                       ::                         U    256 9   1308 dummy0
ff00::/8                       ::                         U    256 6     12 rmnet_data0
ff00::/8                       ::                         U    256 4     10 rmnet_data1
ff00::/8                       ::                         U    256 7     82 wlan1
ff00::/8                       ::                         U    256 7     26 wlan0
::/0                           ::                         !n   -1  1 141905 lo




note : if i disconnect wlan0 it will be back to (cant detect gateway ) so i need to keep wlan0 and wlan1 connected

**Comment by dr1408** [comment]
![4A7639C2-6D53-4114-81FC-69E55DC85F9A](https://github.com/user-attachments/assets/48072537-3b40-4175-851f-5fea54a41e0d)
![B18CB97E-D8FB-479E-82EA-7377CBAB5503](https://github.com/user-attachments/assets/558b2812-a0b9-4544-a594-355128897f7c)

After reverting back to the old iptables captures some stuff but still ip forwarding and internet not working on the victim .. i guess its something missing with ip rules and ip forwarding

**Comment by Fadi002** [comment]
same issue with me have you found solution yet ?

**Comment by dr1408** [comment]
Unfortunately no i guess its issue related to ip forwarding not sure i hope the developers will help it been problem for a year

**Comment by buffermet** [comment]
You can override the gateway by setting the `-gateway-override` argument.

Example: `sudo bettercap -iface wlan0 -gateway-override 192.168.1.1`

**Comment by dr1408** [comment]
Sir we are talking about the victim dosent have internet when we turn arp spoof on .. its due to forwarding issue maybe not realted to gatewat

**Comment by dr1408** [comment]
![A2C7DE28-18B4-4B1D-BD31-2F059AB1AFD3](https://github.com/user-attachments/assets/765104df-6d26-46ed-aad0-3d22aea08d80)


Actually your magical command sir made it work but internet is very slow somtimes site open and somtimes not maybe its my connection problem dunno but will keep testing thanks alot you made my day i been trying to fix it for a year

**Comment by dr1408** [comment]
So it just worked that time now it dosent forward internet again i hope someone will hrlp us with the correct ip rules to forward internet to the victim i applied same commands worked once only other tests didn succeed

**Comment by buffermet** [comment]
> Sir we are talking about the victim dosent have internet when we turn arp spoof on .. its due to forwarding issue maybe not realted to gatewat

It sounds like your router is using ARP spoofing protections. This is stated in all the documentation with clear warnings.

![image](https://github.com/user-attachments/assets/c5f7c150-6699-480a-ac60-66fdbb07d7d1)

You will need to create your own access point, or ARP spoofing protections have to be disabled on the router's admin panel (if possible).

**Comment by buffermet** [comment]
> i used these commands sudo bettercap + set arp.spoof.targets to my target ip

Can you actually give us the full output? We don't want screenshots, just show us everything you are doing.

**Comment by dr1408** [comment]
Yes thats what i did exactly after your command 

net.probe on
Set arp.spoof.targets (ip)
Arp.spoof on
Net.sniff on

it dosent work worked once in like 50 test

**Comment by Fadi002** [comment]
For me the arp spoofing makes the victim internet too slow and even cause the victim browsers and apps timeout due the extremely slow internet

**Comment by dr1408** [comment]
@fadi002 yes i face the same issue thats why its not working actually my victim was iphone

**Comment by dr1408** [comment]
@buffermet actuuqly the attack work fine when i run the tool in my laptop .. but it fails on nethuntet so i guess the issue is  not the router .. my victim is my other phone so im very close to it .. im using my internal wifi not using adapter on phone

**Comment by buffermet** [comment]
you need to get a powered antenna that supports monitor mode and packet injection

**Comment by dr1408** [comment]
Im not sure if afapter is important cause all my tests was done by internal wifi and worked somtimes.. anyway i plugged my antenna and tried tour command it just give me (endpoint lost ) thing dunno why .. i tried sudo bettercap wlan1 then endpoints is stable but still bo internet for victim packets are very slow i hope there will be fix this is 3rd issue i opened during a year i hope one of devs will install the tool on termux or nethunter and figure it out

**Comment by dr1408** [comment]
192.168.1.0/24 > 192.168.1.43  » net[07:58:00] [zeroconf.browsing] 192.168.1.45 is browsing (QUERY) for services _services._dns-sd._udp.local
192.168.1.0/24 > 192.168.1.43  » net[07:58:04] [endpoint.lost] endpoint 192.168.1.45 86:7e:56:bd:b3:03 lost.
192.168.1.0/24 > 192.168.1.43  » net[07:58:05] [endpoint.new] endpoint 192.168.1.45 detected as 86:7e:56:bd:b3:03.
192.168.1.0/24 > 192.168.1.43  » net[07:58:15] [sys.log] [inf] ipv6 fe80::847e:56ff:febd:b303 detected for 192.168.1.45 (86:7e:56:bd:b3:03)
192.168.1.0/24 > 192.168.1.43  » net[07:58:16] [zeroconf.browsing] 192.168.1.45 is browsing (QUERY) for services _services._dns-sd._udp.local
192.168.1.0/24 > 192.168.1.43  » net[07:58:16] [zeroconf.browsing] 192.168.1.45 is browsing (QUERY) for services _services._dns-sd._udp.local
192.168.1.0/24 > 192.168.1.43  » net[07:58:22] [endpoint.new] endpoint 192.168.1.8 detected as 30:fc:eb:22:8e:f5 (LG Electronics (Mobile Communications)).

Im using Tp link w722n V3 with net.probe command and your command

**Comment by dr1408** [comment]
![3F3FA369-6483-4379-856B-B66EDCE1B794](https://github.com/user-attachments/assets/33e36ba7-ea71-4605-8031-6b0e4e7c8e59)

**Comment by dr1408** [comment]
Now i run this commands 

sudo bettercap wlan1 
Set arp.spoof.targets (ip)
Arp.spoof on
Net.sniff on

this is the output and again no internet 

192.168.1.0/24 > 192.168.1.49  » [08:15:35] [net.sniff.https] sni 192.168.1.45 > https://play.googleapis.com
192.168.1.0/24 > 192.168.1.49  » [08:15:37] [net.sniff.dns] dns gateway > 192.168.1.45 : 1.1.168.192.in-addr.arpa is Non-Existent Domain
192.168.1.0/24 > 192.168.1.49  » [08:15:42] [net.sniff.mdns] mdns 192.168.1.45 : PTR query for _services._dns-sd._udp.local
192.168.1.0/24 > 192.168.1.49  » [08:15:42] [net.sniff.dns] dns gateway > 192.168.1.45 : 1.1.168.192.in-addr.arpa is Non-Existent Domain
192.168.1.0/24 > 192.168.1.49  » [08:15:42] [sys.log] [inf] zerogod got mdns packet from unknown ip 192.168.1.45
192.168.1.0/24 > 192.168.1.49  » [08:15:42] [sys.log] [inf] zerogod DNS op=Query QUERY from 192.168.1.45 (r_code=No Error) :
  Q: {_services._dns-sd._udp.local PTR IN}

192.168.1.0/24 > 192.168.1.49  » [08:15:43] [net.sniff.https] sni 192.168.1.48 > https://gateway.facebook.com
192.168.1.0/24 > 192.168.1.49  » [08:15:47] [net.sniff.dns] dns gateway > 192.168.1.45 : 1.1.168.192.in-addr.arpa is Non-Existent Domain
[08:15:52] [net.sniff.dns] dns gateway > 192.168.1.45 : 1.1.168.192.in-addr.arpa is Non-Existent Domain
192.168.1.0/24 > 192.168.1.49  » [08:15:53] [net.sniff.https]

**Comment by buffermet** [comment]
not gonna repeat myself
