### ISSUE TITLE
Bettercap MAC error. Please help!

### ISSUE THREAD

**Issue by ojssu** [bettercap/bettercap#1144]
Hello guys! I need some help in relation to fixing this Bettercap error and it cannot find my MAC address. Ive tried a lot, but nothing works! And its almost as if bettercap isnt working at all! Please Help!
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
*latest bettercap version

* System Type:               x64-based PC Windows 11 using Kali Linux from WPS 
* 
* Command line arguments you are using.
* sudo bettercap
* net.probe on
* net.show
* 
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
* MAC not found, [15:52:34] [sys.log] [err] net.probe error while sending mdns probe: invalid src MAC:

### Steps to Reproduce

1. *sudo bettercap*
2. *net.probe on*
3. *net.show*

**Expected behavior:** *What you expected to happen*
being able to see my devices and capture traffic

**Actual behavior:** *What actually happened*
Displays that there is an error while sending mdns probe: invalid src MAC

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by buffermet** [comment]
Please provide all debug logs (not just the error)

**Comment by ojssu** [comment]
> Please provide all debug logs (not just the error)

my bad, i thought people on here would be able to understand the simple error. Why would you need full debug logs? Now youve made me mad

**Comment by buffermet** [comment]
@ojssu you seem confused, judging by the comment you just deleted.

In the issue template it was clearly asked for you to include ALL debug logs, not just 1 error. I know what the error says. I'm trying to help you figure out WHY it says that...

> Full debug output while reproducing the issue ( bettercap -debug ... ).
