### ISSUE TITLE
Its not issue i got solution for ( could not detect gateway)

### ISSUE THREAD

**Issue by dr1408** [bettercap/bettercap#1146]
This fixed bettercap for me

ip route add default via 192.168.1.1 dev wlan0

replace ip with your gateway ip and wlan0 with interface you use

now bettercap working fine on nethunter and internet is shared

**Comment by buffermet** [comment]
Looks like your DHCP server is misconfigured. You won't have an internet connection at all if there is no gateway.

This has nothing to do with bettercap.

**Comment by dr1408** [comment]
![DEAF021F-8696-42CC-A5CE-51EC2A9E54AC](https://github.com/user-attachments/assets/8f306106-4765-40af-9ab0-978338e4d9c1)

![54148CDB-6652-4603-AA08-0B3261F06A77](https://github.com/user-attachments/assets/1afad3b6-f93c-4345-88c8-2dd8c5b684c8)


Yes its something with linux on phones .. i posted my fix because i saw alot people having same issue .. thanks for this great tool

**Comment by dr1408** [comment]
> ![DEAF021F-8696-42CC-A5CE-51EC2A9E54AC](https://private-user-images.githubusercontent.com/39735654/380102636-8f306106-4765-40af-9ab0-978338e4d9c1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDk2NTcsIm5iZiI6MTcyOTg0OTM1NywicGF0aCI6Ii8zOTczNTY1NC8zODAxMDI2MzYtOGYzMDYxMDYtNDc2NS00MGFmLTlhYjAtOTc4MzM4ZTRkOWMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwOTQyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTE1NjEzODQ3ZGM4YjY4NTgxYTYzMWE0YjlmNGVlZGUwZWViMDExM2Y0ODhlNTdjYmZhZDhkMzhmN2U4OTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6Uf063LA-oiEpbooFC8T_QMWwX55PglcX0u9UYmxoyU)
> 
![08D93D6F-2551-4F98-9B4F-8152209887C7](https://github.com/user-attachments/assets/60a9ec5b-d43f-40b9-93b7-83efd8a56042)


> Yes its something with linux on phones .. i posted my fix because i saw alot people having same issue .. thanks for this great tool

**Comment by dr1408** [comment]
Sorry if you can delete my comments i tried to edit but i couldnt i posted photos for http sniff

**Comment by buffermet** [comment]
No worries, I have looked at the netstat output in the previous issue that you posted, and it shows me that you don't have a gateway assigned (see output below).

I can see that you only have an IPv6 gateway (Next Hop) assigned to the rmnet interface, which are used for cellular data (not Wi-Fi).

The comment that you shared above (`ip route add default via 192.168.1.1 dev wlan0`) manually assigns the gateway for your wlan0 interface.

This problem can occur when your router is not serving the right gateway information (usually on public mesh networks).

It seems everything is working fine now. Happy hacking :)

```
exec=/usr/bin/netstat args=[-r -n -4 -6] ret_err=<nil> ret_out=
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref  Use If
::/0                           ::                         !n   -1  1 129328 lo
fdd8:2918:e2b8:c900::/64       ::                         UAe  256 1      0 wlan0
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0                                                                        fe80::/64                      ::                         U    256 1      0 wlan0
fe80::/64                      ::                         U    1024 1      0 wlan0                                                                        ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 129328 lo
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1                                                                  ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
fdd8:2918:e2b8:c900::/64       ::                         U    1024 1      0 wlan0                                                                        fe80::/64                      ::                         U    1024 1      0 wlan0
ff00::/8                       ::                         U    1024 1      0 wlan0
::/0                           ::                         !n   -1  1 129328 lo                                                                            ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
fe80::/64                      ::                         U    256 1      0 dummy0                                                                        ::/0                           ::                         U    1024 1      0 dummy0
::/0                           ::                         !n   -1  1 129328 lo
fe80::/64                      ::                         U    256 3     39 rmnet_data0
::/0                           fe80::1dcc:e22d:8776:b0c9  UGDAe 1024 1      0 rmnet_data0
::/0                           ::                         !n   -1  1 129328 lo
fc17:0:72:f7a2::/64            ::                         UA   256 1      0 rmnet_data1
fc17:0:72:f7a2::/64            ::                         U    1024 1      0 rmnet_data1                                                                  fe80::/64                      ::                         U    256 1      0 rmnet_data1
::/0                           fe80::905e:2501:1d1a:6f2e  UGDAe 1024 3     10 rmnet_data1
::/0                           ::                         !n   -1  1 129328 lo                                                                            ::/0                           ::                         !n   -1  1 129328 lo
::/0                           ::                         !n   -1  1 129328 lo
::1/128                        ::                         Un   0   10     83 lo                                                                           fc17:0:72:f7a2:eb9c:301b:c989:26c0/128 ::                         Un   0   4      5 rmnet_data1
fdd8:2918:e2b8:c900:2f73:40cc:7828:9017/128 ::                         Un   0   2      0 wlan0
fdd8:2918:e2b8:c900:847e:56ff:febd:b303/128 ::                         Un   0   2      0 wlan0                                                            fe80::1b68:4d7e:1a8f:a6ba/128  ::                         Un   0   4     24 rmnet_data0
fe80::847e:56ff:febd:b303/128  ::                         Un   0   2      0 wlan0                                                                         fe80::b882:dbff:fe62:a4be/128  ::                         Un   0   2      0 dummy0
fe80::eb9c:301b:c989:26c0/128  ::                         Un   0   3      1 rmnet_data1
ff00::/8                       ::                         U    256 9   1308 dummy0
ff00::/8                       ::                         U    256 6     12 rmnet_data0
ff00::/8                       ::                         U    256 4     10 rmnet_data1                                                                   ff00::/8                       ::                         U    256 7     28 wlan0
::/0                           ::                         !n   -1  1 129328 lo
```

**Comment by buffermet** [comment]
@dr1408 it's also important to note that if that the attack only sometimes works, and that the victim loses connectivity, it is likely because you are too far away, or your antenna is not powerful enough.

**Comment by dr1408** [comment]
Yes defined gateway and I restored default ip tables rule I hope everyone having same issue to understand the problem.. Thanks a lot btw I'm using my internal phone wifi wlan0 and is working fine will try https strip and dns spoof and inform you

**Comment by dr1408** [comment]
![313C256D-AE9E-49B4-A2BA-D6722BC707F9](https://github.com/user-attachments/assets/d03c9cb5-5f5d-48fb-a609-221c024a3447)

![734C6C1F-C0AC-4DF6-8CE4-AC9AE819796F](https://github.com/user-attachments/assets/4b972010-e2ca-4787-9342-dcb495cdd536)

Dns spoof worked fine also and I was able to capture password on my server.. Target was iPhone it didn't show any security warning
