### ISSUE TITLE
[Bug]Not intercepting any http/https sniffs

### ISSUE THREAD

**Issue by KillzTheSpy2** [bettercap/bettercap#1147]
The net.sniff wont log any websites i visit on the arp spoofed device.
Also the net.probe doesn't show the right ip, it shows the ipv6 address.

### Environment

bettercap v2.33.0
kali GNU/Linux Rolling (Gnome version 47, linux 6.11.2-amd64, kali linux)
I am doing these commands:
```
sudo bettercap
net.probe on
net.show
set arp.spoof.targets 192.168.0.175
arp.spoof on
net.sniff on
```
Heres the full terminal output: https://pastebin.com/quWJQVre

### Steps to Reproduce

1. *net.probe*
2. *set arp.spoof.targets = 192.168.0.175*
3. *arp.spoof on*
4. *net.sniff on*

**Expected behavior:** *That it shows what websites the device is visiting.*

**Actual behavior:** *Showed none of the websites i was visiting*

P.S:
The whole time the arp.spoof is on, on the spoofed device, i was opening new tabs to testing.com, i think i opened abt 6 or 7 in total. I also redacted any identifying information, like mac addresses, and i renamed the device to MACBOOK-1 because the actual name is identifying information.

**Comment by buffermet** [comment]
```sh
set events.stream.http.request.dump true
set events.stream.http.response.dump true
# set events.stream.http.format.hex false
events.stream off
events.stream on
```
