### ISSUE TITLE
Dns Spoofing works only for the first time and then it malfunctions

### ISSUE THREAD

**Issue by Manas-Kishore-Dev** [bettercap/bettercap#1148]
Please open a new issue and provide all the requested information. I'll help you figure out the problem.

_Originally posted by @buffermet in https://github.com/bettercap/bettercap/issues/418#issuecomment-2465304297_

**Comment by buffermet** [comment]
You just deleted the issue template instead of filling in the information...

What am I supposed to do with no information?

**Comment by Manas-Kishore-Dev** [comment]
Sorry
Actually I am new and don't have the much experience, I will learn and try to do as you told .
