### ISSUE TITLE
Handshakes save to parent directory of wifi.handshakes.file when aggregate == false

### ISSUE THREAD

**Issue by Sniffleupagus** [bettercap/bettercap#1149]
When wifi.handshakes.aggregate = false, and wifi.handshakes.file is set to the directory where they should be stored, they are actually stored a directory above.

In modules/wifi/wifi_recon_handshakes.go, line 29 (v 2.40.0), it gets the path.Dir(shakesFileName), which is the parent dir.  This makes bettercap 2.40.0 not backwards compatible with pwnagotchi, which specifies the directory in wifi.handshakes.file.

### Environment

* Bettercap version you are using ( `bettercap -version` ). 2.40.0
* OS version and architecture you are using.  Raspberry Pi 5, Linux fifteenptseven 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
* Go version if building from sources.  go1.23.2
* Command line arguments you are using. /usr/local/bin/bettercap -no-colors -caplet pwnagotchi-manual -iface wlan0mo
* Caplet code you are using or the interactive session commands. caplet is standard pwnagotchi-manual caplet

No debug output included.  The pcap files go into /root when the variable is set to /root/handshakes by pwnagotchi.

### Steps to Reproduce

1. Replace bettercap on a pwnagotchi with v 2.40.0
2. Restart pwnagotchi and bettercap (systemctl restart bettercap pwnagotchi)
3. Wait for handshake
4. Wonder where the file went

**Expected behavior:** *What you expected to happen*
I expected them to go into /root/handshakes, as was tradition.

**Actual behavior:** *What actually happened*
Handshakes went into /root instead.  The path.Dir(shakesFileName) in getHandshakFileFor() drops the last path element, so it stores them a directory above. By commenting out the "parentDir" line and using shakesFileName in the path.Join, the old behavior is restored.

I do not know the intention with the change. Perhaps further modifying the code to use shakesFileName as is if it is a directory, and use path.Dir if it refers to a file instead would do what you intended and keep backwards compatibility.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by buffermet** [comment]
Feel free to send a pull request
