### ISSUE TITLE
No IPv6 addressing on interface causes bettercap panic condition at runtime in compiled binary and docker version [with fix]

### ISSUE THREAD

**Issue by theweefies** [bettercap/bettercap#1152]
---

*Description of the bug or feature request*

### Environment
* bettercap v2.40.0 (built for linux amd64 with go1.23.3)
- AND -
* bettercap v2.40.0 (built for linux amd64 with go1.22.9)(docker)

* Linux laptop 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
* go version go1.23.3 linux/amd64
* Docker version 27.2.0, build 3ab4256

### Commands
* sudo ./bettercap -eval "http-ui"
* sudo docker run -it --privileged --net=host bettercap/bettercap

### Interface
3: wlp170s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether XX:XX:XX:ec:2e:d0 brd ff:ff:ff:ff:ff:ff
    inet 192.168.68.64/22 brd 192.168.68.255 scope global dynamic wlp170s0
       valid_lft 4855sec preferred_lft 4855sec

# built from source (latest)

* This is a panic at runtime
### docker debug:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bettercap v2.40.0 (built for linux amd64 with go1.22.9) [type 'help' for a list of commands]

192.168.68.0/22 > 192.168.68.64  » [23:22:17] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
192.168.68.0/22 > 192.168.68.64  » [23:22:17] [sys.log] [dbg] creating capture for 'wlp170s0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
192.168.68.0/22 > 192.168.68.64  » [23:22:17] [sys.log] [dbg] exec=/bin/netstat args=[-r -n -4 -6] ret_err=exit status 1 ret_out=/bin/netstat: unrecognized option: 4
BusyBox v1.36.1 (2024-06-10 07:11:47 UTC) multi-call binary.

Usage: netstat [-ral] [-tuwx] [-enWp]

Display networking information

	-r	Routing table
	-a	All sockets
	-l	Listening sockets
		Else: connected sockets
	-t	TCP sockets
	-u	UDP sockets
	-w	Raw sockets
	-x	Unix sockets
		Else: all socket types
	-e	Other/more information
	-n	Don't resolve names
	-W	Wide display
	-p	Show PID/program name for sockets

192.168.68.0/22 > 192.168.68.64  » [23:22:17] [sys.log] [dbg] FindGateway(wlp170s0): nothing found :/
192.168.68.0/22 > 192.168.68.64  » [23:22:17] [sys.log] [war] Could not detect gateway.
192.168.68.0/22 > 192.168.68.64  » [23:22:17] [mod.started] events.stream
192.168.68.0/22 > 192.168.68.64  » panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa0cc20]

goroutine 85 [running]:
net.networkNumberAndMask(0xc000114fd8?)
	/usr/local/go/src/net/ip.go:425
net.(*IPNet).Contains(0x0?, {0xc0005dda5a, 0x4, 0xc0005dda5a?})
	/usr/local/go/src/net/ip.go:449 +0x25
github.com/bettercap/bettercap/v2/packets.(*Queue).worker(0xc0000ea840)
	/go/src/github.com/bettercap/bettercap/packets/queue.go:214 +0x2da
created by github.com/bettercap/bettercap/v2/packets.NewQueue in goroutine 1
	/go/src/github.com/bettercap/bettercap/packets/queue.go:78 +0x29f
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### standalone binary debug (compiled from source)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bettercap v2.40.0 (built for linux amd64 with go1.23.3) [type 'help' for a list of commands]

[23:32:56] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
[23:32:56] [sys.log] [dbg] creating capture for 'wlp170s0' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:-10ms}
[23:32:56] [sys.log] [dbg] exec=/usr/bin/netstat args=[-r -n -4 -6] ret_err=<nil> ret_out=Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.68.1    0.0.0.0         UG        0 0          0 wlp170s0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.68.0    0.0.0.0         255.255.252.0   U         0 0          0 wlp170s0
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
::1/128                        ::                         U    256 1     0 lo
::/0                           ::                         !n   -1  1     0 lo
::1/128                        ::                         Un   0   18     0 lo
ff00::/8                       ::                         U    256 8     0 wlp170s0
::/0                           ::                         !n   -1  1     0 lo

[23:32:56] [sys.log] [dbg] exec=/usr/sbin/ip args=[neigh] ret_err=<nil> ret_out=192.168.68.62 dev wlp170s0 lladdr XX:XX:XX:7e:f8:63 STALE
192.168.68.1 dev wlp170s0 lladdr XX:XX:XX:3b:32:99 REACHABLE
fe80::217:88ff:fe24:985f dev wlp170s0 lladdr XX:XX:XX:24:98:5f STALE
fe80::1484:6161:4ca9:f797 dev wlp170s0 lladdr XX:XX:XX:4e:f1:31 STALE
fe80::4aa6:b8ff:fef4:1b6a dev wlp170s0 lladdr XX:XX:XX:f4:1b:6a STALE
fe80::4aa6:b8ff:feea:8a92 dev wlp170s0 lladdr XX:XX:XX:ea:8a:92 STALE
fe80::10dd:9941:745a:aa90 dev wlp170s0 lladdr XX:XX:XX:a6:6f:a2 STALE
fe80::8e79:f5ff:fe7e:f863 dev wlp170s0 lladdr XX:XX:XX:7e:f8:63 STALE

[23:32:56] [sys.log] [dbg] gateway is 192.168.68.1[XX:XX:XX:3b:32:99]
[23:32:56] [sys.log] [inf] gateway monitor started ...
[23:32:56] [sys.log] [dbg] exec=/usr/bin/netstat args=[-r -n -4 -6] ret_err=<nil> ret_out=Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.68.1    0.0.0.0         UG        0 0          0 wlp170s0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.68.0    0.0.0.0         255.255.252.0   U         0 0          0 wlp170s0
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
::1/128                        ::                         U    256 1     0 lo
::/0                           ::                         !n   -1  1     0 lo
::1/128                        ::                         Un   0   18     0 lo
ff00::/8                       ::                         U    256 8     0 wlp170s0
::/0                           ::                         !n   -1  1     0 lo

[23:32:56] [mod.started] events.stream
[23:32:56] [mod.started] api.rest
[23:32:56] [mod.started] api.rest
[23:32:56] [mod.started] http.server
192.168.68.0/22 > 192.168.68.64  » [23:32:56] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.68.0/22 > 192.168.68.64  » [23:32:56] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.68.0/22 > 192.168.68.64  » panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa675e0]

goroutine 85 [running]:
net.networkNumberAndMask(0xc00095c000?)
	/usr/local/go/src/net/ip.go:426
net.(*IPNet).Contains(0x0?, {0xc00095607e, 0x4, 0xc00095607e?})
	/usr/local/go/src/net/ip.go:450 +0x25
github.com/bettercap/bettercap/v2/packets.(*Queue).worker(0xc000150840)
	/mnt/backup/bettercap/packets/queue.go:222 +0x415
created by github.com/bettercap/bettercap/v2/packets.NewQueue in goroutine 1
	/mnt/backup/bettercap/packets/queue.go:78 +0x29f

### Steps to Reproduce

1. Simply running the command to start bettercap (regardless of options) creates this scenario.

### Problematic Code
queue.go - specifically starting at line 179:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
func (q *Queue) worker() {
	for pkt := range q.srcChannel {
		if !q.active {
			return
		}

		q.trackProtocols(pkt)

		pktSize := uint64(len(pkt.Data()))

		q.TrackPacket(pktSize)

		// decode eth and ipv4/6 layers
		leth := pkt.Layer(layers.LayerTypeEthernet)
		lip4 := pkt.Layer(layers.LayerTypeIPv4)
		lip6 := pkt.Layer(layers.LayerTypeIPv6)
		if leth != nil && (lip4 != nil || lip6 != nil) {
			var srcIP, dstIP net.IP
			if lip4 != nil {
				ip4 := lip4.(*layers.IPv4)
				srcIP = ip4.SrcIP
				dstIP = ip4.DstIP
			} else {
				ip6 := lip6.(*layers.IPv6)
				srcIP = ip6.SrcIP
				dstIP = ip6.DstIP
			}

			// here we try to discover new hosts
			// on this lan by inspecting packets
			// we manage to sniff
			eth := leth.(*layers.Ethernet)
			
			// something coming from someone on the LAN
			isFromMe := q.iface.IP.Equal(srcIP) || q.iface.IPv6.Equal(srcIP)
			isFromLAN := q.iface.Net.Contains(srcIP) || q.iface.Net6.Contains(srcIP)
			if !isFromMe && isFromLAN {
				meta := q.getPacketMeta(pkt)
				q.trackActivity(eth, srcIP, meta, pktSize, true)
			}

			// something going to someone on the LAN
			isToMe := q.iface.IP.Equal(dstIP) || q.iface.IPv6.Equal(dstIP)
			isToLAN := q.iface.Net.Contains(dstIP) || q.iface.Net6.Contains(dstIP)
			if !isToMe && isToLAN {
				q.trackActivity(eth, dstIP, nil, pktSize, false)
			}
		}
	}
}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Condition
* what created this condition is not having IPv6 address assigned to the interface. I initially noticed that when stopping Network Manager and managing network connections manually (manually running wpa_supplicant and manually running dhcp client to set up addressing) could create a situation in which an interface is not setup with IPv6 addressing. This reliably created this error/panic condition. Starting NetworkManager and allowing managed interface setup avoided this panic condition reliably. 

### Fix
* Modification of worker function in queue.go to perform nil check against g.iface.IPv6 and avoid calling Contains function from ip.go fixes this condition:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
func (q *Queue) worker() {
	for pkt := range q.srcChannel {
		if !q.active {
			return
		}

		q.trackProtocols(pkt)

		pktSize := uint64(len(pkt.Data()))

		q.TrackPacket(pktSize)

		// decode eth and ipv4/6 layers
		leth := pkt.Layer(layers.LayerTypeEthernet)
		lip4 := pkt.Layer(layers.LayerTypeIPv4)
		lip6 := pkt.Layer(layers.LayerTypeIPv6)
		if leth != nil && (lip4 != nil || lip6 != nil) {
			var srcIP, dstIP net.IP
			if lip4 != nil {
				ip4 := lip4.(*layers.IPv4)
				srcIP = ip4.SrcIP
				dstIP = ip4.DstIP
			} else {
				ip6 := lip6.(*layers.IPv6)
				srcIP = ip6.SrcIP
				dstIP = ip6.DstIP
			}

			// here we try to discover new hosts
			// on this lan by inspecting packets
			// we manage to sniff
			eth := leth.(*layers.Ethernet)
			
			// something coming from someone on the LAN
			isFromMe := q.iface.IP.Equal(srcIP) || (q.iface.IPv6 != nil && q.iface.IPv6.Equal(srcIP))
			isFromLAN := q.iface.Net.Contains(srcIP) || (q.iface.Net6 != nil && q.iface.Net6.Contains(srcIP))
			if !isFromMe && isFromLAN {
				meta := q.getPacketMeta(pkt)
				q.trackActivity(eth, srcIP, meta, pktSize, true)
			}

			// something going to someone on the LAN
			isToMe := q.iface.IP.Equal(dstIP) || (q.iface.IPv6 != nil && q.iface.IPv6.Equal(dstIP))
			isToLAN := q.iface.Net.Contains(dstIP) || (q.iface.Net6 != nil && q.iface.Net6.Contains(dstIP))
			if !isToMe && isToLAN {
				q.trackActivity(eth, dstIP, nil, pktSize, false)
			}
		}
	}
}
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by buffermet** [comment]
Thanks for your report and fix.
