### ISSUE TITLE
Web UI not working - docker on windows

### ISSUE THREAD

**Issue by peter-archer** [bettercap/bettercap#1155]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). - bettercap v2.40.0
* OS version and architecture you are using. - WIndows 11

docker run -it --privileged --net=host bettercap/bettercap -eval "ui on"

![image](https://github.com/user-attachments/assets/cb32ef80-51a5-4129-848e-f56914dbc208)
![image](https://github.com/user-attachments/assets/6aeba7c8-761e-4a32-bf5b-0e0b610da5c1)

Am I missing something obvious here?

**Comment by buffermet** [comment]
You might need to expose these ports on your containerized docker environment so they are accessible on your Windows environment:

`docker run -p 8080:8080 -p 8081:8081 <options>`

**Comment by buffermet** [comment]
I see you shouldn't need to expose ports since you're using --net=host

Can you give us full debug logs by using the `-debug` flag?

Maybe it could be an extension or browser proxy configuration?

**Comment by peter-archer** [comment]
@buffermet 
![image](https://github.com/user-attachments/assets/894125d2-a7dc-41c8-939b-cdc24b2d62d7)

Have tried using edge as well, no proxy server
Please let me know if you need anything else

**Comment by peter-archer** [comment]
Also just tried on another pc and got the same result

**Comment by buffermet** [comment]
Did you try `caplets.update; ui.update; ui on` ?

**Comment by buffermet** [comment]
This seems to be a known issue. See https://github.com/bettercap/bettercap/issues/590

There appears to be a possible solution: https://github.com/bettercap/bettercap/issues/590#issuecomment-735497578
