### ISSUE TITLE
Usage Enchancement

### ISSUE THREAD

**Issue by jinfagang** [bettercap/bettercap#116]
Thanks for this awesome repo! After a simple around of github and org sites, can not found any usage tutorials or how to use it. Anywhere could I found a tutor or something indicates me to start with rather than install this?

**Comment by b4dnewz** [comment]
there is a [29 page](https://github.com/bettercap/bettercap/wiki) project wiki to start with.

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853731-7b6934de-1d6f-11e8-9083-37ff9f3c40f7.jpg)
