### ISSUE TITLE
Unable to log into UI / lack of documentation

### ISSUE THREAD

**Issue by pavelschon** [bettercap/bettercap#1163]
Documentation says:
![image](https://github.com/user-attachments/assets/636a17b2-e044-41e5-a4eb-4beca9e142fe)
So I do that and got error:
```
» [21:06:26] [sys.log] [err] error while running 'ui on': unknown or invalid syntax "ui on", type help for the help menu.
```

After digging into it I learned that I have to install caplets and update ui to the latest. Documentation does not say that.

Finally, I learned that I have to run `http-ui`

```
» [21:07:47] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
» [21:07:47] [sys.log] [inf] http.server starting on http://127.0.0.1:80
```

After opened the website, I got this:

![image](https://github.com/user-attachments/assets/98ccf443-99e6-4d37-a560-31ad4aa8e996)

Went into console and tried to set up rest credentials like this:
```
» set api.rest.username admin
» set api.rest.password password
» [21:12:24] [sys.log] [war] api.rest Unauthorized authentication attempt from 127.0.0.1:49668 to /api/session?from=
» set api.rest off
» set api.rest on
» [21:12:42] [sys.log] [war] api.rest Unauthorized authentication attempt from 127.0.0.1:49668 to /api/session?from=
```

But still cannot log into the app. What I should fill there in order to log into the app?
To my eyes there's is a lack of clear step-by-step documentation for a newbie like me.

### Environment

* Bettercap version you are using ( `bettercap -version` ). **v2.24.1**
* OS version and architecture you are using. **Kali**
* Go version if building from sources. **go1.23.4**
* Command line arguments you are using. 
* Caplet code you are using or the interactive session commands.

**Comment by buffermet** [comment]
> » [21:06:26] [sys.log] [err] error while running 'ui on': unknown or invalid syntax "ui on", type help for the help menu.

Seems like whatever installer you used is not following the correct procedures.

I cannot reproduce this issue when installing from source:

```
bettercap v2.40.0 (built for linux amd64 with go1.23.4) [type 'help' for a list of commands]

192.168.1.0/24 > 192.168.1.13  » [20:08:14] [sys.log] [inf] gateway monitor started ...
192.168.1.0/24 > 192.168.1.13  » ui on
[20:08:15] [sys.log] [inf] ui starting api.rest as a requirement for ui
```
You can fix this problem by installing from source.

Please let us know how you installed bettercap. It seems more people are having issues when using package managers.

**Comment by pavelschon** [comment]
I used
```
sudo apt install golang
go install github.com/bettercap/bettercap@latest
```
