### ISSUE TITLE
Bug on PATH

### ISSUE THREAD

**Issue by fcafra** [bettercap/bettercap#117]
Hi Simone, 

~/go/bin# ./bettercap -caplet /home/App/bettercap-caplets-modules/http-req-dump.cap  -eval "set arp.spoof.targets MYTARGET"

[10:38:55] [sys.log] [inf] Loading proxy script caplets/http-req-dump.js ...
172.30.1.0/24 > 172.30.1.129  » [10:38:55] [sys.log] [err] Error while runnig caplet /home/App/bettercap-caplets-modules/http-req-dump.cap: open caplets/http-req-dump.js: no such file or directory

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853724-743661e6-1d6f-11e8-8959-cd11ffadf8e0.jpg)
