### ISSUE TITLE
undefined: sort.Slice

### ISSUE THREAD

**Issue by gcoloz** [bettercap/bettercap#118]
Debian 9, 64bit, kernel 4.9.0-4

GOPATH set, libpcap-dev installed

root@devops:~# go get github.com/bettercap/bettercap
# github.com/bettercap/bettercap/session
go/src/github.com/bettercap/bettercap/session/events.go:107: undefined: sort.Slice
go/src/github.com/bettercap/bettercap/session/session.go:360: undefined: sort.Slice

Is it me or something is missing?

**Comment by evilsocket** [comment]
Use Go > 1.8 and **RTFM**

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853719-6e8d8738-1d6f-11e8-9384-920ec767130e.jpg)
