### ISSUE TITLE
no offense but how the fuck is GO better than python ?! -_-

### ISSUE THREAD

**Issue by its0x08** [bettercap/bettercap#119]
### Prerequisites

* [x ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x ] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [x ] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [x ] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description
GO is fucked up never worked for me ....!!!!

*Description of the bug or feature request*
root@kaLi:~/Desktop/scripts/bettercap# go get github.com/bettercap/bettercap
# runtime
/usr/local/go/src/runtime/lfstack_amd64.go:16:45: lfstackPack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:37:45
/usr/local/go/src/runtime/lfstack_amd64.go:20:51: lfstackUnpack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:41:33
/usr/local/go/src/runtime/os_linux.go:27:16: _FUTEX_WAIT redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:21:16
/usr/local/go/src/runtime/os_linux.go:28:16: _FUTEX_WAKE redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:22:16
/usr/local/go/src/runtime/os_linux.go:36:46: futexsleep redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:30:46
/usr/local/go/src/runtime/os_linux.go:67:36: futexwakeup redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:61:36
/usr/local/go/src/runtime/os_linux.go:83:21: getproccount redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:77:21
/usr/local/go/src/runtime/os_linux.go:112:26: _CLONE_VM redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:104:26
/usr/local/go/src/runtime/os_linux.go:113:26: _CLONE_FS redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:105:26
/usr/local/go/src/runtime/os_linux.go:114:26: _CLONE_FILES redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:106:26
/usr/local/go/src/runtime/os_linux.go:114:26: too many errors

### Environment
Linux kaLi 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

Please provide:

* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using (if any).
* Interactive session commands you are using (if any).
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
go get github.com/bettercap/bettercap

2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*
install bettercap as u say in the README
**Actual behavior:** *What actually happened*
super shitty !!! 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by zseha** [comment]
Saying no offense doesn't make things any better.

and also: 
https://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=go&lang2=python3

**Comment by evilsocket** [comment]
No offense by **FUCK YOU**.

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853709-690e48c4-1d6f-11e8-8a8e-90625a0d3b59.jpg)
