### ISSUE TITLE
Sir please help hurr hurrr

### ISSUE THREAD

**Issue by GasGeverij** [bettercap/bettercap#120]
Your program is all wrong i'm getting a big bug sir ?

![image](https://user-images.githubusercontent.com/22458893/36847375-6091213c-1d5e-11e8-8d24-2e9a4194d28a.png)

When fix ?

**Comment by wcrigger** [comment]
here we go....🍿

**Comment by b4dnewz** [comment]
@GasGeverij are you trolling or what?

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853692-61bba738-1d6f-11e8-9265-2cf2585aac6f.jpg)
