### ISSUE TITLE
Windows build terminated

### ISSUE THREAD

**Issue by jinfagang** [bettercap/bettercap#121]
## Platform
windows

## Error
Just run go get, and there was an error:

```
# github.com/google/gopacket/pcap
go\src\github.com\google\gopacket\pcap\pcap.go:22:18: fatal error: pcap.h: No such file or directory
compilation terminated.
```

**Comment by evilsocket** [comment]
RTFM

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36853663-550f0ad4-1d6f-11e8-8298-49401dded15f.jpg)
