### ISSUE TITLE
Error running bettercap via docker

### ISSUE THREAD

**Issue by Tin-Voyager** [bettercap/bettercap#122]
### Prerequisites

* [x ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

*Description of the bug or feature request*

Running official docker image and self built via dockerfile and getting the same error message repeated over and over constantly :
“ERROR: path=/sbin/ip args=[neigh] err=signal: segmentation fault (core dumped) out=‘’”

My command line for running docker image: “docker run —rm -it —privileged —net=host bettercap:latest -iface eth0”

I’ve tried the official docker image on 2 different Ubuntu machines and got the same error messages, likewise for building a fresh docker image on both machines. 

### Environment

Please provide:

Ubuntu 16.04.3 x64
Docker CE 17.12

### Steps to Reproduce

1. Run docker image
2. Not see an error message that seems pretty critical. 

**Expected behavior:** *What you expected to happen*

Not see the error message listed above. 

**Actual behavior:** *What actually happened*

Error message constantly repeated. 

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by alexmozzhakov** [comment]
RTFM?

**Comment by Tin-Voyager** [comment]
I’m not really sure how to take that last comment. Is there something in the manual I’ve not read?

**Comment by b4dnewz** [comment]
@Tin-Voyager seems more related to docker, try to run your command with the `-D` flag and paste the output here to see if there is any useful information besides the details you gave

es: `docker -D run --rm -it --privileged --net=host bettercap:latest -iface eth0`
or use `docker log` to get the logs of the execution, I guess.. I'm not very good with docker

**Comment by evilsocket** [comment]
Hi @Tin-Voyager I think you're using an old docker image, `bettercap:latest` does not exist -> https://hub.docker.com/u/bettercap/

**Comment by Tin-Voyager** [comment]
I put “bettercap:latest” as my own name when I made the docker image. I’ll try the images you’ve suggested regardless

**Comment by alexmozzhakov** [comment]
@Tin-Voyager There is a page on docker in manual, which talks about `Using with Docker`

**Comment by Tin-Voyager** [comment]
@evilsocket. I found that by adding “iproute2” to the apk update list for the 2nd stage of the dockerfile resolved my issue. I tried adding it to the 1st stage but this did not work.

**Comment by zanemcca** [comment]
I had the same problem. Using `bettercap/dev` instead of `bettercap/bettercap` resolved the issue for me
