### ISSUE TITLE
wifi.recon

### ISSUE THREAD

**Issue by adolfaka** [bettercap/bettercap#123]
Greetings to your team!
The wifi.recon module can not be used.

I perform the following steps:
1. sudo docker run -it -privileged -net = host bettercap / bettercap
2. wifi.recon on

Conclusion:
[2018-03-02 05:23:39] [err] exec: "iwconfig": executable file not found in $ PATH

3. which iwconfig
Conclusion:
/sbin/iwconfig

OS: Linux sprut 4.14.0-kali3-amd64 # 1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU / Linux
Docker: Docker version 17.12.1-ce, build 7390fc6
GO: go version go1.10 linux / amd64

**Comment by evilsocket** [comment]
Are you running `which iwconfig` inside the docker container or on your pc?

**Comment by alexmozzhakov** [comment]
@evilsocket Probably not, `docker exec CONTAINER ID which iwconfig` gives no output

**Comment by evilsocket** [comment]
Probably not what? I asked which of the two things.

**Comment by alexmozzhakov** [comment]
@evilsocket sorry, probably not inside the docker
