### ISSUE TITLE
Error while trying to install 

### ISSUE THREAD

**Issue by akhilesharora** [bettercap/bettercap#126]
OS Version: Linux arora-N750HU 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Go Version: go version go1.9 linux/amd64
Command:  go get github.com/bettercap/bettercap
Error:
`github.com/google/gopacket/pcap
gocode/src/github.com/google/gopacket/pcap/pcap.go:22:18: fatal error: pcap.h: No such file or directory
compilation terminated.`

**Comment by alexmozzhakov** [comment]
Have you read instructions before publishing the issue? #121

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36894989-8b478d9e-1e0d-11e8-9650-e162e9cdfc69.jpg)
