### ISSUE TITLE
Can't get libpcap working in arch linux

### ISSUE THREAD

**Issue by Blendman974** [bettercap/bettercap#131]
Libpcap is installed on my system (arch linux 64) but when I try to run bettercap I get this error : 
./bettercap_linux_amd64_2.0.0: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory. 
Any solutions ?

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36933563-7eb079c8-1edb-11e8-90d8-dd5020e1291d.jpg)
