### ISSUE TITLE
Go get error

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#132]
On `go version go1.10 darwin/amd64` returns 
`go/src/gopkg.in/sourcemap.v2/mappings.go:8:2: use of internal package not allowed`

**Comment by HaBaLeS** [comment]
`github.com/bettercap/bettercap (download)
github.com/mattn/go-isatty (download)
github.com/bettercap/gatt (download)
github.com/mgutz/logxi (download)
github.com/mattn/go-colorable (download)
github.com/mgutz/ansi (download)
github.com/google/gopacket (download)
github.com/mdlayher/dhcp6 (download)
github.com/bettercap/readline (download)
github.com/dustin/go-humanize (download)
github.com/elazarl/goproxy (download)
github.com/inconshreveable/go-vhost (download)
github.com/malfunkt/iprange (download)
github.com/pkg/errors (download)
github.com/robertkrimen/otto (download)
Fetching https://gopkg.in/sourcemap.v2?go-get=1
Parsing meta tags from https://gopkg.in/sourcemap.v2?go-get=1 (status code 200)
get "gopkg.in/sourcemap.v2": found meta tag get.metaImport{Prefix:"gopkg.in/sourcemap.v2", VCS:"git", RepoRoot:"https://gopkg.in/sourcemap.v2"} at https://gopkg.in/sourcemap.v2?go-get=1
gopkg.in/sourcemap.v2 (download)
github.com/go-sourcemap/sourcemap (download)
../../../gopkg.in/sourcemap.v2/mappings.go:8:2: use of internal package not allowed
`
Same on go version go1.9.2 linux/amd64

**Comment by alexmozzhakov** [comment]
```
github.com/bettercap/bettercap (download)
github.com/mattn/go-isatty (download)
github.com/google/gopacket (download)
github.com/mdlayher/dhcp6 (download)
github.com/bettercap/readline (download)
github.com/dustin/go-humanize (download)
github.com/elazarl/goproxy (download)
github.com/inconshreveable/go-vhost (download)
github.com/malfunkt/iprange (download)
github.com/pkg/errors (download)
github.com/robertkrimen/otto (download)
Fetching https://gopkg.in/sourcemap.v2?go-get=1
Parsing meta tags from https://gopkg.in/sourcemap.v2?go-get=1 (status code 200)
get "gopkg.in/sourcemap.v2": found meta tag get.metaImport{Prefix:"gopkg.in/sourcemap.v2", VCS:"git", RepoRoot:"https://gopkg.in/sourcemap.v2"} at https://gopkg.in/sourcemap.v2?go-get=1
gopkg.in/sourcemap.v2 (download)
github.com/go-sourcemap/sourcemap (download)
go/src/gopkg.in/sourcemap.v2/mappings.go:8:2: use of internal package not allowed

```
I formatted log a little bit

**Comment by tonjo** [comment]
I think I know what went wrong,
this morning a commit on this package: `github.com/robertkrimen/otto` changed the version
from `sourcemap.v1` to `sourcemap.v2`:

    $ git blame file/file.go  |grep gopkg.in/sourcemap
    67b2826a (Eric Reis Figueiredo 2018-03-03 07:15:14 -0300   9) 	"gopkg.in/sourcemap.v2"
    ~/go/src/github.com/robertkrimen/otto (master)$ git diff 67b2826a^..67b2826a -- file/file.go
    diff --git a/file/file.go b/file/file.go
    index 9093206..f2d66f1 100644
    --- a/file/file.go
    +++ b/file/file.go
       @@ -6,7 +6,7 @@ import (
                "fmt"
                "strings"
 
        -       "gopkg.in/sourcemap.v1"
        +       "gopkg.in/sourcemap.v2"
         )
 
An analog change is in file `parser/parser.go`.
sourcemap v.2 seems to be broken since December.

	$ git blame mappings.go |grep github
	8947752a mappings.go  (Vladimir Mihailenco 2017-12-21 11:52:25 +0200   8) 	"github.com/go-sourcemap/sourcemap/internal/base64vlq"

I opened an issue in [sourcemap](https://github.com/go-sourcemap/sourcemap/issues/12)

**Comment by tonjo** [comment]
Now it compiles, maybe my analysis wasn't correct.

**Comment by wcrigger** [comment]
compiles for me now as well.  groovy
