### ISSUE TITLE
ARP spoofing not working

### ISSUE THREAD

**Issue by Leisors** [bettercap/bettercap#133]
As I have written in the title, ARP spoofing just won't work.
I'm using v2.0.0 precompiled on Kali Rolling. The interface is correct and the target IP has been set.
Cache poisoning does work both with ettercap and arpspoof. 
Any ideas?

(Also, I don't know if the two issues could be connected but I'm experiencing random logs of connections and disconnections from the network's endpoints. This is so annoying I have to shut down net.recon as first thing when running bettercap. Should I open another issue about this? )

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36949637-7307ece4-1feb-11e8-9e2d-ca500554d7fe.jpg)
