### ISSUE TITLE
How to get all ips on a local network of other devices?

### ISSUE THREAD

**Issue by jinfagang** [bettercap/bettercap#134]
Hi, biggod, I'm wanna ask one simple question, How to get all ips on a local network of other devices? I'm totally newbie on this, but bettercap seems really cool?

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/36954723-1cbf19a0-2024-11e8-9d82-b21ae524a59e.jpg)
