### ISSUE TITLE
question of https

### ISSUE THREAD

**Issue by vay3t** [bettercap/bettercap#140]
How can I do bypass https in bettercap 2?

**Comment by evs-pn** [comment]
waiting for the cat ... =)

**Comment by larover** [comment]
Unless you create your own or use bettercap's Certificate Authority, then install/import it into each of your target devices/browsers it's not really possible... However it would be great if there are plans to integrate sslstrip2 by LeonardoNve into this version for partial SSL/HSTS bypass.

**Comment by evilsocket** [comment]
![dxne9zvx4aacrod](https://user-images.githubusercontent.com/86922/37030212-70e769f8-213a-11e8-9160-b78dc12de64f.jpg)
