### ISSUE TITLE
net.sniff module net.sniff.local false doesn't give any output #138

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#143]
### Prerequisites

* [ ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ ] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ ] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ ] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

*Description of the bug or feature request*

### Environment

Please provide:

* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using (if any).
* Interactive session commands you are using (if any).
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by wcrigger** [comment]
hey bud you're supposed to fill in the blanks!

**Comment by alexmozzhakov** [comment]
whoops, accidental
