### ISSUE TITLE
net.sniff module with net.sniff.local false doesn't give any output (reopening #138)

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#145]
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

`net.sniff` module only returns output if `net.sniff.local` set to `true`

### Environment

Please provide:

Darwin Kernel Version 16.7.0 x86_64
go version go1.10 darwin/amd64
Caplet :
```
events.ignore endpoint
events.clear
set net.sniff.verbose false
set net.sniff.local false
set net.sniff.filter not arp
set arp.spoof.targets xx:xx:xx:xx:xx:xx,xx:xx:xx:xx:xx:xx,xx:xx:xx:xx:xx:xx,xx:xx:xx:xx:xx:xx
clear
sleep 3
net.show

```
Debug:
```
[xx:xx:xx] [sys.log] [dbg] Parsing MAC xx:xx:xx:xx:xx:xx
[xx:xx:xx] [sys.log] [dbg] Parsing MAC xx:xx:xx:xx:xx:xx
[xx:xx:xx] [sys.log] [inf] Enabling forwarding.
[xx:xx:xx] [mod.started] arp.spoof
[xx:xx:xx] [sys.log] [inf] ARP spoofer started, probing 4 targets.
[xx:xx:xx] [sys.log] [dbg] Sending 60 bytes of ARP packet to 10.114.64.xx:xx:xx:xx:xx:xx:xx
[xx:xx:xx] [sys.log] [dbg] Sending 60 bytes of ARP packet to 10.114.64.xx:xx:xx:xx:xx:xx:xx
[xx:xx:xx] [mod.started] net.sniff
10.114.64.0/24 > 10.114.64.xx  » [xx:xx:xx] [sys.log] [dbg] Unexpected layer type IPv6, skipping packet.
10.114.64.0/24 > 10.114.64.xx  » [xx:xx:xx] [sys.log] [dbg] Sending 60 bytes of ARP packet to 10.114.64.xx:xx:xx:xx:xx:xx:xx.
10.114.64.0/24 > 10.114.64.xx  » [xx:xx:xx] [sys.log] [dbg] Sending 60 bytes of ARP packet to 10.114.64.xx:xx:xx:xx:xx:xx:xx.
10.114.64.0/24 > 10.114.64.xx  » [xx:xx:xx] [sys.log] [dbg] Sending 60 bytes of ARP packet to 10.114.64.xx:xx:xx:xx:xx:xx:xx.
Missing TLS, ignoring events, ARP and Unexpected layer type IPv6
...
```
### Steps to Reproduce

1. Turn arp.spoof on targets
2. Set net.sniff.local to false 
3. Run net.sniff

**Expected behavior:** returning all non-local requests

**Actual behavior:** no output
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Fixed with https://github.com/bettercap/bettercap/commit/24310b5cad51ef5a65a7a75a123b414508fff87f
