### ISSUE TITLE
DefaultPrompt not restored after wpa_handshake caplet

### ISSUE THREAD

**Issue by p0ngbr** [bettercap/bettercap#146]
### Description

When I run the program normally, the default prompt is displayed. But when I load a caplet that modifies the prompt (**wpa_handshake** for example), it does not change, even when I execute the program without any arguments.

### Environment

Arch Linux kernel 4.15.7-1-ARCH
go version go1.10 linux/amd64

### Steps to Reproduce

1. sudo bettercap
2. sudo bettercap -caplet caplets/wpa_handshake.cap *(or any other that changes the default prompt
)*
3. sudo bettercap

**Expected behavior:**
```
$ sudo bettercap
bettercap v2.1 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.5  » quit

$ sudo bettercap -caplet caplets/wpa_handshake.cap
wlan0 » quit

$ sudo bettercap
bettercap v2.1 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.5  »
```

**Actual behavior:**
```
$ sudo bettercap
bettercap v2.1 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.5  » quit

$ sudo bettercap -caplet caplets/wpa_handshake.cap
wlan0 » quit

$ sudo bettercap
bettercap v2.1 (type 'help' for a list of commands)

wlan0 »
```
 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Someone did not read the wiki ( `--env-file ""` ) https://github.com/bettercap/bettercap/wiki/Interactive-Mode ... but yeah by default can be confusing.
