### ISSUE TITLE
implement rainbow support

### ISSUE THREAD

**Issue by picatz** [bettercap/bettercap#15]
This is kind of self-explanatory and arguably less-important than a lot of other features...

## The Dream
If at all possible/feasible: it'd be amazing to have the [old rainbow feature](https://github.com/evilsocket/bettercap/pull/338) carry on with the new version of bettercap.

**Comment by evilsocket** [comment]
It totally goes to the first milestone U.U

**Comment by picatz** [comment]
🌈☁️🤔This'll be interesting.

**Comment by evilsocket** [comment]
I believe the only way is centralizing all the writes ( `modules/events_stream_view.go` + various fmt.Printf ) to a custom Writer (which by default is `os.Stdout`) and modify the buffers before they're wrote.

**Comment by evilsocket** [comment]
since no one took care of this and, joke aparts, it's quite useless, i'm closing.

**Comment by picatz** [comment]
Yeah. I haven't put the effort into working on this. 😓

**Comment by AlmightyFloppyFish** [comment]
`bettercap | lolcat` works

**Comment by alexmozzhakov** [comment]
@AlmightyFloppyFish nice observation  🌈🌈🌈
