### ISSUE TITLE
Linux static build requires glibc version to be consistent with build environment.

### ISSUE THREAD

**Issue by leonardoporpora** [bettercap/bettercap#155]
### Prerequisites

* [ *] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [* ] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ *] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ *] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

*Description of the bug or feature request*

### Environment

Please provide:

* Debian 9
* sudo ./bettercap 

### Steps to Reproduce

1. sudo ./bettercap

bettercap v2.1 (type 'help' for a list of commands)

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f950ea6c7f8]

runtime stack:
runtime.throw(0xc4b0a1, 0x2a)
	/usr/lib/go-1.8/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/lib/go-1.8/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x9903a0, 0xc4203193f8, 0x400001)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc4203193b0 sp=0xc420319370
os/user._Cfunc_mygetpwuid_r(0x0, 0xc42039a9f0, 0x7f94f8000b10, 0x400, 0xc4203a2068, 0x0)
	os/user/_obj/_cgo_gotypes.go:178 +0x4d fp=0xc4203193f8 sp=0xc4203193b0
os/user.lookupUnixUid.func1.1(0x0, 0xc42039a9f0, 0x7f94f8000b10, 0x400, 0xc4203a2068, 0xc4203194a0)
	/usr/lib/go-1.8/src/os/user/lookup_unix.go:100 +0x175 fp=0xc420319450 sp=0xc4203193f8
os/user.lookupUnixUid.func1(0x10)
	/usr/lib/go-1.8/src/os/user/lookup_unix.go:104 +0x50 fp=0xc420319490 sp=0xc420319450
os/user.retryWithBuffer(0xc42039cf10, 0xc420319588, 0xc42039cf10, 0x0)
	/usr/lib/go-1.8/src/os/user/lookup_unix.go:253 +0x2b fp=0xc4203194f8 sp=0xc420319490
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/os/user/lookup_unix.go:105 +0x161 fp=0xc4203195c0 sp=0xc4203194f8
os/user.current(0xd0, 0xffffffffffffffff, 0x6)
	/usr/lib/go-1.8/src/os/user/lookup_unix.go:49 +0x2f fp=0xc4203195f0 sp=0xc4203195c0
os/user.Current(0xc15000, 0x1, 0xbbdff4)
	/usr/lib/go-1.8/src/os/user/lookup.go:9 +0x22 fp=0xc420319618 sp=0xc4203195f0
github.com/bettercap/bettercap/core.ExpandPath(0xc15000, 0x13, 0x1, 0x1, 0x2, 0xc420397300)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/core/core.go:70 +0x8c fp=0xc420319670 sp=0xc420319618
github.com/bettercap/bettercap/session.(*Session).setupReadline(0xc420334000, 0xc4203c6000, 0xc42039c400)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/session/session.go:214 +0xc29 fp=0xc420319bc0 sp=0xc420319670
github.com/bettercap/bettercap/session.(*Session).Start(0xc420334000, 0xc42037a4d0, 0x10)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/session/session.go:405 +0x5c6 fp=0xc420319ca8 sp=0xc420319bc0
main.main()
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/main.go:58 +0xe79 fp=0xc420319f88 sp=0xc420319ca8
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420319fe0 sp=0xc420319f88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420319fe8 sp=0xc420319fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.8/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/lib/go-1.8/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/lib/go-1.8/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [syscall, locked to thread]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex_escaping(0x35b9550, 0xc42033d440, 0xc42033d448, 0x0)
	github.com/google/gopacket/pcap/_obj/_cgo_gotypes.go:452 +0x4d
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked.func1(0x35b9550, 0xc42033d440, 0xc42033d448, 0x0)
	/home/evilsocket/gocode/src/github.com/google/gopacket/pcap/pcap.go:390 +0x74
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc42033d400, 0xc4200266b0, 0x0, 0x0)
	/home/evilsocket/gocode/src/github.com/google/gopacket/pcap/pcap.go:390 +0x69
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc42033d400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/evilsocket/gocode/src/github.com/google/gopacket/pcap/pcap.go:327 +0x77
github.com/google/gopacket.(*PacketSource).NextPacket(0xc420355980, 0xc5d440, 0xc42033faa0, 0x0, 0x0)
	/home/evilsocket/gocode/src/github.com/google/gopacket/packet.go:795 +0x48
github.com/google/gopacket.(*PacketSource).packetsToChannel(0xc420355980)
	/home/evilsocket/gocode/src/github.com/google/gopacket/packet.go:812 +0x5d
created by github.com/google/gopacket.(*PacketSource).Packets
	/home/evilsocket/gocode/src/github.com/google/gopacket/packet.go:835 +0x94

goroutine 7 [chan receive]:
github.com/bettercap/bettercap/packets.(*Queue).worker(0xc420369720)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/packets/queue.go:145 +0x80
created by github.com/bettercap/bettercap/packets.NewQueue
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/packets/queue.go:75 +0x397

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f950d18df50, 0x72, 0x4)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4203f4068, 0x72, 0x12cd4e0, 0x12c7288)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4203f4068, 0xc4203ba400, 0x200)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4203f4000, 0xc4203ba400, 0x200, 0x200, 0x0, 0x12cd4e0, 0x12c7288)
	/usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4203d4030, 0xc4203ba400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/net.go:181 +0x70
net.dnsRoundTripUDP(0x12cede0, 0xc4203d4030, 0xc4203ee080, 0x487ce2, 0x5aa00dff, 0x4d6582211f3dfc4d)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:64 +0xed
net.(*UDPConn).dnsRoundTrip(0xc4203d4030, 0xc4203ee080, 0x12fd480, 0x12fd480, 0x0)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:47 +0x41
net.exchange(0x12d3560, 0xc420010238, 0xc4203dc0f0, 0xe, 0xc4203d22e0, 0x19, 0xc42003000c, 0x12a05f200, 0x0, 0x0, ...)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:170 +0x425
net.tryOneName(0x12d3560, 0xc420010238, 0xc4203e40a0, 0xc4203d22e0, 0x19, 0xc, 0xc4203dc38b, 0xc4203dc38b, 0x1, 0xbbdfb5, ...)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:193 +0x122
net.lookup(0x12d3560, 0xc420010238, 0xc4203d22e0, 0x19, 0xc, 0x0, 0x0, 0x0, 0xc4203dc074, 0xa, ...)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:331 +0x15b
net.goLookupPTR(0x12d3560, 0xc420010238, 0xc4203be00c, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/dnsclient_unix.go:566 +0xcf
net.(*Resolver).lookupAddr(0x184a4b6, 0x12d3560, 0xc420010238, 0xc4203be00c, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/lookup_unix.go:168 +0x5c
net.LookupAddr(0xc4203be00c, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/lookup.go:326 +0x5d
github.com/bettercap/bettercap/network.NewEndpoint.func1(0xc4203c6000)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/network/lan_endpoint.go:67 +0x3c
created by github.com/bettercap/bettercap/network.NewEndpoint
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/network/lan_endpoint.go:73 +0x8e

**Comment by leonardoporpora** [comment]
I'm using the precompiled version (https://github.com/bettercap/bettercap/releases/download/v2.1/bettercap_linux_amd64_2.1.zip)

**Comment by evilsocket** [comment]
wow this is weird, is it systematic? The more info you can give me about your setup the better as I'll probably need to prepare a VM in order to reproduce this behaviour.

**Comment by leonardoporpora** [comment]
Yes it's systematic now. Let me know the info you need. I'm an Italian student so if you want to speak in Italian is the same for me :)

**Comment by evilsocket** [comment]
Just a plain Debian 9 on amd64?

**Comment by leonardoporpora** [comment]
Yes. Linux Leo-deb 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux

**Comment by evilsocket** [comment]
It seems to be related to https://github.com/golang/go/issues/13470

**Comment by leonardoporpora** [comment]
Yes

**Comment by evilsocket** [comment]
So basically: since the binary is built statically you can only run it if you have the same glibc version, otherwise it'll just crash ... so I believe in your case it's just easier to compile from source.

**Comment by evilsocket** [comment]
Interestingly, now I have two options: either i completely disable static builds (meaning users will have to symlink the correct version of libpcap.so.N), or I just distribute binaries for Ubuntu 17.10 amd64 (my build environment) and let everyone else build their own ...

**Comment by evilsocket** [comment]
https://twitter.com/bettercap/status/971713315012571136

**Comment by edermi** [comment]
Suggestion 1: You may use docker for building the static binaries - it's little overhead and you can share the build script across different distros, just using a different base image. Since Debian has go < 1.8 in it's repos, the static build saved me lots of time and I'd love if you keep it
Suggestion 2: Use an [AppImage](https://appimage.org/), it's quite well supported and to my own surprise I never had problems with it.

**Comment by leonardoporpora** [comment]
@edermi vote here https://www.strawpoll.me/15225259

**Comment by edermi** [comment]
@leonardoporpora I saw the vote, voted for other and wrote a comment to the issue ;). I think dropping static builds as well as providing only Ubuntu binaries are both not the best options. In my opinion, the availability of static binaries is one major reason for the huge success of bettercap 2.

**Comment by evilsocket** [comment]
@edermi not really considering that installing libpcap (or just shipping libpcap.so with the binary itself) can be done on literally every OS very easily.

I reverted to non static builds for linux/amd64 for the moment, I believe users can easily handle this:

    $ ldd $GOPATH/bin/bettercap
         
    linux-vdso.so.1 =>  (0x00007fff6c3d3000)
    libpcap.so.1 => /usr/lib/libpcap.so.1 (0x00007f424ddef000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f424dbd0000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f424d7f0000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f424e030000)

**Comment by evilsocket** [comment]
@edermi also the problem is not building static binaries, but making them work on different platforms ... Docker wouldn't change a thing (unless I create N Docker instances where N=number of different distros I want to support ... that is not gonna happen ^_^) as for AppImage idk, will check it out.

**Comment by q2dg** [comment]
Only for the record: in Ubuntu 17.10, Bettercap 2.2 gives this error: "error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory" The real file is /usr/lib/x86_64-linux-gnu/libpcap.so.1.8.1 so soft-linking "libpcap.so.1" to it solves the problem...but it's ugly.
Thanks a lot, anyway.

**Comment by evilsocket** [comment]
life is ugly
