### ISSUE TITLE
ble.enum not working

### ISSUE THREAD

**Issue by naltun** [bettercap/bettercap#156]
### Description

```
>> ble.recon on
>> ble.enum <mac_addr>
>> [sys.log] [err] Module is already running.
# I wait a few minutes
>> ble.enum <mac_addr>
>> [sys.log] [err] An enumeration for <mac_addr> is already running, please wait.
```
The problem is, `ble.enum` gives an error when I first initiate it, appearing to already be performing an enumeration. This 'enumeration' never completes, prohibiting me from actually performing a BLE enumeration.

### Environment

Please provide:
* Antergos Linux x86_64
* go version go1.10 linux/amd64
* `$ sudo bettercap # => No arguments`
* Interactive session commands: `ble.recon on && ble.enum <mac_addr>`

### Steps to Reproduce

1. `ble.recon on`
2. `ble.enum <mac_addr> # => [sys.log] [err] Module is already running.`
3. `ble.enum <mac_addr> # => [sys.log] [err] An enumeration for <mac_addr> is already running, please wait.`

**Expected behavior:** *What you expected to happen*
I should be able to perform BLE enumeration

**Actual behavior:** *What actually happened*
I am given an error stating I am already performing a `ble.enum`

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by naltun** [comment]
Also:

```
>> active
ble.recon (Bluetooth Low Energy devices discovery.)  
```
I'm not sure if an active BLE enumeration should be present under `active`; if so, then there's definitely no `ble.enum` going on.

**Comment by evilsocket** [comment]
which bettercap version?
