### ISSUE TITLE
Wifi module ideas

### ISSUE THREAD

**Issue by rb4sh** [bettercap/bettercap#157]
### Prerequisites
Done!

### Description

Hi evilsocket, I was playing with bettercap (amazing tool btw), specifically with the wifi module and there are couple of ideas I had which I think would be nice to see in the tool.

1) When using wifi.show, it would be nice to highlight the AP of which the handshake has been captured.

2) Would be nice to see the list of clients in a separate table similar to the AP table when using wifi.show and not only when you set an AP filter (so you can tailor your attack or check unauthenticated clients).
Including in this client table would also be nice to see what are they probing for.

3) For the wifi.recon.channel default is channel hopping or we can set a specific channel, I think it would be nice to be able to set also more than one channel and hop only between those, ex.: wifi.recon.channel 1, 6 (comma separated)

### Environment
Linux Ubuntu 16.04 LTS
Go 1.10

Just my 2 cents,

Thank you for your work and for reading this.

**Comment by evilsocket** [comment]
Ok, so:

0. Congrats (and thank you!) for being the first one to understand how to use the **Prerequisites** section.
1. That would imply some communication between `net.sniff` and `wifi.recon` ... will think about it.
2. Makes sense.
3. Makes perfect sense.

Thank you for being a normal human being with good ideas and the ability to understand what he/she reads <3

**Comment by rb4sh** [comment]
👍 Thanks man and thank you for your time and help. Keep up the good work!

**Comment by evilsocket** [comment]
Ok so:

1. Still not sure what's the best way to do it without coupling `net.sniff` and `wifi.recon` too much ...
2. Given there's no way to control the size of that list, showing -every- client might result (and probably will in city areas) in a loooooong and unusable console output. The same could be achieved, instead, with something like:

    > set ticker.commands "clear; wifi.recon; wifi.recon BSSID-OF-YOUR-INTEREST; wifi.recon clear"
    > ticker on

This will start the ticker and show both the APs and the clients connected to a given AP.
3. Still makes perfect sense :D

**Comment by yungtravla** [comment]
With `wifi.deauth BSSID` I assume the BSSID could be either an AP or a client?

Could we have the BSSID value comma separated so that we can deauth multiple clients and/or APs at once?

**Comment by rb4sh** [comment]
1. Hmm, I was debugging again the wifi module output, so when the handshake is captured the net.sniff module output is something similar to this:
_[net.sniff.leak.802.11] ....some data...._ Maybe at this point in the sniffer you could pass a flag at the wifi module. Ex. (pseudo code): flag ( bool hs_captured, string AP_BSSID);
So in this case the only communication channel would be that flag and they will still be 2 separate module.

2. Makes sense, however unassociated client won't be shown.
What if we pass as BSSID FF:FF:FF:FF:FF:FF (broadcast) and bettercap in this case filters out everything and shows only unassociated clients with probes? This will start to reduce the list. Also to make the table smaller bettercap can show only 10 (or less) clients based on their signal strength.

3. Nothing to add.

Again, thanks for your commitment to this. Have a nice (coding?) day :P :D

**Comment by evilsocket** [comment]
1. WIP
2. Won't do.
3. Done.

**Comment by evilsocket** [comment]
Actually, won't do `1` neither for one reason, the `net.sniff.leak.802.11` event is not WPA2 handshake specific, but it's triggered by any 802.11 packet that the `net.sniff` module has been used for, so as I said initially it'd make the two things too coupled without adding any real value (given you see the event due to `events.stream` you already know what handshake you got).

Closing as @Matrix86 just pushed 3.
