### ISSUE TITLE
Question on REST API

### ISSUE THREAD

**Issue by SadProcessor** [bettercap/bettercap#158]
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue, but I still want to do it...

### Description

Quick question on API, just to check...

### Environment

Bettercap on RPi3 Kali / Query via REST API (from PowerShell)

### Steps to Reproduce

na

**Expected behavior:** *What you expected to happen*

When querying event with a count limit, is expected behavior to return first n events or last n events?
For now returns firsts. would have expected lasts (maybe). 
![bcapapi1](https://user-images.githubusercontent.com/15706849/37106473-d548dc52-2229-11e8-9a82-1e19947f37f3.png)

--------------------------------------
Also got strange chars in error messages (is it on your side? could also be my encoding, will check)
![bcapapi2](https://user-images.githubusercontent.com/15706849/37106649-449ce49a-222a-11e8-989e-058eea094708.png)

---------------------------------------

for the rest all seems to be working... still testing Powershell API client. Should have it ready shortly.

AWESOME STUFF...
Thanks.

**Comment by evilsocket** [comment]
Yeah it should return the last n events :D As for the chars, those are the base escape sequences I use to color / apply effects on console.
