### ISSUE TITLE
$GOPATH not set

### ISSUE THREAD

**Issue by halekan** [bettercap/bettercap#159]
Have problem when try install bettercap

> root@kali64bit:~# go get github.com/bettercap/bettercap

> package github.com/bettercap/bettercap: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by leonardoporpora** [comment]
Why you never read.... read before bother people...

**Comment by evilsocket** [comment]
![rtfm](https://user-images.githubusercontent.com/86922/37147630-dd9e2e2c-22c7-11e8-8ec9-1ce69a75492c.jpg)
