### ISSUE TITLE
Include go vendoring?

### ISSUE THREAD

**Issue by djerfy** [bettercap/bettercap#161]
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

Include go vendoring with `dep` (https://github.com/golang/dep)?
This is to build the homebrew package for macOS [here](https://github.com/Homebrew/homebrew-core/pull/24955)

### Environment

Please provide:

* Bettercap version you are using: v2.1 (latest)
* OS version and architecture you are using: macOS 10.13.3 (latest)
* Go version if building from sources: go 1.10 (from homebrew)
* Command line arguments you are using.
* Caplet code you are using (if any).
* Interactive session commands you are using (if any).
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

This is not a bug but a proposal for homebrew packaging.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Not sure what this request is about, we already have `make deps` or you can simply `go get ./...` ...

**Comment by evilsocket** [comment]
Added my comment there, will close this as there's absolutely no reason to use an additional tool when the default go installation already manages dependencies.

**Comment by djerfy** [comment]
@evilsocket personally I have no problem on all that, it's just homebrew side because it does not allow go get

**Comment by evilsocket** [comment]
@djerfy and that is nuts unless they don't provide some solid reason for that :D

**Comment by djerfy** [comment]
@evilsocket no idea and yes completely agree with you (all the benefit of go too). I think I will close the pull request at home because I have no other way (unless I clone but not the goal)

**Comment by ilovezfs** [comment]
@evilsocket please see my comment here: https://github.com/Homebrew/homebrew-core/pull/24955#discussion_r173612629

**Comment by evilsocket** [comment]
Done, we now are using `glide` and `vendor` folder has been pushed to the repo.

**Comment by ilovezfs** [comment]
Awesome! Thank you @evilsocket

**Comment by djerfy** [comment]
Thank you i will make the corrections soon

**Comment by evilsocket** [comment]
Thank you guys :)
