### ISSUE TITLE
Bettercap support with nethunter terminal

### ISSUE THREAD

**Issue by rafaleon69** [bettercap/bettercap#166]
### Prerequisites

* [ ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ ] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ ] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ ] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using.

Latest 2.0

* OS version and architecture you are using.

Nougat on nexus 6p
* Go version if building from sources.
* Command line arguments you are using.

./bettercap

* Caplet code you are using (if any).
* Interactive session commands you are using (if any).
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happend

kali:~# ./bettercap
CANNOT LINK EXECUTABLE "./bettercap": library "libpcap.so.1" not found
Aborted

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by rafaleon69** [comment]
I know this issue could be fixed with using termux but I would like to know how to fix it on Nethunter terminal?

Thank you for providing this amazing app to us.

All the best
R.

**Comment by evilsocket** [comment]
RTFM

![rtfm](https://user-images.githubusercontent.com/86922/37242253-7ca77510-2466-11e8-9552-b0e8a74e279e.jpg)
