### ISSUE TITLE
 du: cannot access '*': No such file or directory

### ISSUE THREAD

**Issue by marechok** [bettercap/bettercap#168]
when i want to open bettercap i get a problem like this.

@ Building linux/amd64 ...
./build.sh: line 58: go: command not found
du: cannot access '*': No such file or directory 

What is the wrong with it ?

**Comment by yungtravla** [comment]
Do you have go installed?

**Comment by evilsocket** [comment]
The wrong with it is that you did not read / understand the wiki and you're trying to build bettercap the wrong way.
