### ISSUE TITLE
Is it possible to write the output of events.stream to a file?

### ISSUE THREAD

**Issue by rogersmithboyd** [bettercap/bettercap#169]
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

Write events.stream to a file

### Environment

Please provide:

* Bettercap 2.1
* Raspbian 9 (stretch)
* Go 1.8 linux/arm
* wifi.recon on
  ble.recon on
  net.sniff on

Is it possible to save the output to a file?  I know net.sniff supports pcap but I would like to capture the ble and wifi traffic to a file as well.

Thank you
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
mmm not yet :)

**Comment by evilsocket** [comment]
Now it is:

    bettercap -no-colors -eval "set events.stream.output ~/bettercap-events.log"

( Personally I don't use `-no-colors` as I like to replay the events with full coloring, but you can use it if you want :) )

See https://github.com/bettercap/bettercap/wiki/events.stream

**Comment by rogersmithboyd** [comment]
Thank you sir.  Going forward I will expect all my requests to be completed in a timely manor (less than 24 hours) ;-)

**Comment by evilsocket** [comment]
Don't put your expectations too high, this is not my job, I do it when I have time :)

**Comment by robertdavidgraham** [comment]
I assume this feature is no longer supported? I can't get it to work pasting the exact command.
bettercap v2.24 (built for linux amd64 with go1.11.6)

![Screen Shot 2019-06-11 at 8 31 57 PM](https://user-images.githubusercontent.com/3814757/59315498-fdeaae00-8c87-11e9-93e8-828c064ed690.png)

**Comment by yungtravla** [comment]
@robertdavidgraham the `events.stream` module starts automatically, try switching it off before setting the output destination: `-eval "events.stream off; set events.stream.output ~/bettercap-events.log; events.stream on; net.sniff on"`

**Comment by robertdavidgraham** [comment]
Thanks, this worked.
