### ISSUE TITLE
Extra spaces break commands

### ISSUE THREAD

**Issue by digininja** [bettercap/bettercap#178]
*Description of the bug or feature request*
Unexpected spaces between commands and their parameters result in errors.

### Environment

Please provide:

* Bettercap version you are using. - 2.2
* OS version and architecture you are using. - CentOS 7 x86-64
* Go version if building from sources. - go1.8.3 linux/amd64
* Command line arguments you are using. - --debug
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

```
192.168.x/24 > 192.168.x  » arp.spoof on
192.168.x/24 > 192.168.x  » [14:44:52] [sys.log] [inf] Enabling forwarding.
192.168.x/24 > 192.168.x  » [14:44:52] [sys.log] [inf] ARP spoofer started, probing 256 targets.
192.168.x/24 > 192.168.x  » arp.spoof  on
[14:44:54] [sys.log] [err] Unknown or invalid syntax "arp.spoof  on", type help for the help menu.
192.168.x24 > 192.168.x  » gps  on
[14:56:18] [sys.log] [err] Unknown or invalid syntax "gps  on", type help for the help menu.
```

### Steps to Reproduce

1. run the app
2. enter a command but put more than one space between the command and the parameter
3. tested with arp.spoof, net.sniff and gps

**Expected behavior:** *What you expected to happen*

commands should ignore white space before parameters

**Actual behavior:** *What actually happened*

command fails with error
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by yungtravla** [comment]
It seems this only occurs in the interactive session. Variables configured in a caplet file are already stripped from excess spaces.
