### ISSUE TITLE
Format string error

### ISSUE THREAD

**Issue by digininja** [bettercap/bettercap#179]
*Description of the bug or feature request*

Looks like you've got a format string wrong in the net.sniff output.

### Environment

Please provide:

* Bettercap version you are using. - 2.2
* OS version and architecture you are using. - CentOS 7 x86-64
* Go version if building from sources. - go1.8.3 linux/amd64
* Command line arguments you are using. None
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. start net.sniff
2. watch the output

**Expected behavior:** *What you expected to happen*

not sure what should come at the end of the log string but it probably shouldn't be what is there

**Actual behavior:** *What actually happened*

192.168.x24 > 192.168.xxx  » net.sniff off[15:05:30] [net.sniff.leak.tcp] tcp x.x.local.:60052 > xxx:https 443 bytes map[Size:%!s(int=443)]

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
This is normal, basically every event has an opaque `Data` field which varies from event to event, in case of `net.sniff` events, if the packet is just tcp ( wasn't detected by other higher level parsers ), that field is [just printed as it is](https://github.com/bettercap/bettercap/blob/master/modules/events_view.go#L152).
