### ISSUE TITLE
Suggestion: allow for adding custom interactive commands in proxy module js files

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#182]
Another feature could be: adding custom interactive commands in a proxy module js file, where you can `cmd( "show", function() { log(...) } )` and that would allow you to use `http.proxy.command.show` in the interactive session.

Since `get variable` does not escape characters and would not allow us to display nice tables for example.

**Comment by evilsocket** [comment]
I was thinking about this and I'm not sure it's a good idea to couple the proxy modules with the interactive session, defining functionalities in JS and using it from the prompt IMO is bad practice given the resulting command would be slower (and lock the interpreter) ... any specific use case you have in mind? Not sure I understood the escaping and tables thingy here ...

**Comment by yungtravla** [comment]
@evilsocket Ok so I'm working on a captive portal module (sending a PR soon) and it inspired this idea.

The idea is that users can interact with modules real-time (however they choose) as well as access data from the JS that is otherwise not accessible.

## In the case of a captive portal

Users could then issue commands such as `http.proxy.command.show` in order to show a nice looking table of all the current portal leases.

For example, in the javascript we call the `cmd()` function like so:

```javascript
cmd("show", function() {
  log(prettyTable)
})
```

In the interactive session, we can then call:

`http.proxy.command.show`

which would allow us to return data stored in JS variables like so:

```
+--------------+-------------------+---------------+--------+---------------+--------+--------+
|      IP      |        MAC        |     Name      | Status | Authenticated |  Sent  | Recvd  |
+--------------+-------------------+---------------+--------+---------------+--------+--------+
| 192.168.1.23 | xx:xx:xx:xx:xx:xx | Tom-MBP       | user   | 21:22:42      | 1.2 kB | 420 kB |
| 192.168.1.27 | xx:xx:xx:xx:xx:xx | Marc's iPhone | user   | 21:22:32      | 1.3 kB | 420 kB |
| 192.168.1.16 | xx:xx:xx:xx:xx:xx | android-xyz   | admin  | 21:18:57      | 245 B  | 32 kB  |
| 192.168.1.21 | xx:xx:xx:xx:xx:xx | ghxst         | banned | no            | 342 B  | 0 B    |
| 192.168.1.24 | xx:xx:xx:xx:xx:xx | John's iPhone | user   | no            | 0 B    | 0 B    |
+--------------+-------------------+---------------+--------+---------------+--------+--------+
```

This is not possible if we were to call it as a variable like so: `get http.proxy.show`, since it would return the table unescaped like this:

`+--------------+-------------------+---------------+--------+---------------+--------+--------+\n|      IP      |        MAC        |     Name      | Status | Authenticated |  Sent  | Recvd  |\n+--------------+-------------------+---------------+--------+---------------+--------+--------+\n| 192.168.1.23 | xx:xx:xx:xx:xx:xx | Tom-MBP       | user   |   21:22:42    | 1.2 kB | 420 kB |\n| 192.168.1.27 | xx:xx:xx:xx:xx:xx | Marc's iPhone | user   |   21:22:32    | 1.3 kB | 420 kB |\n| 192.168.1.16 | xx:xx:xx:xx:xx:xx | android-xyz   | admin  |   21:18:57    | 245 B  | 32 kB  |\n| 192.168.1.21 | xx:xx:xx:xx:xx:xx | ghxst         | banned |   no          | 245 B  | 0 B    |\n| 192.168.1.24 | xx:xx:xx:xx:xx:xx | John's iPhone | user   |   no          | 0 B    | 0 B    |\n+--------------+-------------------+---------------+--------+---------------+--------+--------+`

<hr>

Or how about `http.proxy.command.forms`:

```javascript
cmd("forms", function() {
  log(formsTable)
})
```

So when we call `http.proxy.command.forms` it would print such a table in the interactive session, showing all the forms that were submitted to the captive portal:


```
+--------------+-----------+----------+----------------------+
|      IP      | firstname | lastname |        email         |
+--------------+-----------+----------+----------------------+
| 192.168.1.24 | Marc      | Connole  | marcccc@email.com    |
| 192.168.1.24 | Tom       | Daniels  | tomdaniels@email.com |
+--------------+-----------+----------+----------------------+
```

<hr>

## In the case of an injected javascript interpreter

Another idea for a proxy module could be: allowing users to spawn an interactive javascript interpreter on injected browser tabs. It'd be awesome if we could execute javascript commands directly by doing something like `http.proxy.command.<tab-id> COMMAND`

The js would then look like this:

```javascript
var packets = {},
    responseHost = env("iface.ipv4"), // 192.168.1.4
    responsePort = env("http.server.port"), // 80
    responsePath = env("http.server.path") // 98209384092384

function randomString() {
  // return a random, 6-letter string that hasn't been generated yet
}

function onRequest(req, res) {
  // Handle request from interpreter
  if (req.Method == "GET" req.Host == responseHost && req.Port == responsePort && req.Path == responsePath) {
    // Look if there is a packet queued for this interpreter (by checking its tab-id), then return the packets in chronological order (joined with ";")
  } else if (req.Method == "POST" req.Host == responseHost && req.Port == responsePort && req.Path == responsePath) { // Handle request from interpreter
    // log the JSON response from the interpreter, for example {"tab_id":"xojpnf", "command":"alert('hi')", "response":"undefined"}
  } else if (req.ContentType == "text/html") { // Handle injectable requests
    // Inject JS interpreter (with a unique tab-id) which communicates with http://<responseHost>:<responsePort>/<responsePath>
    tabID = randomString()

    // ... (inject interpreter script) ...

    // Log that a new session has become available and can be accessed using its unique tab-id
    log("Interpreter session " + tabID + " started on " req.Host + req.Path + " - You can now send commands using http.proxy.command." + tabID + " COMMAND")
    cmd(tabID, function(command) { // function that gives the interactive session the following command: http.proxy.command.<tabID> COMMAND
      packet = {
        "tab-id"    : tabID,
        "command"   : command,
        "response"  : ""
      }
      packets[packets.length + 1] = packet
    }
  }
}
```

**Comment by evilsocket** [comment]
Every time an unknown session command is typed, the full line will be dispatched to a new `onCommand` module callback (if defined) that can return `true` if it can handle it as a custom command:

```js
function onCommand(cmd) {
    if( cmd == "test" ) {
        log( "GOT COMMAND!")
        return true
    }
}
```
