### ISSUE TITLE
error while loading shared libraries: libpcap.so.1:

### ISSUE THREAD

**Issue by paolofuse** [bettercap/bettercap#188]
### Description
Running the AMD64 release binary results in an error:

*error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory*

### Environment

* Bettercap version: 2.2 linux AMD64
* OS version and architecture: Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux
* Command line arguments: all
* **Full debug output** not available because *bettercap -debug* gives same error

### Steps to Reproduce

1. Download release 2.2.0
2. Run bettercap
3. Error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory

**Expected behavior:** *Kali Linux has installed libpcap-dev version 1.8.1.6, maybe should work with this version:*

/usr/lib/i386-linux-gnu/libpcap.so.0.8
/usr/lib/i386-linux-gnu/libpcap.so.1.8.1
/usr/lib/x86_64-linux-gnu/libpcap.so.0.8
/usr/lib/x86_64-linux-gnu/libpcap.so.1.8.1

Versions 2.0 and 2.1 works correctly on the same environment.

**Actual behavior:** *error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory*

**Comment by evilsocket** [comment]
Just created this -> https://github.com/bettercap/bettercap/wiki/Known-Issues

**Comment by Kyu** [comment]
Came here from google and the link is dead, this helped: 

https://linuxhint.com/install-bettercap-on-ubuntu-18-04-and-use-the-events-stream/
