### ISSUE TITLE
package context: unrecognized import path "context"

### ISSUE THREAD

**Issue by michelep** [bettercap/bettercap#194]
I'll try but setup/install procedure die with:

~ $ go get github.com/bettercap/bettercap
package context: unrecognized import path "context" (import path does not begin with hostname)
~ $

My go version is go1.6.2 linux/amd64

**Comment by evilsocket** [comment]
From the very [first page of the Wiki](https://github.com/bettercap/bettercap/wiki) (and README too):

> Make sure you have a correctly configured Go >= 1.8 environment
