### ISSUE TITLE
Libpcap.so.1 not found

### ISSUE THREAD

**Issue by squallx2x** [bettercap/bettercap#195]
Dear,

i installed libpcap-dev, but when I run ./bettercap, there is an error:
"./bettercap: error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory"

**Comment by leonardoporpora** [comment]
https://github.com/bettercap/bettercap/wiki/Known-Issues

**Comment by leonardoporpora** [comment]
How people pretend to learn if they do not read...?!

**Comment by squallx2x** [comment]
Dear,
i'm just Linux beginner. As I ran Bettercap 1.6 before with these installer:
gem clean bettercap.gemspec
gem build bettercap.gemspec
gem install bettercap*.gem
But for Bettercap 2.3, how to install it by downloading whole zip file & extract it ? I tried "go get github.com/bettercap/bettercap" but not success

Thank you!

**Comment by leonardoporpora** [comment]
Np close this issue :)

**Comment by squallx2x** [comment]
But would you please tell me how to install v2.3 ?
go get github.com/bettercap/bettercap sucess but nothing happen.

**Comment by leonardoporpora** [comment]
Read the wiki!

**Comment by mrkumar009** [comment]
tell me @leonardoporpora how people can read non-existing wikis?
