### ISSUE TITLE
Go update error

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#197]
During go update of bettercap:
`go/src/github.com/bettercap/bettercap/modules/gps.go:133:15: info.GetSentence undefined (type nmea.Message has no field or method GetSentence)`

### Environment

`Darwin Macbook.local 16.7.0 Darwin Kernel Version 16.7.0: root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64`
`go version go1.10 darwin/amd64`
### Steps to Reproduce

Run
`go get -u -v github.com/bettercap/bettercap`
or
`go get -u github.com/bettercap/bettercap`

**Expected behavior:** *Updated bettercap*

**Actual behavior:** *Nothing happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by musaakpinar** [comment]
same issue when I try to install from stratch
**During installation of bettercap:**  github.com/bettercap/bettercap/modules
src/github.com/bettercap/bettercap/modules/gps.go:133:15: info.GetSentence undefined (type nmea.Message has no field or method GetSentence)
**Enviroment:** Linux  4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
go version go1.10 linux/amd64

**Comment by wcrigger** [comment]
Same here:

root@kali-desktop:~/go/bin# go get -u github.com/bettercap/bettercap
# github.com/bettercap/bettercap/modules
../src/github.com/bettercap/bettercap/modules/gps.go:133:15: info.GetSentence undefined (type nmea.Message has no field or method GetSentence)
root@kali-desktop:~/go/bin# cat /etc/*release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.1"
VERSION_ID="2018.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"
root@kali-desktop:~/go/bin# go version
go version go1.9.2 linux/amd64
root@kali-desktop:~/go/bin# uname -a
Linux kali-desktop 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

**Comment by SecurityWaffle** [comment]
This is being caused by changes made to the go-nmea package. The GetSentence method appears to be replaced with a different error handling method. 

https://github.com/adrianmo/go-nmea/commit/22095aa1b48050243d3eb9a001ca80eb91a0c6fa

**Comment by yungtravla** [comment]
@SecurityWaffle one downside of compiling with external git repos
