### ISSUE TITLE
Use stable releases (or I found why issue #202 and #201

### ISSUE THREAD

**Issue by blshkv** [bettercap/bettercap#203]
continuation of the issue #201
so apparently,  go-nmea wasn't missing in my setup. It was *one* commit behind (https://github.com/adrianmo/go-nmea/commit/22095aa1b48050243d3eb9a001ca80eb91a0c6fa).
That's why it wasn't reported as missing.

You can call it mistake 0,1,3 and 10. But it would be good if Go authors would release stabled versions so that your stable releases would be using stable dependencies. That basically means that bettercap might fail to compile if such ```major refactoring``` of one of dependencies would happen *after* you released a tool (which *WILL* happen at some point)

But this is where Go sucks and there is nothing we can do. I will pay more attention on such cases.

Peace.

**Comment by evilsocket** [comment]
Ok, either i overestimated your IQ or you're just a troll. Adios.

**Comment by evilsocket** [comment]
(support for either `glider` or some similar solution is already being discussed)

**Comment by blshkv** [comment]
that's perfect! Thank you so getting down to my level of IQ.

**Comment by evilsocket** [comment]
The level of IQ thing was referred to the way you kept opening issues regardless the whole conversation.

**Comment by blshkv** [comment]
My bug was not fixed and I couldn't provide any additional information in locked bugs. So I had no choice but open open a new one. But ok, it is fixed. Thanks again and my apologies again.

Let's move on!

**Comment by evilsocket** [comment]
Your bug was not a bug in the first place, just outdated dependencies, you can keep saying the opposite as much as you want but that does change the thing, you would have "fixed" it yourself just by updating dependencies, given you decided to build from source.

Yeah, don't make me lock this one as well, let's move on ;)

**Comment by wwwatersss8** [comment]
look my IQ doesn't cover you okay
