### ISSUE TITLE
maybe add a module reload function

### ISSUE THREAD

**Issue by evs-pn** [bettercap/bettercap#204]
*Description of the bug or feature request*

If you enabled a module like "arp.spoof" and you changed some value like " arp.spoof.targets" the module has to be reloaded (on && off). It would be a nice feature if you can implement something like "<module name> reload" or reloading the module on the fly whenever important settings are changed.

BTW: Maybe add the possability to set an alias as a target for the arp.spoof module.

Thanks in advance and keep going on!

### Environment

* Bettercap version you are using.
Version 2.3.1
* OS version and architecture you are using.
Arch Linux x64
* Go version if building from sources.
Used stable release

### Steps to Reproduce

arp.spoof.targets 192.168.0.12
arp.spoof on
arp.spoof.targets 192.168.0.13
arp.spoof off
arp.spoof on

**Comment by evilsocket** [comment]
Making everything dynamic (the module reloads when something it needs changes) would require a major refactoring and in some cases it'd be entirely possible, but yeah I'm aware this behaviour is far from optimal. I'll think about something and see what's the cleanest way to support this :)

Regarding using an alias for `arp.spoof.targets` (and why not, maybe any parameter accepting an ip?), that's a great idea, will implement it for sure! :D

**Comment by evs-pn** [comment]
Nice thanks for feedback. I think the live update is only for a few modules practicable. arp.spoof is one of them as you only have one decisive variable.

You will get always updates with real world scenarios from us...we always stay bleeding edge ;)

**Comment by alexmozzhakov** [comment]
I think setting reload just to do off then on where possible will be a good solution
P.S #137

**Comment by evilsocket** [comment]
I was wondering something ... as the first step to implement this feature, I'd create a new `module.whatever reload` aliased to a `module.whatever off; module.whatever on` ... so maybe it'd be nice just to give the user the possibility to define not just an alias to an ip, but also to a set of commands (and have some aliases pre defined by default, like the `reload` thingy) ... that would solve stage 1 of this issue and also be a nice feature for users I guess, something like:

    define arpSpoof "set arp.spoof.targets $1; arp.spoof on"

( where `$1`, `$2`, etc would be any argument passed to `arpSpoof` )

Pretty much like bash / zsh aliases .... thoughts?

**Comment by alexmozzhakov** [comment]
@evilsocket maybe adding `$1`, `$2` to caplets and than somehow searching for them as interactive commands (by filename, for example)
What I mean is `arpSpoof.cap` would look like 
```
set arp.spoof.targets $1
arp.spoof on
```
Then running `arpSpoof 192.168.1.2` would do the trick? (Such caplets may be stored in a subfolder `commands` with define command creating a new file there)
Also, defining `reload.cap` then as 
```
$1 off
$1 on
```
Would be very easy to implement on users needs.

**Comment by evilsocket** [comment]
Wow i really like this! :D

**Comment by evilsocket** [comment]
So by default I'd lookup in `./name-here.cap`, `./caplets/name-here.cap` and `/usr/share/bettercap/caplets/name-here.cap` (OS specific and overridable with some env variable like you do with `$PATH`)

**Comment by evilsocket** [comment]
The new behaviour has been implemented and documented in [this new section of the Wiki](https://github.com/bettercap/bettercap/wiki/Caplets#from-the-interactive-session), thanks for the feedback everyone! :)

**Comment by evs-pn** [comment]
Nice! Works very well.
