### ISSUE TITLE
Only works if you specify the interface using Mac Address. (Windows)

### ISSUE THREAD

**Issue by davidtavarez** [bettercap/bettercap#206]
Only works if you specify the interface using Mac Address. So in order to get buttercup working, you have yo do `ifconfig /all` find the interface and pass the MAC address with `-iface` 

### Environment

* Bettercap 2.31
* Windows Server 2012 64bit
* Go 1.10

**Comment by evilsocket** [comment]
Some drivers on Windows give a name to the interface but internally to API calls the name is actually different, so there's no easy way to lookup the interface that way. It also works if you specify the IP address instead of the MAC.
