### ISSUE TITLE
HTTP traffic not visible when running `http-req-dump.cap`

### ISSUE THREAD

**Issue by Obaied** [bettercap/bettercap#208]
*Description of the bug or feature request*

I'm trying to perform some dynamic analysis on a live malware running on a physical Android device. I need to sniff HTTP & HTTPS traffic coming from the Android device. The setup I have is:
- An Android phone connected to a wifi hotspot
- A MacBook that's running bettercap with the following command on the same hotspot as the Android device:
`sudo bettercap -caplet caplets/http-req-dump.cap -debug -eval "set arp.spoof.targets 192.168.8.122"`

### Environment

Please provide:

* Bettercap version you are using.
2.3.1

* OS version and architecture you are using.
MacBook Pro late 2016 running High Sierra

* Go version if building from sources.
1.9.2 Darwin/amd64

* Command line arguments you are using.
`-caplet caplets/http-req-dump.cap -debug -eval "set arp.spoof.targets 192.168.8.122"`
I modified `http-req-dump.cap` script to enable sniffing (just uncommented the pre-written section)

* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
```
[16:24:18] [mod.started] net.recon
[16:24:18] [sys.log] [inf] Checking latest stable release ...
[16:24:18] [endpoint.new] Endpoint 192.168.8.24 detected as 98:9e:63:b0:df:be (Apple).
[16:24:18] [endpoint.new] Endpoint 192.168.8.100 detected as 48:bf:6b:3e:7b:72 (Apple).
[16:24:19] [sys.log] [inf] You are running 2.3.1 which is the latest stable version.
[16:24:19] [endpoint.new] Endpoint 192.168.8.25 detected as 6c:96:cf:dd:c4:7d.
[16:24:20] [endpoint.new] Endpoint 192.168.8.109 detected as 00:b3:62:de:c6:e8 (Apple).
[16:24:20] [mod.stopped] net.probe
[16:24:20] [sys.log] [dbg] env.change: net.sniff.verbose -> 'false'
[16:24:20] [mod.started] net.sniff
[16:24:20] [sys.log] [dbg] Proxy script caplets/http-req-dump.js loaded.
[16:24:20] [sys.log] [inf] Enabling forwarding.
[16:24:20] [sys.log] [dbg] Applied redirection [en0] (TCP) :80 -> 192.168.8.70:8080
[16:24:20] [sys.log] [inf] Loading proxy certification authority TLS key from /var/root/.bettercap-ca.key.pem
[16:24:20] [sys.log] [dbg] Proxy script caplets/http-req-dump.js loaded.
[16:24:20] [sys.log] [inf] Enabling forwarding.
[16:24:20] [endpoint.new] Endpoint 192.168.8.83 detected as 08:6d:41:d3:e2:46 (Apple).
[16:24:20] [sys.log] [dbg] Applied redirection [en0] (TCP) :443 -> 192.168.8.70:8083
[16:24:20] [mod.started] https.proxy
[16:24:20] [sys.log] [dbg]  addresses=[192.168.8.122] macs=[]
[16:24:20] [sys.log] [inf] Enabling forwarding.
[16:24:20] [mod.started] arp.spoof
192.168.8.0/22 > 192.168.8.70  » [16:24:20] [sys.log] [inf] ARP spoofer started, probing 1 targets.
192.168.8.0/22 > 192.168.8.70  » [16:24:21] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.8.122
```
and it just keeps repeating the last message every second without recording any HTTP or HTTPS traffic from the Android device.

### Steps to Reproduce
- Run `sudo bettercap -caplet caplets/http-req-dump.cap -debug -eval "set arp.spoof.targets 192.168.8.122"` from an OSX machine where `196.168.8.122` is the IP of an Android device.
- Do some traffic on the Android device connected to the same wifi hotspot as the OSX machine.
- Nothing is recorded.

**Expected behavior:** *What you expected to happen*
To see all HTTP traffic. HTTPS traffic "should" be readable after I install the certificate on the Android device, but I should at least see the encrypted packets.

**Actual behavior:** *What actually happened*
I don't see any traffic. I thought that after [this tweet from EvilSocket](https://twitter.com/bettercap/status/967453847114407936), new Macs wouldn't need a new network card for monitor mode.

**Comment by evilsocket** [comment]
This has nothing to do with monitor mode, from the logs everything looks good, so either the ip is wrong or simply the arp spoofing doesn't work on your network. Will double check just to be sure.

**Comment by Obaied** [comment]
Thanks mate. I'll try it on a different network and report back.

Out of curiosity, is it possible to disable arp spoofing on a network?

**Comment by evilsocket** [comment]
You can't "disable" it, but there're some firewalls and routers that can be configured to detect and block the attack.

**Comment by Obaied** [comment]
Ok, I tried something else. Since I have control of the Android device, I setup a manual proxy to point to my OSX machine and to port 8083.

I made this caplet
```
set https.proxy.script caplets/http-req-dump.js
set http.proxy.script caplets/http-req-dump.js

set https.proxy.address 0.0.0.0
set https.proxy.sslstrip true
set https.proxy.port 8083

http.proxy on
https.proxy on
net.recon off
```

and ran it as such `sudo bettercap -caplet caplets/local-https.cap -iface en0`

but I got nothing. I'm trying to basically mimic the behavior of CharlesProxy if you've heard of it.

**Comment by Obaied** [comment]
Update: Just tried the original `sudo bettercap -caplet caplets/http-req-dump.cap -debug -eval "set arp.spoof.targets 192.168.8.122"` command on another private network with the same results.

**Comment by its0x08** [comment]
While u put proxy manually why do u need to send spoofed packets? 
Dont understand this part ..

**Comment by Obaied** [comment]
I'm just trying to simply monitor traffic on my OSX machine and, if needed, [modify incoming/outgoing packets and spoof DNS](https://www.slideshare.net/NatrajG1/basic-dynamic-analysis-of-malware): something like running Burp suite locally.

Correct me if I'm wrong, but the idea of arp spoofing is to trick the network into associating the attacker's MAC address with the IP address of the target in order to _intercept and modify packets_.

With CharlesProxy, the idea was to setup the target's proxy to point to the attacker and route the target's traffic to the attacker's machine in order to _intercept and modify packets_.

So in my mind, both ARP spoofing and rerouting traffic through a manual proxy should yield the same results.

There's also one method I didn't try which is to setup a hotspot on my machine and have the target connect to it, but I would say it would yield the same results as the first approach I mentioned.

I hope I didn't miss something...

**Comment by evilsocket** [comment]
So, I just tested the latest version of bettercap with that caplet on my macOS laptop and it worked perfectly,  as I said your logs seem fine so it's just something in your network (or the ips/values/whatever) you're using that's preventing the attack from working.

Yes, you can use the `http.proxy` module as a proxy pretty much like you use Burp or WhateverProxy, if you have a rogue ap (or just set its address as the http proxy of the victim manually) you don't need to perform arp spoofing.

Closing.

**Comment by Obaied** [comment]
Thanks for taking the time both of you to answer my questions. I just ran Burp Suite, CharlesProxy and WireShark and they all intercepted traffic after manually pointing a proxy address to my OSX machine. I believe there is an issue with Bettercap. I'll investigate when I have time and open a new issue *if* I find a bug or fix it.

P.S: This is my caplet for intercepting traffic. Android is running a proxy to point my Mac's IP address and port 8083 (default HTTPS port for Bettercap):

```
set http.proxy.script caplets/http-req-dump.js
set https.proxy.script caplets/http-req-dump.js
clear

http.proxy on
https.proxy on
net.recon off
```

**Comment by evilsocket** [comment]
@Obaied I just tried it with an iPad (just setting the proxy to the IP of the machine running bettercap with `http.proxy' enabled on port 8080, no spoofing involved) and it works like a charm ... I believe there's something wrong in your configuration ... bettercap's `http.proxy` and `https.proxy` modules are normal transparent proxies and can definitely be used the way you're trying.

**Comment by Obaied** [comment]
Was it with the same caplet as above?

**Comment by evilsocket** [comment]
yep, the only difference is that i tested just the `http.proxy` and not `https.proxy` as the iPad only allows http proxies to be configured, but they share the same exact codebase and logic so if the first works, the second works as well (assuming a correct configuration) :)
