### ISSUE TITLE
Minor UI issue when BLE name contains special characters

### ISSUE THREAD

**Issue by jofrep** [bettercap/bettercap#211]
The table displayed using ble.show is not displayed properly in certain conditions.
If there is a BLE device with a name containg a special characters the cell width is too short 

### Environment
Bettercap 2.3.1
Ubuntu 16.4
Linux gp 4.14.0-11-generic #gpd SMP Thu Oct 12 09:34:06 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce
1. Set a BLE with the name: vívosmart HR+
2. ble.recon on
3. ble.show

**Expected behavior:**
All cells in the same row should have the same width

**Actual behavior:** 
The cell containing the BLE name with vívosmart HR+ is shorter than it should be

**Comment by haritonovsguntis** [comment]
http://www.w3.org/2005/Atom">
