### ISSUE TITLE
error while loading shared libraries: libnetfilter_queue.so.1

### ISSUE THREAD

**Issue by leonardoporpora** [bettercap/bettercap#212]
*Description of the bug or feature request*

### Environment

Please provide:

* 2.4
* OS version and architecture you are using. Debian 9 stretch
* precompiled
* sudo ./bettercap
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. sudo ./bettercap

**Expected behavior:** see the bettercap terminal

**Actual behavior:** ./bettercap: error while loading shared libraries: libnetfilter_queue.so.1: cannot open shared object file: No such file or directory
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Did you install `libnetfilter-queue-dev` as per wiki and readme?

**Comment by leonardoporpora** [comment]
Sorry dear I have also read it but i didn't noticed it, my fault.

**Comment by bhatz829** [comment]
I'm looking at the README in the github right now and I don't see anything related to this.
