### ISSUE TITLE
unable to install bettercap on kali

### ISSUE THREAD

**Issue by bkr32** [bettercap/bettercap#216]
*Description of the bug or feature request*

### Environment

Please provide:

* OS version and architecture you are using. 4.8.0-kali2-amd64
* Go version if building from sources.  go version go1.10rc2 linux/amd64
* Command line arguments you are using. go get github.com/bettercap/bettercap

### Steps to Reproduce

1. run go get github.com/bettercap/bettercap

**Expected behavior:** *What you expected to happen*
should install bettercap and execute it when `bettercap` is executed in terminal
**Actual behavior:** *What actually happened*
nothing happens..
-- 
new to using GO so please excuse if i've made a mistake
**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by leonardoporpora** [comment]
Read the wiki this is not a forum is only for issues or new feature

**Comment by Darthxbox** [comment]
In your home directory is a new directory called 'go'. The bettercap binary is located in ~/go/bin/bettercap

**Comment by bkr32** [comment]
@leonardoporpora i did read the wiki and what is stated is after running ` go get github.com/bettercap/bettercap` it should compile the code and running `bettercap` should bring up the tool which it doesn't so unless there's a forum where someone who has knowledge about this tool can help issues like this are created

@Darthxbox i have found the binary, but isnt it available system wide?
