### ISSUE TITLE
No creds and websites are sniffed

### ISSUE THREAD

**Issue by vostok3r** [bettercap/bettercap#219]
---

I cant get any website visited by other devices in my network in Bettercap.
All i got is 
`192.168.1.0/24 > 192.168.1.134  » [05:48:09] [net.sniff.leak.udp] udp android-92a524d1399a6040.:mdns > 224.0.0.251:mdns 368 bytes map[Size:%!s(int=368)]`

Please provide:

* Bettercap version 2.4.
* Kali Linux 2018.

My steps to sniff traffic:
`bettercap -iface wlan0
net.sniff on
arp.spoof on`

Screenshot:
<img width="736" alt="screen shot on 2018-04-04 at 12_48_31" src="https://user-images.githubusercontent.com/29917942/38301091-3c5a9244-3807-11e8-9dc6-5bcc220b4b11.png">

How I can get bettercap to show me creds from HTTP websites and URL visited by WLAN clients?

**Comment by evilsocket** [comment]
`bettercap -iface wlan0 net.sniff on arp.spoof on` is not a valid command, read the wiki if you want answers.
