### ISSUE TITLE
Can't get any data from network with arp.spoof and net.sniff

### ISSUE THREAD

**Issue by vostok3r** [bettercap/bettercap#220]
You closed my ticket but I launched Bettercap correctly. Please help =)

I cant get any website visited by other devices in my network in Bettercap.
All i got is data like:
`192.168.1.0/24 > 192.168.1.134  » [05:48:09] [net.sniff.leak.udp] udp android-92a524d1399a6040.:mdns > 224.0.0.251:mdns 368 bytes map[Size:%!s(int=368)]`

More info on screenshot below.

* Bettercap version 2.4
* Kali Linux 2018
* Reinstalled bettercap 2 times already

My steps to sniff traffic:
`bettercap -iface wlan0`
Then i entered
`net.sniff on`
`arp.spoof on`

Screenshot:
<img width="736" alt="screen shot on 2018-04-04 at 12_48_31" src="https://user-images.githubusercontent.com/29917942/38301091-3c5a9244-3807-11e8-9dc6-5bcc220b4b11.png">

How I can get bettercap to show me creds from HTTP websites and URL visited by WLAN clients?
It's not only my issue, i got the same report from other users(

**Comment by evilsocket** [comment]
> You closed my ticket but I launched Bettercap correctly.

No, you did not. **RTFM**
