### ISSUE TITLE
Bettercap break very badly if http/s.proxy module tries to run a malformed Javascript script

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#221]
If set http/s.proxy.script variable points to a malformed Javascript script (that is, with at least one syntax error), Bettercap ends in a very bad manner (I attach screen capture for completeness) and, what is worse, breaks the terminal so that is necessary running the "reset" command. Could there be any way to make Bettercap reject to parse a bad written Javascript code and inform the user of this error in a polite manner? Thanks!
![captura de pantalla de 2018-04-08 20-21-15](https://user-images.githubusercontent.com/7274874/38471499-33a50152-3b72-11e8-9e7a-8294b552373c.png)

* Bettercap version you are using. 2.4
* OS version and architecture you are using. Ubuntu 17.10
* Go version if building from sources. Not: downloaded directly from official release
* Command line arguments you are using. None

**Comment by yungtravla** [comment]
> (I attach screen capture for completeness)

Not nearly...

Again, please write a complete issue so we can reproduce this easily.

**Comment by q2dg** [comment]
Ok. Supose you have a file called "test.js" in same folder where bettercap binary is, with this bad-written Javascript content (note the lack of last "}"):

_function onLoad() { console.log("Script loaded");_ 

If you enter in bettercap interactive session and you execute these commands, you'll receive an error similar to shown in screenshot below:

_set https.proxy.script test.js
https.proxy on_

It's curious because using the http module instead (that is: entering these commands: _set http.proxy.script test.js; http.proxy on_) the breaking doesn't happen (in fact, nothing happens, which could be an ok behaviour)

![captura de pantalla de 2018-04-09 13-26-02](https://user-images.githubusercontent.com/7274874/38495560-530edc38-3bfa-11e8-8d3b-3565a23093f5.png)

Thanks

**Comment by evilsocket** [comment]
I tried to reproduce this with:

```js
function onLoad() { console.log("Script loaded");
```

But all I got was:

> (anonymous): Line 3:1 Unexpected end of input

No crashes ... same configuration as you, but using latest go version available from Ubuntu repos.

**Comment by q2dg** [comment]
Well, I have Ubuntu 17.10 and a recently installed  Go 1.8.3 but issue still occurs.
Don't mind, close the issue if you consider it can't be reproducible.
