### ISSUE TITLE
req and res objects in Javascript modules aren't documented

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#222]
It's necessary to deep into caplets examples to graps wich methods and properties have but there's no any centrallised list and no description anywhere.
Thanks

**Comment by yungtravla** [comment]
Whether you write straightforward and consistent modules or not, is up to you.

What are you actually asking for, can you give us some examples?

**Comment by yungtravla** [comment]
I have https://github.com/bettercap/bettercap/issues/217 on my todo list, so if this doesn't allow for what you want, I'm not really sure what the issue is here.

**Comment by yungtravla** [comment]
And there are concise instructions written [in the wiki](https://github.com/bettercap/bettercap/wiki/http.modules) for just about any feature of bettercap.

**Comment by q2dg** [comment]
I have not explained well, sorry. What I wanted is a list of methods and properties of res and req object.
Diving into caplets code I've discovered, at least:

res.Status
res.ContentType
res.Body
res.SetHeader
res.RemoveHeader
res.Headers[i]
res.readBody()
req.Headers[i]
req.readBody()
req.parseForm()
req.Method
req.Path
req.Query
req.Client
req.Hostname
req.ContentType

All of them are very simple to understand, but it would be nice if they could be briefly listed in a centralized reference page.
Thanks

**Comment by yungtravla** [comment]
[they are](https://github.com/bettercap/bettercap/wiki/http.modules)

**Comment by q2dg** [comment]
No. There's a list of builtin Javascript functions but not a list of public res/req's methods/properties

**Comment by yungtravla** [comment]
If you can't figure it out by looking at the code examples in the wiki, you shouldn't be using it in the first place IMO.

**Comment by q2dg** [comment]
Well, it's your opinion. I can dig into source code to figure out. Thanks

**Comment by yungtravla** [comment]
You're always welcome to document the functions and submit them if you feel the need.

**Comment by q2dg** [comment]
Well, looking at JSRequest struct in https://github.com/bettercap/bettercap/blob/9a20e54b2861a3c0b594d8c00680d9bcad791144/modules/http_proxy_js_request.go it seems the list of most interesting properties/methods is:

req.Client
req.Method    
req.Version   
req.Path        
req.Query      
req.Hostname   
req.ContentType
req.Headers[]
req.Body
req.WasModified() -->bool
req.GetHeader(name,otherstring)-->string
req.SetHeader(name,value)
req.RemoveHeader(name)
req.ReadBody(string) -->string
req.ParseForm() -->map

Looking at JSResponse struct in https://github.com/bettercap/bettercap/blob/1f8e97d91fbb67570c5d44e1c5c0442e497d7d09/modules/http_proxy_js_response.go it seems the list of most interesting properties/methods is:

res.Status 
res.ContentType
res.Headers[]
res.Body
req.WasModified() -->bool
req.GetHeader(name,otherstring)-->string
req.SetHeader(name,value)
req.RemoveHeader(name)
req.ReadBody(string) -->string

**Comment by yungtravla** [comment]
@q2dg I might allocate some time to document the code in some areas, but I don't think a wiki page to explain every single thing is necessary. We might as well start teaching people how to code :wink:
