### ISSUE TITLE
DN Spoof all hosts

### ISSUE THREAD

**Issue by talal2** [bettercap/bettercap#223]
Hi !

I Wanna know which command i need to write in hosts.conf to redirect ALL hosts to my PC, without specifying them 
* exemple: 192.168.1.1 msn.com

What i want : ---> 192.168.1.1 'ALL HOSTS'

                                                 Thanks in advance & Much appreciated ;) :)

**Comment by q2dg** [comment]
None, it's the default: https://github.com/bettercap/bettercap/wiki/dns.spoof

**Comment by yungtravla** [comment]
@talal2 RTFM
`set dns.spoof.all true; dns.spoof on`

**Comment by talal2** [comment]
Thanks  to all of you .

                            Much appreciated ;) :)

**Comment by q2dg** [comment]
Sorry for the question, @yungtravla but I've seen you specify _dns.spoof.all on_ and I just have a problem/doubt related to it. 

I want to dns-spoof (via arp-spoof) some pcs of my lan but there is also a local dns server running in it (and configured in all clients as first dns server to call), so I suspect requests to local and cached names goes directly to it, so, therefore, they doesn't go to bettercap and, in consequence, aren't spoofed. Putting dns.spoof.all to on would resolve this problem? If I infer correctly from wiki, this option grabs any dns request flowing through the lan although they aren't addressed to the lan gateway (to arrive to extern dns servers), doesn't it? If it was, this would be terrific, yeah!!

Sorry for the inconvenience.
Thanks a lot
