### ISSUE TITLE
package plugin: unrecognized import path "plugin"

### ISSUE THREAD

**Issue by elbrinke** [bettercap/bettercap#224]
# Prerequisites

*Description of the bug or feature request*
I am trying to install "bettercap" on Ubuntu 18.04. All the dependencies installs normally but when i run the install command according to your github info, i get a strange error. I normally used bettercap in Kali Linux but they still have an older version of bettercap. I am now using Ubuntu 18.04 and would like to run some tools in it. 

### Environment

Please provide:

* Bettercap version you are using. **2.4**
* OS version and architecture you are using. **Ubuntu 18.04 LTS**
* Go version if building from sources. **go version go1.10 gccgo (Ubuntu 8-20180408-0ubuntu1) 8.0.1 20180408 (experimental) [trunk revision 259224] linux/amd64**
* Command line arguments you are using. **go get github.com/bettercap/bettercap**
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. **I installed the dependencies:**

- golang-go
- gccgo-go
- libpcap-dev
- libnetfilter-queue-dev

2. **I run the command as provided on github** 

> ` go get github.com/bettercap/bettercap`

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

_I got the following error:_ 

> `package plugin: unrecognized import path "plugin" (import path does not begin with hostname)`

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Are you sure about the go version you are using? because `plugin` is a standard package since Go 1.8

**Comment by elbrinke** [comment]
Yes, go version go1.10 gccgo (Ubuntu 8-20180408-0ubuntu1) 8.0.1 20180408 (experimental) [trunk revision 259224] linux/amd64

**Comment by warecrer** [comment]
Dear friend, try to install golang-go again.. Another missing file to install.. I try it and it's done._

**Comment by glides** [comment]
Fresh install of Ubuntu 18.04.

I installed dependencies in this order:

    golang-go
    gccgo-go
    libpcap-dev
    libnetfilter-queue-dev

And received the same error. Reinstalling golang-go again replaces the gccgo-go package that was just installed and you're finally good to go.

I assume, had I not installed gccgo-go separately...that the correct package was already in golang-go.

@evilsocket If you wanted the steps to reproduce

**Comment by vladionescu** [comment]
I'm also facing this on up to date Debian 9. Tried installing go from `sudo apt install golang` as well as from the archive following instructions on go's site (go1.11.5.linux-amd64.tar.gz).
