### ISSUE TITLE
Redirect all hosts to my fake dsn

### ISSUE THREAD

**Issue by talal2** [bettercap/bettercap#225]
Hi !

Can anyone please ! right exemples of the right commands for dns spoof ?
& What is the right command to write in dns.conf to redirect all the traffic to my server ?
* Is this correct ----> 192.168.1.1  .*
How can i integrate those commands in bettercap, do i need to change them in any file, or write them in terminal ?

         Thanks in advance ;) :)

**Comment by evilsocket** [comment]
https://github.com/bettercap/bettercap/wiki/dns.spoof
