### ISSUE TITLE
Ruby Prob !

### ISSUE THREAD

**Issue by talal2** [bettercap/bettercap#226]
When i launch an attack, It gives me an errors with ---> /Ruby/................
Can you help, Please !

                                Much appreciated ;) :)

**Comment by yungtravla** [comment]
Ruby??

This is nowhere near a complete report. Please **do not** delete the template and use it properly as described in detail.

We cannot help you if you give us 1 word of the entire error......................

I am gonna leave this open as you have posted a duplicate issue of your own before. Just so you know, your issues don't get deleted, they get closed...
