### ISSUE TITLE
Unable to Launch bettercap

### ISSUE THREAD

**Issue by N0W0RK** [bettercap/bettercap#227]
When I am trying to launch bettercap in the commandline, ruby tells me that it hasnt found a gem called bettercap. This is lekely because i used to have bettercap installed as a ruby gem.

### Environment

betercap version: v. 2.4
OS version: macOS 10.13.4 Beta
go version: go1.10.1 darwin/amd64
Commandline command: bettercap

Error: 
/Users/n0w0rk/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bettercap' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/n0w0rk/.gem/ruby/2.2.0:/Users/n0w0rk/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /Users/n0w0rk/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/n0w0rk/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/n0w0rk/.rvm/gems/ruby-2.2.2/bin/bettercap:22:in `<main>'
	from /Users/n0w0rk/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/n0w0rk/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

### Steps to Reproduce

i dont think you are able to reproduce this error. But in case its still possible:

install bettercap on ruby 2.2.2
delete bettercap gem folder
install latest version of go
install bettercap through go
launch bettercap 

It should launch an interactive bettercap session

instead nothing happens and the error above pops up

**Comment by evilsocket** [comment]
you are using the old ruby version which is not supported anymore, just follow the wiki

**Comment by N0W0RK** [comment]
I still don't see how I am using the ruby version. I followed all steps required to install bettercap and I find the folder in the go repository but ruby thinks its targetet by `sudo bettercap`.

**Comment by evilsocket** [comment]
then uninstall it with `gem uninstall bettercap` ... the Ruby version apparently has precedence in your `$PATH` over the Go version.

**Comment by N0W0RK** [comment]
Thanks that helped, but know terminal doesnt recognize bettercap as a command at all what do i do? I looked in $PATH and the go/bin directory were the bettercap executable is stored is in my $PATH but the command does still not work.

**Comment by evilsocket** [comment]
RTFM
