### ISSUE TITLE
macos install bettercap running faild

### ISSUE THREAD

**Issue by mofei-123** [bettercap/bettercap#233]
macos :10.12.4

brew install bettercap 
 runing error:

bettercap v2.4 (type 'help' for a list of commands)

en0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied)

# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using.
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by alexmozzhakov** [comment]
Run with sudo, wtf
