### ISSUE TITLE
macos install bettercap error

### ISSUE THREAD

**Issue by mofei-123** [bettercap/bettercap#234]
macos version：10.12.4
install setp：

tar xvf libpcap-1.8.1.tar.gz && cd libpcap-1.8.1
./configure --prefix=/usr --disable-optimizer-dbg --disable-yydebug --disable-bluetooth --disable-dbus --without-libnl --without-dag --without-septel --without-snf --without-turbocap

make -j4

sudo make install

error:

sudo make install
rm -f libpcap*.dylib
VER=`cat ./VERSION`; \
	MAJOR_VER=A; \
	COMPAT_VER=1; \
	CURRENT_VER=`sed 's/[^0-9.].*$//' ./VERSION`; \
	gcc -dynamiclib -undefined error -arch x86_64 -arch i386  \
	    -o libpcap.$VER.dylib pcap-bpf.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o    \
	    -install_name /usr/lib/libpcap.$MAJOR_VER.dylib \
	    -compatibility_version $COMPAT_VER \
	    -current_version $CURRENT_VER
[ -d /usr/lib ] || \
	    (mkdir -p /usr/lib; chmod 755 /usr/lib)
VER=`cat ./VERSION`; \
	MAJOR_VER=A; \
	/usr/bin/install -c libpcap.$VER.dylib /usr/lib/libpcap.$VER.dylib; \
	ln -sf libpcap.$VER.dylib /usr/lib/libpcap.$MAJOR_VER.dylib; \
	ln -sf libpcap.$MAJOR_VER.dylib /usr/lib/libpcap.dylib
install: /usr/lib/libpcap.1.8.1.dylib: Operation not permitted
ln: /usr/lib/libpcap.A.dylib: Operation not permitted
ln: /usr/lib/libpcap.dylib: Operation not permitted

# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using.
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
this is libpcap related, not bettercap related ... you could install it more easily using brew instead of compiling it from source, but if you really have to, that "operation not permitted" means you're trying to "make install" without being root (you need to `sudo make install`) ... I still suggest to use brew instead.
