### ISSUE TITLE
Unable to launch bettercap because of the RUBY issue

### ISSUE THREAD

**Issue by JamesViktor** [bettercap/bettercap#236]
# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment
Kali 2018

Please provide:

* Bettercap version you are using. -- v2.4
* OS version and architecture you are using. -- Kali
* Go version if building from sources.
* Command line arguments you are using.--> Simply run the command bettercap
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ). not working

### Steps to Reproduce

1. *First Step*
installing it with apt-get install bettercap
2. *Second Step*
Try to configure it but got the error

checking for capable yacc/bison... insufficient
configure: error: yacc is insufficient to compile libpcap.
 libpcap requires Bison, Berkeley YACC, or another YACC compatible with them.

But its not working.
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 
Error while i am running bettercap 

Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
	11: from /usr/bin/bettercap:19:in `<main>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/vendor_ruby/bettercap.rb:21:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/vendor_ruby/em-proxy.rb:5:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /usr/lib/ruby/vendor_ruby/eventmachine.rb:8:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- rubyeventmachine (LoadError)

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
you are using the old ruby version
