### ISSUE TITLE
support for traffic redirect from host A -> host B

### ISSUE THREAD

**Issue by bmaia** [bettercap/bettercap#238]
I needed to redirect traffic from one host to another (without any proxying) during arp spoofing attacks. As far as I know, it's not possible to do that using the tcp_proxy.go and I wrote a quick hack to handle that:

https://gist.github.com/bmaia/73f796e970e8eb9e7cd846620bba58b4#file-tcp_proxy-go-L6-L12

I wonder if that would be useful as a module or a tcp_proxy option? I can send a pull request for this, but I would like your opinion before.

Thanks!

**Comment by evilsocket** [comment]
mmm i like the idea per se, but wouldn't it be better (and more efficient I guess?) implemented as an [packet.proxy](https://github.com/bettercap/bettercap/wiki/packet.proxy) native module instead? That way, it works on every IP encapsulated thing as long as this module patches IP headers properly.

The downside of this: Linux only.

Otherwise, yeah, it'd make sense to implement it as an optional behaviour for the `tcp.proxy`, keeping in mind that at some point it might be required to do the same for an `udp.proxy` module if it'll ever be implemented.

**Comment by bmaia** [comment]
I didn't like the idea of using packet.proxy at first because I was testing it on macOS...

I wrote some optional flags for the `tcp.proxy`, but I thought it was confusing because it has to bind an address for the local proxy, for example. My idea was to basically copy and paste `tcp.proxy` and create something like `tcp_redirect` with the changes.

**Comment by evilsocket** [comment]
yeah, a new module is better (it's not tha complicated after all and I can abstract the common logic in a separate base_tcp_proxy or whatever :D) ... given that it could also be used to tunnel non spoofed traffic, what do you think about naming it `tcp.tunnel` instead?

**Comment by evilsocket** [comment]
@bmaia hello?

**Comment by bmaia** [comment]
Yeah looks good to me, you want me to send a PR with the renamed `tcp.proxy` with the tunneling capability or are you going to change the logic before and do that yourself?

Also, there's still the possibility of having the `packet.proxy` for linux only, but I still think that having the `*.tunnel` would be useful for other platforms.

**Comment by evilsocket** [comment]
i can work on it but not now, very busy recently, so if you want to send a PR that's more than welcome :)

**Comment by bmaia** [comment]
I made some more tests and it actually makes more sense to use the `tcp.proxy` module for tunneling. The two optional flags are named tcp.tunnel.address and tcp.tunnel.port, please check if it makes sense for you or if you prefer something like `tcp.proxy.tunnel.address` and `tcp.proxy.tunnel.port` for example.

```
            tcp.port : Remote port to redirect when the TCP proxy is activated. (default=443)
         tcp.address : Remote address of the TCP proxy. (default=)
   tcp.proxy.address : Address to bind the TCP proxy to. (default=<interface address>)
      tcp.proxy.port : Port to bind the TCP proxy to. (default=8443)
    tcp.proxy.script : Path of a TCP proxy JS script. (default=)
  tcp.tunnel.address : Address to redirect the TCP tunnel to (optional). (default=)
     tcp.tunnel.port : Port to redirect the TCP tunnel to (optional). (default=0)
```

I also sent a PR with the rogue-mysql-server caplet and a documentation on how to use it:

https://github.com/bettercap/caplets/pull/14

**Comment by evilsocket** [comment]
perfect, thanks! <3

**Comment by bmaia** [comment]
Updated documentation: https://pastebin.com/UArd6FQM

**Comment by evilsocket** [comment]
<3
