### ISSUE TITLE
Add support to monitor device probe requests

### ISSUE THREAD

**Issue by rafaleon69** [bettercap/bettercap#240]
Since adapter integration is included it would be a nice touch to track and map probe responses of the devices connected to the networks as well as foreign ones as well. Would that be possible ?

Nifty tool! I still need to figure out how to sniff WiFi traffic from connected users like I did with previous version of bettercap by using -X -I wlanX...

**Comment by evilsocket** [comment]
> robe responses of the devices connected to the networks

what networks?

> foreign ones

what does this mean?

> would that be possible ?

the wifi.recon module already track WiFi clients rather than just APs if that's what you mean.


If you have doubts, read the wiki https://github.com/bettercap/bettercap/wiki
