### ISSUE TITLE
[Question][Feature] Hostname resolution (mDNS, NBNS)

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#244]
What do you think about adding hostname resolution for non-aliased users? I can work on the PR, but want to know what you think about the feature and maybe if you have any design suggestions. 
Ex:
```
+----------------+--------------------+----------+---------------------------+---------+---------+------------+
|      IP        |        MAC         |  Name    |          Vendor           |  Sent   | Recvd   | Last Seen  |
+----------------+--------------------+----------+---------------------------+---------+---------+------------+
| 192.168.1.120  | xx:xx:xx:xx:xx:xx  | en1      | Apple                     | 169 kB  | 72 kB   | 12:40:53   |
| 192.168.1.1    | xx:xx:xx:xx:xx:xx  | gateway  | Tp-link Technologies Co.  | 27 kB   | 0 B     | 12:40:53   |
|                |                    |          |                           |         |         |            |
| 192.168.1.100  | xx:xx:xx:xx:xx:xx  | sam.local|                           | 31 kB   | 0 B     | 12:43:09   |
+----------------+--------------------+----------+---------------------------+---------+---------+------------+
```
Maybe also parse `net.sniff` packets 
```
[12:54:07] [net.sniff.leak.udp] udp 192.168.1.100:mdns > 224.0.0.251:mdns 224 bytes map[Size:%!s(int=224)]
[12:55:10] [net.sniff.leak.udp] udp 192.168.1.103:netbios-ns > 192.168.1.255:netbios-ns 58 bytes map[Size:%!s(int=58)]
```
### Environment

Please provide:

* Bettercap version you are using.
bettercap v2.5 (HEAD)
* OS version and architecture you are using.
Darwin Macbook.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
* Go version if building from sources.
go version go1.10.1 darwin/amd64

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
anything more complex than this would be a overhead imo https://github.com/bettercap/bettercap/blob/master/network/lan_endpoint.go#L67

**Comment by alexmozzhakov** [comment]
@evilsocket just to be clear, what are you referring to by _this_?

**Comment by evilsocket** [comment]
the dns resolution the tool already performs, link to the source ... i don't like the idea of coupling lan endpoints to the net.sniff module

**Comment by alexmozzhakov** [comment]
@evilsocket 👌 thanks

**Comment by evilsocket** [comment]
:+1:
