### ISSUE TITLE
Kali Linux WSL platform 

### ISSUE THREAD

**Issue by rex007r** [bettercap/bettercap#245]
[E] Oooops, seems like something weird occurred, please copy paste the following output and open a new issue on https://github.com/evilsocket/bettercap/issues :

[E] Platform          : x86_64-linux-gnu
[E] Ruby Version      : 2.5.1
[E] BetterCap Version : 1.6.2
[E] Command Line      : -I wifi0 --random-mac
[E] Exception         : NoMethodError
[E] Message           : undefined method `split' for nil:NilClass
[E] Backtrace         :

    /usr/lib/ruby/vendor_ruby/bettercap/network/target.rb:118:in `normalized_mac'
    /usr/lib/ruby/vendor_ruby/bettercap/context.rb:88:in `update!'
    /usr/lib/ruby/vendor_ruby/bettercap/options/options.rb:68:in `parse!'
    /usr/bin/bettercap:30:in `<main>'
![3](https://user-images.githubusercontent.com/38832608/39405565-dee74fe0-4bc4-11e8-9952-74b3853ee34a.PNG)
![2](https://user-images.githubusercontent.com/38832608/39405566-e556d22e-4bc4-11e8-8b37-0e0a05f6bf0d.PNG)
![1](https://user-images.githubusercontent.com/38832608/39405568-eb63e666-4bc4-11e8-9550-aa04a00a7924.PNG)

Any Solution???

**Comment by evilsocket** [comment]
you're using the old ruby version, switch to a newer release and have fun! ;)

https://github.com/bettercap/bettercap/releases

**Comment by rex007r** [comment]
![1](https://user-images.githubusercontent.com/38832608/39416184-a41390be-4c68-11e8-978d-9ad3f27834f3.PNG)

no dude !!!

the problem is script cant define actual mac & interface

**Comment by evilsocket** [comment]
No "dude", the problem is you just didn't care to understand what I wrote ... again, you are using an old version (which was made in Ruby and it's not supported anymore), the new version is completely different, use that one.
