### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by Cliov** [bettercap/bettercap#258]
sudo bettercap
bettercap v2.5 (type 'help' for a list of commands)
» [11:15:03] [sys.log] [inf] Checking latest stable release ...
» [11:15:03] [endpoint.new] Endpoint 192.168.2.134 detected as e4:46:da:61:76:5a.
» set [11:15:04] [sys.log] [inf] You are running 2.5 which is the latest stable version.
» set http.proxy.port 81
» set https.proxy.port 8443
» set http.proxy.script /caplets/inject.js
» set https.proxy.script /caplets/inject.js
» https.proxy on
[11:15:52] [sys.log] [inf] Loading proxy certification authority TLS key from /var/root/.bettercap-ca.key.pem
» panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4575c79]
goroutine 103 [running]:
github.com/bettercap/bettercap/modules.(*HTTPProxy).Start.func1(0xc42133e510)
	/Users/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:310 +0x189
created by github.com/bettercap/bettercap/modules.(*HTTPProxy).Start
	/Users/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:302 +0x3f

**Comment by alexmozzhakov** [comment]
@Cliov complete the report, please
