### ISSUE TITLE
Missing stdout in interactive session

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#266]
Bettercap does not always show every (info) log.

### Environment

Please provide:

* Bettercap version you are using.
`2.5`
* OS version and architecture you are using.
`Linux ghxst 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux`
* Go version if building from sources.
`go1.10rc2 linux/amd64`
* Command line arguments you are using.
`bettercap -caplet caplets/test.cap`
* Caplet code you are using or the interactive session commands.
```sh
set testvar1 testval1
set testvar2 testval2
set testvar3 testval3
```

### Output (without debug)

```sh
root@ghxst:~# bettercap -caplet caplets/test.cap
bettercap v2.5 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.19  » [14:17:53] [sys.log] [inf] Reading from caplet caplets/test.cap ...
192.168.1.0/24 > 192.168.1.19  » exit

Stopping modules and cleaning session state ...
root@ghxst:~# bettercap -caplet caplets/test.cap
bettercap v2.5 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.19  » [14:18:03] [sys.log] [inf] Checking latest stable release ...
192.168.1.0/24 > 192.168.1.19  » [14:18:06] [sys.log] [inf] You are running 2.5 which is the latest stable version.
192.168.1.0/24 > 192.168.1.19  » exit

Stopping modules and cleaning session state ...
root@ghxst:~# bettercap -caplet caplets/test.cap 
bettercap v2.5 (type 'help' for a list of commands)

[14:18:13] [sys.log] [inf] Reading from caplet caplets/test.cap ...
192.168.1.0/24 > 192.168.1.19  » [14:18:15] [sys.log] [inf] You are running 2.5 which is the latest stable version.
192.168.1.0/24 > 192.168.1.19  » exit

Stopping modules and cleaning session state ...
```

### Output (with debug)

```sh
root@ghxst:~# bettercap -caplet caplets/test.cap -debug
bettercap v2.5 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.19  » [14:41:22] [sys.log] [inf] You are running 2.5 which is the latest stable version.
192.168.1.0/24 > 192.168.1.19  » exit
[14:41:31] [mod.stopped] events.stream

Stopping modules and cleaning session state ...
root@ghxst:~# bettercap -caplet caplets/test.cap -debug
bettercap v2.5 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.19  » [14:41:34] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.19  » [14:41:34] [sys.log] [inf] Checking latest stable release ...
192.168.1.0/24 > 192.168.1.19  » [14:41:36] [sys.log] [inf] You are running 2.5 which is the latest stable version.
192.168.1.0/24 > 192.168.1.19  » exit
[14:41:52] [mod.stopped] events.stream

Stopping modules and cleaning session state ...
root@ghxst:~# bettercap -caplet caplets/test.cap -debug
bettercap v2.5 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.19  » [14:41:54] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.19  » [14:41:55] [sys.log] [inf] You are running 2.5 which is the latest stable version.
192.168.1.0/24 > 192.168.1.19  » exit
[14:42:08] [mod.stopped] events.stream

Stopping modules and cleaning session state ...
```

### Steps to Reproduce

1. Start bettercap and load a caplet `bettercap -caplet caplets/fb-phish.cap`
2. Wait 10s and exit bettercap
3. Keep repeating steps 1 and 2 to see missing logs

### Expected behavior

Every (info) event is logged.

### Actual behavior

I wait at least 10 seconds during each session, and you can see how sometimes it doesn't log every info event that takes place. 

Notice how the reading of a caplet is sometimes not logged.

**Comment by evilsocket** [comment]
at the beginning some logs might be missed as the event stream is still starting, do you see missing logs also after bettercap started?

**Comment by yungtravla** [comment]
No missing logs, but I do miss a lot of the first (yellow) part of the logs:


![screenshot from 2018-05-11 04-35-00](https://user-images.githubusercontent.com/29265684/39888129-49f34486-54d7-11e8-8f96-8f1f68435293.png)

**Comment by alexmozzhakov** [comment]
@evilsocket seems good, except for 
```
192.168.1.0/24 > 192.168.1.19  » ble.enum xx:xx:xx:xx:xx:xx
[18:30:04] [sys.log] [inf] Connecting to xx:xx:xx:xx:xx:xx
```

**Comment by yungtravla** [comment]
I'm still missing some too

![screenshot from 2018-05-14 18-05-19](https://user-images.githubusercontent.com/29265684/40035893-777f1e8e-5847-11e8-8831-499adb3680c9.png)

**Comment by evilsocket** [comment]
not sure what i'm supposed to see from that screenshot :/

**Comment by yungtravla** [comment]
2 lines are missing the yellow string and don't line up with the other logs.

**Comment by evilsocket** [comment]
"the yellow string" is the prompt, those logs don't always line up, depending on the position of the log, your cursor, etc ... this issue is about missing lines, not misaligned lines :D

**Comment by yungtravla** [comment]
Are they purposely not showing the yellow string?

**Comment by yungtravla** [comment]
I didn't return any input so that's an uninterrupted stream

**Comment by evilsocket** [comment]
The two things are not related ( the prompt and logs are printed asynchronously ) and this issue is about missing logs (due to failed writes on the `events.stream` events channel ), which was fixed.

> I didn't return any input so that's an uninterrupted stream

Not sure what you mean, but there's nothing uninterrupted here, just the thread printing the prompt and the one printing logs overlapping sometimes, which is normal being them two different things.

**Comment by yungtravla** [comment]
Ahh I getcha
