### ISSUE TITLE
Bettercap Launch Fail

### ISSUE THREAD

**Issue by iforgotmynametoday** [bettercap/bettercap#270]
Bettercap is not launching after I've entered the 'sudo bettercap' command that starts it up. It stops suddenly and gives this error

E] Oooops, seems like something weird occurred, please copy paste the following output and open a new issue on https://github.com/evilsocket/bettercap/issues :

[E] Platform          : x86_64-linux-gnu
OS                        : Ubuntu 18.04 LTS
[E] Ruby Version      : 2.5.1
[E] BetterCap Version : 1.6.2
[E] Command Line      :
[E] Exception         : Errno::ENOENT
[E] Message           : No such file or directory - netstat
[E] Backtrace         :

    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:25:in ``'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:25:in `block in execute'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:23:in `times'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:23:in `execute'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/network/network.rb:20:in `get_gateway'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/context.rb:117:in `update!'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/options/options.rb:68:in `parse!'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/bin/bettercap:30:in `<top (required)>'
    /usr/local/bin/bettercap:23:in `load'
    /usr/local/bin/bettercap:23:in `<main>'

**Expected behavior:** *Normal start up of bettercap that sniffs addresses of devices connected to the network I'm on*

**Comment by evilsocket** [comment]
you are using the old ruby version, update to the latest one

**Comment by iforgotmynametoday** [comment]
Solved it by installing net-tools with "sudo apt install net-tools"

**Comment by alexmozzhakov** [comment]
🤦‍♂️
