### ISSUE TITLE
Some logs are not showing the subnet and iface ip

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#277]
Some logs are missing the first yellow part showing the `subnet > iface.ipv*`.

### Environment

Please provide:

* Bettercap version you are using.
`v2.6`
* OS version and architecture you are using.
`Linux aiJi2o 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux`
* Go version if building from sources.
`go version go1.10rc2 linux/amd64`
* Command line arguments you are using.
`sudo bettercap`
* Caplet code you are using or the interactive session commands.
```sh
set net.sniff.verbose on
net.sniff on
```
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
![](https://user-images.githubusercontent.com/29265684/40035893-777f1e8e-5847-11e8-8831-499adb3680c9.png)

### Steps to Reproduce

1. Start bettercap with `sudo bettercap -debug`
2. In the interactive session enter `set net.sniff.verbose on; net.sniff on`
3. Wait for logs that are missing the string with yellow background.

**Expected behavior:** All logs show the subnet and iface ip so the logs line up and are easy to skim through.

**Actual behavior:** Some logs are missing the first yellow part showing the `subnet > iface.ipv*`.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
again, this is not a bug, the "yellow part" is not part of the logs at all

>  All logs show the subnet and iface ip so the logs line up and are easy to skim through.

no, this is just a wrong assumption as the two things are not related.

**Comment by evilsocket** [comment]
yes
