### ISSUE TITLE
Arp spoofing in bettercap on different bands not working

### ISSUE THREAD

**Issue by rafaleon69** [bettercap/bettercap#278]
Dear Simone, I really like your work, I think you have done one of a kind job. I have spend a whole day, reading a manual (thank you for sending me back in the past to RTFM - the cat is really cute) and exploring the features of bettercap and I know I will not be done for another few days, there is just so much to learn! But thank you, I really enjoy the process even though it has it's setbacks sometimes.

Finally I have managed to clarify the issues (due to my lack of knowledge) I had in the past and the app finally works as it should, however, if I may...

*Description of the bug or feature request*

When running arp.spoof in an interactive session (arp.spoof on) or using the caplet provided http-req-dump.cap I have managed to "sniff" the http and https requests on the network without any issues only if my devices and the wireless card connected to the network (running bettercap) is on the same frequency 5ghz or 2.4Ghz. Once the device switches to other band, different than one running bettercap it results in no connection to the internet for the spoofed device. I have tried to see if running net.probe after the switch fixes it but it did not. Is there something I am doing wrong again or is it the general issue with the nature of ARP spoofing ? 

### Environment

I have tested the issue on Kali Linux 2018 both on my laptop running by default a 5Ghz card and a Rpi3 with Kali Linux 2018 running 2.4Ghz by default. I was running latest, stable 2.6 version in both cases,

**Expected behavior:** *What you expected to happen*

"arp.spoof on" to work with devices connected to both bands. In simple terms I can spoof only one band at the time to execute successful MITM.

**Actual behavior:** *What actually happened*

Devices on different bands result in no or delayed internet connection even if selected a specific target instead of whole network.

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
lol ... no logs, no versions, nothing ... nice.

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**
