### ISSUE TITLE
arp spoofing is not working when devices are on different bands

### ISSUE THREAD

**Issue by rafaleon69** [bettercap/bettercap#279]
I see you are not a chatty one.

# Prerequisites

*Description of the bug or feature request*
Bug: arp spoofing is not working when devices are on different bands. Arp.spoof on 5GHZ can only successfully spoof devices connected to 5Ghz network and vice versa, The ones connected to 2.4GHZ on the same network result in no internet connection when bettercap is spoofing from 5Ghz. 

### Environment

Please provide:

* Bettercap version you are using.
2.6 latest stable
* OS version and architecture you are using.
Kali Linux 2018 x64
* Go version if building from sources.
go version go1.10.1 linux/amd64
* Command line arguments you are using.
sudo ./bettercap -caplet caplet/http-req-dump.cap -eval "set arp.spoof.targets 192.168.1.101" - debug
or sudo ./bettercap + interactive session caplet; include caplet
* Caplet code you are using or the interactive session commands.
include caplet/http-req-dump.cap

or

set arp.spoof.targets 192.168.1.101
arp.spoof on

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

[23:30:44] [sys.log] [dbg] Skipping address 192.168.1.1 from UDP probing.
[23:30:45] [sys.log] [inf] You are running 2.6 which is the latest stable version.
[23:30:45] [mod.stopped] update
[23:30:45] [mod.stopped] net.probe
[23:30:45] [mod.started] net.sniff
[23:30:45] [sys.log] [dbg]  addresses=[192.168.1.101] macs=[] whitelisted-addresses=[] whitelisted-macs=[]
[23:30:45] [mod.started] arp.spoof
[23:30:45] [sys.log] [inf] ARP spoofer started, probing 1 targets.
[23:30:45] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:46] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:47] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:48] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:49] [mod.started] ticker
[23:30:49] [sys.log] [inf] Ticker running with period 1s.
[23:30:49] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:50] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:51] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:52] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:53] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
[23:30:54] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » ticker off
192.168.1.0/24 > 192.168.1.102  » [23:30:55] [mod.stopped] ticker
192.168.1.0/24 > 192.168.1.102  » [23:30:55] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:30:56] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:30:57] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:30:58] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:30:59] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:00] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:01] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:02] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:03] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:04] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:05] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:06] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:07] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:08] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:09] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:10] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:11] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:12] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:13] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.
192.168.1.0/24 > 192.168.1.102  » [23:31:14] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.101:ac:cf:85:75:35:d8.

### Steps to Reproduce

1. *First Step*
run arp.spoof in bettercap with the above command on either 5Ghz or 2.4Ghz network
2. *Second Step*
Watch devices connected to opposite bands result in no internet connection or really dealyed.
3. *and so on...*

**Expected behavior:** *What you expected to happen*
Bettercap to successfully spoof devices connected to both bands.
**Actual behavior:** *What actually happened*
arp spoofing is not working when devices are on different bands.

Thanks.
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Sometimes this is due to some sort of isolation in the router, what model is it?

**Comment by rafaleon69** [comment]
TP Link Archer AC1600, VR600(EU) Ver. 2.0 Wireless Gigabit VDSL/ADSL Modem Router

**Comment by evilsocket** [comment]
Hi, I've finally managed to do some testing on my router, very similar to yours, and I had no issues spoofing targets on the 5Ghz from the 2.4Ghz and viceversa ... there's some IP isolation going on on your router, which is preventing bettercap from doing that

**Comment by ChillVibesMushroom** [comment]
> Hi, I've finally managed to do some testing on my router, very similar to yours, and I had no issues spoofing targets on the 5Ghz from the 2.4Ghz and viceversa ... there's some IP isolation going on on your router, which is preventing bettercap from doing that

@evilsocket what should I do about IP isolation on my router I've tried port forwarding ipv4:80 externalhost to myipv4:80 internal host and using ncat -v targetipv4:80 to see if I can connect and it says no route to host hmmmm
