### ISSUE TITLE
ctrl-d does not exit

### ISSUE THREAD

**Issue by digininja** [bettercap/bettercap#283]
![better](https://user-images.githubusercontent.com/117081/40492676-f2b49f02-5f68-11e8-989d-14bc6d33c6ae.png)
ctrl-d prints exit and a new line into the terminal but doesn't actually exit the app. Typing exit and hitting enter does exit

### Environment

Please provide:

* Bettercap version you are using.
GitHub Master 24/5/18

* OS version and architecture you are using.
Ubuntu 16.04 64 bit

* Go version if building from sources.
* Command line arguments you are using.
None

* Caplet code you are using or the interactive session commands.

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
nothing extra with debug enabled

### Steps to Reproduce

1. run app
2. hit ctrl-d

**Expected behavior:** *What you expected to happen*
Should exit

**Actual behavior:** *What actually happened*
doesn't exit

**Comment by alexmozzhakov** [comment]
Duplicate of #217

**Comment by digininja** [comment]
Fair enough.
