### ISSUE TITLE
nfqueue - build constraints exclude all Go files in ...

### ISSUE THREAD

**Issue by gudata** [bettercap/bettercap#285]
# Issue
I can't install with 
```
go get -u github.com/bettercap/bettercap
```

or

```
go get github.com/bettercap/bettercap
```

Maybe the problem is in the nfqueue - don't know. I am making my first steps in go.

# Prerequisites

```
sudo apt install libpcap-dev
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpcap-dev is already the newest version (1.8.1-6ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

go get -u github.com/bettercap/bettercap
```
package github.com/bettercap/bettercap/vendor/github.com/chifflier/nfqueue-go/nfqueue: build constraints exclude all Go files in /home/user/.local/gvm/pkgsets/go1.10/global/src/github.com/bettercap/bettercap/vendor/github.com/chifflier/nfqueue-go/nfqueue
```


### Environment

Please provide:

Ubuntu 18.04 LTS Bionic Beaver
Linux  4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

gvm list
```
gvm gos (installed)

=> go1.10
   go1.4
   go1.9

```


* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

**Comment by gudata** [comment]
I did the link pointed here https://github.com/bettercap/bettercap/wiki/Known-Issues
```
sudo ln -s  /usr/lib/x86_64-linux-gnu/libpcap.so.1.8.1 /usr/lib/libpcap.so.1
```

but doesn't help

**Comment by evilsocket** [comment]
as the README indicates:

> Make sure you have ... the libpcap-dev and libnetfilter-queue-dev packages installed

you need to install `libnetfilter-queue-dev`
