### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Deathlive** [bettercap/bettercap#289]
At startup Segmentation fault.

Bettercap latest version.
Linux: https://alpinelinux.org

- installed go, libpcap-dev, netfilter_queue.
- later go get github.com/bettercap/bettercap
- the installation was successful.
but after the launch, **segmentation fault error**.

**Comment by evilsocket** [comment]
**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**
