### ISSUE TITLE
Bypass https

### ISSUE THREAD

**Issue by karencho777** [bettercap/bettercap#291]
Hello , i am using Kali linux 2018.2 and the latest version  of bettercap!

How can i configure the Bettercap so i can bypass ssl and hsts? 

now i have done this configuration : 

bettercap -iface wlan0, then i turned on arp.spoof on ... 

then i turn on https.proxy on and https.proxy.sslstrip true

then give the target arp.spoof.target 192.168.1.64 ...

and the bettercap gives me an errors : 

Client does not support SNI.
Error reading SNI: record overflow.

what o am doing wrong?

**Comment by yungtravla** [comment]
If you could just choose to bypass SSL then I don't see a need for its existence.

What you can do is wait for a user to visit a site without SSL, and sniff that data or lure them into clicking onto a sslstripped link. You can use the built-in sslstrip module or you can use <a href="https://github.com/bettercap/caplets/tree/master/hstshijack">this caplet</a> to sslstrip and also spoof domain names.

I suggest you do some reading on SSL and HSTS before you plan to attack these protocols.
