### ISSUE TITLE
Wifi rogue ap is not showing up after activation

### ISSUE THREAD

**Issue by tweidinger** [bettercap/bettercap#295]
I am trying to run a fake AP on an PI3 with an TP-LINKWN722N 3rd gen.
Wifi recon is working and I can get all informations about the clients/base stations around.
After creating a rogue access point like in the wiki, it says its sending the beacons but
no AP is shown on multiple devices around, after trying it with multiple settings.

### Environment

Please provide:

* Bettercap version you are using.
2.6
* OS version and architecture you are using.
Kali for ARMv6
* Go version if building from sources.
go1.10.3.linux-armv6l
* Command line arguments you are using.
Interactive mode with putting in the example code from the wiki
> set wifi.ap.ssid Banana
> set wifi.ap.bssid DE:AD:BE:EF:DE:AD
> set wifi.ap.channel 5
> set wifi.ap.encryption false
> wifi.recon on; wifi.ap

### Steps to Reproduce

1. Install bettercap with go get on an Raspberry Pi with Kali
2. Create monitoring interface with airmon-ng
3. Use created wlan1mon interface for bettercap
4. Start in interactive mode and try out the example above

**Expected behavior:** 
A wifi access point with ssid Banana will show up on multiple devices around

**Actual behavior:** 
No access point visible

**Comment by tweidinger** [comment]
Hey, most likely this is not a bettercap issue and instead a driver problem in the kernel,
since after verifying changing to monitor mode with airmon-ng showed errors aswell.
Thanks for your helpful question :)

**Comment by yungtravla** [comment]
TP-Link WN722N version 2 and above have been a total nightmare for me :smile:

**Comment by yungtravla** [comment]
@tweidinger maybe Dogcatfee's comment could be of help here: https://github.com/abhijeet2096/TL-WN722N-V2/issues/3

I haven't tried it but it seems to have gained positive responses.

**Comment by kand617** [comment]
I am seeing the same behavior with v1 of the adapter. 
I have the interface on monitor mode (if that makes a difference)
Also I am able to create an AP using Kali's Create Hotspot function....

**Comment by tweidinger** [comment]
@yungtravla Thanks for the reference, but for me it didnt work out :(. I just ordered an Alfa AWUS036ACH Dual Band USB Adapter AC1200 and will hopefully get it to work.

The reference driver for v3 from TP-Link supports monitor mode more or less only in Ubuntu and ~Kernel 3.8.x. Perhaps it will support this officially with debian(kali) and a newer kernel.

**Comment by soelkongen** [comment]
I'm trying to start the AP with my AWUS036ACH, but nothing shows up. Kali can create a hotspot that shows up. 
I have also tried with the TP-Link WN722N v1, didn't work either
