### ISSUE TITLE
Wifi: Feature Request - ESS/BSS filtering

### ISSUE THREAD

**Issue by mlinton** [bettercap/bettercap#296]
Wifi modules are awesome, looking for a feature to filter the BSSID or ESSID by regex, so the first 6 bytes of the BSSID, or a portion of the ESSID name.  Would make targeting much easier.

Thanks again!

**Comment by yungtravla** [comment]
Even easier would be to have tab completion, thoughts?

**Comment by evilsocket** [comment]
closed in 573cb17735ff2e58e92867a163773321f28c270e
