### ISSUE TITLE
Parsing wireshark manuf instead of oui.dat

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#303]
In order to properly handle vendors bettercap needs some changes in MAC ranges logic. Smaller vendors sometimes are given MAC ranges, just like an IP network.  Ex:
```
00:50:C2:6E:E0:00/36	Interact	Interactive Electronic Systems
00:50:C2:6E:F0:00/36	Pneumopa	Pneumopartners LaenneXT SA
00:50:C2:6F:00:00/36	StanleyS	Stanley Security Solutions, Inc.
```
Also, the wireshark manuf list in more complete as it includes IEEE public OUI listing (which is partially included now in `.dat`) with community contributions. We can then exclude `.dat` from this repo and only download a file from wireshark.org while running `make_oui.py` script. 
What do you think?

The file itself is in:
https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf;hb=HEAD

PS. the list is published under `GPL-2.0-or-later`

**Comment by evilsocket** [comment]
@alexmozzhakov this feature update has been great, I can finally lookup 99.9% of the MACs on my test networks, that's great! :D Thanks Alex

**Comment by alexmozzhakov** [comment]
@evilsocket have fun with that 😄
