### ISSUE TITLE
sudo problems rpi3

### ISSUE THREAD

**Issue by b0n3zx** [bettercap/bettercap#305]
Im using the latest update 2.7 with golang 1.9 and compiled on rpi3b arm device.  for some reason it wont run with sudo, says command not found.  raspbian 2018-06-27 kernel 4.14

pi@FYGS:~ $ sudo bettercap
sudo: bettercap: command not found
pi@FYGS:~ $ bettercap
bettercap v2.7 (type 'help' for a list of commands)

eth0: You don't have permission to capture on that device (socket: Operation not permitted)

This is what it gives me every time I compile myself.  I don't know if im just stupid and dont know this linux well enough or what.  Any insight would be greatly appreciated

**Comment by uhuhuhuhuhuhuhuh** [comment]
what do i do next
