### ISSUE TITLE
dns spoofing on Virtual Box setup "help wanted" - I have read the FM - but might be confused

### ISSUE THREAD

**Issue by TomHubGit** [bettercap/bettercap#308]
Hey there,

I am using Bettercap 2.7 on kali within a virtualized environment (Virtual Box).

I am aware of the docu at https://github.com/bettercap/bettercap/wiki/dns.spoof
But if I am missing something completely obvious or stup**, I am happy about a nudge in the right direction.

When I configure and run the DNS spoofer for a specific domain, I see the dns request (through net.sniff.leak.dns) but the lookup is not spoofed. 

Is it me, am I missing something here... 

Arp Spoofing my victim (window 7) works and I see traffic directed to the default GW. 

Thanks!

Tom

### Environment

Please provide:

* Bettercap version you are using. - 2.7
* OS version and architecture you are using. - 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux
* Go version if building from sources. - go version go1.10.3 linux/amd64
* Command line arguments you are using. - iface eth0

### Steps to Reproduce

1. Configure arp spoof (192.168.1.23 is the victim)
arp.spoof.internal: 'true'
arp.spoof.targets: '192.168.1.23'

arp.spoof on 

2. Configure dns spoof (just some test stuff for a dedicated domain)
dns.spoof.address: '128.65.210.180'
dns.spoof.all: 'false'
dns.spoof.domains: '20min.ch'

dns.spoof on

3. DNS request is seen, being answered by the standard DNS server I entered at the victim. 
[21:08:31] [net.sniff.leak.dns] dns 1.1.1.1 > 192.168.1.15 : 20min.ch is 192.124.249.117 

**Expected behavior:** *What you expected to happen*
I would expect that the clients DNS request is intercepted through the arp spoofing and then the DNS request is spoofed with the configured IP address. 

**Actual behavior:** *What actually happened*
The dns request is resolved as usual. 

--

**Comment by evilsocket** [comment]
could you attach the logs?

**Comment by TomHubGit** [comment]
@evilsocket good hint, I will retest tomorrow and attach the logs! Thanks for your reply.

**Comment by evilsocket** [comment]
still no logs provided as requested from the issue template, closing.

**Comment by TomHubGit** [comment]
Sorry for the delay, I was quite busy. 
This is my config, enabling arp and dns spoofing while running with debug mode on:
192.168.1.0/24 > 192.168.1.23  » set dns.spoof.all true
192.168.1.0/24 > 192.168.1.23  » set dns.spoof.address 192.168.1.23
192.168.1.0/24 > 192.168.1.23  » set dns.spoof.domains spiegel.de
192.168.1.0/24 > 192.168.1.23  » set arp.spoof.internal true
192.168.1.0/24 > 192.168.1.23  » set arp.spoof.targets 192.168.1.15

What I see in the log is:
192.168.1.0/24 > 192.168.1.23  » [22:28:32] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.15:08:00:27:cd:43:f1.
192.168.1.0/24 > 192.168.1.23  » [22:28:32] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.15:08:00:27:cd:43:f1.
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [inf] [dns] Sending spoofed DNS reply for spiegel.de (->192.168.1.23) to 192.168.1.15 : 08:00:27:cd:43:f1 ( PCS Systemtechnik GmbH ).
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Sending 98 bytes of packet ...
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [inf] [dns] Sending spoofed DNS reply for spiegel.de (->192.168.1.23) to 08:00:27:dc:82:12.

However on the victim DNS resolution is normal.
What I also see is that for hosts and subdomains of the domain spiegel.de, no DNS spoofing is execute:
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn4.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn4.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn2.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn2.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn1.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn1.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn3.spiegel.de
192.168.1.0/24 > 192.168.1.23  » [22:28:33] [sys.log] [dbg] Skipping domain cdn3.spiegel.de

@evilsocket would this be enough logging to get an idea?

**Comment by TomHubGit** [comment]
I guess my setting was wrong. Spoofing domain should be explicitly *.spiegel.de, correct?

**Comment by evilsocket** [comment]
@TomHubGit yes, correct, do you have different results by using `*.spiegel.de` ? I should document this parameter better i guess ...

**Comment by evilsocket** [comment]
hello?

**Comment by TomHubGit** [comment]
Hey, just crazy project work at the moment. 

But yes, it seems like the * works differently. But I have to check again. I will keep wireshark running on the client and see whats happening. 
Even a local dnsflush didnt worked reliable. 

(sorry for the slow answers, customers are quite demanding these days ;)

**Comment by TomHubGit** [comment]
When I start bettercap on my Kali box (192.168.1.23) it immediately recognizes the Win box (192.168.1.15). 

The settings have been done as stated below:
```
[21:53:35] [endpoint.new] Endpoint 192.168.1.15 detected as 08:00:27:cd:43:f1 (PCS Systemtechnik GmbH)

set dns.spoof.address 192.168.1.23
set dns.spoof.domains spiegel.de
set dns.spoof.all true
set arp.spoof.targets 192.168.1.23
set arp.spoof.internal true

dns.spoof on
[21:57:24] [sys.log] [inf] Enabling forwarding.
arp.spoof on
[21:57:26] [sys.log] [war] ARP spoofer started targeting 254 possible network neighbours of 1 targets.

```
When I flush the DNS cache on my Win box I still get the official results. 
```
PS C:\Users\Victim> nslookup www.spiegel.de
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    aacfb9d106f4.link11.de
Addresses:  128.65.210.180
          128.65.210.181
          128.65.210.182
          128.65.210.183
          128.65.210.184
          128.65.210.185
Aliases:  www.spiegel.de
```

What is kinda strange, on the Kali box, I see arp messages for the whole subnet, even though I specified the single IP of the win box. 

Setting a DNS filter on the Kali wireshark doesnt reveal any messages intercepted. 

Just verified the settings for arp.spoof and they seem fine:
```
192.168.1.0/24 > 192.168.1.23  » get arp.spoof.internal 

  arp.spoof.internal: 'true'

192.168.1.0/24 > 192.168.1.23  » get arp.spoof.targets 

  arp.spoof.targets: '192.168.1.15'

```
<img width="1076" alt="screen shot 2018-08-20 at 22 02 28" src="https://user-images.githubusercontent.com/20123996/44363709-3a64d780-a4c5-11e8-8c42-54582a0fc7a2.png">

**Comment by TomHubGit** [comment]
This time I configured dns.spoof.domain to *.spiegel.de

The result is now visible:
192.168.1.0/24 > 192.168.1.23  » [22:07:51] [sys.log] [inf] [dns] Sending spoofed DNS reply for www.spiegel.de (->192.168.1.23) to 192.168.1.15 : 08:00:27:cd:43:f1 ( PCS Systemtechnik GmbH ).
192.168.1.0/24 > 192.168.1.23  » [22:07:51] [sys.log] [inf] [dns] Sending spoofed DNS reply for www.spiegel.de (->192.168.1.23) to 08:00:27:dc:82:12.
192.168.1.0/24 > 192.168.1.23  » [22:07:52] [sys.log] [inf] [dns] Sending spoofed DNS reply for c.spiegel.de (->192.168.1.23) to 192.168.1.15 : 08:00:27:cd:43:f1 ( PCS Systemtechnik GmbH ).

I checked Wireshark on the Kali box and it seems like it works now. Will try to configure the apache2 on Kali to respond to www.spiegel.de for final result.
Right now the browser receives a timeout.

What is still strange, nslookup is not spoofed. I still receive the official replies.

(Wireshark on the Win box is not running thanks to some .dll issues. Gotta fix that before I can proceed testing on that end)

**Comment by TomHubGit** [comment]
Hi @evilsocket, I just setup a Win server to get Wireshark up and running.

I guess this was an issue with my setup. It seems like the machines still used the original MAC address of the default GW when issuing the DNS request (even though I dont understand while I see the messages from within bettercap about spoofing dns reply).

Cheeking the arp cache on the Windows server reveals that the MAC address resolves to the Kali box. 

Interesting but I guess you can close this one. It is just my setup acting weird ;) 

Thanks again for your support and creating such a cool tool!

I use it a lot with the amazing Evilginx to demonstrate cyber security to people and why we need to raise awareness!

**Comment by evilsocket** [comment]
Glad to hear that!
