### ISSUE TITLE
Unable to sniff passwords

### ISSUE THREAD

**Issue by saikishorekate** [bettercap/bettercap#310]
I have enabled all the modules but when i am able to login in the same computer browser on http its not showing any password or header on the bettercap 2.
If i have missed anything help me out!

Thank You!

**Comment by alexmozzhakov** [comment]
@saikishorekate RTFM and complete the report?

**Comment by saikishorekate** [comment]
![image](https://user-images.githubusercontent.com/10182914/43996088-ee2ae578-9dd8-11e8-86c1-bc136f6a1474.png)
![screenshot from 2018-08-12 02-40-48](https://user-images.githubusercontent.com/10182914/43996104-45acabf6-9dd9-11e8-8bf6-169477eaf055.png)


This what i am getting the result
When i login via HTTP it's showing nothing! in bettercap.

**Comment by yungtravla** [comment]
12 logs isn't gonna tell us much...

Is that a virtual machine, or is that just your browser? You can't target your own IP.

Please give us all the info or we can't help you.

**Comment by saikishorekate** [comment]
OK! I have made a hotspot connection using mobile to the laptop and connected another computer via USB Tethering!
When I try to login anything in the computer its showing the traffic but not the HTTP passwords!
Does it works on such type of arrangement?

**Comment by torerobo** [comment]
A similar problem. Bettrcap does not maintain a log of passwords for logins from http sites. I tried Ettercap(G) and see the logins and password entered, but bettercap does not show. Perhaps there is some secret, but in the documentation I did not find anything.
Example site www.banki.ru/forum/

**Comment by yungtravla** [comment]
@torerobo you can save all data by specifying an output file for `net.sniff.output` (ie. `set net.sniff.output path/to/pcaps/sniffed-data.pcap`

 You can also use the http-req-dump.cap caplet and save the session output.

**Comment by yungtravla** [comment]
@saikishorekate we cannot help you if you describe your problem so vaguely. Please explain the issue properly, provide concise details and full debug output.

**Comment by yungtravla** [comment]
@torerobo I didn't ask for a pcap. I gave you 2 options with which you can save sniffed login credentials.

**Comment by torerobo** [comment]
@yungtravla 
Clear. Thank you.
But can I see logins and passwords in the terminal in real time? as in ettercap (G) or only when saving .pcap and then analyzing it.

**Comment by yungtravla** [comment]
@torerobo why don't you try it, or RTFM?

**Comment by alexmozzhakov** [comment]
@torerobo you may also try using https://github.com/DanMcInerney/net-creds.

**Comment by saikishorekate** [comment]
@yungtravla Before bettercap version 1 I used just connect the LAN cable to the collage network and start HTTP sniffer it automatically start displaying the headers and passwords!
When I do the same in bettercap version 2 it fails to do the same!

**Comment by torerobo** [comment]
@yungtravla 
You write see the documentation. But the documentation for bettercap 2 cat wept. Here https://github.com/bettercap/bettercap/wiki/net.sniff
and not acting here https://www.bettercap.org/legacy/.

I ask a specific question: Bettercap 2 can sniff passwords online (like in etteracap G)?
I tried it as written here https://github.com/bettercap/caplets/blob/master/simple-passwords-sniffer.cap
set net.sniff.regexp. * password =.+ (but in the terminal EMPTY!) Ettercap G sees all logins and passwords, and bettercap is silent.

Please answer the question whether bettercap supports the capture of logins and passwords in direct mode and output to the terminal / or not?

While there is no valid documentation of the meaning is completely absent in the software. I'm sorry that it's so direct.

**Comment by yungtravla** [comment]
https://github.com/bettercap/caplets/blob/master/README.md

**Comment by torerobo** [comment]
@yungtravla 
Excellent. Do you understand what I'm asking?

sudo bettercap
set arp.spoof.targets 192.168.0.101
set net.sniff.output '/home/d/Desktop/P/test.pcap'
net.sniff on

I see a connection to HTTP. I see traffic but it represents interest. I enter my login and password, bettercap is silent and does not display anything in the terminal.

net.sniff off

wireshark '/home/d/Desktop/P/test.p. And a miracle! there is also no word about login and password!

In this case, ettercap (G) output in the direct mode login and password from HTTP.

What am I doing wrong? You answer the question: bettercap can or does not know how to capture logins and passwords from the site and DISPLAY them in the terminal?

**Comment by torerobo** [comment]
So bettercap 2 is just garbage, which does not capture logins and passwords. And to grab logins and passwords you need to use ettercap

**Comment by yungtravla** [comment]
what you're doing wrong is you're not reading what it says

https://github.com/bettercap/caplets/blob/master/README.md
