### ISSUE TITLE
bettercap console comands look strange in windows

### ISSUE THREAD

**Issue by cq674350529** [bettercap/bettercap#315]
### Environment

* Bettercap version: bettercap_windows_amd64_2.7
* OS version and architecture: windows7 x86_64.

Hi, recently I need to capture some  packets through the `MITM` way, so I try to use `bettercap` in windows7. But the console commands look strange. There are some noise chars around the cmd.

![image](https://user-images.githubusercontent.com/13868458/44254205-b7c5e900-a234-11e8-8a10-fcbef5bd8b80.png)
Above bettercap console is opened by just click the `exe`.

If open the console by run `bettecap.exe` in windows cmd console, the cmd looks even weird.
 
![image](https://user-images.githubusercontent.com/13868458/44254398-4d617880-a235-11e8-8b69-14854c88089c.png)

What should I do to make it look well? Or I should try it on Linux platform?

Thanks in advance!

**Comment by benleb** [comment]
try the ```--no-color``` option

**Comment by benleb** [comment]
okay, then maybe this... https://github.com/bettercap/bettercap/issues/60

**Comment by cq674350529** [comment]
I have tried to use `betercap` in `cmder`. It works well. Thanks again.

**Comment by gvanem** [comment]
I'm no fan either of readline. Even with `bettercap.exe -no-colors`, I see junk like this:
![bettercap-colours](https://user-images.githubusercontent.com/945271/50908308-c1412f00-1429-11e9-9df2-a3b3d2b4a59a.png)

This is also typical of some curses program that think all users have black background.
