### ISSUE TITLE
Error looking up hardware address

### ISSUE THREAD

**Issue by bedawi** [bettercap/bettercap#316]
Hardware address for IP address cannot be looked up.
A workaround is pinging the device. Then it works. 

### Environment

Bettercap 2.7 and 2.8
Linux version 4.17.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-25)) #1 SMP Debian 4.17.8-1kali1 (2018-07-24)

bettercap -debug -iface wlan0
set arp.spoofing.targets x.x.x.x; arp.spoofing on

x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: ticker.period -> '1'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: mac.changer.iface -> '<interface name>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: mac.changer.address -> '<random mac>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.probe.throttle -> '10'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: arp.spoof.targets -> '<entire subnet>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: dhcp6.spoof.domains -> 'microsoft.com, goole.com, facebook.com, apple.com, twitter.com'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: dns.spoof.domains -> '*'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: dns.spoof.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: dns.spoof.all -> 'false'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.verbose -> 'true'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.local -> 'false'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.filter -> 'not arp'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.regexp -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.output -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: net.sniff.source -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.server.path -> '.'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.server.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.server.port -> '80'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.server.certificate -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.server.key -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.port -> '80'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.proxy.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.proxy.port -> '8080'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: http.proxy.script -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.port -> '443'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.proxy.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.proxy.port -> '8083'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.proxy.certificate -> '~/.bettercap-ca.cert.pem'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.proxy.key -> '~/.bettercap-ca.key.pem'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: https.proxy.script -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: tcp.port -> '443'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: tcp.address -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: tcp.proxy.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: tcp.proxy.port -> '8443'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: tcp.proxy.script -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.address -> '<interface address>'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.port -> '8083'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.username -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.password -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.certificate -> '~/.bcap-api.rest.certificate.pem'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: api.rest.key -> '~/.bcap-api.rest.key.pem'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: wifi.recon.channel -> ''
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: wifi.hop.period -> '250'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: wifi.skip-broken -> 'true'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [war] Could not find mac for x.x.x.1
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: iface.index -> '3'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: iface.name -> 'wlan0'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: iface.ipv4 -> 'x.x.x.51'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: iface.ipv6 -> '...'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: iface.mac -> '...'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: gateway.address -> 'x.x.x.51'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: gateway.mac -> '...'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: $ -> '{by}{fw}{cidr} {fb}> {env.iface.ipv4} {reset} {bold}» {reset}'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: log.debug -> 'true'
x.x.x.0/24 > x.x.x.51  » [17:00:38] [sys.log] [dbg] env.change: log.silent -> 'false'
x.x.x.0/24 > x.x.x.51  » [17:01:01] [sys.log] [dbg] Error while looking up hardware address for x.x.x.60: Could not find hardware address for x.x.x.60.

### Steps to Reproduce

1. Start bettercap: bettercap -debug -iface wlan0
2. Set a spoofing target that is not yet in the machine's arp list: set arp.spoofing.targets x.x.x.x; arp.spoofing on

**Expected behavior:** 
An ARP-request should be sent for IP.

**Actual behavior:** 
You only see the error in debug mode. Without debug mode on, the user is oblivious to the fact that arp poisoning does not work.

**Comment by AlmightyFloppyFish** [comment]
I have the same problem on my Thinkpad L560 but not on any other of my devices.

Linux 4.17.14-artix1-1-ARTIX

Happens on both Arch and Artix, No difference between docker, source compiled and precompiled installation

**Comment by evilsocket** [comment]
did you try to just enable the net.probe module? ( `net.probe on` )

**Comment by evilsocket** [comment]
basically this depends on the endpoint and how it interacts / responds / broadcasts to the network, `net.probe on` should start sending active probes to every ip in the subnet and therefore solve the problem (also make sure `net.recon` is on, which should be by default anyway)

**Comment by ChillVibesMushroom** [comment]
But then like what if it drops connections and begins with end point lost end point detected etc @evilsocket
