### ISSUE TITLE
Feature Reuqest: Show DNS queries running without DNS spoofing

### ISSUE THREAD

**Issue by mazen160** [bettercap/bettercap#317]
Hi,

I thought showing DNS queries within the network is a good idea. It's one of the features missed in the previous version.

I have tested it with the latest stable version and it's not there.

**Comment by evilsocket** [comment]
it is, both simple DNS and SNI requests are parsed by the `net.sniff` module https://github.com/bettercap/bettercap/wiki/net.sniff
