### ISSUE TITLE
Feature Request: "history" command to show previous commands

### ISSUE THREAD

**Issue by mazen160** [bettercap/bettercap#318]
Hi,

Having a "history" command to show previous commands is a cool addition. It helps on writing bettercap caplets.

Thanks!

**Comment by evilsocket** [comment]
bettercap has a default history file on `/root/bettercap.history` https://github.com/bettercap/bettercap/wiki/Interactive-Mode

**Comment by benleb** [comment]
I think it would be convenient if one could type „history“ and this file gets shown in bettercap... Yes we could use `!cat ...` but thats not the same.

@evilsocket do you not want this feature in bettercap or do you not want to implement it yourself, but a PR would be nice?

**Comment by evilsocket** [comment]
I simply don't see the need of this feature given you can access that file ... a PR would be welcome provided it follows good code quality standards.
