### ISSUE TITLE
Addition Request: exit confirmation when SIGINT is issued.

### ISSUE THREAD

**Issue by mazen160** [bettercap/bettercap#319]
Hi,

Probably a small UX addition. When clicking CTRL+C, it would be cool to have a simple prompt to confirm the exiting action.

**Comment by evilsocket** [comment]
mmm i'm not sure about it, it'd make stuff like:

```sh
# bettercap -eval "help net.probe; q"
```
more difficult to handle as exiting would always require confirmation ... any specific reason why you'd like to see this implemented?

**Comment by benleb** [comment]
A reason could be that one hits Ctrl+C to delete already typed things in the current line - like in bash.
Experienced this countless times in bettercap already 🙄😄

**Comment by mazen160** [comment]
@evilsocket 
Exactly as @benleb said. I have encountered it multiple times too.
I'm sure almost all users face the same :)


"quit" and "exit" should not encounter the prompt.
