### ISSUE TITLE
can't use bettercap precompiled on Kali

### ISSUE THREAD

**Issue by leonardoporpora** [bettercap/bettercap#320]
*Description of the bug or feature request*
Cannot run precompiled bettercap on Kali 

### Environment

Please provide:

* Bettercap version you are using. 2.8
* OS version and architecture you are using. Kali 64-bit 2018.2
* Go version if building from sources. None
* Command line arguments you are using. ./bettercap

### Steps to Reproduce

1. ./bettercap

**Expected behavior:** bettercap should work

**Actual behavior:** bettercap doesn't work

I get:" ./bettercap: error while loading shared libraries: libpcap.so.1: cannot open shared object file: no such file or directory"
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by leonardoporpora** [comment]
I have installed both libpcap-dev and libnetfilter-queue-dev

**Comment by evilsocket** [comment]
check the *known issues* section here https://github.com/bettercap/bettercap/wiki/Known-Issues

**Comment by Kyu** [comment]
Came here from google and the link is dead, this helped: 

https://linuxhint.com/install-bettercap-on-ubuntu-18-04-and-use-the-events-stream/

**Comment by Kyu** [comment]
Came here from google and the link is dead, this helped: 

https://linuxhint.com/install-bettercap-on-ubuntu-18-04-and-use-the-events-stream/
