### ISSUE TITLE
TCP.PROXY issue or PBKAC?

### ISSUE THREAD

**Issue by kloris** [bettercap/bettercap#322]
---

*Description of the bug or feature request

Hi guys (girls?), I am not sure if this is a bug or a PBKAC but when trying to make the tcp.proxy replace some bytes in a packet I get these kind of errors:

[05:27:43] [sys.log] [err] Error while executing onData callback: TypeError: 'replace' is not a function

Please find the screenshot attached for some more details as well.

### Environment

Please provide:

* Bettercap version you are using.
--> newest, 2.8
* OS version and architecture you are using.
--> Kali Linux 64 bit
* Go version if building from sources.
--> N.a.
* Command line arguments you are using.
--> ./bettercap -caplet bettercap.cap (find this attached as well)
* Caplet code you are using or the interactive session commands.
-->
# bettercap caplet
set tcp.address 192.168.2.156
set tcp.port 59950
set tcp.proxy.port 8443
set tcp.proxy.script tcp-req-dump.js
# go ^_^
tcp.proxy on

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
root@kali:~/Desktop# bettercap -caplet bettercap.cap -debug
bettercap v2.8 (type 'help' for a list of commands)

[05:34:59] [sys.log] [inf] TCP module loaded
[05:34:59] [sys.log] [dbg] TCP proxy script tcp-req-dump.js loaded.
[05:34:59] [sys.log] [inf] Enabling forwarding.
[05:34:59] [endpoint.new] Endpoint 192.168.233.1 detected as 00:50:56:c0:00:08 (VMware).
[05:34:59] [endpoint.new] Endpoint 192.168.233.254 detected as 00:50:56:ff:1b:9d (VMware).
[05:34:59] [sys.log] [dbg] Applied redirection [eth0] (TCP) 192.168.2.156:59950 -> 192.168.233.131:8443
[05:34:59] [mod.started] tcp.proxy
192.168.233.0/24 > 192.168.233.131  » [05:34:59] [sys.log] [inf] TCP proxy started ( x -> 192.168.233.131:8443 -> 192.168.2.156:59950 )
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [inf] TCP proxy got a connection from 192.168.233.1:54674
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [err] Error while executing onData callback: TypeError: 'replace' is not a function
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [dbg] 192.168.233.1:54674 -> 192.168.2.156:59950 : 13 bytes
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [err] Error while executing onData callback: TypeError: 'replace' is not a function
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [dbg] 192.168.2.156:59950 -> 192.168.233.1:54674 : 56 bytes
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [err] Error while executing onData callback: TypeError: 'replace' is not a function
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [dbg] 192.168.233.1:54674 -> 192.168.2.156:59950 : 27 bytes
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [err] Error while executing onData callback: TypeError: 'replace' is not a function
192.168.233.0/24 > 192.168.233.131  » [05:35:13] [sys.log] [dbg] 192.168.2.156:59950 -> 192.168.233.1:54674 : 17 bytes
192.168.233.0/24 > 192.168.233.131  » exit
[05:35:37] [mod.stopped] events.stream

### Steps to Reproduce

1. *First Step*
--> Run bettercap as mentioned in first step. (bettercap -caplet bettercap.cap

**Expected behavior:** *What you expected to happen*
--> That it would at least give a message as in version 2.7 like ("So and so many bytes rewritten")
**Actual behavior:** *What actually happened*
--> See the screenshot, I got this error.
-- 

Can you tell me if this is a bug or me doing stupid stuff?

Are there more examples somewhere for the TCP.PROXY as I am new to this and need some specifics..
thanks guys!
[bettercap.zip](https://github.com/bettercap/bettercap/files/2313840/bettercap.zip)

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Initially the tcp.proxy module used to pass `string` objects to the modules, they're recently being converted to byte arrays in order to fix encoding issues, that's why the `replace` method is not available anymore, because those objects are not strings.

**Comment by DavidNorena** [comment]
Yeah, but how to work then with the data in tcp.proxy, please?

**Comment by ChillVibesMushroom** [comment]
> Yeah, but how to work then with the data in tcp.proxy, please?

Im skimming through issues opened and closed on git because I got some dated information from a chat and I'm going to look through this I'm going to try your method
