### ISSUE TITLE
dns spoof is not working ?

### ISSUE THREAD

**Issue by CyberTheReape** [bettercap/bettercap#324]
BetterCap 2 and other versions do not have dns spoof ... i can't do dns spoof with bettercap 2 and other versions ....Why does the caplets folder is not have dns spoof.cap in it.... pleaase answer

**Comment by LulzsecHackz** [comment]
Idk, i have" too many open "files issue

**Comment by evilsocket** [comment]
https://github.com/bettercap/bettercap/wiki/dns.spoof
