### ISSUE TITLE
dial tcp 192.168.1.6:8080: socket: too many open files

### ISSUE THREAD

**Issue by LulzsecHackz** [bettercap/bettercap#325]
http: Accept error: accept tcp 192.168.x.y:8080: accept: too many open files; retrying in 5ms

I get this error when i open any 192.168.x.y:8080 page

Help Please? i am running mac os but i can still get helps from linux persons

**Comment by evilsocket** [comment]
the requirements for the issue have not been fullfilled, there was a form to fill you just deleted, bye.

**Comment by eenblam** [comment]
@LulzsecHackz If you're running MacOS, you can see the max number of open files with `ulimit -n` and set it with `ulimit -n $YOURLIMIT`. You'll need to run this as the same user that you're running Bettercap as, probably within the same session.

This is likely an issue with your system that you need to sort out, not an issue with Bettercap, but if you can determine that it is indeed Bettercap opening these files (see `man lsof`) then come back and fill out the issue template.

**Comment by SemiIngSoft** [comment]
@eenblam  I have the same problem but in Linux Ubuntu 18.04
