### ISSUE TITLE
ICMP redirects

### ISSUE THREAD

**Issue by phocean** [bettercap/bettercap#327]
Has *ICMP redirects* support been removed since version 2?

I see no way to configure that, and the documentation does not seem up to date or mentioning anything about that.

Thank you for any clarification.

**Comment by evilsocket** [comment]
yes, the feature has been removed as only very old and misconfigured devices are vulnerable to it, so i thought it wasn't worth being ported to the 2.x rewrite.

**Comment by phocean** [comment]
Ok, thanks. But I regret this as I still encounter such networks regularly during pentests.
