### ISSUE TITLE
Bettercap only showing --help log

### ISSUE THREAD

**Issue by asciiterminal** [bettercap/bettercap#330]
what ever i am typing in the terminal bettercap is giving me this

``flag provided but not defined: -T
Usage of bettercap:
  -autostart string
    	Comma separated list of modules to auto start. (default "events.stream, net.recon")
  -caplet string
    	Read commands from this file and execute them in the interactive session.
  -cpu-profile file
    	Write cpu profile file.
  -debug
    	Print debug messages.
  -env-file string
    	Load environment variables from this file if found, set to empty to disable environment persistence.
  -eval string
    	Run one or more commands separated by ; in the interactive session, used to set variables via command line.
  -iface string
    	Network interface to bind to, if empty the default interface will be auto selected.
  -mem-profile file
    	Write memory profile to file.
  -no-colors
    	Disable output color effects.
  -no-history
    	Disable interactive session history file.
  -silent
    	Suppress all logs which are not errors.

**Comment by yungtravla** [comment]
Please write a complete issue
