### ISSUE TITLE
cant perform dns.spoof please help

### ISSUE THREAD

**Issue by asciiterminal** [bettercap/bettercap#332]
i am trying to perform dns spoofing and i cant seem to play it 
can someone tell me step by step that would be great.

**Comment by eenblam** [comment]
@asciiterminal This issue will likely be closed unless you update it with more information.  Please fill out the issue template you deleted when you opened this.

If you haven't tried anything yet, check out the documentation for `dns.spoof` [on the wiki](https://github.com/bettercap/bettercap/wiki/dns.spoof).
