### ISSUE TITLE
Not able to sniff https password

### ISSUE THREAD

**Issue by TotoMerumeni** [bettercap/bettercap#334]
Good morning to everyone, probably I'm not writing in the right section but I really need help that I'm not finding anywhere.
I'm running Bettercap v 2.8 on Kali Linux and I need to use Bettercap for a demo on how to sniff https password but I'm not able to do it. I'm sure that it's possible to do it with this software and I'm quite sure that there are some options connected to the https.proxy modules but when i turn it on, with the arp.spoof and the net.sniff ones, I'm not able to collect password.
Please can someone help me or suggest me some guides? Thanks in advance.

**Comment by eenblam** [comment]
@TotoMerumeni please revise your issue with the template provided, and include the steps you took that didn't seem to work.

(Since you already deleted it from your initial comment, you can copy and paste it from https://github.com/bettercap/bettercap/issues/new)

**Comment by eenblam** [comment]
`set https.proxy.script caplets/http-req-dump.js`?

**Comment by TotoMerumeni** [comment]
Mmmm sorry... what do you mean?
What does this caplet do? His it in same bettercap folders or should I download it somewhere?

**Comment by eenblam** [comment]
You can get all the current caplets via `git clone https://github.com/bettercap/caplets`. This isn't a caplet but an asset used by the `http-req-dump.cap` caplet.

**Comment by eenblam** [comment]
@TotoMerumeni if you were wondering more generally about `https.proxy.script`, it allows you to pass a JS script. See https://github.com/bettercap/bettercap/wiki/http.modules and https://github.com/bettercap/bettercap/wiki/https.proxy for details.

**Comment by TotoMerumeni** [comment]
@eenblam sorry, but can you explain me better what "set https.proxy.script caplets/http-req-dump.js" will do? The wiki is not really helping me.

**Comment by Moksha10** [comment]
Check out my channel - soon I will hacking https://www.youtube.com/channel/UCSYSJwuG5Bl_o3RLqynkRpg

**Comment by Phoenix88HH** [comment]
Jjhjj
