### ISSUE TITLE
Support for http.proxy.script

### ISSUE THREAD

**Issue by zhgeek** [bettercap/bettercap#336]
Somehow, there were no signs on Bettercap for **Windows** after I have set http.proxy.script below:

function onRequest(req, res) {
 if( req.Header.indexOf('gzip') != -1 ){
  var head = res.GetHeader();
  if( head.indexOf('gzip') != -1 ) {
   req.Header = head.replace(
    'gzip',
    'identity'   _//Replace "Accept-Encoding: gzip" To "Accept-Encoding: identity"._
   );
  }
 }
}

 And I have also start http.proxy, arp.spoof, net.probe and net.sniff. **I wanna replace the
HTTP request Header Accept-Encoding to be 'identity' so that the HTTP response will be plaintext
rather than GZIP encode.** As for Ettercap, I can do this by compiling an etterfilter below, could
you teach me how to make it on Bettercap for Windows? THANK YOU!

if (ip.proto == TCP && tcp.dst == 80) {
 if (search(DATA.data, "Accept-Encoding")) {
  pcre_regex(DATA.data, "(Accept-Encoding:).*([\r\n])", "$1 identity$2");
  msg("change encoding");
 }
}

**Comment by yungtravla** [comment]
There are several errors in your proxy script. Please refer to the wiki https://github.com/bettercap/bettercap/wiki/http.modules which explains the correct syntax in detail.
