### ISSUE TITLE
How To Change HTTP Headers

### ISSUE THREAD

**Issue by RrUZi** [bettercap/bettercap#340]
function onRequest(req, res) {
	req.SetHeader('Accept','application/x-ms-application'); 
	log( "Change value." );
}

I wish to change the value of 'Accept' on an HTTP request header, is the code above correct? For there is not enough key value information of 'req' in this wiki, [https://github.com/bettercap/bettercap/wiki/http.modules](url)

**Comment by yungtravla** [comment]
It looks fine. Did you try to see if it works?
