### ISSUE TITLE
Arp.spoof is highly unstable

### ISSUE THREAD

**Issue by kdlsw** [bettercap/bettercap#343]
*Description of the bug or feature request*
Unstable, experiencing endpoint lost continuously.
### Environment
Kali Linux
Please provide:

V2.9 * Bettercap version you are using.
Linux kali 4.16.0-kali2-amd64 * OS version and architecture you are using.
installed with apt* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
```
192.168.0.0/24 > 192.168.0.104  » [15:12:34] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
192.168.0.0/24 > 192.168.0.104  » [15:12:36] [endpoint.new] endpoint 192.168.0.103 detected as xxxxxx (Hon Hai Precision Ind. Co.,Ltd.).
192.168.0.0/24 > 192.168.0.104  » [15:12:49] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
192.168.0.0/24 > 192.168.0.104  » [15:12:52] [endpoint.new] endpoint 192.168.0.103 detected as xxxxxx (Hon Hai Precision Ind. Co.,Ltd.).
192.168.0.0/24 > 192.168.0.104  » [15:13:04] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
192.168.0.0/24 > 192.168.0.104  » [15:13:07] [endpoint.new] endpoint 192.168.0.103 detected as xxxxxx (Hon Hai Precision Ind. Co.,Ltd.).
192.168.0.0/24 > 192.168.0.104  » [15:13:19] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
192.168.0.0/24 > 192.168.0.104  » [15:13:22] [endpoint.new] endpoint 192.168.0.103 detected as xxxxxx (Hon Hai Precision Ind. Co.,Ltd.).
192.168.0.0/24 > 192.168.0.104  » [15:13:34] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
192.168.0.0/24 > 192.168.0.104  » [15:13:37] [endpoint.lost] endpoint 192.168.0.102 (Intel Corporate) lost.
192.168.0.0/24 > 192.168.0.104  » [15:13:38] [endpoint.new] endpoint 192.168.0.103 detected as xxxxxx (Hon Hai Precision Ind. Co.,Ltd.).
192.168.0.0/24 > 192.168.0.104  » [15:13:39] [endpoint.new] endpoint 192.168.0.102 detected as xxxxxx (Intel Corporate).
192.168.0.0/24 > 192.168.0.104  » [15:13:50] [endpoint.lost] endpoint 192.168.0.103 (Hon Hai Precision Ind. Co.,Ltd.) lost.
```

### Steps to Reproduce
After starting net.sniff and net.probe, all default, no traffic can be captured even I'm loading html, 1.xx version works fine with the same devices.

The main problem is, if I run arp.spoof, it is likely to lose the target endpoint, when it's lost, the client will not show again under net.show, and I cannot use internet on the attacker side, arp table is empty, I have to bring down and up wlan interface to restore it. Victim side is totally fine with everything. 

Even with some luck, the arp did work, I am receiving traffic from the target, it seems not possible to use http.proxy.sslstrip with it, victim cannot load ssl striped page, and after a while, it is likely to lose endpoint again.

I have tested this on 2 NIC interface, laptop internal NIC and TL-WN722N TP-Link, both devices seem to work fine with 1.x version, sometime the sslstrip seems a bit slow on loading website, but i certainly have a much higher chance to get it work compared with 2.x

--

**Comment by evilsocket** [comment]
did you try to `net.probe off` while `arp.spoof on` ?

**Comment by kdlsw** [comment]
> did you try to `net.probe off` while `arp.spoof on` ?

Thank you for the reply. I tried this configuration, seems not improving the problem, sslstrip didn't work and client lost frequently, after I stop spoofing, attacker's arp table is empty and cannot use internet.

**Comment by evilsocket** [comment]
it sounds more like a problem with the router ... with some routers I experienced the same behaviour while, on most of them, the spoofing doesn't cause such problems and it's very reliable and stable ... if this is your case, as it seems to be, i'm afraid there's not much we can do software side.

**Comment by MHackmate** [comment]
but for virtual machine, when I tried after configuring them in NatNetwork also it is giving same errors.

> it sounds more like a problem with the router ... with some routers I experienced the same behaviour while, on most of them, the spoofing doesn't cause such problems and it's very reliable and stable ... if this is your case, as it seems to be, i'm afraid there's not much we can do software side.

**Comment by paatagog** [comment]
The same is for me.
Moreover, I have the following scenario:
I have installed virtualbox and run 2 computers in the same NatNetwor:
1. kali linux
2. windows 10

One day arp.spoof worked very well, but after some days it stop working exactly as @kdlsw described.

I is strange, that the exactly same scenario is working at first, and after some days does not in the same virtual environment.

**Comment by raisubham1024** [comment]
Currently i'm facing the same issue, anyone find solution ??
