### ISSUE TITLE
multiple domain->ip mappings in the dns.spoof module

### ISSUE THREAD

**Issue by john-bonachon** [bettercap/bettercap#344]
I'm testing using the lastest version.
Say I want to dns spoof my local machine queries. i.e only wordpress.com

set dns.spoof.domains wordpress.com
dns.spoof on

`dns.spoof.address` is my interface ip by default, so should I run a service to handle it? does bettercap provides a "hosts" file to map domain -> ip?

I can't see any dns spoof requests, only when I set `dns.spoof.all` to true

**Comment by evilsocket** [comment]
The `dns.spoof` module will, as the name would suggest, simply spoof the responses of the DNS queries it gets. In order for your computer to effectively receive the DNS queries of other network endpoints, either they directly use you as their resolver ( say in `/etc/resolv.conf` ), or you have to run the `arp.spoof` module as well in order to MITM their traffic and have the `dns.spoof` do its job.

**Comment by john-bonachon** [comment]
Right, thanks for reply. But I don't get how to spoof a single domain. If dns.spoof.address is my ip, means that any domain will map to my ip? 

I remember that in ettercap you could use a _hosts_ file where you could map domain -> ip

**Comment by evilsocket** [comment]
No, let's say you want `facebook.com` to be resolved as `1.2.3.4`, you will do:

  set dns.spoof.domains facebook.com
  set dns.spoof.address 1.2.3.4
  dns.spoof on

**Comment by evilsocket** [comment]
As per [documentation](https://github.com/bettercap/bettercap/wiki/dns.spoof)

**Comment by john-bonachon** [comment]
and multiple ones ?
set dns.spoof.domains facebook.com, wordpress.com
set dns.spoof.address 1.2.3.4, 5.6.7.8
?

**Comment by evilsocket** [comment]
nope, currently you can have a list of domains pointing to the same ip (which usually you leave the default, the one of your network interface), but not to different ips ... one solution might be to run two bettercap processes each one spoofing one domain to a different ip ... but yeah this might be considered a feature request, I guess?

**Comment by john-bonachon** [comment]
well yes!

should it work locally? I've tried but only when doing mitm on another device dns spoofing works..
