### ISSUE TITLE
Cannot read encrypted requests/responses from secure TCP ports via tcp.proxy

### ISSUE THREAD

**Issue by tamtam22** [bettercap/bettercap#347]
Hi,

I am trying to read and modify data sent via a secure telnet port (TCP/992). However, the tcp.proxy module doesn't decrypt the data sent/received on the secure TCP port (unlike the HTTPS proxy).

Please kindly advise what could be done to intercept request and response for secure TCP ports other than port 443. Thanks!

### Environment

* Bettercap version: **bettercap_linux_amd64_2.9.zip**
* OS version and architecture: **Kali Linux 2018.2**
* Command line arguments you are using: **sudo ./bettercap -caplet caplets/tcp-req-dump.cap**
* Caplet code you are using or the interactive session commands:
```
set tcp.proxy.script caplets/tcp-req-dump.js
set tcp.port 992
set tcp.address <victim ip>
set tcp.proxy.port 992
tcp.proxy on
```

### Steps to Reproduce

1. Run `sudo ./bettercap -caplet caplets/tcp-req-dump.cap`
2. I am able to view some data returned. However, most of it was encrypted other than some info in the SSL certificate.

**Expected behavior:**
*The tcp.proxy should work the same way as HTTPS proxy, which helps to encrypt/decrypt requests and responses happening on non-standard secure TCP ports*

**Actual behavior:**
*The data received is all encrypted via SSL. It was not possible to understand the request and response sent/received.*

**Comment by evilsocket** [comment]
the tcp proxy is different from the https one and it can only intercept communications but it can't decrypt TLS
