### ISSUE TITLE
arm precompiled version not working on kali arm

### ISSUE THREAD

**Issue by muratcesmecioglu** [bettercap/bettercap#350]
*Description of the bug or feature request*
Precompiled version can't start

### Environment

Please provide:

* Bettercap version you are using: 2.9.0
* OS version and architecture you are using: Raspberry pi 3 B + Kali 2018.3.Nexmon
* Go version if building from sources: Precompiled version
* Command line arguments you are using: bettercap
* Caplet code you are using or the interactive session commands: None
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ): Same as normal run

### Steps to Reproduce

wget https://github.com/bettercap/bettercap/releases/download/v2.9/bettercap_linux_arm7_2.9.zip
unzip bettercap_linux_arm7_2.9.zip
mv bettercap /usr/local/bin/bettercap
chmod +x /usr/local/bin/bettercap   -> Just in case
bettercap

**Expected behavior:**
To run

**Actual behavior:**
-bash: /usr/local/bin/bettercap: No such file or directory
![image](https://user-images.githubusercontent.com/12040730/46162910-56ad1e80-c292-11e8-981e-37e6a386b83e.png)

**NOTES:**
I read known issues and check libpcap.so file.
I have _/usr/lib/arm-linux-gnueabihf/libpcap.so.1.8.1_ and i also symlinked this file to _/usr/lib/libpcap.so.1_.
It doesn't work anyway.
**What is the correct way to start precompiled version?**

**Comment by muratcesmecioglu** [comment]
I solved the problem. Yay!

I downloaded and inspect apt-get version bettercap. Here is file command output:
apt-get version (2.7kali)
_/root/temp/usr/bin/bettercap: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter **/lib/ld-linux-armhf.so.3**, for GNU/Linux 3.2.0, BuildID[sha1]=f1e6ee1207fbcc23aaa53c63dee9c4b548c5e06d, stripped_

Here is 2.9 arm7 version file command output:
_bettercap: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter **/lib/ld-linux.so.3**, for GNU/Linux 3.2.0, BuildID[sha1]=79a9dda55db1c1dc621095e3c3966e08a1820d80, with debug_info, not stripped_

I don't know linux very well but i think 2.9 version can't find right interpreter. According to my research i find similiar problem in github: https://github.com/ethereum/wiki/issues/29#issuecomment-186562818

So i create a symlink FROM /lib/ld-linux-armhf.so.3 TO /lib/ld-linux.so.3
And it's working now. I will make some tests but i seems working.

**Comment by evilsocket** [comment]
Yeah i think kali arm requires a specific binary.

**Comment by evilsocket** [comment]
added to the known issues https://github.com/bettercap/bettercap/wiki/Known-Issues#bash-usrlocalbinbettercap-no-such-file-or-directory

**Comment by Taknok** [comment]
Where are the known issues now ?
