### ISSUE TITLE
HSTS BYPASS ISSUE

### ISSUE THREAD

**Issue by semsemsami** [bettercap/bettercap#351]
Hi I have issue with hsts bypass

in old version 1.6.2 I use 

bettercap -T "ip address" --proxy -P POST

with new version 2.9 i can't bypass any hsts website 

Is there similar code for v2.9 to bypass hsts website

**Comment by evilsocket** [comment]
RTFM

**Comment by evilsocket** [comment]
https://github.com/bettercap/caplets/blob/master/http-req-dump.cap
