### ISSUE TITLE
Makefile issue: gomegacheck is not supported on go 1.8

### ISSUE THREAD

**Issue by yconselvan** [bettercap/bettercap#352]
README stats that go compiler >= 1.8 can be used. But when compiling with 1.8 got the following error

# honnef.co/go/tools/lint/lintutil
../../../honnef.co/go/tools/lint/lintutil/util.go:273: undefined: types.SizesFor
Makefile:56: recipe for target 'gomegacheck' failed
make: *** [gomegacheck] Error 2

It seems that types.SizesFor was added in 1.9

**Comment by evilsocket** [comment]
does just `make build` work instead?
