### ISSUE TITLE
Go Get Not Working?

### ISSUE THREAD

**Issue by jpmoelter** [bettercap/bettercap#353]
*Go Get not working in Windows 10*

### Environment

Please provide:

* Bettercap version you are using. 
**2.9**
* OS version and architecture you are using.
**Windows 10 Pro x64**
* Go version if building from sources.
**Go 1.11**
* Command line arguments you are using.
**go get github.com/bettercap/bettercap**
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
**Users\########\go\src\github.com\bettercap\bettercap\vendor\github.com\google\gopacket\pcap\pcap.go:22:18: fatal error: pcap.h: No such file or directory
compilation terminated.**

### Steps to Reproduce

1. *First Step*
**Run go get command, after completing prior steps in Wiki**

**Expected behavior:** *What you expected to happen*
**Per wiki, "And eventually just go get github.com/bettercap/bettercap as you would do on other platforms."**
**Actual behavior:** *What actually happened*
**go get command errors out. See above for detailed output.**

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
> fatal error: pcap.h: No such file or directory

you did not install pcap, RTFM
