### ISSUE TITLE
flag provided but not defined: -T

### ISSUE THREAD

**Issue by rifkichaplin** [bettercap/bettercap#354]
* Beetercap version: 2.9-0kali1.
* OS version and architecture: Linux kali 4.14.59-v7+ #1131 SMP Thu Aug 2 15:57:42 BST 2018 armv7l GNU/Linux
* Installation : apt-get install bettercap.

### Steps to Reproduce
1. root@kali:~# dpkg -l | grep bettercap
ii  bettercap                            2.9-0kali1                     armel        Complete, modular, portable and easily extensible MITM framework
2. There is an example for using "sudo bettercap -T 192.168.1.10".
    but, I got 
   root@kali:~# bettercap -T 192.168.0.11
                     flag provided but not defined: -T
                     Usage of bettercap:
                    -autostart string

**Expected behavior:** * My Expected is a flag "-T" can be defined by bettercap tools *

**Actual behavior:** *as documentation at this link "https://www.bettercap.org/legacy/index.html#examples" can run with expected result*

--

**Comment by omgwtfwow** [comment]
The docs you linked to are for the previous version of bettercap. The documentation for the version you have installed is here https://github.com/bettercap/bettercap/wiki

**Comment by rifkichaplin** [comment]
So, what the bettercap version to use this link "https://www.bettercap.org/legacy/index.html#examples"  ??

**Comment by yungtravla** [comment]
@rifkichaplin that is the legacy version of bettercap which is no longer supported.

**Comment by CapitanCook10** [comment]
Hi Bro!

Did you solved that issue? I have the same problem. I'm working in my network and i'm trying to scan a PC, 

Best.

**Comment by yungtravla** [comment]
@CapitanCook10 two people here have already answered your question.
