### ISSUE TITLE
[bug] http.proxy and net.sniff doesn't work on Mac OS 10.14

### ISSUE THREAD

**Issue by j3ssie** [bettercap/bettercap#355]
I installed lastest version of bettercap from releases(2.10.0) and caplets then I ran the command below to sniffing traffic from my network but it didn't work.
```
sudo ./bettercap -iface en0 -caplet caplets/http-req-dump.cap
```
I can all the victim from `net.show `or but I can't see any traffic from the victim. 
I also try to enable `net.sniff` or `https.proxy` but same result that I can't see any traffic from the victim.

I tested the same network on legacy bettercap(1.6.2) then it worked.

## Environment
* Bettercap version: 2.10.0 from releases.
* OS version: MacOS 10.14

**Comment by evilsocket** [comment]
Thanks for ignoring completely the issue template and for not reporting _even a single line of logs_, this helps me a lot to understand your problem and help you solving it! I also appreciate very much how you considered the time that we spent creating the documentation and such issue template! :+1:
