### ISSUE TITLE
Add a wifi kill connection option

### ISSUE THREAD

**Issue by All3xJ** [bettercap/bettercap#356]
To my opinion it would be good to see a specific option in bettercap or maybe a caplet to do that faster to implement.

**Comment by evilsocket** [comment]
... what?

**Comment by All3xJ** [comment]
I'm sorry, I know I was too sinthetic. I meant, as you know, with mitm you have also the possibility to "cut" or kill (you can call it how you want) the connection of clients connected in that wifi. It would be great if an option or caplet exist so that anyone don't have to do it step by step but instead achieve it immediatly.

**Comment by evilsocket** [comment]
what do you mean step by step? it's just a `arp.ban on`

**Comment by All3xJ** [comment]
Oh, I didn't know that, thanks! Sorry for the stupid request
