### ISSUE TITLE
where is the sniffered passwd?

### ISSUE THREAD

**Issue by net2net** [bettercap/bettercap#358]
kali2.0 bettercap 2.10

net.sniff.output : /tmp/p.txt

everything goes well，I test ftp,telnet ,the sniffered ftp password output here：/tmp/p.txt
but the password was not  humanized,it was very difficulty to read the password。it contains many unstanded chars .

i want to know if there is a configure options for bettercap ,this option can output a clear password file?

thanks for u great work!

**Comment by evilsocket** [comment]
clearly you don't know what a pcap is, RTFM
