### ISSUE TITLE
Compilation error in Android (termux) with go get

### ISSUE THREAD

**Issue by All3xJ** [bettercap/bettercap#362]
After I followed the instructions here https://github.com/bettercap/bettercap/wiki/Compilation-on-Android and have installed dependencies, I get this error during go compilation: 

```
go get github.com/bettercap/bettercap
# github.com/bettercap/bettercap/network
go/src/github.com/bettercap/bettercap/network/net_gateway_android.go:14:8: undefined: str
```

**Comment by mgp25** [comment]
Hi,

You need to add one import to `/network/net_gateway_android.go`:

```go

import (
	"github.com/bettercap/bettercap/core"

	"github.com/evilsocket/islazy/str"
)
```

**Comment by All3xJ** [comment]
sudo make install does not work, so to start it I need to run the program from the compilation dir. But It works :)
