### ISSUE TITLE
HTTP(S) interception on proxy configured browser

### ISSUE THREAD

**Issue by mashhoorgulati** [bettercap/bettercap#363]
### Environment

Please provide:

* Bettercap version 1.6.2
* OS version Kali GNU Rolling

Is it possible to intercept traffic of a browser which is configured with proxy.

I'm using this command.

 bettercap -T x.x.x.x --proxy -P

and getting this output

[E] You're using bettercap as a normal HTTP(S) proxy, it wasn't designed to handle CONNECT requests:

CONNECT sam.msn.com:443 HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
Connection: Keep-Alive
Content-Length: 0
Host: sam.msn.com
Pragma: no-cache

my target is using IE 11 with on Windows 7 with proxy configured.

Proxy is on y.y.y.y:80

Is it possible to intercept this kind of connections.?

**Comment by yungtravla** [comment]
You are using the legacy version of bettercap which is no longer supported.

**Comment by mashhoorgulati** [comment]
> You are using the legacy version of bettercap which is no longer supported.

I understand. I have to use the legacy version since I'm unable to make use of the newer or current version. I will get there eventually.

However, I feel my issue remains relevant regardless of the version. Since its more about the topology.
