### ISSUE TITLE
Termux error go get github.com/bettercap/bettercap # github.com/bettercap/bettercap/network go/src/github.com/bettercap/bettercap/network/net_gateway_android.go:14:8: undefined: str

### ISSUE THREAD

**Issue by HaxxaH** [bettercap/bettercap#364]

**Comment by mgp25** [comment]
Wow, my eyes hurt. I know I am not the one that should tell you but... wtf.

- You have not filled the issue template. It is there for a reason, not to be deleted.
- Have you even searched in the issue tracker? It seems not. The same exact question has been answered just a couple days ago!! (https://github.com/bettercap/bettercap/issues/362)
- You pasted all the error in the title, which is ugly.

**Comment by HaxxaH** [comment]
Actually I have but can you give me a step by step?

**Comment by HaxxaH** [comment]
On how to import and compile it from the source thanks

**Comment by mgp25** [comment]
Add the line to the file. See https://github.com/bettercap/bettercap/issues/362.

Once then, `$ make build && sudo make install`

**Comment by HaxxaH** [comment]
Do I download the zip file?

**Comment by mgp25** [comment]
Until it is updated in the repo, you can work with your local changes. You don't need to download the code again. Source should be in `cd $GOPATH/src/github.com/bettercap/bettercap`

**Comment by HaxxaH** [comment]
Sorry but where is it located because I can't find it

**Comment by HaxxaH** [comment]
I'm stuck 

make build && sudo make install
make: *** No rule to make target 'build'.  Stop.

**Comment by HaxxaH** [comment]
Yeah I'm still stuck plz help

**Comment by MisterBianco** [comment]
Please close this issue, if he needs help he can fill out a proper ticket with a full issue template.

This issue will help no one with the same issue because there is no supplied detail.

I move to close.
