### ISSUE TITLE
curl error in a request to the api

### ISSUE THREAD

**Issue by endikap100** [bettercap/bettercap#366]
*Description of the bug or feature request*

### Environment

* Bettercap version: v2.10
* OS version: kali-rolling
* Command line arguments: `bettercap -eval "set api.rest.username bcap; set api.rest.password bcap; net.probe on; api.rest on"`

### Steps to Reproduce

1. Launch with  `bettercap -eval "set api.rest.username bcap; set api.rest.password bcap; net.probe on; api.rest on"`
2. Try to connect to the api with curl `curl -k --user bcap:bcap https://192.168.122.214:8081/api/session`

**Actual behavior:** 
This gives an error `curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number`, in debian testing and in rali-rolling ssl library is packaged without sslv3 support (maybe i'm wrong).
Could tls support be added?

**Comment by evilsocket** [comment]
the api do not use tls by default, you need to fill the certificate fields (see wiki) in order to enable it

**Comment by endikap100** [comment]
ok thanks
