### ISSUE TITLE
(make build && sudo make install) need help

### ISSUE THREAD

**Issue by HaxxaH** [bettercap/bettercap#367]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap 2.10
* OS version Android 9
* Go version 2.10
* Command line(make build && sudo make install)
make build && sudo make install
make: *** No rule to make target 'build'.  Stop.

**Comment by endikap100** [comment]
$ go get github.com/bettercap/bettercap
$ cd $GOPATH/src/github.com/bettercap/bettercap
$ make build && sudo make install

are you using thous commands? because it seems that you aren't in the correct folder.

**Comment by HaxxaH** [comment]
cd
$ GOPATH/src/github.com/bettercap/bettercap
bash: GOPATH/src/github.com/bettercap/bettercap: No such file or directory

**Comment by HaxxaH** [comment]
This is where it's located on my device 
/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/
But it still says no such file or directory

**Comment by yungtravla** [comment]
You need to set up your Go environment. This is cleary stated in the second line of the installation guide:

> Make sure you have a correctly configured Go >= 1.8 environment
