### ISSUE TITLE
HSTSHijack Caplet Problem :/ 

### ISSUE THREAD

**Issue by XXH3X** [bettercap/bettercap#368]
*Description of the bug or feature request*

### Environment
Linux Mint 19
Please provide:

* Bettercap 2.10
* Linux Mint 19 x64
* go version go1.10.4 linux/amd64
* sudo ./bettercap -caplet caplets/hstshijack/hstshijack.cap
* hstshijack caplet

xxh3x@XXH3X:~/go/bin$ sudo ./bettercap -caplet caplets/hstshijack/hstshijack.cap 
bettercap v2.10 (type 'help' for a list of commands)

[13:52:24] [sys.log] [inf] loading proxy script hstshijack.js ...
[13:52:24] [sys.log] [inf] (hstshijack) Generating random variable names for this session ...
[13:52:24] [sys.log] [inf] (hstshijack) Reading SSL log ...
[13:52:24] [sys.log] [err] Error while executing onLoad callback: 
Traceback:
  TypeError: 'env' is not a function
    at onLoad (<anonymous>:219:22)

192.168.1.0/24 > 192.168.1.100  » [13:52:24] [sys.log] [err] Error while running caplet caplets/hstshijack/hstshijack.cap: TypeError: 'env' is not a function
192.168.1.0/24 > 192.168.1.100  »  

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

PS: I've change the caplet to the right paths, I've also attached the file that I've changed the paths below as well as the logs

[log.txt](https://github.com/bettercap/bettercap/files/2498131/log.txt)
[hstshijack.cap.zip](https://github.com/bettercap/bettercap/files/2498133/hstshijack.cap.zip)

**Comment by XXH3X** [comment]
Nevermind, installation problem

**Comment by yungtravla** [comment]
The caplet has been updated. Please `bettercap -eval caplets.update`
