### ISSUE TITLE
rest api new feature suggestion

### ISSUE THREAD

**Issue by endikap100** [bettercap/bettercap#377]
*Description of feature request*

**Expected behavior:** is it possible the implementation of a call like a fusion of GET /api/events and DELETE /api/events a call that deletes all the events that returns?

**Actual behavior:** now you need to do GET /api/events and then DELETE /api/events, or is it possible to do then at the same time?
Thanks

**Comment by yungtravla** [comment]
What do you mean with "at the same time"?

Do you mean a single request that will return the events and delete them?

Personally I would check for a status 200 before giving the instruction to delete the logs, but if you are worried that your second DELETE request will not arrive, this might be a useful solution.

**Comment by yungtravla** [comment]
Not sure if this would be the right way to handle it if you're worried that the delete request won't arrive, because for the same reason the response might not arrive, and you would miss out on events. I think it's better to ensure the logs are fetched before sending the delete request.

**Comment by endikap100** [comment]
Do the event logs have id to delete only the event logs that have been processed by a external program?

**Comment by yungtravla** [comment]
Can you please elaborate on what you are trying to achieve?

What do you mean with an external program? Is it a web application that interacts with the bettercap API? In that case you could build a parser to serialize the logs and give them unique identifiers.

**Comment by evilsocket** [comment]
this would break the RESTful standard logic.

**Comment by endikap100** [comment]
> Can you please elaborate on what you are trying to achieve?
> 
> What do you mean with an external program? Is it a web application that interacts with the bettercap API? In that case you could build a parser to serialize the logs and give them unique identifiers.

I'm developing an app that uses the bettercap api, and I want to get all the events without losing anyone.
Now i'm geting the events an if the reponse has code 200, I delete them.
