### ISSUE TITLE
Lastest version won't build

### ISSUE THREAD

**Issue by AlexandreRouma** [bettercap/bettercap#379]
Hi, I'm getting an error when trying to build:
session/module_param.go:87:4: expected ';', found 'else'

### Environment
Bettercap: Latest (just downloaded now)
OS: Kali Linux 2018.3 (Debian)
Go: 1.11.1

### Steps to Reproduce

1. run go get github.com/bettercap/bettercap

**Expected behavior:** *It iinstalls correctly*

**Actual behavior:** *It errors out*

**Comment by evilsocket** [comment]
@ohpe's fault :D sorry guys, fixed

**Comment by ohpe** [comment]
When I pushed the PR #378, [25a2f48](https://github.com/bettercap/bettercap/commit/25a2f48a0262c9dde2e6f2540de3f5822c4a9640#diff-0a9fefd2f44f3164adf1d107857d05d4) wasn't merget yet. 
Nice race condition :)

**Comment by evilsocket** [comment]
ghghghgh :*

**Comment by 2fst4u** [comment]
Still getting this error. Should it be resolved already?

**Comment by evilsocket** [comment]
yes, did you pull the code from master?

**Comment by 2fst4u** [comment]
I'm just running the "go get" command

**Comment by evilsocket** [comment]
$ go get -u github.com/bettercap/bettercap
    $ cd $GOPATH/src/github.com/bettercap/bettercap
    $ make build && sudo make install

**Comment by 2fst4u** [comment]
Seems to be all good now. Thanks, team

**Comment by evilsocket** [comment]
You're welcome
