### ISSUE TITLE
Error while starting module events.stream: Uknown value for v

### ISSUE THREAD

**Issue by CybSecInfoHub** [bettercap/bettercap#380]
Can not even run the bettercap from the start, as it will show up such error info, any ideas about this?

**Comment by yungtravla** [comment]
Don't expect us to be able to guess what's going on. There was an issue template for a reason and you just deleted it. Please write a proper issue so we can help.

**Comment by yungtravla** [comment]
Experiencing the same problem here. I'll post an issue, so don't worry about writing another one.

**Comment by ohpe** [comment]
The `default` statement is breaking the flow. @yungtravla I'm going to push a PR

**Comment by yungtravla** [comment]
Cool :) it looks like the default case should be removed as there was no else statement.

**Comment by Edznux** [comment]
Yup, my bad, sorry guys !

**Comment by yungtravla** [comment]
@Edznux all good, can happen :)
