### ISSUE TITLE
http.proxy crashing on mac os 10.13 and higher

### ISSUE THREAD

**Issue by Tomygames** [bettercap/bettercap#385]
*Description of the bug or feature request*
When attempting to setup the http.proxy and then enabling it, bettercap crashes and exits with error code 1
Tried on 2 computers

### Environment

Please provide:

* Bettercap version you are using *: bettercap v2.10 (built from master and release too)
* OS version and architecture you are using *: macOS High Sierra 10.13.6
* Command line arguments you are using *: no args
* Caplet code you are using or the interactive session commands * : `http.proxy on`
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ):
```
192.168.1.0/24 > 192.168.1.7  » set http.proxy.script http-req-dump.js
192.168.1.0/24 > 192.168.1.7  » http.proxy on
[23:28:40] [sys.log] [inf] loading proxy script http-req-dump.js ...
[23:28:40] [sys.log] [inf] Enabling forwarding.
[23:28:40] [sys.log] [err] exit status 1
```
(same without the proxy script)

### Steps to Reproduce

1. Get a macOS 10.13 and up install
2. setup stuff
3. turn http proxy on

**Expected behavior:** Start the proxy with the given settings/default settings

**Actual behavior:** Exits

**Comment by sgeisbacher** [comment]
for me it perfectly works on macOS Mojave 10.14.1 and bettercap v2.10

**Comment by evilsocket** [comment]
are you sure that's the debug output?

**Comment by xxxcrow** [comment]
the same story on kali
`root@kali:~# bettercap -debug
bettercap v2.24 (built for linux arm with go1.11.6) [type 'help' for a list of commands]

192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.8.1 dev wlan0 proto dhcp metric 600
192.168.8.0/24 dev wlan0 proto kernel scope link src 192.168.8.225 metric 600
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) line 'default via 192.168.8.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.8.1 dev wlan0 proto dhcp metric 600 default 192.168.8.1 wlan0]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] gateway is 192.168.8.1[e4:95:6e:46:25:4f]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [session.started] {session.started 2019-06-18 15:31:46.851000755 +0000 UTC m=+0.207501315 <nil>}
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [mod.started] events.stream
192.168.8.0/24 > 192.168.8.225  » http.proxy on
[15:32:01] [sys.log] [err] exit status 1
192.168.8.0/24 > 192.168.8.225  »
`
exit status 1, good explanation!
