### ISSUE TITLE
Bettercap works very slow

### ISSUE THREAD

**Issue by 4LeNNiKs** [bettercap/bettercap#388]
*I'm trying to use bettercap on my "Raspberry pi zero w" with my wireless adapter "TP-LINK WN7200ND".
And it's works but VERY slowly. For example: I'm update the web page (without ssl) on my phone and log shows on my terminal after 5-10 minutes and when i enter "net.sniff on" i can't use this terminal(keyboard doesn't work, but i can switch terminals).  I used bettercap on my laptop and it works without any freezes. What can i do to remove these freezes ?*

### Environment

* Bettercap version: 2.10
* OS: Kali ARM, Raspberry pi zero w.
* Command line arguments: -iface wlan1.
* Interactive session commands: net.probe on; arp.spoof on; net.sniff on;

### Steps to Reproduce

1. *bettercap -iface wlan1*
2. *net.probe on*
3. *arp.spoof on*
4. *net.sniff on*

**Expected behavior:** *bettercap starts sniffing network traffic*

**Actual behavior:** *Sniff works but very slowly*

**Comment by evilsocket** [comment]
maybe because the rpi zero w *IS* very slow? you can't expect it to MITM the whole subnet.
