### ISSUE TITLE
arp.spoof not working.

### ISSUE THREAD

**Issue by dreadlocked** [bettercap/bettercap#389]
I'm using a MacBook Pro over a USB Ethernet network interface which iface identifier is "en10".
My computer internal IP & Mac: `10.X.X.130 | XX:XX:XX:XX:7A`
Gateway IP & Mac: `10.X.X.1 | XX:XX:XX:XX:2B`

 I'm using the following commands:

`$ sudo bettercap -iface en10`

```
set gateway.address <gateway_ip>
set gateway.mac <gateway_mac>
```

Then, set an HTTP proxy server:
```
set http.proxy.script http-req-dump.js
http.proxy on
```

And finally
`arp.spoof on`

When I take a look on the ARP packets, bettercap is sending an ARP request like the following:
`10.X.X.130 has Mac address XX:XX:XX:XX:7A`

So it's telling that my IP has my MAC, obviously this is not gonna spoof anything. What am I doing wrong?

**Comment by benleb** [comment]
Do you know what ARP is or even how it works?

**Comment by dreadlocked** [comment]
Uhm yep. And for your response, you didn't even understand the problem. Closing issue.
