### ISSUE TITLE
panic: gob: decoding into local type *map[string]string, received remote type unknown type

### ISSUE THREAD

**Issue by kallakoras** [bettercap/bettercap#391]
bettercap v2.11 (type 'help' for a list of commands)

panic: gob: decoding into local type *map[string]string, received remote type unknown type

goroutine 1 [running]:
github.com/bettercap/bettercap/network.NewLAN(0xc420536a00, 0xc4200bc000, 0xc420030640, 0xc420030650, 0x0)
        /home/evilsocket/gocode/src/github.com/bettercap/bettercap/network/lan.go:39 +0x179
github.com/bettercap/bettercap/session.(*Session).Start(0xc420520000, 0xc420468d00, 0x10)
        /home/evilsocket/gocode/src/github.com/bettercap/bettercap/session/session.go:251 +0x4b4
main.main()
        /home/evilsocket/gocode/src/github.com/bettercap/bettercap/main.go:63 +0xcb2

4.18.0-kali2-amd64
go version go1.10.4 linux/amd64

Included is from the pre-compiled binary. But experiencing the same crash if I compile locally.

**Comment by evilsocket** [comment]
try to `rm -rf /root/bettercap.aliases` before starting bettercap
