### ISSUE TITLE
error reading SNI: record overflow

### ISSUE THREAD

**Issue by placidchat** [bettercap/bettercap#392]
Bettercap v2.11 & v2.10
raspberry pi + go version 1.11.1 cross compiled on an x86_64

When reading in https data while https.proxy is on, error reading SNI:record overflow is thrown. 
Reading inconshreivable/go-vhost, it seems once this is encountered, there isn't further upstream contact to the site, and the web browser shows that the site is not contactable.

**Comment by evilsocket** [comment]
no debug logs, you just deleted the whole issue template without filling it ... how do you expect me to fix this? closing

**Comment by login-already-taken** [comment]
Hi evilsocket,
I encounter this issue too. Here are the debug log from the console when launching an https proxy connecting to it via firefox quantum and trying to access google.com : 

192.168.0.0/24 > 192.168.0.13  » https.proxy on
[04:11:33] [sys.log] [inf] loading proxy certification authority TLS key from /root/.bettercap-ca.key.pem
[04:11:33] [sys.log] [inf] loading proxy certification authority TLS certificate from /root/.bettercap-ca.cert.pem
[04:11:33] [sys.log] [dbg] Applied redirection [wlp2s0] (TCP) :443 -> 192.168.0.13:8083
[04:11:33] [mod.started] https.proxy
192.168.0.0/24 > 192.168.0.13  » [04:11:33] [sys.log] [inf] https.proxy started on 192.168.0.13:8083 (sslstrip disabled)
192.168.0.0/24 > 192.168.0.13  » [04:11:35] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:36] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:38] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:38] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:39] [sys.log] [war] error reading SNI: unexpected message.
192.168.0.0/24 > 192.168.0.13  » [04:11:41] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:42] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:42] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:42] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:43] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:43] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:44] [sys.log] [war] error reading SNI: unexpected message.
192.168.0.0/24 > 192.168.0.13  » [04:11:48] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:48] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » [04:11:49] [sys.log] [war] error reading SNI: unexpected message.
192.168.0.0/24 > 192.168.0.13  » https.proxy on[04:11:49] [sys.log] [war] error reading SNI: record overflow.
192.168.0.0/24 > 192.168.0.13  » https.proxy off
[04:11:51] [mod.stopped] https.proxy
[04:11:51] [sys.log] [dbg] Disabling redirection [wlp2s0] (TCP) :443 -> 192.168.0.13:8083
[04:11:51] [sys.log] [war] error accepting connection: accept tcp 192.168.0.13:8083: use of closed 
network connection.

I'm running Ubuntu 16.01, go version 1.11.1 linux/amd64 and the latest Bettercap 2.11 compiled from source.

I'm available if you need any other info or to test fixes.

**Comment by placidchat** [comment]
Hi there i've tried to alter the code to dump more errors. I don't know go, so needed a few days to look through the spec. But after tinkering around, the fault is actually mine. So here is how it works.

If you use a web browser that has a vanilla environment i.e. no http{s}_proxy set, then bettercap works. If you set the proxies, then, in my case, i get the sni record overflow. Is there a way that bettercap can work in the same way as squid instead of transparently ?

**Comment by q2dg** [comment]
I have exactly the same the same error: if Bettercap does a arp-spoof combined with http.proxy/https.proxy it works but when I want to explicitely specify in "net parameters" of firefox its http and https proxy, Bettercap throws the "error reading SNI: record overflow" message.
Here there is another similar issue but solution is cryptic: https://github.com/bettercap/bettercap/issues/329
