### ISSUE TITLE
Trying a dns spoofing on 2 different routers doesn't work

### ISSUE THREAD

**Issue by Virgula0** [bettercap/bettercap#393]
I'm trying to execute a dns spoofing but it seems not working for me...

I'm trying to execute on my own local address a dns spoofing so I set bettercap like below:

```
set http.proxy.sslstrip true
set net.sniff.verbose false
set arp.spoof.targets 192.168.1.60 #my own pc
arp.spoof on
http.proxy on
net.sniff on
```

then:

```
set dns.spoof.domains example.com
set dns.spoof.address 127.0.0.1 #address to redirect traffic to
set dns.spoof.all true
dns.spoof on
```

when I try to navigate to example.com my browser doesn't redirect me on 127.0.0.1 and if I check with an nslookup bettercap seems answer correctly but in browser doesn't work

nslookup example.com
Responses:
```
192.168.1.0/24 > 192.168.1.60  » [19:46:09] [sys.log] [inf] [dns] sending spoofed DNS reply for www.example.com (->127.0.0.1) to XX:XX:XX:XX:XX:XX.
192.168.1.0/24 > 192.168.1.60  » [19:46:38] [sys.log] [inf] [dns] sending spoofed DNS reply for example.com (->127.0.0.1) to XX:XX:XX:XX:XX:XX.
192.168.1.0/24 > 192.168.1.60  » [19:46:46] [sys.log] [inf] [dns] sending spoofed DNS reply for example.com (->127.0.0.1) to XX:XX:XX:XX:XX:XX.
```

**Comment by yungtravla** [comment]
127.0.0.1 is reserved as a loopback address. Traffic destined to and from that address will do just that, loop back.

You need to specify a real DNS server, or your local address (not loopback).

**Comment by yungtravla** [comment]
Also, targeting your own machine with the ARP spoofer is futile. You already have access to your local traffic, you do not need to poison your own ARP tables.
