### ISSUE TITLE
Modify tcp traffic generated on my own router

### ISSUE THREAD

**Issue by JuanSchallibaum** [bettercap/bettercap#394]
Hi! I'm doing a job about security in bgp. I'm working with CORE Network (network topology emulator), and Quagga (routing software). I need to replace some data in BGP layer, of outgoing packets. Specifically i need to remove my own ASN from the AS-PATH of the UPDATE packet that is generated on my own router (generated by Quagga). To do that, I decided to use your tcp.proxy module.

I called bettercap with this caplet:

```
set tcp.proxy.script tcp-req-dump2.js
set tcp.port 179
set tcp.address 66.66.66.5
set tcp.proxy.port 8080
net.recon off
tcp.proxy on
```

With this script only for printing data flow (testing):

```
function onLoad() {
    log("TCP module loaded")
}

function onData(from, to, data) {
    log(data)
}
```

(then i thought to add a regex in the script that matches the UPDATE packet I want to replace and change it for the one I want).

and i added this line with iptables:
**iptables -t nat -A OUTPUT -p tcp -d 66.66.66.5 --dport 179 -j DNAT --to-destination 66.66.66.6:8080**

to route all the traffic generated on my own router destinated to 66.66.66.5:179, through the tcp proxy. This iptables OUTPUT line seems identical to the automatically generated by bettercap iptables PREROUTING line.

When i run the topology i got the next output:

> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59742                                                       66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59744
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59746
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59748
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59750
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] TCP proxy got a connection from 66.66.66.6:59752
> 66.66.66.4/30 > 66.66.66.6  » [20:59:34] [sys.log] [inf] 255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,59,1,4,2,154,0,180,66,66,66,6,30,2,6,1,4,0,1,0,1,2,2,128,0,2,2,2,0,2,6,65,4,0,0,2,154,2,4,64,2,128,120
> ...
> ...
> 66.66.66.4/30 > 66.66.66.6  » [21:02:36] [sys.log] [war] Error while accepting TCP connection: accept tcp 66.66.66.6:8080: accept4: too many open files
> 66.66.66.4/30 > 66.66.66.6  » [21:02:36] [sys.log] [war] Error while accepting TCP connection: accept tcp 66.66.66.6:8080: accept4: too many open files
> 66.66.66.4/30 > 66.66.66.6  » [21:02:36] [sys.log] [war] Error while accepting TCP connection: accept tcp 66.66.66.6:8080: accept4: too many open files
> 66.66.66.4/30 > 66.66.66.6  » [21:02:36] [sys.log] [war] Error while accepting TCP connection: accept tcp 66.66.66.6:8080: accept4: too many open files
> 66.66.66.4/30 > 66.66.66.6  » [21:02:36] [sys.log] [war] Error while accepting TCP connection: accept tcp 66.66.66.6:8080: accept4: too many open files

As you see, always send the same packet, (OPEN BGP message), changing the source port, opening a lot of file descriptors, until they aren't more available...

Is there any way to use tcp.proxy to achieve what I want? I thought about modifying the quagga source code but it would be too much work to do something as simple as what I propose...

Thanks in advance!

**PD.: I achieved that i wanted, establishing the connection from the start with scapy, and then sending the bogus updates... But i would like to know how to solve my problem with my previous idea: Incercepting  the update packet generated by quagga in my own router and replacing with regex with the bogus update packet that i want.**

**Comment by evilsocket** [comment]
you don't need additional iptables rules, bettercap takes care of that ... you can change the buffer within the js module

**Comment by JuanSchallibaum** [comment]
Hi Simone! Thanks for your time! Bettercap generates a PREROUTING iptables rule, that works for stealed traffic, that is, the traffic we receive from another device through any MITM technique. But local originated traffic isn't passing through PREROUTING chain, that's why I thought that for this case, it was necessary to add a rule to the OUTPUT table, but it doesn't work... I got the output that I show... Thanks in advance. Bye!

https://stackoverflow.com/questions/23180696/linux-iptables-redirect-outgoing-traffic-to-local-port
