### ISSUE TITLE
Environment file is overwritten by default values 

### ISSUE THREAD

**Issue by placidchat** [bettercap/bettercap#397]
*Description of the bug or feature request*

### Environment
bettercap 2.11 arm 

### Steps to Reproduce
1. add environment variables into bettercap.env
2. include this
 { "#####testvar":"testvaroutput",
    "https.proxy.certificate.commonname" : "this common name"
}

**Expected behavior:** *What you expected to happen*
1. get * displays the changed name

**Actual behavior:** *What actually happened*
1. The environment variable isn't changed and is still the default
2. The test variable is propagated into the session environment

--> 
During loading of the environment file, the moduleparam that gets registered to the session does not reflect the user written environment file. The default is used instead.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
no logs, no info about the path of that file, nothing ... closing this as it's incomplete.

**Comment by placidchat** [comment]
1. Steps to Reproduce
    In the file bettercap.env, add the following environment variables as a json styled entry

    { 
        "#####testvar":"testvaroutput",
        "https.proxy.certificate.commonname" : "this common name"
    }

2. To confirm the environment variables are not propagated into the environment
2.1 run bettercap -env-file bettercap.env
2.2 at the prompt: get *
2.3 it displays #####testvar
      but not the user set https.proxy.certificate.commonname

3. There are no logs because no error messages are generated

**Comment by xiaoyao9184** [comment]
@placidchat same
