### ISSUE TITLE
http.proxy redirection not working (partially solved)

### ISSUE THREAD

**Issue by fightforge** [bettercap/bettercap#398]
Hi,
i'm testing the latest version 2.11 but i cannot get http.proxy redirection to work.
To get redirection to work i need to change this lines in firewall_linux.go

### From

`"-j", "DNAT",`
` "--to", fmt.Sprintf("%s:%d", r.DstAddress, r.DstPort),`

### To

`"-j", "REDIRECT",`
` "--to-port", fmt.Sprintf("%d", r.DstPort),`

Bettercap version: 2.11
Os: ParrotSec 4.18
Go version: go1.10.4
command line: sudo bettercap -iface eth0 -caplet rtfm
Output: no error on output, just cannot see rtfm cat imag loaded in target browser

I don't know how to reproduce this. If i don't change the above lines i cannot get http.proxy redirection to work.

What i'm doing wrong?

Thanks for all

**Comment by evilsocket** [comment]
you did not provide any command line, any logs or details as required. Closing as incomplete.
