### ISSUE TITLE
dns.spoof  is Not working ?

### ISSUE THREAD

**Issue by CaiJiJi** [bettercap/bettercap#399]
![log](https://user-images.githubusercontent.com/10561685/49227562-52cd8200-f424-11e8-993e-2ff1ae4e2649.png)

nslookup result
```
➜ /tmp >nslookup www.example.com
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	www.example.com
Address: 93.184.216.34

➜ /tmp >nslookup www.example.com
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	www.example.com
Address: 93.184.216.34
```
what happned?

**Comment by PerrierCitror** [comment]
Same issue today, just began learning the tool and am reassured to see it might be a bug in this version. Just couldn't make it work.

**Comment by benleb** [comment]
Did you also supply an IP address for the domain? Did you set dns.spoof.all? How do you route the DNS requests to your attacker host? Are they reaching it? Does it reply?

**Comment by evilsocket** [comment]
what about providing logs as requested? closing as incomplete
