### ISSUE TITLE
DNS spoofing not working please help

### ISSUE THREAD

**Issue by PerrierCitror** [bettercap/bettercap#401]

**Comment by benleb** [comment]
Did you also supply an IP address for the domain? Did you set dns.spoof.all? How do you route the DNS requests to your attacker host? Are they reaching it? Does it reply?

**Comment by PerrierCitror** [comment]
I think dns.spoof.all is on by default, it worked with the arp spoofing module and http.spoof without having to specify the victim IP. Only the dns spoof module doesn't work.

**Comment by benleb** [comment]
If you use DNS spoof without ARP spoof you have to add your attacker host IP as the victims DNS server to get the requests

**Comment by PerrierCitror** [comment]
I used it as a standalone. Not with ARP spoof.

**Comment by alifa2try** [comment]
![image](https://user-images.githubusercontent.com/19759609/54078945-78dfa980-42d2-11e9-9ec1-4fd91835b624.png)
DNS Spoof not working for me as well. Or is there anything I am missing here? Here is the value of the modules I have set

**Comment by Parshuram2** [comment]
> Did you also supply an IP address for the domain? Did you set dns.spoof.all? How do you route the DNS requests to your attacker host? Are they reaching it? Does it reply?

I set dns.spoof.hosts to my hosts file which has just one line 192.168.x.x *... Now, should't that redirect all .com websites? Although I tried ettercap, MITMf and Bettercap DNS Spoofing simply doesn't work on Chrome. I downloaded a shitty browser from playstore. It managed to redirect listverse.com..that too just once as a fluke. Don't know what's going on. HSTS already killed LAN hacks including wifi hacks like Fluxion...becasue people use fb,google and insta..nothing else..so they never get to see the enter credentials portal. Now, even shitty sites are not being redirected..strange.,

**Comment by sxm22** [comment]
> > Did you also supply an IP address for the domain? Did you set dns.spoof.all? How do you route the DNS requests to your attacker host? Are they reaching it? Does it reply?
> 
> I set dns.spoof.hosts to my hosts file which has just one line 192.168.x.x *... Now, should't that redirect all .com websites? Although I tried ettercap, MITMf and Bettercap DNS Spoofing simply doesn't work on Chrome. I downloaded a shitty browser from playstore. It managed to redirect listverse.com..that too just once as a fluke. Don't know what's going on. HSTS already killed LAN hacks including wifi hacks like Fluxion...becasue people use fb,google and insta..nothing else..so they never get to see the enter credentials portal. Now, even shitty sites are not being redirected..strange.,

 me too I tried every where and everything, it still does not work

**Comment by jokeman332** [comment]
Same issue here...
