### ISSUE TITLE
New Builtin Functions Suggestion

### ISSUE THREAD

**Issue by tykkz** [bettercap/bettercap#402]
Hello,

In some of my HTTP modules, before reading a file with "readFile" function, I want to check whether it exists in the system or not.

I can add the function to [script_builtins.go](https://github.com/bettercap/bettercap/blob/master/modules/script_builtins.go) and do a PR (an **existFile** function).

Questions:

1. Is there any other way to check the file on the system? (that is already implemented)
2. Would anyone want to have any other builtin functions?

**Comment by yungtravla** [comment]
You can do `readFile("path/to/file")` which returns an error if the file is not found.
