### ISSUE TITLE
Unsetting of variables does not work

### ISSUE THREAD

**Issue by mgrottenthaler** [bettercap/bettercap#403]
According to the documentation you can unset a variable by typing `set variable-name ""`:
```
set variable-name new-value (a value of "" will clear the variable contents),
```

This does not work in the current version. I get the following error message:
```
» set events.stream.output ""
» [16:00:51] [sys.log] [err] unknown or invalid syntax "set events.stream.output", type help for the help menu.
```

### Environment

* Bettercap version: 2.11
* Kali Linux Rolling
* Command line arguments: `bettercap -iface eth1`
* **Full debug output**: `[sys.log] [err] unknown or invalid syntax "set events.stream.output", type help for the help menu.`

### Steps to Reproduce

1. type: `set events.stream.output ""`

**Expected behavior:** The variable is unset/set to an empty string

**Actual behavior:** Error!

**Comment by yungtravla** [comment]
Although an empty value is a defined value, a new command like `unset` could undefine environment variables.
