### ISSUE TITLE
Arp Spoof Dns Spoof Inconsistent Results

### ISSUE THREAD

**Issue by RadMod** [bettercap/bettercap#404]
Arp Spoof Dns Spoof Inconsistent Results

VMWARE Pro 12.5 Kali, Ubuntu on Windows 10 Pro Host

Please provide:

* Bettercap Version 2 latest 
*Kali Linux VM latest version
* NA
* bettercap -caplet arp.cap
*set arp.spoof.targets 10.0.0.8
set dns.spoof.domains xxxyyyzzz.com
set dns.spoof.address 10.0.0.81
set arp.spoof.internal true
set dns.spoof.all true
set http.server.path /var/www/html
dns.spoof on
arp.spoof on
http.server on
* **Not sure where to find the syslog please provide direction).

### Steps to Reproduce

1. Ran bettercap -caplet arp.cap
2. Ran bettercap in interactive mode and copied commands from cap file line by line
3. Ran bettercap in debug more. Not sure were to find the sys.log

**Expected behavior:** I would like a fake website to load when the victim goes to xxxyyyzzz.com

**Actual behavior:** Inconsistent results

Some times it works, most time it doesn't.
When it doesn't work the results are inconsistent
For instance the ARP spoof and DNS spoof works on Windows and Ubuntu victims.
I can use nslookup and verify that the address is resolving to attacker machine. 
However when I enter the URL in the browser I get page can not be displayed.
Other times the ARP spoof is working however Nslookup resolves address using real DNS server
But most times ARP spoof does not work.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
no logs, closing
