### ISSUE TITLE
caplets.update command fails on Android

### ISSUE THREAD

**Issue by kkar** [bettercap/bettercap#405]
caplets.update command fails on Android

### Environment
* Bettercap latest
* Android 8.0.0
* Termux
* All required permissions (FS) and Root, granted, for Termux App
* Exact command: *tsudo go/bin/bettercap*
* Caplets update command: *caplets.update*

**Expected behavior:** *Caplets update process...*

**Actual behavior:** *Getting error: /usr: read-only*

![48395210_2325925257626389_1718342833749884928_n](https://user-images.githubusercontent.com/8864418/50164216-b5f75980-02ea-11e9-88d3-9baa2844b381.png)

After that, I tried to set the CAPSPATH environment variable to an existing Path, but I got the same result (Shown below).
![48381010_2246178762283210_3651548304199647232_n](https://user-images.githubusercontent.com/8864418/50167234-6a947980-02f1-11e9-83ec-f8a21969ba1c.png)

**Comment by yungtravla** [comment]
You will need to remount your filesystem with read & write access.

You can also manually grab the caplets [here](https://github.com/bettercap/caplets).
