### ISSUE TITLE
DNS Spoofing on https domains cause NET::ERR_CERT_COMMON_NAME_INVALID error by Chrome.

### ISSUE THREAD

**Issue by OliveIT** [bettercap/bettercap#407]
I'm going to block access of one or many computers in local net to some certain sites.
So I want to use this awesome tool's arp and dns spoofing function to do so.
e.g  when visiting youtube.com other content will appear instead

### Environment

Please provide:

* Bettercap version you are using.  Latest
* OS version and architecture you are using.  Kali Linux
* Go version if building from sources.  Downloaded release version
* Command line arguments you are using.  sudo bettercap
* Caplet code you are using or the interactive session commands. No

### Steps to Reproduce

1. *First Step*
set arp.spoof.targets 192.168.15.134
arp.spoof on
2. *Second Step*
set dns.spoof.hosts /root/Documents/simple.list
dns.spoof on

content of simple.list
107.178.240.207 www.youtube.com
107.178.240.207 youtube.com

**Expected behavior:** *What you expected to happen*
redirect https://www.youtube.com -> https://kinsta.com/

**Actual behavior:** *What actually happened*
Chrome shows below message
"Your connection is not private
Attackers might be trying to steal your information from www.youtube.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID"

![untitled1](https://user-images.githubusercontent.com/42824831/50231144-d3ffaf80-03f9-11e9-8db3-8fa309bf4092.png)

**Comment by yungtravla** [comment]
This is exactly what certificates are for. So you can ensure that you are connecting to the intended address. Unless you have installed a root certificate on the victim's machine, you cannot manipulate the traffic.

You seem to have already partially achieved what you wanted to achieve though (block access).

**Comment by OliveIT** [comment]
Hi @yungtravla 
Thanks for your prompt reply.
Yes, I already installed root ca cert that Bettercap generates on the victim's machine.
But it seems Chrome blocks the incoming cert(of kinsta.com) because it's not issued to youtube.com.
How can I fix this using your https.proxy or http.proxy?

**Comment by yungtravla** [comment]
Hi @OliveIT, in that case you do not need to spoof DNS queries for youtube as you have access to the decrypted traffic. A simple HTTP redirect will do what you want.

HTTP(S) proxy script:

```js
function onRequest(req, res) {
  if ( req.Hostname.match(/youtube\.com$/i) ) {
    res.Status = 301;
    res.SetHeader("Location", "http://kinsta.com");
  }
}
```

**Comment by OliveIT** [comment]
@yungtravla, what a neat idea!!!
Do you think it can replace embedded youtube video on https webpage too?
Let me implement that and come back to you.

**Comment by yungtravla** [comment]
The page's content is all yours once you can proxy decrypted traffic ;)

**Comment by vivekkalal** [comment]
i use bettercap new version and i also use caplets which is provided by github but it does not bypassing https 
and not excess any website in the target machine ]
The webpage show me this
This site can’t be reached10.0.2.5 took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

So what to do help me

**Comment by vivekkalal** [comment]
what changes i made in my caplets to solve this error and i easily bypass https
