### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [bettercap/bettercap#412]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by yungtravla** [comment]
evilsocket has been providing [precompiled executables](https://github.com/bettercap/bettercap/releases) for all platforms with every new release. The very first line of the **How to install** page in the [wiki](https://github.com/bettercap/bettercap/wiki) tells you this.
