### ISSUE TITLE
Slow at "bettercap.exe -h"

### ISSUE THREAD

**Issue by gvanem** [bettercap/bettercap#413]
I just discovered this tool and after building it myself (using TDM-gcc), it kinda works. 

But the [release](https://github.com/bettercap/bettercap/releases/download/v2.11.1/bettercap_windows_amd64_2.11.1.zip
) version have a serious issue. Even a `bettercap.exe -h` takes 30 sec to complete!

Using *Process Explorer*, I see the Msys crap `stty.exe stty cbreak min 1` is blocking for a long somehow:
![bettercap-stty](https://user-images.githubusercontent.com/945271/50905277-c2bb2900-1422-11e9-8873-e06181b0453c.png)

before returning with the help-text (seems to be waiting for `bowser.sys`). What is `stty` needed for on Windows?

The fix for this problem was to use the rock-solid Cygwin32 version of `stty.exe` instead (in fact I try to remove every trace of my old Msys tools).

**Comment by gvanem** [comment]
> which terminal are you using?

You mean shell? I use JPsoftware's [4NT](https://jpsoft.com/blogs/2011/10/windows-command-line-tabbed-windows-and-jp-software-part-iii/) v5.00 (Unicode). I'm on Windows-10. Even 15 years later 4NT works fine on it.

But, ... *drum-roll*. The original problem of `bowser.sys` blocking Msys' programs has gone! Maybe the 
large Window-Update  (to version 1809, OS build 17763.253) had any effect after I rebooted 10 January?

**Comment by evilsocket** [comment]
no idea, but definitely not a bettrcap's issue

**Comment by gvanem** [comment]
> no idea, but definitely not a bettrcap's issue

I agree.
