### ISSUE TITLE
Bettercap dnsspoofing doesn't have any effect

### ISSUE THREAD

**Issue by G1THVB** [bettercap/bettercap#416]
OS: Kali Linux
Bettercap Version: 1.6.2
Command: `Bettercap --dns dns.conf `

dns.conf contents: 
`local .*\.com`  (Attempting to redirect all traffic to my IP)

Problem: No given errors, but the attack has no effect on the victim pc (on the same network I triple checked). I browse an http website on the victim's pc like: www.bacon.com while running the attack, and I should be redirected to the attacker's IP but instead the website loads just fine on the victim's pc and nothing happens at all.

I also tried to do this with Arp Spoofing, but still no effect.
Command w/ Arp Spoof: 

`bettercap -I wlan0 -S ARP -X --gateway 192.168.0.1 --target 192.168.0.7 --dns dns.conf  --httpd --httpd-path ./pub --httpd-port 8080`

The browser on the Victim's PC is google chrome v71.0.3578.98 (latest one)
However when I use a different browser on victim's pc (like internet explorer) still no effect.
Victim pc is running windows 7 2003. 

**dnsspoof on bettercap simply doesn't have any effect**

Please tell me what I am doing wrong, Git Hub is my last resort, I have been trying to get this to work over a year. If I cannot do this with Bettercap, than please suggest a software that can dnsspoof victims and redirect them to any URL. 

-thanks
 

Here is what the console looked like for: **Bettercap --dns dns.conf**
My IP: 192.168.0.2

```
[I] [wlan0] 192.168.0.2 : 34:F3:9A:1F:92:1C / wlan0 ( Intel Corporate )
[I] [GATEWAY] 192.168.0.1 : B0:DA:F9:52:99:F5 ( ??? )
[I] [DISCOVERY] Precomputing list of possible endpoints, this could take a while depending on your subnet ...
[I] [DISCOVERY] Done in 9.3 ms
[I] [DISCOVERY] Targeting the whole subnet 192.168.0.0..192.168.0.255 ...
[I] Acquired 5 new targets :

  [NEW] 192.168.0.6 : A4:77:33:A8:87:C8 ( Google )
  [NEW] 192.168.0.7 : 10:F1:F2:27:CF:9E ( ??? )
  [NEW] 192.168.0.11 : 00:18:61:34:BD:79 ( Ooma )
  [NEW] 192.168.0.17 : 00:24:D7:A7:AB:20 ( Intel Corporate )
  [NEW] 192.168.0.254 : B0:DA:F9:52:99:F9 ( ??? )

[I] Found NetBIOS name 'USER-PC' for address 192.168.0.17
[I] Found NetBIOS name 'ARRIS-LGW' for address 192.168.0.254
[I] [DNS] Starting on 192.168.0.2:5300 ...
[I] [192.168.0.6 > DNS] Received request for 'connectivitycheck.gstatic.com', sending spoofed reply 192.168.0.2 ...
[I] [192.168.0.6 > DNS] Received request for 'www.bacom.com', sending spoofed reply 192.168.0.2 ...
[I] [192.168.0.6 > DNS] Received request for 'www.google.com', sending spoofed reply 192.168.0.2 ...
[I] [192.168.0.6 > DNS] Received request for 'connectivitycheck.gstatic.com', sending spoofed reply 192.168.0.2 ...
```

**Comment by evilsocket** [comment]
versions < 2.x are not supported  anymore
