### ISSUE TITLE
Listening to a particular ip bettercap 2.11

### ISSUE THREAD

**Issue by gauravr15** [bettercap/bettercap#417]
I am trying http-req-dump.cap on bettercap 2.11, but whenever i run the complete command, it only listens to the last active ip on my subnet and i am unable to change it. 
The error message which i get at last is address already in use. And the address which is being displayed is the last active ip rather than my targeted ip.

**Comment by evilsocket** [comment]
`set http.proxy.address whatever.ip.rtfm` -> https://github.com/bettercap/bettercap/wiki/http.proxy
