### ISSUE TITLE
Bettercap dns.spoof doesn't have any effect

### ISSUE THREAD

**Issue by G1THVB** [bettercap/bettercap#418]
Bettercap dns.spoof doesn't redirect victim pc which is on the same network. No signs that it even knows the victim pc is browsing. Attack always fails. 

Bettercap Version: 2.11.1 (Latest stable Version)
Attacker OS: Kali Linux 2018.1
Victim OS: Windows 7 2003
Victim Browser: Google Chrome (Same effect with any browser though)
Victim Ip: 192.168.0.17
Attacker IP: 192.168.0.2

**Steps to Reproduce My Attack**
`set dns.spoof.hosts hosts.conf`
 `dns.spoof on `

**hosts.conf content:**
192.168.0.2                 *.com
192.168.0.2		    *.time.com

(During the attack I went to time.com on the victim PC)

the log:

```
192.168.0.0/24 > 192.168.0.2  » [18:26:04] [endpoint.new] endpoint 192.168.0.17 detected as 00:24:d7:a7:ab:20 (Intel Corporate).
192.168.0.0/24 > 192.168.0.2  » set dns.spoof.hosts hosts.conf
192.168.0.0/24 > 192.168.0.2  » dns.spoof on
[18:26:17] [sys.log] [inf] loading hosts from file hosts.conf ...
[18:26:17] [sys.log] [inf] [dns.spoof] *.com -> 192.168.0.2
[18:26:17] [sys.log] [inf] [dns.spoof] *.time.com -> 192.168.0.2
192.168.0.0/24 > 192.168.0.2  » ^C
Are you sure you want to quit this session? y/n y
WARNING: Stopping module dns.spoof timed out.
```

**Expected behavior:**
When the victim goes to time.com during the attack, he will be redirected to my spoofed web page, I am running apache2 on my linux machine, so the site is reachable. 

**Actual behavior:**
Nothing happened when the victim went to time.com. He saw the normal webpage and bettercap didn't 
show any signs of dns redirecting. We are both on the same network, and we are both not on the 5G version of the network

**Comment by G1THVB** [comment]
Nvm mate just had to use arp-spoof. Bettercap 2.0 is fucking awesome thanks a lot!!! 
I have been trying to get this to work for a long time. God bless the developers if this fucking amazing tool. Thanks a lot!!!!

**Comment by G1THVB** [comment]
Command that made it work:
```
set arp.spoof.targets 192.168.0.17, 192.168.0.1 (target and router)
arp.spoof on
```

**Comment by evilsocket** [comment]
dns.spoof alone only spoofs DNS packets that you receive, in order to receive ALL of them (including requests from other hosts), you also need ARP spoofing as you figured out :) Enjoy!

**Comment by AlekyaKowta** [comment]
Hey, but i have my arp spoofing on, but for some reason, dns spoofing doesnt work.

**Comment by DurgaLavanyaRani** [comment]
Hey, dns spoof not working (bettercap v2.28) with these parameters, what am i missing ?

net.probe on; 
set arp.spoof.targets 192.168.29.147, 192.168.29.1; 
set arp.spoof.internal true;
set dns.spoof.domains abcd.com; set dns.spoof.address 192.168.29.249; 
set net.sniff.verbose false; 
net.sniff on; dns.spoof on; arp.spoof on

appreciate your help.

**Comment by n1h4x** [comment]
same here, i got these params and not working... 192.168.0.1 is my router, 192.168.0.81 is my target (in this case the kali itself)
  arp.spoof.targets : 192.168.0.1, 192.168.0.81
  arp.spoof.whitelist : 
  arp.spoof.internal : true
  arp.spoof.fullduplex : false

dns.spoof (Replies to DNS messages with spoofed responses.)

  dns.spoof.ttl : 1024
  dns.spoof.hosts : 
  dns.spoof.domains : *.com
  dns.spoof.address : someIP
  dns.spoof.all : false

events.stream (Print events as a continuous stream.)

  events.stream.http.format.hex : true
  events.stream.time.format : 15:04:05
  events.stream.output.rotate : true
  events.stream.output.rotate.format : 2006-01-02 15:04:05
  events.stream.output.rotate.when : 10
  events.stream.http.response.dump : false
  events.stream.output : 
  events.stream.output.rotate.compress : true
  events.stream.output.rotate.how : size
  events.stream.http.request.dump : false

net.recon (Read periodically the ARP cache in order to monitor for new hosts on the network.)

  net.show.meta : false
  net.show.filter : 
  net.show.sort : ip asc
  net.show.limit : 0

**Comment by CiberSecLabs** [comment]
Same Issue, same config ... it's not working !

**Comment by CalfCrusher** [comment]
I have same exactly issue

**Comment by AnAntsColony** [comment]
Same issue here

**Comment by Mo7amedShaban1** [comment]
Same issue here any idea?

**Comment by Mo7amedShaban1** [comment]
After a long time of hassle 😁
It works fine with me. The problem was in the dns server. It should relies on the ISP dns so, make sure to keep as the default configuration.

**Comment by ricko2991** [comment]
@Mo7amedShaban1 Can you show me the commands you used? I don't know why I keep failing.

**Comment by davehouser1** [comment]
I am unable to figure out how to get dns.spoofing to work either.
I am following these instructions exactly
https://www.bettercap.org/modules/ethernet/spoofers/dns.spoof/ 

I am listening on the correct interface, but I see no traffic.
It sounds like arp spoofing needs to be in place. I enabled arp spoofing, same problem. 

Recommendation to Bettercap team: It would be nice to have a quick start section in your documentation to detail simple setups for different use cases. If DNS spoofing requires other modules / caps to be on it would be helpful to new users to see a quick example of how to get something like dns.spoofing enabled. 

If this exists already, I am sorry I missed it, please share.

**Comment by AlexGalo0** [comment]
Well , i had the same problem but it wasn't bettercap fault , it was because i had previously visit the domain before doing the arp and dns spoofing , so , remember to delete the browser history before trying. It worked for me!

**Comment by k7zloy** [comment]
> Что ж, у меня была такая же проблема, но это была не ошибка bettercap , а потому, что я ранее посещал домен перед выполнением arp и dns-подмены, поэтому не забудьте удалить историю браузера перед попыткой. У меня это сработало!

Thanks

**Comment by Moosa-Imran** [comment]
Try clearing the browsing history, including the cache, from the victim's browser. Then, you will see that it works. This is because our browsers store a cache for DNS.

**Comment by buffermet** [comment]
There are many reasons why DNS spoofing may not work:

1. Victim's browser has cached DNS records.
2. Victim's browser is using a different DNS protocol (e.g. DoH/DoT).
3. Victim's OS is using a different DNS protocol (e.g. DoH/DoT).
4. Attacker spawned an access point with a DNS server enabled (e.g. Dnsmasq).
5. Attacker needs to enable ARP spoofing.
6. The router is protected against ARP spoofing.

**Comment by buffermet** [comment]
Please open a new issue and provide all the requested information. I'll help you figure out the problem.
