### ISSUE TITLE
Compile for ARM6

### ISSUE THREAD

**Issue by bennesp** [bettercap/bettercap#420]
*Description of the bug or feature request*

I was following a 6 months old interesting [article](https://www.evilsocket.net/2018/07/28/Project-PITA-Writeup-build-a-mini-mass-deauther-using-bettercap-and-a-Raspberry-Pi-Zero-W/), that explained also how to simply compile on the Raspberry Pi Zero W this repo.
Nowadays, the compilation fails because of the low memory on that device, in fact when go get tries to do the go install part, the output is:

`/usr/local/go/pkg/tool/linux_arm/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
`

This is fine, I mean, it is a tiny device not meant to do the compilation process. On the other hand I would like to use buttercap even on that device.
So I tried to cross compile on a Mac OS X for the ARM6 of the pi zero w.
Nevertheless, I had some problems, since cross compilation is a bit tricky due to cgo code, inside the dependency `github.com/tarm/serial`.
I saw issue #44 but actually it is not so simple to install arm-linux-gnueabi-gcc  on a Mac.

Since I also see a Release page, with all the other architectures, I would ask to you if it is possible to have also a Release for ARM6, since I saw that on a Linux machine it would be not so difficult to do (I may be wrong obviously)

Thank you in advance for your great work

### Environment

* Bettercap version: 308fa01e81cac12eed3efa902ba2c2c9d20b1389
* Go version if building from sources: go1.11.4 darwin/amd64

**Comment by evilsocket** [comment]
it's very easy to overcome the memory allocation process using swap, in fact this is what I do whenever I need to recompile bettercap for the rpiz:

	# dd if=/dev/zero of=/path/to/swapfile bs=1M count=1024 # For 1GB swap file
	# mkswap /path/to/swapfile
	# swapon /path/to/swapfile

This way the system will just use this file to swap whenever memory is low ... compilation will work flawlessly ;)

**Comment by bennesp** [comment]
I missed that, thank you very much!
