### ISSUE TITLE
V2.13 crash on MacOS when wifi.show is used

### ISSUE THREAD

**Issue by ZimSec** [bettercap/bettercap#423]
Bettercap Version 2.13

go version go1.11.4 darwin/amd64

ProductName:	Mac OS X
ProductVersion: 10.14.2
BuildVersion: 18C54

Panic Error output: 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/tui.Table(0x4a0ad80, 0xc0000b2008, 0xc0004561b0, 0x9, 0x9, 0xc000622c00, 0x10, 0x10)
	/Users/zjam/go/src/github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/tui/table.go:101 +0xf7f
github.com/bettercap/bettercap/modules.(*WiFiModule).Show(0xc000033a40, 0x0, 0x0)
	/Users/zjam/go/src/github.com/bettercap/bettercap/modules/wifi_show.go:278 +0x6dd
github.com/bettercap/bettercap/modules.NewWiFiModule.func8(0x0, 0x0, 0x0, 0x1, 0x0)
	/Users/zjam/go/src/github.com/bettercap/bettercap/modules/wifi.go:153 +0x2a
github.com/bettercap/bettercap/session.(*Session).Run(0xc0000e6000, 0xc0000a67a0, 0x9, 0x1, 0x1)
	/Users/zjam/go/src/github.com/bettercap/bettercap/session/session.go:394 +0x645
main.main()
	/Users/zjam/go/src/github.com/bettercap/bettercap/main.go:114 +0x129c

### Steps to Reproduce

1. $ sudo bettercap
2. wifi.recon on
3. wifi.show

**Expected behavior:**
List wifi ap's

**Actual behavior:** 
Gives a panic runtime error and Bettercap crashes

**Comment by djjerdog** [comment]
Seeing the same behavior in Linux 4.19

**Comment by evilsocket** [comment]
sorry for the lame bug, it should be fixed now, can you confirm?

**Comment by ZimSec** [comment]
Can confirm, works perfectly now thanks
