### ISSUE TITLE
Not seeing FTP password in main tab

### ISSUE THREAD

**Issue by JBalanza** [bettercap/bettercap#424]
*Description of the bug or feature request*

Is there any way of showing FTP credentials or at least the FTP full packets in the main tab? as http packets could be seen I didnt find any way of showing FTP content too.
Let me know if I've made a mistake but I think the only way of doing it is to save them into pcap and them looking into it. 

### Environment

Please provide:

* Bettercap version you are using.
Bettercap v2.11.1
* OS version and architecture you are using.
Linux Parrot 4.18.0
* Go version if building from sources.
Used bettercap that comes by default, but my Go version is go1.11.4
* Command line arguments you are using.
-iface and -caplet
* Caplet code you are using or the interactive session commands.

`net.recon off

set http.proxy.port 8080
set http.proxy.script hook.js
set http.proxy.sslstrip true
http.proxy on

set net.sniff.verbose true
net.sniff on

set events.stream.http.request.dump true

events.ignore net.sniff.http.response
events.ignore http.proxy.spoofed-response
events.ignore net.sniff.dns
events.ignore net.sniff.tcp
`

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
Not showing ftp response's content.

### Steps to Reproduce

As i'm in an Evil twin attack, MitM is already done. I'm able to see http traffic but no ftp's.
1. *First Step*
bettercap -iface wlan0 -caplet 'caplet.cap'

**Expected behavior:** *What you expected to happen*
See FTP authentication packet, where you can see plain-text credentials send to FTP server
**Actual behavior:** *What actually happened*
I'm only seeing the next line:
`[11:13:46] [net.sniff.tcp] tcp 192.168.1.33:52180 > XXX.XXX.XXX.XXX:ftp 40 bytes`

Regards

**Comment by mukulmehar** [comment]
I'm having the same issue
