### ISSUE TITLE
Insta reboot on wifi.deauth

### ISSUE THREAD

**Issue by freewill404** [bettercap/bettercap#429]
Bettercap v2.13.1
OS X 10.14.2 (Air 2019)

The laptop reboots instantly right after I run "wifi.deauth BSSID"

Same issue with https://github.com/unixpickle/JamWiFi.

**Comment by yungtravla** [comment]
If this happens every time you send a deauthentication or disassociation packet, then I think there is something wrong with your wifi driver, not with bettercap.

**Comment by yungtravla** [comment]
@freewill404 the issue is not bettercap, as you have pointed out this happens in other scenarios too, it is most likely an issue with the wireless card/driver in your macbook air.

What you can do is check your kernel log to see if there are any messages in regards to this deauthing issue.

**Comment by umbrellait-alexey-ville** [comment]
Also happening on 2019 MBP with T2 running Mojave 10.14.6.
