### ISSUE TITLE
Error while setting interface en12 in monitor mode: Cannot set rfmon for this handle

### ISSUE THREAD

**Issue by jens66** [bettercap/bettercap#432]
*Description of the bug or feature request*
When trying to activate wifi.recon on i get the following error:
Error while setting interface en12 in monitor mode: Cannot set rfmon for this handle
### Environment
Please provide:
Bettercap version: v2.13.1
Macosx 10.14.1 on macbook pro 15" late 2018
go1.11.1 darwin/amd64

* Command line arguments you are using.
sudo bettercap -iface en12 
* Caplet code you are using or the interactive session commands.
none
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
sudo bettercap -iface en12 -debug
bettercap v2.12 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.20  » [08:02:17] [sys.log] [dbg] FindGateway(en12) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [sys.log] [dbg] FindGateway(en12) output:
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           91        0    en12       
10.37.129/24       link#23            UC              1        0   vnic1      !
10.211.55/24       link#22            UC              1        0   vnic0      !
127                127.0.0.1          UCS             0        0     lo0       
127.0.0.1          127.0.0.1          UH              4   707165     lo0       
169.254            link#24            UCS             0        0    en12      !
192.168.1          link#24            UCS             3        0    en12      !
192.168.1.1/32     link#24            UCS             1        0    en12      !
192.168.1.1        38:d5:47:e3:98:80  UHLWIir        25      199    en12   1200
192.168.1.20/32    link#24            UCS             0        0    en12      !
192.168.1.66       a4:d9:31:ce:43:35  UHLWI           0        2    en12    751
192.168.1.229      a4:d9:31:69:dd:dd  UHLWIi          1       28    en12    736
192.168.1.246      40:cb:c0:e4:33:43  UHLWIi          1        3    en12   1197
224.0.0/4          link#24            UmCS            2        0    en12      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0    en12       
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       20    en12       
255.255.255.255/32 link#24            UCS             0        0    en12      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0       
default                                 fe80::%utun1                    UGcI          utun1       
default                                 fe80::%utun2                    UGcI          utun2       
::1                                     ::1                             UHL             lo0       
fdc5:91b:d81c:1:18eb:2fa5:fcec:4784     0:c0:ca:a4:79:84                UHL             lo0       
fdc5:91b:d81c:1:8434:be94:833b:b523     0:c0:ca:a4:79:84                UHL             lo0       
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0       
fe80::1%lo0                             link#1                          UHLI            lo0       
fe80::%en5/64                           link#8                          UCI             en5       
fe80::aede:48ff:fe00:1122%en5           ac:de:48:0:11:22                UHLI            lo0       
fe80::aede:48ff:fe33:4455%en5           ac:de:48:33:44:55               UHLWIi          en5       
fe80::%utun0/64                         fe80::bcb0:97b0:74f7:42d7%utun0 UcI           utun0       
fe80::bcb0:97b0:74f7:42d7%utun0         link#18                         UHLI            lo0       
fe80::%utun1/64                         fe80::d887:7a4f:f9b3:3805%utun1 UcI           utun1       
fe80::d887:7a4f:f9b3:3805%utun1         link#19                         UHLI            lo0       
fe80::%utun2/64                         fe80::8518:d161:c947:29fd%utun2 UcI           utun2       
fe80::8518:d161:c947:29fd%utun2         link#20                         UHLI            lo0       
fe80::%en12/64                          link#24                         UCI            en12       
fe80::1032:6eb7:f2f:e3d7%en12           a4:d9:31:69:dd:dd               UHLWI          en12       
fe80::1ab4:30ff:fe14:1c98%en12          link#24                         UHLWI          en12       
fe80::1c9d:c854:9fdb:3c70%en12          0:c0:ca:a4:79:84                UHLI            lo0       
ff01::%lo0/32                           ::1                             UmCI            lo0       
ff01::%en5/32                           link#8                          UmCI            en5       
ff01::%en0/32                           link#10                         UmCI            en0       
ff01::%awdl0/32                         link#12                         UmCI          awdl0       
ff01::%utun0/32                         fe80::bcb0:97b0:74f7:42d7%utun0 UmCI          utun0       
ff01::%utun1/32                         fe80::d887:7a4f:f9b3:3805%utun1 UmCI          utun1       
ff01::%utun2/32                         fe80::8518:d161:c947:29fd%utun2 UmCI          utun2       
ff01::%en12/32                          link#24                         UmCI           en12       
ff02::%lo0/32                           ::1                             UmCI            lo0       
ff02::%en5/32                           link#8                          UmCI            en5       
ff02::%en0/32                           link#10                         UmCI            en0       
ff02::%awdl0/32                         link#12                         UmCI          awdl0       
ff02::%utun0/32                         fe80::bcb0:97b0:74f7:42d7%utun0 UmCI          utun0       
ff02::%utun1/32                         fe80::d887:7a4f:f9b3:3805%utun1 UmCI          utun1       
ff02::%utun2/32                         fe80::8518:d161:c947:29fd%utun2 UmCI          utun2       
ff02::%en12/32                          link#24                         UmCI           en12
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [sys.log] [dbg] FindGateway(en12) line 'default            192.168.1.1        UGSc           91        0    en12' matched with [default            192.168.1.1        UGSc           91        0    en12 default 192.168.1.1 UGSc 91 0 en12]
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [sys.log] [dbg] gateway is 192.168.1.1[38:d5:47:e3:98:80]
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [session.started] {session.started 2019-02-04 08:02:17.10587 +0100 CET m=+0.026173772 <nil>}
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [mod.started] events.stream
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [endpoint.new] endpoint 192.168.1.66 detected as a4:d9:31:ce:43:35 (Apple, Inc.).
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [endpoint.new] endpoint 192.168.1.229 detected as a4:d9:31:69:dd:dd (Apple, Inc.).
192.168.1.0/24 > 192.168.1.20  » [08:02:17] [endpoint.new] endpoint 192.168.1.246 detected as 40:cb:c0:e4:33:43 (Apple, Inc.).
192.168.1.0/24 > 192.168.1.20  »  
### Steps to Reproduce

1. *First Step* connect ALFA AUWS036ACH to the macbook
2. startup terminal

3. issue command: sudo bettercap -iface en12
4. wait for 30 seconds
5. issue command wifi.recon on

**Expected behavior:** *What you expected to happen*
I expect not to get an error
**Actual behavior:** *What actually happened*
i got an error: Error while setting interface en12 in monitor mode: Cannot set rfmon for this handle
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
What wifi card and drivers are you using? That error means your card does not support monitor mode.

**Comment by evilsocket** [comment]
I don't think macOS supports alfas in monitor mode, you can just use the default Mac interface (en0) once disconnected from other networks, it should support monitor mode natively :)

**Comment by jens66** [comment]
When i try this natively the mac crashes (simular as # 448) the only difference is that i am trying to use the fake access point exactly as describe on the bettercap page (ssid Banana etc).

**Comment by jens66** [comment]
btw i update mohave to the latest version 10.14.5

**Comment by Amurmurmur** [comment]
any ideas if there are any drivers for mac for the AWUS 1900 to support monitor mode and packet injection ?

**Comment by stas-grgv** [comment]
Same issue with Zyxel 6605, works fine on Parallels with Kali Linux with installed drivers. On mac I tried to get handshake with integrated card and it works fine, but range is low.
