### ISSUE TITLE
gateway detection regex doesn't work

### ISSUE THREAD

**Issue by mozzbozz** [bettercap/bettercap#434]
### Environment

Please provide:

* Bettercap version: v2.13.1
* OS version and architecture: Debian Stretch
* Command line arguments you are using: `--debug`

### Steps to Reproduce

1. Have a network device / interface with a dash in the name (like `tun-sim`)
2. Start bettercap -> it will complain that it can't determine the gateway
3. Thanks to the debug output one can see the used regex - it doesn't match as soon as there is a dash in the device name. Therefore, bettercap won't be able to determine the gateway ip address.

I can recommend this page for playing around with regexes (there you can also see the problem clearly): https://regex101.com/r/Aj6hxS/1

Complete output for clarification:
```
10.1.2.0/24 > 10.1.2.3  » [04:20:42] [sys.log] [dbg] FindGateway(tun-sim) [cmd=ip opts=[route] parser=^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)(?:\s.*|)$]
10.1.2.0/24 > 10.1.2.3  » [04:20:42] [sys.log] [dbg] FindGateway(tun-sim) output:
default via 10.1.2.1 dev tun-sim 
10.1.2.0/24 dev tun-sim proto kernel scope link src 10.1.2.3 
192.168.112.0/20 dev eth0 proto kernel scope link src 192.168.112.5
10.1.2.0/24 > 10.1.2.3  » [04:20:42] [sys.log] [dbg] FindGateway(tun-sim): nothing found :/
10.1.2.0/24 > 10.1.2.3  » [04:20:42] [sys.log] [war] Could not detect gateway.
```

### Possible Solution

I think the following regex should do it:
```
^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s([\w-]+)(?:\s.*|)$
```

(added `[`, `-` and `]`)

**Comment by yungtravla** [comment]
Thanks :)

According to man7.org:

> Valid characters for hostnames are ASCII(7) letters from a to z, the digits from 0 to 9, and the hyphen (-).

So the correct regexp would be `^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s([a-zA-Z0-9-]+)(?:\s.*|)$`

**Comment by yungtravla** [comment]
PR opened https://github.com/bettercap/bettercap/pull/435

**Comment by yungtravla** [comment]
It looks like hostnames can actually be appended domains, and may only start and end with letters or numbers, so the regexp needs to be extended a little further:

`^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s((?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9]+)(?:\s.*|)$`

**Comment by yungtravla** [comment]
Whoops, I wasn't paying attention...

This command is trying to find the gateway IP, it is not searching for hostnames.

The problem was actually the regexp to match IPv4 addresses: `[0-9\.]+`

This is an invalid sequence, as symbols between [ ] brackets don't need to be escaped from being regexp characters.

The correct regexp would be: `[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+` as the IP may not end with a dot.

![screenshot from 2019-02-05 14-59-32](https://user-images.githubusercontent.com/29265684/52253967-b14c3a80-2956-11e9-9b45-fa15045d53fd.png)

**Comment by yungtravla** [comment]
Back again... It also turns out that interface names are not always matched, as @mozzbozz had pointed out initially. A quick search tells me that interface names allow any character that is not a whitespace character, so `\w+` should be `\S+`.
