### ISSUE TITLE
incomplete list of deps in ./vendor folder

### ISSUE THREAD

**Issue by blshkv** [bettercap/bettercap#437]
Hi, 

I'm not sure what is the best practice with golang, but  ruby language has a similar concept where all dependencies can be kept in ./vendor folder for users convenience. However, it is advised not to distribute (not include in the release) a ruby software with required packages in this folder since ruby dependencies can be shared (installed as a system package) and developers don't need to trace any critical updates of these dependencies. It is a different story with golang, but you might still consider not to distribute it. 

Anyway, I found that at least the following two packages do not present in this folder:
```
        "github.com/bettercap/gatt 66e7446993acb3de936b3f487e5933522ed16923"                                               
        "github.com/bettercap/readline 62c6fe6193755f722b8b8788aa7357be55a50ff1"
```

**Comment by evilsocket** [comment]
this is how go dep works, not related to bettercap.
