### ISSUE TITLE
Issue when starting bettercap 

### ISSUE THREAD

**Issue by n0xii** [bettercap/bettercap#438]
root@kali:~# bettercap
 _          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                                     |_| v1.6.2
http://bettercap.org/

[I] Starting [ spoofing:✔ discovery:✔ sniffer:✘ tcp-proxy:✘ udp-proxy:✘ http-proxy:✘ https-proxy:✘ sslstrip:✘ http-server:✘ dns-server:✘ ] ...

[E] Oooops, seems like something weird occurred, please copy paste the following output and open a new issue on https://github.com/evilsocket/bettercap/issues :

[E] Platform          : x86_64-linux-gnu
[E] Ruby Version      : 2.5.1
[E] BetterCap Version : 1.6.2
[E] Command Line      : 
[E] Exception         : Errno::ENOENT
[E] Message           : No such file or directory - netstat
[E] Backtrace         :

    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:25:in ``'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:25:in `block in execute'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:23:in `times'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/shell.rb:23:in `execute'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/network/network.rb:20:in `get_gateway'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/context.rb:117:in `update!'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/lib/bettercap/options/options.rb:68:in `parse!'
    /var/lib/gems/2.5.0/gems/bettercap-1.6.2/bin/bettercap:30:in `<top (required)>'
    /usr/local/bin/bettercap:23:in `load'
    /usr/local/bin/bettercap:23:in `<main>'

**Comment by yungtravla** [comment]
You are using the legacy version.

Please read [instructions](https://github.com/bettercap/bettercap) before posting an issue.
