### ISSUE TITLE
[Feature Request] Reposition Update Argument

### ISSUE THREAD

**Issue by zero77** [bettercap/bettercap#440]
Can you please move or also add the update argument to the outside of bettercap for example, bettercap -update.
Thanks

**Comment by evilsocket** [comment]
you can simply:

`sudo bettercap -eval "update.check on; q"`

**Comment by zero77** [comment]
@evilsocket 
Thanks
This should probably go in the reed me or wiki, where abouts should i put it.

**Comment by evilsocket** [comment]
it is already https://github.com/bettercap/bettercap/wiki/Interactive-Mode

![schermata da 2019-02-11 12-54-28](https://user-images.githubusercontent.com/86922/52561611-34104200-2dfc-11e9-80f9-038515655f5a.png)

**Comment by zero77** [comment]
I meant a small section, specifically on updating bettercap.

**Comment by evilsocket** [comment]
that depends on the distro you are using or, if you're using a precompiled version from this github, you just need to download it and replace it ... there's really nothing more than that to document.
