### ISSUE TITLE
bettercap alert -> help

### ISSUE THREAD

**Issue by user568989** [bettercap/bettercap#442]
I dont know if it a bug or i did not do something right (probably)

* Bettercap version V2.14
* OS version kali linux (attacker) victim(windows 8) - IE 11.0
* Go version V1.11

Tried to run:
./bettercap (without any caplet) -eval "set arp.spoof.targets x.x.x.x"

and in bettercap interpreter:

**************************************************
set http.proxy.injectjs alert("Hello World")
set http.proxy.sslstrip true

http.proxy on
arp.spoof on

**************************************************
What i expected is to see in every browser (Tested on IE 11.0) HTML pages http's (Browser message: "Hello world")

Did not work... i opened IE, http website and  did nto see any message..

I also tried to do this with MITMf and it did work and successfully saw my alert message and even images...

I also tried to deal with fb-phsih and some other caplets (did not work, followed by instructions in github and some other websites which is pretty much the same) but this is the easiest one (alert) so ...

any idea?

**Comment by evilsocket** [comment]
no debug logs provided, closing

**Comment by user568989** [comment]
No Javascript message in HTML pages

* Bettercap version V2.14
* OS version kali linux (attacker) victim(windows 8) - IE 11.0
* Go version V1.11

commands:
*************************************************
set http.proxy.injectjs alert("TEST")
set http.proxy.sslstrip true

http.proxy on
arp.spoof on

*************************************************
Input : 

![screenshot 69](https://user-images.githubusercontent.com/42979542/52647203-f0493580-2eec-11e9-8b8d-88fb6d840cc9.png)


Output : 

![screenshot 70](https://user-images.githubusercontent.com/42979542/52647228-fdfebb00-2eec-11e9-9162-4a74d2e933fb.png)


As you can see, the "TEST" message needed to be printed in this website (IE)...

@evilsocket  any ideas why it does not work??

**Comment by evilsocket** [comment]
what part of *debug logs* is not clear? locking this down.
