### ISSUE TITLE
bettercap- help

### ISSUE THREAD

**Issue by user568989** [bettercap/bettercap#443]
No Javascript message in HTML pages

* Bettercap version V2.14
* OS version kali linux (attacker) victim(windows 8) - IE 11.0
* Go version V1.11

command:    ./bettercap -debug

the commands in bettercap:
********************************************
set http.proxy.injectjs alert("TEST")
###### Also tried putting test.js instead of the command above
test.js includes   [     alert("TEST");     ]

set http.proxy.sslstrip true
http.proxy on
arp.spoof on
***************************************************
![screenshot 72](https://user-images.githubusercontent.com/42979542/52655239-65703700-2efc-11e9-8c03-4e19ca85d44d.png)

looks like bettercap sendthe package and..

![screenshot 74](https://user-images.githubusercontent.com/42979542/52655273-79b43400-2efc-11e9-8c01-bd9411e396ba.png)

looks like the "Could not find hardware address..." message displays only when i type "q" or "CTRL- C"...
 as long as i dont type "q" or "CTRL -C", picture number 1 describes what's happening...

result = No message in IE

modules r on:
net.probe is on
http.proxy is on
arp.spoof is on

Tested it on Host and the message("Could not find hardware...") did not appear

result = No message in IE

**Comment by evilsocket** [comment]
what is the IP address of the target you expect to be poisoned?

**Comment by user568989** [comment]
10.100.102.28

**Comment by user568989** [comment]
Ignore picture 2 i receive pifcture 2 only when i try to arp spoof the all network which is by deafult

**Comment by evilsocket** [comment]
dude you either provide the correct debug logs of the what you're actually trying to do or I can't help you ... and by debug logs I don't mean incomplete screenshots, but a copy/paste of the entire output of bettercap, with `-debug`, while you try to arp.spoof that specific target.

**Comment by evilsocket** [comment]
I can see `could not find hardware address for 10.100.102.28`, while for valid IP ( the `.17` ) both spoofing and proxying are working as you can see in the logs ...

**Comment by user568989** [comment]
I can see that but why it does not work?? Is it working for u?

**Comment by evilsocket** [comment]
yes, it is

**Comment by user568989** [comment]
Ok i am gonna try that in Kali live cause i tried that in VB strange MITMf without any errors..
last question r u using any VM or VB?

**Comment by user568989** [comment]
yea i did it haha from kali LIVE i am gonna run some tests in VB  ...
thankx anyway
