### ISSUE TITLE
No result with wifi.show 

### ISSUE THREAD

**Issue by Ridter** [bettercap/bettercap#446]
### Environment

Bettercap v2.15
Mac OS X 10.14.3
Darwin Kernel Version 18.2.0
go version go1.11.4 darwin/amd64

### Steps to Reproduce

1. *sudo bettercap -iface en0*
2. *wifi.recon on*
3. *wifi.show*

**Expected behavior:** *What you expected to happen*
 wifi list
**Actual behavior:** *What actually happened*
 no result
-- 

![image](https://user-images.githubusercontent.com/6007471/52783377-ac8d3200-308c-11e9-8d01-117f306c8802.png)

**Comment by evilsocket** [comment]
your en0 must be disconnected from other networks in order for monitor mode to work ...

**Comment by Ridter** [comment]
🤦‍♂️.. thx

**Comment by evilsocket** [comment]
ahaha you're welcome, have fun!: :D
