### ISSUE TITLE
implement / fix windows native compatibility

### ISSUE THREAD

**Issue by evilsocket** [bettercap/bettercap#45]
- [x] Fix what's needed in order to compile (or cross compile) for Windows.
- [x] Implement `net/arp_parser_windows.go` using `arp -a`.
- [x] Implement `net/net_windows.go` using `netsh interface ipv4 show route`.
- [x] Implement `firewall/firewall_windows.go`: packet forwarding.
- [ ] Implement `firewall/firewall_windows.go`: [netsh based port redirection](https://stackoverflow.com/questions/11525703/port-forwarding-in-windows).

**Comment by evilsocket** [comment]
Unfortunately it looks like port redirection with `netsh` is not possible, [this doesn't work as expected](https://github.com/evilsocket/bettercap-ng/blob/master/firewall/firewall_windows.go#L55) as it just creates a local listener which redirects to 8080 but does not work on forwarded packets.

**Comment by aflick2486** [comment]
So this should work, you have to have ipv6 libraries installed with `netsh int ipv6 install` and then use `netsh interface portproxy add v4tov4 listenport=<localport> listenaddress=<localaddress> connectport=<destport> connectaddress=<destaddress>`. It does create a local listener on the local port and forwards it to the dest port. Would you be able to explain a little more on what you mean by it "does not work on forwarded packets"?

**Comment by evilsocket** [comment]
because it just creates a listener at application layer

**Comment by NxxN39** [comment]
Just in case, did you add the rule to allow the incoming port?

netsh advfirewall firewall add rule name=”BetterCap-Ng” protocol=TCP dir=in localip=x.x.x.x  localport=xxxx action=allow

**Comment by evilsocket** [comment]
mmm nope i did not, i will try to see if that changes anything, thanks

**Comment by NxxN39** [comment]
Good write up from someone who apparently has been here already :)  http://woshub.com/port-forwarding-in-windows/

**Comment by evilsocket** [comment]
@NxxN39 added the firewall rule to enable the port, which is working ( I can connect to the box port 80 which is redirected to 8080 ), but it's not routing others' connections

**Comment by evilsocket** [comment]
From a conversation in our dev channel:

    as u can see from the code i'm succesfully enabling incoming traffic on those ports
    i also enabled routing with regedit
    everything works, problem is:
    that port redirection is fake
    well, not fake fake, but it's basically a socks proxy tunnelling from ip A to ip B
    so it does not forward connections at the packet level, like iptables does on linux
    which is what we'd need in order for the proxy to work

**Comment by NxxN39** [comment]
Is routing enabled on your machine? I remember a specific reg key has to be enabled to turn on routing on some versions of win. Which one are you using?

**Comment by evilsocket** [comment]
Yes I enabled routing via regedit ( `\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Tcpip\Parameters\IPEnableRouter` -> 0x00000001 ).

**Comment by evilsocket** [comment]
using windows 10

**Comment by evilsocket** [comment]
Also [this](https://github.com/evilsocket/bettercap-ng/blob/master/firewall/firewall_windows.go#L46) should enable forwarding too.

**Comment by ohpe** [comment]
They are basically the same command, one set via `netsh` and one via the registry. [REF.](https://blogs.technet.microsoft.com/networking/2008/11/20/balancing-act-dual-nic-configuration-with-windows-server-2008-nlb-clusters/)

**Comment by evilsocket** [comment]
Efforts are being made on [this branch](https://github.com/evilsocket/bettercap-ng/tree/packet_routing), removing from first milestone for now.

**Comment by evilsocket** [comment]
Closing this issue as port forwarding is just not supported on Windows at the firewall level like it is on other OS, userland packet routing is needed which makes everything slow as hell.
