### ISSUE TITLE
Clearing environment variables does not work with single quotes

### ISSUE THREAD

**Issue by vladionescu** [bettercap/bettercap#450]
# Prerequisites

Trying to clear a wifi.show.filter is unintuitive.

### Environment

Please provide:

* Bettercap version you are using. `6980b86`
* OS version and architecture you are using. `Debian 9 amd64`
* Go version if building from sources. `1.11.5.linux-amd64`
* Command line arguments you are using. `-iface wlxec086b08f0c8`
* Caplet code you are using or the interactive session commands. `set wifi.show.filter`
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

```
$ sudo bettercap -iface wlxec086b08f0c8 -debug
bettercap v2.16 (type 'help' for a list of commands)

 wlxec086b08f0c8  » [12:36:06] [sys.log] [dbg] FindGateway(wlxec086b08f0c8) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
 wlxec086b08f0c8  » [12:36:06] [sys.log] [dbg] FindGateway(wlxec086b08f0c8) output:
default via 10.137.0.6 dev eth0 
10.137.0.6 dev eth0 scope link
 wlxec086b08f0c8  » [12:36:06] [sys.log] [dbg] FindGateway(wlxec086b08f0c8): nothing found :/
 wlxec086b08f0c8  » [12:36:06] [sys.log] [dbg] Could not detect gateway.
 wlxec086b08f0c8  » [12:36:06] [session.started] {session.started 2019-02-15 12:36:06.172205544 -0800 PST m=+0.017311581 <nil>}
 wlxec086b08f0c8  » [12:36:06] [mod.started] events.stream
 wlxec086b08f0c8  » [12:36:06] [mod.started] net.recon
 wlxec086b08f0c8  » get wifi.show.filter 

  wifi.show.filter: ''

 wlxec086b08f0c8  » set wifi.show.filter AAAA
 wlxec086b08f0c8  » set wifi.show.filter 
 wlxec086b08f0c8  » [12:36:22] [sys.log] [err] unknown or invalid syntax "set wifi.show.filter", type help for the help menu.
 wlxec086b08f0c8  » 
 wlxec086b08f0c8  » set wifi.show.filter clear
 wlxec086b08f0c8  » get wifi.show.filter 

  wifi.show.filter: 'clear'

 wlxec086b08f0c8  » set wifi.show.filter ''
 wlxec086b08f0c8  » [12:36:39] [sys.log] [err] unknown or invalid syntax "set wifi.show.filter", type help for the help menu.
 wlxec086b08f0c8  » set wifi.show.filter ""
 wlxec086b08f0c8  » get wifi.show.filter 

  wifi.show.filter: ''

 wlxec086b08f0c8  »
```

### Steps to Reproduce

1. Set a wifi.show.filter to anything.
2. Try to clear it using either a blank filter or an empty single quoted string. Notice this throws errs.
3. Clear it by setting it to an empty double quoted string. This works.

**Expected behavior:** Single quoted empty strings should work because the representation of an empty filter is '', so the expectation is that you can set the filter to that value.

**Actual behavior:** Single quote and empty strings are error conditions.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by yungtravla** [comment]
You should put an effort in reading the manual and/or descriptions of commands and variables of bettercap before complaining about them. If you had done that, you would have known that you are using the wrong syntax.

This is how it works:

![screenshot from 2019-02-16 11-41-06](https://user-images.githubusercontent.com/29265684/52892650-27b32d00-31e0-11e9-80e4-ed488336063e.png)

**Comment by yungtravla** [comment]
@vladionescu sorry, I responded too quickly. The output you provided confused me once I got to:

```
 wlxec086b08f0c8  » set wifi.show.filter 
 wlxec086b08f0c8  » [12:36:22] [sys.log] [err] unknown or invalid syntax "set wifi.show.filter", type help for the help menu.
 wlxec086b08f0c8  » 
 wlxec086b08f0c8  » set wifi.show.filter clear
 wlxec086b08f0c8  » get wifi.show.filter
```
