### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by its0x08** [bettercap/bettercap#455]
Hello,
Congratulations for the new feature using PMKID to crack the wifi ..! 
Is there a  way combining the gps module to use the PMKID for war driving ?!

Thanks im advance!

**Comment by evilsocket** [comment]
could you please elaborate a bit more? there's already a gps module that you can use together with the wifi ones ..

**Comment by its0x08** [comment]
@evilsocket ok let me tell u the idea and you can tell me if its possible ..
Im making a wing(kind of drone) so i was planning on installing a "orange pi 0" on it and use it to collect PMKIDs on the move but would be also useful a logging file that will show time, lat, lon, (essid,Ssid or bssid).
So then I can make my script that parses it and puts it on Google Earth..
So the other thing is that I also need a compatible gps module( if you've tried any good one) to attach it to the setup..

**Comment by yungtravla** [comment]
@its0x08 you can already do that, bettercap prints the timestamp for every log, and if you use the `ticker` you can print the GPS coordinates + send PMKID frames every N seconds.

**Comment by its0x08** [comment]
@yungtravla thanks
Ill test it asap!

**Comment by N2Network** [comment]
> @evilsocket ok let me tell u the idea and you can tell me if its possible ..

@its0x08 I'm curious if you ever ended up implementing this and if you would mind sharing your code?

**Comment by N2Network** [comment]
@yungtravla could you give me a simple example command that would parse this data and write to a csv on a unique ticker event? I'm struggling to find anything to reference.

**Comment by evilsocket** [comment]
@N2Network I'm implementing a library / package to parse that data and use it for that type of extractions / renderings, some patience please :)

@yungtravla i got this ;)

**Comment by N2Network** [comment]
> this

Excellent, thank you.

**Comment by evilsocket** [comment]
https://github.com/bettercap/recording/blob/master/examples/example.go
