### ISSUE TITLE
Manufacturer add to wifi.show [feature request]

### ISSUE THREAD

**Issue by angusonmacgyver** [bettercap/bettercap#456]
Would you consider adding manufacturer of the router to wifi.show list ? It is a useful information to have when trying to identify vulnerable devices. Airodump has a switch --manufacturer to accomplish just that. 

Thanks once again for all your work

**Comment by evilsocket** [comment]
![oooooooooooo-can-do](https://user-images.githubusercontent.com/86922/53168575-4009ba00-35db-11e9-98fd-8cab13ed6a1c.jpg)

**Comment by angusonmacgyver** [comment]
You work quickly:)
