### ISSUE TITLE
credentials - terminal

### ISSUE THREAD

**Issue by ManOfGold3** [bettercap/bettercap#458]
bettercap : 2.16V
Hey sir the tool works just fine but i saw on some pic that fb-phish displays on the terminal screen the credentials like here: 

![image](https://user-images.githubusercontent.com/47866529/53193687-7b4dbe00-35c6-11e9-8ac3-9b039e31cb3f.png)

i got the credentials with wireshark why it did not display on the terminal screen? i did not see any module that can provide this..  
Did i do something wrong? it was removed?

forgot also the caplet "download autopwn" did not see anything in terminal 
yours:

![image](https://user-images.githubusercontent.com/47866529/53194152-8ce39580-35c7-11e9-94b6-e232c2db1795.png)

thankx anyway

**Comment by yungtravla** [comment]
... https://github.com/bettercap/bettercap/wiki
