### ISSUE TITLE
Decloaking Hidden WiFi Networks [feature request]

### ISSUE THREAD

**Issue by 4p3rtur3** [bettercap/bettercap#459]
It would be great if _<hidden>_ Networks could be decloaked via for example Management Beacon Packets.
Is that possible?

**Comment by evilsocket** [comment]
you only need to deauth clients ( wifi.deauth ) and wait, as described here https://www.bengrewell.com/2018/02/11/decloaking_hidden_wireless/ ... beacons are already parsed and the ESSID updated whenever bettercap detects a change.

**Comment by 4p3rtur3** [comment]
Yea I knew this method, but is it really necessary to deauth? Like in "wifite" where its parsing for those beacons and dekloacs hidden wifi's before you interact. I tried it before making this request, fixed wifi.recon.channel to my hidden networks channel and shut down the wifi at my clients myself and reconnected them after that again. Neither bettercap decloaked nor it captured the 4 Way Handshake "passively".

Sorry for walking on your nerves in a closed Issue Thread! I appreciate your work!
Kind regards
