### ISSUE TITLE
http.proxy not working because of an error in iptables

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#461]
Hello! I use bettercap on my smartphone (described below) and get an iptables error when trying to run http.proxy. When i try to reproduce the issue in Virtualbox (Kali x86) or on my PC (Kubuntu x64) using the same version of bettercap and iptables, I have everything working fine. Maybe it's the kernel firmware, but I'm not sure...

### Environment

* Bettercap version you are using:
  Bettercap 2.17 arm7
* OS version and architecture you are using:
  Kali linux, which is installed using Linux Deploy (chroot) on a Sony Xperia M (nicki) smartphone.
  All packages are up to date.
  Iptables version:
  `iptables v1.8.2 (nf_tables)`
  I use Lineage OS 14.1 firmware.
  Kernel version:
  `Linux localhost 3.4.0-nicki+ #1 SMP PREEMPT Fri Dec 14 21:06:28 HKT 2018 armv7l GNU/Linux`
* Go version if building from sources:
  I'm using a precompiled version
* Command line arguments you are using:
  `sudo bettercap -gateway-override 192.168.1.30`
* Caplet code you are using or the interactive session commands:
  In the interactive session, I enter the command
  `http.proxy on`
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ):
```
bettercap v2.17 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.103  » [14:43:54] [sys.log] [dbg] GatewayProvidedByUser(192.168.1.30) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [sys.log] [dbg] valid gateway ip 192.168.1.30
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [sys.log] [dbg] gateway is 192.168.1.30[f8:1a:67:8a:ef:dc]
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [session.started] {session.started 2019-02-25 14:43:54.408192517 +0300 +03 m=+0.302914736 <nil>}
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [mod.started] events.stream
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [endpoint.new] endpoint 192.168.1.100 detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).
192.168.1.0/24 > 192.168.1.103  » [14:43:54] [endpoint.new] endpoint 192.168.1.106 detected as 50:8f:4c:fb:0c:aa (Xiaomi Communications Co Ltd).
192.168.1.0/24 > 192.168.1.103  » [14:44:04] [endpoint.new] endpoint 192.168.1.104 detected as 00:13:0d:39:53:ee (Galileo Avionica).
192.168.1.0/24 > 192.168.1.103  » http.proxy on
ERROR for 'iptables [-P FORWARD ACCEPT]': exit status 4
192.168.1.0/24 > 192.168.1.103  » [14:44:06] [sys.log] [err] exit status 4
192.168.1.0/24 > 192.168.1.103  » q
[14:44:09] [mod.stopped] events.stream

Stopping modules and cleaning session state ...
ERROR for 'iptables [-t nat -D PREROUTING -i wlan0 -p TCP --dport 80 -j DNAT --to 192.168.1.103:8080]': exit status 2
```

### Steps to Reproduce

1. *Run bettercap*
2. *Just run http.proxy*

**Expected behavior:** *What you expected to happen*
  I want to run http.proxy

**Actual behavior:** *What actually happened*
  I get ERROR for iptables
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
iptables is simply not supported by a Kali chroot on Android

**Comment by garlapann** [comment]
> iptables is simply not supported by a Kali chroot on Android

But what may be a choice but to start bettercap outside the container?

**Comment by evilsocket** [comment]
RTFM https://github.com/bettercap/bettercap/wiki/Compilation-on-Android

**Comment by garlapann** [comment]
> RTFM https://github.com/bettercap/bettercap/wiki/Compilation-on-Android
Compilation to run in Termux or similar emulators? Or will my chroot Kali work too?

**Comment by garlapann** [comment]
How then do the utilities in Kali Nethunter work? Does it not use iptables for redirections?
