### ISSUE TITLE
Cannot compile on Termux

### ISSUE THREAD

**Issue by Hritik14** [bettercap/bettercap#463]
I'm unable to find `libusb1.0-dev` on termux.
It says package not found.
Further,
trying to install bettercap results in
`# /home/builder/.termux-build/_cache/18-aarch64-21-v2/bin/aarch64-linux-android-pkg-config --cflags  -- libusb-1.0
/home/builder/.termux-build/_cache/18-aarch64-21-v2/bin/aarch64-linux-android-pkg-config: fork/exec /home/builder/.termux-build/_cache/18-aarch64-21-v2/bin/aarch64-linux-android-pkg-config: no such file or directory`

**Comment by yungtravla** [comment]
libusb can be found in the [termux-root-packages](https://github.com/termux/termux-root-packages)

**Comment by Hritik14** [comment]
Successfully installed libusb yet the error doesn't seem to go away.

**Comment by yungtravla** [comment]
you need to provide all the info that was requested in the issue template that you deleted in order for us to be able to help you

**Comment by Hritik14** [comment]
My bad !
Updated the post with the template.

**Comment by yungtravla** [comment]
@Hritik14 thanks, can you please try again with the `-u` flag?

Example:

```
go get -u github.com/bettercap/bettercap
```

> The -u flag instructs get to use the network to update the named packages
and their dependencies. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.

**Comment by yungtravla** [comment]
@Hritik14 great :+1: 

The docs have been upgraded and moved to https://bettercap.org

I'll check to see if there is some missing info there, thanks!

**Comment by bogiton** [comment]
I was facing the same issue and I solved it by installing pkg-config and explicitly setting the path for it.
```
pkg install pkg-config
export PKG_CONFIG="/data/data/com.termux/files/usr/bin/pkg-config"
```

**Comment by yungtravla** [comment]
@bogiton thanks, that did the trick for me, I'll submit a PR :)
