### ISSUE TITLE
Bettercap 2.18 on MacOS reports that it is version 2.17

### ISSUE THREAD

**Issue by sdcampbell** [bettercap/bettercap#467]
*Description of the bug or feature request*

Bettercap 2.18 on MacOS reports that it is version 2.17

### Environment

Please provide:

* Bettercap version you are using. 2.18
* OS version and architecture you are using. Darwin rmt-mbp-4152.lan 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
* Go version if building from sources. N/A
* Command line arguments you are using. ./bettercap
* Caplet code you are using or the interactive session commands. N/A
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

sudo ./bettercap
Password:
bettercap v2.17 (type 'help' for a list of commands)

### Steps to Reproduce

1. *First Step* I created a new directory (test) to ensure that I wasn't executing some other version of Bettercap. 
2. *Second Step* Copied bettercap_macos_amd64_2.18.zip to 'test' directory.
3. *Third Step* unzip bettercap_macos_amd64_2.18.zip
4. *Fourth Step* sudo ./bettercap

**Expected behavior:** *What you expected to happen* I expected to see version 2.18 in the output.

**Actual behavior:** *What actually happened* I saw version 2.17.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
yeah, a stupid problem on my macOS build system, will be correct the next release :D
