### ISSUE TITLE
installation from source produces error (type *os.File has no field or method SyscallConn)

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#468]
bettercap installation from source throws the following error after a dependency update:

```shell
# github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
vendor/github.com/mdlayher/raw/raw_linux.go:88:14: f.SyscallConn undefined (type *os.File has no field or method SyscallConn)
```

### Environment

Please provide:

* Bettercap version you are using.
`bettercap v2.18`
* OS version and architecture you are using.
`Linux 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux`
* Go version if building from sources.
`go version go1.11.5 linux/amd64`
* Command line arguments you are using.
`go get -u github.com/bettercap/bettercap`
* Caplet code you are using or the interactive session commands.
` `
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
` `

### Steps to Reproduce

Install bettercap from source and find the following error:

```
# github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:88:14: f.SyscallConn undefined (type *os.File has no field or method SyscallConn)
```

I do not see why it complains about a non-existent function for os.File when godocs states that it is there:

https://golang.org/pkg/os/#File.SyscallConn

This is the line that throws the error:

https://github.com/mdlayher/raw/blob/81144197cf93eb7382abd04a6a15154cfce2e65c/raw_linux.go#L88

**Comment by adamtimmins** [comment]
I'm experiencing this error on the RPI Zero W, following @evilsocket's guide for project pita:

OS version and architecture
>  Linux pita 4.14.71-v6 #1 Sat Oct 27 11:07:28 UTC 2018 armv6l GNU/Linux

 Go version
> go version go1.11.6 linux/arm

Command line I'm using
> go get -u github.com/bettercap/bettercap

Following this guide: 
https://www.evilsocket.net/2018/07/28/Project-PITA-Writeup-build-a-mini-mass-deauther-using-bettercap-and-a-Raspberry-Pi-Zero-W/

**Comment by adamtimmins** [comment]
Cheers dude, works like a charm ;)

**Comment by evilsocket** [comment]
:+1:
