### ISSUE TITLE
Not compiled in termux because of an error "undefined: HIDRecon"

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#470]
Hi! I want to compile from the sources in the Termux on my Android M (CM 13.1), but get an error:

`termux@xperia ~ $ go get github.com/bettercap/bettercap`
`# github.com/bettercap/bettercap/modules/hid`
`go/src/github.com/bettercap/bettercap/modules/hid/duckyparser.go:13:7: undefined: HIDRecon`

### Environment

* OS version and architecture you are using.
*Android M (CM 13.1)*
* Go version if building from sources.
*go version go1.11.5 android/arm*
* Command line arguments you are using.
*go get github.com/bettercap/bettercap*

**Comment by garlapann** [comment]
Thank you! Now I will try

**Comment by garlapann** [comment]
`termux@xperia ~ $ go get github.com/bettercap/bettercap`
`go/src/github.com/bettercap/bettercap/modules/modules.go:13:2: build constraints exclude all Go files in /data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/modules/hid`
`termux@xperia ~ $`

**Comment by evilsocket** [comment]
ops, my bad, now it's fixed for real :D

**Comment by garlapann** [comment]
)))

**Comment by garlapann** [comment]
Thank you, everything is compiled and working!!!
