### ISSUE TITLE
BLE: Cannot connect to device multiple times. Hangs.

### ISSUE THREAD

**Issue by glassdonut** [bettercap/bettercap#471]
Issuing a command that connects to a BLE device works the first time. But subsequent connection attempts hang on "connecting to ...". This is not just multiple ble.enum attempts, but multiple ble connection attempts.

### Environment

Please provide:

* Bettercap version you are using: newest release (v2.18)
* OS version and architecture you are using: Ubuntu v18.04.2
* Go version if building from sources: n/a
* Command line arguments you are using: bettercap -debug
* Caplet code you are using or the interactive session commands: n/a
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

> bettercap v2.18 (type 'help' for a list of commands)
> _\*disable net recon, enable and disable ble.recon\*_

>\>\> ble.write 00:11:22:33:44:55:66 abcd 00
[sys.log] [inf] ble.recon connecting to 00:11:22:33:44:55:66 ...
[sys.log] [inf] ble.recon connected, enumerating all the things for 00:11:22:33:44:55:66!
[sys.log] [err] ble.recon writable characteristic abcd not found.
[sys.log] [inf] ble.recon disconnecting from 00:11:22:33:44:55:66 ...

>\>\> ble.write 00:11:22:33:44:55:66 abcd ff
[sys.log] [inf] ble.recon connecting to 00:11:22:33:44:55:66 ...
_**HANGS HERE**_

**(note: this happens with any combination of connection attempts from different commands (enum, write, etc). does not matter if the command fails (as it did here) or succeeds.**

### Steps to Reproduce

1. run `bettercap`
2. get devices with ble.recon on -> ble.recon off
3. ble.enum or ble.write to any device.
4. ble.enum or ble.write to the device again. (hangs)

**Expected behavior:** *What you expected to happen*
_The connection to succeed and the command to complete again._

**Actual behavior:** *What actually happened*
_Nothing after the "connecting to ..." message. Must restart session to re-issue these commands._

**Comment by evilsocket** [comment]
did you try other devices and/or other bluetooth adapters? because i can't reproduce

**Comment by glassdonut** [comment]
Yep, tested with different bluetooth devices and different adapters, same issue :\
Will reinstall clean and see if that helps.

**Comment by codeholio** [comment]
I may be encountering this too, I have a trigger to ble.enum on any ble.device.new event and it only completes on the first hit of the trigger, then hangs and sometimes leaves the ble adapter in a bad state requiring hciconfig up/down before resuming. v2.19
