### ISSUE TITLE
Bettercap performances configuration

### ISSUE THREAD

**Issue by vasiliyph** [bettercap/bettercap#472]
### Environment

* Bettercap version: 2.18
* OS version: Debian/Ubuntu/CentOS
* Go version: 1.11+

In this publication said about perfomances:
https://www.evilsocket.net/2018/02/27/All-hail-bettercap-2-0-one-tool-to-rule-them-all/

> Go’s amazing concurrency mechanisms allowes bettercap 2.0 to run on low end hardware and still keep proxying hundreds of connections per second and forwarding tens of hundres of packets

But how to achieve such perfomance?
Compile from source code module on Ubuntu 18.04 and run with http + https proxy module.
I wrote a regular utility on destop in Windows, so that at an interval of 1 second I sent 1 request to 3 sites through a proxy module.
After 3-4 minutes, the host periodically stops responding to some requests. That is, it does not support the load and some of the requests simply do not process (discard).
Configuration of the VPS: DigitalOcean VPS, 3vcpu, 1GB RAM. CPU VPS loaded by 30%. Try server with 2vcpu, 4GB RAM. CPU VPS loaded by 22-25 %.
In fact, the server does not support with the number of requests, beucase load not critical, but proxied host no connect.
What optimization should be carried out to get maximum performance? and yet, what is the limit / threshold for requests through such a proxy (http + https proxy with own CA + content injection)?

Maybe it is necessary to configure somehow an additional module or the server itself?
And in the documentation it was mentioned that you can run several copies of bettercap, will this help?

Thanks.

**Comment by yungtravla** [comment]
Please provide debug logs as requested in the template...

`After 3-4 minutes, the host periodically stops responding`

How do you know this is a fault with bettercap, and not a fault with the host?

We need those logs if you want us to help you.
