### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by aorizondo** [bettercap/bettercap#475]
The documentation should would be accessible in a single-file format, such as PDF, MD or RST. Its hard to work offline on this because one can not just easily download the documentation from[ bettercap.org](https://www.bettercap.org/intro/).

**Comment by yungtravla** [comment]
one can `git clone github.com/bettercap/website` to download all the documentation

**Comment by yungtravla** [comment]
@aorizondo or did you mean it is hard to navigate the website when it is offline? and therefore want it in a single file format?

**Comment by aorizondo** [comment]
@yungtravla thanks for the tip
