### ISSUE TITLE
How to display the event date as in bettercap 1.x ?

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#476]
Hi! Is there a way to add a date before time to the output of the interactive session? Default settings show only the event time, while in earlier versions bettercap in each row displays the date and then time. And if it is possible, how to adjust the date and time format? Thanks in advance!

**Comment by evilsocket** [comment]
there's no way to do it currently, will implement now, stay tuned ;)

**Comment by garlapann** [comment]
ok, thanks!

**Comment by evilsocket** [comment]
implemented, you can see an example here https://www.bettercap.org/modules/core/events.stream/#examples

**Comment by evilsocket** [comment]
```sh
sudo bettercap -eval "set events.stream.time.format Mon Jan 2 15:04:05 -0700 MST 2006"
```

or just (during the interactive session):

```
> set events.stream.time.format Mon Jan 2 15:04:05 -0700 MST 2006
```

**Comment by garlapann** [comment]
doesn't work for me

`termux@xperia ~ $ sudo bettercap -eval "set events.stream.time.format Mon Jan 2 15:04:05 -0700 MST 2006 ; net.sniff on"`
`bettercap v2.18 (type 'help' for a list of commands)`

`[15:23:15] [endpoint.new] endpoint 192.168.1.100 (roma-pc.lan.) detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).`
`192.168.1.0/24 > 192.168.1.103  » [15:23:17] [endpoint.new] endpoint 192.168.1.104 detected as 00:13:0d:39:53:ee (Galileo Avionica).`
`192.168.1.0/24 > 192.168.1.103  » [15:23:17] [net.sniff.mdns] mdns marina-phone.lan. : PTR query for _37F83649._sub._googlecast._tcp.local`
`192.168.1.0/24 > 192.168.1.103  » [15:23:17] [net.sniff.mdns] mdns marina-phone.lan. : PTR query for _googlecast._tcp.local`

**Comment by evilsocket** [comment]
did you pull the new code from master?

**Comment by garlapann** [comment]
I'm an idiot )))

**Comment by evilsocket** [comment]
you can use this https://github.com/bettercap/bettercap/releases/download/v2.19/bettercap_android_arm_2.19.zip

**Comment by garlapann** [comment]
I compile on the device at the moment, I will check soon... You said there would be no precompiled versions for arm, right?

**Comment by evilsocket** [comment]
well, i managed to solve the main compilation issue i had on android arm, so it's now available again :)

**Comment by garlapann** [comment]
Checked out, works perfectly! That's what was required, thank you very much!

`termux@xperia ~ $ sudo bettercap -eval "set events.stream.time.format Mon Jan 2 15:04:05 -0700 MST 2006 ; net.sniff on"`
`bettercap v2.19 (built for android arm with go1.12) [type 'help' for a list of commands]`

`[Sat Mar 9 15:39:47 +0000 UTC 2019] [endpoint.new] endpoint 192.168.1.100 detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).`
`192.168.1.0/24 > 192.168.1.103  » [Sat Mar 9 15:39:50 +0000 UTC 2019] [endpoint.new] endpoint 192.168.1.104 (marina-phone.lan.) detected as 00:13:0d:39:53:ee (Galileo Avionica).`

**Comment by evilsocket** [comment]
you're welcome! :+1:

**Comment by garlapann** [comment]
Could you add some information to the documentation on how to change the date format?
For example, if I want to see the format "2019-03-09 20:30" in my output.
