### ISSUE TITLE
Build fails on Raspberry

### ISSUE THREAD

**Issue by Throwaway684736** [bettercap/bettercap#477]
I'm still on 1.6.2 which works flawlessly.

Tried to install the latest build, but it fails to complete. All deps are met.
Here's the output:

go get github.com/bettercap/bettercap

# github.com/bettercap/bettercap/caplets
../go/src/github.com/bettercap/bettercap/caplets/manager.go:39: undefined: sort.Slice
# github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
../go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:134: undefined: time.Until
../go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:324: undefined: unix.Errno
../go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:337: undefined: unix.Errno
root@localhost:~/tmp# cd $GOPATH/src/github.com/bettercap/bettercap
--
root@localhost:~/go/src/github.com/bettercap/bettercap# make build 
# github.com/bettercap/bettercap/caplets
caplets/manager.go:39: undefined: sort.Slice
# github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
vendor/github.com/mdlayher/raw/raw_linux.go:134: undefined: time.Until
vendor/github.com/mdlayher/raw/raw_linux.go:324: undefined: unix.Errno
vendor/github.com/mdlayher/raw/raw_linux.go:337: undefined: unix.Errno
Makefile:10: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by yungtravla** [comment]
follow the [instructions](https://www.bettercap.org/installation/)....

**Comment by yungtravla** [comment]
check your go version, and fill out a complete issue so we're able to help
