### ISSUE TITLE
Сan't change time zone

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#478]
You are tired of me I guess, but I have another difficulty. I can't change my time zone to Moscow time.
I tried to adjust the date format for myself and it worked:
`$ sudo bettercap -eval "set events.stream.time.format 2006-01-02 03:04:05 MST; net.sniff on"`
`bettercap v2.19 (built for android arm with go1.12) [type 'help' for a list of commands]`

`192.168.1.0/24 > 192.168.1.103  » [2019-03-10 11:33:00 UTC] [endpoint.new] endpoint 192.168.1.100 detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).`

But when I set up at MSK:
`$ sudo bettercap -eval "set events.stream.time.format 2006-01-02 03:04:05 MSK; net.sniff on"`
`bettercap v2.19 (built for android arm with go1.12) [type 'help' for a list of commands]`

`[2019-03-10 11:33:27 MSK] [endpoint.new] endpoint 192.168.1.100 (roma-pc.lan.) detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).`

How to do it properly? Or is it a bug?

**Comment by evilsocket** [comment]
closing because this is about golang timeformat more than bettercap. did you try using the offset instead of the time zone name? ` +03:00` instead of `MST`

**Comment by evilsocket** [comment]
this also will help https://yourbasic.org/golang/format-parse-string-time-date-example/

**Comment by garlapann** [comment]
I tried "+3" and "+03", to which the output was received "+10". Thanks for the reply and for the link, I'll deal with it.

**Comment by garlapann** [comment]
Did you test the time zone change yourself? I don't know what you changed in the code, but I think it's broken. +03:00 not working. +0300 also does not work. Running without parameters also displays the time not corresponding to the locale, but previous versions were able to take the time zone from the locale! I could not get anything to work except MST, although it is displayed when running without parameters. It feels like a variable is being handled incorrectly. I'm upset...

**Comment by ohpe** [comment]
the option is a `time.Format` not a `time.Parse`, no timezone change should be allowed but just output formatting.

**Comment by garlapann** [comment]
The question remains: how the hell do you get release 2.19 to show the time according to the locale?

**Comment by yungtravla** [comment]
`TZ=Australia/Sydney bettercap`

**Comment by garlapann** [comment]
Sorry guys, it's not a bettercap problem. This is the Termux problem. On Ubuntu the time is displayed correctly. Sorry about the noise.

**Comment by garlapann** [comment]
Then the question is: what variables bettercap determines the time zone?
