### ISSUE TITLE
Dockerfile reporting errors - probably fixed - suggestion for new Dockerfile

### ISSUE THREAD

**Issue by TomHubGit** [bettercap/bettercap#480]
---
Hi, I just tried to build the latest version in a docker image and came across some errors. I was able to modify the Dockerfile so the build succeeds, but I am quite a docker newbie and not sure if this is correct. Please find my suggestions at the very end.

issues:
Cloning the current git repo and trying to build a docker image fails in two stages:
Missing libusb, I assume do to the wrong package name (see my final comment at the end):
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libusb-1.0-dev (missing):
    required by: world[libusb-1.0-dev]
The command '/bin/sh -c apk add --no-cache --update bash iptables wireless-tools build-base libpcap-dev libusb-1.0-dev linux-headers libnetfilter_queue-dev git' returned a non-zero code: 1
```
and cloning caplets, due to the fact that git clone wants to clone caplets into bettercap/caplets which contains the go code rather then in InstallBase    = "/usr/local/share/bettercap/" as defined in env.go
```
Step 10/17 : RUN git clone https://github.com/bettercap/caplets
 ---> Running in 331fc0ac0a7b
fatal: destination path 'caplets' already exists and is not an empty directory.
The command '/bin/sh -c git clone https://github.com/bettercap/caplets' returned a non-zero code: 128

```
### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
Latest, 2.19
* OS version and architecture you are using.
4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Go version if building from sources.
* Command line arguments you are using.
docker image build -t bettercap:v2.19 .
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1) git clone https://github.com/bettercap/bettercap bettercap
2) docker image build -t bettercap:v2.19 .

**Expected behavior:** *What you expected to happen*
Successful build of docker image
**Actual behavior:** *What actually happened*
Build breaks
-- 

Suggestion:
Modify the Dockerfile and
replace libusb-1.0-dev with libusb-dev

and define the path for caplets 
RUN git clone https://github.com/bettercap/caplets /usr/local/share/bettercap/

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by TomHubGit** [comment]
I still get an error when executing the container. So I assume libusb-dev is not the right package. Any ideas anyone?

**Comment by TomHubGit** [comment]
I think I fixed it, the problem was that the libusb was not part of the second stage of the build.
libusb was added to the second stage of the build:
```
# final stage
FROM alpine
RUN apk add --no-cache --update bash libusb-dev iproute2 libpcap libnetfilter_queue wireless-tools
```

**Comment by TomHubGit** [comment]
What still exists is the problem of the caplets, and I am quite confused about the docker handling here.

In the build stage I added:
`RUN git clone https://github.com/bettercap/caplets.git /usr/local/share/bettercap/caplets/`

Looking a the created layer image, this works fine and creates the corresponding files and folder:
```
/usr/local/share/bettercap/caplets # ls -lat
total 240
drwxr-xr-x    8 root     root          4096 Mar 12 10:29 .
drwxr-xr-x    3 root     root          4096 Mar 12 10:29 ..
-rw-r--r--    1 root     root         35187 Mar 12 10:29 LICENSE.md
-rw-r--r--    1 root     root           147 Mar 12 10:29 Makefile
-rw-r--r--    1 root     root          7889 Mar 12 10:29 README.md
-rw-r--r--    1 root     root           280 Mar 12 10:29 airodump.cap
-rw-r--r--    1 root     root            92 Mar 12 10:29 ap-config.cap
-rw-r--r--    1 root     root           237 Mar 12 10:29 ap.cap
-rw-r--r--    1 root     root           388 Mar 12 10:29 beef-active.cap
-rw-r--r--    1 root     root           472 Mar 12 10:29 beef-inject.js
-rw-r--r--    1 root     root           166 Mar 12 10:29 beef-passive.cap
-rw-r--r--    1 root     root           666 Mar 12 10:29 crypto-miner.cap
-rw-r--r--    1 root     root          1842 Mar 12 10:29 crypto-miner.js
drwxr-xr-x    9 root     root          4096 Mar 12 10:29 download-autopwn
...
```

However when I copy the files within the Dockerfile, the result is somewhat "messed up" with subfolders being moved in the caplets dir, the folder download-autopwn disappeared etc.

```
/app # ls -lat /usr/local/share/bettercap/caplets
total 404
drwxr-xr-x   12 root     root          4096 Mar 12 10:29 .
drwxr-xr-x    3 root     root          4096 Mar 12 10:29 ..
-rw-r--r--    1 root     root            17 Mar 12 10:29 .gitignore
-rw-r--r--    1 root     root         35187 Mar 12 10:29 LICENSE.md
-rw-r--r--    1 root     root           259 Mar 12 10:29 Makefile
-rw-r--r--    1 root     root          1082 Mar 12 10:29 README.md
-rw-r--r--    1 root     root           280 Mar 12 10:29 airodump.cap
drwxr-xr-x    2 root     root          4096 Mar 12 10:29 android
-rw-r--r--    1 root     root            92 Mar 12 10:29 ap-config.cap
-rw-r--r--    1 root     root           237 Mar 12 10:29 ap.cap
...
```

The directive I used in the Dockerfile is
`COPY --from=build-env /usr/local/share/bettercap/caplets/* /usr/local/share/bettercap/caplets/`

**Comment by TomHubGit** [comment]
Ok, so this was an issue with my Dockerfile. After changing it, it seems to work now.

This is my final Dockerfile, maybe it helps others as well:
```
# build stage
FROM golang:alpine AS build-env

ENV SRC_DIR $GOPATH/src/github.com/bettercap/bettercap

# added by Tom
ENV CAP_DIR /usr/local/share/bettercap/caplets

RUN apk add --update ca-certificates
RUN apk add --no-cache --update bash iptables wireless-tools build-base libpcap-dev libusb-dev linux-headers libnetfilter_queue-dev git

WORKDIR $SRC_DIR
ADD . $SRC_DIR
RUN go get -u github.com/golang/dep/...
RUN make deps
RUN make

# added by Tom
RUN git clone https://github.com/bettercap/caplets $CAP_DIR

# final stage
FROM alpine
RUN apk add --no-cache --update bash libusb-dev iproute2 libpcap libnetfilter_queue wireless-tools
COPY --from=build-env /go/src/github.com/bettercap/bettercap/bettercap /app/
COPY --from=build-env /go/src/github.com/bettercap/bettercap/caplets /app/

# added by Tom
COPY --from=build-env $CAP_DIR $CAP_DIR/

WORKDIR /app

EXPOSE 80 443 53 5300 8080 8081 8082 8083 8000
ENTRYPOINT ["/app/bettercap"]
```

**Comment by TomHubGit** [comment]
Preserving the /usr/local/share/bettercap/caplets directory should also make the automated update work:
```

/opt/my-containers/bettercap# docker run -it --privileged --net=host bettercap:v2.19
bettercap v2.19 (built for linux amd64 with go1.12) [type 'help' for a list of commands]

10.19.0.0/16 > 10.19.0.5  » [10:59:18] [sys.log] [war] Could not find mac for 165.227.160.1
10.19.0.0/16 > 10.19.0.5  » caplets.update
[10:59:28] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[10:59:30] [sys.log] [inf] caplets installing caplets to /usr/local/share/bettercap/caplets ...
```

**Comment by evilsocket** [comment]
hi, would you mind forking the project, fixing the Dockerfile and sending a pull request? <3

**Comment by evilsocket** [comment]
i pushed a new Dockerfile that should fix the issue

**Comment by TomHubGit** [comment]
hi @evilsocket, thanks for that. This time you have been faster ;)
