### ISSUE TITLE
HID: this component is not supported on this OS [Windows]

### ISSUE THREAD

**Issue by 4p3rtur3** [bettercap/bettercap#482]
I am using a successfully flashed Bitcraze.se Crazyradio PA Dongle Rev.C which is working fine on my Linux machine with bettercap (and RFStorm nRF24LU1+ Research Firmware).
At my Windows I tried:
1. Without Zadig
2. libusb-win32 (v1.2.6.0)
3. With WinUSB (v6.1.7600.16385)
![Zadig](https://user-images.githubusercontent.com/33102632/54174792-863e9480-4488-11e9-8b36-f9182bd1b3c8.png)

In any case I get this:
![Anmerkung 2019-03-12 052505](https://user-images.githubusercontent.com/33102632/54174791-85a5fe00-4488-11e9-9743-1e05a0043b5a.png)

### Environment

Please provide:

* bettercap v2.19 (built for windows amd64 with go1.9.2)
* Windows 10 Education 64Bit (1809 Build 17763.348)
* Via CMD: bettercap.exe

### Steps to Reproduce

1. Start bettercap via CMD: _bettercap.exe_
2. Start HID Recon: _hid.recon on_
3. See/read error: _this component is not supported on this OS_

**Expected behavior:** *Similar behavior like on my Linux machine.*

**Actual behavior:** *Got an error that this OS (case: Windows) is not supported*

-- 

I am using libusb-1.0(64Bit) on Windows for my SDR-RTL devices and programms with no problems, so this should work I guess? 

Kind regards!

**Comment by evilsocket** [comment]
the module is simply not compiled by default for windows, mostly because i couldn't easily create a build environment myself, as it uses `https://github.com/google/gousb`, which is `pkg-config` based, which looks like a pain in the ass to configure properly on windows :D

would give me a couple of tips on how to create this env properly? in that case i could start testing the module and then releasing it for windows, thanks! :D

**Comment by 4p3rtur3** [comment]
**Allright here we go:**

**Note:** **_Let all installations add their PATH to Windows %PATH%!!!_**
**Download and install GoLang for Windows:** https://golang.org/dl/
**Download and install MSYS2(msys2-x86_64*.exe):** https://www.msys2.org/
**Download and install Git for Windows:** https://gitforwindows.org _or_ https://git-scm.com/download/win _(both seems legit, I took git-scm.com)_

**We need MSYS2 to use the same $PATH like the Windows one(%PATH%):**
_For that we go to MSYS2 dir and edit "msys2_shell.cmd" --> uncomment "set MSYS2_PATH_TYPE=inherit" at line ~16(rem set MSYS2_PATH_TYPE=inherit by default)._

**Start msys2_shell.cmd and use following commands for Updates(needs a restart of the Terminal and a second update command), needed packages(like pkg-config and libusb) and set the right PKG_CONFIG_PATH:**
_pacman -Syu
pacman -S --needed base-devel msys2-devel
pacman -S mingw64/mingw-w64-x86_64-libusb
export PKG_CONFIG_PATH="C:\msys64\mingw64\lib\pkgconfig:"_

**Try to make gousb:**
_go get -v github.com/google/gousb_

**Done.**

**Comment by 4p3rtur3** [comment]
Somehow it wont compile properly because of 9+ errors like these in hid_unsupported.go:
![Anmerkung 2019-03-14 133722](https://user-images.githubusercontent.com/33102632/54357438-5ba63480-465e-11e9-86ce-e8f2c870bd30.png)

hid.go:
![Anmerkung 2019-03-14 133847](https://user-images.githubusercontent.com/33102632/54357494-82fd0180-465e-11e9-9688-444d4cde2eb7.png)

![hiderr](https://user-images.githubusercontent.com/33102632/54357539-97d99500-465e-11e9-9bdc-dc6f0226e8dc.png)

I am brand new to Golang, guess I fail to see the issue here, but anyway there are no complications with pkg-config and libusb anymore :) 

**And somehow MSYS2 does not remember** 
_set PKG_CONFIG_PATH="C:\msys64\mingw64\lib\pkgconfig:"
export PKG_CONFIG_PATH="C:\msys64\mingw64\lib\pkgconfig:"_
so it must be recalled every session.

**Comment by evilsocket** [comment]
yeah you have to uncomment the `!windows` directive from the hid .go files

**Comment by 4p3rtur3** [comment]
**Okay here the final Update**

**Building via the _MSYS2 MSYS_ Terminal leads to this:**
![Anmerkung 2019-03-14 163859](https://user-images.githubusercontent.com/33102632/54370910-c1071f00-4678-11e9-909b-e1e9b5c7ce1a.png)

**Of course we must build via the _MSYS2 MinGW 64-bit_ Terminal:**
![Anmerkung 2019-03-14 164015](https://user-images.githubusercontent.com/33102632/54371014-f4e24480-4678-11e9-8be0-afd32216416c.png)

_sudo make install_ of course does not work on Windows so I put on the ".exe" extension manually on "bettercap" binary and added the needed "libusb-1.0.dll" to the same directory.

**E voilà!:**
![done](https://user-images.githubusercontent.com/33102632/54371256-5efae980-4679-11e9-9d95-d3cc7a26bc21.png)

Thank you @evilsocket  for developing this great project! 

Kind regards :)

**Comment by evilsocket** [comment]
trying it now, thanks so much! now the challenge is making this work via ssh (https://github.com/bettercap/bettercap/blob/master/build.sh#L54)

**Comment by evilsocket** [comment]
mmm @4p3rtur3, I've installed everything via pacman, set the env variables (each time, in every new shell i've openened) and got to the point of running `c:\msys64\mingw64.exe` for the other shell, but I still got this:

![Schermata da 2019-03-16 12-27-22](https://user-images.githubusercontent.com/86922/54474599-2547f100-47e7-11e9-9172-1d456d995800.png)

**Comment by 4p3rtur3** [comment]
Alright this is my mistake, I copied the "mingw64" folder from the "x86_64-8.1.0-posix-seh-rt_v6-rev0" installation (https://sourceforge.net/projects/mingw-w64/) into the MSYS2 root direcotry "C:\msys64" and kind of patched the MSYS2 Mingw64.

Have not thoght about that because I needed it for some other projects, but I completely uninstalled MSYS2 und recreated everything and found out that the missing files are in that "x86_64-8.1.0-posix-seh-rt_v6-rev0" installation. So just copy the folder like I described without overwriting and it should finally work now:
![Anmerkung 2019-03-17 033833](https://user-images.githubusercontent.com/33102632/54484503-89f76000-4868-11e9-99d7-fa713030b477.png)

Again I am very sorry for not mentioning this, I did not think that primary worked because of it!

Kind regards!

**Comment by evilsocket** [comment]
after replacing folders, setting environment variables and -i'm not even sure what i did- i managed to compile! :D thanks a ton

![Schermata da 2019-03-17 12-16-44](https://user-images.githubusercontent.com/86922/54489631-9c948800-48ae-11e9-95aa-831b42935f6f.png)

**Comment by realgam3** [comment]
Even after those messages it took me a whole day to compile battercap on my windows machine :\
This is what i done:
https://www.msys2.org/

On MSys2:
pacman -Syu
pacman -S mingw-w64-x86_64-go mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libusb

On Windows:
export GOPATH=%USERPROFILE%\go
export GOROOT=C:\MSys64\mingw64\lib\go
export PATH=%PATH%;%GOPATH%\bin;%GOROOT%\bin;C:\MSys64\mingw64\bin
export PKG_CONFIG_PATH=C:\MSys64\mingw64\lib\pkgconfig
