### ISSUE TITLE
compilation error on termux : no such file or directory 

### ISSUE THREAD

**Issue by xyzNOTNOOB** [bettercap/bettercap#486]
### Environment

Please provide:

* Bettercap 2.19
* android  6.0.1  aarch64 processor 
* device redmi note 3 sd edition
* Go version go1.12 android/arm64
* used commands mentioned  here: https://www.bettercap.org/installation/ to compile from source on android 
### Steps to Reproduce
-pkg install root-repo
-pkg install golang git libpcap-dev libusb-dev
-go get -u github.com/bettercap/bettercap

**Expected behavior: to compile and move executable to go/bin folder 

**Actual behavior:i got this error 

-- /home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config --cflags  -- libusb-1.0
/home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config: fork/exec /home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config: no such file or directory

....... 
i was on version 2.11 or 2.9 - actually i can't remember - for a while it compiled successfully on the same device the same os.
i just made an acc. to find solution for this prob. help will be greatly appreciated :)

**Comment by evilsocket** [comment]
oh yeah, i forgot about this one ... there's one terrible fix for this (will add it to the docs now, thanks for reminding me! :D), remount / as `rw`, create that folder yourself, and symlink the file:

```sh
sudo su
mount -o rw,remount /
mkdir -p /home/builder/.termux-build/_cache/18-arm-21-v2/bin/
ln -s `which pkg-config` /home/builder/.termux-build/_cache/18-arm-21-v2/bin/arm-linux-androideabi-pkg-config
```

**Comment by evilsocket** [comment]
closed with https://github.com/bettercap/website/commit/6a2176f9a6ae7b6c0f6524965ddd934614aaf97d

**Comment by evilsocket** [comment]
opened https://github.com/termux/termux-packages/issues/3505

**Comment by shownb** [comment]
i installed like that:
apt update
apt install golang git libpcap-dev libusb-dev pkg-config
go get -u github.com/bettercap/bettercap

without any problem.

**Comment by slegna29** [comment]
Do i need to root my device to install zphisher in my termux?? That error always appears in my device everytime i install zphisher 😭😭 teach me how to fix it pls..

**Comment by umairmaqsood558** [comment]
Do i need to root my device to install zphisher in my termux?? That error always appears in my device everytime i install zphisher 😭😭 teach me how to fix it pls.    no

**Comment by shuvo49** [comment]
cp cannot start no such file or directory in termux

**Comment by Horse010** [comment]
عندما احاول تشغيل اي أداة  مثلا python2 Lazymux.py 
يكتب لي   Errno 2] No such file or directory

**Comment by iboa20010** [comment]
> 

Why
![Screenshot_20220421-010814_Termux](https://user-images.githubusercontent.com/103155933/164333217-c73e3a20-e995-4f4d-9ade-be251db81a45.jpg)

**Comment by DualGiT31** [comment]
Pkg install golang...

**Comment by romanprem0123** [comment]
> Do i need to root my device to install zphisher in my termux?? That error always appears in my device everytime i install zphisher 😭😭 teach me how to fix it pls. no
rxce file is there send please  +91 9360414662 my whatsapp

**Comment by Ameer786smok** [comment]
Termux app is lot of errors pls fix them any tool installetion warenty errors

**Comment by rajbir999** [comment]
![Screenshot_2024-09-01-16-40-52-331_com termux](https://github.com/user-attachments/assets/71d5fd24-6cdf-45a7-973e-cdf239bf4403)


[*] Choose an option: 1
main.sh: line 46: cd: /data/data/com.termux/files/home/venom-instagram-bruteforce/10M-pass: No such file or directory
bash: 10M-pass.sh: No such file or directory        plz help me

**Comment by rajbir999** [comment]
Plz help me all members
