### ISSUE TITLE
Need to fix time zone definition in Android

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#487]
Hi, my previous issue #478 was locked for conversation but the problem was not solved. I mistakenly thought it was a _termux_ error, but it's not. 
In fact, it's a fairly long-standing **golang flaw**  golang/go#20455.
I solved the problem locally in the same way that **tmm1** used in his case https://github.com/golang/go/issues/20455#issuecomment-342287698. It's not very elegant because I'm not very good at programming, but it still works for me.
I announced _fixTimezone()_ on _bettercap/vendor/github.com/mgutz/logxi/v1/init.go_ and called in _init()_. 
In any case, I want to ask the developers of bettercap to add this crutch to the code until a fix for _golang_ appears. Need a method _isAndroid()_, which will recognize Android and perform this fix.
Thank you in advance for your attention.

**Comment by evilsocket** [comment]
as you said, it's a go flaw, that is why the other issue has been closed, and this is gonna be closed too.
