### ISSUE TITLE
HID.SNIFF is not showing sniffing output

### ISSUE THREAD

**Issue by SymbianSyMoh** [bettercap/bettercap#490]
*Description of the bug or feature request*
Based on the LONG discussion we had on twitter (https://mobile.twitter.com/SymbianSyMoh/status/1105626843326173185), HID.Sniff module is not outputting anything which is unclear neither in the documentation nor in the behavior of the module functionality.

### Environment
* Bettercap version: bettercap v2.19 (built for linux amd64 with go1.10.4)
* OS version and architecture:  Kali GNU/Linux Rolling x86_64, Kernel: 4.19.0-kali3-amd64 
* Command line arguments: -autostart "hid.recon, events.stream" -eval "set ticker.commands 'clear; hid.show'; ticker on" then hid.sniff ADDR

### Steps to Reproduce
1. Start hid.recon
2. Choose to sniff a specific target hid.sniff ADDR

**Expected behavior:** *What you expected to happen*
I'm expecting hid.sniff ADDR to show sniffed packets

**Actual behavior:** *What actually happened*
hid.sniff ADDR is not showing sniffed packets hence no output

**Comment by evilsocket** [comment]
hey @SymbianSyMoh, what do you think about it?

**Comment by SymbianSyMoh** [comment]
@evilsocket I can confirm, Works as expected 👍 
![Screen Shot 2019-03-15 at 11 51 33 PM](https://user-images.githubusercontent.com/3141848/54471405-03665400-477e-11e9-9333-994a011e59aa.png)
