### ISSUE TITLE
HTTPS error reading SNI timeout/reset by peer/EOF

### ISSUE THREAD

**Issue by vasiliyph** [bettercap/bettercap#491]
* Bettercap version: 2.18
* OS version and architecture: Ubuntu 18.04 x64 
* Go version if building from sources: 1.11
* Command line arguments you are using: sudo bettercap -caplet /home/mitm6.cap -cpu-profile /home/cpu.txt -mem-profile /home/mem.txt

Caplet code:

```
set http.proxy.script inject.js
set https.proxy.script inject.js

set https.proxy.certificate ca.pem
set https.proxy.key key.pem

http.proxy on
https.proxy on

sleep 1

arp.spoof on
```

inject.js code:

```
function onLoad() {
    //log("onLoad");
}

function onResponse(req, res) {
	log( "Path: " + req.Path );
	log( "Hostname: " + req.Hostname );
	var body = res.ReadBody();
	log( "body: " + body );
}
```

Launched the system. The number of requests for proxying is 5-10 requests per second. Sites http and https (mostly https).
In the console, errors of this type appear regularly:

> https.proxy error reading SNI: read tcp 10.10.0.6:8083 -> 5.18.234.67:24438: read: connection reset by peer
> https.proxy error reading SNI: read tcp 10.10.0.6:8083 -> xxx.xxx.xxx.xxx:xxxxx: read: connection reset by peer
> 
> https.proxy error reading SNI: read tcp 10.10.0.6:8083 -> 106.197.136.175:54982: i/o timeout
> https.proxy error reading SNI: read tcp 10.10.0.6:8083 -> xxx.xxx.xxx.xxx:xxxxx: i/o timeout
> 
> https.proxy error reading SNI: EOF.

Screenshots: 
![Безымянный](https://user-images.githubusercontent.com/22670109/54344367-1e3fa800-465a-11e9-8aef-dff41ec7f356.png)
![Screenshot_2](https://user-images.githubusercontent.com/22670109/54344375-226bc580-465a-11e9-94e1-ed02c6fa02c2.png)
![Screenshot_3](https://user-images.githubusercontent.com/22670109/54344378-24358900-465a-11e9-849b-e055b5d65973.png)

Note: The system works through an external DNS server (BIND) forwards requests to the Bettercap proxy server. Perhaps these are requests from the system applications, and not from the browser.

**Comment by evilsocket** [comment]
yeah sometimes i get those too, but usually they don't interfere with the actual navigation (client side), that is why it's reported as a warning instead of an error. Do you, like me, only experience that error or is there also something not working while the requests are being proxied?

**Comment by vasiliyph** [comment]
In fact, this does not affect surfing in the browser or any applications, judging by my tests.

I will not open a new report, I want to ask this.
Then one more question: how on Ubuntu to launch bettercap from the system, and not from the user? Because if you run from the user and close the session (putty), then bettercap of course closes. Try some methods from google for running process as system ( setsid or & ). Maybe make bettercap as service to run as service? Thanks.

**Comment by evilsocket** [comment]
https://www.gnu.org/software/screen/
