### ISSUE TITLE
error accepting connection: too many open files.

### ISSUE THREAD

**Issue by vasiliyph** [bettercap/bettercap#493]
* Bettercap version: 2.18
* OS version and architecture: Ubuntu 18.04 x64 
* Go version if building from sources: 1.11
* Command line arguments you are using: sudo bettercap -caplet /home/mitm6.cap -cpu-profile /home/cpu.txt -mem-profile /home/mem.txt

Caplet code:

```
set http.proxy.script inject.js
set https.proxy.script inject.js

set https.proxy.certificate ca.pem
set https.proxy.key key.pem

http.proxy on
https.proxy on

sleep 1

arp.spoof on
```

inject.js code:

```
function onResponse(req, res) {
	var reqJsPath = req.Path;
	if (reqJsPath.replace(/\?.*/, "").match(/\.js$/i)){
		log( "js extension exist");

		var body = res.ReadBody();
		res.Body = body + "console.log('log js verification')";
	}
}
```

Launched the system. The number of requests for proxying is 7-10 requests per second. Sites http and https (mostly https).
After 10 minutes, errors fell down:

> https.proxy error accepting connection: accept tcp 10.10.0.6:8083: accept4: too many open files.
> https.proxy error accepting connection: accept tcp 10.10.0.6:8083: accept4: too many open files; retrying in 10/20/40/etc ms
> unknown or invalid syntax "Connection: Keep-Alive:"
> net.recon pipe2: too many open files

Screenshots:
![screen_bug](https://user-images.githubusercontent.com/22670109/54472105-9930cc00-47dc-11e9-801d-1bd7056412db.png)
![Screenshot_5](https://user-images.githubusercontent.com/22670109/54472106-9a61f900-47dc-11e9-8c51-d052782153d5.png)
![Screenshot_10](https://user-images.githubusercontent.com/22670109/54472108-9b932600-47dc-11e9-865b-f3f7d0259502.png)

When the server was restarted and the session started after 10 minutes, it began to work normally again without such an error. But such an error is not the first time it appears.

The cpu and mem log can not be applied, because I had to close the session by force of rebooting the server (the console does not accept/respond to the q command).

**Comment by evilsocket** [comment]
why in the second picture you're trying to execute http requests as commands?!

**Comment by evilsocket** [comment]
also, when that error happens, would you mind running the following command in another terminal:

    sudo lsof -p `pidof bettercap`

and paste here the output? thanks!

**Comment by vasiliyph** [comment]
The problem repeated. I attach a log file. Run command 2 times (there is a separation)
[log.txt](https://github.com/bettercap/bettercap/files/2974021/log.txt)

**Comment by evilsocket** [comment]
https://stackoverflow.com/questions/3734932/max-open-files-for-working-process
