### ISSUE TITLE
HID: usb device 1915:0102 not found on mac

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#497]
Hello, I'm trying  to use hid.recon on Mac:
I have an USB devices compatible (on linux it work with no problem)
lsusb give this output:
`Bus 020 Device 025: ID 1915:0102 Nordic Semiconductor ASA Research Firmware`
(so is detected)
but the latest (2.19) fresh compiled version of Bettercap still having this error:
`[15:07:33] [sys.log] [err] error while running 'hid.recon on': make sure that a nRF24LU1+ based USB dongle is connected and running the rfstorm firmware: usb device 1915:0102 not found`

I've compiled it using go version go1.12 darwin/amd64 after check that libusb was installed (with brew) on a 10.14.3 (Mojave) Os X

I can reproduce the problem simple launching Bettercap with hid.recon on command.
No more significative output using debug

Thanks in advance 
Giorgio

**Comment by evilsocket** [comment]
oh that's very weird, it seems like libusb is not detecting that device ... what does dmesg says when you plug it in?

**Comment by Giorgiofox** [comment]
dmesg on OS X is not friendly, but I've found that:
```
000108.108716 Research Firmware@14500000: IOUSBHostDevice::getDescriptorGated: compliance violation: USB 2.0 9.3.5: device returned more than wLength data
000108.626520 IOUSBHostDevice@14500000: IOUSBHostDevice::getDescriptorGated: compliance violation: USB 2.0 9.3.5: device returned more than wLength data
000108.629132 Research Firmware@14500000: IOUSBHostDevice::getDescriptorGated: compliance violation: USB 2.0 9.3.5: device returned more than wLength data
HID Activity Tickle (type:0 sender:100000373
```

**Comment by evilsocket** [comment]
mmm not promising, seems more an OS related issue rather than a bettercap's bug :/ not sure how to help here ... seems related to https://github.com/BastilleResearch/mousejack/issues/2

**Comment by IppSec** [comment]
I just had this issue.  Fixed it by installing the project @evilsocket linked (BastilleResearch/mousejack). 

The make install script appears to have flashed my device with an expected version.  Prior to doing this, I had manually flashed my CrazyRadio with the latest firmware with no luck.  It should also be noted prior to installing the Bastille software the light on my CrazyRadio did not stay lit.

**Comment by mlinton** [comment]
> I just had this issue. Fixed it by installing the project @evilsocket linked (BastilleResearch/mousejack).
> 
> The make install script appears to have flashed my device with an expected version. Prior to doing this, I had manually flashed my CrazyRadio with the latest firmware with no luck. It should also be noted prior to installing the Bastille software the light on my CrazyRadio did not stay lit.

Can you elaborate on the fix for this?  I just tried my CrazyRadio PA dongle with a linux VM and it worked as expected, but on OSX, it is not detected.
