### ISSUE TITLE
Bettercap crash with unknown error

### ISSUE THREAD

**Issue by vasiliyph** [bettercap/bettercap#499]
* Bettercap version: 2.18
* OS version and architecture: Ubuntu 18.04 x64 
* Go version if building from sources: 1.11
* Command line arguments you are using: sudo bettercap -caplet /home/mitm6.cap -cpu-profile /home/cpu.txt -mem-profile /home/mem.txt

Caplet code:

```
set http.proxy.script inject.js
set https.proxy.script inject.js

set https.proxy.certificate ca.pem
set https.proxy.key key.pem

http.proxy on
https.proxy on

sleep 1

arp.spoof on
```

inject.js code:

```
function onResponse(req, res) {
	var reqJsPath = req.Path;
	if (reqJsPath.replace(/\?.*/, "").match(/\.js$/i)){
		log( "js extension exist");

		var body = res.ReadBody();
		res.Body = body + "console.log('log js verification')";
	}
}
```

Launched the system. The number of requests for proxying is 7-10 requests per second. Sites http and https (mostly https).
After 10 minutes, session crashed and i saw errors (attach 3 logs files, because it happens regularly several times a day):
[log2.txt](https://github.com/bettercap/bettercap/files/2976538/log2.txt)
[log3.txt](https://github.com/bettercap/bettercap/files/2976539/log3.txt)
[log4.txt](https://github.com/bettercap/bettercap/files/2976540/log4.txt)

The cpu and mem log can not be applied, because bettercap session crashed .

**Comment by evilsocket** [comment]
i need the full logs, not just the crash

**Comment by vasiliyph** [comment]
How get full log? Run as -debug or what?
Because crash occurs, the cpu and mem dump is not saved :(

**Comment by evilsocket** [comment]
just paste the entire output, not only the crash ... i don't care about cpu and memory profile files.

**Comment by vasiliyph** [comment]
This is the entire output log in the terminal. Maybe there is an opportunity to make it longer (because many lines are stupidly overwritten, as you can see from the output), so that I can throw it all off. But if such a crash occurs (I just don’t monitor the bettercap session at the moment), then this is all that is displayed in the putty terminal.

**Comment by evilsocket** [comment]
the log is incomplete and some of the crashe stack traces too, i can't help you without the info i need.

**Comment by vasiliyph** [comment]
Attach full stack traces. User zip, because log big for github. Thanks.
[crash_logs.zip](https://github.com/bettercap/bettercap/files/2999724/crash_logs.zip)

**Comment by evilsocket** [comment]
how much memory has the computer running this? and on how many clients you're doing this?

**Comment by vasiliyph** [comment]
1 vCPU, 1GB RAM, ~700 users (but spoof not all request...clients connect to DNS server, DNS server forward request to bettercap proxy, we touch not all user domains)

**Comment by evilsocket** [comment]
i'ma afraid you'll need better hardware for that amount of users, if you check the logs, it's a simple out of memory error.

**Comment by vasiliyph** [comment]
Increased server capacity, let's see how it will be now.
Found another problem / error:
After a while, the bettercap session simply stops (with message "Killed", without any errors or warnings.
I apply the full output log (this error is not the first time, therefore 2 log files)
[killed_logs.zip](https://github.com/bettercap/bettercap/files/3002032/killed_logs.zip)

**Comment by evilsocket** [comment]
it still sounds like resource problems, what dmesg has to say about it?

**Comment by vasiliyph** [comment]
When crashed again - i will dmesg and attach.
But now and so powerful server, 4 vCPU and 4 GB RAM.
