### ISSUE TITLE
wifi.handshakes.file parameter can be changed while wifi.recon is on but is not update when actually saving the file

### ISSUE THREAD

**Issue by nigga-plz** [bettercap/bettercap#502]
I am capturing PMKIDs and handshakes of different networks and I wanted to have a pcap file for each BSSID. So i used the parameter "wifi.handshakes.file" to set the output file. However, I noticed that the parameter is updated but the new value is not used if it is changed, with "set wifi.handshakes.file <filename>", while wifi.recon is on. To actually change the output file I have to first stop the wifi.recon, then change the parameter, then restart the wifi.recon.

### Environment

* Bettercap version `v2.19 (built for linux amd64 with go1.11.5)`
* `Linux kali 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux`
* bettercap -iface wlan0 (running as root)

### Steps to Reproduce

1. Run bettercap with the specified interface:
  `bettercap -iface wlan0` 
2. Set the handshake capture file
   `set wifi.handshakes.file pmkid_1.pcap` 
3. Start the wifi.recon module
   `wifi.recon on`
4. As soon as you find the target access point, run the assoc and succesfully save the capture to pmkid_1.pcap
   `wifi.assoc <BSSID 1>`
5. Change the capture file to a new one while wifi.recon is still on
   `set wifi.handshakes.file pmkid_2.pcap` 
6. Verify the capture file parameter
   `get wifi.handshakes.file` 
```
wlan0  » set wifi.handshakes.file pmkid_2.pcap
wlan0  » get wifi.handshakes.file 

  wifi.handshakes.file: 'pmkid_2.pcap'
```

7. run assoc against another AP
   `wifi.assoc <BSSID 2>`
8. Capture file is saved to the file `pmkid_1.pcap` 

**Expected behavior:** the output file should be either updated and saved correctly also when wifi.recon is on or print a warning when updating the parameter while wifi.recon is on and print the correct value when getting the parameter with `get wifi.handshakes.file` .

**Actual behavior:** the parameter is correctly updated while issuing the set command but the new value is not actually used when saving the file

**Comment by evilsocket** [comment]
this is the default behaviour, you need to either set the parameter before the module is started, or restart the module to apply the changes.

**Comment by nigga-plz** [comment]
Perfect, thank you. It simply wasn't clear to me.
