### ISSUE TITLE
automate !COMMAND parameters and variables

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#510]
Hello,
I'm using Bettercap 2.19 and trying to automate some network scan:
My idea is to start a Nmap scan for every IP address discovered, so:

```
net.recon on
events.on endpoint.new !COMMAND nmap {{ip}}
```

(the command will be more complex, this is only for example)
 
**What I can use for "{{IP}}" variable?** 

Where I can find a list of this variables?

Thanks
Giorgio

**Comment by evilsocket** [comment]
that depends on the event, in case of `endpoint.new` you need to:

`events.on endpoint.new !nmap {{ipv4}}`

**Comment by elig0n** [comment]
I found some valid values for `wifi.ap.new` by grepping `json:` strings in the source distribution, especially those found at `modules/wifi/wifi_events.go`  and from the [JSON response examples](https://www.bettercap.org/modules/core/api.rest/) but not all are valid for the different events (even of the same "class"). I had no success at all with i.e. `wifi.client.probe`. Some coherent documentation can help around here
