### ISSUE TITLE
Is it possible to write the output of *.show to a file? (feature request)

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#511]
I'm using Bettercap 2.19 on OS X and Linux and Docker :)

I think can be very useful save the output of *.show command to a file, for example  net.show or net.show.meta  or hid.show or ble.show 
Also after doing several syn.scan for example, will be very useful save data of net.show.meta (maybe also in CSV format) with a command 

<3 Thanks
Giorgio

**Comment by evilsocket** [comment]
no logs, no docker command line, nothing ... what can i say? try with `--privileged`
