### ISSUE TITLE
SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### ISSUE THREAD

**Issue by vasiliyph** [bettercap/bettercap#514]
* Bettercap version: 2.18
* OS version and architecture: Ubuntu 18.04 x64 
* Go version if building from sources: 1.11
* Command line arguments you are using: sudo bettercap -caplet /home/mitm6.cap

Problems with proxy module with certificates in Mozilla. If you generate a certificate, go to the site with this certificate for the first time, then everything is fine. But if you restart the session bettercap, then Mozilla swears at the certificate with an error:
SEC_ERROR_REUSED_ISSUER_AND_SERIAL
I search for this error and found, that need cache certificates and user cached version:
https://github.com/elazarl/goproxy/issues/311
How fix this error? Cache all certificated not good idea too, but maybe found another fix. Thanks.

**Comment by evilsocket** [comment]
as documented in that other issue, this is not a bug in bettercap ... and you're using an outdated version by the way, newer versions cache generated https certificates already.

**Comment by vasiliyph** [comment]
This bug is still there, though bettercap is not to blame.
Mozilla current session profile receives a certificate from the current session bettercap. Then, if restart bettercap, and the Mozilla profile session is not closed, then when sending the request, the error is thrown: SEC_ERROR_REUSED_ISSUER_AND_SERIAL
If you restart the Mozilla, or clear the cache, the certificate is overloaded and starts to work again.
In fact, for the current profile session, the Mozilla caches the serial numbers of certificates, and unless you restart the Mozilla, the certificate serial numbers cache will not be cleared.
Therefore, for greater stability and functionality (there are users who do not close the browser for a very long time, but bettercap session has been restarted), it would not be bad to invent a certificate serial number cache system. So that for example the generated certificate was stored somewhere, or the serial number was always the same.
Is it possible to do this or not?

Screenshots with tests:
![Screenshot_1](https://user-images.githubusercontent.com/22670109/55167373-e8361400-5181-11e9-91ac-f94d1b0dce3e.png)
![Screenshot_2](https://user-images.githubusercontent.com/22670109/55167381-ecfac800-5181-11e9-80d0-f4ed1152eb9f.png)

**Comment by q2dg** [comment]
I have EXACTLY the same problem

**Comment by evilsocket** [comment]
if anyone can pin point exactly why ff is giving that error, i can see if there're any easy workarounds i can push to the code

**Comment by yungtravla** [comment]
It seems that this is caused when the user deletes the bettercap CA cert which remained active in firefox. When a new certificate is generated by bettercap, firefox complains about the existing bettercap CA cert.

I think this can only be solved by going into firefox settings and removing the old bettercap CA certificate.

https://support.mozilla.org/en-US/kb/Certificate-contains-the-same-serial-number-as-another-certificate?redirectlocale=en-US&redirectslug=Certificate+contains+the+same+serial+number+as+another+certificate

> Cause
> 
> Older routers will sometimes improperly regenerate their security certificates instead of keeping the same one for the life of the device. If you have added a permanent security exception for your router, and if this regeneration is done improperly, Firefox will detect the change as a possible attack.

**Comment by vasiliyph** [comment]
A little bit wrong.
Bettercap root certificate for each SSL domain generates a separate certificate.
A separate certificate for the domain is cached in firefox for the current browser session (recording including the serial number of this separate certificate)
If you restart the bettercap, then a certificate will be generated again for this domain, but with a different serial number.
But firefox made a cache of the past temporary certificate, and when trying to re-sign the request with a new temporary certificate, firefox swears that the serial numbers do not match.
The only fix here is to cache the temporary certificates of the bettercap for the entire time (and not for the current session), or make the generated serial number of the temporary certificate coincide with the previously generated one.

**Comment by vasiliyph** [comment]
problem not fixed and still exist...

**Comment by evilsocket** [comment]
did you delete the certificates generated from the previous bettercap version in order for the new ones to be generated again?

**Comment by vasiliyph** [comment]
In the mitm6.cap file, the root certificate, which is generated using openssl.
In the bettercap itself, I do not delete / change anything, but simply restart it.
In Mozilla, too, I do not delete anything. And in this case, the Mozilla gives an error.
If you restart the Mozilla, after clearing its profile (cache, history), then everything is loaded without any problems.
