### ISSUE TITLE
hid.inject and error sending frame - unexpected response

### ISSUE THREAD

**Issue by flacostec** [bettercap/bettercap#515]
Hello,

I'm getting a bunch of "error sending frame #x of HID command #x: unexpected response 00" when I am trying to inject a ducky payload on a vulnerable Logitech dongle. However, sometimes it works.

Is there a way to troubleshoot this ? Have you experienced that too ?

**Comment by evilsocket** [comment]
yes, it seems related to the rfstorm firmware and the distance from the dongle itself

**Comment by flacostec** [comment]
Is it necessary to sniff more packet before injecting or performing an injection can be done right after the device has been seen ? That would be nice if it could be done automatically.

**Comment by evilsocket** [comment]
As long as the device type has been detected (or not, if you force it via the [hid.force.type](https://www.bettercap.org/modules/hid/#parameters)), you can inject.

If you want to inject automatically, you can use the [events.on](https://www.bettercap.org/modules/core/events.stream/#events-on-tag-commands) command:

    events.on hid.device.new hid.inject {{address}} US /path/to/script.txt

Please read the docs.
