### ISSUE TITLE
Get 404 page not found

### ISSUE THREAD

**Issue by Jaja83Full** [bettercap/bettercap#517]
Hello been speaking to you on twitter about the 404 page not found.

bettercap --version = bettercap v2.21.1 (built for linux amd64 with go1.11.5)

go version = go version go1.11.6 linux/amd64

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.1

BETTERCAP START
```
root@Jaja:~# bettercap -caplet http-ui
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

[15:33:37] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.0.0/24 > 192.168.0.13  » [15:33:37] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.0.0/24 > 192.168.0.13  »  
```
BETTERCAP DEBUG
```
root@Jaja:~# bettercap -debug
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

192.168.0.0/24 > 192.168.0.13  » [15:42:03] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.0.0/24 > 192.168.0.13  » [15:42:03] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp metric 600 
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.13 metric 600
192.168.0.0/24 > 192.168.0.13  » [15:42:03] [sys.log] [dbg] FindGateway(wlan0) line 'default via 192.168.0.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlan0 proto dhcp metric 600 default 192.168.0.1 wlan0]
192.168.0.0/24 > 192.168.0.13  » [15:42:03] [sys.log] [dbg] gateway is 192.168.0.1[c0:05:c2:3f:9c:68]
192.168.0.0/24 > 192.168.0.13  » [15:42:03] [session.started] {session.started 2019-03-28 15:42:03.284805346 +0000 GMT m=+0.099502755 <nil>}
192.168.0.0/24 > 192.168.0.13  » [15:42:03] [mod.started] events.stream
192.168.0.0/24 > 192.168.0.13  »  
```
NETSTAT
```
root@Jaja:~# netstat -an | grep LISTEN
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN     
unix  2      [ ACC ]     STREAM     LISTENING     25739    @/tmp/.ICE-unix/1017
unix  2      [ ACC ]     STREAM     LISTENING     16996    @/tmp/dbus-csCBq8sG
unix  2      [ ACC ]     STREAM     LISTENING     25631    /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     20366    @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     25693    @/tmp/.X11-unix/X1
unix  2      [ ACC ]     STREAM     LISTENING     16992    @/tmp/dbus-VqpBnvoJ
unix  2      [ ACC ]     STREAM     LISTENING     25637    /run/user/0/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     16993    @/tmp/dbus-yhXslgn8
unix  2      [ ACC ]     STREAM     LISTENING     25640    /run/user/0/bus
unix  2      [ ACC ]     STREAM     LISTENING     25642    /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     25674    @/tmp/dbus-RMewA1nA
unix  2      [ ACC ]     STREAM     LISTENING     25644    /run/user/0/pulse/native
unix  2      [ ACC ]     STREAM     LISTENING     25647    /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     25649    /run/user/0/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     306      /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     25651    /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     27280    @/dbus-vfs-daemon/socket-dIa4supC
unix  2      [ ACC ]     STREAM     LISTENING     318      /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     20422    @/tmp/.ICE-unix/660
unix  2      [ ACC ]     STREAM     LISTENING     334      /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     LISTENING     341      /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     16995    @/tmp/dbus-rUPG3fmw
unix  2      [ ACC ]     SEQPACKET  LISTENING     361      /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     23306    @/tmp/dbus-B1EKyIZ8r4
unix  2      [ ACC ]     STREAM     LISTENING     16249    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     16253    /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     16257    /var/run/pcscd/pcscd.comm
unix  2      [ ACC ]     STREAM     LISTENING     20367    /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     20423    /tmp/.ICE-unix/660
unix  2      [ ACC ]     STREAM     LISTENING     20404    @/tmp/dbus-VrFnHVD0D3
unix  2      [ ACC ]     STREAM     LISTENING     77452    /run/user/0/speech-dispatcher/speechd.sock
unix  2      [ ACC ]     STREAM     LISTENING     19092    /var/run/irqbalance554.sock
unix  2      [ ACC ]     STREAM     LISTENING     25258    /run/user/0/keyring/control
unix  2      [ ACC ]     STREAM     LISTENING     25776    /run/user/0/keyring/ssh
unix  2      [ ACC ]     STREAM     LISTENING     25778    /run/user/0/keyring/pkcs11
unix  2      [ ACC ]     STREAM     LISTENING     21696    /run/user/135/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     22467    /run/NetworkManager/private-dhcp
unix  2      [ ACC ]     STREAM     LISTENING     21702    /run/user/135/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     21705    /run/user/135/pulse/native
unix  2      [ ACC ]     STREAM     LISTENING     21708    /run/user/135/bus
unix  2      [ ACC ]     STREAM     LISTENING     21710    /run/user/135/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     21712    /run/user/135/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     25694    /tmp/.X11-unix/X1
unix  2      [ ACC ]     STREAM     LISTENING     21714    /run/user/135/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     21716    /run/user/135/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     25724    /tmp/ssh-mjyXq9F3vYXl/agent.1017
unix  2      [ ACC ]     STREAM     LISTENING     25740    /tmp/.ICE-unix/1017
unix  2      [ ACC ]     STREAM     LISTENING     25675    @/tmp/dbus-BrKuH829
```
Sorry for taking up your time and massive thank you for being so helpful

Jamie P

**Comment by Jaja83Full** [comment]
Not sure if that this helps but after i run 

root@Jaja:~# bettercap -caplet http-ui
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

[15:33:37] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.0.0/24 > 192.168.0.13 » [15:33:37] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.0.0/24 > 192.168.0.13 »

i type help i get ui  not running in modules

Modules

      any.proxy > not running
       api.rest > running
      arp.spoof > not running
      ble.recon > not running
        caplets > not running
    dhcp6.spoof > not running
      dns.spoof > not running
  events.stream > running
            gps > not running
            hid > not running
     http.proxy > not running
    http.server > running
    https.proxy > not running
   https.server > not running
    mac.changer > not running
   mysql.server > not running
      net.probe > not running
      net.recon > not running
      net.sniff > not running
   packet.proxy > not running
       syn.scan > not running
      tcp.proxy > not running
         ticker > not running
             ui > not running
         update > not running
           wifi > not running
            wol > not running

**Comment by yungtravla** [comment]
`ui` module is set to `running` when it is updating, the `http.server` module actually serves the ui.

So what's the exact issue here, you visit http://127.0.0.1:80 and you are not prompted with a login screen?

**Comment by yungtravla** [comment]
those debug logs don't help, you need to show debug logs while the ui is running: 
`bettercap -caplet http-ui -debug`

**Comment by Jaja83Full** [comment]
hi yungtravla  , i dont get a login screen i get a  404 page not not found. i was speaking to @evilsocket twitter account. sorry about the debug being wrong , hopw this is better.

root@Jaja:~# bettercap -caplet http-ui -debug
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

[01:05:42] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[01:05:42] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp metric 600 
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.13 metric 600
[01:05:42] [sys.log] [dbg] FindGateway(wlan0) line 'default via 192.168.0.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlan0 proto dhcp metric 600 default 192.168.0.1 wlan0]
[01:05:42] [sys.log] [dbg] gateway is 192.168.0.1[c0:05:c2:3f:9c:68]
[01:05:42] [session.started] {session.started 2019-03-29 01:05:42.335292535 +0000 GMT m=+0.088737874 <nil>}
[01:05:42] [mod.started] events.stream
[01:05:42] [mod.started] api.rest
[01:05:42] [mod.started] http.server
192.168.0.0/24 > 192.168.0.13  » [01:05:42] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
panic: listen tcp 127.0.0.1:8081: bind: address already in use

goroutine 98 [running]:
github.com/bettercap/bettercap/modules/api_rest.(*RestAPI).Start.func1()
	github.com/bettercap/bettercap/modules/api_rest/api_rest.go:224 +0x22f
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
	github.com/bettercap/bettercap/session/module.go:252 +0x1bc

**Comment by yungtravla** [comment]
in the last output you gave us it clearly says ` panic: listen tcp 127.0.0.1:8081: bind: address already in use` which means that you are already listening on that port... try a different one

**Comment by yungtravla** [comment]
if that does not solve your problem then you need to give us clear, step by step instructions on how to reproduce this issue

**Comment by Jaja83Full** [comment]
im sorry i had run bettercap -caplet http-ui on 1 terminal and run the bettercap -caplet http-ui -debug on another teminal , this what i get if i just run it on its own.

root@Jaja:~# bettercap -caplet http-ui -debug
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

[03:31:14] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[03:31:14] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp metric 600 
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.13 metric 600
[03:31:14] [sys.log] [dbg] FindGateway(wlan0) line 'default via 192.168.0.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlan0 proto dhcp metric 600 default 192.168.0.1 wlan0]
[03:31:14] [sys.log] [dbg] gateway is 192.168.0.1[c0:05:c2:3f:9c:68]
[03:31:14] [session.started] {session.started 2019-03-29 03:31:14.95693646 +0000 GMT m=+0.075462452 <nil>}
[03:31:14] [mod.started] events.stream
[03:31:14] [mod.started] api.rest
[03:31:14] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
[03:31:14] [mod.started] http.server
192.168.0.0/24 > 192.168.0.13  » [03:31:14] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.0.0/24 > 192.168.0.13  »  

i install bettercap with
apt-get install bettercap
i then updated bettercap with
apt get upgrade bettercap

i downloaded the bettercap ui zip file
then made a dir
mkdir -p /usr/local/share/bettercap
unzipped
unzip ui.zip -d /usr/local/share/bettercap/
then done
bettercap -eval "update.check on; caplets.update; q"
then 
bettercap -caplet http-ui -autostart

when i go to browser to the 127.0.0.1 i get 404 page not found

i really appreciate you taking the time to help me means alot massive preps to you.

**Comment by yungtravla** [comment]
Have you tried just doing `ui.update` before loading the http-ui caplet?

**Comment by Jaja83Full** [comment]
hi thanks again for taking your time helping me trying to resolve this 

yeah i done this 

192.168.0.0/24 > 192.168.0.13  » ui.update 
[05:47:32] [sys.log] [inf] ui checking latest stable release ...
[05:47:33] [sys.log] [inf] ui downloading ui v1.1.0 from https://github.com/bettercap/ui/releases/download/v1.1.0/ui.zip ...
[05:47:35] [sys.log] [war] ui removing previously installed UI from /usr/local/share/bettercap/ui ...
[05:47:35] [sys.log] [inf] ui installing to /usr/local/share/bettercap/ui ...
[05:47:36] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
192.168.0.0/24 > 192.168.0.13  » ui.version 
192.168.0.0/24 > 192.168.0.13  » [05:47:43] [sys.log] [inf] ui v1.1.0
192.168.0.0/24 > 192.168.0.13  »

**Comment by Jaja83Full** [comment]
![Screenshot from 2019-03-29 05-50-09](https://user-images.githubusercontent.com/49035370/55212152-97a4d200-51e6-11e9-837d-182d8d55e043.png)

this what i get in the browser

**Comment by Jaja83Full** [comment]
hmmm when i run it outside i get this 

root@Jaja:/# bettercap -caplet ui.update
bettercap v2.21.1 (built for linux amd64 with go1.11.5) [type 'help' for a list of commands]

[06:08:21] [sys.log] [err] error while running caplet ui.update: caplet ui.update.cap not found
192.168.0.0/24 > 192.168.0.13  »

**Comment by yungtravla** [comment]
In your screenshot it shows that you receive the standard 404 `not found` response from golang's HTTP server, although bettercap does not seem to print any errors.

Can you please make sure that `/usr/local/share/bettercap/ui/` directory exists and is extracted correctly? See below.

![Screenshot from 2019-03-29 19-34-38](https://user-images.githubusercontent.com/29265684/55223406-dc1d8580-5259-11e9-8b5e-0d0facf2d95c.png)

**Comment by Jaja83Full** [comment]
yeah i have it their 
![Screenshot from 2019-03-29 11-56-38](https://user-images.githubusercontent.com/49035370/55231206-d43df100-5219-11e9-8fd1-bfe135973ab4.png)

where should my golang be , random question

**Comment by yungtravla** [comment]
Your $GOPATH environment variable is determined by where you installed golang. By default this is at $HOME

Can you please show us the output of:

`cat /usr/local/share/bettercap/caplets/http-ui.cap`.

**Comment by Jaja83Full** [comment]
dont have :/
root@Jaja:/usr/local/share/bettercap/ui# cat /usr/local/share/bettercap/caplets/http-ui.cap
cat: /usr/local/share/bettercap/caplets/http-ui.cap: No such file or directory

**Comment by Jaja83Full** [comment]
YOU ARE GREAT MAN THANK YOU THINK WE GOT IT.

Kali apt-get install bettercap installs bettercap to the /usr/share/bettercap/
i moved the ui  from usr/local/share/bettercap/ui to usr/share/bettercap/ui now im getting this :D whats the default user and password

![Screenshot from 2019-03-29 12-54-49](https://user-images.githubusercontent.com/49035370/55233988-ffc4d980-5221-11e9-9bbc-1200bd7e04cd.png)

**Comment by Jaja83Full** [comment]
I FUCKING LOVE YOU
THANK YOU SO MUCH FOR TAKING YOUR TIME TO HELP MASSIVE RESPECT 
![Screenshot from 2019-03-29 13-14-59](https://user-images.githubusercontent.com/49035370/55235193-dc4f5e00-5224-11e9-8adc-9a72bfa3f829.png)

**Comment by evilsocket** [comment]
@yungtravla i will make a statue of you some day

**Comment by yungtravla** [comment]
:laughing: someone's excited about the new ui

**Comment by joker2a** [comment]
> YOU ARE GREAT MAN THANK YOU THINK WE GOT IT.
> 
> Kali apt-get install bettercap installs bettercap to the /usr/share/bettercap/
> i moved the ui from usr/local/share/bettercap/ui to usr/share/bettercap/ui now im getting this :D whats the default user and password
> 
> ![Screenshot from 2019-03-29 12-54-49](https://user-images.githubusercontent.com/49035370/55233988-ffc4d980-5221-11e9-9bbc-1200bd7e04cd.png)

Big thanks !!!!!

**Comment by sybind** [comment]
No need to copy the files, just make a symlink `cd /usr/share/bettercap/ && ln -s /usr/local/share/bettercap/ui ui`

**Comment by xxxcrow** [comment]
> No need to copy the files, just make a symlink `cd /usr/share/bettercap/ && ln -s /usr/local/share/bettercap/ui ui`

good way, but more logical just to create config file https-ui.cap
there's a string "set https.server.path"

-----------------------------------------
and here's my problem 😅
can't connect to rest api when logging in
if to go to the ip:port of rest api, browser shows 405 error
thank you, hope for answer 🤗
(and also, how to correctly set up the certificate, if anybody can aswer easy,it would be nice 😄)

**Comment by Ondrik8** [comment]
(((((

This client requires at least API v2.24 but http://127.0.0.1:8081/api is at v2.23 

![Screenshot_1](https://user-images.githubusercontent.com/34920852/59855986-b0083100-937e-11e9-9509-6c320d649ba2.png)

**Comment by Ondrik8** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/34920852/59856076-da59ee80-937e-11e9-88a3-a2e84bab823a.png)

**Comment by evilsocket** [comment]
@Ondrik8 the error message is clear: you need to use the latest version, 2.23 is one version old.

**Comment by Ondrik8** [comment]
i am use:

caplets.update 
ui.update
git pull  


it turns out to reinstall everything again?))

**Comment by Ondrik8** [comment]
) yes re installation helped) thanks!

**Comment by fat-tire** [comment]
2019.3 (rolling) kali on raspberry pi.  I'd `apt install bettercap` but no web ui.  Figured it was a `/usr/share` vs `/usr/local/share` thing so...

Symlinking the directory, ie--

      ln -s /usr/share/bettercap /usr/local/share/bettercap

Didn't help because, whoops, there is no `/ui` directory in there.  There was a /www in there.  Maybe it got renamed or something.  So I tried changing it--

     set https.server.path /usr/share/bettercap/caplets/www

Doh.  that sends you to a [broken](https://github.com/bettercap/caplets/blob/master/www/index.html) [rickroll](https://www.youtube.com/embed/oHg5SJYRHA0).

It took a sec to realize I was missing

     sudo apt install bettercap-ui

And now all is good.

**Comment by macflyhub** [comment]
So much messing around... and the solution was..

 sudo apt install bettercap-ui

Thank you [clap] [party]

**Comment by jeansamarani** [comment]
I tried to follow the steps as mentioned above and I installed the bettercap ui package. However, I am not getting anymore the 404 error but a blank page. Any idea what could be wrong? 

This is the content of the folder ui: 

root@kali:/usr/share/bettercap/ui# ls
app  assets  browserslist  environments  favicon.ico  index.html  karma.conf.js  main.ts  partials  polyfills.ts  styles.scss  test.ts  tsconfig.app.json  tslint.json

root@kali:/usr/share/bettercap/caplets# sudo bettercap -caplet http-ui
bettercap v2.27 (built for linux amd64 with go1.14.1) [type 'help' for a list of commands]

10.0.2.0/24 > 10.0.2.15  » [17:26:27] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
10.0.2.0/24 > 10.0.2.15  » [17:26:27] [sys.log] [inf] **http.server starting on http://127.0.0.1:8089**
10.0.2.0/24 > 10.0.2.15  » help

I can see that the http server is running on port 8089 as I have configured.
     

Modules      
       api.rest > running
      
  events.stream > running

    http.server > running
    
root@kali:/usr/share/bettercap/caplets# cat http-ui.cap 
# api listening on http://127.0.0.1:8081/ and ui to http://127.0.0.1
set api.rest.address 127.0.0.1
set api.rest.port 8081
set http.server.address 127.0.0.1
set http.server.port 8089
# default installation path of the ui
set http.server.path /usr/share/bettercap/ui

# !!! CHANGE THESE !!!
set api.rest.username user
set api.rest.password pass

# go!
api.rest on
http.server on


Any help??

**Comment by DarkSkull91** [comment]
> I tried to follow the steps as mentioned above and I installed the bettercap ui package. However, I am not getting anymore the 404 error but a blank page. Any idea what could be wrong?
> 
> This is the content of the folder ui:
> 
> root@kali:/usr/share/bettercap/ui# ls
> app assets browserslist environments favicon.ico index.html karma.conf.js main.ts partials polyfills.ts styles.scss test.ts tsconfig.app.json tslint.json
> 
> root@kali:/usr/share/bettercap/caplets# sudo bettercap -caplet http-ui
> bettercap v2.27 (built for linux amd64 with go1.14.1) [type 'help' for a list of commands]
> 
> 10.0.2.0/24 > 10.0.2.15 » [17:26:27] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
> 10.0.2.0/24 > 10.0.2.15 » [17:26:27] [sys.log] [inf] **http.server starting on http://127.0.0.1:8089**
> 10.0.2.0/24 > 10.0.2.15 » help
> 
> I can see that the http server is running on port 8089 as I have configured.
> 
> Modules
> api.rest > running
> 
> events.stream > running
> 
> ```
> http.server > running
> ```
> 
> root@kali:/usr/share/bettercap/caplets# cat http-ui.cap
> # api listening on http://127.0.0.1:8081/ and ui to http://127.0.0.1
> 
> set api.rest.address 127.0.0.1
> set api.rest.port 8081
> set http.server.address 127.0.0.1
> set http.server.port 8089
> # default installation path of the ui
> 
> set http.server.path /usr/share/bettercap/ui
> # !!! CHANGE THESE !!!
> 
> set api.rest.username user
> set api.rest.password pass
> # go!
> 
> api.rest on
> http.server on
> 
> Any help??

I also have your problem. Did you resolve?

**Comment by azamet90** [comment]
> I tried to follow the steps as mentioned above and I installed the bettercap ui package. However, I am not getting anymore the 404 error but a blank page. Any idea what could be wrong?
> 
> This is the content of the folder ui:
> 
> root@kali:/usr/share/bettercap/ui# ls
> app assets browserslist environments favicon.ico index.html karma.conf.js main.ts partials polyfills.ts styles.scss test.ts tsconfig.app.json tslint.json
> 
> root@kali:/usr/share/bettercap/caplets# sudo bettercap -caplet http-ui
> bettercap v2.27 (built for linux amd64 with go1.14.1) [type 'help' for a list of commands]
> 
> 10.0.2.0/24 > 10.0.2.15 » [17:26:27] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
> 10.0.2.0/24 > 10.0.2.15 » [17:26:27] [sys.log] [inf] **http.server starting on http://127.0.0.1:8089**
> 10.0.2.0/24 > 10.0.2.15 » help
> 
> I can see that the http server is running on port 8089 as I have configured.
> 
> Modules
> api.rest > running
> 
> events.stream > running
> 
> ```
> http.server > running
> ```
> 
> root@kali:/usr/share/bettercap/caplets# cat http-ui.cap
> # api listening on http://127.0.0.1:8081/ and ui to http://127.0.0.1
> 
> set api.rest.address 127.0.0.1
> set api.rest.port 8081
> set http.server.address 127.0.0.1
> set http.server.port 8089
> # default installation path of the ui
> 
> set http.server.path /usr/share/bettercap/ui
> # !!! CHANGE THESE !!!
> 
> set api.rest.username user
> set api.rest.password pass
> # go!
> 
> api.rest on
> http.server on
> 
> Any help??

same problem i do have did u solve this problem?

**Comment by ConsultanIT** [comment]
Hi team 

how I can downgrade bettercap from the last version to version 2.23

best regards

**Comment by buffermet** [comment]
@ConsultanIT You can look on the [releases](https://github.com/bettercap/bettercap/releases) page, or you can clone a older version of the repo.

A quick search on Google would have given you this information, please don't abuse the issue tracker.

**Comment by richardwesthaver** [comment]
in case anyone is having issues on ArchLinux - 404 is avoided by moving the default ui location to /usr/share/betterment/ui or copying that directory to /usr/local/share/betterment/ui. Tested on most recent build from Pacman

**Comment by fuomag9** [comment]
> in case anyone is having issues on ArchLinux - 404 is avoided by setting the default ui location to /usr/share/betterment/ui or copying that directory to /usr/local/share/betterment/ui. Tested on most recent build from Pacman

This is what worked for me
`sudo ln -s /usr/share/bettercap/ /usr/local/share/bettercap`
