### ISSUE TITLE
[Feature Request] add support to choose HCI device for BLE

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#519]
Hello,

I think that choose the bluetooth device to use for ble.recon can be very useful: for example I have the internal bluetooth device as HCI0 and an external dongle as HCI1 that is better and more performing. 

Bettercap seem using only HCI0. Actually I can use `rfkill` command to block the HCI0 device and permit Bettercap to use che HCI1

Maybe adding the option -hci so `sudo Bettercap -hci hci1`

I'm using Bettercap 2.21.1 on Kali Linux compiled with Go1.11.5

Thank you
Giorgio

**Comment by evilsocket** [comment]
pushed to master, `set ble.device 1; ble.recon on`

**Comment by hitchcme** [comment]
5.15.44-Re4son-v7+ armv7l
bettercap v2.32.0 (built for linux arm with go1.19.2)
bettercap -debug
set ble.device 1; ble.recon on
    finds two devices, but defaults to hci0
    does same regardless of the manual setting, as if 1) the value isn't actually being used or 2.) it isn't actually changing
        even though 'get ble.device' reflects the change.

Changing the "-1" at line 10 in 
   "${ROOT}/modules/ble/ble_options_linux.go"
      to be the wanted interface index "works"...
      although the "ble.device" setting still doesn't seem to be used except for display purposes, while the setting in
          ble_options_linux.go seems to be used explicitly.
