### ISSUE TITLE
[android] arp.spoof does not send arp packets to the victim

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#521]
Hi! I needed to run arp.spooff with net.sniff on my device and I failed with it. Arp.the spoof module does not work for me, more specifically - it does not send arp packets to the victim (192.168.1.120). There is no protection against arp spoofing on the router. I also tried on another device and also failed. What is remarkable, on my desktop PC (ubuntu amd64) connected by wire to the router, spoofing works well and I see http and https requests of the victim. But on smartphones, only mdns are visible.
In all cases, the plot was the same: I run bettercap; after a few seconds, I refresh the same page (vk.com) in google chrome on the victim.
I also doubt that the problem is related to the device settings, because I also use [Intercepter-ng for android](https://github.com/intercepter-ng/intercepter-ng.github.io) and there are no problems with it on this device in this network.

### Environment

* Bettercap version you are using ( `bettercap -version` ).
  2.22 (compiled from master) / also tried with 2.21.1
* OS version and architecture you are using.
  Android 6.0.1 arm, Termux 0.66 / also tried on Android 7.1.2 arm, Termux 0.66 (another device)
* Go version if building from sources.
  go1.12.1
* Command line arguments you are using.
`sudo $GOPATH/bin/bettercap -eval "set arp.spoof.targets 192.168.1.120; set net.sniff.filter host 192.168.1.120; arp.spoof on; http.proxy on; net.sniff on" -debug -no-colors | tee android.txt` 
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ):
[android.txt](https://github.com/bettercap/bettercap/files/3024164/android.txt)

Below attached a session entry from ubuntu for comparison.
[ubuntu.txt](https://github.com/bettercap/bettercap/files/3024067/ubuntu.txt)

**Comment by evilsocket** [comment]
did you launch the android one with your flags plus `-debug` ?

**Comment by garlapann** [comment]
Yes, **android.txt** was recorded using the command written in the first post. And, Yes, there's a **-debug** option before **-no-colors**.

**Comment by evilsocket** [comment]
did you also try to enable net.recon and net.probe?

**Comment by garlapann** [comment]
yes, i did

**Comment by garlapann** [comment]
Yes, tried again with `net.probe on` and arp packets went, but on the victim the internet was gone. Tried _Intercepter-ng_ and pages were loaded and I saw requests. Then just decided to reboot the victim and the internet appeared, I finally saw http and https requests in bettercap. Two questions: can I enable net.probe with arp.spoof? And why is there no internet on the victim after running the spoofing (seen only with bettercap)?

**Comment by evilsocket** [comment]
try to do this: `net.probe on` and `net.recon on` until `net.show` shows your target, then `net.probe off` and you can `arp.spoof on` ;)

**Comment by garlapann** [comment]
Yeah, that's what I did.)))

**Comment by anudeepreddy** [comment]
any update on this?
