### ISSUE TITLE
DNS Spoof doesn't work at all

### ISSUE THREAD

**Issue by Parshuram2** [bettercap/bettercap#523]
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). 2.21
* OS version and architecture you are using. Kali 2019.1 VirtualBox 
* Go version if building from sources. go 12.1
* Command line arguments you are using. bettercap --iface wlan0
* Caplet code you are using or the interactive session commands. dns.spoof on
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
debug shows no information about DNS Spoof. After the website loads DNS Spoof tries to spoof links inside the page i.e "share" links.
### Steps to Reproduce
DNS Spoof doesn't work at all. set.dns.all true dns.spoof.hosts => 192.168.x.x * set dns.spoof.domains listverse.com ..

**Expected behavior: "Not Secure" sites should redirect

**Actual behavior:** Nothing happens

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
RTFM https://www.bettercap.org/modules/ethernet/spoofers/dns.spoof/
