### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by bestemic** [bettercap/bettercap#525]
I can't download on debian 9 stable bettercap.
I use command go get github.com/bettercap/bettercap and i got some errors.
H github.com/bettercap/bettercap/caplets
.go/src/github.com/bettercap/bettercap/caplets/manager.go:40: undefined: sort.Slice
# github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
.go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:134: undefined: time.Until
.go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:324: undefined: unix.Errno
.go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:337: undefined: unix.Errno

**Comment by yungtravla** [comment]
incomplete report, please use the template
