### ISSUE TITLE
[Feature request] Reachable wifi scan

### ISSUE THREAD

**Issue by aorizondo** [bettercap/bettercap#527]
When I do wifi.recon I can see all the nearby AP's but also the ones that are beyond a reachable distance. Would be nice have a "ping" method that can easily determinate which AP is in my transmition range. In console I do this with `iw dev wlan0 scan` while listen in monitor mode with wireshark, if a "probe response" arrives with my mac as destination then I know that AP is reachable by my adapter.
I'm using bettercap version 2.21.2 on debian testing amd64

**Comment by yungtravla** [comment]
When you do `wifi.show` the signal strength is already indicated in the very first RSSI column, expressed in dBm.
