### ISSUE TITLE
Hello have a question of dns 

### ISSUE THREAD

**Issue by l0ltesti** [bettercap/bettercap#528]
Hello sir
i have a question of dns spoofing 
well if i want all domain > redirect 1.2.3.4
and if i want blah.blah.com/ilos/main/main_form.acl > redirect 1.2.3.4
please example host.conf file 
thank you

**Comment by yungtravla** [comment]
RTFM https://www.bettercap.org/modules/ethernet/spoofers/dns.spoof/
