### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by N2Network** [bettercap/bettercap#529]
Trying to figure out the best approach to logging/replay.  First is it possible to plot access points, clients, beacon probes, on the map? Second, what is the best method for logging these items for later but based on geographical location? Any sample code would be great so I could work on modifying.

**Comment by yungtravla** [comment]
Yes, it's possible and described here: https://github.com/bettercap/bettercap/issues/455

It may be worth to have a builtin parser that maps it for you, but you can always do it manually or use your own parser.

As for sorting by geolocation, you simply have to sort by coordinates.

**Comment by N2Network** [comment]
> Yes, it's possible and described here: #455
> 
> It may be worth to have a builtin parser that maps it for you, but you can always do it manually or use your own parser.
> 
> As for sorting by geolocation, you simply have to sort by coordinates.

Thanks, I was searching for logging and not GPS.
