### ISSUE TITLE
deauth all stopped working

### ISSUE THREAD

**Issue by N2Network** [bettercap/bettercap#531]
I'm not sure what happened. I was running this command before and it would deauth all clients

wifi.deauth ff:ff:ff:ff:ff:ff
OR 
wifi.deauth * 
OR 
wifi.deauth all

All of a sudden it started only deauth one client then it stops.

**Comment by evilsocket** [comment]
OMFG do you understand you need to attach debug logs or not? i can't help you like this

incomplete report
