### ISSUE TITLE
When running the deauth command all the access points starts to disappear and it locks to one channel

### ISSUE THREAD

**Issue by N2Network** [bettercap/bettercap#532]
events.on wifi.client.new wifi.deauth {{Client/mac}}
events.on wifi.ap.new wifi.assoc {{mac}}
set ticker.period 20; set ticker.commands "wifi.deauth ff:ff:ff:ff:ff:ff"; ticker on

I'm running the following commands and I'm noticing two weird issues. The first is I used to be able to run wifi.deauth * and it would start deauth on tons of networks. Now when I run it the command only invokes against one ap and then just stops. 

The second issue I'm noticing is after running these commands and coming back in 5 minutes my network adapter is locked on one channel typically 1 or 44. I know it's locked because I can only see AP's clients on that one channel in my list I also can only see about 15 AP's as to normally I can see around 110.

**Comment by evilsocket** [comment]
incomplete report

**Comment by hugoyepezcrow** [comment]
Hello
I was running the example in a laptop with Kali Linux in your page (https://www.bettercap.org/modules/wifi/) 
Examples

Run bettercap using eth0 as the main interface but start the wifi module on wlan0 instead:

sudo bettercap -iface eth0 -eval "set wifi.interface wlan0; wifi.recon on"
Keep deauthing clients from the access point with BSSID DE:AD:BE:EF:DE:AD every five seconds:

> set ticker.period 5; set ticker.commands "wifi.deauth DE:AD:BE:EF:DE:AD"; ticker on
Use the ticker and wifi.recon modules to create a WiFi scanner (performing channel hopping on every supported frequency):

> set ticker.commands "clear; wifi.show"; wifi.recon on; ticker on
Sort by BSSID and filter for BSSIDs starting with F4:

> set wifi.show.sort bssid asc
> set wifi.show.filter ^F4
> wifi.show
Only recon on channels 1, 2 and 3:

> wifi.recon.channel 1,2,3; wifi.recon on
Will send management beacons as the fake access point “Banana” with BSSID DE:AD:BE:EF:DE:AD on channel 5 without encryption:

> set wifi.ap.ssid Banana
> set wifi.ap.bssid DE:AD:BE:EF:DE:AD
> set wifi.ap.channel 5
> set wifi.ap.encryption false
> wifi.recon on; wifi.ap

When I try to connect to Access Point created, the computer or any device can not connect to AP. I can see de BSSID but not connect.

Can you help me with this problem or maybe I could improve de code. Let me know if you need more information about my specific problem.

Best regards

Hugo
