### ISSUE TITLE
dns.spoof doesn't do its job in a consistent and permanent manner

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#534]
Hello.
 I'm using last Bettercap's version (2.22) on a Ubuntu 18.04 machine and I've done this:

_set arp.spoof.targets x.x.x.x
arp.spoof on
set dns.spoof.domains *.marca.com,marca.com
dns.spoof on_

"Victim"'s machine (with x.x.x.x IP) is another Ubuntu 18.04 which runs systemd-resolve. So I've done _systemd-resolve --flush-cache_ to flush its DNS cache but when I do _dig www.marca.com_ there, I still get real name resolution. If I repeat executing  _systemd-resolve --flush-cache_ A LOT of times, one time I get fake Bettercap's resolution but when I try to navigate with browser,  real name resolution turns again, so I must repeat executing  _systemd-resolve --flush-cache_ A LOT of times to get another fake Bettercap response. It seems dns.spoof works very randomly (and during a little time).

Thanks.

PD: I've seen a lot of closed issues related to this problem or similar. I think it deservers a look

**Comment by q2dg** [comment]
Sorry, I forgot we have an internal DNS server on our land. Setting set arp.spoof.internal true solves these inconsistencies. Thanks and sorry

**Comment by q2dg** [comment]
Well, it was a mirage. The erratic behaviour remains

**Comment by evilsocket** [comment]
it seems to me that what's working randomly here is systemd's DNS cache invalidation policy ... if bettercap doesn't receive DNS requests to send spoofed responses to, because systemd is caching them even if you just flushed the cache, there's not a lot i can do ... do you see, bettercap's side, any DNS queries that are not spoofed correctly as you would expect when they happen?

**Comment by evilsocket** [comment]
no feedback in days, closing

**Comment by q2dg** [comment]
Sorry for being late...I was redoing my network lab to further investigate your questions.
And you're right: it seems a fault of systemd-resolved. I've opened this issue in their github: https://github.com/systemd/systemd/issues/12243
