### ISSUE TITLE
Provide a Bettercap's CA certificate to integrate into browser

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#536]
Hello.
When using https.proxy, warning message appear in non-HSTS sites asking for accept custom certificate. Could it be possible to provide a CA certificate related to https.proxy module to integrate inside browser infraestructure to recognize https proxy as a valid interlocutor? Mitmproxy, for instance, does that. 

Thanks!

**Comment by yungtravla** [comment]
You can already serve bettercap's CA certificate with the `http.server` which you can then install on the target devices.

**Comment by q2dg** [comment]
Oh, sorry, I just discovered .bettercap-ca-cert.pem file located inside /root folder. Thanks!

**Comment by JaydenForYou** [comment]
i can't locate these certificate files, can you guys provide them with me?thanks!

**Comment by buffermet** [comment]
@JaydenForYou bettercap will generate these when you start a HTTPS module, for example `https.proxy`.

<img width="709" alt="Screen Shot 2021-04-24 at 3 03 23 pm" src="https://user-images.githubusercontent.com/29265684/115947924-38713300-a50e-11eb-85fb-c789bcc52321.png">

**Comment by ChillVibesMushroom** [comment]
> You can already serve bettercap's CA certificate with the `http.server` which you can then install on the target devices.

Oh yaya, I'm going to look into this I'm taking a coffee break.

**Comment by wonderlili-lab** [comment]
> You can already serve bettercap's CA certificate with the `http.server` which you can then install on the target devices.

Hi all
I have searched all internet but can't find any single tutorial : how do you serve this cert with http.server? is there a specific URL to go to, from the device? 

![Screenshot bettercap](https://user-images.githubusercontent.com/132570610/236192397-df7e5968-70fc-4eb6-a95a-d1063a199172.png)

Going to 192.168.1.188:8080  from the device is generating an error...
`dial tcp 192.168.1.188:8080: socket: too many open files`

Going to 192.168.1.188 from the device is generating an error...
`dial tcp 192.168.1.188: connect: connection refused`
