### ISSUE TITLE
Bettercap breaks very badly if tries to open an already used port (when using http.server or http.proxy modules, for instance)

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#539]
Seen in Bettercap's last version (v2.22) running on Ubuntu 18.04 and Fedora 29: if a port is already in use (80,443,8080,8083...), when launching some Bettercap's modules that use any of them, Bettercap breaks so badly than I must execute "reset" command to get control of shell again. It would be pretty Bettercap warned with an error message and exited gracefully. Thanks.

**Comment by yungtravla** [comment]
```
 ~ » py3 -m http.server & bettercap -eval "set http.server.port 8000; http.server on"
[1] 6291
bettercap v2.23 (built for linux amd64 with go1.11.6) [type 'help' for a list of commands]

Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
[12:31:01] [sys.log] [inf] http.server starting on http://192.168.1.95:8000
[12:31:01] [sys.log] [err] http.server listen tcp 192.168.1.95:8000: bind: address already in use
```

As far as I can tell the error is printed properly and my terminal does not get messed up. It seems the issue is not seen as fatal and therefore only throws an error.

**Comment by q2dg** [comment]
I see...it's strange because it's not what I see in my system. Thanks anyway
