### ISSUE TITLE
Unable to log events in file

### ISSUE THREAD

**Issue by q2dg** [bettercap/bettercap#540]
Seen in Bettercap's last version (v2.22) running on Ubuntu 18.04 and Fedora 29

When executing _bettercap -eval "set events.stream.output ~/events.log"_ , events continue appearing on screen and, when exiting from session, "events.log" isn't created. In other words: this option isn't taken into account.

The same behaviour is seen if the _set events.stream.output ~/events.log_ line is written the first inside a caplet and I run _bettercap -caplet somecaplet.cap_

Thanks

**Comment by yungtravla** [comment]
I cannot reproduce this issue on v2.23

**Comment by q2dg** [comment]
If it helps...
![Captura de pantalla de 2019-04-12 09-53-23](https://user-images.githubusercontent.com/7274874/56021124-f602a200-5d08-11e9-93e5-fe95e693d97b.png)

If not, I'll wait until v2.23
Thanks!

**Comment by infosecgeek** [comment]
Same issue (on Kali)

Example usage: _bettercap -iface eth0 -caple_t local-sniffer.cap -eval "set events.stream.output ~/bettercap-session.log; set events.stream.output.rotate false"_

_active_ shows the correct file location, yet no file is created and events continue printing to screen.

**Comment by evilsocket** [comment]
events.stream is autostarted, meaning the `eval` commands are executed afterwards, meaning you need to stop and restart the module in order for those changes to the configuration to take effect.

**Comment by infosecgeek** [comment]
Perfect! All good now ;) 

Thanks!

**Comment by q2dg** [comment]
Yes, you're right!!!!
Thanks a lot!!!
I'll close the issue, then.
Thanks!
