### ISSUE TITLE
[Bug Report] https.proxy change CORS headers

### ISSUE THREAD

**Issue by cnwangjihe** [bettercap/bettercap#543]
Bettercap v2.22 on Debian 9 amd64  
https.proxy will ignore ```Access-Control-Allow-Credentials: true```, and set ```Access-Control-Allow-Origin``` to *  
And Chrome reports this  
![image](https://s2.ax1x.com/2019/04/17/Az90lF.png)  
normal situation:
![image](https://s2.ax1x.com/2019/04/17/Az9T0A.png)  
using https.proxy:  
![image](https://s2.ax1x.com/2019/04/17/Az96T1.png)

**Comment by Ghastlcon** [comment]
same question.

**Comment by cnwangjihe** [comment]
Thanks a lot

**Comment by rehmanazharpapa** [comment]
bro can you make a litest version for arm v6 plz i am crying
