### ISSUE TITLE
[Feature Request] Save the "*.show" table in some output file

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#544]
Hello, 
I think that can be very useful a command  save in a output file the table of a *.show command, for example "wifi.show": maybe something like "set wifi.show.output wifi.txt" and "wifi.show.write or similar else..
Also saving a CSV can be very very useful.

Thank you!
I'm using Bettercap 2.22 on Kali Linux

**Comment by evilsocket** [comment]
you can copy/paste it, redirect bettercap's output or simply use the rest API ... this feature is redundant.
