### ISSUE TITLE
net.show not capture all ip

### ISSUE THREAD

**Issue by albakry6** [bettercap/bettercap#546]
i have problem with bettercap when i open it and write net.show it gives me my ip and gateway only and it doesnt show me all the ip in the local network example my phone ip 

please anyone have solve for this ?

**Comment by evilsocket** [comment]
did you activate `net.probe` ?

**Comment by albakry6** [comment]
92.168.1.7 │ 48:5d:60:62:46:05 │ wlan0   │ AzureWave Technology Inc.   │ 0 B    │ 0 B   │ 08:32:20 │
│ 192.168.1.1 │ 7c:11:cb:2d:2e:36 │ gateway │ Huawei Technologies Co.,Ltd │ 420 kB │ 82 kB │ 08:32:20 │

yes it give me the same result >> iam using kali linux light and i install bettercap from source of kali linux live as sudo apt-get install bettercap 

is this true install ?

**Comment by yungtravla** [comment]
@albakry6 please fill out a complete issue using the issue template and include debug logs

**Comment by yungtravla** [comment]
and to install from source you should follow the installation guide https://www.bettercap.org/installation/

**Comment by MuhammadShahzeb123** [comment]
You shall first type "net.probe on" Hit enter. Then Type "net.recon on" and Hit Enter. Now you will be able to see all networks

**Comment by sidharthsajith** [comment]
> You shall first type "net.probe on" Hit enter. Then Type "net.recon on" and Hit Enter. Now you will be able to see all networks

still, it is not working for me

**Comment by Dhanushprasana** [comment]
> i have problem with bettercap when i open it and write net.show it gives me my ip and gateway only and it doesnt show me all the ip in the local network example my phone ip
> 
> please anyone have solve for this ?

connect your vm to bridged network

**Comment by BoPann** [comment]
I am having the same problem too. I use kali on  WSL2. Even tho the net.probe and net.recon are both on. All I can see when doing net.show is eth0 and the gateway.

**Comment by filetoolhost** [comment]
> I am having the same problem too. I use kali on WSL2. Even tho the net.probe and net.recon are both on. All I can see when doing net.show is eth0 and the gateway.

me to im using kalo on wsl and the same problem dont show any device i try to do net.probe on but he detect nothing beside my eth0 and gateway i was having bettercap from virtual machine and its was working great but whit wsl in not working

**Comment by Carlloz22** [comment]
Connecting to bridge mode did it for me! Thank you!!

**Comment by KazimFedxD** [comment]
i am on wlan0 but its not working for me\
]
