### ISSUE TITLE
libusb-1.0.dll not found

### ISSUE THREAD

**Issue by lanybass** [bettercap/bettercap#557]
which version of libusb-1.0.dll ?
I've tried many version,but stil not work.
could anybody give a link?

**Comment by yungtravla** [comment]
libusb-`1.0`

**Comment by ScriptTiger** [comment]
If you're using Windows, you need this:
https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z

Whether you're using Cygwin, MinGW, or just directly using the bettercap.exe, just use the MinGW dll for whichever architecture you are, the MinGW32 if you're x86 and MinGW64 if you're x86_64.

I'm assuming Linux users wouldn't ask that question, as you could literally just type it into whatever package manager you're using and it pops right up.

**Comment by lanybass** [comment]
> If you're using Windows, you need this:
> https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z
> 
> Whether you're using Cygwin, MinGW, or just directly using the bettercap.exe, just use the MinGW dll for whichever architecture you are, the MinGW32 if you're x86 and MinGW64 if you're x86_64. Just make sure that's in the same directory as bettercap.exe and you're good to go.
> 
> I'm assuming Linux users wouldn't ask that question, as you could literally just type it into whatever package manager you're using and it pops right up.

it works ,thank you~

**Comment by 4p3rtur3** [comment]
For further information: https://github.com/bettercap/bettercap/issues/482
