### ISSUE TITLE
[Feature Request] configurable endpoint/AP pruning timeout

### ISSUE THREAD

**Issue by mlinton** [bettercap/bettercap#560]
Nodes (net, wifi, hid, ble, etc) all timeout of the table after a set period of time ("lost"), it would be great to have this parameter configurable so that you could keep a full list of all of the detected nodes.

This would be especially helpful when deploying bettercap for a period of time and want to report on all of the radio based nodes (ble, hid, wifi) seen during that time.

**Comment by hugoyepezcrow1** [comment]
Hello,

I want to ask you if Bettercap can create a rogue AP and share internet to the users. Also if the answer is yes can you help me with a example.

Thanks

Hugo

**Comment by yungtravla** [comment]
@hugoyepezcrow1 this is not the right place for your question. To answer your question: no, you will need to set up your own access point of which the traffic you can route through bettercap using your downstream interface.

**Comment by evilsocket** [comment]
so far i've implemented `wifi.ap.ttl` and `wifi.sta.ttl` (in master, still to be released)
