### ISSUE TITLE
bettercap 2.23 cannot be built from source archive

### ISSUE THREAD

**Issue by equal-l2** [bettercap/bettercap#561]
### Environment

Go: `go version go1.12.4 darwin/amd64`
OS: macOS 10.14.4
dep: 
```
dep:
 version     : v0.5.1
 build date  : 2019-03-11
 git hash    : faa6189
 go version  : go1.12
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```

### Steps to Reproduce

1. Download the source from https://github.com/bettercap/bettercap/archive/v2.23.tar.gz
2. Decompress it into `$GOPATH/src/github.com/bettercap/bettercap`
3. Run `dep ensure -vendor-only`
4. Run `go build`

**Expected behavior:** *What you expected to happen*
`go build` runs successfully.

**Actual behavior:** *What actually happened*
`go build` fails with the following error:
```
# github.com/bettercap/bettercap/modules/api_rest
modules/api_rest/api_rest_controller.go:98:30: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
modules/api_rest/api_rest_controller.go:109:23: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
modules/api_rest/api_rest_controller.go:114:55: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
modules/api_rest/api_rest_controller.go:257:29: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
modules/api_rest/api_rest_controller.go:267:22: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
```

-- 

I know this is NOT the officially-prefered way to install bettercap, but it should work for ordinary packages.
I suspect the cause is that the version of `bettercap/recording` is wrongly specified in `Gopkg.lock`. `record.Record.Index()` has introduced in bettercap/recording@1f9c73b but `Gopkg.lock` specifies an older commit bettercap/recording@1396b95.

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by equal-l2** [comment]
This makes https://github.com/Homebrew/homebrew-core/pull/39021 not working.

**Comment by evilsocket** [comment]
> I know this is NOT the officially-prefered way to install bettercap

exactly
