### ISSUE TITLE
bettercap.service is a disabled or a static unit, not starting it.

### ISSUE THREAD

**Issue by DulyHub** [bettercap/bettercap#563]
While installing Bettercap in kali the next message appears:
bettercap.service is a disabled or a static unit, not starting it.

### Environment

Please provide:

*Bettercap version:

bettercap v2.23 (built for linux amd64 with go1.11.6)

*Kali Version:

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.1
Codename:	n/a

* Go version if building from sources.

*Commands:

1144  sudo apt-get install build-essential ruby-dev libcap-dev
1145  apt-get update
1146 apt-get install bettercap

* Caplet code you are using or the interactive session commands.

*Console:

<pre><font color="#EF2929"><b>root@Kali</b></font>:<font color="#729FCF"><b>~</b></font># apt-get install bettercap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  bettercap
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5,869 kB of archives.
After this operation, 23.4 MB of additional disk space will be used.
Selecting previously unselected package bettercap.
(Reading database ... 489993 files and directories currently installed.)
Preparing to unpack .../bettercap_2.23-0kali1_amd64.deb ...
Unpacking bettercap (2.23-0kali1) ...
Setting up bettercap (2.23-0kali1) ...
**bettercap.service is a disabled or a static unit, not starting it.**
</pre>

### Steps to Reproduce

1. Just try to install it and then the message appear

**Expected behavior:** *What you expected to happen*
Install correctly and complete Bettercap cause i dont have it complete.

**Actual behavior:** *What actually happened*

Looks like to be incomplete and when i try to bettercap -t 192.xxx.xxx.xxx -X   nothing happens :/
When i type bettercap -h to see all the modules, etc just appear this few comands:

<pre><font color="#EF2929"><b>root@Kali</b></font>:<font color="#729FCF"><b>~</b></font># bettercap -h
Usage of bettercap:
  -autostart string
    	Comma separated list of modules to auto start. (default &quot;events.stream&quot;)
  -caplet string
    	Read commands from this file and execute them in the interactive session.
  -cpu-profile file
    	Write cpu profile file.
  -debug
    	Print debug messages.
  -env-file string
    	Load environment variables from this file if found, set to empty to disable environment persistence.
  -eval string
    	Run one or more commands separated by ; in the interactive session, used to set variables via command line.
  -gateway-override string
    	Use the provided IP address instead of the default gateway. If not specified or invalid, the default gateway will be used.
  -iface string
    	Network interface to bind to, if empty the default interface will be auto selected.
  -mem-profile file
    	Write memory profile to file.
  -no-colors
    	Disable output color effects.
  -no-history
    	Disable interactive session history file.
  -silent
    	Suppress all logs which are not errors.
  -version
    	Print the version and exit.
</pre>

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
google is your friend https://kali.training/topic/managing-services/

`systemctl enable bettercap`

**Comment by Khurram-Chaudhry** [comment]
┌──(root㉿kali)-[~]
└─# systemctl enable bettercap
Failed to enable unit: Unit file bettercap.service does not exist.

**Comment by evilsocket** [comment]
You need to install the service first, to install a service file in Kali Linux, you need to create a systemd service file and then enable and start it. This involves placing the service file in the `/etc/systemd/system/` directory, reloading the daemon, and then starting the service.

**Comment by Khurram-Chaudhry** [comment]
Thanks.


Khurram Chaudhary
