### ISSUE TITLE
ble.show not show BLE device name

### ISSUE THREAD

**Issue by Giorgiofox** [bettercap/bettercap#565]
Hi,
using **ble.recon on** I can see some device with name, i.e. 
`[ble.device.new] new BLE device BLECTF detected as B4:E6:2D:xx:xx:xx (Espressif Inc.) -63 dBm.
`
where **BLECTF** is the device name, but with **ble.show** the column "name" does not appear anymore.

I'm using bettercap v2.23 (built for linux arm with go1.11.6) on Kali Linux and Arch. 

Thanks in advance
Giorgio

**Comment by Kishaihd** [comment]
I'm having this exact same problem, using bettercap v2.26.1 (built for linux amd64 with go1.13.4) on Arch linux.
