### ISSUE TITLE
DNS Ip problem with SSLstrip

### ISSUE THREAD

**Issue by bobob15** [bettercap/bettercap#568]
Hello ! I just installed Bettercap (V2.24) but I have a problem with DNS during a MITM.
Indeed, for some websites such as Facebook or Instagram, the DNS returns IP 0.0.0.0 while for Twitter for example, it returns its correct IP address.
So I have a message of this type on the "victim's" PC :
"ERR_NAME_NOT_RESOLVED"

Could you help me?

![DNS IP problem](https://user-images.githubusercontent.com/19501429/57366817-1139c380-7188-11e9-80c9-77ee36441424.jpg)

**Comment by yungtravla** [comment]
incomplete report
