### ISSUE TITLE
net.show and net.probe not showing all connected IP

### ISSUE THREAD

**Issue by jepunband** [bettercap/bettercap#573]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
bettercap v2.21.1

* OS version and architecture you are using.
4.19.0-parrot4-28t-amd64

* Go version if building from sources.
-
* Command line arguments you are using.
bettercap

* Caplet code you are using or the interactive session commands.

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. bettercap
2. net.show
3. net probe on

**Expected behavior:** *What you expected to happen*
should show a list of all connected devices not host and gateway only.

**Actual behavior:** *What actually happened*
bettercap is only showing host and gateway Ip, all other connected devices are not shown or captured.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by yungtravla** [comment]
incomplete report
