### ISSUE TITLE
Evilsocket AWUS1900 question

### ISSUE THREAD

**Issue by Dema323** [bettercap/bettercap#575]
Hi @evilsocket  Does you AWUS1900 and the drivers you used work with airgeddon ?
I saw your tutorial on evilsocket.net and me and some other people are having real issues with the AWUS 1900 and the drivers you shared on the page.  Is your AWUS 1900 working with those drivers ? Are you able to use airgeddon ?

**Comment by evilsocket** [comment]
this is not about bettercap, closing
