### ISSUE TITLE
Bettercap not getting target info

### ISSUE THREAD

**Issue by Dema323** [bettercap/bettercap#576]
Please provide:

* Bettercap version you are using ( Latest version).
* OS version and architecture you are using Manjaro 4.19
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce
[https://www.evilsocket.net/2019/02/13/Pwning-WiFi-networks-with-bettercap-and-the-PMKID-client-less-attack/](url)

**Expected behavior:** *A window with all Ap's around me*

**Actual behavior:** *module wifi not running*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by Dema323** [comment]
And if you could just answer my other question that you closed would be great.

**Comment by yungtravla** [comment]
this is not even close to a complete report

**Comment by Dema323** [comment]
everyone a dick on this repo ?

**Comment by yungtravla** [comment]
If you can't even formulate a question, how the fuck do you expect an answer?? There's an entire website with documentation (https://www.bettercap.org/), a lot of time went into it, and now you think you can get a private 1 on 1 bettercap tutorial? Learn some basics before you call people dicks, skid.
