### ISSUE TITLE
Ble.recon not working

### ISSUE THREAD

**Issue by yesimxev** [bettercap/bettercap#577]
*Description of the bug or feature request*

### Environment
Kali NetHunter on CM13, OnePlus One (armhf)
bettercap v2.24 (built for linux arm with go1.11.6)
Using Sena UD100 and chinese CSR4.0 dongles

### Full debug output:
```
» [12:16:45] [sys.log] [err] no supported devices available
10.1.1.0/24 > 10.1.1.101  » [12:16:45] [sys.log] [dbg] ble.recon initializing device (id:-1) ...
10.1.1.0/24 > 10.1.1.101  » [12:16:45] [sys.log] [dbg] ble.recon [gatt.log] got 1 devices
10.1.1.0/24 > 10.1.1.101  » [12:16:45] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 does not support LE
10.1.1.0/24 > 10.1.1.101  » [12:16:45] [sys.log] [dbg] ble.recon [gatt.log] error while opening device 0: does not support LE
10.1.1.0/24 > 10.1.1.101  » [12:16:45] [sys.log] [dbg] ble.recon error while creating new gatt device: no supported devices available
```
### Steps to Reproduce
1. hciconfig hci0 up
2. bettercap
3. ble.recon on

**Expected behavior:**
It should start scanning
**Actual behavior:**
Doesn't do it. Looks like the BLE enable function is different than it was in BLEAH, because it worked before. Also hcitool lescan works with these adapters

Similar on my S6edge (arm64) NetHunter
```
10.20.0.0/24 > 10.20.0.104   ble.recon on
[19:57:50] [sys.log] [dbg] ble.recon initializing device (id:-1) ...
[19:57:50] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 up
[19:57:50] [sys.log] [dbg] ble.recon [gatt.log] got 1 devices
[19:57:50] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 reset
[19:57:51] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 down
[19:57:51] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 can't bind to hci user channel, err: invalid argument.
[19:57:51] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 opened
[19:57:51] [sys.log] [dbg] ble.recon starting discovery ...
```

**Comment by evilsocket** [comment]
hci0 does not support LE

**Comment by yesimxev** [comment]
hci0 does support LE as I mentioned, please re-open @evilsocket

**Comment by dmachibya** [comment]
facing this same issue, and I'm a newbie in linux...
here is what I've tried so far as suggested in the steps above
    1. hciconfig hci0 up
    2. bettercap
    3. ble.recon on

but still getting the same error! Help please!

**Comment by yesimxev** [comment]
@dmachibya does `hcitool lescan` show any BLE devices? For me, bleah was working flawlessly with the same adapter, but I'd like to use bettercap as it has bleah ported into it @evilsocket still not mind reopening the issue?

**Comment by azamet90** [comment]
> @dmachibya does `hcitool lescan` show any BLE devices? For me, bleah was working flawlessly with the same adapter, but I'd like to use bettercap as it has bleah ported into it @evilsocket still not mind reopening the issue?

```
sudo hcitool lescan
Set scan parameters failed: Input/output error
```


does it means it is not supporting?

**Comment by sonupreti** [comment]
When I do ble.recon on, My bluetooth turns off and didn't turn on until I quit bettercap, any solution plz.@
