### ISSUE TITLE
No GPS position shown on the world map

### ISSUE THREAD

**Issue by keldnorman** [bettercap/bettercap#580]
*Description of the feature request*
No GPS position shown on the world map - need GPSd support 

### Environment
Debian 9.9 stretch i686 (Running on a fitlet2 mini PC)
Bettercap Ui 1.3.0 and Bettercap 2.23
Go version 1.12.3 linux/amd64

### Steps to Reproduce
I have a USB GPS attached to the system a G-STAR IV and gpsd running + xgps running to show that i have a GPS lock ( gpsd: https://en.wikipedia.org/wiki/Gpsd )

I have ensured that the position module is using the correct /dev/ttyUSBxxx that the GPS is presented as.

When I activate the "Position" module in the WEB GUI (see image) then the bettercap engine does not pick up the GPS position.

Would it be much work to make bettercap compatible with gpsd ? 

**Expected behavior:** 
The mascot logo should move to the current GPS position on the world map (op north at Denmark where i live and have the GPSd lock)

**Actual behavior:** 
GPS Web GUI View shows No satellites

![bettercap_gps](https://user-images.githubusercontent.com/10332862/59748732-017bc780-927c-11e9-933a-c59ee6754655.JPG)

**Comment by evilsocket** [comment]
did you try to kill gpsd and all the other processes using that /dev/ttyUSB and only use bettercap?

**Comment by keldnorman** [comment]
I did.
I tested with two different USB GPS devices, ensured the chmod was correct on the /dev/ttyUSB0, tested that I could get a lock with the xgps util - killed everything (gpsd and xgps) and started bettercap (it sees the /dev/ttyUSB0 device) but never gets a lock or show any SAT's found. . .

**Comment by evilsocket** [comment]
that's weird, i only tested this with my SkyTraq receiver ( https://www.amazon.it/gp/product/B00EDI5M3A ) which works great ... some receivers as far as I know require some vendor-specific AT initialization commands before they actually start streaming stuff on the USB, is there anything related to that in the manual of your device by any chance?

**Comment by Wh1t3Fox** [comment]
I've been trying to use a https://www.amazon.com/dp/product/B008200LHW and experiencing the same issues as @keldnorman.

**Comment by Wh1t3Fox** [comment]
v2.28 fixes this
