### ISSUE TITLE
"http.proxy" exit status 1

### ISSUE THREAD

**Issue by xxxcrow** [bettercap/bettercap#583]
Kali on Raspberry Pi 3 b+
Http.proxy module "exit status 1" error
Here's a log with -debug option on
> root@kali:~# bettercap -debug
bettercap v2.24 (built for linux arm with go1.11.6) [type 'help' for a list of commands]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.8.1 dev wlan0 proto dhcp metric 600
192.168.8.0/24 dev wlan0 proto kernel scope link src 192.168.8.225 metric 600
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] FindGateway(wlan0) line 'default via 
192.168.8.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.8.1 dev wlan0 proto dhcp metric 600 default 192.168.8.1 wlan0]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [sys.log] [dbg] gateway is 192.168.8.1[hi:dd:en:4p:ri:vc]
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [session.started] {session.started 2019-06-18 15:31:46.851000755 +0000 UTC m=+0.207501315 <nil>}
192.168.8.0/24 > 192.168.8.225  » [15:31:46] [mod.started] events.stream
192.168.8.0/24 > 192.168.8.225  » http.proxy on
[15:32:01] [sys.log] [err] exit status 1
192.168.8.0/24 > 192.168.8.225  »

**Comment by raymondbo1234** [comment]
Running Kali on raspberry pi zero w with bettercap version v2.24.1. I get the same error "http.proxy" exit status 1 

 `bettercap -debug
bettercap v2.24.1 (built for linux arm with go1.11.6) [type 'help' for a list of commands]

192.168.0.0/24 > 192.168.0.88  » [10:57:43] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.0.0/24 > 192.168.0.88  » [10:57:43] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp src 192.168.0.88 metric 302
172.16.0.0/30 dev usbeth proto kernel scope link src 172.16.0.1
172.26.0.0/24 dev bteth proto kernel scope link src 172.26.0.1 linkdown
192.168.0.0/24 dev wlan0 proto dhcp scope link src 192.168.0.88 metric 302
192.168.0.0/24 > 192.168.0.88  » [10:57:43] [sys.log] [dbg] FindGateway(wlan0) line 'default via 192.168.0.1 dev wlan0 proto dhcp src 192.168.0.88 metric 302' matched with [default via 192.168.0.1 dev wlan0 proto dhcp src 192.168.0.88 metric 302 default 192.168.0.1 wlan0]
192.168.0.0/24 > 192.168.0.88  » [10:57:43] [sys.log] [dbg] gateway is 192.168.0.1[Mac Adress of Gateway]
192.168.0.0/24 > 192.168.0.88  » [10:57:43] [session.started] {session.started 2019-09-01 10:57:43.966638 +0000 UTC m=+1.017182001 <nil>}
192.168.0.0/24 > 192.168.0.88  » [10:57:43] [mod.started] events.stream
192.168.0.0/24 > 192.168.0.88  » http.proxy on
192.168.0.0/24 > 192.168.0.88  » [10:57:52] [sys.log] [err] exit status 1
192.168.0.0/24 > 192.168.0.88  »

**Comment by he1senbug** [comment]
Catched such an issue on Raspberry Pi Zero W with Kali Linux.
After debugging I have found that the error throws on attempt to run iptables command.
I was able to fix the problem by running in shell:
`update-alternatives --config iptables`
and selecting
`/usr/sbin/iptables-legacy 10 manual mode`

**Comment by lastorder-svg** [comment]
try using it with sudo su....
