### ISSUE TITLE
sslstrip on v2.24.1 shows error on target

### ISSUE THREAD

**Issue by ItsAryan** [bettercap/bettercap#587]
after arpspoof and sslstrip target browser show "Go back to safe" error

**Comment by constantstruggle** [comment]
because HSTS needs stripping from the site your targeting if possible.  SSLStrip and SSL attacks are quiet difficult to pull off now unless you can get your certs installed.

**Comment by yungtravla** [comment]
huge thread on when you can and cannot sslstrip: https://github.com/bettercap/bettercap/issues/428
