### ISSUE TITLE
I have an issue with buttercup sniff I am runnning it on Mac OS

### ISSUE THREAD

**Issue by hamuu96** [bettercap/bettercap#588]
I am trying to sniff login information from a http site but I seem not to get the information 
this is the information am getting please help
![Screenshot 2019-07-09 at 19 35 41](https://user-images.githubusercontent.com/36361150/60906820-c0764200-a280-11e9-8f67-ec3d208f6402.png)

**Comment by yungtravla** [comment]
Please write a complete report
