### ISSUE TITLE
[sys.log] [war] Could not detect gateway.

### ISSUE THREAD

**Issue by 0Zerro** [bettercap/bettercap#589]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). : bettercap v2.24.1 (built for linux amd64 with go1.11.6)
* OS version and architecture you are using. : 4.19.37-5kali1 (2019-06-20) x86_64 
* Go version if building from sources. 
* Command line arguments you are using. : none
* Caplet code you are using or the interactive session commands. : no caplets
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ) : 

`bettercap v2.24.1 (built for linux amd64 with go1.11.6) [type 'help' for a list of commands]

```
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [sys.log] [dbg] FindGateway(wlan0) output:
default via 10.80.45.213 dev wlan0 proto dhcp metric 600 
10.80.45.0/24 dev wlan0 proto kernel scope link src 10.80.45.190 metric 600
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [sys.log] [dbg] FindGateway(wlan0) line 'default via 10.80.45.213 dev wlan0 proto dhcp metric 600' matched with [default via 10.80.45.213 dev wlan0 proto dhcp metric 600 default 10.80.45.213 wlan0]
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [sys.log] [war] Could not find mac for 10.80.45.213
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [session.started] {session.started 2019-07-11 07:12:13.811788275 -0400 EDT m=+0.101654519 <nil>}
10.80.45.0/24 > 10.80.45.190  » [07:12:13] [mod.started] events.stream
```

When ever I start using 
`bettercap -iface wlan0`
I get 
`[06:55:26] [sys.log] [war] Could not detect gateway.`
What I typed : `net.probe on` 
What I expected : to start checking nearby devices that are connected to an access point
What I got : `[07:07:47] [sys.log] [inf] net.probe starting net.recon as a requirement for net.probe`  
then nothing it didn't show anything and didn't even discover a client although I'm in a busy spot
 
`netstart-nr`
 gave me 
`Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.80.45.213    0.0.0.0         UG        0 0          0 wlan0
10.80.45.0      0.0.0.0         255.255.255.0   U         0 0          0 wlan0
`
just saw someone else addressing the same issue and you asking for `netstart-nr` so thought of adding it 
Thanks in advance;it's a great tool I used to enjoy using it until I got that issue.

**Comment by Drjacky** [comment]
@0Zerro How did you solve it?
