### ISSUE TITLE
Cannot access http-ui on Windows using Docker image

### ISSUE THREAD

**Issue by AnthonyMastrean** [bettercap/bettercap#590]
I can't get anything to load at `http://127.0.0.1` on Windows using the latest Docker image. I don't see anything relevant in the bettercap logs or the browser dev tools!

![image](https://user-images.githubusercontent.com/217842/61084737-a06b8d80-a3fc-11e9-95b0-3c9021f8857f.png)

### Environment

Please provide:

* Bettercap version: `bettercap/bettercap:latest` (which is currently reporting: `bettercap v2.24 (built for linux amd64 with go1.12.4`)
* OS version and architecture you are using: Windows 10 1903 64-bit
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

I pulled the latest image.

```
$ docker pull bettercap/bettercap
```

And decided to just run the commands interactively in the bettercap shell (to avoid trying to figure out how to quote or concat commands, etc.).

```
PS> docker run --rm -it --privileged --net=host bettercap/bettercap -debug
bettercap v2.24 (built for linux amd64 with go1.12.4) [type 'help' for a list of commands]

10.0.75.0/24 > 10.0.75.2  » [21:00:51] [sys.log] [dbg] FindGateway(hvint0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
10.0.75.0/24 > 10.0.75.2  » [21:00:51] [sys.log] [dbg] FindGateway(hvint0) output:
default via 192.168.65.1 dev eth0
10.0.75.0/24 dev hvint0 proto kernel scope link src 10.0.75.2
127.0.0.0/8 dev lo scope host
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.27.0.0/16 dev br-99ac7e7b344b proto kernel scope link src 172.27.0.1 linkdown172.29.0.0/16 dev br-e281a12da720 proto kernel scope link src 172.29.0.1 linkdown
192.168.65.0/24 dev eth0 proto kernel scope link src 192.168.65.3
10.0.75.0/24 > 10.0.75.2  » [21:00:51] [sys.log] [dbg] FindGateway(hvint0): nothing found :/
10.0.75.0/24 > 10.0.75.2  » [21:00:51] [sys.log] [war] Could not detect gateway.10.0.75.0/24 > 10.0.75.2  » [21:00:51] [session.started] {session.started 2019-07-11 21:00:51.8228417 +0000 
UTC m=+0.083636601 <nil>}
10.0.75.0/24 > 10.0.75.2  » [21:00:51] [mod.started] events.stream
10.0.75.0/24 > 10.0.75.2  » caplets.update
[21:00:57] [sys.log] [inf] caplets creating caplets install path /usr/local/share/bettercap/ ...
[21:00:57] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[21:00:57] [sys.log] [inf] caplets installing caplets to /usr/local/share/bettercap/caplets ...
10.0.75.0/24 > 10.0.75.2  » ui.update[21:01:00] [sys.log] [inf] ui checking latest stable release ...
[21:01:00] [mod.started] ui
[21:01:00] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...[21:01:01] [sys.log] [inf] ui installing to /usr/local/share/bettercap/ui ...
[21:01:01] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
10.0.75.0/24 > 10.0.75.2  » [21:01:01] [mod.stopped] ui
10.0.75.0/24 > 10.0.75.2  » http-ui
10.0.75.0/24 > 10.0.75.2  » [21:01:03] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:808110.0.75.0/24 > 10.0.75.2  » [21:01:03] [mod.started] api.rest
10.0.75.0/24 > 10.0.75.2  » [21:01:03] [mod.started] http.server
10.0.75.0/24 > 10.0.75.2  » [21:01:03] [sys.log] [inf] http.server starting on http://127.0.0.1:80
10.0.75.0/24 > 10.0.75.2  » help

           help MODULE : List available commands or show module specific help if no module name is provided.                active : Show information about active modules.                  quit : Close the session and exit.
         sleep SECONDS : Sleep for the given amount of seconds.
              get NAME : Get the value of variable NAME, use * alone for all, or NAME* as a wildcard.       
        set NAME VALUE : Set the VALUE of variable NAME.
  read VARIABLE PROMPT : Show a PROMPT to ask the user for input that will be saved inside VARIABLE.        
                 clear : Clear the screen.
        include CAPLET : Load and run this caplet in the current session.             ! COMMAND : Execute a shell command and print its output.
        alias MAC NAME : Assign an alias to a given endpoint given its MAC address.

Modules
      any.proxy > not running
       api.rest > running
      arp.spoof > not running
      ble.recon > not running
        caplets > not running    dhcp6.spoof > not running
      dns.spoof > not running
  events.stream > running            gps > not running
            hid > not running
     http.proxy > not running    http.server > running    https.proxy > not running
   https.server > not running    mac.changer > not running
    mdns.server > not running
   mysql.server > not running
      net.probe > not running      net.recon > not running
      net.sniff > not running
   packet.proxy > not running
       syn.scan > not running
      tcp.proxy > not running
         ticker > not running
             ui > not running
         update > not running
           wifi > not running
            wol > not running

10.0.75.0/24 > 10.0.75.2  » help http.server

http.server (running): A simple HTTP server, to be used to serve files and scripts across the network.      

   http.server on : Start httpd server.
  http.server off : Stop httpd server.

  Parameters

  http.server.address : Address to bind the http server to. (default=<interface address>)
     http.server.path : Server folder. (default=.)
     http.server.port : Port to bind the http server to. (default=80)
```

**Expected behavior:** *What you expected to happen*

I should see a killer UI.

**Actual behavior:** *What actually happened*

I get an ERR_CONNECTION_REFUSED error.

**Comment by AnthonyMastrean** [comment]
I guess I'm still learning about Docker 

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

https://docs.docker.com/network/host/

**Comment by AnthonyMastrean** [comment]
I guess I'm still interested in how to publish the http-ui port and actually hit the website on Windows and Docker... even if things don't work, generally, without `--net=host` (unless `--privileged` picks up the slack on Windows?)

**Comment by AnthonyMastrean** [comment]
If I run the image like so

```
$ docker run --rm -it --privileged -p 80:80 bettercap/bettercap
```

And run the same commands (`caplets.update`, `ui.update`, and `http-ui`), I see the same output. I can confirm the Docker port publish here

```
PS> docker ps -a
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                                                    NAMES
9098baaafa38        bettercap/bettercap   "/app/bettercap"    5 minutes ago       Up 5 minutes        53/tcp, 443/tcp, 5300/tcp, 8000/tcp, 8080-8083/tcp, 0.0.0.0:80->80/tcp   admiring_curran
```

But, the website still doesn't load (same ERR_CONNECTION_REFUSED). And I don't see any active TCP connections on port 80.

```
PS> Get-ActiveTCPConnections | ?{ $_.LocalPort -eq 80 } | Format-Table -AutoSize
```

**Comment by AnthonyMastrean** [comment]
Actually, it looks like I was using localhost, not 127.0.0.1. Let's try again...

 *  ERR_EMPTY_RESPONSE on `http://127.0.0.1`
 * and ERR_CONNECTION_REFUSED on `http://localhost`

**Comment by mrtuborg** [comment]
On the same page now. You can remove "Windows" from tittle, I am trying the same on OSX, so this is not an OS-specific.

First of all, you are not using persistent volumes, after `caplets.update, ui.update` you closing container and everything is gone. You need to make it persistent, like this:

1.  Create a persistent volume for a container:
```
% docker volume create bettercap
```

2. Map this volume inside running container with option `-v`:
```
% docker run -it --privileged --net=host bettercap/bettercap -v bettercap:/usr/local/share/bettercap -eval "caplets.update; ui.update; q"
```

3. Run bettercap with http-ui
```
docker run -it --privileged --net=host -v bettercap:/usr/local/share/bettercap bettercap/bettercap -caplet http-ui
```

So, after all it should work, but for me I still cannot reach http port, will Digg further and update here if I will find something.

**Comment by AnthonyMastrean** [comment]
@mrtuborg thanks for the repro! I don't _need_ a named volume since I'm running the container in the foreground with an interactive shell. For the purposes of this bug report, It made things a little more straightforward (no cached state, clean startup/shutdown every time... I just exit the shell).

You are right that, to persist the data, you need the volume.

**Comment by yoaquim** [comment]
Can confirm that starting a foreground container with `docker run -it --privileged --net=host bettercap/bettercap` and within the container running `caplets.update;ui.update;http-ui` _appears_ to work, but in fact cannot access it from my machine:

```
192.168.65.0/24 > 192.168.65.3  » caplets.update;ui.update;http-ui
[22:50:07] [sys.log] [inf] caplets creating caplets install path /usr/local/share/bettercap/ ...
[22:50:08] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[22:50:09] [sys.log] [inf] caplets installing caplets to /usr/local/share/bettercap/caplets ...
[22:50:09] [sys.log] [inf] ui checking latest stable release ...
[22:50:09] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...
[22:50:11] [sys.log] [inf] ui installing to /usr/local/share/bettercap/ui ...
[22:50:11] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
192.168.65.0/24 > 192.168.65.3  » [22:50:11] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.65.0/24 > 192.168.65.3  » [22:50:11] [sys.log] [inf] http.server starting on http://127.0.0.1:80
```

**Comment by baconwaifu** [comment]
From what I can tell, the UI is binding to localhost by default, and since `--net=host` only works on linux, it's impossible to access bettercap's "localhost" from outside the container. try changing the listen address to `0.0.0.0`, and setting a non-default password.

**Comment by AnthonyMastrean** [comment]
@baconwaifu do you mean change the listen address on Docker's `--publish` parameter? I believe, from `docker ps` output, that `0.0.0.0` is an implied default when you use it like `-p 80:80`. Or is there a setting _in_ bettercap?

**Comment by baconwaifu** [comment]
You have to change the configuration so *bettercap* isn't binding to `127.0.0.1`. docker's `publish` binding affects where `docker` forwards the port from, but since bettercap is binding to the container's `localhost`, even if docker is correctly directing port 80 to it, bettercap's not listening.

**Comment by AnthonyMastrean** [comment]
@baconwaifu Good call, that it won't be useful on Windows. It's just my default to try new software in Docker, when possible. I'm sure there's value in fixing whatever binding problems popped up here, but I'll go about things another way.

**Comment by nazariyv** [comment]
I am using kali with docker and 404 page not found when trying localhost:80 or 127.0.0.1:80

**Comment by nazariyv** [comment]
looks like following mrtuborg's instructions worked! I had to mount the volume, and then it started working. thanks!

**Comment by hadifarnoud** [comment]
any update on this? have the same issue on MacOS

**Comment by lanrat** [comment]
I have found a solution for accessing the HTTP UI from within docker. You need to manually set the HTTP and API server to listen on `0.0.0.0` and then manually start the HTTP and API server. Using the `http-ui` caplet will not work as it overrides the listen addresses back to `127.0.0.1`

I use the following script to start my bettercap instance in side Docker.

```bash
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

WEB_CMD="set wifi.handshakes.file /data/bettercap-wifi-handshakes.pcap; \
    set api.rest.address 0.0.0.0; \
    set http.server.port 1337; \
    set http.server.address 0.0.0.0; \
    set http.server.path /usr/local/share/bettercap/ui; \
    api.rest on; \
    http.server on;"

# use below to update caplets and UI
UPDATE_CMD="caplets.update; ui.update; q"

docker run --rm -it --name bettercap --privileged \
    --net=host \
    -v bettercap:/usr/local/share/bettercap \
    -v "$DIR/data":/data \
    bettercap/bettercap \
    -eval "$WEB_CMD"

```
