### ISSUE TITLE
Problems "getting started" on Windows

### ISSUE THREAD

**Issue by AnthonyMastrean** [bettercap/bettercap#591]
I'm not a networking genius, so I'm kind of coming at this with _just_ the information on https://www.bettercap.org/ and https://github.com/bettercap/bettercap/. And I'm not sure if any of my later errors are due to earlier setup, so I'm just gonna walk through the whole thing.

### Environment

Please provide:

* Bettercap version: `bettercap v2.24.1 (built for windows amd64 with go1.12.4)`
* OS version and architecture you are using: Windows 10 Pro 64-bit 1903
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

Download the Windows file from the [releases page](https://github.com/bettercap/bettercap/releases/tag/v2.24.1).

Does it need to be [unblocked](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/)? Is that a relevant security issue? The ZIP file shows as blocked when downloaded. But, I'm not sure it behaves any differently when unblocked. I'll proceed by unblocking then extracting.

![image](https://user-images.githubusercontent.com/217842/61138475-95187080-a495-11e9-8acf-74f1da0beed0.png)

At this point, `bettercap.exe` does nothing when invoked (maybe an error message here would help).

```
PS> .\bettercap.exe
```

There are more [install pre-reqs](https://www.bettercap.org/installation/#precompiled-binaries).

> For every new release, we distribute bettercap’s precompiled binaries. In order to be able to use them, you’ll need the following dependencies on your system:
> 
> libpcap
> libusb-1.0-0 (required by the HID module)

I don't understand what "need... on your system" means for Windows. In the same folder as `bettercap.exe`? Installed to some well-known system location?

I'm not sure where to get [libpcap for Windows](https://en.wikipedia.org/wiki/Pcap#pcap_libraries_for_Windows)... [WinPcap](https://www.winpcap.org/news.htm) is obsolete, [Npcap](https://nmap.org/book/inst-windows.html) is current (but, will it work?), and [libpcap](https://www.tcpdump.org/#latest-releases) is a source code archive (do I need to build one)?

I'll go with Npcap, for now, with these settings.

![image](https://user-images.githubusercontent.com/217842/61138079-c3e21700-a494-11e9-9c7e-4f4de0bdbc17.png)

For libusb, I _assume_ on Windows we're looking for something like `libusb-1.0.dll`. It looks like this is the [official website](https://libusb.info/) and the downloads come from their [GitHub releases](https://github.com/libusb/libusb/releases) page. This is another blocked archive. I'll unblock and extract.

![image](https://user-images.githubusercontent.com/217842/61138453-8762eb00-a495-11e9-89c0-531f8f13a970.png)

There is no installer, it's just a DLL (actually, several DLLs for different... platforms?). I'll choose `libusb-1.0.22.7z\MS64\dll\libusb-1.0.dll`. I don't know where to "install" this, but [this issue](https://github.com/bettercap/bettercap/issues/557#issuecomment-487404561) indicates...

> Just make sure that's in the same directory as bettercap.exe

Now we're in business! I ran in an Administrator PowerShell session otherwise, I get a sketchy UAC pop-up from Npcap.

![npcap-uac](https://user-images.githubusercontent.com/217842/61140666-d3179380-a499-11e9-9edb-331312fa3642.jpg)

```
PS> .\bettercap.exe                                                                                                        

WARNING: This terminal does not support colors, view will be very limited.

bettercap v2.24.1 (built for windows amd64 with go1.12.4) [type 'help' for a list of commands]

10.0.75.0/24 > 10.0.75.1  »
```

I am unable to update caplets.

```
10.0.75.0/24 > 10.0.75.1  » caplets.update
[11:16:12] [sys.log] [inf] caplets creating caplets install path /usr/local/share/bettercap/ ...
[11:16:12] [sys.log] [err] open /tmp/caplets.zip: The system cannot find the path specified.
```

At this point, I'm looking for `bettercap`'s data folders, because I see it's still referencing Linux paths (`/usr/local/share/bettercap`). I found files in `C:\`! This is an extremely non-standard path for Windows applications.

Some paths that might make sense on Windows include (I'm not finding great [references](https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/) on the use and expectations of these locations):

 * `%USERPROFILE%\.bettercap`
 * `%PROGRAMDATA%\bettercap`
 * `%LOCALAPPDATA%\bettercap`

Using my new knowledge, if I manually create `C:\tmp`, then I can update caplets.

```
PS> mkdir C:\tmp
PS> bettercap.exe
...
10.0.75.0/24 > 10.0.75.1  » caplets.update
[11:16:59] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[11:16:59] [sys.log] [inf] caplets installing caplets to \usr\local\share\bettercap\caplets ...
```

Now, I can update the UI and run the HTTP server.

```
10.0.75.0/24 > 10.0.75.1  » ui.update
[11:24:22] [sys.log] [inf] ui checking latest stable release ...
[11:24:23] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...
[11:24:24] [sys.log] [inf] ui installing to \usr\local\share\bettercap\ui ...
[11:24:32] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
10.0.75.0/24 > 10.0.75.1  » http-ui
[11:25:06] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
```

Success!

![image](https://user-images.githubusercontent.com/217842/61139713-e164b000-a497-11e9-9d8b-8f09c961a3f9.png)

Although, the log dumps a lot of `wtf` messages on start and while poking around the UI.

```
wtf: caplet C:\usr\local\share\bettercap\caplets\ap.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\gps.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\http-ui.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\https-ui.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\local-sniffer.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\mana.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\massdeauth.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\mitm6.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\netmon.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\pita.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\rogue-mysql-server.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\simple-passwords-sniffer.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\crypto-miner\crypto-miner.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\download-autopwn\download-autopwn.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\fb-phish\fb-phish.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\gitspoof\gitspoof.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\hstshijack\hstshijack.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\http-req-dump\http-req-dump.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\jsinject\jsinject.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\login-manager-abuse\login-man-abuse.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\proxy-script-test\proxy-script-test.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\rtfm\rtfm.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\tcp-req-dump\tcp-req-dump.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\web-override\web-override.cap not found
```

**Expected behavior:** *What you expected to happen*

It would be good for bettercap to follow Windows standards, conventions, and user expectations. And it would be good if the docs were more complete for Windows users. A summary of the items that I found above...

 - [ ] Note whether the bettercap Windows archive needs to be unblocked.
 - [ ] Provide an error message if pre-requisites are not found.
 - [ ] Provide instructions/links for installing libpcap on Windows via Npcap.
 - [ ] Provide instructions/links for installing libusb on Windows via their website (also, note unblocking and "install" by copy/paste... or consider bundling the tested version of libusb with bettercap for Windows?)
 - [ ] Explain the sketchy UAC pop-up coming from Npcap.
 - [ ] Write files to the correct Windows location.
 - [ ] Test for and create your required data directories if they do not exist (to avoid errors, say, when trying to download `caplets.zip`).
 - [ ] Figure out why bettercap writes these `wtf` messages to the logs on Windows

**Actual behavior:** *What actually happened*

The Windows experience is a little rough.

**Comment by AnthonyMastrean** [comment]
It sure looks like bettercap on Windows isn't loading the caplets that are sitting here on disk. I can click "install" or run `caplets.update` and it does the same thing (lots of `wtf` messages, too). Maybe a path issue?

![image](https://user-images.githubusercontent.com/217842/61141342-5b4a6880-a49b-11e9-9207-34a1c7d6080f.png)
![image](https://user-images.githubusercontent.com/217842/61141357-656c6700-a49b-11e9-8f86-e30d696acee2.png)

**Comment by fuomag9** [comment]
If it wasn't for this issue I'd not have even been able to install it on windows

**Comment by netzeng** [comment]
the same to you  .+1

**Comment by elvarb** [comment]
Regarding the wtf messages I'm finding lots of hardcoded paths that could be the cause of the problem. I have tried to modify some of them but have not been successful of fixing the errors.

Using web-override as an example

web-override.cap includes reference to web-override.js, not sure from what root path bettercap tries to read the .js file but I tried changing it to full windows path without success.

web-override.js defines res.Body as the full path "/usr/local/share/bettercap/caplets/www/index.html" and since this is javascript and not Go I'm not sure if it understands to read from the C:\ root or not. Tried changing to full windows path here also without success.

Next step would be to go over the Go code in bettercap to understand precisely what it is doing when it logs the error.

**Comment by master-qwerty** [comment]
Hello there,
I am trying to reproduce "guide" above but it failing when trying to run `.\bettercap.exe`
From Kali I know that it has to be run with parametr `-iface`. I'v tried that as well but no luck. 
What I am missing ? I really would like to test it under Windows but absence of any guide is making it almost nightmare, and even if any exist like this one, it does not work. I really appreciate any help.

```
> WARNING: This terminal does not support colors, view will be very limited.
> bettercap v2.24.1 (built for windows amd64 with go1.12.4) [type 'help' for a list of commands]
> Ethernet 2: Error opening adapter: The system cannot find the device specified.  (20)
```

**Installation status:**
- OS & build: Windows 10 Pro - 1903

- NPCAP installed

```

> DisplayName            DisplayVersion   Publisher                              InstallDate
> -----------             --------------   ---------                              -----------
> Npcap 0.9982            0.9982           Nmap Project
```
- DLL copied as per guide above.

```

> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----        6/22/2019   3:14 PM       40300450 bettercap.exe
> -a----        3/25/2018   3:00 AM         121856 libusb-1.0.dll
> -a----        1/27/2019   1:52 PM          35187 LICENSE.md
> -a----        4/24/2019   8:13 PM           4817 README.md

```
Thanks in advance,

**Comment by AnthonyMastrean** [comment]
Looking forward to trying the fix when it's released! Thanks @realgam3

**Comment by pizzafox** [comment]
Can we get an update as to when this is going to be released? Compiling from source isn't viable for Windows users and WSL networking support is broken, which leaves most Windows users unable to use Bettercap.

**Comment by evilsocket** [comment]
@pizzafox why exactly compiling from source isn't viable for Windows users? How do you think the windows prebuilt binaries are compiled? :D

**Comment by pizzafox** [comment]
The docs say that running all the install commands will put the binary in `/usr/local/bin/bettercap`. What does this do on Windows? Also, `build-essential` is listed as a dependency and is a Linux only package as far as I can tell.
Finally, while not impossible (as far as I can tell), many Bettercap dependencies have their own dependencies. Since Windows doesn't have a package manager to install them, you have to manually go through the dependency tree and install all of the Windows versions of the dependencies

**Comment by fuomag9** [comment]
And there's also the fact that there's no compiling guide for Windows on the wiki as far as I remember

**Comment by realgam3** [comment]
> And there's also the fact that there's no compiling guide for Windows on the wiki as far as I remember

OK so it took me a while but you will like it :)
This is what i done:
https://www.msys2.org/

On MSys2:
pacman -Syu
pacman -S mingw-w64-x86_64-go mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libusb

On Windows:
export GOPATH=%USERPROFILE%\go
export GOROOT=C:\MSys64\mingw64\lib\go
export PATH=%PATH%;%GOPATH%\bin;%GOROOT%\bin;C:\MSys64\mingw64\bin
export PKG_CONFIG_PATH=C:\MSys64\mingw64\lib\pkgconfig

**Comment by 0-x27** [comment]
Dear BetterCap, please resolve these issues/hardcoded paths that don't exist on the windows platform, thanks.

**Comment by evilsocket** [comment]
Dear @0-x27, this is an opensource project, if you're in such an urge to get these fixes, you can do them yourself and send a PR.

I think people tend to forget this is free software.

**Comment by 0-x27** [comment]
@evilsocket Though it's open source, it wouldn't hurt to **properly** implement the file path into windows? Regardless if its free software or not, but whatever.

**Comment by AnthonyMastrean** [comment]
There’s a PR merged that addresses some if not all of the path issues. I haven’t had time to build and test it yet, but I assume the PR author did. 

https://github.com/bettercap/bettercap/issues/618

There’s a build script with a Windows section you can piece apart if you need to build it manually.

https://github.com/bettercap/bettercap/blob/master/build.sh

**Comment by evilsocket** [comment]
> @evilsocket Though it's open source, it wouldn't hurt to **properly** implement the file path into windows? Regardless if its free software or not, but whatever.

@0-x27 yes, and that means that if you really need windows support to be *properly* implemented, you can write it yourself and send a pull request. I think you have a pretty weird idea of what opensource is.

**Comment by realgam3** [comment]
> > @evilsocket Though it's open source, it wouldn't hurt to **properly** implement the file path into windows? Regardless if its free software or not, but whatever.
> 
> @0-x27 yes, and that means that if you really need windows support to be _properly_ implemented, you can write it yourself and send a pull request. I think you have a pretty weird idea of what opensource is.

Is it possible to arrange a short conversation? maybe we can fix it together :)

**Comment by rfitzpatrick1** [comment]
Is anyone else unable to view the images on this issue, or is it a problem with my computer?

**Comment by fuomag9** [comment]
> Is anyone else unable to view the images on this issue, or is it a problem with my computer?

It's just you

**Comment by rfitzpatrick1** [comment]
After fixing my previous issue, I have tried to replicate the steps shown above, but when I try to execute bettercap, I get the following:
WARNING: This terminal does not support colours, view will be very limited

bettercap v2.26.1 (built for windows amd64 with go1.13.3) [type 'help' for a list of commands]

169.254.0.0/16 > 169.254.26.244 >> [16:31:56] [sys.log] [war] Could not detect gateway.
169.254.0.0/16 > 169.254.26.244 >> @[J@[2K

(I'm not 100% sure that they're @ symbols and not something else, as they look rectangular on the command prompt)

How can I rectify this?

**Comment by realgam3** [comment]
You can use ConEmu/Console 2
Or ansicon on Windows 😅
http://sourceforge.net/projects/conemu/
http://sourceforge.net/projects/console/
https://github.com/adoxa/ansicon

Have fun 😊

**Comment by rfitzpatrick1** [comment]
I've now managed to get to the login screen as shown above. Where would I now find my username and password? From what it says on the Usage page, I'm guessing that it would be somewhere in the caplets folder. However, the only location in which I would think it might be located is login-manager-abuse, but I can't open any of the files in it.
As per the instructions on the Usage page, I haven't (knowingly) run caplets.update more than once.

**Comment by karan221** [comment]
> 
> 
> I've now managed to get to the login screen as shown above. Where would I now find my username and password? From what it says on the Usage page, I'm guessing that it would be somewhere in the caplets folder. However, the only location in which I would think it might be located is login-manager-abuse, but I can't open any of the files in it.
> As per the instructions on the Usage page, I haven't (knowingly) run caplets.update more than once.

I am only getting a blank screen.

**Comment by debasser1911** [comment]
> After fixing my previous issue, I have tried to replicate the steps shown above, but when I try to execute bettercap, I get the following:
> WARNING: This terminal does not support colours, view will be very limited
> 
> bettercap v2.26.1 (built for windows amd64 with go1.13.3) [type 'help' for a list of commands]
> 
> 169.254.0.0/16 > 169.254.26.244 >> [16:31:56] [sys.log] [war] Could not detect gateway.
> 169.254.0.0/16 > 169.254.26.244 >> @[J@[2K
> 
> (I'm not 100% sure that they're @ symbols and not something else, as they look rectangular on the command prompt)
> 
> How can I rectify this?

have the same problem on windows 10

**Comment by Aashs** [comment]
I get a error when i tried running it exe file - The code execution cannot proceed because libusb-1.0dll was not found. Reinstalling the program may fix this problem. Where can I get libusb
