### ISSUE TITLE
"UI Version 1.3.0 requires API 2.24"

### ISSUE THREAD

**Issue by cmchir** [bettercap/bettercap#596]
Hi!

I am using the latest Bettercap (2.24.1) running on Kali Linux (running on VirtualBox on a Mac) and in the UI, I get this:

"UI Version | 1.3.0 requires API 2.24" in the Advanced section of the UI

I have installed bettercap-ui separately (version 1.3.0) because it was not on the Kali Linux's bettercap deployment.
I have also performed a 'sudo gem update'
Is there a way how I can get the latest bettercap-ui please?

Thanks and Regards,

**Comment by evilsocket** [comment]
ui 1.3 and bettercap 2.24.1 work great together, you're doing something wrong (maybe you updated but still running an older version of bettercap?)

![Schermata da 2019-09-08 15-41-06](https://user-images.githubusercontent.com/86922/64489073-2f572380-d24f-11e9-89b2-653c7852d80e.png)
