### ISSUE TITLE
What hardware works well with Bettercap?

### ISSUE THREAD

**Issue by victorhooi** [bettercap/bettercap#597]
Is it possible to document what hardware works well with Bettercap.

For example, say you wanted to build your own standalone Bettercap device. (Like a Wifi Pineapple but more hands on 😋).

Are there wifi routers our there that are known to work? (Install on top of OpenWRT?)

Or would a Raspberry Pi 4 work? And with what USB wifi dongles?

**Comment by evilsocket** [comment]
duplicate https://github.com/bettercap/bettercap/issues/727
