### ISSUE TITLE
implement packet.proxy module

### ISSUE THREAD

**Issue by evilsocket** [bettercap/bettercap#6]
implement `packet.proxy` module using NFQUEUEs.

**Comment by evilsocket** [comment]
Given this would be a Linux only module and that executing a javascript for every packet while blocking it would add a massive overhead to network traffic, the `ip.proxy` will use [Go plugin system](https://golang.org/pkg/plugin/) for modules.

**Comment by leonardoporpora** [comment]
Good job bro 🔝😎

**Comment by evilsocket** [comment]
Documented here https://github.com/bettercap/bettercap/wiki/packet.proxy
