### ISSUE TITLE
Betternet with GPS Event sessions similar to WiFi?

### ISSUE THREAD

**Issue by AirSingh** [bettercap/bettercap#600]
Running Bettercap v2.24.1 built for Linux amd64 with Go version 1.10.4

This is not really a bug issue, but a question in regards to the gps commands.  I am working on a Alpine Linux based OS, and bettercap is being used to communicate with raspbery Pi devices. Im taking in readings for WiFi signals and their Access Points, as well as GPS Coordinates. Everything is working fine, but I wanted to ask how, if possible, to obtain readings of the gps.show commands to be outputted on to the my own AWS servers, or maybe just a log file that can be accessed and read (from there I could be extracted and outputted to wherever needed). Currently i have gps lat/long showing in the terminal in 3 seconds periods (via ticker command). I seen the event sessions go file and the wifi events being created, and noticed there was nothing for GPS, and was wondering if there was a way to input GPS Event sessions, so that gps coordiantes would be displayed there in intervals. Any help would be greatly appreciated

**Comment by yungtravla** [comment]
Of course you can :D I suggest using the builtin REST API, it sorts the events neatly in JSON format, so it's very easy to parse. You should parse these logs locally and then send them to your AWS server.

If you don't want to use the API you could have a shell script that parses plaintext logs and uploads them to your AWS server.

**Comment by AirSingh** [comment]
thanks
