### ISSUE TITLE
windows  bettercap  execute  error?

### ISSUE THREAD

**Issue by netzeng** [bettercap/bettercap#602]
G:\bettercap_windows_amd64_2.24.1>bettercap -eval "caplets.update; ui.update; q"

WARNING: This terminal does not support colors, view will be very limited.

bettercap v2.24.1 (built for windows amd64 with go1.12.4) [type 'help' for a list of commands]

[19:55:24] [sys.log] [war] Could not detect gateway.
[19:55:25] [sys.log] [err] **error while running 'caplets.update': open /tmp/caplets.zip: The system cannot find the path specified.**
[19:55:25] [sys.log] [inf] ui checking latest stable release ...
[19:55:26] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...

**Comment by netzeng** [comment]
192.168.1.0/24 > 192.168.1.103  » caplets.update
[10:23:57] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[10:24:01] [sys.log] [inf] caplets installing caplets to \usr\local\share\bettercap\caplets ...
192.168.1.0/24 > 192.168.1.103  » caplets.show
wtf: caplet C:\usr\local\share\bettercap\caplets\ap.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\gps.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\http-ui.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\https-ui.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\local-sniffer.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\mana.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\massdeauth.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\mitm6.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\netmon.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\pita.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\rogue-mysql-server.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\simple-passwords-sniffer.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\crypto-miner\crypto-miner.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\download-autopwn\download-autopwn.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\fb-phish\fb-phish.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\gitspoof\gitspoof.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\hstshijack\hstshijack.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\http-req-dump\http-req-dump.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\jsinject\jsinject.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\login-manager-abuse\login-man-abuse.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\proxy-script-test\proxy-script-test.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\rtfm\rtfm.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\tcp-req-dump\tcp-req-dump.cap not found
wtf: caplet C:\usr\local\share\bettercap\caplets\web-override\web-override.cap not found
[10:24:09] [sys.log] [err] no installed caplets on this system, use the caplets.update command to download them
192.168.1.0/24 > 192.168.1.103  »

**Comment by realgam3** [comment]
I have fixed it here:
https://github.com/realgam3/bettercap/commit/c46bb905b9040e56342ba119fec292aad317ae2a

I will add a pull request
