### ISSUE TITLE
Performance Issues - Rpi0W

### ISSUE THREAD

**Issue by mlinton** [bettercap/bettercap#608]
When running on a raspberryPI Zero W, performance starts fine only consuming around 55% CPU, however after several hours it degrades and is not stable anymore.

bettercap v2.24.1 (built for linux arm with go1.12.7)
Rasbian buster - Linux raspberrypi 4.19.55-Re4son+ #1 Tue Jul 2 18:44:01 AEST 2019 armv6l GNU/Linux

- Used the Re4son installer to get the nexmon drivers installed
- enabled usb0 interface using the dwc2 overlay
- removed wpa_supplicant services and processes
- increased swapsize to 2048M with /etc/dphys-swapfile
- ifconfig wlan0 down and enabled the monitor on the built-in interface
- just enabled wifi.recon with default channels selected
- running https-ui and connecting to the interface from the host over usb0
- small home neighbourhood network environment with < 10 wifi networks visible

It appears that after a few hours the process is hung however it appears to just be very sluggish and slow taking several minutes to respond to any input.

![image](https://user-images.githubusercontent.com/2158650/62903737-f5aefd80-bd20-11e9-9115-cc7433bf1797.png)
and a few minutes later
![image](https://user-images.githubusercontent.com/2158650/62903891-6bb36480-bd21-11e9-90c1-9339f2815ee1.png)
and now after about an hour and a half
![image](https://user-images.githubusercontent.com/2158650/62904934-87206e80-bd25-11e9-9e1e-a830f5db42a8.png)

Not sure if the goroutines are supposed to keep increasing like that?

Then after leaving it running overnight, I come back to a TLS errors in the console, and a completely hung process.

![image](https://user-images.githubusercontent.com/2158650/62949310-33ed0100-bda3-11e9-93f7-11ec3872a890.png)

**Comment by mlinton** [comment]
Possible update and cause: 

It looks like when I start the process with http-ui instead of https-ui I don't get the same performance issues.  Could this be somehow related to the https processing in the UI?  I'll let it run overnight and see if the issue manifests again with only http.

**Comment by mlinton** [comment]
I'm still getting other performance issues with long-term runs.  Is there someone else with rpi0w hardware that can try to reproduce this?

**Comment by evilsocket** [comment]
it's related to https as you said, do you have the same issue if using the http ui instead?

**Comment by mlinton** [comment]
After leaving it overnight with just the http-ui instead of https-ui running, no lockups and appears to be running fine still.  Seems like it must be something with the https-ui on the rpizero.  Any ideas?

**Comment by evilsocket** [comment]
yes, it's the encryption related to HTTPS ... remember that the rpi0 has just one single CPU core and encryption is a relatively heavy operation on it :) Each time the API is polled (at least each second, more often if possible) the CPU spikes to 100% and stays there until the keys exchange is done, if lots of connections over time end up being queued like this, eventually the API will stop responding and the CPU will be always near 100%.

**Comment by mlinton** [comment]
So is the fact that the UI creates more connections over time the culprit?  It seems to start off working fine, then degrades over time.  Maybe there is a way to clean up the API connections?

**Comment by evilsocket** [comment]
Yep, that's the reason ... and I'm afraid there's no way to clean that up, if they get queued because TLS is taking CPU time to execute, the only way to work around that is either decreasing considerably the polling time of the UI ( https://github.com/bettercap/ui/blob/master/src/app/services/api.service.ts#L25 ), which would make it update waaaaay slower, or just use HTTP ...

**Comment by mlinton** [comment]
HTTP it is!  I also made a few modifications to a Raspbian installation to help free up resources including disabling services (avahi, bluetooth, alsa, hcitools, etc).  Would love to help test out the beta version.
