### ISSUE TITLE
dns.spoof.address can't use ports

### ISSUE THREAD

**Issue by Hand-Lock** [bettercap/bettercap#609]
bettercap v2.23
kali linux 2019.2

reproduce:
setup arp.spoof
set a dns.spoof.address with a port (ex. 0.0.0.0:4000)
enable dns.spoof

error:
Parameter dns.spoof.address not valid: '0.0.0.0:4000' does not match rule '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'.

**Comment by baconwaifu** [comment]
Expected behavior. DNS does not touch ports, it is a simple name lookup only.

A way to accomplish something similar would be to spoof the entire host, and then proxy the resulting connections to the real server uninterrupted if it's not a port you're interested in.
