### ISSUE TITLE
wifi.* are untested and probably buggy on macOS

### ISSUE THREAD

**Issue by evilsocket** [bettercap/bettercap#61]
Despite the `wifi.recon` and `wifi.deauth` modules support macOS, they have not been tested as I have no idea if it is even possible to have a wifi interface in monitor mode with packet injection on this platform.

[This](https://github.com/evilsocket/bettercap-ng/blob/master/network/net_darwin.go#L35) is what put the wifi card on a specifc channel and everything else is managed by [this](https://github.com/evilsocket/bettercap-ng/blob/master/modules/wifi_recon.go) for every platform.

**Comment by alexmozzhakov** [comment]
`wifi.recon` detects network and `wifi.deauth` deauthes users as expected. Some networks are shown as <hidden>. I can finally do it while connected to the internet. Well done!

**Comment by evilsocket** [comment]
wow that's way better than expected :D will check the unicode issue, thanks!

**Comment by evilsocket** [comment]
it should be fixed with https://github.com/bettercap/bettercap/commit/38faff29d57e6d1ab5289dbd890fb5fe4b8bb338

**Comment by evilsocket** [comment]
ops nope, 1 sec

**Comment by evilsocket** [comment]
it should be fixed ow

**Comment by alexmozzhakov** [comment]
I still got `Sweex LW0{0x0f}^1� `. Sorry for not being able to clearly test it and identify the actual name.
Also, got this warning while updating `go/src/github.com/bettercap/bettercap/network/wifi_station.go:4:2: imported and not used: "fmt"`

**Comment by evilsocket** [comment]
my bad, try again now :)

**Comment by evilsocket** [comment]
**NOTE** I see some duplicates ESSID with slightly different BSSIDs ... I think this is not a bug of bettercap but some bug in how macOS is handling error correction with the WiFi card in monitor mode. Also, as those bogus packets are just seen once, after a while the duplicates disappear so it's not a big deal.

**Comment by alexmozzhakov** [comment]
@evilsocket I don't know about the bug, can you give me a link with an explanation? The bug is very unpleasant since the table becomes too long because of {0xXX} chars and question marks, so an output is very hard to understand.  The bogus packets appear all the time with every network available, and it takes some time for them to disappear. Also, sometimes correct network names also disappear.

**Comment by evilsocket** [comment]
did you pull the repo and recompile dude? because that was fixed a few commits ago

**Comment by alexmozzhakov** [comment]
I've tried checking 802.11 probes with wireshark and got some of them as [malformed packet] by checking "frame check sequence"

**Comment by alexmozzhakov** [comment]
@evilsocket of course I did.

**Comment by alexmozzhakov** [comment]
OK, I've updated it again and I don't see any problems as for now. I'll let it run for a couple of hours just to be sure, but as for now, you may close an issue.

**Comment by evilsocket** [comment]
Maybe I can do even better ;)

**Comment by evilsocket** [comment]
@alexmozzhakov pull now and try, thanks to your hint about frame check sequence it's waaaay better now :D

**Comment by evilsocket** [comment]
i say we can close this ^_^
