### ISSUE TITLE
Nexus 6p: bettercap seem to work on wlan1 only

### ISSUE THREAD

**Issue by gagna** [bettercap/bettercap#613]
After some trouble I finally installed NetHunter on my Nexus 6p running Android Nougat 7.1.1, it was a pain but now it works.

Why would I want this to work? Because Nexmon firmware also works alone without Kali NetHunter, on stock rom according to their GitHub project page, it also support packet injection on Oreo.

If i can use bettercap on android I won't need NetHunter, you can make a nice stealth setup without external adapter.

Thanks to Nexmon firmware, monitor mode also works on wlan0, but only outside the NetHunter chroot enviroment. I installed the nexmon firmware with Hijacker app

I downloaded the precompiled android binary and put it inside `/su/xbin` 

### Environment

* Bettercap version 2.24.1
* Android 7.1.1 Nougat stock + NetHunter chroot enviroment
* precompiled binary copied inside `/su/xbin`
* `su` then `bettercap -iface wlan0`
* No caplet used

### wlan0

`bettercap -iface wlan0 `

It start correctly but after `wifi.recon on` it throw an error:

`[00:00:00] [sys.log] [err] error while activating handle: unknow activated error: -6`

**Full debug output** 
```
bettercap v2.24.1 (built for android arm64 with go1.12.7) [type 'help' for a list of commands]

 wlan0  » [16:16:17] [sys.log] [dbg] Could not find mac for 192.168.168.1
 wlan0  » [16:16:17] [session.started] {session.started 2019-08-23 16:16:17.073524498 +0000 UTC m=+0.101543501 <nil>}
 wlan0  » [16:16:17] [mod.started] events.stream
 wlan0  » wifi.recon on
[16:17:09] [sys.log] [inf] wifi using interface wlan0 (24:df:6a:34:02:d9)
[16:17:09] [sys.log] [dbg] wifi interface wlan0 txpower set to 30
 wlan0  » [16:17:10] [sys.log] [err] error while activating handle: unknown activated error: -6
 wlan0  »
```

### wlan1

I was able to set wlan1 (ext. usb AWUS36NHA) in monitor mode.

The external `wlan1 `card works, I was able to deauth client from AP but when bettercap try the save *.pcap inside the root folder it throw an error because that folder is write-only

`[00:00:00] [sys.log] [err] wifi error while saving handshake frames to /bettercap-wifi-handshakes.pcap: open /bettercap-wifi-handshakes.pcap: read-only file system`

Any workaround for this?

**Comment by evilsocket** [comment]
for nexmon: did you try to run the `monstart` command first? that should create a monitor interface from wlan0, but wlan0 must not be used by other processes ... i have no idea how this works in android.

for the handshakes: you can `set wifi.handshakes.file /whatever/you/want.pcap` before `wifi.recon on` .

[RTFM!](https://www.bettercap.org/modules/wifi/)
