### ISSUE TITLE
Alfa AWUS036ACH: error while activating handle: unknown activated error

### ISSUE THREAD

**Issue by schrodyn** [bettercap/bettercap#614]
# Problem Description
Testing a USB Alfa AC1200 (AWUS036ACH) with bettercap. When executing `wifi.recon on` I receive the following error:

```
 wlxXXXXXXXXXXXX  » wifi.recon on
[21:35:43] [sys.log] [inf] wifi using interface wlxXXXXXXXXXXXX (00:XX:XX:XX:XX:XX)
[21:35:43] [sys.log] [war] wifi could not set interface wlxXXXXXXXXXXXX txpower to 30, 'Set Tx Power' requests not supported
[21:35:43] [sys.log] [err] error while activating handle: unknown activated error: -1
 wlxXXXXXXXXXXXX  »  
```

### Environment
```
bettercap v2.24.1 (built for linux amd64 with go1.10.4)
```
```
# iwconfig wlxXXXXXXXXXXXX
wlxXXXXXXXXXXXX  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency=2.452 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
Linux sapientia 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
```
Wireless card drivers built and installed using dkms method from https://github.com/aircrack-ng/rtl8812au
```
bettercap -debug -iface wlxXXXXXXXXXXXX
bettercap v2.24.1 (built for linux amd64 with go1.10.4) [type 'help' for a list of commands]

 wlxXXXXXXXXXXXX  » [21:42:51] [sys.log] [dbg] FindGateway(wlxXXXXXXXXXXXX) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
 wlxXXXXXXXXXXXX  » [21:42:51] [sys.log] [dbg] FindGateway(wlxXXXXXXXXXXXX) output:
default via 192.68.0.1 dev wlp3s0 
default dev enp0s25 scope link metric 1002 linkdown 
169.254.0.0/16 dev enp0s25 proto kernel scope link src 169.254.9.111 linkdown 
192.168.0.0/24 dev wlp3s0 proto kernel scope link src 192.168.0.10 
192.168.72.0/24 dev vmnet8 proto kernel scope link src 192.168.72.1 
192.168.228.0/24 dev vmnet1 proto kernel scope link src 192.168.228.1
 wlxXXXXXXXXXXXX  » [21:42:51] [sys.log] [dbg] FindGateway(wlxXXXXXXXXXXXX): nothing found :/
 wlxXXXXXXXXXXXX  » [21:42:51] [sys.log] [dbg] Could not detect gateway.
 wlxXXXXXXXXXXXX  » [21:42:53] [session.started] {session.started 2019-08-24 21:42:53.817373034 +0100 IST m=+2.014107730 <nil>}
 wlxXXXXXXXXXXXX  » [21:42:53] [mod.started] events.stream
 wlxXXXXXXXXXXXX  » wifi.recon on
[21:43:02] [sys.log] [inf] wifi using interface wlxXXXXXXXXXXXX (xx:xx:xx:xx:xx:xx)
[21:43:02] [sys.log] [war] wifi could not set interface wlxXXXXXXXXXXXX txpower to 30, 'Set Tx Power' requests not supported
[21:43:02] [sys.log] [err] error while activating handle: unknown activated error: -1
 wlxXXXXXXXXXXXX  »  
```
### Steps to Reproduce

1. bettercap -debug -iface wlxXXXXXXXXXXXX
2. wifi.recon on

**Comment by gagna** [comment]
Have you launched the command with administrator privileges?

**Comment by schrodyn** [comment]
Yes, running as root.

```
# id
uid=0(root) gid=0(root) groups=0(root)
# iwconfig
wlxXXXXXXXXXXXX  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated
          Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
# iw dev wlxXXXXXXXXXXXX set type monitor
# ./bettercap -iface wlxXXXXXXXXXXXX
bettercap v2.24.1 (built for linux amd64 with go1.10.4) [type 'help' for a list of commands]

 wlxXXXXXXXXXXXX  » wifi.recon on
[18:50:24] [sys.log] [inf] wifi using interface wlxXXXXXXXXXXXX (xx:xx:xx:xx:xx:xx)
[18:50:24] [sys.log] [war] wifi could not set interface wlxXXXXXXXXXXXX txpower to 30, 'Set Tx Power' requests not supported
[18:50:25] [sys.log] [err] error while activating handle: unknown activated error: -1
 wlxXXXXXXXXXXXX  » quit
```

**Comment by rulzgz** [comment]
I have the same issue with the same adapter but different kernel and distro:
```
~ iwconfig wlp0s20f0u3 
wlp0s20f0u3  IEEE 802.11b  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency:2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

~ uname -a
Linux theden 4.14.138-1-MANJARO #1 SMP PREEMPT Fri Aug 9 19:03:55 UTC 2019 x86_64 GNU/Linux

~ cat /etc/lsb-release    
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```
The issue appears even with the adapter already in monitor mode and txpower configured.

**Comment by victorhooi** [comment]
I seem to be having the same issue on a Raspberry Pi 3+, with a AWUS036ACH adapter as well.

I am testing with the [rtl8812au driver here](https://github.com/aircrack-ng/rtl8812au).

I launch betttercap as so:
```
$ sudo bettercap -iface wlan1
bettercap v2.24.1 (built for linux arm with go1.11.6) [type 'help' for a list of commands]
```

When I try to execute any wireless commands with this card, I get the error:
```
 wlan1  » wifi.recon on
[02:51:10] [sys.log] [inf] wifi using interface wlan1 (00:c0:ca:8f:00:b2)
[02:51:10] [sys.log] [war] wifi could not set interface wlan1 txpower to 30, 'Set Tx Power' requests not supported
 wlan1  » [02:51:10] [sys.log] [err] error while activating handle: unknown activated error: -1
```

**Comment by JimWas** [comment]
Same issue using the rtl8812au driver here.

 wlan0  » wifi.recon on 
 wlan0  » [23:05:31] [sys.log] [inf] wifi using interface wlan0 (xx:xx:xx:xx:xx:xx)
 wlan0  » [23:05:31] [sys.log] [war] wifi could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported
 wlan0  » [23:05:31] [sys.log] [err] error while activating handle: unknown activated error: -1

**Comment by evilsocket** [comment]
can you guys just have the interface -not- in monitor mode and then just let bettercap put it in monitor mode?

**Comment by rulzgz** [comment]
I started bettercap with interface in mode auto:

`~ $ iwconfig wlp0s20f0u3
...
wlp0s20f0u3  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

~ $ sudo docker run -it --privileged --net=host bettercap/bettercap -iface wlp0s20f0u3

bettercap v2.24 (built for linux amd64 with go1.12.4) [type 'help' for a list of commands]

 wlp0s20f0u3  » wifi.recon on
[15:19:34] [sys.log] [inf] wifi using interface wlp0s20f0u3 (b6:62:c4:d0:24:e2)
[15:19:34] [sys.log] [war] wifi could not set interface wlp0s20f0u3 txpower to 30, 'Set Tx Power' requests not supported
 wlp0s20f0u3  » [15:19:34] [sys.log] [err] error while activating handle: unknown activated error: -1
`

There's no difference for me, still got the same messages.

**Comment by JimWas** [comment]
> I started bettercap with interface in mode auto:
> 
> ```
> ~ $ iwconfig wlp0s20f0u3
> ...
> wlp0s20f0u3  unassociated  Nickname:"<WIFI@REALTEK>"
>           Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
>           Sensitivity:0/0  
>           Retry:off   RTS thr:off   Fragment thr:off
>           Power Management:off
>           Link Quality:0  Signal level:0  Noise level:0
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:0   Missed beacon:0
> 
> ~ $ sudo docker run -it --privileged --net=host bettercap/bettercap -iface wlp0s20f0u3
> 
> bettercap v2.24 (built for linux amd64 with go1.12.4) [type 'help' for a list of commands]
> 
>  wlp0s20f0u3  » wifi.recon on
> [15:19:34] [sys.log] [inf] wifi using interface wlp0s20f0u3 (b6:62:c4:d0:24:e2)
> [15:19:34] [sys.log] [war] wifi could not set interface wlp0s20f0u3 txpower to 30, 'Set Tx Power' requests not supported
>  wlp0s20f0u3  » [15:19:34] [sys.log] [err] error while activating handle: unknown activated error: -1
> ```
> 
> There's no difference for me, still got the same messages.

Yes, the same for me. Exact same error message regardless if monitor mode is enabled or not before running.

**Comment by evilsocket** [comment]
does the interface work with other tools (airodump-ng)?

**Comment by JimWas** [comment]
> does the interface work with other tools (airodump-ng)?

Monitor mode works fine in other apps like wifite, airodump.

**Comment by schrodyn** [comment]
Just to confirm, since I opened this issue, the same applies to me. Can put the interface into monitor mode with `iw dev wlx00xxxxxxxxxx set type monitor` and dump happily with airodump-ng. I have an issues with airmon-ng but renaming the interface resolves that, seems related to a bug in airmon-ng with long interface names

**Comment by HarterHorst** [comment]
Same here. I have just upgraded 88XXau from Version v5.2.20.2_28373.20180619 to v5.6.4.1_33916.20190619 from [here](https://github.com/aircrack-ng/rtl8812au) using DKMS and I get the same message. airmon-ng and airodmp-ng work fine. With the old driver everyhing was fine. 

modinfo 88XXau partly:
``` filename:       /lib/modules/5.2.0-kali2-amd64/updates/88XXau.ko
version:        v5.6.4.1_33916.20190619
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
```

```wlan0     unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
starting bettercap...

```root@kali:/# bettercap -iface wlan0
bettercap v2.24.1 (built for linux amd64 with go1.13) [type 'help' for a list of commands]

 wlan0  » wifi.recon on
[17:58:47] [sys.log] [inf] wifi using interface wlan0 (32:b7:92:0d:0a:fb)
[17:58:47] [sys.log] [war] wifi could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported
 wlan0  » [17:58:47] [sys.log] [err] error while activating handle: unknown activated error: -1
 wlan0  »  
```

```
root@kali:/# uname -a
Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux
```

**Comment by FireFart** [comment]
I changed the `gopacket` code to also display the detailed error message when an activate error occurs here https://github.com/google/gopacket/pull/718

When adding this to the bettercap code on master the nested error message is now:
```text
[err] error while activating handle: Error: wlan0: SIOCGIWPRIV: Argument list too long
```

I hope this patch helps to track down this issue as I'm also currently having the same issue with the rtl8812au driver (from the v5.6.4.1 branch)

**Comment by er4z0r** [comment]
Has anybody managed to get this working in the meantime?
I am having the same issue:

```
wlp0s20f0u1  » wifi.recon on
[16:54:00] [sys.log] [inf] wifi using interface wlp0s20f0u1 (00:c0:ca:xx:xx:xx)
[16:54:00] [sys.log] [war] wifi could not set interface wlp0s20f0u1 txpower to 30, 'Set Tx Power' requests not supported
[16:54:00] [sys.log] [err] error while activating handle: unknown activated error: -1
```
OS: `Linux pwnbx 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux`
Package:
`aur/rtl88xxau-aircrack-dkms-git r672.2c3ce70-1`

/sys/kernel/debug/usb/devices

```
T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  8 Spd=480  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=0bda ProdID=8812 Rev= 0.00
S:  Manufacturer=Realtek
S:  Product=802.11n NIC
S:  SerialNumber=123456
C:* #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=500mA
I:* If#= 0 Alt= 0 #EPs= 5 Cls=ff(vend.) Sub=ff Prot=ff Driver=rtl88xxau
E:  Ad=81(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=02(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=03(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=04(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=85(I) Atr=03(Int.) MxPS=  64 Ivl=125us
```

**Comment by evilsocket** [comment]
anybody tried this https://twitter.com/Sec_GroundZero/status/1193521307519987712 ?

**Comment by HarterHorst** [comment]
Yap, works for me. Just have updated the 88XXau driver from [here](https://github.com/aircrack-ng/rtl8812au) to Version 5.6.4.2. and bettercap to v2.26.1 and everything seems to be ok. No error messages regarding "Set Tx Power" nor "error activating handle"

**Comment by evilsocket** [comment]
Nice, then we can close this :D

**Comment by azamet90** [comment]
same problem still exist here on kali i did installed the driver from aircrack but same :/

> Nice, then we can close this :D

**Comment by Kalagan76** [comment]
Hi, i meet this issue too. I have the last version of Bettercap and version 5.6.4.2 of the drivers. Anyway, i have the same message about TX power when i type "wifi.recon on".

I'm running Kali linux in virtualbox and i notice that, despite that the wireless adapter works in monitor mode an packets injection, the name never changes from wlan0 to wlan0mon (when running airmon-ng, etc...)? Could it be an issue?

**Comment by azamet90** [comment]
> Hi, i meet this issue too. I have the last version of Bettercap and version 5.6.4.2 of the drivers. Anyway, i have the same message about TX power when i type "wifi.recon on".
> 
> I'm running Kali linux in virtualbox and i notice that, despite that the wireless adapter works in monitor mode an packets injection, the name never changes from wlan0 to wlan0mon (when running airmon-ng, etc...)? Could it be an issue?

Because of the developer from bettercap must change from ifconfig to iw for txpower because of the developer from the alfa driver change it from iwconfig to iw too so until bettercap is updated will not work with alfa

**Comment by azamet90** [comment]
> > Hi, i meet this issue too. I have the last version of Bettercap and version 5.6.4.2 of the drivers. Anyway, i have the same message about TX power when i type "wifi.recon on".
> > I'm running Kali linux in virtualbox and i notice that, despite that the wireless adapter works in monitor mode an packets injection, the name never changes from wlan0 to wlan0mon (when running airmon-ng, etc...)? Could it be an issue?
> 
> Because of the developer from bettercap must change from ifconfig to iw for txpower because of the developer from the alfa driver change it from iwconfig to iw too so until bettercap is updated will not work with alfa

https://github.com/aircrack-ng/rtl8812au/issues/476#issuecomment-554730278
Same aksi what airgeddon developer is doing must hım do too check this topic

**Comment by evilsocket** [comment]
`iw wlan0 set type managed` doesn't make much sense to put the interface in monitor mode ... i'm confused ...

**Comment by evilsocket** [comment]
@azamet90 also, bettercap doesn't use neither ifconfig nor iw to set the interface in monitor mode, but a call to libpcap via Gopacket

**Comment by azamet90** [comment]
> @azamet90 also, bettercap doesn't use neither ifconfig nor iw to set the interface in monitor mode, but a call to libpcap via Gopacket

also on my intel wifi i dont have this txpower problem my internal wifi does not support more then 20 dbm tx power but it not giving any error like that but on alfa it does but on web-gui mode it is not giving any error

**Comment by azamet90** [comment]
> @azamet90 also, bettercap doesn't use neither ifconfig nor iw to set the interface in monitor mode, but a call to libpcap via Gopacket

also on my intel wifi i dont have this txpower problem my internal wifi does not support more then 20 dbm tx power but it not giving any error like that but on alfa it does but on web-gui mode it is not giving any error

and also i cannot detect bluetooth devices and wifi.recon on not shows the hostnames connected to wifi and also it works with net.probe on ... these things happens on internal wifi which it shouldnt do that

**Comment by OscarAkaElvis** [comment]
All we say at that comment (https://github.com/aircrack-ng/rtl8812au/issues/476#issuecomment-554730278) is that for the next airgeddon version the use of iwconfig and ifconfig will be removed. All related actions will be done using ip and iw commands... that's all. To set monitor mode instead of iwconfig stuff we can use `iw wlan0 set monitor control` and to set again managed mode this command can be used `iw wlan0 set type managed`. I think airgeddon is not related too much with this, just clarifying.

**Comment by its0x08** [comment]
I simply turn off the wifi in kali settings or by using ifdown wlan0 then i run bettercap
That error is when wlan0 is being used by the OS and bettercap at the same time 
So OS  has it hooked meaning bettercap is the second to hook same interface. And thats a conflict so bettercap simply doest work if the interface is up and running 
At least for me!!

**Comment by uamithril** [comment]
> anybody tried this https://twitter.com/Sec_GroundZero/status/1193521307519987712 ?

works for me, on virtual machine
`Linux kaliVirtual 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux`
via switch to branch v5.2.20

then
`make`
`make install`
`sudo reboot`
After reboot i check if `wlan0` shows via
`ifconfig`
yes, and then:
`airmon-ng check kill`
`sudo ip link set wlan0 down`
`sudo iw dev wlan0 set type monitor`
`sudo ip link set wlan0 up`
All works!

**Comment by nazariyv** [comment]
Having same issue on Alfa AWUS036ACH and Kali, running bettercap in docker. Will try some of the solutions above to remedy. What is interesting is that bettercap worked flawlessly on the first time around, but after I installed the http-ui which causes caplets to be overriden, it stopped working. Don't know if it is related though.

**Comment by nazariyv** [comment]
Here is my debug log after I switch on wifi.recon.

<img width="779" alt="Screenshot 2020-05-22 at 22 57 36" src="https://user-images.githubusercontent.com/13678461/82712363-b6361a00-9c7f-11ea-9cea-6ed45780d954.png">

**Comment by nazariyv** [comment]
And when I follow the steps here to install 5.2.20 and reach the final step where I am manually setting tx power, I get this:

```
$ iwconfig wlan0 txpower30
Error for wireless request  "Set Tx Power" (8826) :
   SET failed on device wlan0 ; Operation not permitted
```

**Comment by nazariyv** [comment]
following steps outlined by @uamithril fixed evertyhing. thx!
