### ISSUE TITLE
getting empty APS / CLient list in REST after a few hours 

### ISSUE THREAD

**Issue by moshehoorialgo** [bettercap/bettercap#620]
getting an empty json in the REST API after a few hours of activity.

`{"aps":[]}`

### Environment

Please provide:

* bettercap v2.24.1 (built for linux arm64 with go1.11.6)
* Linux kali 4.19.55-Re4son-v8+ #1 SMP PREEMPT Sun Jun 30 10:40:44 UTC 2019 aarch64 GNU/Linux
* initial command line arguments:
```
 wifi.recon on 
ble.recon on
net.probe on
net.recon on
api.rest on 

```
* ** Debug log is attached

### Steps to Reproduce

1. run : `monstart `
2. `/usr/bin/bettercap -debug -iface wlan0mon < /root/program/bacap.commands`
where bacap.commands contains the commands above.
3. wait a few hours ( rest API works correctly at this point )
4. run `curl http://127.0.0.1:8081/api/session/wifi` 

**Expected behavior:** 
get all APS and client list.

**Actual behavior:** *What actually happened*
i got  `{"aps":[]}`
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
not a bettercap bug (conversation here https://twitter.com/evilsocket/status/1170631160197779457)
