### ISSUE TITLE
how to fix ? (math/bits)

### ISSUE THREAD

**Issue by CLOY0** [bettercap/bettercap#626]
root@debian:~/go/src/github.com/bettercap/bettercap# make build
vendor/golang.org/x/sys/unix/affinity_linux.go:10:2: cannot find package "math/bits" in any of:
	/root/go/src/github.com/bettercap/bettercap/vendor/math/bits (vendor tree)
	/usr/local/go/src/math/bits (from $GOROOT)
	/root/go/src/math/bits (from $GOPATH)
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by yungtravla** [comment]
By following the [instructions](https://www.bettercap.org/installation/).

**Comment by CLOY0** [comment]
I followed these instructions.

Compiling from Sources
In order to compile bettercap from sources, make sure that:
    You have a correctly configured Go >= 1.8 environment.
    $GOPATH is defined and $GOPATH/bin is in $PATH.

You’ll also need to install the dependencies:

    build-essential
    libpcap-dev
    libusb-1.0-0-dev (required by the HID module)
    libnetfilter-queue-dev (on Linux only, required by the packet.proxy module)
Once you’ve met this conditions, you can run the following commands to compile and install bettercap in /usr/local/bin/bettercap:

go get github.com/bettercap/bettercap
cd $GOPATH/src/github.com/bettercap/bettercap
make build 
sudo make install

**Comment by yungtravla** [comment]
You have to follow the issue template which you deleted when you wrote this issue...
