### ISSUE TITLE
Bettercap eats all memory and dies

### ISSUE THREAD

**Issue by a9e78rauijasdf** [bettercap/bettercap#628]
So...uhm - running Bettercap 2.24.1 on Kubuntu 18.04.3 (4.15.0-64). Just running Bettercap on the CLI yields no input - looks like its hanging, but in reality its eating every single bit of available memory, ultimately causing the machine to crash.

Bettercap was downloaded as a binary, and did run just fine once. Had to reboot machine to recover from bettercap eating memory - it ate about 6gb memory.

I cant find files that perhaps was generated during last run of bettercap. Can reproduce this every time i run Bettercap.

**Comment by yungtravla** [comment]
You're gonna have to find some type of logs because we can't guess what's going on.

**Comment by a9e78rauijasdf** [comment]
Well...thanks for the help...  If I knew what relevant logs to attach, I would have done that, but as it doesnt log anything, and just hogs memory like I hog bacon, its a wee bit hard to attach anything that would matter. Any serious ideas as to what I could try and log?

Stracing the process didnt give me anything useful, but Im not an expert in decoding strace.

**Comment by yungtravla** [comment]
> Stracing the process didnt give me anything useful, but Im not an expert in decoding strace.

Can you attach the stack trace?

**Comment by yungtravla** [comment]
We can't help you because you haven't provided a shred of useful information. We don't know what modules you're using in bettercap, whether or not you're using a caplet, etc.

**Comment by a9e78rauijasdf** [comment]
I havent enabled any modules, and no caplets are active. This is the output:

# bettercap 
bettercap v2.24.1 (built for linux amd64 with go1.10.4) [type 'help' for a list of commands]

and then it just hangs there - hogging 2.5gb memory within seconds. What more information can I provide?

**Comment by a9e78rauijasdf** [comment]
I've upgraded to latest release again. I saw the exact same issue there. Decidede to purge my system of everything related to bettercap. After installing 2.25.1 and updating caplets - as per the instructions - it immediately ate memory again and eventually crashed the system. I suspect that there exists some bug in the caplet update feature, although it did work on second attempt. I've since tried to replicate the issue, but havent been able to. Bettercap runs like it should now.
Im sorry that I was not able to provide more information, but if I knew what to provide, it would be *a lot* easier to write a good bug report.... :)

**Comment by buffermet** [comment]
My hunch at first was a network/driver issue, but without logs we can't make guesses.

No worries, glad to hear that you no longer face this issue :)

**Comment by a9e78rauijasdf** [comment]
Reopening issue - it now resumes weird behavior. Just updated to 2.26.1. Restarted machine, ran bettercap as root. No bettercap prompt appears:
# bettercap
bettercap v2.26.1 (built for linux amd64 with go1.13.3) [type 'help' for a list of commands]

And it just hangs there, whilst eating juicy memory. I've tried starting it with -debug and -memprofile, but it doesnt write anything to file, nor print anything to screen.

# ldd /usr/local/bin/bettercap 
        linux-vdso.so.1 (0x00007ffe493aa000)
        libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f93da71f000)
        libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f93da507000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f93da303000)
        libnetfilter_queue.so.1 => /usr/lib/x86_64-linux-gnu/libnetfilter_queue.so.1 (0x00007f93da0fc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f93d9edd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f93d9aec000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f93d98ce000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f93da960000)
        libnfnetlink.so.0 => /usr/lib/x86_64-linux-gnu/libnfnetlink.so.0 (0x00007f93d96c7000)
        libmnl.so.0 => /lib/x86_64-linux-gnu/libmnl.so.0 (0x00007f93d94c1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f93d92b9000)

Strace attached - can anything be of use in debugging now?
[bettercap-strace.txt](https://github.com/bettercap/bettercap/files/3895928/bettercap-strace.txt)

**Comment by buffermet** [comment]
I see in your initial post that you are using a compiled binary. Have you tried installing bettercap from source?

**Comment by a9e78rauijasdf** [comment]
I've tried using sources, but the install fails. Here's a very recent output from the source install attempt:
$go version
go version go1.10.4 linux/amd64

I guess this version satiffies the requirement for a Go >= 1.8 ;)

$ echo $GOPATH
/home/username/go

$ echo PATH
/home/username/.local/bin:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/username/.rvm/bin:/home/username/.rvm/bin:/home/username/.rvm/bin:/home/username/.rvm/bin:/home/username/go

All dependencies are satisfied.

$ go get github.com/bettercap/bettercap
# github.com/google/gopacket/pcapgo
go/src/github.com/google/gopacket/pcapgo/capture.go:26:47: undefined: unix.TpacketAuxdata
go/src/github.com/google/gopacket/pcapgo/capture.go:87:13: undefined: unix.TpacketAuxdata
go/src/github.com/google/gopacket/pcapgo/capture.go:91:29: undefined: unix.TP_STATUS_VLAN_VALID
go/src/github.com/google/gopacket/pcapgo/capture.go:201:9: undefined: unix.SetsockoptSockFprog
go/src/github.com/google/gopacket/pcapgo/capture.go:226:9: undefined: unix.SetsockoptPacketMreq
go/src/github.com/google/gopacket/pcapgo/capture.go:230:36: undefined: unix.TpacketStats
go/src/github.com/google/gopacket/pcapgo/capture.go:231:9: undefined: unix.GetsockoptTpacketStats
# github.com/miekg/dns
go/src/github.com/miekg/dns/dnssec_keyscan.go:149:18: undefined: ed25519.SeedSize
go/src/github.com/miekg/dns/dnssec_keyscan.go:152:8: undefined: ed25519.NewKeyFromSeed
go/src/github.com/miekg/dns/dnssec_privkey.go:86:24: p.Seed undefined (type ed25519.PrivateKey has no field or method Seed)

This effectively prevents me from completing the manual install, hence my use of the binary package.

**Comment by buffermet** [comment]
What happens if you do `go get -u github.com/bettercap/bettercap`?

**Comment by a9e78rauijasdf** [comment]
I appended -v as well. It checks a load of URLs and return code is 0 - so all should be fine?
