### ISSUE TITLE
[Feature Request] Infect binaries via MITM

### ISSUE THREAD

**Issue by illiliti** [bettercap/bettercap#633]
It would be great to have something like peinjector or bdfproxy.

**Comment by buffermet** [comment]
This isn't what you're asking for, but it's a rough alternative that replaces binaries with your own and fills the rest with null bytes to keep the Content-Length identical.

What you're asking for is a much stealthier process where the client does not notice any change in the binary.

I'll put this on my to-do list until I get more time or someone beats me to it ;)
