### ISSUE TITLE
Won't detect any wifi interface besides enp3s0 even with -iface

### ISSUE THREAD

**Issue by TheRedSpy15** [bettercap/bettercap#636]
When I open the web ui, and go to Wifi. The only interface listed is enp3s0. Of which is even a wifi interface. The onboard and usb adapter interfaces are not listed. Even when confirmed they exist with ifconfig, and specified with -iface

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). **2.25**
* OS version and architecture you are using. **64-bit Ubuntu 19.04**
* Go version if building from sources. **N/A**
* Command line arguments you are using. **-caplet http-ui -iface wlp2s0**
* Caplet code you are using or the interactive session commands. **http-ui**
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
```
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [sys.log] [dbg] FindGateway(wlp2s0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [sys.log] [dbg] FindGateway(wlp2s0) output:
default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600 
169.254.0.0/16 dev docker0 scope link metric 1000 linkdown 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.0.0/24 dev wlp2s0 proto kernel scope link src 192.168.0.31 metric 600
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [sys.log] [dbg] FindGateway(wlp2s0) line 'default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600 default 192.168.0.1 wlp2s0]
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [sys.log] [dbg] gateway is 192.168.0.1[3c:37:86:e8:cb:82]
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [session.started] {session.started 2019-10-11 14:32:39.99339705 -0400 EDT m=+0.096579757 <nil>}
192.168.0.0/24 > 192.168.0.31  » [14:32:39] [mod.started] events.stream
```
### Steps to Reproduce

1. run precompiled bettercap (./bettercap)
2. with -iface wlp2s0 (confirmed it exists with ifconfig)
3. open web ui, to see only enp3s0 is list under wifi interfaces

**Expected behavior:** see wlp2s0 already selected, or at least be listed in the web ui

**Actual behavior:** only enp3s0 is listed

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by a9e78rauijasdf** [comment]
Whats the output of iwconfig and "rfkill list" ?

**Comment by hokuco** [comment]
I am also having this problem if it helps. 
Ubuntu 19.10
with 0iface wlp2s0
opened webui, only let me use en01

**Comment by buffermet** [comment]
I'm not sure I understand the problem here. 

Note that there is a separate `wifi.interface` variable that will set the assigned interface in monitor mode when using `wifi.recon`. This is not the same as the assigned `net.recon` interface using the `-iface` flag.

Are you trying to use interface A for net.recon and interface B for wifi.recon? Can't you just swap them around?

Perhaps you are asking for a way to swap the `net.recon` and the `wifi.recon` interfaces using the web ui?

If you want to switch between 2 interfaces you could assign the loopback interface (if you don't need net.recon).

**Comment by TheRedSpy15** [comment]
@a9e78rauijasdf 
```
0: ideapad_wlan: Wireless LAN
        Soft blocked: no
        Hard blocked: no
1: ideapad_bluetooth: Bluetooth
        Soft blocked: no
        Hard blocked: no
2: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
24: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
25: phy1: Wireless LAN
        Soft blocked: no
        Hard blocked: no
```

**Comment by buffermet** [comment]
Simply enabling `wifi.recon` will use the `net.recon` interface that you specified using the `-iface`. If you want to use a different interface, you assign it to `wifi.interface` variable. Please read the docs.

**Comment by patvdleer** [comment]
@TheRedSpy15  I think the issue @TheRedSpy15 is having is due to the network manager "claiming" the interface, I can only use the interface (either all or none) in Bettercap when I disable/turnoff wireless in the network manager of Ubuntu itself.
