### ISSUE TITLE
Is it possible to inject JS into routers webpage?

### ISSUE THREAD

**Issue by Dieter44** [bettercap/bettercap#638]
Please provide:
* Bettercap version:  v2.25
* OS:   linux arm on a raspberry pi
* Go version:  1.13.1

I successfully injected a js script into http pages with http.proxy but it does not work with the login page of my router (http://fritz.box). How can I inject something into the login page of the router or is that impossible with bettercap?

And if it is no possible: Can I redirect the http request to my own fake login server?

Thanks

**Comment by buffermet** [comment]
You sure can. If the router does not have ARP spoofing protection you can use the builtin ARP spoofer to proxy HTTP requests for the gateway IP.
