### ISSUE TITLE
Bettercap doesn't run on termux/Android q. returns wlan0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Unknown error 524

### ISSUE THREAD

**Issue by AngelouDi** [bettercap/bettercap#642]
### Environment

* Bettercap v2.25
* Android Q. SuperiorOs 3.0 unofficial. ARM64.
* Command: bettercap

***Full debug output** 

bettercap v2.25 (built for android arm64 with go1.13.1) [type 'help' for a list of commands]

wlan0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Unknown error 524

### Steps to Reproduce

1. Run termux
2. tsu
3. bettercap

**Expected behavior:** 
Run bettercap

**Actual behavior:**
Returns

bettercap v2.25 (built for android arm64 with go1.13.1) [type 'help' for a list of commands]

wlan0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Unknown error 524
-- 

Extra info: Tshark doesn't run also:  Capturing on 'dummy0'
tshark: The capture session could not be initiated on interface 'dummy0' (You don't have permission to capture on that device).
Please check to make sure you have sufficient permissions.

On Debian and Debian derivatives such as Ubuntu, if you have installed Wireshark from a package, try running

    sudo dpkg-reconfigure wireshark-common

selecting "<Yes>" in response to the question

    Should non-superusers be able to capture packets?

adding yourself to the "wireshark" group by running

    sudo usermod -a -G wireshark {your username}

and then logging out and logging back in again.
0 packets captured

So could it be permission/compatibilty problem with the ROM or Android Q?

**Comment by baconwaifu** [comment]
you need CAP_NET_RAW to capture packets, and some root solutions don't give you that. What root are you using? (magisk, kingo, superSU, etc.)

**Comment by AngelouD** [comment]
I am running magisk 20.0

Some thing I noticed. Bettercap runs fine on mobile data.

**Comment by heywoodlh** [comment]
I know this is a few months old, but just for the record: 
@AngelouD to validate what @baconwaifu said, I am using SuperSU for root access on my Android (running LineageOS). I gave Termux root permissions and that fixed it for me.

For me I elevate to root from Termux and then run the Bettercap binary installed through Termux:

```bash
❯ su -
:/ # /data/data/com.termux/files/usr/bin/bettercap
bettercap v2.26.1 (built for android arm with go1.13.5) [type 'help' for a list of commands]

192.168.230.0/24 > 192.168.230.103  » 
```

If I don't elevate, I get the same error:

```bash
❯ bettercap
bettercap v2.26.1 (built for android arm with go1.13.5) [type 'help' for a list of commands]

socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Permission denied
```

Technically, with this approach I don't have to use Termux, I could just use the developer terminal emulator, but I prefer to use Termux.

**Comment by buffermet** [comment]
@heywoodlh you mention "the same error" yet I only see 1 error. Your logs show that bettercap found the gateway and everything seems to work fine when you run as root.

**Comment by buffermet** [comment]
@AngelouD what happens when you enter `tsu -p -c "$GOPATH/bin/bettercap"`

**Comment by heywoodlh** [comment]
@buffermet, I must not have been clear enough in my response. I was just chiming in to affirm that the problem doesn't occur when you properly elevate to root. I wasn't saying I was having an issue.

**Comment by buffermet** [comment]
@heywoodlh my bad, I didn't read your message properly.
