### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by rnsi** [bettercap/bettercap#649]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
bettercap v2.26.1 (built for linux arm with go1.13.1)
* OS version and architecture you are using.
Linux 4.19.66-Re4son+ #1 Sun Aug 18 13:42:02 AEST 2019 armv6l GNU/Linux
* Go version if building from sources.
* Command line arguments you are using.
bettercap -iface mon0
* Caplet code you are using or the interactive session commands.
set $ {by}{fw}{env.iface.name}{reset} {bold}» {reset}
set ticker.period 10
set ticker.commands wifi.deauth ff:ff:ff:ff:ff:ff
ifi.recon on
ticker on

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
[19:36:57] [sys.log] [err] wifi could not inject WiFi packet: send: Resource temporarily unavailable

### Steps to Reproduce

As noted in issue 569, https://github.com/bettercap/bettercap/issues/569 this is a limitation of the Raspberry Pi onboard hardware. Is there any way to suppress the 'Resource temporarily unavailable' lines? I'd like to log the output, but there's too many error lines and I think it will kill the sd card.

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by cyrus104** [comment]
@rnsi, did you figure this out. I get this same error on the latest version and I'm running it on an x86 computer with a supported ath9k.

**Comment by rnsi** [comment]
Sorry, no I did not. I've abandoned that project.
