### ISSUE TITLE
bettercap needs to be updated

### ISSUE THREAD

**Issue by azamet90** [bettercap/bettercap#657]
TX power control was added yesterday on alfa awus036ach driver 
https://github.com/aircrack-ng/rtl8812au/
 "iwconfig" is deprecated, so you have to use "iw"
Many tools have not migrated from "iwconfig" to "iw" and from "ifconfig" to "ip" yet. That's the issue.

can you please update your tool for it?

**Comment by Frituurpanda** [comment]
Thanks for the detailed explanation @evilsocket!
