### ISSUE TITLE
Error when trying to sniff https traffic with https.proxy on

### ISSUE THREAD

**Issue by julienh1** [bettercap/bettercap#664]
*Description of the bug or feature request*

I'm connected to a wifi network and I try to sniff https traffic. I enable https proxy module but it does not work and I only can sniff http traffic.

### Environment

* I use Bettercap 2.26.1 (built for Linux 386 with go1.13.1)
* I'm using Kali Linux Lite x86 
* I installed bettercap with an apt-get install bettercap.

* I run the following commands

net.probe on
net.show
set arp.spoof.fullduplex true
set arp.spoof.targets IP
arp.spoof on
set http.proxy.sslstrip true
http.proxy on
set https.proxy.sslstrip true
https.proxy on
set net.sniff.verbose true
net.sniff on

* I have the error message when I write https.proxy on

[Https.proxy] loading proxy certification authority TLS key from /root/.bettercap-ca.key.pem
[Https.proxy] loading proxy certification authority TLS key from /root/.bettercap-ca.cert.pem
[err] tls: failed to find any PEM data in certificate input

### Steps to Reproduce

Run bettercap, set arp spoofing, set http proxy, set https proxy

**Expected behavior:** *sniffing https traffic and display domain names sniffed*

**Actual behavior:** *only sniff http traffic, error message for https.proxy*

--

**Comment by buffermet** [comment]
https://www.google.com/search?q=what%20is%20https
