### ISSUE TITLE
ALFA AWUS1900 Kali linux 2019.4

### ISSUE THREAD

**Issue by HachimanSec** [bettercap/bettercap#666]
---

Hello everyone, 
maybe someone has an idea about the problem here. I was reading all the forums and docs, but I dont really get it. Especially as most people remark that it should work out of the box with the default dkms driver. 

I am running Kali 2019.4 rolling release (`5.3.0-kali2-amd64`) in VirtualBox `6.0.14 r133895 (Qt5.6.3) `with an Alfa AWUS1900 WiFi adapter (the USB host in VirtualBox is set to USB3.0).

Installing the default driver (`apt install realtek-rtl88xxau-dkms`) doesnt make the WiFi adapter work. 
I reverted to the aircrack-ng driver set ([https://github.com/aircrack-ng/rtl8812au](https://github.com/aircrack-ng/rtl8812au)). 

Now the adapter works:
```
> lsusb
Bus 002 Device 002: ID 0bda:8813 Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac Wireless Adapter

> iwconfig 
eth0      no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency=5.54 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
When I start bettercap (`bettercap -iface wlan0 -caplet https-ui`) I cant start the WiFi module. 

It stops with an error that TX power cant be set (see screenshot). 
However setting it manually works:` iw wlan0 set txpower fixed 3000`

Kismet actually seems to work as well. 
<img width="1465" alt="Screenshot 2019-12-03 at 19 03 32" src="https://user-images.githubusercontent.com/20123996/70077635-7dd34e80-1601-11ea-9e97-91c92f12b0e1.png">
<img width="852" alt="Screenshot 2019-12-03 at 19 06 35" src="https://user-images.githubusercontent.com/20123996/70077637-7e6be500-1601-11ea-847a-fcc9271c0083.png">

### Environment

Please provide:

* bettercap v2.26.1 (built for linux amd64 with go1.13.4)
* Linux kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux
* go version go1.13.4 linux/amd64
* -iface wlan0 -caplet https-ui
* Caplet code you are using or the interactive session commands.
* **Full debug output** 
```
bettercap -debug -iface wlan0 -caplet https-ui
bettercap v2.26.1 (built for linux amd64 with go1.13.4) [type 'help' for a list of commands]

[19:19:05] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[19:19:05] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.1.1 dev eth0 proto dhcp metric 100 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.5 metric 100
[19:19:05] [session.started] {session.started 2019-12-03 19:19:05.397962949 +0100 CET m=+0.021996959 <nil>}
[19:19:05] [mod.started] events.stream
[19:19:05] [sys.log] [inf] api.rest loading TLS key from /root/.bettercap-https.key.pem
[19:19:05] [sys.log] [inf] api.rest loading TLS certificate from /root/.bettercap-https.cert.pem
[19:19:05] [sys.log] [inf] api.rest loading TLS key from /root/.bettercap-https.key.pem
[19:19:05] [sys.log] [inf] api.rest loading TLS certificate from /root/.bettercap-https.cert.pem
 wlan0  » [19:19:05] [sys.log] [inf] https.server loading server TLS key from /root/.bettercap-https.key.pem
 wlan0  » [19:19:05] [mod.started] api.rest
 wlan0  » [19:19:05] [sys.log] [inf] api.rest api server starting on https://0.0.0.0:8083
 wlan0  » [19:19:05] [mod.started] https.server
 wlan0  » [19:19:05] [sys.log] [inf] https.server loading server TLS certificate from /root/.bettercap-https.cert.pem
 wlan0  » [19:19:05] [sys.log] [inf] https.server starting on https://0.0.0.0:443
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/styles.92a454e3ed7c5bffbed3.css
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/runtime.26209474bfa8dc87a77c.js
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/polyfills.681b44b3f292a3819611.js
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/scripts.68228f7acaf48355d8cf.js
 wlan0  » [19:19:08] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/main.ec83a59338123ba3bb5d.js
 wlan0  » [19:19:09] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/assets/images/logo.png
 wlan0  » [19:19:09] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/fa-solid-900.fb4ea3247aace8c1c8bc.woff2
 wlan0  » [19:19:09] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/fa-brands-400.24a77b8baa5b34fb5081.woff2
 wlan0  » [19:19:09] [sys.log] [dbg] https.server 127.0.0.1 GET 0.0.0.0/fa-regular-400.34e0db45ef15f5a05814.woff2
 wlan0  » [19:19:19] [sys.log] [inf] wifi using interface wlan0 (fa:e6:36:f4:7d:3f)
 wlan0  » [19:19:19] [sys.log] [dbg] SetInterfaceTxPower(wlan0, 30) iw based
 wlan0  » [19:19:19] [sys.log] [war] wifi could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported
```

### Steps to Reproduce

1. Start bettercap with https-ui
2. Login to UI and navigate to WiFi module
3. Try to start WiFi module

**Expected behavior:** WiFi capture

**Actual behavior:** Error according to screenshot

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by HachimanSec** [comment]
Just found https://github.com/bettercap/bettercap/issues/232 and the recent comments about downgrading to:
https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20

Will try that.

**Comment by SilverMaple** [comment]
> Just found #232 and the recent comments about downgrading to:
> https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20
> 
> Will try that.

Did it work? I'm running into the same problem.

**Comment by keldnorman** [comment]
Bettercap should just be altered to use the iw util instead - is that hard to fix ?:

 iw wlan0 set txpower fixed 3000

**Comment by yrjo** [comment]
worked for me as well, discussed here:
https://github.com/bettercap/bettercap/issues/629
btw, its just workaround.

i believe that changing deprecate iwconfig to iw will help here:

> func SetInterfaceTxPower(name string, txpower int) error {
	if core.HasBinary("iwconfig") {
		if out, err := core.Exec("iwconfig", []string{name, "txpower", fmt.Sprintf("%d", txpower)}); err != nil {
			return err
		} else if out != "" {
			return fmt.Errorf("unexpected output while setting txpower to %d for interface %s: %s", txpower, name, out)
		}
	}
	return nil
}

**Comment by swapsakker** [comment]
> worked for me as well, discussed here:
> #629
> btw, its just workaround.
> 
> i believe that changing deprecate iwconfig to iw will help here:
> 
> > func SetInterfaceTxPower(name string, txpower int) error {
> > if core.HasBinary("iwconfig") {
> > if out, err := core.Exec("iwconfig", []string{name, "txpower", fmt.Sprintf("%d", txpower)}); err != nil {
> > return err
> > } else if out != "" {
> > return fmt.Errorf("unexpected output while setting txpower to %d for interface %s: %s", txpower, name, out)
> > }
> > }
> > return nil
> > }

Change it where, and anyone tried?

**Comment by fascinated** [comment]
> > Just found #232 and the recent comments about downgrading to:
> > https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20
> > Will try that.
> 
> Did it work? I'm running into the same problem.

I found that downgrading to the most current version of the 5.2.20 branch didn't work, but if you built a specific older commit, the problem went away. I built https://github.com/aircrack-ng/rtl8812au/tree/377c12c688c6777a4b39191f773c2ef5403958ef using kernel 4.15.0 and this issue was resolved.

**Comment by evilsocket** [comment]
use https://github.com/aircrack-ng/rtl8814au

**Comment by b3nj1-1** [comment]
# Install Driver Alfa AWUS1900 

Primero debemos instalar los encabezado esto se hace de manera manual, aqui les dejo el link de donde pueden descargarlos 
 https://http.kali.org/kali/pool/main/l/linux/.

Los paquetes que necesitamos va a depender de la version en mi caso tengo la:

5.10.0-kali9-amd64

Pueden ver la version con el comando ```uname -r```.

Los paquetes son:

* linux-headers-5.10.0-kali9-amd64_5.10.46-1kali1_amd64.deb
* linux-headers-5.10.0-kali9-common_5.10.46-1kali1_all.deb
* linux-kbuild-5.10_5.10.46-4kali1_amd64.deb

Los instalamos con el comando ```dpkg -i <Paquete>```

El orden de los paquetes es:

1 - linux-headers-5.10.0-kali9-common_5.10.46-1kali1_all.deb
2 - inux-kbuild-5.10_5.10.46-4kali1_amd64.deb
3 - linux-headers-5.10.0-kali9-amd64_5.10.46-1kali1_amd64.deb

Para descargar los paquetes podemos tirar de wget o directamente de la web
