### ISSUE TITLE
Golang and install old and daft

### ISSUE THREAD

**Issue by kevtheskin** [bettercap/bettercap#671]
Hello there, I have been trying to upgrade/install bettercap on my kali box using go and it just does not work. I clearly dont know what im doing . I havent a clue if go is installed and when I run cd $GOPATH/src/github.com/bettercap/bettercap  $ GOPATH/src/github.com/bettercap/bettercap
bash: GOPATH/src/github.com/bettercap/bettercap: No such file or directory.I have tried different ways to install go and add paths but just know :(
Please help Im just and auld brain trying to learn something new
Cheers Kev

**Comment by iamgoodbytes** [comment]
@kevtheskin can't you install via `apt-get install bettercap` and call it a day? Or is there a reason you are trying to build from source?

**Comment by buffermet** [comment]
Read the documentation... https://www.bettercap.org/installation/#linux-deploy-method
