### ISSUE TITLE
question

### ISSUE THREAD

**Issue by azamet90** [bettercap/bettercap#676]
how to use this jsinject/jsinject.js ? because of i get this error:
```
jsinject/jsinject /home/azamet/Masaüstü/beef-inject.js
192.168.43.0/24 > 192.168.43.39  » [11:53:35] [sys.log] [inf] net.sniff starting net.recon as a requirement for net.sniff
192.168.43.0/24 > 192.168.43.39  » [11:53:35] [sys.log] [err] open jsinject/jsinject.js: no such file or directory

```

the wiki is useless... only caplets how to use is listed but tons of commands is available

**Comment by buffermet** [comment]
Your question was already answered here: https://github.com/bettercap/bettercap/issues/290

Please don't post issues unless there is a bug or feature request/suggestion.

**Comment by azamet90** [comment]
> Your question was already answered here: #290
> 
> Please don't post issues unless there is a bug or feature request/suggestion.


i think you dont understand me :)
/home/azamet/Masaüstü/beef-inject.js this is my absolute path but what is the correct syntax?

**Comment by azamet90** [comment]
anyways; thanks for "not" helping :D

**Comment by buffermet** [comment]
I'm not gonna help you if you refuse to read the documentation and do what it says. You also don't write a complete issue, and the template clearly says those issues get closed immediately.

No one is going to waste their time on explaining how to use bettercap when there is very elaborate documentation [here](https://www.bettercap.org).

**Comment by azamet90** [comment]
> I'm not gonna help you if you refuse to read the documentation and do what it says. You also don't write a complete issue, and the template clearly says those issues get closed immediately.
> 
> No one is going to waste their time on explaining how to use bettercap when there is very elaborate documentation [here](https://www.bettercap.org).

you mean there is somethings which is telling how to use beef-inject.js but i say you there is nothing mentioned about that? you think it is funny for me to disqus only for getting help? why it was so hard to tell just this

**Comment by buffermet** [comment]
@azamet90 dude, if you had read the documentation you would know how to use bettercap. You somehow think bettercap + beef inject caplet requires new documentation when it works like any other caplet...

You simply refuse to learn how bettercap works and that's not my problem.

You should also write a full issue but you just deleted the template instead.
