### ISSUE TITLE
hstshijack/hstshijack: "dial tcp: lookup ... no such host" (it reproduces after v2.23)

### ISSUE THREAD

**Issue by fadeevab** [bettercap/bettercap#678]
Looks like a regression: HSTS hijacking works on bettercap v2.23, and doesn't work upper.

Steps:
1. arpspoof is on: intercept the traffic between Windows (192.168.0.107) and Gateway (192.168.0.1).
2. `hstshijack/hstshijack`
3. google.com -> wvvw.google.corn -> search "1111111" (`http://wvvw.google.corn/search?q=111111111`)-> error in the browser:
```
dial tcp: lookup wvvw.google.corn on 192.168.0.1:53: no such host
```
Strange, but there is even video how to "fix" (downgrade bettercap to v2.23): https://www.youtube.com/watch?v=XoUPHF-wyMc&feature=youtu.be

### Environment

*  `bettercap -version` :  bettercap v2.26.1 (built for linux amd64 with go1.13.3)
* `uname -a`: Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux
* Command line: `bettercap -iface eth0`
* Caplet: `hstshijack/hstshijack`

Logs:
```
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [inf] dns.spoof sending spoofed DNS reply for play.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
192.168.0.0/24 > 192.168.0.106  »  
    
     [hstshijack.callback] CALLBACK http://wvvw.google.com/lQkctfflaIgh?source=hp&ei=H_oDXrLuFczLrgTo95-4Cg&iflsig=AAP1E1EAAAAAXgQIL2xQNMhT-YFDD06rUG7pFluFwLE5&q=111111111&btnK=%D0%9F%D0%BE%D1%88%D1%83%D0%BA%20Google&btnI=%D0%9C%D0%B5%D0%BD%D1%96%20%D0%BF%D0%BE%D1%89%D0%B0%D1%81%D1%82%D0%B8%D1%82%D1%8C&btnK=%D0%9F%D0%BE%D1%88%D1%83%D0%BA%20Google&btnI=%D0%9C%D0%B5%D0%BD%D1%96%20%D0%BF%D0%BE%D1%89%D0%B0%D1%81%D1%82%D0%B8%D1%82%D1%8C&oq=111111111&gs_l=psy-ab.3...9894.11248..69816...0.0..1.310.1675.2j5j2j1......0....1..gws-wiz.....0..0i131j0.AMvz6dolZWI&ved=0ahUKEwjy-cP6gtLmAhXMpYsKHej7B6cQ4dUDCAU&uact=5

...

192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] http.proxy < 192.168.0.107:52154 POST wvvw.google.com/lQkctfflaIgh
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [http.proxy.spoofed-request] {http.proxy.spoofed-request 2019-12-25 19:10:14.52246548 -0500 EST m=+411.552427311 {192.168.0.107 POST wvvw.google.com /lQkctfflaIgh 0}}
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] hstshijack Patched spoofed hostname play.google.corn to play.google.com and set scheme to HTTPS.
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] http.proxy < 192.168.0.107:52215 POST play.google.corn/log
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] hstshijack Patched SSL of www.google.com in request headers.
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [http.proxy.spoofed-request] {http.proxy.spoofed-request 2019-12-25 19:10:14.596675054 -0500 EST m=+411.626636884 {192.168.0.107 POST play.google.com /log 0}}
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] dns.spoof sending 108 bytes of packet ...
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [inf] dns.spoof sending spoofed DNS reply for play.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [dbg] dns.spoof sending 120 bytes of packet ...
192.168.0.0/24 > 192.168.0.106  » [19:10:14] [sys.log] [inf] dns.spoof sending spoofed DNS reply for play.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
192.168.0.0/24 > 192.168.0.106  » [19:10:15] [sys.log] [dbg] dns.spoof skipping domain 14.226.52.65.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:15] [sys.log] [dbg] dns.spoof skipping domain 14.226.52.65.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:15] [sys.log] [dbg] dns.spoof skipping domain 14.226.52.65.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:16] [sys.log] [dbg] dns.spoof skipping domain 14.226.52.65.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof skipping domain 200.21.107.13.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [inf] dns.spoof sending spoofed DNS reply for wvvw.google.corn (->192.168.0.106) to 192.168.0.107 : 08:00:27:e6:e5:59 (PCS Computer Systems GmbH).
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof sending 108 bytes of packet ...
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] http.proxy < 192.168.0.107:52222 GET wvvw.google.corn/search
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] hstshijack Patched spoofed hostname wvvw.google.corn to www.google.corn and set scheme to HTTPS.
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] hstshijack Patched spoofed hostname www.google.corn to www.google.com and set scheme to HTTPS.
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [http.proxy.spoofed-request] {http.proxy.spoofed-request 2019-12-25 19:10:32.207132262 -0500 EST m=+429.237094094 {192.168.0.107 GET www.google.com /search 0}}
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof skipping domain 200.21.107.13.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof sending 108 bytes of packet ...
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [inf] dns.spoof sending spoofed DNS reply for wvvw.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof skipping domain 200.21.107.13.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof skipping domain 2.114.142.52.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof skipping domain 200.21.107.13.in-addr.arpa
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [dbg] dns.spoof sending 108 bytes of packet ...
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [inf] dns.spoof sending spoofed DNS reply for wvvw.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
192.168.0.0/24 > 192.168.0.106  » [19:10:32] [sys.log] [inf] dns.spoof sending spoofed DNS reply for wvvw.google.corn (->192.168.0.106) to 192.168.0.1 : d4:6e:0e:fc:08:b6 (Tp-Link Technologies Co.,Ltd.).
```

**Comment by fadeevab** [comment]
It could be related to #615

**Comment by tkent** [comment]
I'm seeing similiar behavior. FWIW, I can add some additional information about it.

It does not appear to be related to any misbehavior with the `dns.spoof` caplet. The `dial tcp...` errors are coming from bettercap itself when the hsts caplet + proxy is trying to capture the targeted site's https content. If you curl one of the urls that fail to load, you'll see that bettercap's HTTP proxy is returning with a 500 status and the dns error you're seeing in the browser. Here's an example:

```
curl -v 'http://www.spoofdomain.corn/szUabpCdeLgSIM?'
*   Trying 192.168.0.3...
* TCP_NODELAY set
* Connected to www.spoofdomain.corn (192.168.0.3) port 80 (#0)
> GET /szUabpCdeLgSIM? HTTP/1.1
> Host: www.spoofdomain.corn
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 31 Dec 2019 23:22:06 GMT
< Content-Length: 65
< 
dial tcp: lookup www.spoofdomain.corn on 192.168.0.1:53: no such host
* Connection #0 to host www.spoofdomain.corn left intact
* Closing connection 0
```

For testing, I setup a router to NAT all DNS requests from the attack target to a DNSChef instance setup to spoof queries the same way the bettercap `dns.spoof` module is supposed to. That gave me 100% reliability for dns spoofing on the attack target and I was able to confirm that with nslookup.

In this configuration, the hsts caplet would correctly strip https off of *most* of the resources loaded by the target site. However, some resources always returned a 500 error with a `dial tcp:....` message. It seems that somewhere in the process bettercap is trying to do a DNS lookup of some of the fqdns it spoofed.


If I had more time, I'd go poking around to see how the hsts module maps spoofed fqdns back to real ones for proxying. But, I'm out of time! Hopefully this report makes it easier to chase down by somebody else.

**Comment by buffermet** [comment]
I believe this either has to do with the fact tha gopacket does not have native support for DNS/TCP or clients with hardcoded DNS servers.

**Comment by buffermet** [comment]
Please note that DNS responses can be cached for hours or longer and any changes that you make will not take effect until you clear your DNS cache.

**Comment by fadeevab** [comment]
@buffermet `ipconfig /flushdns` didn't help on the target system. I played a lot with different bettercap versions, and bettercap v2.23 is stable, it just works. Unfortunately I failed to find the root of cause comparing v2.23 to master. I tried to revert some chances, e.g. gopacket version and some patches, but that didn't help.

**Comment by buffermet** [comment]
I'm having the same issue.

`nslookup` returns a non-authoritative response as expected, but when I send a HTTP request from a browser, hostnames are not resolved.

This is why I initially thought it was due to a hardcoded DNS server, however, a PCAP reveals that I'm getting mixed DNS replies from bettercap. Sometimes it resolves and sometimes it does not.

![Screenshot from 2020-01-02 11-05-21](https://user-images.githubusercontent.com/29265684/71648660-ecb3dc80-2d52-11ea-93df-70f2e7cd0c1f.png)

**Comment by buffermet** [comment]
I experience no issues when DNS spoofing + serving HTTP over a port other than 80.

Setting `http.server.port` to anything other than 80 results in a working connection and the requested path is served.

I used the following caplet to test:

```
set http.server.port 8021
http.server on

set dns.spoof.domains any.randomfqdn.com
set dns.spoof.all true
dns.spoof on
```

These were bettercap's logs:

```
bettercap v2.26.1 (built for linux amd64 with go1.13.5) [type 'help' for a list of commands]

[21:18:48] [sys.log] [war] Could not detect gateway.
[21:18:48] [sys.log] [war] Could not detect gateway.
[21:18:48] [sys.log] [inf] net.sniff starting net.recon as a requirement for net.sniff
[21:18:48] [sys.log] [inf] http.server starting on http://192.168.32.1:8021
[21:18:48] [endpoint.new] endpoint 192.168.32.228 detected as fc:c2:de:aa:bb:cc (Murata Manufacturing Co., Ltd.).
[21:18:48] [sys.log] [inf] dns.spoof any.randomfqdn.com -> 192.168.32.1
[21:20:33] [sys.log] [inf] dns.spoof sending spoofed DNS reply for any.randomfqdn.com (->192.168.32.1) to 192.168.32.228 : fc:c2:de:aa:bb:cc (Murata Manufacturing Co., Ltd.).
[21:20:34] [sys.log] [inf] dns.spoof sending spoofed DNS reply for any.randomfqdn.com (->192.168.32.1) to 192.168.32.228 : fc:c2:de:aa:bb:cc (Murata Manufacturing Co., Ltd.).
```

This was the request from and response to the targeted client:

```
$ curl -v any.randomfqdn.com:8021
*   Trying 192.168.32.1:8021...
* TCP_NODELAY set
* Connected to any.randomfqdn.com (192.168.32.1) port 8021 (#0)
> GET / HTTP/1.1
> Host: any.randomfqdn.com:8021
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Last-Modified: Mon, 06 Jan 2020 10:58:44 GMT
< Date: Mon, 06 Jan 2020 11:20:43 GMT
< Content-Length: 911
<
<pre>
<a href=".git/">.git/</a>
<a href=".github/">.github/</a>
<a href=".gitignore">.gitignore</a>
<a href=".travis.yml">.travis.yml</a>
<a href="Dockerfile">Dockerfile</a>
<a href="ISSUE_TEMPLATE.md">ISSUE_TEMPLATE.md</a>
<a href="LICENSE.md">LICENSE.md</a>
<a href="Makefile">Makefile</a>
<a href="README.md">README.md</a>
<a href="bettercap">bettercap</a>
<a href="bettercap.service">bettercap.service</a>
<a href="build.sh">build.sh</a>
<a href="builder/">builder/</a>
<a href="caplets/">caplets/</a>
<a href="changelog.sh">changelog.sh</a>
<a href="core/">core/</a>
<a href="firewall/">firewall/</a>
<a href="go.mod">go.mod</a>
<a href="go.sum">go.sum</a>
<a href="log/">log/</a>
<a href="main.go">main.go</a>
<a href="modules/">modules/</a>
<a href="network/">network/</a>
<a href="packets/">packets/</a>
<a href="release.sh">release.sh</a>
<a href="session/">session/</a>
<a href="tls/">tls/</a>
</pre>
* Connection #0 to host any.randomfqdn.com left intact
```

If I serve HTTP over port 80 (using bettercap's `http.server` or any other HTTP server), I experience the same issue as seen in @tkent's logs.

Needless to say, bettercap never complained about port 80 already being used.

**Comment by crispywizard** [comment]
Same issue.  Serving a website from anything other than port 80 and specifying the port in the victim browser makes the hijack work as expected.  This seems to be a big clue.

This issue has been outstanding for a long time, can anyone fix it?  Downgrading bettercap fixes it, so it's a regression somewhere.  I can't make heads or tails of it though.

**Comment by crispywizard** [comment]
I did some testing, and reverting commit be62757efa880297ff474e1033056734148d3723 fixes this issue.  I don't know if reverting this causes any "side effects" further down the line but it seems fine from what I can see.

**Comment by buffermet** [comment]
@Matrix86 is it possible that you were facing a TLS enabled port (443, 8443) and therefore had issues proxying?

From what I can see, this commit overrides the request's hostname with the initially requested hostname, inhibiting the ability to spoof it.

**Comment by aaronovz1** [comment]
Still seeing this in v2.27.1 in Kali 2020

**Comment by 0x0ff537** [comment]
The same error is still occurring in version 2.30.2. I tested in a recently imported kali virtual machine (latest kali version), enabling hstshijack caplet throws dial tcp error while trying to reach facebook.corn or twitter.corn in victim machine (simple https sites are being downgraded successfully). I also tested it with v2.23 and it works pretty well for https and hsts sites.
