### ISSUE TITLE
beef-hook injection

### ISSUE THREAD

**Issue by Giuliano-di-torino** [bettercap/bettercap#682]
Hello there
I'm using bettercap v2.26.1 on kali3 machine with latest update and upgrades.
beef version 5 the latest upgrade. the BeEF hook works fine on its own when I test it either on the local machine or windows10 machine running in virtualbox with the network adapter set to bridge either wlan0 or vmnet8 and I succeed to hook microsoft edge and chrome and firefox in the guest machine in virtual box.
in the case of hook injection via arp spoofing with bettercap how ever it seems I cannot get it work no matter what. there is no any updated caplets for beef-hook any more and when I try to use , set http.proxy.injectjs <hook.js URL>  , it is absolutely useless even though in the targeted machine I brows to a http hosted webpage. so I'm wondering if hook injection is working in bettercap any more at all ? 
However if it is still working and that's just me that cannot get it to work, then I highly appreciate any tips and tricks to make it work and maybe some updated caplet or script that can help to get the job done.
Thanks.

**Comment by buffermet** [comment]
You're not using bettercap as described in the documentation, and you didn't post a complete issue.
