### ISSUE TITLE
Bettercap still running

### ISSUE THREAD

**Issue by sunumd** [bettercap/bettercap#686]
# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

# Description OS and application
1. Bettercap version (1.6.2)
2. OS version and architecture (Linux Parrot 5.4.0-2parrot1-amd64 #1 SMP Parrot 5.4.8-2parrot1 x86_64 GNU/Linux)
3. Go version (go1.13.5 Linux/amd64)

# Command line
1. Running bettercap `bettercap --interface eth0 --gateway 192.168.0.1`
(when i run the application, it still run and can't stop automatically so i not use any command line.)
2. Running bettercap debug, to show the command used `bettercap --debug`
(when i run the command, i found and i remember to using it)
3. so this is command i used it `[D] LANG=en && LANGUAGE=en_EN.UTF-8 && arp -a -n` and i don't now to turn off it, it's make an automatically scanning until down (still running)

# The screenshoot
![Screenshot at 2020-01-19 05-36-04](https://user-images.githubusercontent.com/48803788/72674574-6f70b300-3a46-11ea-9189-d1c833d890a2.png)
![Screenshot at 2020-01-19 05-36-51](https://user-images.githubusercontent.com/48803788/72674575-6f70b300-3a46-11ea-912f-70597c889b18.png)
![Screenshot at 2020-01-19 05-37-49](https://user-images.githubusercontent.com/48803788/72674576-6f70b300-3a46-11ea-89d0-2c8d4d71cb24.png)
![Screenshot at 2020-01-19 05-59-20](https://user-images.githubusercontent.com/48803788/72674577-70094980-3a46-11ea-852a-102699c2fabd.png)
![Screenshot at 2020-01-19 05-59-42](https://user-images.githubusercontent.com/48803788/72674578-70094980-3a46-11ea-98f7-a3e8412789e8.png)
![Screenshot at 2020-01-19 06-00-02](https://user-images.githubusercontent.com/48803788/72674579-70a1e000-3a46-11ea-91ea-daf315d1998f.png)
![Screenshot at 2020-01-19 06-00-24](https://user-images.githubusercontent.com/48803788/72674580-70a1e000-3a46-11ea-85e6-6d30faaa8ea1.png)
![Screenshot at 2020-01-19 06-00-44](https://user-images.githubusercontent.com/48803788/72674581-70a1e000-3a46-11ea-92d1-fe064f8e11aa.png)
![Screenshot at 2020-01-19 06-01-09](https://user-images.githubusercontent.com/48803788/72674582-713a7680-3a46-11ea-9585-f2e8849f485a.png)

**Comment by amaurylopin** [comment]
How did you manage to make it work ?
I'm having the same issue and still stuck
