### ISSUE TITLE
Fake access point

### ISSUE THREAD

**Issue by LeaKitty** [bettercap/bettercap#688]
Hello :) ,

  I have a problem with the fake access point (Wi-Fi), I created correctly as in the example given, but could not connect it with my smartphone or tablet, it always tells me "connection rejected".

Do you know why ?

**My settings :**
- My Bettercap version is 2.26.1.
- My OS version is linux 5.3 amd64 (kali-linux).
- My Go version is 1.13.6.
- My wireless card Alfa AWUS036ACH AC1200.

**Steps :**

1. My card wifi in monitor mode with iwconfig
2. bettercap -iface wlan0
3. set wifi.ap.ssid Banana; set wifi.ap.bssid DE:AD:BE:EF:DE:AD; set wifi.ap.channel 5; set wifi.ap.encryption false; wifi.recon on; wifi.ap
4. Wait
5. I see the fake access point and try it connected me with my smartphone or tablet
6. But I always get the message "connection rejected"

_Sorry for my English still basic_

**Comment by buffermet** [comment]
AFAIK bettercap only sends beacons, it does not handle DHCP leases nor does it have a DNS server module.

To achieve what you want, you will have to spawn your own AP and use the same interface with bettercap.
