### ISSUE TITLE
windows wifi

### ISSUE THREAD

**Issue by boo6ster** [bettercap/bettercap#689]
Does the windows wifi support work at all? I have two wifi cards on the atheros chipset that support monitor mode and packet injection. Every time I get an error:

bettercap.exe -iface 50:B7:C3:DA:2D:BB
bettercap v2.26.1 (built for windows amd64 with go1.13.3) [type 'help' for a list of commands]

192.168.1.0/24 > 192.168.1.100  » [01:36:48] [sys.log] [war] Could not detect gateway.
192.168.1.0/24 > 192.168.1.100  » wifi.recon on
192.168.1.0/24 > 192.168.1.100  » wifi.recon on
[01:36:58] [sys.log] [inf] wifi using interface \Device\NPF_{59D37800-6DA4-456D-B13E-AFC3B1531583} (50:b7:c3:da:2d:bb)
[01:36:58] [sys.log] [err] error while setting interface \Device\NPF_{59D37800-6DA4-456D-B13E-AFC3B1531583} in monitor mode: Cannot set rfmon for this handle

After installing Npcap, I have the error:

bettercap.exe -iface 52:B7:C3:DA:2D:BB
bettercap v2.26.1 (built for windows amd64 with go1.13.3) [type 'help' for a list of commands]

169.254.0.0/16 > 169.254.89.174  » [02:37:34] [sys.log] [war] Could not detect gateway.
169.254.0.0/16 > 169.254.89.174  » wifi.recon on
169.254.0.0/16 > 169.254.89.174  » wifi.recon on
[02:37:46] [sys.log] [inf] wifi using interface \Device\NPF_{3A48B3F4-3AF3-492B-8869-B2803E930DE1} (52:b7:c3:da:2d:bb)
[02:37:46] [sys.log] [err] error while activating handle: unknown activated error: -1

On second wifi card i have the error:

[02:49:11] [sys.log] [err] error while getting supported frequencies of \Device\NPF_{F088E537-8CFD-4725-A6CC-64C8E301439C}: Windows does not support WiFi channel hopping.

Windows 8 64bit

**Comment by adde88** [comment]
Monitor-mode on Windows requires modified/custom drivers, and i wouldn't call it "stable".

**Comment by Robin6464** [comment]
Wireshark with npcap captures wifi packets in monitor mode. If bettercap under windows worked without WiFi channel hopping, could this help? If so, can you build a binaries for windows without this option? I know windows has big limitations and I thought bettercap could be the only tool under windows for deauth attack and handshake capture :)

**Comment by Robin6464** [comment]
I am very sorry that bettercap for windows is useless to use wifi network. Wireshark for windows can in monitor mode capture WiFi packets containing handshake and pkmid. Commview for wifi under windows can send deauth packets in monitor mode. If someone writes to me that windows has limitations and you can't impress these things, to cement under windows, I don't understand it. Maybe someday I will see a bettercap version for windows with wifi support :)

**Comment by adde88** [comment]
There are huge limitations with wifi on Windows compared to Linux when it comes to tools that requires monitor mode!
Yes, some tools like Commview / npcap can capture raw wifi frames in monitor mode, but they don't work on all adapters, and several adapters that does support monitor mode still have limitations.

**Comment by Robin6464** [comment]
You can buy a low-cost usb wifi card for windows with full monitor mode support. This approach should not exclude the possibility of using in bettercap wifi networks.
