### ISSUE TITLE
Does not support Kali 32-bit system

### ISSUE THREAD

**Issue by EastwindZL** [bettercap/bettercap#69]
OS：

Kali Linux 32 Bit  2018.1

![20180223_142648](https://user-images.githubusercontent.com/29472751/36581021-d1e436de-18a5-11e8-94c7-97203587b60a.png)
![20180223_142730](https://user-images.githubusercontent.com/29472751/36581022-d22a04ac-18a5-11e8-936c-57de924c9d3c.png)

**Comment by evilsocket** [comment]
there's a specific issue template that you did not respect, closing
