### ISSUE TITLE
PLEASE HELP ME ( I NEED HELP)

### ISSUE THREAD

**Issue by arminh4ck3r** [bettercap/bettercap#690]
Sniffer module was NOT enabled ( -X argument ), this will cause the MITM to run but no data to be collected.

GOT THIS PLEASE HELP

**Comment by buffermet** [comment]
You're running the legacy 1.x version which is no longer supported.

**Comment by arminh4ck3r** [comment]
THANK YOU SO MUCH

**Comment by arminh4ck3r** [comment]
which one should i install ?

**Comment by buffermet** [comment]
Please read the documentation thoroughly, this is an issues tracking page, not a place for tutorials...

https://www.bettercap.org/

**Comment by arminh4ck3r** [comment]
man i have the newest version of bettercap but still have this                                                                     Sniffer module was NOT enabled ( -X argument ), this will cause the MITM to run but no data to be collected.

**Comment by buffermet** [comment]
Obviously the old version is still installed. For the second time, please use Google instead of this issues tracker.
