### ISSUE TITLE
premission solutions...

### ISSUE THREAD

**Issue by arminh4ck3r** [bettercap/bettercap#691]
Hello.Are there any ways to find a solution for :
wlan0: You don't have permission to capture on that device (socket: Operation not permitted) 
Thank you. Good luck .....

**Comment by FrankSpierings** [comment]
Which user is attempting to capture? Have you tried `sudo`?

**Comment by bikrambox** [comment]
> Which user is attempting to capture? Have you tried `sudo`?

Works!
