### ISSUE TITLE
`wifi.show` returns nothing

### ISSUE THREAD

**Issue by AnatoleLucet** [bettercap/bettercap#695]
When I use `wifi.show` it does not return any device. I tried to run `nmcli d wifi list` it does returns two devices (as it should).

### Environment

Bettercap version: `bettercap v2.26.1 (built for linux amd64 with go1.13.3)`

Proc version: `Linux version 5.4.0-kali2-amd64 (devel@kali.org) (gcc version 9.2.1 20200104 (Debian 9.2.1-22)) #1 SMP Debian 5.4.8-1kali1 (2020-01-06)`

Command line arguments you are using: `-iface wlan0`

Caplet code you are using or the interactive session commands:
- `wifi.recon on`
- `wifi.show`

Full debug output while reproducing the issue ( `bettercap -debug ...` ):
```
kali@kali:~$ sudo bettercap -iface wlan0 -debug
bettercap v2.26.1 (built for linux amd64 with go1.13.3) [type 'help' for a list of commands]

 wlan0  » [22:10:18] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
 wlan0  » [22:10:18] [sys.log] [dbg] FindGateway(wlan0) output:

 wlan0  » [22:10:18] [sys.log] [dbg] FindGateway(wlan0): nothing found :/
 wlan0  » [22:10:18] [sys.log] [dbg] Could not detect gateway.
 wlan0  » [22:10:18] [session.started] {session.started 2020-02-07 22:10:18.962938254 +0000 UTC m=+0.012570303 <nil>}
 wlan0  » [22:10:18] [mod.started] events.stream
 wlan0  » wifi.recon on
[22:10:22] [sys.log] [inf] wifi using interface wlan0 (2e:39:a0:ee:d5:60)
[22:10:22] [sys.log] [dbg] wifi interface wlan0 txpower set to 30
[22:10:22] [sys.log] [dbg] wifi new frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 5180 5200 5220 5240 5260 5280 5300 5320 5500 5520 5540 5560 5580 5600 5620 5640 5660 5680 5700]
[22:10:22] [sys.log] [dbg] wifi wifi supported frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 5180 5200 5220 5240 5260 5280 5300 5320 5500 5520 5540 5560 5580 5600 5620 5640 5660 5680 5700]
[22:10:22] [sys.log] [inf] wifi started (min rssi: -200 dBm)
 wlan0  » [22:10:22] [mod.started] wifi
 wlan0  » [22:10:22] [sys.log] [inf] wifi channel hopper started.
 wlan0  » [22:10:22] [sys.log] [dbg] wifi wifi stations pruner started (ap.ttl:5m0s sta.ttl:5m0s).
 wlan0  » [22:10:22] [sys.log] [dbg] wifi hopping on channel 1
 wlan0  » [22:10:23] [sys.log] [dbg] wifi hopping on channel 2
 wlan0  » w[22:10:23] [sys.log] [dbg] wifi hopping on channel 3
 wlan0  » wifi[22:10:24] [sys.log] [dbg] wifi hopping on channel 4
 wlan0  » wifi.sh[22:10:24] [sys.log] [dbg] wifi hopping on channel 5
 wlan0  » wifi.show

wlan0 (ch. 5) / ↑ 0 B / ↓ 0 B / 0 pkts

 wlan0  » [22:10:25] [sys.log] [dbg] wifi hopping on channel 6
 wlan0  » [22:10:25] [sys.log] [dbg] wifi hopping on channel 7
 wlan0  » [22:10:26] [sys.log] [dbg] wifi hopping on channel 8
 wlan0  » exit[22:10:26] [sys.log] [dbg] wifi hopping on channel 9
 wlan0  » exit

Stopping modules and cleaning session state ...
```

Maybe the output of `ip a` can help:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether ea:7b:93:fa:4e:13 brd ff:ff:ff:ff:ff:ff
```

### Steps to Reproduce

1. `sudo bettercap -iface wlan0`
2. `wifi.recon on`
3. `wifi.show`

**Expected behavior:** A list of nearby wifi devices.

**Actual behavior:** The list is empty.

**Comment by AnatoleLucet** [comment]
It was an issue with my wireless card. I had to buy an external usb wireless card.

**Comment by AnatoleLucet** [comment]
@Finesse are you the wireless card of the MacBook Air 2020 supports monitor mode and packet injection?
> The interface only needs to support monitor mode and packet injection, it’ll be bettercap itself to switch it to the right mode, just make sure there aren’t other processes using the same wifi interface.
https://www.bettercap.org/modules/wifi/

**Comment by Finesse** [comment]
@AnatoleLucet I don't know. I use the built-in hardware on both laptops.

**Comment by AnatoleLucet** [comment]
Ok. I'll reopen IYW, but i don't think this is related to bettercap.
You might want to get an external wireless card like a Panda ([which seems to support MacOS](http://www.pandawireless.com/Installation%20for%20Mac%20%7C%20Panda%20Wireless.html)).

**Comment by Finesse** [comment]
I admit it can be unsolvable to Bettercap. I expect at least a confirmation from the contributors that it's a "won't fix".

**Comment by buffermet** [comment]
> It was an issue with my wireless card. I had to buy an external usb wireless card.

This is correct. Closing.

**Comment by dontsovcmc** [comment]
wifi.show doesn't work on Macbook M3 (Sonoma 14.3.1) with internal card

**Comment by b0fhb0fh** [comment]
> wifi.show doesn't work on Macbook M3 (Sonoma 14.3.1) with internal card

the same
Apple MB Pro M3 Sonoma 14.5

**Comment by lylythechosenone** [comment]
Same for a MBP 13" M1 (2020). However, the internal card does certainly support monitor mode (I've used it extensively). Only this one command doesn't work.
