### ISSUE TITLE
Wi-Fi Access Point Attack

### ISSUE THREAD

**Issue by Anth0-M** [bettercap/bettercap#696]
Hello, :)

I've been on bettercap for 2 months now and I find it very practical and easy to use but there is only one point that blocks me concerning wifi.

I create a Fake access point but then how do I create a Wi-Fi attack ? 

Is there a tutorial to know how to set this up please ?

Thank you.

**Comment by buffermet** [comment]
Specify "Wi-Fi attack"...

Bettercap is literally `the Swiss Army knife for 802.11, BLE and Ethernet networks reconnaissance and MITM attacks`.

It looks to me like you should read the [documentation](https://www.bettercap.org/).
