### ISSUE TITLE
Add JS for http(s).server or disable proxying for http(s).proxy

### ISSUE THREAD

**Issue by grigorescu** [bettercap/bettercap#697]
*Description of the bug or feature request*

I'd like to request adding support for a script-driven HTTP(S) server, similar to http(s).proxy, but without proxying functionality.

Certain attacks need additional capabilities than just serving up static files (e.g. setting custom headers, serving dynamic content, etc.). While the script functionality of the http(s).proxy helps, in some circumstances, a user might not want traffic flowing through the machine running bettercap. An example would be environments with strict NAC.

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
bettercap v2.26.1 (built for darwin amd64 with go1.13.3)
* OS version and architecture you are using.
MacOS 10.14
* Go version if building from sources.
Using release.
* Command line arguments you are using.
n/a
* Caplet code you are using or the interactive session commands.
n/a
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
n/a

### Steps to Reproduce

1. `set http.server.script payload.js`
2. `http.server on`

**Expected behavior:** Run http.server, with payload.js functions being called for the requests.

**Actual behavior:** Error, not currently implemented.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by buffermet** [comment]
You can use your own web server and redirect traffic to it using bettercap, in conjunction with the `api.rest` module, you can create callbacks, etc.
