### ISSUE TITLE
"Could not detect gateway" on Windows 10

### ISSUE THREAD

**Issue by rfitzpatrick1** [bettercap/bettercap#701]
Please provide:

* Bettercap version you are using ( `bettercap -version` ): v2.26.1
* OS version and architecture you are using: Windows 10 Home

1. Download Windows file from https://github.com/bettercap/bettercap/releases
2. Extract
3. Put libusb and libpcap files in the same folder as bettercap.exe
![Bettercap folder](https://user-images.githubusercontent.com/56458738/74957228-2920c200-53ff-11ea-848b-839181e9d509.jpg)
4. Invoke bettercap.exe in command prompt
![Command Prompt 1](https://user-images.githubusercontent.com/56458738/74958683-3b9bfb00-5401-11ea-99aa-94384c2ff2be.jpg)
5. Met with a pop-up saying "Do you want to allow this app to make changes to your device?". Select Yes.
6. Get output on the command prompt looking like this:
![Command Prompt](https://user-images.githubusercontent.com/56458738/74959504-95e98b80-5402-11ea-8c02-cd6fdce29b29.jpg) (I don't know what the symbol at the start and after the J are supposed to be)

I was originally following the steps on Issue #591 and using Npcap, but ended up with exactly the same output as I am now.

**Comment by Gh0stByte** [comment]
I'm having a similar issue but first of all to address yours; both of your libraries are still compressed and virtually useless.

**Comment by minanagehsalalma** [comment]
@rfitzpatrick1  @Gh0stByte  have you figured it out mate ?

**Comment by Gh0stByte** [comment]
> 
> 
> @rfitzpatrick1 @Gh0stByte have you figured it out mate ?

Hey! It's been a while since I messed around with it. If I recall correctly, however, the issue is with what WSL was compatible with. Your network card had to be able to enter promiscuous mode and if it didn't, you'd have to use a USB dongle. However, wsl doesn't work with USB devices yet.

**Comment by minanagehsalalma** [comment]
> > @rfitzpatrick1 @Gh0stByte have you figured it out mate ?
> 
> Hey! It's been a while since I messed around with it. If I recall correctly, however, the issue is with what WSL was compatible with. Your network card had to be able to enter promiscuous mode and if it didn't, you'd have to use a USB dongle. However, wsl doesn't work with USB devices yet.

@Gh0stByte "promiscuous mode" i think mine can i used it with wireshark in local network and even with aircrack even though it wasn't performing good ... damn it looks like i have to use a VM again ... i really wanted to use it cause there is no alternatives for windows :(

**Comment by ce-roid** [comment]
So...any new solution?
