### ISSUE TITLE
"No such file or directory" error when running precompiled binaries - pi 0w

### ISSUE THREAD

**Issue by ikuamike** [bettercap/bettercap#704]
I was following this tutorial on creating project pita https://www.evilsocket.net/2018/07/28/Project-PITA-Writeup-build-a-mini-mass-deauther-using-bettercap-and-a-Raspberry-Pi-Zero-W/

### Environment

Please provide:

* Bettercap version you are using `bettercap v2.26.1 (built for linux arm with go1.13.1)`.
* OS version and architecture you are using - `Kali 2020.1 for raspberry pi zero w, Linux pita 4.19.93-Re4son+ #1 Wed Jan 8 14:55:22 AEDT 2020 armv6l GNU/Linux`.

### Steps to Reproduce

1. Download latest release bettercap_linux_armhf_v2.26.1.zip
2. extract and run ./bettercap

**Expected behavior:** *What you expected to happen*
Expected to run
**Actual behavior:** *What actually happened*

![Screenshot from 2020-02-29 13-14-49](https://user-images.githubusercontent.com/5783614/75607269-a0d4a800-5af5-11ea-9e30-2f53c23dea0a.png)

###  Workaround

This is issue was closed on an older release https://github.com/bettercap/bettercap/issues/350

Creating this symlink seems to make it work `ln -s /lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3`

![Screenshot from 2020-02-29 13-23-43](https://user-images.githubusercontent.com/5783614/75607383-d5952f00-5af6-11ea-8017-07f944fc5361.png)

**Comment by aster1sk** [comment]
Quick note on cross-compiling bettercap for different Raspberry Pi models.

Non-exhaustive list of dependencies :

```
apt -y install \
    autoconf \
    bison \
    build-essential \
    cmake \
    flex \
    gawk \
    gcc-aarch64-linux-gnu \
    gcc-arm-linux-gnueabihf \
    git-core \
    golang-go \
    libtool \
    wget
```

This output of this Makefile has been tested with success on Raspbian, Alpine, BuildRoot and OpenWRT on Pi3B and Pi3B+ - it compiles a 32bit arm with the following file signature :

```
bettercap: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=0453f52ffb890c19788afdcce9221af632bb668b, for GNU/Linux 3.2.0, stripped
```

Experiment by changing GOARM=5 to different versions for whatever model you're using.

If you'd like to build a 64 bit version (3B+, Pi4) - replace `gcc-arm-linux-gnueabihf` with `gcc-aarch64-linux-gnu` in the Makefile below.

```
.PHONY: bettercap libusb libpcap clean update

bettercap: libusb libpcap
	cd bettercap && env CC=arm-linux-gnueabihf-gcc GOARCH=arm GOARM=5 GOOS=linux CGO_ENABLED=1 \
		PKG_CONFIG_PATH="$$HOME/.local/lib/pkgconfig" \
		CGO_LDFLAGS="-L$$HOME/.local/lib -lpcap -lusb-1.0" \
		go build -tags netgo -trimpath -ldflags '-linkmode external -extldflags "-static" -s -w' -v -o bettercap

libpcap:
	cd ./libpcap && CC=arm-linux-gnueabihf-gcc ./configure --prefix=$$HOME/.local --host=arm-linux --with-pcap=linux && make clean && make && make install

libusb:
	cd ./libusb && ./bootstrap.sh && ./configure --prefix=$$HOME/.local --host=arm-linux-gnueabihf --enable-udev=false CC=arm-linux-gnueabihf-gcc && make clean && make && make install

clean:
	rm -rf bettercap libusb libpcap

update:
	git clone https://github.com/libusb/libusb.git
	git clone --branch=libpcap-1.9 https://github.com/the-tcpdump-group/libpcap.git
	git clone https://github.com/bettercap/bettercap.git

```
