### ISSUE TITLE
hstshijack.cap

### ISSUE THREAD

**Issue by AkumaBiNoTori** [bettercap/bettercap#711]
* 2.23
* 64-bit kalilinux on virtual box.
 i was running an attack on my win10 64-bit machine  i used to have the dial tcp connection refused when i used the caplet on https sites my instructor said i should download an older version of bettercap i did and it worked but now on when i open a normal http website i get the error idk what exactly you want to see in the file so send me what you want to see in the files and ill send it

**Comment by buffermet** [comment]
What we want to see is exactly what was mentioned in the issue template that you deleted.
