### ISSUE TITLE
ARP proplem

### ISSUE THREAD

**Issue by chunxingque** [bettercap/bettercap#712]
ARP spoofing in Kali, but the victim host cannot access the Internet
I have done ipv4 forwarding
echo '1' >> / proc / sys / net / ipv4 / ip_forward
help me

**Comment by doggukan** [comment]
same issue happening on termux as root.as soon as arp spoof or http.proxy enabled internet doesnt works.

**Comment by chunxingque** [comment]
I remove iptables ，and solved this problem

**Comment by doggukan** [comment]
how did you removed it ? http.proxy module doesnt works without it.
