### ISSUE TITLE
sslstrip enabled but redirect not working?

### ISSUE THREAD

**Issue by suryansh786** [bettercap/bettercap#716]
https.proxy is turned on after setting the vale true for sslstrip. I've also run hstsihijacking and arpspoof
You cannot visit (domain name) right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by buffermet** [comment]
Anything you need to know about sslstrip/hstshijack has been discussed here https://github.com/bettercap/bettercap/issues/428
