### ISSUE TITLE
Cannot locate credentials

### ISSUE THREAD

**Issue by rfitzpatrick1** [bettercap/bettercap#721]
Bettercap version 2.27.1 on Windows 10

I dragged the bettercap.exe file into the command window and entered the commands shown in the photo:
![Bettercap installation output](https://user-images.githubusercontent.com/56458738/79672423-a4b5aa00-81c9-11ea-9374-a56f92368472.png)
Once this is done, I am able to access the home page:
![Bettercap home page](https://user-images.githubusercontent.com/56458738/79672454-02e28d00-81ca-11ea-9f82-79065cef45f6.png)
On the usage page, it says "Edit the default credentials in /usr/local/share/bettercap/caplets/http-ui.cap". However, when I try to access the http-ui.cap file, I get a message saying "The file http-ui" is a capture file in a format that Wireshark does not understand." So I am wondering what I can do to fix this.
I also note that the http-ui file has a different path to the one stated on the usage page. It says the required path is  /usr/local/share/bettercap/caplets/http-ui.cap, but when I try to follow this path, there is no caplets folder in the bettercap folder, only a folder called ui that contains numerous other files. There is a caplets folder in the path /ProgramData/bettercap/caplets. So would I need to transfer the folder to the path shown on the Usage page?

**Comment by buffermet** [comment]
You're trying to open a caplet file using Wireshark because your machine thinks it is a PCAP file.
