### ISSUE TITLE
Problems with connecting to webui HTTP 405

### ISSUE THREAD

**Issue by altucor** [bettercap/bettercap#724]
So i just installed bettercap, downloaded latest relaese from github and unpacked it. Installed webui and im abbe to login in to it only once after this im started receiving HTTP 405 error. Im getting this error when trying to connect from Chrome, in Firefox i can see only blank screen.
I thought it can be problems in browsers and certificates so i tried connect with wget and got same error, below at the end i have two logs from bettercap server and wget client machine.

Also there is not obvious behaviour of http-ui caplet. I thought i can use this instead of https version and connect from other machine. But im not able to establish connection. Yep i've read https://www.bettercap.org/usage/#web-ui page and saw information about http version which works only for localhost connections, but i thought it is just recommendations and both servers able receive requests from any hosts.

### Environment

Please provide:

* bettercap v2.27.1 (built for linux amd64 with go1.13.10)
* (Proxmox container ubuntu 16.04) Linux bettercap 5.0.15-1-pve #1 SMP PVE 5.0.15-1 (Wed, 03 Jul 2019 10:51:57 +0200) x86_64 x86_64 x86_64 GNU/Linux
* go version go1.6.2 linux/amd64 
* Command line arguments you are using.
root@bettercap:~# ./bettercap -caplet https-ui -debug
* Caplet code you are using or the interactive session commands.
root@bettercap:~# cat /usr/local/share/bettercap/caplets/https-ui.cap 
# api listening on https://0.0.0.0:8083/ and ui on https://0.0.0.0
set api.rest.address 0.0.0.0
set api.rest.port 8083
set https.server.address 0.0.0.0
set https.server.port 443

# make sure both use the same https certificate so api requests won't fail
set https.server.certificate ~/.bettercap-https.cert.pem
set https.server.key ~/.bettercap-https.key.pem 
set api.rest.certificate ~/.bettercap-https.cert.pem
set api.rest.key ~/.bettercap-https.key.pem 
# default installation path of the ui
set https.server.path /usr/local/share/bettercap/ui

# !!! CHANGE THESE !!!
set api.rest.username *hidden*
set api.rest.password *hidden*

# go!
api.rest on
https.server on
root@bettercap:~# 

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
**Server log:**
root@bettercap:~# ./bettercap -caplet https-ui -debug
bettercap v2.27.1 (built for linux amd64 with go1.13.10) [type 'help' for a list of commands]

[20:59:05] [sys.log] [dbg] FindGateway(eth0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[20:59:05] [sys.log] [dbg] FindGateway(eth0) output:
default via 10.0.0.1 dev eth0 
10.0.0.0/8 dev eth0  proto kernel  scope link  src 10.0.0.51
[20:59:05] [sys.log] [dbg] FindGateway(eth0) line 'default via 10.0.0.1 dev eth0' matched with [default via 10.0.0.1 dev eth0 default 10.0.0.1 eth0]
[20:59:05] [sys.log] [dbg] gateway is 10.0.0.1[6c:3b:6b:3d:1d:5c]
[20:59:05] [session.started] {session.started 2020-04-25 20:59:05.373421627 +0000 UTC m=+0.110476769 <nil>}
[20:59:05] [mod.started] events.stream
[20:59:05] [sys.log] [dbg] api.rest {Bits:4096 Country:US Locality: Organization:bettercap devteam OrganizationalUnit:https://bettercap.org/ CommonName:bettercap}
[20:59:05] [sys.log] [inf] api.rest generating TLS key to /root/.bettercap-https.key.pem
[20:59:05] [sys.log] [inf] api.rest generating TLS certificate to /root/.bettercap-https.cert.pem
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [mod.started] api.rest
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [sys.log] [inf] https.server loading server TLS certificate from /root/.bettercap-https.cert.pem
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [mod.started] https.server
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [sys.log] [inf] https.server starting on https://0.0.0.0:443
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [sys.log] [inf] api.rest api server starting on https://0.0.0.0:8083
10.0.0.0/8 > 10.0.0.51  » [20:59:12] [sys.log] [inf] https.server loading server TLS key from /root/.bettercap-https.key.pem
10.0.0.0/8 > 10.0.0.51  » 2020/04/25 20:59:24 http: TLS handshake error from 10.0.0.2:64814: remote error: tls: unknown certificate
2020/04/25 20:59:25 http: TLS handshake error from 10.0.0.2:64815: remote error: tls: unknown certificate
2020/04/25 20:59:34 http: TLS handshake error from 10.0.0.2:64819: remote error: tls: unknown certificate
2020/04/25 21:00:07 http: TLS handshake error from 10.0.0.2:64825: remote error: tls: unknown certificate
2020/04/25 21:00:21 http: TLS handshake error from 10.0.0.2:64826: remote error: tls: unknown certificate
10.0.0.0/8 > 10.0.0.51  » ^C
Are you sure you want to quit this session? y/n y
[21:03:51] [mod.stopped] api.rest

*Client log:*
MY@MY-PC:~$ wget https://10.0.0.51
--2020-04-26 00:00:41--  https://10.0.0.51/
Connecting to 10.0.0.51:443... connected.
ERROR: cannot verify 10.0.0.51's certificate, issued by ‘CN=bettercap,OU=https://bettercap.org/,O=bettercap devteam,L=,C=US’:
  Self-signed certificate encountered.
    ERROR: certificate common name ‘bettercap’ doesn't match requested host name ‘10.0.0.51’.
To connect to 10.0.0.51 insecurely, use `--no-check-certificate'.
MY@MY-PC:~$ wget --no-check-certificate https://10.0.0.51
--2020-04-26 00:00:52--  https://10.0.0.51/
Connecting to 10.0.0.51:443... connected.
WARNING: cannot verify 10.0.0.51's certificate, issued by ‘CN=bettercap,OU=https://bettercap.org/,O=bettercap devteam,L=,C=US’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘bettercap’ doesn't match requested host name ‘10.0.0.51’.
HTTP request sent, awaiting response... 405 Method Not Allowed
2020-04-26 00:00:52 ERROR 405: Method Not Allowed.

MY@MY-PC:~$

--------------------------------------------------------------------------------------------
And experiments with http not secure server
*Server Side*
root@bettercap:~# lsof -i -P -n
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
dhclient    223 root    6u  IPv4 21292699      0t0  UDP *:68
master      377 root   12u  IPv4 21293908      0t0  TCP 127.0.0.1:25 (LISTEN)
master      377 root   13u  IPv6 21293909      0t0  TCP [::1]:25 (LISTEN)
sshd      25052 root    3u  IPv4 21863007      0t0  TCP *:22 (LISTEN)
sshd      25052 root    4u  IPv6 21863009      0t0  TCP *:22 (LISTEN)
sshd      25053 root    3u  IPv4 21866609      0t0  TCP 10.0.0.51:22->10.0.0.2:64592 (ESTABLISHED)
bettercap 25354 root    6u  IPv6 21984054      0t0  TCP *:8081 (LISTEN)
bettercap 25354 root    7u  IPv6 21984056      0t0  TCP *:80 (LISTEN)
root@bettercap:~#

*Client side*
MY@MY-PC:~$ wget http://10.0.0.51
--2020-04-26 00:20:31--  http://10.0.0.51/
Connecting to 10.0.0.51:80... failed: Connection refused.
MY@MY-PC:~$

### Steps to Reproduce

1. *Run bettercap with web ui*
2. *Try to connect to the web ui*

**Expected behavior:** *Web ui should be displayed*

**Actual behavior:** *Receiving 405 HTTP error from server*

**Comment by evilsocket** [comment]
i need the error you have in the browser dev console please

**Comment by om8n** [comment]
gg33

**Comment by joao-d-oliveira** [comment]
Hi! Recently having the same issue.

I thought that it could be due to the default listening port (443) which I changed in the configuration to something else (given 443 is occupied with another thing, not webserver)

Then updated to the last version of bettercap (compiled myself:  `bettercap v2.32.0 (built for linux amd64 with go1.13.8)`
And re-downloaded the caplets and ui

Kept the default path to: `/usr/local/share/bettercap/ui` and "simplified the index.html file just to display something... and still didn't get it to work.

I believe it might have to do with some issue of the webserver not linking the requests to /usr/local/share/bettercap/ui/index.html

The browser dev console doesn't say much, only says:
> Error (red): Failed to load resource: the server responded with a status of 405 ()
> Warning (yellow): crbug/1173575, non-JS module files deprecated. 

(Not sure the warning is connected with the error.)

**Comment by joao-d-oliveira** [comment]
Tried further debugging on a different browser and got a bit more information that might be useful.
> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

> **Response Header (Raw)**:
[HTTP/2 405 Method Not Allowed 126ms]	
GET https://192.168.1.8:808/
Status 405
Method Not Allowed
VersionHTTP/2
Transferred109 B (0 B size)    	
    HTTP/2 405 Method Not Allowed
    content-length: 0
    date: Sun, 26 Sep 2021 19:13:37 GMT
    X-Firefox-Spdy: h2
    GET / HTTP/2
    Host: 192.168.1.8:808
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive
    Upgrade-Insecure-Requests: 1
    Sec-Fetch-Dest: document
    Sec-Fetch-Mode: navigate
    Sec-Fetch-Site: none
    Sec-Fetch-User: ?1

**Comment by farmerb0i** [comment]
I believe the issue could be with the relative path in the caplet file. 
When I run the following on my kali box, I typically run with sudo. 
> **sudo** bettercap -caplet https-ui  
I see the following
`[20:27:34] [sys.log] [inf] gateway monitor started ...
[20:27:34] [sys.log] [inf] api.rest loading TLS key from /root/.bettercap-https.key.pem
[20:27:34] [sys.log] [inf] api.rest loading TLS certificate from /root/.bettercap-https.cert.pem`
Note that the caplet shows 
`set https.server.certificate **~/.bettercap-https.cert.pem**`

Which is not where the caplet is expecting it's path to be;  in my case `/home/kali/.bettercap-https.cert.pem`

If I explicitly set my filepath in the caplet then it works. 
I'd be interested to know if this works for anybody else.??
