### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by rfitzpatrick1** [bettercap/bettercap#725]
I have successfully installed Bettercap v2.27.1 to my computer and am able to access the web UI login page. I am now wondering how to find my username and password. The usage page says "Edit the default credentials in /usr/local/share/bettercap/caplets/http-ui.cap", but when I try to access the http-ui capture file, I get a message saying "The capture file is not a capture file in a format that Wireshark understands" Why would this be? Have I misinterpreted what it says on the Usage page, and is there a way to fix this problem? I haven't (knowingly) run caplets.update more than once.

**Comment by buffermet** [comment]
You define them with the `api.rest.username` and `api.rest.password` variables in the http-ui.cap script that you executed.

It will help if you read the documentation, the answer to your question is already there: https://www.bettercap.org/usage/

**Comment by buffermet** [comment]
You define them with the `api.rest.username` and `api.rest.password` variables in the http-ui.cap script that you executed.

It will help if you read the documentation, the answer to your question is already there: https://www.bettercap.org/usage/

**Comment by buffermet** [comment]
Note that the `.cap` file is a caplet file which bettercap evaluates, not a PCAP file.

**Comment by nazariyv** [comment]
@buffermet lol I have got everything working but can't figure out where to get the rest api username and password 🤦‍♂️

**Comment by msmyers** [comment]
It's in "./caplets/https-ui.cap" and the default appears to be "user" and "pass"
