### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/bettercap/bettercap/v2

### ISSUE THREAD

**Issue by KateGo520** [bettercap/bettercap#727]
## Background
The `github.com/bettercap/bettercap` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v2`. And it’s module path is `"github.com/bettercap/bettercap"`, instead of `"github.com/bettercap/bettercap/v2"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v2.26.1 of the `bettercap/bettercap`:
```
$ go get github.com/bettercap/bettercap@v2.27.1
go: finding github.com/bettercap/bettercap v2.27.1
go: finding github.com/bettercap/bettercap v2.27.1
go get github.com/bettercap/bettercap@v2.27.1: github.com/bettercap/bettercap@v2.27.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
run `go get github.com/bettercap/bettercap`, the version will stuck in v2.24.1:
```
$go get github.com/bettercap/bettercap
go: downloading github.com/bettercap/bettercap v2.24.1+incompatible
go: github.com/bettercap/bettercap upgrade => v2.24.1+incompatible
```
SO anyone using Go modules will not be able to easily use any newer version of `bettercap/bettercap`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/bettercap/bettercap/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v2 `subdirectory` (github.com/bettercap/bettercap/v2) and place a new go.mod file in that subdirectory. The `module path` must end with `/v2`. Copy or move the code into the v2 subdirectory. Update `import statements` within the module to also use `/v2` (import "github.com/bettercap/bettercap/v2/…"). Tag the release with `v2.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/bettercap/bettercap@version-tag`, module users need to use this following way to get the `bettercap/bettercap`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/bettercap/bettercap@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `bettercap/bettercap`.

**[*]** You can see who will be affected here: [5 module users, e.g., n0ot/nvremoted, 84KaliPleXon3/bettercap, nu11secur1ty/bettercap_dev_mod]
https://github.com/search?q=bettercap%2Fbettercap+filename%3Ago.mod
## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by KateGo520** [comment]
@buffermet  @evilsocket

**Comment by Nicceboy** [comment]
This similar problem occurred to me, when trying to install specific version with go. 
For example 
```console
GO111MODULE=on go list -m  -versions github.com/bettercap/bettercap
```
Can be used to list all versions, and only following versions are listed:
```
github.com/bettercap/bettercap v2.0.0+incompatible v2.3.1+incompatible v2.11.1+incompatible v2.13.1+incompatible v2.21.1+incompatible v2.24.1+incompatible
```
So it is quite hard to install specific version of bettercap only by using go package manager or use as dependency.

**Comment by falgunxd** [comment]
### Easiest solution

when executing the command 
`go get -u github.com/bettercap/bettercap`

following error can be seen:

> go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

This clearly mentions **go get is not supported outside a module. To build and install a command, use 'go install' with a version**
meaning, we should instead use the following command
`go install github.com/bettercap/bettercap@latest`

This works.
