### ISSUE TITLE
bettercap --target nor -TY works

### ISSUE THREAD

**Issue by eliassal** [bettercap/bettercap#730]
*Description of the bug or feature request*

### Environment

* Bettercap version  v2.26.1 (built for linux amd64 with go1.13.3)

* Debian (Kali2020 virtual machine).
using 
* bettercap --target 192.168.1.27 --proxy -P POST

### Steps to Reproduce

1. open terminal
2. Run the command above

**Expected behavior:** *Bettercap to run and start the different services to test MitM on a target*
I am following some tutorials and all suggest using this form of statement

**Actual behavior:** *flag provided but not defined: -target
Usage of bettercap:
  -autostart string
        Comma separated list of modules to auto start. (default "events.stream")
  -caplet string
        Read commands from this file and execute them in the interactive session.
  -cpu-profile file
        Write cpu profile file.
...........
..........*

-- 

![betterCap](https://user-images.githubusercontent.com/8447864/82080044-2a9f1500-96e4-11ea-8ba3-943a0565834e.jpg)

**Comment by buffermet** [comment]
You're trying to use flags from the legacy version which is no longer supported. Read the docs of v2.x at https://www.bettercap.org/

**Comment by eliassal** [comment]
Thanks, I went through the "usage", not able to find what replaced " -T" or "--target argument.
