### ISSUE TITLE
can't install bettercap from kali terminal using apt-get install

### ISSUE THREAD

**Issue by jigsaw678** [bettercap/bettercap#732]
`Err:1 http://kali.download/kali kali-rolling/main amd64 bettercap-caplets all 0+git20200110-0kali1
  403  Forbidden [IP: 104.18.103.100 80]
E: Failed to fetch http://kali.download/kali/pool/main/b/bettercap-caplets/bettercap-caplets_0+git20200110-0kali1_all.deb  403  Forbidden [IP: 104.18.103.100 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by rafaribe** [comment]
Please check the [installation instructions](https://www.bettercap.org/installation/).

**Comment by buffermet** [comment]
Closing as correct solution is provided.

**Comment by d3k4-k3rb3r0s** [comment]
Solution doesn't help
