### ISSUE TITLE
windows cmd no colors problem

### ISSUE THREAD

**Issue by elig0n** [bettercap/bettercap#736]
On Windows 10 :

    WARNING: This terminal does not support colors, view will be very limited.

    bettercap v2.27.1 (built for windows amd64 with go1.13.10) [type 'help' for a list of commands]

typing any letter at the prompt is then accompanied by color codes i.e.

    » e[J[2KK

In [Windows Terminal ](https://github.com/microsoft/terminal) color codes are not displayed but redrawing refresh is noticeable with every character typed.

**Comment by Nightmare247** [comment]
i think the solution might be to put -no-colors argument

**Comment by elig0n** [comment]
-no-colors shows: `WARNING: Terminal colors have been disabled, view will be very limited.`
but still shows  these escape symbols appended at the end of the input cursor: `←[J←[2K`
also it's a shame because the windows cmd.exe terminal does support colors so this can be worked around in a PR

**Comment by buffermet** [comment]
That's probably because your input prompt is stored in a separate variable.

You can use the following command to change it:

`set $ ""`

**Comment by elig0n** [comment]
@buffermet that only changes the prompt which is before the input cursor/caret. The escape characters appear after the caret.

**Comment by MattPlayGamez** [comment]
@elig0n sorry for this random question.
But how did you install it on Windows?
I can't find a guide or anything in particular.
Have a nice day,
Matthew.

**Comment by lmediavilla** [comment]
Just install npcap and it will run bettercap on windows [https://npcap.com/#download](url)
