### ISSUE TITLE
Web UI shows a blank page

### ISSUE THREAD

**Issue by mYnDstrEAm** [bettercap/bettercap#737]
When starting the Web UI with `http-ui on` or exactly as described in the documentation with `sudo bettercap -caplet http-ui` after having changed the credentials in `/usr/share/bettercap/caplets/http-ui.cap` (/usr/local/share does not have a bettercap folder) I'm getting just a blank page with the bettercap favicon and bettercap set as the page title.

It might have to do with some other problems that cause the sniffing to not really work. [I asked about it here](https://security.stackexchange.com/questions/231471/why-does-bettercap-not-capture-any-traffic-and-why-is-its-web-ui-just-a-blank-pa).

### Environment

* Bettercap version v2.27.1
* Kali Linux 64bit
* Command `sudo bettercap` / `sudo bettercap -debug` (and `sudo bettercap -caplet http-ui`)
* Full debug output:
```
>> http-ui on
[mod.started] api.rest
[sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
[mod.started] http.server
[sys.log] [inf] http.server starting on http://127.0.0.1:80
>> 
```

### Steps to Reproduce

1. Start Kali Linux virtual machine on Debian/KDE with nftables firewall
2. Start bettercap
3. Turn on http-ui
4. Open localhost with preinstalled Kali Linux browser

**Expected behavior:** I expected it to show the Web UI.

**Actual behavior:** It showed a blank/empty/white page.

**Comment by benkhouya** [comment]
Same here!

**Comment by cyrus104** [comment]
Same here, there is a similar issue on github.com/bettercap/ui which has a recommended fix but I just tried it and it did not work.

**Comment by avmiz** [comment]
same at me

**Comment by drneox** [comment]
I had a similar problem in kali, because kali install bettercap in different path by default,  this was resolved installing golang and compile bettercap from command line as describe in the oficial website:
[](https://www.bettercap.org/installation/)

1. go get github.com/bettercap/bettercap
2. cd $GOPATH/src/github.com/bettercap/bettercap
3. make build 
4. sudo make install

**Comment by rielinux** [comment]
Yeah....me too, my browser said " 404 page not found "

**Comment by Excalibur025** [comment]
Also getting the "404 page not found" error although it only seems to happen with https-ui. Running without SSL locally seems to work okay. 

Tried an alternate clean install and build with npm instead of git and still didn't cooperate. Tested in elinks to make sure it wasn't firefox or midori misbehaving. Still nothing.

**Comment by Ahmet1s2** [comment]
philmacrack can you explain how docker downloads cuz this code is not workin

**Comment by j3hst3hr** [comment]
+1 here

checking the console in web browser:

main.ec83a59338123ba3bb5d.js:formatted:4107 ERROR TypeError: Cannot read properties of undefined (reading 'devices')
    at n.updateSession (main.ec83a59338123ba3bb5d.js:formatted:30617:43)
    at new n (main.ec83a59338123ba3bb5d.js:formatted:30581:22)
    at ji (main.ec83a59338123ba3bb5d.js:formatted:7187:24)
    at Ai (main.ec83a59338123ba3bb5d.js:formatted:7126:21)
    at po (main.ec83a59338123ba3bb5d.js:formatted:7717:35)
    at Object.oo [as createEmbeddedView] (main.ec83a59338123ba3bb5d.js:formatted:7638:13)
    at t.createEmbeddedView (main.ec83a59338123ba3bb5d.js:formatted:6825:34)
    at n.createEmbeddedView (main.ec83a59338123ba3bb5d.js:formatted:6649:27)
    at n._updateView (main.ec83a59338123ba3bb5d.js:formatted:10030:83)
    at n.set [as ngIf] (main.ec83a59338123ba3bb5d.js:formatted:10002:26)


        function _e(n) {
            for (var t = [], e = 1; e < arguments.length; e++)
                t[e - 1] = arguments[e];
            n.error.apply(n, Object(l.__spread)(t))
        }

the data is indeed loading and being parsed just fine if you check the XHR output... 


any updates on this?

**Comment by highrider0602** [comment]
Also experiencing the same thing. Has anyone found a fix for this yet?

**Comment by sigmamale1980** [comment]
For anyone facing this issue i did:

sudo ln -sf /usr/share/bettercap   /usr/local/share/bettercap

then:

sudo bettercap -caplet http-ui

Good luck guys.

**Comment by keldnorman** [comment]
I made a helper script to install the latest version here:

https://github.com/keldnorman/bettercap2.32.0

**Comment by kingmak** [comment]
got success with the following steps:

first i ran bettercap like this : `sudo bettercap -caplet http-ui -iface eno1 -debug`
next in the terminal type : `ui.version` {should say something like ui folder does not exist, so lets install it}
next in the terminal type : `ui.update` {should install the ui}
next in the terminal type : `quit`

now run bettercap again with the http-ui caplet (reference above) and visit the webpage. it should have a login page. Hope it helps!

**Comment by sigmamale1980** [comment]
Thanks for the steps. It worked.

**Comment by chr0n1x** [comment]
@kingmak I just tried this on version 2.42.x. `ui.update` and `ui.version` don't work. any idea what I could be doing wrong? I have net connection and everything, I've tried binding the services (http, ui, api, etc) to the default loopback, lan IP, even changing the port and nothing is working

(trying to access the UI from a remote machine on my lan)
