### ISSUE TITLE
Problem with net.sniff

### ISSUE THREAD

**Issue by devilmen80** [bettercap/bettercap#738]
Hello,
I'm running latest version of bettercap.
Now,my problem is that after having activate all modules (net.recon on,arp.spoof on,http.proxy on, https.proxy,net.sniff on and net.probe on I can see only the traffic mdns.Someone can help me??

**Comment by prohurtz** [comment]
I have same problem, someone help please

**Comment by buffermet** [comment]
Read the documentation... https://www.bettercap.org/

**Comment by gokulash123** [comment]
**On all the below mentioned:**
http.proxy on
http.server on
https.proxy on

**once you have done** 
specify the target, arp spoof, and  with below command 
1. set arp.spoof.targets <ip>; arp.spoof on; 
2. net.sniff on

_It will work in smooth without any error_

**Comment by OGTech1** [comment]
> **On all the below mentioned:** http.proxy on http.server on https.proxy on
> 
> **once you have done** specify the target, arp spoof, and with below command
> 
> 1. set arp.spoof.targets ; arp.spoof on;
> 2. net.sniff on
> 
> _It will work in smooth without any error_

**Comment by OGTech1** [comment]
Tried the http proxy, server on and https proxy on but still didn't worked.  Will be glad if anybody can be of assistance.  Thank you in advance
