### ISSUE TITLE
Using bettercap to view Client Hello of Handshake phase TLS

### ISSUE THREAD

**Issue by alicelangertton** [bettercap/bettercap#750]
Hi guys,

I wanted to know if I can use bettercap to view the Handshake phase of a connection between a client and a server(as we do easily with Wireshark). For ex. to view Client Hello and all other things that it includes : cipher suites etc.
Is it possible to view this using bettercap?

**Comment by buffermet** [comment]
Yes you can. This is already documented at https://www.bettercap.org/

You want to use the packet proxy.
