### ISSUE TITLE
bettercap on windows shows wrong ip and adapter and weird text

### ISSUE THREAD

**Issue by minanagehsalalma** [bettercap/bettercap#756]
i downloaded the last one from here 
https://github.com/bettercap/bettercap/releases

`bettercap_windows_amd64_v2.28.zip`

![image](https://user-images.githubusercontent.com/20546638/87991009-7c4d8c80-cae5-11ea-93b9-988007a7dc09.png)

i don't know what even this adapter is .
i have npcap  latest version already installed.

**Comment by minanagehsalalma** [comment]
@evilsocket why ?

**Comment by evilsocket** [comment]
because you didn't fill the issue template, which at the end says:

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by minanagehsalalma** [comment]
> because you didn't fill the issue template, 

@evilsocket i think have provided enough info ... and i have checked the template now and it won't diff much.

**Comment by evilsocket** [comment]
you didn't say which OS version you're running this stuff on, what command line did you use to start bettercap, which caplets you enabled, wether you're runing it in bash, cygwin or just plain cmd.exe. Just to name a few things you missed.
