### ISSUE TITLE
compile 32 bit PLEASE PLS

### ISSUE THREAD

**Issue by alexalwks2** [bettercap/bettercap#758]
Cannot compile on 32 bit at all.

Can you give instructions or make 1 build for 64 bit and for 32 bit also?

Thank you.

**Comment by dan-sec** [comment]
Here you have one: https://github.com/dan-sec/bc32bit.
I hope it helps.

**Comment by alexalwks2** [comment]
thank you

**Comment by buffermet** [comment]
I assume that none of the maintainers are running on a 32-bit system, nor plan on doing so.

Since you are provided with someone's binary, I'm closing this issue.
