### ISSUE TITLE
bettercap arp.spoof via smartphone tethering and wifi pineapple

### ISSUE THREAD

**Issue by GregorBiswanger** [bettercap/bettercap#763]
Hey Community, 
my pineapple nano is connected via wifi on my android smartphone.. my notebook too.. on my notebook I used hyper-v with kali and bettercap v2.28.. I can ping from kali to my pineapple and from my pineapple to kali without any problems... If I start bettercap I see the pineapple... but with arp spoofing, I can see only the internet requests from my notebook?! I connected me with ssh and execute curl etc. but I don´t see anything on my bettercap?! have anyone a Idea?

p.s. the internet connection gives my android smartphone via tethering

**Comment by GregorBiswanger** [comment]
I activated `arp.spoof.fullduplex` and now I get dns resolutions of loaded libaries (google analytics etc.) from the requests .. I still don't see the url actually called. 

Unfortunately, the request from the victim device is constantly interrupted. 

What could that be? Everything works fine without tethering via my smartphone, via wifi router at home.

**Comment by GregorBiswanger** [comment]
javascript injection does not work with fullduplex either .. tested with beef.js - without tethering, as already mentioned everything works fine and that even without fullduplex.

**Comment by GregorBiswanger** [comment]
I found the solution to my problem. I have to make a port forwarding on the pineapple (iptables PREROUTING) to the running http(s) proxies of bettercap.

https://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/

**Comment by ChillVibesMushroom** [comment]
> I found the solution to my problem. I have to make a port forwarding on the pineapple (iptables PREROUTING) to the running http(s) proxies of bettercap.
> 
> https://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/

Can you install bettercap on the wifi pineapple
