### ISSUE TITLE
massdeauth does nothing

### ISSUE THREAD

**Issue by cyberthingsforgeeks** [bettercap/bettercap#767]
---

*I run massdeauth caplet: nothing happens*

### Environment

* bettercap v2.28 (built for linux arm64 with go1.13.12)
* Kali Linux RaspberryPi 3B+ (64-Bit). arm64.
(actually I also tried with armhf 32 bit version of kali, with the same raspberry, but still same bug)
* sudo ./bettercap -caplet massdeauth
* caplet: massdeauth default
* **
[22:08:37] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[22:08:37] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.1.1 dev wlan0 proto dhcp metric 600 
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.169 metric 600
[22:08:37] [sys.log] [inf] wifi using interface wlan0 (MYMACADDRESS)
[22:07:51] [sys.log] [dbg] wifi hopping on channel 2
wlan0 » [22:07:51] [sys.log] [dbg] SetInterfaceChannel(wlan0, 2) iw based
wlan0 » [22:07:52] [sys.log] [dbg] wifi hopping on channel 3
wlan0 » [22:07:52] [sys.log] [dbg] SetInterfaceChannel(wlan0, 3) iw based
wlan0 » [22:07:52] [sys.log] [dbg] wifi hopping on channel 4
wlan0 » [22:07:52] [sys.log] [dbg] SetInterfaceChannel(wlan0, 4) iw based
wlan0 » [22:07:53] [sys.log] [dbg] wifi hopping on channel 5
wlan0 » [22:07:53] [sys.log] [dbg] SetInterfaceChannel(wlan0, 5) iw based
wlan0 » [22:07:53] [sys.log] [dbg] wifi hopping on channel 6
wlan0 » [22:07:53] [sys.log] [dbg] SetInterfaceChannel(wlan0, 6) iw based
wlan0 » [22:07:54] [sys.log] [dbg] wifi hopping on channel 7
wlan0 » [22:07:54] [sys.log] [dbg] SetInterfaceChannel(wlan0, 7) iw based
wlan0 » [22:07:54] [sys.log] [dbg] wifi hopping on channel 8
wlan0 » [22:07:54] [sys.log] [dbg] SetInterfaceChannel(wlan0, 8) iw based
wlan0 » [22:07:55] [sys.log] [dbg] wifi hopping on channel 9
wlan0 » [22:07:55] [sys.log] [dbg] SetInterfaceChannel(wlan0, 9) iw based
wlan0 » [22:07:55] [sys.log] [dbg] wifi hopping on channel 10
wlan0 » [22:07:55] [sys.log] [dbg] SetInterfaceChannel(wlan0, 10) iw based
wlan0 » [22:07:56] [sys.log] [dbg] wifi hopping on channel 11
wlan0 » [22:07:56] [sys.log] [dbg] SetInterfaceChannel(wlan0, 11) iw based
wlan0 » [22:07:56] [sys.log] [dbg] wifi hopping on channel 12
wlan0 » [22:07:56] [sys.log] [dbg] SetInterfaceChannel(wlan0, 12) iw based
wlan0 » [22:07:57] [sys.log] [dbg] wifi hopping on channel 13
_AND CONTINUES IN LOOP INDEFINITELY_** 

### Steps to Reproduce

Just execute `sudo ./bettercap -caplet massdeauth`.
You'll see it does nothing, it's stucks and continue to refresh without doing anything.

--

**Comment by cyberthingsforgeeks** [comment]
up

**Comment by buffermet** [comment]
Hi,

It doesn't look like you're sending any deauth/disassoc packets. You're just hopping channels.

What wireless adapter are you using? Does it support packet injection and monitor mode?

The documentation states:

> wifi.deauth BSSID : Start a 802.11 deauth attack, if an access point BSSID is provided, every client will be deauthenticated, otherwise only the selected client. Use 'all', '*' or a broadcast BSSID (ff:ff:ff:ff:ff:ff) to iterate every access point with at least one client and start a deauth attack for each one.

My guess is that you are not in monitor mode and therefore bettercap is not finding any APs with clients.
