### ISSUE TITLE
What does this net.fuzz module do

### ISSUE THREAD

**Issue by LotusPs** [bettercap/bettercap#768]
What is the principle of net.fuzz module and where can it be used?

**Comment by buffermet** [comment]
Wouldn't it be great if there was documentation alongside bettercap 🤔 

https://www.bettercap.org/

**Comment by numoworld** [comment]
Can you provide any information on what is fuzzing in this context? Like any articles that would help

**Comment by evilsocket** [comment]
@numoworld you can see how to use net.fuzz in the examples here https://www.bettercap.org/modules/ethernet/net.sniff/#examples

**Comment by evilsocket** [comment]
Change 90% of mDNS incoming packets by fuzzing 40% of their payload (will reinject fuzzed packets):

```
set net.sniff.verbose true
set net.fuzz.rate 0.9
set net.fuzz.ratio 0.4
set net.fuzz.silent false
set net.fuzz.layers Payload
set net.sniff.filter "host 224.0.0.251 and port 5353"
net.fuzz on
```

Change 100% of WiFi packets by fuzzing 70% of their Dot11InformationElement and Dot11Data layers:

```
set net.sniff.verbose true
set net.fuzz.rate 1.0
set net.fuzz.ratio 0.7
set net.fuzz.layers Dot11InformationElement, Dot11Data
net.fuzz on
```
