### ISSUE TITLE
Mac Os Catalina When trying to start Ble.recon I get: panic: interface conversion: interface {} is nil, not xpc.Dict 

### ISSUE THREAD

**Issue by Thman558** [bettercap/bettercap#769]
I am using version 2.28
I am on Mac Os Catalina 10.15.6 I installed bettercap from the darwin installer
go version go1.15 darwin/amd64
ble.recon on
ble.recon on

ble.recon on
panic: interface conversion: interface {} is nil, not xpc.Dict

goroutine 17 [running, locked to thread]:
github.com/bettercap/gatt/xpc.Dict.MustGetDict(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bettercap/gatt@v0.0.0-20191018133023-569d3d9372bb/xpc/xpc_darwin.go:39
github.com/bettercap/gatt.(*device).HandleXpcEvent(0xc0006b4b80, 0xc000540960, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bettercap/gatt@v0.0.0-20191018133023-569d3d9372bb/device_darwin.go:453 +0x1545
github.com/bettercap/gatt/xpc.handleXpcEvent(0x6107270, 0xc000737718)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bettercap/gatt@v0.0.0-20191018133023-569d3d9372bb/xpc/xpc_darwin.go:214 +0x222
github.com/bettercap/gatt/xpc._cgoexpwrap_40d1f51a8537_handleXpcEvent(0x6107270, 0xc000737718)
	_cgo_gotypes.go:464 +0x35

1. Start bettercap
2. start ble.recon
3. and then the error

I expected it to start Bluetooth low energy
It failed

**Comment by evilsocket** [comment]
BLE XPC messages keep changing across macOS versions, and it's closed source of course ... i doubt we'll be ever able to properly support BLE on mac :/ maybe i should just remove the feature from mac

**Comment by ajtazer** [comment]
> maybe i should just remove the feature from mac

Noooooo😭
pls make it work
