### ISSUE TITLE
DNS SPOOFING ONLY 1 IP TARGET

### ISSUE THREAD

**Issue by hugollores19** [bettercap/bettercap#772]
Hello,
is possible do set Dns Spoof for only 1 target? 

Because after setting arp.spoof and dns.spoof work in all network of interface, but I would like set dns spoof only for 1 ip of all

Thank You

**Comment by Nightmare247** [comment]
i am not 100% sure, but i think that first you arp spoof your target then dns spoof them. Then i think you will acheive what you are saying. Again, im not sure

**Comment by buffermet** [comment]
In the case that you are the gateway, you will not need to ARP spoof, so directly targeting the victim using the `dns.spoof` module would be an enhancement.
