### ISSUE TITLE
SSLstrip - Add an option to disable domain spoofing

### ISSUE THREAD

**Issue by duckdeeper** [bettercap/bettercap#780]
This is a feature request.
Adding an option to disable domain spoofing in http proxy module would be a nice feature. For non HSTS websites, domain spoofing is unnecessary.
I think @Petitoto can do this easily.
Thanks.

**Comment by buffermet** [comment]
Do you mean the `ノ` character that gets added to the TLD?

You can already disable that by setting the `http.proxy.sslstrip.useIDN` var to `false`, but this should be removed for [this reason](https://github.com/bettercap/bettercap/pull/770#issuecomment-700409925).

**Comment by Petitoto** [comment]
I think he means disabling any domain spoofing (currently sslstrip doubles last character of the TLD).
This is done in #770, which also adds the ability to choose how domains are spoofed and removes the useIDN option. I will investigate next week the issue mentionned by @buffermet which lead to close the PR, but if @duckdeeper you could test it, it would be interesting 👌

**Comment by buffermet** [comment]
@Petitoto please see https://github.com/bettercap/bettercap/pull/770#issuecomment-700409925 where I explained why this way of spoofing domains on the proxy side is a bad idea.

**Comment by duckdeeper** [comment]
> I think he means disabling any domain spoofing (currently sslstrip doubles last character of the TLD).
> This is done in #770, which also adds the ability to choose how domains are spoofed and removes the useIDN option. I will investigate next week the issue mentionned by @buffermet which lead to close the PR, but if @duckdeeper you could test it, it would be interesting ok_hand

Yes i mean this exactly.

I think this https://github.com/bettercap/bettercap/pull/770 would be a nice feature if its get merged. Giving bettercap an another useful built in feature. But i also think SSLstrip must not spoof domains. Automatic domain spoofing must be in another module or something?

**Comment by buffermet** [comment]
@duckdeeper see https://github.com/bettercap/caplets/tree/master/hstshijack.
