### ISSUE TITLE
Error eth0: You don't have permission to capture on that device (socket: Operation not permitted)

### ISSUE THREAD

**Issue by uhuhuhuhuhuhuhuh** [bettercap/bettercap#783]
getting this error 
eth0: You don't have permission to capture on that device (socket: Operation not permitted)
do i need to get an adapter or is it something i need to download

**Comment by evilsocket** [comment]
use sudo (google "linux sudo" if you don't know what sudo is)

**Comment by alonek1** [comment]
hey patrick @uhuhuhuhuhuhuhuh , thank you  for your question 😁

**Comment by whoiskumaratul** [comment]
It's a little late, but I just had the same problem. You need to give tcpdump the permission and capability to allow raw packet captures and network interface manipulation.

Add a capture group and add yourself to it:

**sudo groupadd pcap
sudo usermod -a -G pcap $USER**

Next, change the group of tcpdump and set permissions:

**sudo chgrp pcap /usr/sbin/tcpdump
sudo chmod 750 /usr/sbin/tcpdump**

OR


**sudo chgrp pcap /usr/bin/tcpdump
sudo chmod 750 /usr/bin/tcpdump**


Finally, use setcap to give tcpdump the necessary permissions:

sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump

Be careful, that this will allow everybody from the group pcap to manipulate network interfaces and read raw packets!


[www.kumaratuljaiswal.in](https://www.kumaratuljaiswal.in)
[www.hackingtruth.in](https://www.hackingtruth.in)

**Comment by jorgejo26** [comment]
please i am this error both on windows and virtualbox i am new new to this world of ethical hacking,  also i am a fast learner, and i believe  that i can to alot in this space if can find good mentor that can willingly help gain access into the knowledge of this profession
