### ISSUE TITLE
Connect to the UI from another host

### ISSUE THREAD

**Issue by aviv0506** [bettercap/bettercap#786]
*Description of the bug or feature request*
I installed the latest version of Bettercap UI in Raspberry pi in Kali Linux, and it works fine, but I want to remotely connect to the UI through another host (EX- another Windows computer) and I can't get it done.
What I tried to do, is convert the localhost 127.0.0.1 of the Raspberry pi - Kali Linux with Ngrok, to a public IP, and I could see the login page for the UI, but when I tried to connect with the credentials, I got an error: Can't connect to https://0.0.0.0:8083/api

* Bettercap version you are using ( `bettercap -version` ).
* Kali Limux AArch64 (AMD64)

**Comment by Haasie** [comment]
i got the exact same problem.
output of command line says i got a bad certificate.

**Comment by buffermet** [comment]
First of all, 0.0.0.0 is a loopback address.

Second, your report is incomplete.
