### ISSUE TITLE
Can't see 5.0ghz networks with wifi.show and UI

### ISSUE THREAD

**Issue by aviv0506** [bettercap/bettercap#790]
### Environment
Kali linux & Ubunto
Please provide:

* I use the latest version of Bettercap
* Tried with Kali Linux abd with ubunto

Hello,
When starting Bettercap (sudo bettercap -caplet http-ui) UI version everything works fine , exepct for 2 things:
1. The command "wifi.show" show me only 2.4 ghz networks (without 5.0ghz).
2. In the UI, in "WIFI" screen, I can only see 2.4 ghz networks (without the 5.0ghz netwroks).

**Important notes:
- The interface I am using is Alfa360ach (which support both 2.4 and 5.0).
- the interface does show 5.0 ghz networks in bettercap ONLY in the CLI when I run the command: "sudo bettercap -caplet http-ui wlan1", but not in the UI version/the "wifi.show" command.

I had two guesses of what causes the bug:
1. One antena of the Alfa sniff 2.4 ghz and the other sniff 5.0ghz. Maybe the wifi.show command show only one side?
2. Maybe it has something to do with the caplet/file bettercap itself which only take the 2.4 networks?

**Comment by evilsocket** [comment]
if you have multiple wifi interfaces, you need to set the correct one (set wifi.interface wlan1) before starting the wifi module, or you need to start bettercap with -iface wlan1
