### ISSUE TITLE
Terminal usually getting broken with lot of input

### ISSUE THREAD

**Issue by nuschpl** [bettercap/bettercap#793]
It happens often when lot of info is scrolling through betteracap something with encoding happends and chars are unreadable. The only solution is to blindly quit bettercap, issue reset command on Linux and launch it back. It would be more than convinient if bettercap could do terminal reset on it's own without losing current poisoning state- possibly just by issuing system command

**Comment by cgr71ii** [comment]
Have you try to issue "!reset"? It is possible to issue terminal commands from Bettercap UI using "!", but i don't know if it will fix your problem since I have not experienced what you are describing.
