### ISSUE TITLE
Issues with the new wifi.client.probe

### ISSUE THREAD

**Issue by Neal** [bettercap/bettercap#80]
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/bettercap/bettercap).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description

A couple small issues with the new `wifi.client.probe` feature:

- It seem the SSID is cutting off 2 characters at least for some of them.
- On the REST API, `From` isn't encoded properly?

```
{"tag":"wifi.client.probe","time":"2018-02-24T14:17:09.768307-08:00","data":{"From":"4ptDr5Gn","SSID":"TMobileWingm"}}
```
(also notice the SSID should be `TMobileWingman`)

- A way to filter out certain SSID or mac addresses would be nice if possible trivially.

**Comment by evilsocket** [comment]
yeah unfortunately gopacket dot11 support is incomplete to say the least, so [i had to improvise a little](https://github.com/bettercap/bettercap/blob/master/modules/wifi_recon.go#L449) ...

**Comment by Neal** [comment]
No, it's only on `wifi.client.probe` messages, not on `wifi.ap.*` - so that wouldn't affect `wifi.show` right? And it seems it's cutting off 2 characters on all SSIDs on `wifi.client.probe`.

**Comment by evilsocket** [comment]
and do you see the issue while the `wifi.client.probe` events are printed on console? (i'm trying to understand if it's an `api.rest` problem or not).

**Comment by Neal** [comment]
oh yes, I see the issue on console as well. sorry for the confusion.
