### ISSUE TITLE
Binary Lookup Inefficiencies For Linux Distributions

### ISSUE THREAD

**Issue by bonedaddy** [bettercap/bettercap#802]
Currently when using `bettercap` on Linux distributions, there are repeated instances where the `os` package is used to lookup two different binaries (`iw`, and `iwconfig`). When using the `wifi` module of bettercap, in particular when changing wifi channels, each time the channel is to be changed, the `Core::HasBinary` function is used, followed by the `Core::Exec` function. 

Both of these functions will query the OS to see if the corresponding executable exists. While on the surface this isn't problematic, some basic math lets us determine that for a full spectrum scan of 2.4Ghz and 5Ghz networks which has around 50 (possibly more I didnt get an exact number) different channels, thats a total of 100 lookups for a single scan of the entire available 2.4Ghz and 5Ghz spectrum.

If you're running the wifi module for even 10 minutes this will amount to a large number of lookups when in reality a single lookup at the start of `bettercap` and caching that result would be enough. It is *extremely* unlikely you would **ever** uninstall `iw` or `iwconfig` while bettercap is operating, thus we dont even need to consider cache invalidation.

I've implemented this functionality [in a fork of bettercap](https://github.com/bonedaddy/bettercap/pull/5/files) and the speed improvements of using a lookup cache vs looking up the executable every time you want to hop a channel is tremendous:

```
BenchmarkCachedExeLookup-12    	74515759	        15.4 ns/op
BenchmarkDirectExeLookup-12    	        192610	                6177 ns/op
```

This change would lead to massively improved wifi recon capabilities, mass association and mass deauth performance as well. 

As the title of this issue mentions, I don't believe this issue is present on darwin, or windows distributions as those use a single command, whose name and path are hard-coded (i think??)

**Comment by bonedaddy** [comment]
While not strictly related, the `Core::Exec` function is used by a variety of different modules, and could further be optimized to cache the `Os::LookPath`results to increase overall performance.

**Comment by evilsocket** [comment]
fixed by PR 5
