### ISSUE TITLE
[BUG] GPS works with serial device /dev/ttyS0, but will not work with GPSD

### ISSUE THREAD

**Issue by curious-ninja** [bettercap/bettercap#805]
Bettercap refuses to use gpsd for GPS data.
I can see from the gps.go module that gpsd is supported.

When I enter the following commands:
set gps.device localhost:2947
gps on

I get the error:
cannot open localhost:2947: No such file or directory

 Also tried tcp://localhost:2947

Any suggestions?
Thanks

**Comment by gumanov** [comment]
Whoops.

Just realized that gpsd support was added in a commit on Sept 25, 2020.
The latest release is dated Jul 3rd, 2020, v2.28.

So I need to build bettercap from the master branch to get it working, until a new release is out.

**Comment by gumanov** [comment]
So I compiled bettercap from the latest source, and attempted to use gpsd via the gps module settings page in the web=ui.

set gps.device localhost:2947
gps on

I get the following error:
[object ProgressEvent]
Http failure response for (unknown url): 0 Unknown Error

**Comment by evilsocket** [comment]
could you enable debug messages by restarting bettercap with -debug and see if you get this https://github.com/bettercap/bettercap/blob/master/modules/gps/gps.go#L100 ?

**Comment by curious-ninja** [comment]
Here is the error I get when I run it with -debug:

192.168.0.0/16 > 192.168.10.10  » set gps.device 'localhost:2947'
192.168.0.0/16 > 192.168.10.10  » gps on
[16:33:41] [sys.log] [dbg] gps connecting to gpsd at localhost:2947
[16:33:41] [mod.started] gps
192.168.0.0/16 > 192.168.10.10  » panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa80d80]

goroutine 24 [running]:
github.com/tarm/serial.(*Port).Close(0x0, 0x1, 0x400066aa80)
        /root/go/pkg/mod/github.com/tarm/serial@v0.0.0-20180830185346-98f6abe2eb07/serial_linux.go:163 +0x20
github.com/bettercap/bettercap/modules/gps.(*GPS).Start.func1()
        /home/kali/go/src/github.com/bettercap/bettercap/modules/gps/gps.go:205 +0x130
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
        /home/kali/go/src/github.com/bettercap/bettercap/session/module.go:281 +0x160

**Comment by evilsocket** [comment]
if you pull the new code it should be fixed, thanks for reporting the bug!

**Comment by curious-ninja** [comment]
Awesome, thanks!!
