### ISSUE TITLE
when http.proxy on OR https.proxy on appear [sys.log] [err] exit status 4 

### ISSUE THREAD

**Issue by alex01dleek** [bettercap/bettercap#813]
I deploy kali on my android iphone, android version 11. by linux delpoy.
when I set http.proxy on OR https.proxy on ,it  appear  [sys.log] [err] exit status 4 ,and that proxy won‘t work .
I query that on bettercap.org and github, didn't get a solution，so how to fix it,and what about that error code?

**Comment by evilsocket** [comment]
incomplete issue, closing

**Comment by yakhira** [comment]
what is solution? what status 4 mean?

**Comment by evilsocket** [comment]
from https://github.com/bettercap/bettercap/blob/master/ISSUE_TEMPLATE.md

**ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY**
