### ISSUE TITLE
Is there a way to do soft kill in scripts?

### ISSUE THREAD

**Issue by uemahra** [bettercap/bettercap#814]
Hi,
I'm trying to exit bettercap by script, the command I use is ps -ef|grep bettercap|grep -v 'grep'|awk '{print $2}'|xargs kill -9 > /dev/null 2>&1
but if kill bettercap using this, it won't restore targets' origin mac table, so besides ctrl+c, is there a way to exit bettercap and restore targets' mac table in scripts?

**Comment by buffermet** [comment]
Are you saying that you are running bettercap as a daemon and want to preserve the MAC addresses of clients?

You can write the output of bettercap to a file using the `events.stream.output` variable.

You need to provide more details about your setup and caplet.

**Comment by buffermet** [comment]
And since you're only grepping for `bettercap` you can simply kill all bettercap processes with `sudo killall bettercap -9`

**Comment by buffermet** [comment]
If you want to watch the events and interact with the session while writing the events to a file, something like this should do:

`touch bettercap.output && tail -f bettercap.output & sudo bettercap`

**Comment by buffermet** [comment]
See documentation at https://www.bettercap.org/

**Comment by buffermet** [comment]
Ignore my previous comment about tailing the output file.


Looks like you can already interact with the session and write the events to a file (`bettercap.output`) simultaneously using this code in your caplet:

```
set events.stream.output bettercap.output
events.stream off
events.stream on
```

**Comment by uemahra** [comment]
Hi Buffermet,

I already running bettercap in a terminal to do arp and http spoofing. And it works fine. when my javascript finished it's job, it automate triggers my php script to kill bettercap by that command. The problem here is kill bettercap like this, can't restore the target's origin mac table, so it there a way to exit bettercap and restore mac address table besides ctrl+c? cause I can't use ctrl+c to exit bettercap in scripts.

**Comment by buffermet** [comment]
@uemahra like I said, you need to use the following code in your caplet:

```
set events.stream.output bettercap.output
events.stream off
events.stream on
```

That way, when your script kills bettercap, you will have all the MAC addresses of clients that were found on the subnet.

If you set `net.sniff.verbose` to `true` before starting the net.sniff module, you will have all the mDNS info as well.

**Comment by uemahra** [comment]
hi, I think set events.stream.output bettercap.output
events.stream off
events.stream on
is for collecting information. right? What I ask is there a way exit bettercap and restore target's mac address table, cause kill better process won't restore target machine's mac address table, it still consider my kali as a gateway.

**Comment by buffermet** [comment]
> hi, I think set events.stream.output bettercap.output
> 
> events.stream off
> 
> events.stream on
> 
> is for collecting information. right? What I ask is there a way exit bettercap and restore target's mac address table, cause kill better process won't restore target machine's mac address table, it still consider my kali as a gateway.

Yes, if you do `arp.spoof off` it will restore the ARP cache.

**Comment by uemahra** [comment]
how can I pass arp.spoof off to another terminal, my shutdown script is in php, the bettercap runs through ssh, I don't think they can interact. do you have suggestions

**Comment by buffermet** [comment]
You should use the api.rest module, so you can execute commands via authenticated POST requests. See the documentation.

**Comment by uemahra** [comment]
Hi, I used python subprocess finished this, thank you.
