### ISSUE TITLE
Problem setting monitor mode. Only in Bettercap

### ISSUE THREAD

**Issue by wvthoog** [bettercap/bettercap#817]
### Description

So this problem started seemingly out of nowhere a few days ago. Worked correctly before. Bettercap is running within Termux and uses a TP-Link WN722N (Atheros AR9271) via a USB-OTG dongle. The card get recognized and is assigned to WLAN1. Setting monitor mode with iw, iwconfig and airmon-ng all work. Running Wifite and Airodump-NG also both work. 

But when in run **sudo bettercap -debug -iface wlan1**

and do a **wifi.recon on** 

the following error occurs

 wlan1  » wifi.recon on
[07:09:29] [sys.log] [inf] wifi using interface wlan1 (98:de:d0:09:3a:1c)
[07:09:29] [sys.log] [dbg] SetInterfaceTxPower(wlan1, 30) iw based
[07:09:29] [sys.log] [war] wifi could not set interface wlan1 txpower to 30, 'Set Tx Power' requests not supported
[07:09:29] [sys.log] [err] error while setting interface wlan1 in monitor mode: Cannot set rfmon for this handle

From other issues I've read about this was caused by not setting the correct interface at startup. But mine is correct (wlan1) and it supports monitor mode.

To be sure, I've reinstalled the Termux environment and Bettercap. Problem persists. 

### Environment

* Bettercap version you are using ( `bettercap -version` ).
bettercap v2.28 (built for android arm64 with go1.14.4)
* OS version and architecture you are using.
Linux localhost 4.4.197-Minimal-4.4 #1 SMP PREEMPT Sat Dec 21 07:57:47 CET 2019 aarch64 Android
* Command line arguments you are using.
sudo bettercap -debug -iface wlan1
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
$ sudo bettercap -debug -iface wlan1
bettercap v2.28 (built for android arm64 with go1.14.4) [type 'help' for a list of commands]

 wlan1  » [07:09:10] [sys.log] [dbg] Could not find mac for 192.168.2.1
 wlan1  » [07:09:10] [session.started] {session.started 2021-01-19 07:09:10.346429559 +0000 UTC m=+0.279606407 <nil>}
 wlan1  » [07:09:10] [mod.started] events.stream
 wlan1  » wifi.recon on
[07:09:29] [sys.log] [inf] wifi using interface wlan1 (98:de:d0:09:3a:1c)
[07:09:29] [sys.log] [dbg] SetInterfaceTxPower(wlan1, 30) iw based
[07:09:29] [sys.log] [war] wifi could not set interface wlan1 txpower to 30, 'Set Tx Power' requests not supported
[07:09:29] [sys.log] [err] error while setting interface wlan1 in monitor mode: Cannot set rfmon for this handle

### Steps to Reproduce

1. Run bettercap on specific interface that supports monitor mode
2. Wifi.recon on raises an error saying that it won't support monitor mode

Really at a loss here. Tried to find out on my own what could be wrong. But everything else seem to work just fine with this card. (wfite, airodump etc) Any help is greatly appreciated.

**Comment by wvthoog** [comment]
Some additional information setting the wlan1 interface into monitor mode successfully using iw

$ iw wlan1 info
Interface wlan1
	ifindex 41
	wdev 0xd00000001
	addr 98:de:d0:09:3a:1c
	type managed
	wiphy 13
	txpower 0.00 dBm
$ sudo iw wlan1 set monitor none
$ sudo ifconfig wlan1 up
$ iw wlan1 info
Interface wlan1
	ifindex 41
	wdev 0xd00000001
	addr 98:de:d0:09:3a:1c
	type monitor
	wiphy 13
	channel 1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
	txpower 20.00 dBm

**Comment by icarostangent** [comment]
Exact same problem on a fresh install of Parrot OS

**Comment by wvthoog** [comment]
It seems to be a problem with libpcap-1.10.0. So I've downgraded to libpcap-1.9.1-1 and now it works again.

**Comment by warp123** [comment]
how did you downgraded the library, because in Kali repo there is only one available for libpcap0.8 that it's installed

**Comment by wvthoog** [comment]
wget https://termux.mentality.rip/termux-packages-24/aarch64/libpcap_1.9.1-1_aarch64.deb
dpkg -i libpcap_1.9.1-1_aarch64.deb

**Comment by warp123** [comment]
thank you. I will check.

**Comment by toxdk** [comment]
I have just tested it.
libpcap 1.9.1-4 is working
libpcap 1.10.0-2 is not working
You can find the old libpcap 1.9.1-4 here:
http://old.kali.org/kali/pool/main/libp/libpcap/

So for Kali x64
wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb
dpkg -i libpcap0.8_1.9.1-4_amd64.deb

**Comment by warp123** [comment]
Yes it works. Great.

**Comment by warp123** [comment]
By the way @wvthoog how did you trace the library causing the problem? Good job in any case!!

**Comment by wvthoog** [comment]
@warp123 came across [this](https://pkg.go.dev/github.com/jax777/gopacket@v1.1.10/pcap) page while googling for "Cannot set rfmon for this handle"

**Comment by ChinmaySiwach** [comment]
hi i wanted to know should i change my external wifi card mode to monitor when using bettercap or managed mode is also fine?

**Comment by Mgwilow2** [comment]
> Il semble que le problème soit lié à libpcap-1.10.0. J'ai donc rétrogradé vers libpcap-1.9.1-1 et maintenant cela fonctionne à nouveau.
hello how did you downgrade libpcap???
