### ISSUE TITLE
My dns.spoof not work

### ISSUE THREAD

**Issue by BlueTearsY** [bettercap/bettercap#818]
I use soft router，os is OpenWrt and install BetterCap

Version： bettercap v2.28 (built for linux amd64 with go1.15.6)

I want to use dns spoof，my step is：

1.   bettercap -iface eth3  (eh3 is LAN，it connect a wifi router，my computer connect wifi router)
2.   set dns.spoof.domain *
3.   set dns.spoof.address 1.2.3.4
4.   set dns.spoof.all true
5.   dns.spoof on

 eth3  » [07:54:51] [sys.log] [inf] dns.spoof * -> 1.2.3.4
 eth3  » [07:54:51] [sys.log] [inf] dns.spoof starting net.recon as a requirement for dns.spoof
 eth3  » [07:55:39] [sys.log] [err] error sending packet: Packet queue is not active.
 eth3  » [07:56:42] [sys.log] [err] error sending packet: Packet queue is not active.
 eth3  » [07:57:22] [sys.log] [err] error sending packet: Packet queue is not active.
 eth3  » [07:57:47] [sys.log] [err] error sending packet: Packet queue is not active.

dns.spoof can't not work, always prompt "eth3  » [07:57:47] [sys.log] [err] error sending packet: Packet queue is not active."

Please, What's the problem?  Thanks

**Comment by evilsocket** [comment]
https://github.com/bettercap/bettercap/releases/tag/v2.29

**Comment by evilsocket** [comment]
( it's dns.spoof.domains )
