### ISSUE TITLE
Bettercap: Cannot set rfmon for this handle AWUS1900

### ISSUE THREAD

**Issue by lluchyluck** [bettercap/bettercap#819]
Command attempted:
bettercap --iface (in my case wlan0)
When inside bettercap: wifi.recon on

What happened:
[err] error while setting interface wlan0 in monitor mode: Cannot set rfmon for this handle

More info:
Im using an awus1900 with 88xxau driver, 5.9.0-kali5-amd64.
I dont know whats happening, the driver is ok, monitor mode when enabled with airmon-ng works, but when bettercap tries to enable it shows that msg, i suppose that the issue is with the bettercap software.
Any ideas??

**Comment by crematori1707** [comment]
Faced the same problem. Everything worked fine a few days ago. In other programs, monitor mode works: wifite, airgeddon, aircrack.
Reinstalled kali linux, it worked. After apt-get update & updrade, the problem is back. I think the problem is in bettercap. Sorry for my broken english.

**Comment by gombossb** [comment]
It's the same for me on Kali + Raspberry Pi, it worked for me until I updated other packages on the system about a week ago...

**Comment by warp123** [comment]
yes i can confirm that the same happens to me. Kali installed on boot hdd. The wifi adapter can be set to monitor mode with airmon-ng just fine. Wireshark also works with the card in monitor mode. I have tested even with one more wifi adapter and the internal wifi of the laptop, and it fails in any case

**Comment by toxdk** [comment]
I have just tested it.
libpcap 1.9.1-4 is working
libpcap 1.10.0-2 is not working
You can find the old libpcap 1.9.1-4 here:
http://old.kali.org/kali/pool/main/libp/libpcap/

So for Kali x64
wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb
dpkg -i libpcap0.8_1.9.1-4_amd64.deb

**Comment by warp123** [comment]
You are quick. Thanks

**Comment by lluchyluck** [comment]
I will try it, thanks.

**Comment by lluchyluck** [comment]
Works you are a genious man.

**Comment by taesai** [comment]
1000 Thanks!

**Comment by qkum** [comment]
> I have just tested it.
> libpcap 1.9.1-4 is working
> libpcap 1.10.0-2 is not working
> You can find the old libpcap 1.9.1-4 here:
> http://old.kali.org/kali/pool/main/libp/libpcap/
> 
> So for Kali x64
> wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb
> dpkg -i libpcap0.8_1.9.1-4_amd64.deb

But what problems will arise with other programs when we downgrade? 

My suspicion is other programs will stop working as a result.

**Comment by SonOfBR549** [comment]
I have confirmed this. I have written a short script to downgrade to 0.8 and then restore to 1.10. Works consistently. So, I can live with this. I'm not a Linux, Bettercap or libcap expert, does anyone know whether this is a libcap or Bettercap problem? and if it is a Bettercap problem, is it being fixed? ETA?

**Comment by Monkeyonthecar** [comment]
total noob here, but how do i upgrade it again. I can not use some applications and `sudo apt-get install libpcap-dev` or similar commands (`sudo apt --fix-broken install`) do not work

**Comment by V0r-T3x** [comment]
This solution is working for a raspberry pi zero too. I got the same problem with the Broadcom bcm2835 chipset.

**Comment by VHAE04** [comment]
> I have just tested it. libpcap 1.9.1-4 is working libpcap 1.10.0-2 is not working You can find the old libpcap 1.9.1-4 here: http://old.kali.org/kali/pool/main/libp/libpcap/
> 
> So for Kali x64 wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb dpkg -i libpcap0.8_1.9.1-4_amd64.deb

thk it work for me 
i use parrot os

**Comment by Muhammed388** [comment]
> I have just tested it. libpcap 1.9.1-4 is working libpcap 1.10.0-2 is not working You can find the old libpcap 1.9.1-4 here: http://old.kali.org/kali/pool/main/libp/libpcap/
> 
> So for Kali x64 wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb dpkg -i libpcap0.8_1.9.1-4_amd64.deb

how do i do this to kali

**Comment by VHAE04** [comment]
> > I have just tested it. libpcap 1.9.1-4 is working libpcap 1.10.0-2 is not working You can find the old libpcap 1.9.1-4 here: http://old.kali.org/kali/pool/main/libp/libpcap/
> > So for Kali x64 wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb dpkg -i libpcap0.8_1.9.1-4_amd64.deb
> 
> how do i do this to kali

in kali or parrot u need download version arm in here 
http://old.kali.org/kali/pool/main/libp/libpcap/

[libpcap-dev_1.8.1-5_arm64.deb](http://old.kali.org/kali/pool/main/libp/libpcap/libpcap-dev_1.8.1-5_arm64.deb)

**Comment by tigerschweinekater** [comment]
Can someone please explain why this is closed as resolved?
It does not work with newer libpcap versions (including 10.1), which I can reproduce. But is this the kind of issue that should instead be reported in libpcap (i.e., a real regression bug) or is this just an API change in libpcap that requires bettercap to be adjusted?

**Comment by Zetlin** [comment]
This is still an issue

**Comment by Zetlin** [comment]
> Can someone please explain why this is closed as resolved? It does not work with newer libpcap versions (including 10.1), which I can reproduce. But is this the kind of issue that should instead be reported in libpcap (i.e., a real regression bug) or is this just an API change in libpcap that requires bettercap to be adjusted?

This is still an issue unfortunately

**Comment by Maynardnaze** [comment]
What a shame. Bettercaps beautiful too. Broken on all RPIs and the big 3 adapters.

**Comment by 909sbjr** [comment]
> > I have just tested it. libpcap 1.9.1-4 is working libpcap 1.10.0-2 is not working You can find the old libpcap 1.9.1-4 here: http://old.kali.org/kali/pool/main/libp/libpcap/
> > 
> > So for Kali x64 wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb dpkg -i libpcap0.8_1.9.1-4_amd64.deb
> 
> thk it work for me 
> i use parrot os

WHAT EXACT COMMANDS DID U TYPE TO GET IT TO WORK? I ALSO USE PARROT AND AM NEW?

**Comment by WonderMr** [comment]
RTL 8188 with custom driver https://github.com/aircrack-ng/rtl8188eus
and this commands 
`ip link set wlan0 down
sudo iw dev wlan0 set type monitor
ip link set wlan0 up`

works fine for me without downgrading of libpcap

**Comment by BirdsAreFlyingCameras** [comment]
@WonderMr Thank you!

**Comment by sAnJaY1000101** [comment]
I have the same problem in my windows 11 machine, any fixes for win11?
