### ISSUE TITLE
bettercap http-ui not accessible via IPv6

### ISSUE THREAD

**Issue by cvmiller** [bettercap/bettercap#820]
*Description of the bug or feature request*
http.server unable to listen to IPv6 any address '::'  
192.168.215.0/24 > 192.168.215.140  » set http.server.address ::
192.168.215.0/24 > 192.168.215.140  » 
192.168.215.0/24 > 192.168.215.140  » http.server off
192.168.215.0/24 > 192.168.215.140  » http.server on
[23:17:59] [sys.log] [err] Parameter http.server.address not valid: '::' does not match rule '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'.

### Environment

Please provide:
bettercap v2.29 (built for linux arm64 with go1.15.7)
Ubuntu 20.04LTS 
Linux ubuntu 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

* Bettercap version you are using ( `bettercap -version` ).
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
bettercap v2.29 (built for linux arm64 with go1.15.7) [type 'help' for a list of commands]

192.168.215.0/24 > 192.168.215.140  » [23:21:29] [sys.log] [dbg] FindGateway(eth0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
192.168.215.0/24 > 192.168.215.140  » [23:21:29] [sys.log] [dbg] FindGateway(eth0) output:
default via 192.168.215.1 dev eth0 proto dhcp src 192.168.215.140 metric 100 
192.168.215.0/24 dev eth0 proto kernel scope link src 192.168.215.140 
192.168.215.1 dev eth0 proto dhcp scope link src 192.168.215.140 metric 100
192.168.215.0/24 > 192.168.215.140  » [23:21:29] [sys.log] [dbg] FindGateway(eth0) line 'default via 192.168.215.1 dev eth0 proto dhcp src 192.168.215.140 metric 100' matched with [default via 192.168.215.1 dev eth0 proto dhcp src 192.168.215.140 metric 100 default 192.168.215.1 eth0]
192.168.215.0/24 > 192.168.215.140  » [23:21:29] [sys.log] [dbg] gateway is 192.168.215.1[28:c6:8e:16:19:d7]
192.168.215.0/24 > 192.168.215.140  » [23:21:29] [session.started] {session.started 2021-01-24 23:21:29.159591237 +0000 UTC m=+0.192916327 <nil>}
192.168.215.0/24 > 192.168.215.140  » [23:21:29] [mod.started] events.stream
192.168.215.0/24 > 192.168.215.140  » http.server off
[23:21:34] [sys.log] [err] module http.server is not running
192.168.215.0/24 > 192.168.215.140  » set http.server.address ::
192.168.215.0/24 > 192.168.215.140  » http.server on
192.168.215.0/24 > 192.168.215.140  » [23:21:42] [sys.log] [err] Parameter http.server.address not valid: '::' does not match rule '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'.

### Steps to Reproduce

1. start bettercap  `sudo ./bettercap`
2. set http.server.address to '::'
3. start http.server
4. Observe parse error, which appears to only accept IPv4 addresses

**Expected behavior:** *What you expected to happen*
I expected bettercap webserver to listen on IPv6 any address "::"

**Actual behavior:** *What actually happened*
Input parser does not accept IPv6 any address (or any other IPv6 address), and therefore is unaccessible via IPv6.

--

**Comment by evilsocket** [comment]
As you can also see from the logs, IPv6 is not currently supported.

**Comment by cvmiller** [comment]
Given that it is 2021, is it possible to make this a Feature Request?

**Comment by evilsocket** [comment]
sure, but it's a major change that at least personally i don't have the time to implement ... maybe some of the other contributors ... also it wouldn't work for every model as some of the attacks are IPv4 specific ... there's also a DHCPv6 specific attack (that works via IPv4 tho).
