### ISSUE TITLE
"https.proxy.redirect"can't work

### ISSUE THREAD

**Issue by alex01dleek** [bettercap/bettercap#821]
FIRST:     when I run https.proxy on . it's not work ,and display "[err] Redirection '[wlan0] (TCP) :443 -> 172.20.10.8:8890' already enabled."
THEN:     I turn false https.proxy.redirect  , https.proxy can be on,when I turn off https.proxy, there is a war sign "https.proxy error accepting connection: accept tcp 172.20.10.8:8890: use of closed network connection."
So, I think the problem is in redirection.how to fix it

**Comment by evilsocket** [comment]
incomplete issue, you just removed the template and didn't fill the required information.
