### ISSUE TITLE
Doesn't redirect HTTP/S

### ISSUE THREAD

**Issue by IliyanUI** [bettercap/bettercap#822]
Hello,

I am trying to simulate a MITM attack using Bettercap and SEToolkit.
What I do is Redirect the target using Bettercap, then launch SEToolkit from new terminal and select the already built in Twitter fake page.
I don't get any error along the way and everything seems fine. Then I get the: "Information will be displayed to you as it arrives below" and when I open the browser from my target machine, It doesnt redirect me to Twitter page. It just doesnt and I don't know what is the issue because I don't get error either. I tried to clone website of my choice, tried the Google built in page but still nothing. I tried to redirect both HTTP and HTTPS but still no result.

I am using Kali LIVE USB.

Any help will be appreciated,

Thanks

**Comment by evilsocket** [comment]
no logs, completely ignored the issue template ... closing as incomplete.
