### ISSUE TITLE
Nexmon / RPI4 Issues with mon0 monitoring

### ISSUE THREAD

**Issue by mlinton** [bettercap/bettercap#824]
Feature Request - because I'm not smart enough to get it working.

So I did try to get this working by editing the net_linux.go file and adding logic in my branch (https://github.com/mlinton/bettercap/blob/master/network/net_linux.go) but I can't get it to change the channel successfully without returning an error code (exit status 64).

I don't know why this is doing this, probably something really stupid here is the line of code:

out, err := core.Exec("nexutil", []string{"-k", fmt.Sprintf("%d", channel)})

and the command that I want it to call is "nexutil -k1" for channel 1 and "nexutil -k11" for channel 11

What am I doing wrong here?

Thanks!

**Comment by evilsocket** [comment]
i'm not sure i understand what's the problem here, bettercap supports nexmon by default (pwnagotchi for instance), can you paste some errors you're getting? you shouldn't be trying to make it work, it should just work :D
