### ISSUE TITLE
SSLStripe Not working on new version 2.29 :(

### ISSUE THREAD

**Issue by razorJhon** [bettercap/bettercap#825]
Using Bettercap version 2.29 Latest
OS Kali Linux 2020

Steps to Reproduce

1. net.sniff on
2. net.recon on
3. net.probe on
4. https.proxy.sslstripe on
5. https.proxy on
6. set arp.spoof.targets 192.168.1.X
7. arp.spoof on

What you expected to happen?

getting login information from my lan network.

What actually happened?
getting only requests from HTTP and some website of HTTPS but not the login
also while spoofing i am getting on my computer that the connection is not private ,

Attackers might be trying to steal your information from www.google.com (for example, passwords, messages or credit cards). Learn more
NET ::ERR_CERT_AUTHORITY_INVALID

am i doing something wrong or the SSLStripe is not working anymore ?

**Comment by buffermet** [comment]
There is no sslstripe, it's sslstrip.

**Comment by razorJhon** [comment]
> There is no sslstripe, it's sslstrip.

sorry i typed that wrong in the thread , sorry for that .
