### ISSUE TITLE
Bettercap scan entire network when I set only one

### ISSUE THREAD

**Issue by PoleG97** [bettercap/bettercap#826]
i'm using the lastest release of bettercap. It's running on kali linux 2020.4

I don't know why, but when I try to set only one terget, bettercap scan all network.. What happend?

![Captura de pantalla 2021-01-30 213918](https://user-images.githubusercontent.com/44400218/106367533-a3620200-6343-11eb-91f0-224866799f93.png)

**Comment by buffermet** [comment]
Incomplete report. You deleted the issue template.

**Comment by buffermet** [comment]
Also you clearly haven't read the documentation.

https://www.bettercap.org
