### ISSUE TITLE
Device is shown multiple times with wrong mac address when arp.spoof is on

### ISSUE THREAD

**Issue by tonjo** [bettercap/bettercap#83]
### Description

During arp spoofing, some endpoints are shown twice, with wrong mac address.

### Environment

* OS version: Ubuntu 16.04, kernel 4.13.0-36-generic
* bettercap version: precompiled 2.0.0 RC2

### Steps to Reproduce
Launch the commands:

1. net.show
2. arp.spoof on
3. net.show

**Expected behavior:** 
Device should not be shown twice with their mac address changed

**Actual behavior:** 
Device is shown twice, one with correct mac address, one with a wrong one, to be specific, with the pc running bettercap mac address.

    [15:43:41] [endpoint.new] Endpoint 192.168.1.8 (smartphone1) detected as MAC_ADDRESS_PHONE (Huawei Technologies Co.).
    [15:43:50] [endpoint.new] Endpoint 192.168.1.8 (HUAWEI_nova.station.) detected as MAC_ADDRESS_MY_PC (Hewlett Packard).

    +-------------+-------------------+----------------------------+-------------------------+--------+--------+-----------+
    |     IP      |        MAC        |            NAME            |         VENDOR          |  SENT  | RECVD  | LAST SEEN |
    +-------------+-------------------+----------------------------+-------------------------+--------+--------+-----------+
    | 192.168.1.8 | MAC_ADDRESS_PHONE | smartphone1                | Huawei Technologies Co. | 342 B  | 325 B  | 15:43:50  |
    | 192.168.1.8 | MAC_ADDRESS_MY_PC | HUAWEI_nova.station.       | Hewlett Packard         | 342 B  | 325 B  | 15:43:50  |
    +-------------+-------------------+----------------------------+-------------------------+--------+--------+-----------+

`# arp -an` of pc running bettercap is ok, it shows right mac addresses

		$ arp -an
		? (192.168.1.8) at MAC_ADDRESS_PHONE [ether] on enp0s25
		? (192.168.1.1) at MAC_ADDRESS_GATEW [ether] on enp0s25

**Comment by evilsocket** [comment]
If you keep using the same precompiled version how do you expect the fixes I'm pushing to the code to work?

I already fixed this several commits ago.

**Comment by evilsocket** [comment]
ref https://github.com/bettercap/bettercap/issues/82

**Comment by tonjo** [comment]
Editing mistake, it was *not* the precompiled version, but the latest one i pulled today.
I started to write the issue before trying the last version, and forgot to change the version.
Anyway, I discovered something else, opening a new one with other details.

**Comment by tonjo** [comment]
PS: sorry, Sunday, not very brilliant today

**Comment by evilsocket** [comment]
"i pulled today" when? pull it **now**, compile it, confirm the bug is open or not.
