### ISSUE TITLE
Termux Bettercap Install

### ISSUE THREAD

**Issue by aaron358** [bettercap/bettercap#837]
# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

[E] Oooops, seems like something weird occurred, please copy paste the following output and open a new issue on https://github.com/evilsocket/bettercap/issues :

[E] Platform          : aarch64-linux-gnu
[E] Ruby Version      : 2.7.0
[E] BetterCap Version : 1.6.2
[E] Command Line      :
[E] Exception         : Errno::EACCES
[E] Message           : Permission denied @ rb_sysopen - /proc/sys/net/ipv4/ip_forward
[E] Backtrace         :

    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/linux.rb:45:in `initialize'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/linux.rb:45:in `open'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/linux.rb:45:in `forwarding_enabled?'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/base.rb:47:in `initialize'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/base.rb:28:in `new'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/firewalls/base.rb:28:in `get'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/context.rb:67:in `initialize'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/context.rb:51:in `new'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/context.rb:51:in `get'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/lib/bettercap/options/options.rb:42:in `parse!'
    /var/lib/gems/2.7.0/gems/bettercap-1.6.2/bin/bettercap:30:in `<top (required)>'
    /usr/local/bin/bettercap:23:in `load'
    /usr/local/bin/bettercap:23:in `<main>'

**Comment by buffermet** [comment]
You are using the legacy version of bettercap which is no longer supported.

**Comment by aaron358** [comment]
Hello Bettercap Team my name is Aaron and I'm I'm learning termux, the
legacy version of Bettercap isent supported buy termux?? N is there any
other versions of Bettercap to try on termux?

**Comment by buffermet** [comment]
@aaron358 you clearly haven't read the manual or even the text that you copied and pasted in your own issue...

RTFM

https://www.bettercap.org

**Comment by aaron358** [comment]
Sorry I understand it's cause I learned termux on YouTube slot of stuff
gets left out, any advice on what to Wen all the red code comes up I'm
unsure on how to read the code

**Comment by buffermet** [comment]
I'm telling you one more time that you are using the wrong version of bettercap. Read the manual...
