### ISSUE TITLE
Bettercap in Termux

### ISSUE THREAD

**Issue by aaron358** [bettercap/bettercap#838]
# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/bettercap/bettercap/blob/master/README.md), that you are running the [latest stable version](https://github.com/bettercap/bettercap/releases) and that you already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. *First Step*
2. *Second Step*
3. *and so on...*

**Expected behavior:** *What you expected to happen*

**Actual behavior:** *What actually happened*

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

Hello Bettercap Team my name is Aaron, and I have Installed Bettercap on my termux Machine for androide, I red the manual and I came across the termux installation commands however, I am using Bettercap legacy version which doesn't work on termux, I am unsure on how to install Bettercap v2.29 is there any way I could receive some help and advice on how to install Bettercap v.2.29, I apt upgrade after Sudo Su it's still the legacy version tho?? There are no tutorial on how to do this, Any Helpfully Advice, to a new pentester

#837

**Comment by buffermet** [comment]
Mate if you can't find the latest version you have a lot more reading to do.

Stop abusing the issue tracker.

**Comment by buffermet** [comment]
The entire installation instructions are on the site I linked you in your previous issue. You haven't bothered helping yourself and neither will we.
