### ISSUE TITLE
Missing releases for Windows and MacOS

### ISSUE THREAD

**Issue by SubZero5** [bettercap/bettercap#846]
Hi!

Not sure what to post this as exactly.

*Description of the bug or feature request*

V2.28 release had bettercap_darwin_amd64_v2.28.zip and bettercap_windows_amd64_v2.28.zip

V2.29 release had bettercap_windows_amd64_v2.29.zip but did not have bettercap_darwin_amd64_v2.29.zip

V2.30 release does not have bettercap_darwin_amd64_v2.30.zip and/or bettercap_windows_amd64_v2.30.zip

Why are they not updated or released?

**Comment by buffermet** [comment]
I assume there was a shortage of time, but you don't have to wait, you can compile them yourself.

**Comment by evilsocket** [comment]
Hi! As you can see https://travis-ci.org/github/bettercap/bettercap/jobs/762608473 some builds are failing and I have no idea how to debug and fix that as the current travis build mechanism has been implemented by @caquino

**Comment by evilsocket** [comment]
fixed with https://github.com/bettercap/bettercap/commit/1fea9f02fb43d364b402494016f3bf65deaaec22

**Comment by SubZero5** [comment]
Thanks for the bettercap_windows_amd64_v2.30.2.zip but, still no bettercap_darwin_amd64_v2.30.2.zip available... 😭

**Comment by evilsocket** [comment]
@caquino for some reason the macOS build didn't upload the binary? https://travis-ci.org/github/bettercap/bettercap/jobs/762866557

**Comment by SubZero5** [comment]
@caquino might see this as Closed/Resolved...
