### ISSUE TITLE
Readline autocomplete support improvements.

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#85]
### Description

```
10.114.64.0/21 > 10.114.71.250  » net.show 
by    seen  by    sent  by    rcvd  

```
if I press `tab` as for showing suggestions I see all of these words with selection option of both `by` AND `seen`. What I expect is:
```
10.114.64.0/21 > 10.114.71.250  » net.show 
by
```
and then
```
10.114.64.0/21 > 10.114.71.250  » net.show by
seen   sent   rcvd
```
Or

```
10.114.64.0/21 > 10.114.71.250  » net.show 
[by seen]     [by  sent]     [by rcvd]  
```
(Brackets as for selection option)

**Comment by evilsocket** [comment]
Code [is here](https://github.com/bettercap/bettercap/blob/master/session/session.go#L166), you are more than welcome to fork the repo, implement the stuff you want and send a pull request :)

**Comment by alexmozzhakov** [comment]
@evilsocket Thanks, I'll try my best.
