### ISSUE TITLE
Is there a way not to hardcode caplets to /usr/local?

### ISSUE THREAD

**Issue by herbygillot** [bettercap/bettercap#850]
---
`bettercap` hardcodes its caplet installation location  to **/usr/local/share/bettercap**.

It also appears that (some) caplets seem to be compiled with the same assumption.

How can this be made configurable?

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). 2.30.2
* OS version and architecture you are using. macOS, amd64
* Go version if building from sources. go 1.16.2

**Comment by evilsocket** [comment]
there is now :D
