### ISSUE TITLE
Are there any plans to support IPv6 NDP spoofing?

### ISSUE THREAD

**Issue by who0sy** [bettercap/bettercap#851]
Is it planned to support ipv6 NDP spoofing ?

**Comment by evilsocket** [comment]
i'd love to, any suggestion on how to create an IPv6 test environment for NDP spoofing inside an IPv4 network? i don't think i have an IPv6 capable router

**Comment by evilsocket** [comment]
starting to https://github.com/bettercap/bettercap/commit/bef4c6abaa656b95c3a314c9ea26921ee0e87eb1

**Comment by evilsocket** [comment]
also https://github.com/bettercap/bettercap/commit/a6d5d5d048707409cd633c13b0e43117caa19939

**Comment by funkymonkey5150** [comment]
Sounds good I’ll send what I have

**Comment by evilsocket** [comment]
both spoofing techniques (NDP and RA) confirmed working vs linux targets with ipv6 addresses
