### ISSUE TITLE
wifi no client

### ISSUE THREAD

**Issue by Amoto1103** [bettercap/bettercap#852]
### Environment

bettercap v2.30.2 (built for linux amd64 with go1.15.8)
os: kali with linux kernal 5.10
WLAN card: EDIMAX EW-7811Un V1

my problem:
When i run 'wifi.recon on' and 'wifi.show', all the aps can be shown. However, no clients to those aps are listed.
![image](https://user-images.githubusercontent.com/31895191/111859221-313c8f80-897a-11eb-8dc9-a1bd41869a0a.png)
Also, there's no 'wifi.client.new' label shown in: 
![image](https://user-images.githubusercontent.com/31895191/111859244-677a0f00-897a-11eb-8dd6-75ed5fa228cb.png)
So what's the problem here? Is this the problem with bettercap or my hardware?

**Comment by evilsocket** [comment]
interesting ... what happens if you stick on a single channel with "wifi.recon.channel 6" (use your router's channel maybe so you know that there are indeed clients) ?

**Comment by Amoto1103** [comment]
Sometimes clients appear while sometimes not. At one moment, it shows 1 client connected to my own ap and that's right. But when I disconnect my client, it still shows 1 client connected. I think the information is not updated. 
Another problem is that, when I use the http-ui, start the wifi function and click "deauth" certain client, it doesn't work. That confuses me.

**Comment by evilsocket** [comment]
That is when you stay on one channel like i said?

**Comment by evilsocket** [comment]
also did you check that networkmanager is not messing with the interface? https://security.stackexchange.com/questions/101275/airmon-ng-confliciting-with-network-manager-in-kali

**Comment by Amoto1103** [comment]
Yes, I have stayed on one channel and stop the networkmanager. Now the result is better, but still sometimes death successfully and sometimes not. Also, delay still exists. A 'deauth' command leads to a real disconnect effect 2 minutes later and a disconnected client is shown 'connected'. I will try more times. Anyway, thank you for your help.

**Comment by evilsocket** [comment]
what if you:

```
wifi.recon off
set wifi.hop.period 1000
wifi.recon on
```

?
