### ISSUE TITLE
WebUI not letting me use my wifi card.

### ISSUE THREAD

**Issue by de4dmemories** [bettercap/bettercap#853]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). : Newest
* OS version and architecture you are using. : kali, latest stable, latest kernel
* Caplet code you are using or the interactive session commands. : http-ui
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ). : 
* 
error while setting interface wlan1 in monitor mode: Cannot set rfmon for this handle

yet, I can use this same wifi card in my terminal. everything works. I had to downgrade libcap from 10 to 9, but i got the CLI working. Just not the web ui. What could be the issue?

### Steps to Reproduce

1. *First Step*  =  bettercap -caplet http-ui
2. *Second Step*  =  wifi.recon on (in the web ui) with the card im using already in monitor mode. Tried it with it in managed mode, same error.

**Actual behavior:** *What actually happened*

error while setting interface wlan1 in monitor mode: Cannot set rfmon for this handle

Sorry if i'm missing something, fairly new to cyber security just got into a program. Any help would be appreciated.

**Comment by evilsocket** [comment]
i don't see logs
