### ISSUE TITLE
Hstshijack caplet not working

### ISSUE THREAD

**Issue by zwjulian** [bettercap/bettercap#855]
Hello,
I have installed bettercap on my kali linux machine. However, when I want to run the hstshijack caplet (with the command: sudo bettercap -caplet /usr/share/bettercap/caplets/hstshijack/hstshijack.cap) I get the following error:

[sys.log] [err] error while running caplet /usr/share/bettercap/caplets/hstshijack/hstshijack.cap: exit status 4

What can I do to fix this?
Kind regards,
Julian

**Comment by buffermet** [comment]
You need to write a complete issue and provide debug output using the `-debug` flag.
