### ISSUE TITLE
Problems with arp.ban on

### ISSUE THREAD

**Issue by zohanplus777** [bettercap/bettercap#858]
Found a topic about how ssl certificates are replaced using DNS spoofing using bettercap.
I set up the main part, everything worked out, made a redirect from all domains.
The arp.ban mod is needed so that this window appears when redirecting from HTTPS:
![img6_codeb](https://user-images.githubusercontent.com/77664306/112261434-e9b94a80-8c7c-11eb-9068-7aff39e3b572.png)

It does not work for me, the following is displayed in the **bettercap** console by the command arp.ban on:
![Screenshot_1](https://user-images.githubusercontent.com/77664306/112261483-05245580-8c7d-11eb-84d5-3b994d58881f.png)

Forwarding was prescribed by the command: **echo 1> / proc / sys / net / ipv4 / ip_forward**

But all the same, when you try to enter the site in HTTPS, it displays a connection error.

I am using Kali Linux latest version

**Comment by buffermet** [comment]
Your error message is in Russian, but I'm guessing it's a certificate warning.

`arp.ban` is not used to spoof TLS connections, it is used to block a client's internet connection. You should be using `arp.spoof` to poison your victim's arp table.

It sounds to me like you have unreasonable expectations attacking TLS. Please read #428 carefully.

**Comment by zohanplus777** [comment]
I wanted to make it so that on my test pc there would be a message saying that I need to Log in to the network "Open the login page"
See the first screenshot.

And after clicking on "Enter the network" I will be transferred to the substitution of DNS, that is, to my local server.

**Comment by buffermet** [comment]
What you are talking about are completely different things.

The "open login page" popup is for captive portals, not for TLS warnings.

With the current implementation of the DNS spoofer, it's not possible to use bettercap for (decent) captive portals, unless a third party DNS proxy server is used. (Stay tuned for updates)

You also sound confused about DNS rebinding and TLS. I suggest you read up on both.

**Comment by buffermet** [comment]
The captive portal module can be found here: https://github.com/bettercap/bettercap/issues/631#issuecomment-2726983539
