### ISSUE TITLE
Problems with arp.ban 

### ISSUE THREAD

**Issue by zohanplus777** [bettercap/bettercap#859]
I wanted to make it so that on my test pc there would be a message saying that I need to Log in to the network "Open the login page"
See the first screenshot.

And after clicking on "Enter the network" I will be transferred to the substitution of DNS, that is, to my local server.

I will use the following commands:
dns.spoof on
dhcp6.spoof on
arp.ban on

I repeat, in the first screenshot, not a warning about a certificate, but a login page, after which it will redirect the substitution to dns.

Found a topic about how ssl certificates are replaced using DNS spoofing using bettercap.
I set up the main part, everything worked out, made a redirect from all domains.
The arp.ban mod is needed so that this window appears when redirecting from HTTPS:

![img6_codeb](https://user-images.githubusercontent.com/77664306/112287442-6f4cf280-8c9d-11eb-9a3a-0f885cbea809.png)

It does not work for me, the following is displayed in the bettercap console by the command arp.ban on:

![Screenshot_1](https://user-images.githubusercontent.com/77664306/112287489-7bd14b00-8c9d-11eb-849b-81e96766d181.png)

But all the same, when you try to enter the site in HTTPS, it displays a connection error.

I am using Kali Linux latest version

**Comment by evilsocket** [comment]
that is not what the arp.ban module is for, you probably want arp.spoof, please read the docs https://bettercap.org/

**Comment by zohanplus777** [comment]
> это не то, для чего предназначен модуль arp.ban, вы, вероятно, хотите arp.spoof, пожалуйста, прочтите документацию https://bettercap.org/

I have read everything, but I do not understand why the person is not transferred to the authorization window? The autorasia in the first screenshot?

**Comment by buffermet** [comment]
Duplicate of https://github.com/bettercap/bettercap/issues/858

**Comment by buffermet** [comment]
@zohanplus777 you need to be more specific.

Did you change your approach? If not, then the reason for your problem is that you are using `arp.ban` which blocks connections for clients.
