### ISSUE TITLE
error installing lastest version from source

### ISSUE THREAD

**Issue by tehseensagar** [bettercap/bettercap#860]
OS: ParrotOS
GO_Version: 1.15.8

go get github.com/bettercap/bettercap

`# github.com/bettercap/bettercap/network
go/src/github.com/bettercap/bettercap/network/net_linux.go:72:3: not enough arguments to return
	have (error)
	want ([]int, error)
go/src/github.com/bettercap/bettercap/network/net_linux.go:76:5: undefined: output
go/src/github.com/bettercap/bettercap/network/net_linux.go:77:49: undefined: output
go/src/github.com/bettercap/bettercap/network/net_linux.go:148:2: not enough arguments to return
	have (error)
	want ([]int, error)`

What is wrong any idea?

**Comment by evilsocket** [comment]
just fixed it, my mistake

**Comment by tehseensagar** [comment]
@evilsocket  Thanks error is gone :) .
