### ISSUE TITLE
Original HTTP response headers are proxied even when JSResponse.ToResponse returns a response with headers that are spoofed

### ISSUE THREAD

**Issue by 0x0ff537** [bettercap/bettercap#871]
### Environment
* Bettercap version: bettercap v2.31.0 (built for linux amd64 with go1.16.3)
* OS version and architecture you are using: Linux kali 5.10.0-kali3-amd64
* Go version: go1.16.3 linux/amd64
* Caplet code you are using or the interactive session commands: [spoof.cap](https://github.com/0x0ff537/bettercap-files/blob/main/spoof.cap) and a custom [hstshijack caplet](https://github.com/0x0ff537/bettercap-files/tree/main/hstshijack)

### Steps to Reproduce
1. Run an arp spoofing attack. 
2. Run custom hstshijack caplet. 

**Expected behavior:**
When credentials are entered in a successfully downgraded http site they are displayed in bettercap's screen, and (as I'm using fake credentials just for testing purposes) a failed login attempt page should be displayed in browser, this page should also use http protocol. This same behaviour applies for facebook.corn, twitter.corn, etc. 
Bettercap v2.23 work this way.

**Actual behavior:**
I compiled the latest bettercap version from source and tested the same attack that used to work with version 2.23, now even if  it successfully downgrades https sites no credentials are displayed in bettercap's screen and instead of the login failure attempt page there's a 'Connection failed' page and the URL has the https protocol. I'm using the same custom hstshijack caplet with both versions and testing with same websites as well.

**Comment by manish-frustated** [comment]
you find anything mate?

**Comment by buffermet** [comment]
You did not provide any logs.

**Comment by buffermet** [comment]
I missed the reference to your caplet code.

Please provide screenshots of the errors and logs.

If you are experiencing abnormal behaviour on spoofed pages, it is likely due to JavaScript implementations from the host and it's your job to evade those.

**Comment by buffermet** [comment]
Also, you should update the caplet. You are using an old one.

I'm not sure why you are using your own implementation (replace.js) which achieves the same as the default payload (hijack.js).

Please read the documentation.

**Comment by 0x0ff537** [comment]
Hi!
Yeah, I forgot to mention that I'm using a custom caplet because the original one was not working as expected, with mine it works better, just the issues I mentioned. Also this is not aproblem about javascript implementation from the host because the same custom caplet and same websites are successfully downgraded and show the expected info with bettercap 2.23.
But yeah, I'll take some screenshots and document the issue more in depth and share it here.

Thanks mate!

**Comment by buffermet** [comment]
@0x0ff537 

> 'Connection failed' page and the URL has the https protocol

A redirect to a HTTPS site from a spoofed page indicates that (in this case your) injection was not successful in evading the host's JavaScript protections.

> used to work with version 2.23, now even if it successfully downgrades https sites...

> the same custom caplet and same websites are successfully downgraded and show the expected info with bettercap 2.23

Then it sounds like the issue is not related to the caplet, but with newer versions of bettercap.

I wrote this caplet and if you refuse to update or read the documentation, I will not give you any support. There is no point in opening issues for outdated software from years ago...

**Comment by buffermet** [comment]
> Then it sounds like the issue is not related to the caplet, but with newer versions of bettercap.

I just compiled the latest source and used the latest version of the caplet and I having no issues downgrading sites.

**Comment by buffermet** [comment]
@0x0ff537 I just fixed a bug in the latest keylogger payload, but looking at your caplet setup from years ago, this won't affect you.

If you are still facing issues after updating to the latest version, I'll be happy to assist you.

<img width="788" alt="jfwiojefwhefw" src="https://user-images.githubusercontent.com/29265684/116576873-4f22ea00-a953-11eb-9582-7ba782aa906d.png">
<img width="788" alt="fwhfuewfuhoef" src="https://user-images.githubusercontent.com/29265684/116576854-49c59f80-a953-11eb-9171-7c4e8e53a3e4.png">
<img width="788" alt="fj23jf982j" src="https://user-images.githubusercontent.com/29265684/116576847-47fbdc00-a953-11eb-98a4-815f53965e3d.png">

**Comment by 0x0ff537** [comment]
Hi! Cool, thanks a lot!

I know I didn't mentioned it before but yeah, I read the documentation, I'm not refusing to read it or to update, just for the record.

Also this is a bit weird, I tested it with bettercap compiled from source and original hstshijack caplet which I got by running caplets.update.
My target machine is a windows 10 VM with the latest chrome version, which is the browser I'm using for testing, also I clear the entire browser's cahce before any testing attempt. So here is bettercap running:
![bettercap231_1](https://user-images.githubusercontent.com/82984484/116592547-bdc95e80-a8e5-11eb-8f18-d572933816ee.png)

![bettercap231_2](https://user-images.githubusercontent.com/82984484/116592579-c6219980-a8e5-11eb-8a6d-051bc285210c.png)

![bettercap231_3](https://user-images.githubusercontent.com/82984484/116592596-ca4db700-a8e5-11eb-831f-dd42f14e71a7.png)

And I'm using linkedin as test site, but it wasn't downgraded:
![bettercap231_originalcap_linkedin](https://user-images.githubusercontent.com/82984484/116592838-126cd980-a8e6-11eb-88f1-71742b8b32c5.png)

Then I changed to my custom hstshijack caplet. I do this by removing the original hstshijack caplet and setting the CAPSPATH variable to point to the old caplets folder path, there I have my custom hstshijack caplet folder:
![bettercap231_customcap](https://user-images.githubusercontent.com/82984484/116592970-36c8b600-a8e6-11eb-9035-21742db9e7d7.png)

![bettercap231_customcap2png](https://user-images.githubusercontent.com/82984484/116593006-40eab480-a8e6-11eb-8559-57d525d7c51f.png)

And now linkedin is succesfully downgraded:
![bettercap231_linkedin_customcap](https://user-images.githubusercontent.com/82984484/116593209-75f70700-a8e6-11eb-8e34-74d325191d3d.png)

But once I click on Log in button it redirects me to this page (which uses https) and there are no credentials in bettercap's screen:
![bettercap231_customcap_linkedinresult](https://user-images.githubusercontent.com/82984484/116593373-9f179780-a8e6-11eb-96b5-01eaddce5e3a.png)

Something similar happens with facebook:
![bettercap231_facebooklogin_customcap](https://user-images.githubusercontent.com/82984484/116593450-b9517580-a8e6-11eb-8858-83eb2a89c965.png)

![bettercap231_facebookresult](https://user-images.githubusercontent.com/82984484/116593469-bce4fc80-a8e6-11eb-9c06-5355639602ac.png)

Now, I tested the same with bettercap 2.23 and my custom hstshijack caplet:
![bettercap223_1](https://user-images.githubusercontent.com/82984484/116593557-d38b5380-a8e6-11eb-9af2-43942e6e0550.png)

![bettercap223_2](https://user-images.githubusercontent.com/82984484/116593583-da19cb00-a8e6-11eb-9079-627e41fe185e.png)

![bettercap223_3](https://user-images.githubusercontent.com/82984484/116593592-de45e880-a8e6-11eb-8ffd-164855d56c0c.png)


And the results are:
![bettercap223_linkedinloginpage_customcap](https://user-images.githubusercontent.com/82984484/116593659-f1f14f00-a8e6-11eb-9f1e-743b94cc5bab.png)

This time the failed login attempt page remain in http and credentials are displayed in bettercap's screen:
![bettercap223_linkedinresult](https://user-images.githubusercontent.com/82984484/116593681-f74e9980-a8e6-11eb-9809-226646c7141a.png)

![bettercap223_linkedinpass](https://user-images.githubusercontent.com/82984484/116593802-1b11df80-a8e7-11eb-9bfb-7032041bd64f.png)

And the same goes for facebook:
![bettercap223_facebookresult](https://user-images.githubusercontent.com/82984484/116593874-30870980-a8e7-11eb-9757-c9fd5dc5b6d9.png)

![bettercap223_facebooklogin_customcap](https://user-images.githubusercontent.com/82984484/116593843-282ece80-a8e7-11eb-8d90-a07ef9630b1e.png)

![bettercap223_facebookpass](https://user-images.githubusercontent.com/82984484/116593898-38df4480-a8e7-11eb-8319-ae065756c344.png)

I hope this resgister can help to give an idea of what's going on, if anything else is needed just let me know.
Also I can see you have downgraded the sites successfully, may I know which OS is it? And you are using firefox, aren't you?
Just to do more testing.

And appreciate the help!

Greetings!

**Comment by buffermet** [comment]
@0x0ff537 thanks for providing screenshots.

Your first screenshot of the caplet configuration clearly shows that you are only spoofing `google.com`, `*.google.com`, `gstatic.com` and `*.gstatic.com`. In the other (outdated) caplet, your hstshijack configuration does show that you are targeting `linkedin.com`.

You must target the sites that you wish to spoof accordingly. An easy way to test that the spoofing works is to simply target `*.com` and replace it with `*.corn`.

**Comment by 0x0ff537** [comment]
Hi!
Ok, I'll do the changes, run some tests and let you know the results.

Thanks mate!

**Comment by buffermet** [comment]
@0x0ff537 I am also noticing some anomalies.

It seems like facebook is upgrading XMLHttpRequests to use HTTPS, if that is the case, and easy bypass would be to use hidden iframes, images (etc.) to send callbacks.

<img width="551" alt="Screen Shot 2021-05-01 at 11 33 03 pm" src="https://user-images.githubusercontent.com/29265684/116784179-37c03a00-aad6-11eb-9a6e-5527adc0d7cf.png">

I am also noticing that the CSP header is not downgraded correctly, causing the injected payloads to be blocked on a lot of sites. The JSRequest shows that they are spoofed, but the browser is showing the original headers. I will look into it now.

<img width="533" alt="Screen Shot 2021-05-01 at 11 34 31 pm" src="https://user-images.githubusercontent.com/29265684/116784155-0fd0d680-aad6-11eb-9be1-8e90676e4db9.png">

**Comment by buffermet** [comment]
@0x0ff537 all good now.

Happy hacking.

<img width="1049" alt="Screen Shot 2021-05-02 at 12 58 11 am" src="https://user-images.githubusercontent.com/29265684/116786446-f9c91300-aae1-11eb-985b-4d4c15608aa6.png">

**Comment by 0x0ff537** [comment]
Hi!
Cool man! Thanks for looking into it. I'll compile it from source again and run some tests, may I know how does your hstshijack caplet looks like?

Thanks for the help!

**Comment by buffermet** [comment]
@0x0ff537 make sure you also add `*.corn` to the `dns.spoof.domains` variable.

**Comment by 0x0ff537** [comment]
Ok! I will.

Thanks mate!
