### ISSUE TITLE
gps.show (lat/long) missing in events.stream

### ISSUE THREAD

**Issue by geekskunk** [bettercap/bettercap#878]
events.stream.output does not contain gps.show output (only seen in interactive view)

example cap to reproduce:
```
set events.stream.output ./gps-show-cap.log
events.stream on
gps on
set ticker.commands gps.show
set ticker.period 5
ticker on
```

### Environment
* Bettercap version:  v2.3.1
* Go version: go1.13.8 
* linux/arm (Ubuntu 20)
* running produces no debug (may not be a bug,)

### Steps to Reproduce

1. Run bettercap with cap example above in 1 terminal (gps lat/long should begin to display)
2. In separate terminal tail gps-show-cap.log  (gps lat/long will not be seen)

**Expected behavior:**
gps show/lat/long to be sent over events.stream

**Actual behavior:** *What actually happened*
gps lat/long not seen over events.stream

**Comment by evilsocket** [comment]
now there's a new `gps.new` event that's triggered (and goes into the event stream) as soon as new GPS data is available ... no need to call `gps.show` 👍🏻
