### ISSUE TITLE
arp.spoof using own IP address?

### ISSUE THREAD

**Issue by krypto-kraken** [bettercap/bettercap#879]
Hello all,

First off, thanks for the awesome tool. I am trying to arp spoof with: _arp.spoof on_ and for some reason the IP address of my own machine is being used instead of the IP of the gateway. For example, instead of 192.168.8.1 (the IP of my router) being spoofed, 192.168.8.152 (the IP address of my Mac) is being used. So when I open Wireshark, I see ARP messages like:

**"192.168.8.152 is at <MacBook Mac Address>"** instead of what I expect to see: **"192.168.8.1 is at <MacBook Mac Address>"**

Is there any way to manually set the gateway IP you want to spoof? I read through the documentation and all I could find were ways to specify the target you want to direct the ARP messages to.

Thanks!!

**Comment by evilsocket** [comment]
please provide the logs and all the other info that were in the issue template you just ignored, then i'll reopen.
