### ISSUE TITLE
Installation error: package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by xSetBack** [bettercap/bettercap#880]
Error with GO when i try to install Bettercap with ' _go get -u github.com/bettercap/bettercap_ '.

Output:
' _package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)_ '.

I'm trying to install the latest version of bettercap with no results.

**System info:**
_Linux setback 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux_
.
**Go version:**
_go version go1.11.6 linux/amd64_

**### Steps to Reproduce**

I was only following the [official installation guide](https://www.bettercap.org/installation/)

**Expected behavior:** *Bettercap successfully installed*

**Actual behavior:** *unrecognized import path "crypto/ed25519" (import path does not begin with hostname)*

--

**Comment by xSetBack** [comment]
**Ok, I've resolved this issue.**
The problem was the Golang version, the version go1.11.6 seems to be too old.
I get the latest version and all works fine.

**What i've done:**

_wget https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.16.4.linux-amd64.tar.gz_

and I have added the directory to my $PATH.

**Comment by codebyannapurna** [comment]
I believe it is good to update the Instructions to the latest versions.
