### ISSUE TITLE
arp.spoof using own IP address 

### ISSUE THREAD

**Issue by krypto-kraken** [bettercap/bettercap#883]
Hello,

Sorry for not seeing the template to begin with. I think I have all information included this time but just let me know if I missed something.

*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version 2.29
* macOS Bug Sur 11.3.1
* Built using homebrew - not source
* _sudo bettercap_ -> _arp.spoof on_
* Not using a caplet

*** FULL DEBUG OUTPUT BELOW *** 

[1mbettercap v2.29[0m [2m(built for darwin amd64 with go1.15.6)[0m [type '[1mhelp[0m' for a list of commands]

[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [18:45:48] [[32msys.log[0m] [[2m[30m[100mdbg[0m] FindGateway(en0) [cmd=netstat opts=[-n -r] parser=([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+).*]
[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [18:45:48] [[32msys.log[0m] [[2m[30m[100mdbg[0m] FindGateway(en0) output:
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
default            10.215.1.1         UGScg          en0       
default            link#18            UCSIg      bridge1      !
default            link#20            UCSIg      bridge1      !
10.xx.xxx/24       link#20            UC         bridge1      !
10.xx.xxx.2        f2.18.98.xx.xx.xx  UHLWIi         lo0       
10.215.1/24        link#6             UCS            en0      !
10.215.1.1/32      link#6             UCS            en0      !
10.215.1.1         30:23:3:xx.xx.xx   UHLWIir        en0   1190
10.215.1.10        44:e4:ee:xx.xx.xx  UHLWIi         en0    605
10.215.1.70        30:23:3:xx.xx.xx    UHLWI          en0   1152
10.215.1.211       d2:cb:90:xx.xx.xx  UHLWI          en0    527
10.215.1.218       30:23:3:xx.xx.xx    UHLWI          en0   1152
10.215.1.247/32    link#6             UCS            en0      !
10.215.1.247       f0:18:98:xx.xx.xx  UHLWI          lo0       
127                127.0.0.1          UCS            lo0       
127.0.0.1          127.0.0.1          UH             lo0       
169.254            link#6             UCS            en0      !
172.16.10/24       link#18            UC         bridge1      !
172.16.10.2        f2.18.98.xx.xx.xx  UHLWIi         lo0       
224.0.0/4          link#6             UmCS           en0      !
224.0.0.251        1:0:5e:xx.xx.xx      UHmLWI         en0       
224.0.0.251        1:0:5e:xx.xx.xx      UHmLWIg    bridge1       
224.0.0.251        1:0:5e:xx.xx.xx      UHmLWIg    bridge1       
225.0.3.15         1:0:5e:xx.xx.xx       UHmLWI         en0       
239.255.255.250    1:0:5e:xx.xx.xx   UHmLWI         en0       
239.255.255.250    1:0:5e:xx.xx.xx    UHmLWIg    bridge1       
239.255.255.250    1:0:5e:xx.xx.xx    UHmLWIg    bridge1       
255.255.255.255/32 link#6             UCS            en0      !
[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [18:45:48] [[32msys.log[0m] [[2m[30m[100mdbg[0m] FindGateway(en0) line 'default            10.215.1.1         UGScg          en0' matched with [default            10.215.1.1         UGScg          en0 default 10.215.1.1 UGScg en0]
[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [18:45:48] [[32msession.started[0m] {session.started 2021-05-24 18:45:48.889585 -0400 EDT m=+0.027058413 <nil>}
[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [18:45:48] [[32mmod.started[0m] events.stream
[J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m [J[2K
[43m[97m10.215.1.0/24 [30m> 10.215.1.247 [0m [1m» [0m[0m^C
Are you sure you want to quit this session? y/n 
[18:45:55] [[32msys.log[0m] [[97m[43mwar[0m] Got SIGTERM

Stopping modules and cleaning session state ...
[18:45:55] [[32msession.closing[0m] {session.closing 2021-05-24 18:45:55.032477 -0400 EDT m=+6.169766122 <nil>}

*** END DEBUG OUTPUT ***

### Steps to Reproduce

1. Start up bettercap - _sudo bettercap_
2. _arp.spoof on_

**Expected behavior: When monitoring Wireshark, I expected to see an ARP message such as "10.215.1.1 is at [my own MAC address]" - with 10.215.1.1 being the gateway router on my network. Basically, I was expecting to see ARP messages directing clients on the network toward my MAC address for any traffic, DNS queries, etc...

**Actual behavior: see below - my original IP address (10.215.1.247) is being used instead of 10.215.1.1 and ARP is just functioning as intended. 

![image](https://user-images.githubusercontent.com/32921526/119416746-532bf880-bcc2-11eb-8b8b-f451b355b92d.png)

Thanks for the help!!

**Comment by c4bler** [comment]
I also got this. Running _sudo bettercap -iface tap0_
Bettercap just seemed interested in advertising its own IP address to the targets, according to wireshark.
Maybe it has problems with the openvpn interface?
At start, i get this exact log message:
`[sys.log] [war] Could not find mac for `

One thing to note. It worked fine by just running 'sudo bettercap' on my class A network (eth0 default).
`sudo bettercap
set arp.spoof.fullduplex true
set arp.spoof.targets 10.0.0.1,10.0.0.2
arp.spoof on`
The only difference in 'ip addr' between the non-working and working iface is 'state UNKNOWN' instead of 'state UP'
