### ISSUE TITLE
when http.proxy on OR https.proxy on appear [sys.log] [err] exit status 4

### ISSUE THREAD

**Issue by yakhira** [bettercap/bettercap#886]
*Description of the bug or feature request*

### Environment

Please provide:

* bettercap v2.30.2 (built for linux arm64 with go1.15.8)
* Nethunter on Android
* bettercap -iface wlan0
* http.proxy on
* Debug output:
192.168.0.0/24 > 192.168.0.3  » http.proxy on
[15:53:21] [sys.log] [err] exit status 4

### Steps to Reproduce

1. http.proxy on

**Expected behavior:** *working http.proxy mode*

**Actual behavior:** *[15:53:21] [sys.log] [err] exit status 4*

**Comment by yakhira** [comment]
what exactly status 4 mean?

**Comment by yakhira** [comment]
never mind, figured out by myself

**Comment by elmage78** [comment]
Hey i have encountered your EXACT SAME ISSUE down to the version is the same so if you could please share how you managed to fix it
