### ISSUE TITLE
Compilation Fails [OpenWRT] [mipsle]

### ISSUE THREAD

**Issue by DeathCamel58** [bettercap/bettercap#887]
Compiling using OpenWRT's cross compiler toolchain fails. 

### Environment

Host:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```
`Linux deathcamel57 5.11.0-7614-generic #15~1618626693~21.04~ecb25cd~dev-Ubuntu SMP Thu Apr 22 15:35:26  x86_64 x86_64 x86_64 GNU/Linux`

Target:
```
DISTRIB_ID='OpenWrt'`
DISTRIB_RELEASE='19.07.3'
DISTRIB_REVISION='r11063-85e04e9f46'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.3 r11063-85e04e9f46'
DISTRIB_TAINTS='no-all `busybox'
```

OpenWRT Toolchain:
Tag `19.07.3` on OpenWRT's repository

### Details
Using OpenWRT's cross compiler toolchain, Bettercap commit ff91392866078d8b679b3711f668bebceed0b115 compiles properly.
Using the next commit (b3da4e30f7f6f1301f9c81d58a87c36494d83faf) does not compile properly. This issue persists up to latest commit.

### Failing Compilation Output
Command run: `make package/bettercap/{clean,compile} V=sc`
```
github.com/bettercap/bettercap/modules/events_stream
github.com/bettercap/bettercap/modules/c2
github.com/bettercap/bettercap/modules
github.com/bettercap/bettercap
# github.com/bettercap/bettercap
/home/deathcamel57/Documents/dev/openwrt/staging_dir/hostpkg/lib/go-cross/pkg/tool/linux_amd64/link: running ccache_cc failed: exit status 1
/home/deathcamel57/Documents/dev/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/lib/gcc/mipsel-openwrt-linux-musl/7.5.0/../../../../mipsel-openwrt-linux-musl/bin/ld: non-dynamic relocations refer to dynamic symbol __libc_start_main
/home/deathcamel57/Documents/dev/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/lib/gcc/mipsel-openwrt-linux-musl/7.5.0/../../../../mipsel-openwrt-linux-musl/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status

Cleaning module download cache (golang/go#27455)
make[2]: *** [Makefile:59: /home/deathcamel57/Documents/dev/openwrt/build_dir/target-mipsel_24kc_musl/bettercap-2.31.1/.built] Error 2
make[2]: Leaving directory '/home/deathcamel57/Documents/dev/pineapple-packages-community/network/bettercap'
time: package/feeds/pineapplecommunity/bettercap/compile#66.15#6.35#20.93
make[1]: *** [package/Makefile:113: package/feeds/pineapplecommunity/bettercap/compile] Error 2
make[1]: Leaving directory '/home/deathcamel57/Documents/dev/openwrt'
make: *** [/home/deathcamel57/Documents/dev/openwrt/include/toplevel.mk:227: package/bettercap/compile] Error 2
```
Full log attached: [failed-compilation.txt](https://github.com/bettercap/bettercap/files/6573219/failed-compilation.txt)

As a note, here's my OpenWRT package build file for your reference (rename to `Makefile`): 
[Makefile.txt](https://github.com/bettercap/bettercap/files/6573248/Makefile.txt)

I do recognize that this may not be an issue with your OpenWRT's toolchain, not your project. Feel free to close. Thank you for bettercap.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by adde88** [comment]
I also get the exact same problem when trying to update Bettercap. 😮 
I'll try to dig more into the problem whenever i have time. 👍

**Comment by julianoborba** [comment]
Got same error, this solved:

https://github.com/immortalwrt/Rclone-OpenWrt/issues/1#issuecomment-568445311

In my case, at `openwrt/feeds/packages/lang/golang/golang-package.mk` file on `define GoPackage/Environment/Default` procedure, replace `CGO_ENABLED=1 \` to `CGO_ENABLED=0 \`.

Hope it works for you, as we apparently have the same issue.
