### ISSUE TITLE
wifi.deauth.aquired does not work

### ISSUE THREAD

**Issue by dennis777** [bettercap/bettercap#889]
### Environment
Bettercap version: `v2.31.1`
OS: `Kali Linux`
Args: `bettercap (-debug) -iface wlan1`
Code run in interface: 
```
wifi.recon on; set wifi.deauth.aquired true; set wifi.show.manufacturer true
set ticker.commands "wifi.deauth BSSID"; ticker on
```

 Debug output:
```
wlan1  » [06:19:13] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
wlan1  » [06:19:13] [sys.log] [dbg] Could not find mac for 
[06:19:49] [sys.log] [dbg] SetInterfaceTxPower(wlan1, 30) iw based
[06:19:49] [sys.log] [dbg] wifi new frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484]
[06:19:49] [sys.log] [dbg] wifi wifi supported frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484]
wlan1  » [06:19:49] [sys.log] [dbg] wifi wifi stations pruner started (ap.ttl:5m0s sta.ttl:5m0s).
wlan1  » [05:55:32] [sys.log] [dbg] wifi got frame 1/4 of the [BSSID] <-> [Client BSSID] handshake (without PMKID)
wlan1  » [05:55:32] [sys.log] [dbg] wifi adding beacon frame to handshake for [BSSID]
wlan1  » [05:55:32] [sys.log] [dbg] wifi (aggregate true) saving handshake frames to /root/bettercap-wifi-handshakes.pcap
wlan1  » [06:19:49] [sys.log] [dbg] wifi wifi stations pruner started (ap.ttl:5m0s sta.ttl:5m0s).
wlan1  » [05:55:32] [wifi.client.handshake] captured [Client BSSID] -> [SSID] (BSSID) WPA2 handshake (half) to /root/bettercap-wifi-handshakes.pcap
wlan1  » [05:55:32] [sys.log] [dbg] wifi saving extra DataQOSData frame (173 bytes) for [Client BSSID] (Client Manufacturer)
wlan1  » [05:55:32] [sys.log] [dbg] wifi (aggregate true) saving handshake frames to /root/bettercap-wifi-handshakes.pcap
wlan1  » [05:55:32] [sys.log] [dbg] wifi got frame 2/4 of the [BSSID] <-> [Client BSSID] handshake
wlan1  » [05:55:46] [sys.log] [dbg] wifi skipping deauth for AP [SSID] (key material already acquired)
wlan1  » [05:55:46] [sys.log] [dbg] wifi skipping deauth for AP [SSID] (key material already acquired)
...
```
### Steps to Reproduce
1. Launch Bettercap `bettercap -iface wlan1`
2. Run the commands once inside the interface (see commands above)

**Expected behavior:**
Bettercap will continue to deauth the listed Client BSSID even if bettercap has already collected a handshake for the clients AP

**Actual behavior:**
Bettercap deauths targets until handshake is captured and then bettercap skips deauthing Client because it has already captured the handshake for the clients AP. In essence, it ignores the `set wifi.deauth.aquired true` and will skip deauthing clients and APs regardless what `wifi.deauth.aquired` it is set to.

**Comment by evilsocket** [comment]
settings must be set **before** turning the module on

**Comment by dennis777** [comment]
Hello, I tried running the same command this time setting the settings before turning the module on but it still doesn't work. 

```
set wifi.deauth.aquired true; set wifi.show.manufacturer true; wifi.recon on; 
set ticker.commands "wifi.deauth BSSID"; ticker on
```

**Comment by buffermet** [comment]
We will need more logs as it is possible than no more clients are connected to the AP.

The `wifi.deauth` module requires at least 1 station to be authenticated to an AP.

**Comment by dennis777** [comment]
Okay sure. What would you like me to do?

**Comment by dennis777** [comment]
Let me know which steps you would like me to follow

**Comment by dennis777** [comment]
@buffermet Hello, my issue has not been resolved, bettercap is skipping over despite `set wifi.deauth.aquired true`

**Comment by buffermet** [comment]
You need to provide complete debug logs, not just a portion like you have in your original post.
