### ISSUE TITLE
Cannot get password using bettercap and stuck in a loop of net.sniff.http.request/response

### ISSUE THREAD

**Issue by gaurav3278** [bettercap/bettercap#899]
---

*Description of the bug or feature request*

### Environment kali lunix as vm

Please provide:

* Bettercap version you are using ( `bettercap -version` ). **v2.23**
* OS version and architecture you are using.  **kali lunix as vm**
* Go version if building from sources.
* Command line arguments you are using.   **bettercap -iface eth0 -caplet spoof.cap**

* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. i started bettercap arp spoofing
2. i tried to spoof another vm win 10
3. everything works fine bt then i continuously get msg of net.sniff.http.request and net.sniff.http.response

**Expected behavior:** *I expect to gain password by bypassing https site*

**Actual behavior:** *i got stuck in  net.sniff.http.request and net.sniff.http.response 
![Screenshot 2021-07-15 092434](https://user-images.githubusercontent.com/75034765/125726563-d024876b-d75b-4c8b-a3f8-4d1e079dd92e.jpg)
.i was able to degrade https but cant get password and username *

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
that looks more like a bug in the webapp, net.sniff can't create "loops", it just reports what's sniffing on the interface, which in this case depends on the vm activity rather than the spoofing itself
