### ISSUE TITLE
arp spoofing causes remote access to drop

### ISSUE THREAD

**Issue by J3rry367** [bettercap/bettercap#900]
### Environment
* Bettercap version: bettercap v2.31.1
* OS version: Windows 10
* Command line arguments: bettercap.exe -iface <<iface>> -caplet http-ui

### Steps to Reproduce
1. Remote into Windows 10 system (RDP, TeamViewer, SSH, ping, etc.)
2. run 'bettercap.exe -iface <<iface>> -caplet http-ui'
3. start arp.spoof

**Expected behavior:** *What you expected to happen*
remote connection to stay active so I can monitor and disable spoofing as necessary.

**Actual behavior:** *What actually happened*
remote connection drops until arp.spoof has been stopped or network connection is reset. I've tried on multiple Windows 10 systems on multiple different network environments. The system is not locking up but it appears as though the network card is being locked up by the attack.

**Comment by Decapitater** [comment]
are you using external antenna for spoofing ?
