### ISSUE TITLE
Exit status code 4 when running proxy-related modules

### ISSUE THREAD

**Issue by mrsheepsheep** [bettercap/bettercap#909]
Related to bettercap/caplets#53

### Environment

* bettercap v2.32.0
* linux arm64
* go1.15.15
* Running on Kali Nethunter (Android 10, rooted device, running directly from kali chroot)
* Bettercap was installed from `apt install bettercap`

Bettercap started with `bettercap -i wlan0` followed by `http.proxy on`.

Debug output below, but there are no debug messages related the proxy.

![image](https://user-images.githubusercontent.com/4931825/132121789-47f7378f-1d03-49f3-8763-2c9d08cc4fbd.png)

`curl` exits with status code 7 when connection fails, so that was expected.

Same behavior when running `https.proxy on` and `any.proxy on`

### Expected behavior
Proxy should start running and listen for connections on specified port (in the case of the screenshot, port 8081)

Here is how it behaves on a "normal" Kali amd64 installation :

![image](https://user-images.githubusercontent.com/4931825/132121862-56ed9d1c-87e0-4c70-8d7e-37eef0175ed2.png)

### Actual behavior
`http.proxy on` and other proxy-related services exits with status code 4, running them again shows redirection is already enabled, but running `curl 127.0.0.1:8081` to reach the proxy shows it's not running.

### Steps to reproduce

I could not provide steps to reproduce, as I'm running on a fresh Nethunter install and steps are already clearly defined - just run bettercap and run `http.proxy on` on the same environment. Since I don't know what causes the issue, you probably cannot easily reproduce the problem.

Any suggestion on how I could further debug this on my own (if you could not replicate the environment) ? The `-debug` option is not helping much here.

**Comment by ntoskrnl-exe** [comment]
I have a similar problem. Given the above user is having a similar problem and the -debug is not providing much more information - is there another way to troubleshoot this issue?

**Comment by 90N45-d3v** [comment]
### Same problem on Raspberry Pi Zero W

I got the same issue while trying to use proxy modules on my rpi0w with a Raspberry OS lite + re4son kernel (Linux raspberrypi 4.14.93-Re4son+ #1 Fri Jan 25 05:56:01 AEDT 2019 armv6l GNU/Linux).
Everything works fine on my kali linux machine.

I just used the pre-compiled bin-file and installed this dependencies with apt: _golang git build-essential libpcap-dev libusb-1.0-0-dev libnetfilter-queue-dev_
Are there any dependencies for the proxy functionality of bettercap, which aren't mentioned in the [bettercap documentation](https://www.bettercap.org/installation/)?

**Comment by buffermet** [comment]
Looks like an uncaught error.

You may find out more by tailing the contents of `/var/log/syslog` when the error occurs.

**Comment by evilsocket** [comment]
is wlan0 connected?
