### ISSUE TITLE
multiple wireless interfaces configuration/support

### ISSUE THREAD

**Issue by geekskunk** [bettercap/bettercap#910]
Interested if possible to use more then 1 wireless interface for wifi.recon.

**Comment by buffermet** [comment]
You should use multiple instances of bettercap because there would be no way to specify which interface to operate/configure.

**Comment by Jellyfrog** [comment]
I think this should be reopened again, for example kismet supports multiple interfaces at the same time.

A very quick look at the code and it seems like if it was possible to load multiple instances of the wifi module [with different parameters], this could work.
Its most likely a very oversimplified assumption tho :)
