### ISSUE TITLE
'ble' commands work once per bettercap run?

### ISSUE THREAD

**Issue by jethr0-1** [bettercap/bettercap#922]
### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ): bettercap v2.32.0
* OS version and architecture you are using - Kali 2021.3, x86_64
* Command line arguments you are using - None, only ran 'sudo bettercap'
* Caplet code you are using or the interactive session commands - ble.recon/write/enum
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ) - https://pastebin.com/U2GpJbUq

### Steps to Reproduce

1. ```sudo bettercap``` and Run ble.recon
2. Run ble.enum on a detected device
3. Attempt to run ble.enum on the same device again

**Expected behavior:** *What you expected to happen*
Get the same result on the second enum as on the first.

**Actual behavior:** *What actually happened*
Returned ```[war] ble.recon connection timeout```

From what I can tell only the first ble command that interacts directly with a device works, and then I have to restart bettercap in order to write or enum anything else. Is there a way to solve this?

**Comment by telefax** [comment]
I have a similar problem but with events.stream (not really testing anything else).
I'm loading a caplet with some info about my logfile, rotation etc, so apparently I need to do a ```events.stream off``` and then ```events.stream on``` at every new session to make my event.stream settings take effect.

However, events.stream refuses to start again after I have stopped it once.
```active``` doesn't show it and help just says "not running" on events.streams.

Running: ```bettercap v2.32.0 (built for linux arm with go1.15.9)```

**Comment by mmbaguette** [comment]
You’re probably using VirtualBox or another virtual machine. I had the same issue. You could try importing the Bluetooth adapter like it’s a USB, to give your VM full control.

**Comment by jethr0-1** [comment]
> You’re probably using VirtualBox or another virtual machine. I had the same issue. You could try importing the Bluetooth adapter like it’s a USB, to give your VM full control.

Nope, not using any kind of virtualisation. Using Kali Linux running on my laptop bare-metal.
