### ISSUE TITLE
[BUG]Rpi Zero 2 W: (fatal error: concurrent map iteration and map write)

### ISSUE THREAD

**Issue by alexl83** [bettercap/bettercap#927]
*Description of the bug or feature request*
bettercap crashes with
`(fatal error: concurrent map iteration and map write)`
on Rpi Zero 2 W using pwnagotchi 1.5.5, kali packages 5.4.83-20210516 and an external rt5592-based wifi adapter

same scenarios/setup do not trigger crashes on rPi Zero W (first generation)
Same crash happens on both my rPi Zero 2 W boards

**Seems similar to Issue #811 and #803**

Tried bettercap releases:
- 2.31 from pwnagotchi distribution
- 2.31.1 from bettercap release page (armhf)
- 2.32 compiled natively from sources (using go1.17.4.linux-armv6l and official build instructions) (build attached) 
[bettercap_2.32.zip](https://github.com/bettercap/bettercap/files/7656326/bettercap_2.32.zip)
 
`sha256: c8060376323594949b837bc264e55e1bef04263609c944c0cacdc2534d8dee50 bettercap`

bettercap up-to-date with
`sudo bettercap -eval "caplets.update; ui.update; q"`

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). 
```
bettercap v2.32.0 (built for linux arm with go1.17.4)
bettercap v2.31.0 (built for linux arm with go1.16.2)
bettercap v2.31.1 (built for linux arm with go1.16.2)
```

* OS version and architecture you are using. `Raspberry OS Buster (pwnagotchi 1.5.5)`
* Go version if building from sources. `go1.17.4 armv6l`
* Command line arguments you are using. `/usr/bin/bettercap -no-colors -caplet pwnagotchi-auto -iface mon0`
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
[bettercap_crashlog.txt](https://github.com/bettercap/bettercap/files/7656254/bettercap_crashlog.txt)

### Steps to Reproduce

1. connect wifi adapter
2. provide power and let it run for 7-60 mins
3. wait for crash

**Expected behavior:** 
continuos running and packet collection

**Actual behavior:**
bettercap crashes and pwnagotchi unit goes blind 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by nuk3s** [comment]
I am able to replicate this behavior on my RPI02w.  It appears to occur more frequently when exposed to a large number of networks, i.e. when driving or biking, as opposed to when sitting in one place with only a moderate  number (~30) of networks nearby.

**Comment by evilsocket** [comment]
duplicarte of https://github.com/bettercap/bettercap/issues/803
