### ISSUE TITLE
Can't build bettercap from source, issue with packet_proxy module

### ISSUE THREAD

**Issue by janemba** [bettercap/bettercap#928]
### Environment

Please provide:

* GNU/Linux Slackware kernel 5.12.13
* go version go1.16.5 gccgo (GCC) 11.2.0 linux/amd64
* go get github.com/bettercap/bettercap

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
* Output from `go get` command
```
github.com/bettercap/bettercap imports
	github.com/bettercap/bettercap/modules imports
	github.com/bettercap/bettercap/modules/packet_proxy imports
	plugin: package plugin is not in GOROOT (/usr/lib64/go/src/plugin)
```

### Steps to Reproduce

1. go get -u github.com/bettercap/bettercap

**Expected behavior:** *What you expected to happen*
* build bettercap

**Actual behavior:** *What actually happened*

```
$ go get -u github.com/bettercap/bettercap
go: downloading golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/mattn/go-colorable v0.1.12
github.com/bettercap/bettercap imports
	github.com/bettercap/bettercap/modules imports
	github.com/bettercap/bettercap/modules/packet_proxy imports
	plugin: package plugin is not in GOROOT (/usr/lib64/go/src/plugin)
```
--

**Comment by buffermet** [comment]
Is your go environment set up properly?

Can you give us the output of `echo $GOROOT` and `ls $GOROOT`?

**Comment by myk-coder** [comment]
> Is your go environment set up properly?
> 
> Can you give us the output of `echo $GOROOT` and `ls $GOROOT`?

go build -o bettercap .
modules/packet_proxy/packet_proxy_linux.go:7:2: package plugin is not in GOROOT (/usr/src/plugin)
make: *** [Makefile:9: build] Error 1


same error here, help please
