### ISSUE TITLE
Build Docker image for ARM and ARM64

### ISSUE THREAD

**Issue by NN708** [bettercap/bettercap#931]
At present, the Docker image `bettercap/bettercap` only supports AMD64 so cannot be run on Raspberry Pi or M1. Hope that multi-arch image could be built and published on Docker Hub.

**Comment by mmbaguette** [comment]
Even if it could, I tried Bettercap on Docker and had no luck: https://www.reddit.com/r/HowToHack/comments/clytqd/bettercap_install_error_with_docker/.

**Comment by greaterthanstar** [comment]
I saw this line when doing `docker search bettercap`: 
`x2qnet/docker-rpi-bettercap         Bettercap for Raspberry Pi `
Is that legit or vouched for by the bettercap team?? any movement on the rPI front?

**Comment by IQEwan** [comment]
Does the dev team have any updates for Apple Chip in 2022?

**Comment by srinjoychakravarty** [comment]
still not able to compile and run bettercap v2.23 on kali on Mac M1 host (Feb 2023) !?

**Comment by evilsocket** [comment]
https://hub.docker.com/r/bettercap/bettercap/tags
