### ISSUE TITLE
Problem with sslstrip. Not loading the site

### ISSUE THREAD

**Issue by Mariontaz** [bettercap/bettercap#932]
Hey!
I have some problems with sslstrip. The sslstrip is not working. It will redirect to http from https but the site will not load. The sslstrip doesn’t work at all I tried different versions all from the newest to 1.6.2. I’m using mobile hotspot for the internet connection and tried it on iPhone safari browser and opera browser. It will be redirect to http and I see that in pcap but the problem is that the site will not load. And no sites will load. I even look up the sites on hstspreload.org list and they should be working. What is the problem? I have tried everything. Now I’m using the newest bettercap version but the problem is on all versions. I’m using Ubuntu 20.04. Go version I have always follow the manuals so now in the newest version I’m using go 1.6. 

The commands I have used is:
sudo bettercap -iface wlp4s0 
net.probe on
net.sniff on
set arp.spoof.fullduplex true (both with and without it, I have tried both) 
set arp.spoof.internal true 
set http.proxy.sslstrip true (I have tried with https.proxy.sslstrip also and with both of them at same time)
http.proxy on (I have tried with https.proxy.sslstrip also and with both of them at same time, https.proxy on with http.proxy and them separated) 
arp.spoof on

**Comment by buffermet** [comment]
Please write a complete issue using the issue template that you deleted.
