### ISSUE TITLE
Deauth not working!!!!!!!

### ISSUE THREAD

**Issue by MURSHIG** [bettercap/bettercap#933]
When I Start deauth, app showing it started, but when I checking it on my phone, its not disconnecting

**Comment by ZhangUranus** [comment]
Same issue with me,  macOS Monterey 12.1 & Macbook-pro 2019.  I do not know whether it is for Apple inc did something special in OS to filter this deauthing package. Any help ..?

**Comment by mmbaguette** [comment]
Your question is very unclear. Can you tell us the steps to reproduce your issue? What have tried?

**Comment by buffermet** [comment]
We cannot help you if you do not fill out the complete issue template that you deleted.
