### ISSUE TITLE
Attack simulation MITM  for genymotion with bettercap

### ISSUE THREAD

**Issue by mandana94** [bettercap/bettercap#934]
I installed and run bettercap. But when I enter command "net.show", the genymotion IP does not scan or show me.
I want to attack (MITM) on a simulated device with bettercap.
please guide me.
Thank you.

**Comment by mmbaguette** [comment]
Please read the *very helpful and very clear* documentation before you open a question. The `net.probe` module finds new devices, then the `net.recon` module lists new hosts that have already been found.

`net.probe on`:
https://www.bettercap.org/modules/ethernet/net.probe/
