### ISSUE TITLE
Bettercap shuts Bluetooth off when ble.recon is on

### ISSUE THREAD

**Issue by mmbaguette** [bettercap/bettercap#936]
`ble.recon` module doesn't show any devices.

`sudo bettercap --debug`:

I turn `ble.recon on`:
```
192.168.60.0/24 > 192.168.60.128  » ble.recon on
[20:14:19] [sys.log] [dbg] ble.recon initializing device (id:-1) ...
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] got 1 devices
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 up
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 reset
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 down
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] dev: hci0 opened
[20:14:19] [sys.log] [dbg] ble.recon [gatt.log] hci.mainLoop started
```
As soon as the module's on, the Bluetooth icon in Kali Linux disappears. Weirdly enough, when I `ble.recon off`, Bluetooth turns back on:
```
[gatt.log] hci.Close()
[20:18:49] [sys.log] [inf] ble.recon stopping scan ...
[20:18:49] [mod.stopped] ble.recon
[20:18:49] [sys.log] [dbg] ble.recon stopping device
[20:18:49] [sys.log] [dbg] ble.recon [gatt.log] got nil buffer, breaking mainLoop
[20:18:49] [sys.log] [dbg] ble.recon [gatt.log] mainLoop exited
[20:18:49] [sys.log] [dbg] ble.recon [gatt.log] linux.device.Close()
[20:18:49] [sys.log] [dbg] ble.recon [gatt.log] closing &{5 [{5 1 0}] 0 hci0 0xc0005a04a0 0xc0005a04a8}
[20:18:49] [sys.log] [dbg] ble.recon [gatt.log] hci.mainLoop stopped
192.168.60.0/24 > 192.168.60.128  » [20:18:50] [sys.log] [dbg] ble.recon resetting device instance
192.168.60.0/24 > 192.168.60.128  » [20:18:50] [sys.log] [dbg] ble.recon state changed to PoweredOff
192.168.60.0/24 > 192.168.60.128  » [20:18:50] [sys.log] [dbg] ble.recon gatt device closed
192.168.60.0/24 > 192.168.60.128  » [20:18:50] [sys.log] [dbg] ble.recon module stopped, cleaning state
```
hciconfig:
```
hci0:   Type: Primary  Bus: USB
        BD Address: E8:48:B8:C8:20:00  ACL MTU: 1021:6  SCO MTU: 255:12
        UP RUNNING 
        RX bytes:9766 acl:0 sco:0 events:745 errors:0
        TX bytes:42127 acl:0 sco:0 commands:844 errors:1
```
`hci0` is still on even when the `ble.recon` module is running.

System:
- TP-Link UB500 External Bluetooth Adapter
- Kali Linux 2021.4
- bettercap v2.32.0 (built for linux amd64 with go1.15.15)
- VMware (no issue on PC with same Bluetooth adapter)
- Toshiba Satellite Laptop (old laptop)

I don't believe the problem is with VMware because I'm directly connecting the Bluetooth adapter like a USB into the guest machine running Kali Linux.

**Comment by buffermet** [comment]
Use `ble.show` to enumerate detected devices.

Please read the manual: https://www.bettercap.org/modules/ble/

**Comment by buffermet** [comment]
If there really are Bluetooth devices broadcasting within your vicinity, try disabling your default Bluetooth manager before starting the ble.recon module:

`sudo systemctl stop bluetooth`

**Comment by mmbaguette** [comment]
Thanks for reopening this issue. Yes I have tried that too. ble.recon should show me devices. ble.show is now necessary. Is there a chance that BLE is not supported on my Bluetooth adapter? I have done my research, and read that it’s fully compatible on Ubuntu, and at least on Windows BLE compatible, but I don’t know about BLE on Linux. 

I read similar issues and they told me to do hcitool lescan to find BLE devices That resulted in a socket i/o error, which is apparently common: https://stackoverflow.com/questions/22062037/hcitool-lescan-shows-i-o-error

I asked something in the comments of the first answer that has to do with Kali. I’ll try Bettercap ble.recon on Ubuntu and get back to you. Thanks.

**Comment by buffermet** [comment]
It should work on Kali. Try troubleshooting with the answers in that Stackoverflow link. As far as I can tell your setup should work.

**Comment by mmbaguette** [comment]
Yes I did that. In the first answer, it suggested restarting dbus. But just like someone in the comments of that answer claims, that process crashes kali. Bluez is at the latest version for me.

**Comment by mmbaguette** [comment]
Closing this issue. Tried with Ubuntu. I think that Linux is just no good when it comes to BLE in general. `hcitool lescan` doesn't even work, which is a main Bluetooth module for scanning BLE devices. I have so many issues with Bluez (which is the package for hciconfig, hcitool and bluetoothctl).

**Comment by buffermet** [comment]
I haven't had issues with it on Kali. It may just be a driver issue.

**Comment by mmbaguette** [comment]
Probably, but it doesn't seem like something Bettercap can solve /:
