### ISSUE TITLE
ble.recon throws an error

### ISSUE THREAD

**Issue by naltun** [bettercap/bettercap#94]
### Description
`ble.recon on` throws an error:
```
192.168.2.0/24 > 192.168.2.20  » ble.recon on
192.168.2.0/24 > 192.168.2.20  » [08:34:43] [sys.log] [inf] Initializing BLE device ...
192.168.2.0/24 > 192.168.2.20  » [08:34:43] [sys.log] [err] no supported devices available
```

### Environment
* Antergos Linux -- x86_64
* go version go1.10 linux/amd64
* None, eg. `$ bettercap`
* None
* `ble.recon on`

Please provide:

* OS version and architecture you are using.
* Go version if building from sources.
* Command line arguments you are using.
* Caplet code you are using (if any).
* Interactive session commands you are using (if any).
* No debug output after `ble.recon on`

### Steps to Reproduce

1. Launch `bettercap` normally, without arguments
2. Activate `ble` reconnaissance 

**Expected behavior:** *What you expected to happen*
To begin BLE device monitoring

**Actual behavior:** *What actually happened*
An error, `192.168.2.0/24 > 192.168.2.20  » [08:34:43] [sys.log] [err] no supported devices available`

**Comment by naltun** [comment]
I troubleshooted the issue to being a local issue. I had some issues with `rfkill` but have fixed them. Feel free to close this. Thanks mate.

**Comment by evilsocket** [comment]
:+1: - victory dance -
