### ISSUE TITLE
Question about the source code

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [bettercap/bettercap#941]
i was reading the bettercap source code under the `wifi_deauth.go` at  

https://github.com/bettercap/bettercap/blob/master/modules/wifi/wifi_deauth.go

im new to networking and was confused at this code here 

```go
	// let the network card breath a little
	time.Sleep(10 * time.Millisecond)
```

i understand the comment has `let the network card breathe` but is that needed? if so then why?

**Comment by Azrotronik** [comment]
Yes, Most consumer grade WLAN cards can't handle such loads, and bettercap sends a _lot_ of packets, you risk missing handshake packets and so on, especially when you're deauthing "*" (All networks in range).

**Comment by ArkAngeL43** [comment]
oh cool, i didnt even think about that. i certainly appreciate the response
