### ISSUE TITLE
USE bettercap I can't complete DNS spoofing

### ISSUE THREAD

**Issue by czg6666666** [bettercap/bettercap#942]
Hello, I can't complete DNS spoofing, I do this experiment, there are two virtual machines, one is connected to the router with WiFi (A), the other is bridged with a virtual network card (B), and A is used to specify the WiFi network interface of wlan0, Then use bettercap for ARP spoofing and DNS spoofing, virtual machine B, but as described in the picture, he cannot resolve the url www.taobao.com to my virtual machine A. Why?

【A machine】
.168.0.0/24 > 192.168.0.106  » set arp.spoof.targets 192.168.0.103
192.168.0.0/24 > 192.168.0.106  » arp.spoof on
[08:52:16] [sys.log] [inf] arp.spoof enabling forwarding
192.168.0.0/24 > 192.168.0.106  » [08:52:16] [sys.log] [inf] arp.spoof arp spoofer started, probing 1 targets.
192.168.0.0/24 > 192.168.0.106  » set dns.spoof.domains *
192.168.0.0/24 > 192.168.0.106  » set dns.spoof.address 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » dns.spoof on
[08:52:41] [sys.log] [inf] dns.spoof * -> 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » dns.spoof off
192.168.0.0/24 > 192.168.0.106  » set dns.spoof.all true
192.168.0.0/24 > 192.168.0.106  » dns.spoof on
[08:54:16] [sys.log] [inf] dns.spoof * -> 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » dns.spoof off
192.168.0.0/24 > 192.168.0.106  » set dns.spoof.domains www.baidu.com,wwww.taobao.com
192.168.0.0/24 > 192.168.0.106  » set dns.spoof.address 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » dns.spoof on
[08:56:03] [sys.log] [inf] dns.spoof www.baidu.com -> 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » [08:56:03] [sys.log] [inf] dns.spoof wwww.taobao.com -> 192.168.0.106
192.168.0.0/24 > 192.168.0.106  » [09:08:53] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106  » [09:08:54] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106  » [09:08:55] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106  » [09:08:56] [sys.log] [war] arp.spoof could not find spoof targets

【B machine】
┌──(root💀kali)-[~]
└─# ping www.taobao.com
PING www.taobao.com.danuoyi.tbcache.com (111.29.22.227) 56(84) bytes of data.
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=1 ttl=55 time=28.6 ms
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=2 ttl=55 time=28.1 ms
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=3 ttl=55 time=27.4 ms
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=4 ttl=55 time=198 ms
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=5 ttl=55 time=30.8 ms
64 bytes from 111.29.22.227 (111.29.22.227): icmp_seq=6 ttl=55 time=28.1 ms

**Comment by HaBaPoT** [comment]
192.168.0.0/24 > 192.168.0.106 » [09:08:53] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106 » [09:08:54] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106 » [09:08:55] [sys.log] [war] arp.spoof could not find spoof targets
192.168.0.0/24 > 192.168.0.106 » [09:08:56] [sys.log] [war] arp.spoof could not find spoof targets

You need to configure your network adapters on virtual machines.
