### ISSUE TITLE
Windows Install?

### ISSUE THREAD

**Issue by MattPlayGamez** [bettercap/bettercap#947]
Hi,
How to install it on Windows?
Have a nice day,

Matthew

**Comment by Azrotronik** [comment]
If you want a precompiled binary, here is the slightly older version:
https://github.com/bettercap/bettercap/releases/tag/v2.31.1 (bettercap_windows_amd64_v2.31.1.zip)

which isn't recommended, It's better to install Go, clone the source code, and run the Makefile, It's easy as 1 2 3.

**Comment by MattPlayGamez** [comment]
hi @Gustavomurta,
Sorry for the late response,
**pkg-config: exec: “pkg-config”: executable file not found in %PATH%**
I got this error, but I've installed go(lang) and CMake, so I don't understand what I'm missing.

Matthew

**Comment by MattPlayGamez** [comment]
Hi @Gustavomurta,

I've Go(lang) installed and CMake.
I can't get Bettercap installed via `go install github.com/bettercap/bettercap@latest`
I get an error that `pkg-config` isn't installed, but I can only find it for Linux.

Matthew

**Comment by Gustavomurta** [comment]
Hi Mattew, 
I didn't have this problem in the installation because I already had pkg-config installed on windows.
You may try install this - [pkg-config_0.23-2_win64.zip](https://download.gnome.org/binaries/win64/dependencies/pkg-config_0.23-2_win64.zip)
https://download.gnome.org/binaries/win64/dependencies/

**Comment by BitterSauce** [comment]
I am an absolute noob into the world of coding and compilation. I want to install and test with Bettercap. Do you guys recommend youtube or practice some coding languages first?

**Comment by darias08** [comment]
> If you want a precompiled binary, here is the slightly older version: https://github.com/bettercap/bettercap/releases/tag/v2.31.1 (bettercap_windows_amd64_v2.31.1.zip)
> 
> which isn't recommended, It's better to install Go, clone the source code, and run the Makefile, It's easy as 1 2 3.

How exactly do you run the MakeFile? I have already installed go on my Windows 10 and I have created the git clone for this repository. And now if I want to run the `MakeFile` on windows 10 cmd it won't run. Anything I can do to get bettercap to run?

**Comment by ZXTube** [comment]
> How exactly do you run the MakeFile? I have already installed go on my Windows 10 and I have created the git clone for this repository. And now if I want to run the `MakeFile` on windows 10 cmd it won't run. Anything I can do to get bettercap to run?

You can download make from google or using choco if you have it installed (`choco install make`). And then you open cmd in the bettercap directory, and type make in the cmd

**Comment by TheKevinWang** [comment]
If you don't need hid modules, you can also simply delete all files in modules/hid/ and remove the entries for gousb and nrf24 in go.mod and modules/module.go (and also delete `sess.Register(hid.NewHIDRecon(sess))` )
