### ISSUE TITLE
net.sniff on causes weird log

### ISSUE THREAD

**Issue by lolea-xandr** [bettercap/bettercap#948]
After running bettercap with a caplet containing these commands:
net.probe on
set arp.spoof.fullduplex true
set arp.spoof.targets 192.168.200.130
arp.spoof on
net.sniff on

bettercap started generating this: "[net.sniff.dns] dns gateway > local : 2.200.168.192.in-addr.arpa is Non-Existent Domain"

I have tried running the commands one by one and the message started showing up after "net.sniff on".

The weird thing is I've tried the exact same thing again (running the commands manually) and the message appeared only once, whereas in the first case it keeps on being shown every 5 seconds

What could be causing this log? 

PS: I have tried these exact same commands before and they worked perfectly fine.

**Comment by anirud-09** [comment]
Bro Don't change hstshijack file. In zsecurity video he has replace hstshijjack with modified one but now in v2.23 the issuse was solved to there is no need of to change the directory hstshijack.

**Comment by MacharlaLalithAkash** [comment]
> After running bettercap with a caplet containing these commands: net.probe on set arp.spoof.fullduplex true set arp.spoof.targets 192.168.200.130 arp.spoof on net.sniff on
> 
> bettercap started generating this: "[net.sniff.dns] dns gateway > local : 2.200.168.192.in-addr.arpa is Non-Existent Domain"
> 
> I have tried running the commands one by one and the message started showing up after "net.sniff on".
> 
> The weird thing is I've tried the exact same thing again (running the commands manually) and the message appeared only once, whereas in the first case it keeps on being shown every 5 seconds
> 
> What could be causing this log?
> 
> PS: I have tried these exact same commands before and they worked perfectly fine.

Same thing is happening with me!!
What I found is arp spoof is happening but victim is not able to surf the Internet.
I also tried to allow ipv4 packet forwarding using "**_sudo echo 1 > /proc/sys/net/ipv4/ip_forward_**" but still no use.

Someone please help me wit this...

**Comment by amit0688** [comment]
bhai iska soluution mila ?

**Comment by jimmyjenseng** [comment]
Please, have you found any solution yet as I'm facing similar issues at the moment. 
Thank you

**Comment by Alhawwashi** [comment]
It happens normally and you don't care, but is the victim's device connected to the Internet?

If yes, it is normal. Basically, in a man-in-the-middle attack, you are basically literally kneading the network. When some requests are sent by the victim’s device in large quantities, they are not received and you are shown Non-Existent Domain.
