### ISSUE TITLE
Is bettercap at the end of its development?

### ISSUE THREAD

**Issue by ToontjeM** [bettercap/bettercap#950]
Latest release Aug 2021. No updates to support libpcap > 0.8
Do we need to start looking at alternatives?

**Comment by tigerschweinekater** [comment]
It is a great project, so I think it would be sad to just abandon it like this. If there are no patches around that solve the issue, maybe we as its community (who cannot find the time to port it to recent libpcap releases ourselves, at least I absolutely can't unfortunately) should try and put out a bounty for this? What do you think about this? Or are there even any patches that fix the issue?

**Comment by cyber-arsenull** [comment]
What would be needed to support libpcap > 0.8?

**Comment by evilsocket** [comment]
Hi.

Short answer: no, the project is not at the end of its development. You can see that there have been commits after the release you're mentioning https://github.com/bettercap/bettercap/compare/v2.32.0...master

Recently (about 6 months ago) I took a sabbatical, away from work and (mostly) away from computers and especially coding, that is why i've been less active on this and other repos. Now I'm slowly getting back to writing code, but I'm not willing to rush it.

Having said that, I'm planning new features for bettercap, but at this time I'm not going to commit to a timeline or to a specific amount of effort. This is an unpaid and open source project after all, people can contribute with their own code and I'm always more than happy to merge valid pull requests.
