### ISSUE TITLE
How to trigger captive portal?

### ISSUE THREAD

**Issue by nexon33** [bettercap/bettercap#952]
So I want to trigger a captive portal that goes to my apache server on kali.
Currently I redirect all http traffic with 302 to the ip of the apache server (local on the same kali pc) with arp spoofing and http proxy.

I tried to block the connection with arp.ban but that doesn't seem to work. Is there any way to drop all https traffic and isolate the machine so I can trigger a captive portal? (or some other way to trigger a captive portal)

I only used arp with default settings which is half duplex mode if I remembered correctly.

**Comment by evilsocket** [comment]
this is a start https://github.com/bettercap/caplets/tree/master/web-override

**Comment by buffermet** [comment]
The captive portal module can be found here: https://github.com/bettercap/bettercap/issues/631#issuecomment-2726983539
