### ISSUE TITLE
Searching for a plugin ScreenShotter to capture screenshots from clients browsers 

### ISSUE THREAD

**Issue by minanagehsalalma** [bettercap/bettercap#957]
[The Plugin in mention 
](https://github.com/byt3bl33d3r/MITMf/blob/master/plugins/screenshotter.py)

[A video of it 
](https://youtu.be/SHI7E4hl6k8)

i searched the whole web and couldn't find anything like it for modern tools 

I am a bit puzzled .. as  the plugin seems pretty basic , how there isn't  a one for better cap till now :|

Thanks

**Comment by buffermet** [comment]
Tools like html2canvas already exist and nothing is stopping you from using it in a HTTP proxy.

**Comment by minanagehsalalma** [comment]
> Tools like html2canvas already exist and nothing is stopping you from using it in a HTTP proxy.

@buffermet  hmm but this isn't a plugin , is it ?

How do i use it ? 

I think I could work out the injection part , but what about the automatically saving images on my device not the client device every couple of seconds ? Do i have to get the browser to send the images to the proxy as post request or ...? I don't quite get how the screen shoter plugin does it.

Any Guide about injecting such js libraries and getting them to work across all site would be appreciated : )

**Comment by minanagehsalalma** [comment]
> There's an entire guide written at https://bettercap.org

I meant for close problems like this

But thanks will give it a look : )

**Comment by minanagehsalalma** [comment]
@buffermet Lol , look what i found while trying my luck with double quotes and a lot of search tries 

> capture screen shots of the browser "bettercap"


![image](https://user-images.githubusercontent.com/20546638/165351636-aeab91f3-c9dd-4566-9221-a2071bd43f40.png)

Shame on you have a post about the same very thing i am asking for and not telling 😥

**Comment by buffermet** [comment]
Shame on me?

I simply didn't know that post existed.

You're wasting my time and your own when you could have just looked for what you want to find.

**Comment by buffermet** [comment]
And by the way, that image literally shows html2canvas which is what I mentioned earlier.

Don't abuse the issue page for 1:1 tutorial requests.
