### ISSUE TITLE
webui no longer works, the webpage only displays the words "Time" and "Type".

### ISSUE THREAD

**Issue by gn0b0dy** [bettercap/bettercap#958]
I have tried this on nethunter on my phone and also on kali 64bit on the raspberry pi 4. I follow the webui instructions on the bettercap website and input the commands to start the local http webui. Everything works so far. I go to 127.0.0.1 and enter my credentials to access the webui. When I enter them it sends me to a page (127.0.0.1/#/events) that only displays the words "Time" and "Type". The webpage has some styling done and looks to be grey, which is what I remember the styling looking like when I used to be able to get this to work. I used to be able to run this on nethunter fine, please help me figure out what is wrong, thanks.

**Comment by schlaf3r** [comment]
reinstall the web ui interface following these instructions. https://github.com/bettercap/ui i had the same problem and by reinstalling it i got it to work again.

**Comment by EthanZoneCoding** [comment]
I was able to fix it by installing the 1.31 version

**Comment by schlaf3r** [comment]
The latest version is 1.30 on the officialpage. Where did you find a 1.31 version at?

**Comment by EthanZoneCoding** [comment]
I replaced the binary with the one from here, restarted, updated caplets, and ran.

https://github.com/bettercap/bettercap/releases/tag/v2.31.1

**Comment by EthanZoneCoding** [comment]
Oh my mistake, it was 2.31

**Comment by rocemc** [comment]
> Oh my mistake, it was 2.31

Hi, how did you replace the binary?
Thank you

**Comment by EthanZoneCoding** [comment]
I literally dragged the new one into the same folder as the old one and chose replace when it told me it already existed.

**Comment by rocemc** [comment]
Hi, thank you. That sounds easy enough. I will give it a try.

**Comment by kawaiipantsu** [comment]
**Hi this is still an issue - Just to be clear.**
(Though this might be more suited for the bettercap-ui repo??)

Clean install on fresh Kali in this example.
First i just install as normal
```
apt-get update
apt-get install bettercap bettercap-caplets bettercap-ui
```

Run bettercap, and update caplets and update ui.
```
» caplets.update
[21:46:47] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
[21:46:49] [sys.log] [inf] caplets installing caplets to /usr/local/share/bettercap/caplets ...

» ui.update
[21:47:01] [sys.log] [inf] ui checking latest stable release ...
[21:47:02] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...
[21:47:04] [sys.log] [war] ui removing previously installed UI from /usr/local/share/bettercap/ui ...
[21:47:04] [sys.log] [inf] ui installing to /usr/local/share/bettercap/ui ...
[21:47:05] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
```

Now i start the UI
```
» http-ui
[21:40:39] [sys.log] [inf] http.server starting on http://127.0.0.1:80
[21:40:39] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
```

Opening browser (Firefox 91.9.0esr) and logging in, just getting an empty page with Time, Type shown top left.
![bettercap-ui-problem](https://user-images.githubusercontent.com/12233528/179605471-24b462a7-e272-400f-91a1-11940e269220.png)

The web-developer console just throws constant messages with:
> ERROR TypeError: n.ble is undefined

**Comment by jilleb** [comment]
Can confirm,this is reproducable.

**Comment by Lungshot** [comment]
Same issue

**Comment by 8xu** [comment]
> **EDIT: To be clear, this is already reported in the bettercap-ui repo as an issue. Guess we can close it in here. EDIT: bettercap-ui issue link: [bettercap/ui#81](https://github.com/bettercap/ui/issues/81)**
> 
> **EDIT2: As a followup, what worked for me was to uninstall the packages from Kali and git clone bettercap and install/build it manually. Then follow the update steps and web-ui works as intended. So there must be some changes made in beteween the deb packages version and source**
> 
> **Hi this is still an issue - Just to be clear.** (Though this might be more suited for the bettercap-ui repo??)
> 
> Clean install on fresh Kali in this example. First i just install as normal
> 
> ```
> apt-get update
> apt-get install bettercap bettercap-caplets bettercap-ui
> ```
> 
> Run bettercap, and update caplets and update ui.
> 
> ```
> # bettercap
> bettercap v2.32.0 (built for linux amd64 with go1.18.1) [type 'help' for a list of commands]
> » caplets.update
> [21:46:47] [sys.log] [inf] caplets downloading caplets from https://github.com/bettercap/caplets/archive/master.zip ...
> [21:46:49] [sys.log] [inf] caplets installing caplets to /usr/local/share/bettercap/caplets ...
> 
> » ui.update
> [21:47:01] [sys.log] [inf] ui checking latest stable release ...
> [21:47:02] [sys.log] [inf] ui downloading ui v1.3.0 from https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip ...
> [21:47:04] [sys.log] [war] ui removing previously installed UI from /usr/local/share/bettercap/ui ...
> [21:47:04] [sys.log] [inf] ui installing to /usr/local/share/bettercap/ui ...
> [21:47:05] [sys.log] [inf] ui installation complete, you can now run the http-ui (or https-ui) caplet to start the UI.
> ```
> 
> Now i start the UI
> 
> ```
> » http-ui
> [21:40:39] [sys.log] [inf] http.server starting on http://127.0.0.1:80
> [21:40:39] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
> ```
> 
> Opening browser (Firefox 91.9.0esr) and logging in, just getting an empty page with Time, Type shown top left. ![bettercap-ui-problem](https://user-images.githubusercontent.com/12233528/179605471-24b462a7-e272-400f-91a1-11940e269220.png)
> 
> The web-developer console just throws constant messages with:
> 
> > ERROR TypeError: n.ble is undefined

Having the same issue. Running kali

**Comment by DeserranoJorden** [comment]
Same issue here

**Comment by AryanHere71** [comment]
```

sudo apt install -y golang git libusb-1.0-0-dev libpcap-dev libnetfilter-queue-dev
git clone https://github.com/bettercap/bettercap.git
cd bettercap
go install
go build
sudo ./bettercap

caplets.update
ui.update
https-ui enable

```

it worked for me

**Comment by unknownvmdk** [comment]
same issue ...

**Comment by kelke** [comment]
same issue.. kali package did not work, while compiling using go did

**Comment by theomgdev** [comment]
same issue

**Comment by fvsion** [comment]
Same issue kali package broken.

**Comment by SWxEng** [comment]
same issue in kali 

![image](https://user-images.githubusercontent.com/55116927/218638042-8a2f1d2a-6931-466b-90d5-61a7337738df.png)

**Comment by SWxEng** [comment]
> ```
> 
> sudo apt install -y golang git libusb-1.0-0-dev libpcap-dev libnetfilter-queue-dev
> git clone https://github.com/bettercap/bettercap.git
> cd bettercap
> go install
> go build
> sudo ./bettercap
> 
> caplets.update
> ui.update
> https-ui enable
> ```

it worked for me

**Comment by lorena-ml** [comment]
hello!!! i made everything here and now i cant execute bettercap. It says my interface doesnt exist even though >it does<

Does someone know what can i do in this case?

**Comment by MirozoPL** [comment]
> caplets.update
> ui.update
> https-ui enable

Can't connect to https://0.0.0.0:8083/api

**Comment by lorena-ml** [comment]
I actually made this commands and didn't work either :(

but it's okay. tysm!

2023년 5월 7일 (일) 오후 12:15, Mirozo ***@***.***>님이 작성:

**Comment by xDarkAntiMatterx** [comment]
sudo apt install -y golang git libusb-1.0-0-dev libpcap-dev libnetfilter-queue-dev
git clone https://github.com/bettercap/bettercap.git
cd bettercap
go install
go build
sudo ./bettercap

caplets.update
ui.update
https-ui
working

**Comment by gonzalu** [comment]
> reinstall the web ui interface following these instructions. https://github.com/bettercap/ui i had the same problem and by reinstalling it i got it to work again.

So far this option is well into an hour of updates and installs LOL. Be aware that nodejs, npm take FOREVER to install on a Raspberry pi 4 with latest Kali Linux x64

Finally it ended with unresolvable errors. :( Will try on 32bit Kali for Raspberry.

**Comment by keldnorman** [comment]
I made a helper script to install the latest version here: 

https://github.com/keldnorman/bettercap2.32.0

**Comment by xiaoyao9184** [comment]
same issue @ kali 2024.2

```
┌──(kali㉿kali-raspberry-pi-zero-w)-[~]
└─$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2024.2
Codename:       kali-rolling
```


```
┌──(kali㉿kali-raspberry-pi-zero-w)-[~]
└─$ apt show bettercap
Package: bettercap
Version: 2.32.0+git20240107.924ff57-1~exp1
Built-Using: golang-1.22 (= 1.22.3-1), golang-github-acarl005-stripansi (= 0.0~git20180116.5a71ef0-3), golang-github-adrianmo-go-nmea (= 1.8.0-1), golang-github-antchfx-jsonquery (= 1.3.4-1), golang-github-antchfx-xpath (= 1.3.0-1), golang-github-bettercap-nrf24 (= 0.0~git20190219.aa37e6d-2), golang-github-bettercap-readline (= 1.4+git20210228.655e48b-2), golang-github-chifflier-nfqueue-go (= 0.0~git20170228.61ca646-2), golang-github-dustin-go-humanize (= 1.0.1-1), golang-github-elazarl-goproxy (= 1.1-1), golang-github-evilsocket-islazy (= 1.11.0-1), golang-github-evilsocket-recording (= 0.0~git20190408.3ce1dcf-2), golang-github-gobwas-glob (= 0.2.3+git20180208.19c076c-2), golang-github-golang-groupcache (= 0.0~git20210331.41bb18b-1), golang-github-google-go-github (= 60.0.0-1), golang-github-google-go-querystring (= 1.1.0-2), golang-github-google-gousb (= 1.1.1-3), golang-github-gorilla-mux (= 1.8.1-1), golang-github-gorilla-websocket (= 1.5.1-1), golang-github-hashicorp-mdns (= 1.0.3-2), golang-github-jpillora-go-tld (= 1.2.1-2), golang-github-kr-binarydist (= 0.1.0-1), golang-github-malfunkt-iprange (= 0.9.0-5), golang-github-mdlayher-dhcp6 (= 0.0~git20190311.2a67805-2), golang-github-miekg-dns (= 1.1.58-1), golang-github-mitchellh-go-homedir (= 1.1.0-1), golang-github-pkg-errors (= 0.9.1-3), golang-github-robertkrimen-otto (= 0.0~git20200922.ef014fd-2), golang-github-stratoberry-go-gpsd (= 1.3.0-1~exp1), golang-github-tarm-serial (= 0.0+git20151113-5.1), golang-github-thoj-go-ircevent (= 0.2-3), golang-golang-x-net (= 1:0.24.0+dfsg-1), golang-golang-x-sys (= 0.19.0-1), golang-golang-x-text (= 0.14.0-2), golang-gopkg-sourcemap.v1 (= 1.0.5+git20170213.0.6e83ace-1), golang-vhost (= 0.0~git20140120-3), gopacket (= 1.1.19-6)
Priority: optional
Section: net
Maintainer: Debian Security Tools <team+pkg-security@tracker.debian.org>
Installed-Size: 24.8 MB
Depends: ca-certificates, iproute2, iptables, iw, libc6 (>= 2.34), libnetfilter-queue1 (>= 1.0.0), libpcap0.8t64 (>= 1.5.1), libusb-1.0-0 (>= 2:1.0.22)
Homepage: https://www.bettercap.org
Download-Size: 6,476 kB
APT-Manual-Installed: yes
APT-Sources: http://http.kali.org/kali kali-rolling/main armel Packages
Description: Complete, modular, portable and easily extensible MITM framework
 The Swiss Army knife for 802.11, BLE, IPv4 and IPv6 networks reconnaissance
 and MITM attacks.
 .
 bettercap is a powerful, easily extensible and portable framework  written
 in Go which aims to offer to security researchers, red teamers and reverse
 engineers an easy to use, all-in-one solution with all the features they
 might possibly need for performing reconnaissance and attacking WiFi
 networks, Bluetooth Low Energy devices, wireless HID devices and Ethernet
 networks.
 .
 Main Features:
  * WiFi networks scanning, deauthentication attack, clientless PMKID
    association attack and automatic WPA/WPA2 client handshakes capture.
  * Bluetooth Low Energy devices scanning, characteristics enumeration,
    reading and writing.
  * 2.4Ghz wireless devices scanning and MouseJacking attacks with
    over-the-air HID frames injection (with DuckyScript support).
  * Passive and active IP network hosts probing and recon.
  * ARP, DNS, NDP and DHCPv6 spoofers for MITM attacks on IPv4 and IPv6
    based networks.
  * Proxies at packet level, TCP level and HTTP/HTTPS application level
    fully scriptable with easy to implement javascript plugins.
  * A powerful network sniffer for credentials harvesting which can also be
    used as a network protocol fuzzer.
  * A very fast port scanner.
  * A powerful REST API with support for asynchronous events notification
    on websocket to orchestrate your attacks easily.
  * A very convenient web UI.
  * More! (https://www.bettercap.org/modules/)
 .
 This package contains a Swiss Army knife for 802.11, BLE and Ethernet networks
 reconnaissance and attacks.


┌──(kali㉿kali-raspberry-pi-zero-w)-[~]
└─$ apt show bettercap-ui
Package: bettercap-ui
Version: 1.3.0+really1.3.0-0kali1
Priority: optional
Section: javascript
Maintainer: Kali Developers <devel@kali.org>
Installed-Size: 19.8 MB
Depends: bettercap, bettercap-caplets
Homepage: https://github.com/bettercap/ui
Download-Size: 2,103 kB
APT-Manual-Installed: yes
APT-Sources: http://http.kali.org/kali kali-rolling/main armel Packages
Description: bettercap's web UI
 This package contains the bettercap's web UI.


┌──(kali㉿kali-raspberry-pi-zero-w)-[~]
└─$ apt show bettercap-caplets
Package: bettercap-caplets
Version: 0+git20230105-0kali1
Priority: optional
Section: misc
Maintainer: Kali Developers <devel@kali.org>
Installed-Size: 395 kB
Depends: bettercap-ui
Recommends: bettercap
Homepage: https://github.com/bettercap/caplets
Download-Size: 113 kB
APT-Manual-Installed: yes
APT-Sources: http://http.kali.org/kali kali-rolling/main armel Packages
Description: Bettercap scripts (caplets) and proxy modules
 This package contains Bettercap scripts (caplets) and proxy modules. The
 bettercap's interactive sessions can be scripted with .cap files, or caplets.
```

the bettercap pkg in kali maintained by Debian Security Tools see https://pkg.kali.org/pkg/bettercap

I also check https://bugs.kali.org/view_all_bug_page.php, https://bugs.kali.org/view.php?id=8435

Since the UI 1.3.0 version is fixed and released many years ago, I don't think it's a version mismatch problem. I think the Debian team modified its version and there is a compatibility problem.

I am registering for a Kali and Debian tracker account, but my gmail cannot receive the verification email. Maybe Gmail is also shutting down.

**Comment by hwac121** [comment]
**Mine Is Fixed!**
I am on Kali LINUX and had the same issue. I fixed my issue by uninstalling the Kali repo versions of bettercap, web ui, and caplets. Then I followed the instructions on the Bettercap home page and installed it manually myself. Everything not only works perfectly now, but it is much faster response time.

**Comment by vitorhmcorreia** [comment]
2024 update, for a local installation:


> sudo apt install -y golang git libusb-1.0-0-dev libpcap-dev libnetfilter-queue-dev
> git clone https://github.com/bettercap/bettercap.git
> cd bettercap
> go install
> go build

> sudo ./bettercap
>> caplets.update
>> quit

> sudo ./bettercap sudo ./bettercap -caplet https-ui

**Comment by edilbertoh7** [comment]
cual es el nombre de usuario y contraseña de la interfaz grafica de bettercap?
gracias
