### ISSUE TITLE
alias command not working with some entries

### ISSUE THREAD

**Issue by tonjo** [bettercap/bettercap#96]
### Description

Not sure if it is a bug, maybe is intended. It would be nice, though.

`alias` command not working with own pc mac address. 
Probably it works only with new endpoints discovered.

### Environment

- OS version: Ubuntu 16.04, kernel 4.13.0-36-generic
- bettercap version: from go get ... Tuesday 27 at 14:20 Italian time

### Steps to Reproduce

1. net.show
2. choose pc mac address and try to set an alias: `alias MAC_ADDRESS_MYPC mypc`

**Expected behavior:** 
Alias is set.

**Actual behavior:**
An error occur

[betterbug2.txt](https://github.com/bettercap/bettercap/files/1763369/betterbug2.txt)

**Comment by evilsocket** [comment]
yes, it doesn't make sense giving an alias to your own address, it is expected
