### ISSUE TITLE
arp spoof not working

### ISSUE THREAD

**Issue by bugattie** [bettercap/bettercap#960]
I have two machines on my VirtualBox and they both are set to NatNetwork, one is Kali and the other is MSEdge - Windows 10.

I have installed bettercap v2.32.0.

My target windows has an ip 10.0.2.4
I ran these commands from my kali attackers machine
```
set arp.spoof.fullduplex true
set arp.spoof.targets 10.0.2.4; arp.spoof on
```
> The above command returns
> arp.spoof arp spoofer started, probing 1 targets.

But right after these commands, I'm losing internet connection on my target windows machine, therefore I'm unable to see any results on my Kali machine.

**Comment by D4rkX0** [comment]
Hello,

im facing same issue, i can made arp spoofing in ettercap, but it doesn't work with bettercam.

**Comment by Master-Kang** [comment]
没有人回答问题吗？。。。

**Comment by orcundinler** [comment]
you can check the video:

https://www.youtube.com/watch?v=ufCjg55jWaE
