### ISSUE TITLE
2.32.0 ble.show module not showing up for me

### ISSUE THREAD

**Issue by Beauxrel** [bettercap/bettercap#962]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ). ***2.32.0***
* OS version and architecture you are using. ***Kali Linux VM***

### Steps to Reproduce

1. sudo bettercap
2. help
3.  ??? The module isnt there

**Expected behavior:** *What you expected to happen*
        Expected module to show up
**Actual behavior:** *What actually happened*
       ble module is not showing up

**Comment by mikeelliottuk** [comment]
I get the same.  Have just installed bettercap on new Ubuntu installation.  ble module not present, ble commands generate error.

**Comment by Beauxrel** [comment]
Could someone also provide instructions on how to download and run previous versions of bettercap with source code, Im new to linux.

**Comment by You-ne** [comment]
Same probleme here, too bad as I was mainly using bettercap for its BLE module... For anyone in need, ble module is still here in v2.31.1, see here (https://miloserdov.org/?p=1112) how to reinstall it from source.

**Comment by marcsal1** [comment]
Same issue for me: BLE module does not show up on version 2.32.0. (using kali)

**Comment by You-ne** [comment]
> Could someone also provide instructions on how to download and run previous versions of bettercap with source code, Im new to linux.

Here ya go: https://miloserdov.org/?p=1112

**Comment by marcsal1** [comment]
With the docker image it still works.
`sudo docker pull bettercap/bettercap`
`sudo docker run -it --privileged --net=host bettercap/bettercap --eval "ble.recon on"`

**Comment by mikeelliottuk** [comment]
> With the docker image it still works. `sudo docker pull bettercap/bettercap` `sudo docker run -it --privileged --net=host bettercap/bettercap --eval "ble.recon on"`

Yeah, I've been testing this with mixed results.  I start up bettercap in the container and it immeadiately finds six or seven devices.  I can enumerate them etc, but a few seconds later they all drop and it stops discovering anything new.  Only way I can see to get it working is to quit the app and relaunch the container.  hciconfig shows that my bluetooth adapter is still up and running.  Are you seeing the same?

**Comment by marcsal1** [comment]
> > With the docker image it still works. `sudo docker pull bettercap/bettercap` `sudo docker run -it --privileged --net=host bettercap/bettercap --eval "ble.recon on"`
> 
> Yeah, I've been testing this with mixed results. I start up bettercap in the container and it immeadiately finds six or seven devices. I can enumerate them etc, but a few seconds later they all drop and it stops discovering anything new. Only way I can see to get it working is to quit the app and relaunch the container. hciconfig shows that my bluetooth adapter is still up and running. Are you seeing the same?

Yes, I had the same issue.

**Comment by mikeelliottuk** [comment]
> > Could someone also provide instructions on how to download and run previous versions of bettercap with source code, Im new to linux.
> 
> Here ya go: https://miloserdov.org/?p=1112

thanks for the info, but I couldn't work out from this page how to install a previous version.  From the bettercap releases page I can see that the previous version is 2.31.1 but I've no idea how to obtain it.

Any help appreciated.

**Comment by mr-slonn** [comment]
It's working! https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500

**Comment by mikeelliottuk** [comment]
> It's working! [#970 (comment)](https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500)

Could you please elaborate?  Is there a new version available?  Did you change something to get it working, or has it always worked for you on this version?

**Comment by mikeelliottuk** [comment]
> > > It's working! [#970 (comment)](https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500)
> > 
> > 
> > Could you please elaborate? Is there a new version available? Did you change something to get it working, or has it always worked for you on this version?
> 
> I installed the latest version of Kali and "blu.recon on" did not work for me as described in this and also in that topic, I did everything according to the instructions from the comment [#970 (comment)](https://github.com/bettercap/bettercap/issues/970#issuecomment-1154161500) and everything worked.

beautiful... tried the same steps and it's now working on Ubuntu also.  Thanks for sharing.

**Comment by ChayimEliazer** [comment]
> I get the same. Have just installed bettercap on new Ubuntu installation. ble module not present, ble commands generate error.
> 
> Bettercap version 2.32.0, installed yesterday. OS is Ubuntu Desktop v22.04, x64.
> 
> help Modules
> 
> ```
>   any.proxy > not running
>    api.rest > not running
>   arp.spoof > not running
>          c2 > not running
>     caplets > not running
> dhcp6.spoof > not running
>   dns.spoof > not running
> ```
> 
> events.stream > running hid > not running http.proxy > not running http.server > not running https.proxy > not running https.server > not running mac.changer > not running mdns.server > not running mysql.server > not running ndp.spoof > not running net.probe > not running net.recon > not running net.sniff > not running packet.proxy > not running syn.scan > not running tcp.proxy > not running ticker > not running ui > not running update > not running wifi > not running wol > not running
> 
> ble.show 192.168.1.0/24 > 192.168.1.123 » [19:16:23] [sys.log] [err] unknown or invalid syntax "ble.show", type help for the help menu.

Just type the name of the service then type on

**Comment by chesspkali** [comment]
> With the docker image it still works. `sudo docker pull bettercap/bettercap` `sudo docker run -it --privileged --net=host bettercap/bettercap --eval "ble.recon on"`

lots of thank you bro

**Comment by ankush10001** [comment]
![Screenshot 2024-06-02 081904](https://github.com/bettercap/bettercap/assets/136737868/458f7e37-19a7-41cf-927e-ae294783c72a)
 help me
