### ISSUE TITLE
Bettercap Error in Termux when running command "bettercap""

### ISSUE THREAD

**Issue by Jbrimbelibap** [bettercap/bettercap#963]
CANNOT LINK EXECUTABLE "bettercap": cannot locate symbol "nfq_fd" referenced by "/data/data/com.termux/files/usr/bin/bettercap"...

Using termux, i ran "pkg install bettercap" to get the tool (didn't want to compile)

Please provide:

Bettercap 2.32.0-1 aarch64
Android 12L
"pkg install bettercap",  then i ran "bettercap"

### Steps to Reproduce

1. Install dependencies listed on install guide website 
2. pkg install bettercap
3. bettercap or sudo bettercap or bettercap --help or anything really 

Expected in to start like on my Linux pc
got this instead: 
CANNOT LINK EXECUTABLE "bettercap": cannot locate symbol "nfq_fd" referenced by "/data/data/com.termux/files/usr/bin/bettercap"...

♥ I reproduced the issue on 2 phones, if my issue is unjustified please guide me

**Comment by sans404-dev** [comment]
Same issue, CANNOT LINK EXECUTABLE "./bettercap": library "libmnl.so.0" not found

**Comment by sans404-dev** [comment]
I found solution, type go install github.com/bettercap/bettercap@latest && cd $HOME/go/bin then you can execute sudo ./bettercap

**Comment by Jbrimbelibap** [comment]
Thank you, it does work ! Do you know a way to use the wlan0 for monitoring ? I was able to do so with airodump-ng and some binaries i added in /system/bin to enable the monitor mode on qualcomm wireless inferfaces. Bettercap doesn't detect it unfortunatly

**Comment by evilsocket** [comment]
seems to be an issue related to whatever build mechanism is used for that package, closing

**Comment by sans404-dev** [comment]
> Thank you, it does work ! Do you know a way to use the wlan0 for monitoring ? I was able to do so with airodump-ng and some binaries i added in /system/bin to enable the monitor mode on qualcomm wireless inferfaces. Bettercap doesn't detect it unfortunatly

airodump-ng start wlan0
