### ISSUE TITLE
HID Recon - Error in libusb on Kali

### ISSUE THREAD

**Issue by s2cube** [bettercap/bettercap#969]
HID Recon - Error in libusb on Kali

### Environment

Please provide:

Version: bettercap v2.32.0 (built for linux amd64 with go1.18.1)
libusb-1.0-0 and libusb-1.0-0-dev installed
* Command line arguments: (-debug)
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

hid hopping on 83 channels every 100ms
handle_events: error: libusb: interrupted [code -10]

### Steps to Reproduce

1. Connect CrazyRadio PA with Research Firmware
2. sudo bettercap
3. hid.recon on

**Expected behavior:** *What you expected to happen*

No errors. 

**Actual behavior:** *What actually happened*

It works in Ubuntu with the same settings as Kali

Tried on two separate Kali installations.

It displays this error repeatedly : 

handle_events: error: libusb: interrupted [code -10]

--

**Comment by DAT4** [comment]
I get the same error - also with crazyradio on arch linux it is annoying :)

**Comment by SeregaEngineer** [comment]
hi, is there any way to hide this error?
