### ISSUE TITLE
bettercap cannot find BLE modules

### ISSUE THREAD

**Issue by peterfajardo** [bettercap/bettercap#970]
bettercap v2.32.0 (built for linux amd64 with go1.18.1)

error: [err] unknown or invalid syntax "ble.recon on", type help for the help menu

to recreate:

#i invoked bettercap by running:
sudo bettercap
# then to reproduce the error simply typed ble.recon on

when i look into the modules folder,there is no ble folder

*** am i missing something??

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by peterfajardo** [comment]
THANK YOU!!!  probelm solved ... 
Thank you DroidKali. That was the problem. Problem SOLVED

**Comment by DroidKali** [comment]
You are welcome! Glad to help you.
