### ISSUE TITLE
'http.proxy on' command returns exit status 1

### ISSUE THREAD

**Issue by AlphaHd0** [bettercap/bettercap#974]
* When I use the `http.proxy on` command, it gives the following error:

`[11:34:37] [sys.log] [err] exit status 1`

### Environment

Please provide:

* Bettercap version - bettercap v2.31.1 (built for windows amd64 with zip file)
* OS version and architecture you are using - Windows 10 (x64)

### Steps to Reproduce

1. *I run all of the above session commands*

**Expected behavior:** *Running the above code without errors.*

**Actual behavior:** *Returns the above error.*

**Comment by oluwaponle** [comment]
Run with elevated privileges - sudo on unix, administrator on Windows
