### ISSUE TITLE
Can't find router Mac Address 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [bettercap/bettercap#975]
Hi you guys I've finally had time to submit a report been working crazy hours so I haven't touched my setup in a focused manner in a while debating doing it now as I'm exhausted but I really enjoy using bettercap2 we have a click jacking abilitiy yo is there a tut for that.

*Description of the bug or feature request*

### Environment

Dragon os focal live USB 

Please provide:

* Bettercap version you are using ( `bettercap -version` ).

Latest

* OS version and architecture you are using.
Lubuntu dragon os focal latest 

* Go version if building from sources.

Latest Go Version 

* Command line arguments you are using.

Sudo -i

Bettercap -iface wlo1 --gateway-override 192.168.1.1

Net.probe on
Net.sniff on

Set arp.spoof.fullduplex true
Arp.spoof on 

* Caplet code you are using or the interactive session commands.

Manual because I'm built like that 

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

Literally that's my only issue

Mac address gateway not found 

### Steps to Reproduce

1. sudo -i 
2. Bettercap -iface wlo1 --gateway-override 192.168.1.1
3. Arp.spoof on 

..*

**Expected behavior:** *What you expected to happen*

Being able to see my app traffic

**Actual behavior:** *What actually happened*

Mac address for the gateway isn't found 😞

Then it goes kapoot and replays the same error message and makes me sad 

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by w3ider** [comment]
Hello, 

I also had the same problem, especially when changing network card types (I'm talking about virtual environments, I went from bridged to host-only and there appeared the problem, investigating I realized that for some reason, although linux is assigned the IP configuration by DHCP without problems bettercap does not pick up that change, but if you manually set the IP on the network card you are going to use bettercap can read it without problems.

curious things, I hope it helps, because looking all over the internet I did not find the solution to this.

**Comment by ChillVibesMushroom** [comment]
> Hello,
> 
> I also had the same problem, especially when changing network card types (I'm talking about virtual environments, I went from bridged to host-only and there appeared the problem, investigating I realized that for some reason, although linux is assigned the IP configuration by DHCP without problems bettercap does not pick up that change, but if you manually set the IP on the network card you are going to use bettercap can read it without problems.
> 
> curious things, I hope it helps, because looking all over the internet I did not find the solution to this.

Thank you

**Comment by evanwheelrr** [comment]
I have the same problem. Can someone tell me step by step how to fix it?

**Comment by TalhaOzbek** [comment]
Another solution is to write "bettercap" or "bettercap eth0" (whichever you are using) to the root terminal many times. it will be work you can be sure about it.

**Comment by evilsocket** [comment]
no debug logs provided
