### ISSUE TITLE
 error while initializing wlan0 to channel 1: iwconfig: out=Error for wireless request "Set Frequency" (8B04) : SET failed on device wlan0 ; Operation not supported. err=exit status 250 

### ISSUE THREAD

**Issue by ghost** [bettercap/bettercap#978]
# Prerequisites
 error while initializing wlan0 to channel 1: iwconfig: out=Error for wireless request "Set Frequency" (8B04) : SET failed on device wlan0 ; Operation not supported. err=exit status 250 
---

*Description of the bug or feature request*

### Environment

Please provide:

*bettercap v2.32.0 (built for linux amd64 with go1.18.5)
* Linux voidinc 5.18.15-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:41 +0000 x86_64 GNU/Linux
* go version go1.18.5 linux/amd64
  * sudo bettercap -caplet http-ui
* Caplet code you are using or the interactive session commands.
* **https://pastebin.com/arn2Z4ga

### Steps to Reproduce

1. open the webui
2. go the the wifi tab
3. click the start wifi module

**Expected behavior:** *What you expected to happen*
No errors

**Actual behavior:** *What actually happened*
 error while initializing wlan0 to channel 1: iwconfig: out=Error for wireless request "Set Frequency" (8B04) : SET failed on device wlan0 ; Operation not supported. err=exit status 250 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by DogLife2007** [comment]
what network card are you using?
