### ISSUE TITLE
error while loading shared libraries: libpcap.so.0.8

### ISSUE THREAD

**Issue by kurobeats** [bettercap/bettercap#98]
### Prerequisites

* [x ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

Running the AMD64 release binary results in an error:

`bettercap: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory`

### Environment

Fedora 27, 64bit
```
bettercap -debug
bettercap: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
```

### Steps to Reproduce

1. Download release
2. chmod 755 ./bettercap
3. Error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

**Expected behavior:** *What you expected to happen*
libpcap is installed:

/usr/lib64/libpcap.so.1
/usr/lib64/libpcap.so.1.8.1

**Actual behavior:** *What actually happened*
It did not find libpcap
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Can you try to symlink it from your version?

**Comment by asjadsyed** [comment]
For other people having this issue, here's specifically what I did to solve it:

```sh
$ locate libpcap
/usr/lib64/libpcap.so <-- was one among many results for me
$ cd /usr/lib64/ # go to that directory
$ sudo ln -s libpcap.so libpcap.so.0.8 # create a symlink to libpcap.so.0.8 from libpcap.so (or whatever you actually have instead)
$ cd - # go back to your bettercap directory
```

**Comment by cyqsimon** [comment]
@asjadsyed I ran into this same issue when trying to use https://github.com/jclehner/nmrpflash
Your solution worked for me too, thanks.

**Comment by egyptianf** [comment]
@asjadsyed I ran into the smae issue when trying to run [Lantern](https://github.com/getlantern) in my `manjaro` linux, and your solution also worked for me too, thanks.
