### ISSUE TITLE
security_monitor script can not operate

### ISSUE THREAD

**Issue by LuckyFishGeek** [bettercap/bettercap#984]
*version： bettercap v2.32.0
*OS：kali 5.18.0-kali7-amd64
* Command line arguments you are using:     bettercap -script /root/scripts/security_monitor/main.js

### Steps to Reproduce

1. run:   bettercap -script /root/scripts/security_monitor/main.js
2. error:  error loading /root/scripts/security_monitor/main.js: ReferenceError: 'fileExists' is not defined
3. project address:   https://github.com/bettercap/scripts/tree/main/security_monitor

**Expected behavior:** *What you expected to happen*
Script does not run
**Actual behavior:** *What actually happened*
![Snipaste_2022-10-08_09-20-14](https://user-images.githubusercontent.com/29472751/194680506-41d212b3-31b9-413a-a3c8-964cde10c6e6.png)

**Comment by evilsocket** [comment]
can't reproduce
