### ISSUE TITLE
make docker fails

### ISSUE THREAD

**Issue by tranzmatt** [bettercap/bettercap#987]
make docker fails from the master branch fails with the following:

Host OS:
Docker version 20.10.18, build b40c2f6
Ubuntu 22.04

Sending build context to Docker daemon  55.17MB
Step 1/18 : FROM golang:alpine AS build-env
 ---> f9a40cb7e8ec
Step 2/18 : ENV SRC_DIR $GOPATH/src/github.com/bettercap/bettercap
 ---> Using cache
 ---> 0e4035d5a286
Step 3/18 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> 824116f63f6b
Step 4/18 : RUN apk add --no-cache bash iptables wireless-tools build-base libpcap-dev libusb-dev linux-headers libnetfilter_queue-dev git
 ---> Using cache
 ---> 6edd819094c8
Step 5/18 : WORKDIR $SRC_DIR
 ---> Using cache
 ---> 0f710d920edb
Step 6/18 : ADD . $SRC_DIR
 ---> 2ab7e6d95fb8
Step 7/18 : RUN make V=1 build
 ---> Running in 1203f6a4d449
go build -o bettercap .
go: downloading github.com/evilsocket/islazy v1.10.6
go: downloading github.com/bettercap/readline v0.0.0-20210228151553-655e48bcb7bf
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/robertkrimen/otto v0.0.0-20210614181706-373ff5438452
go: downloading github.com/malfunkt/iprange v0.9.0
go: downloading github.com/bettercap/recording v0.0.0-20190408083647-3ce1dcf032e3
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: downloading github.com/thoj/go-ircevent v0.0.0-20210723090443-73e444401d64
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/mdlayher/dhcp6 v0.0.0-20190311162359-2a67805d7d0b
go: downloading github.com/gobwas/glob v0.0.0-20181002190808-e7a84e9525fe
go: downloading github.com/adrianmo/go-nmea v1.3.0
go: downloading github.com/koppacetic/go-gpsd v0.4.0
go: downloading github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: downloading github.com/bettercap/gatt v0.0.0-20210514133428-df6e615f2f67
go: downloading github.com/hashicorp/mdns v1.0.4
go: downloading github.com/chifflier/nfqueue-go v0.0.0-20170228160439-61ca646babef
go: downloading github.com/bettercap/nrf24 v0.0.0-20190219153547-aa37e6d0e0eb
go: downloading github.com/google/gousb v1.1.2
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/antchfx/jsonquery v1.1.4
go: downloading github.com/miekg/dns v1.1.43
go: downloading golang.org/x/net v0.0.0-20210813160813-60bc85c4be6d
go: downloading github.com/elazarl/goproxy v0.0.0-20210801061803-8e322dfb79c4
go: downloading github.com/inconshreveable/go-vhost v0.0.0-20160627193104-06d84117953b
go: downloading github.com/jpillora/go-tld v1.1.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/kr/binarydist v0.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/sys v0.0.0-20210820121016-41cdb8703e55
go: downloading github.com/antchfx/xpath v1.2.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading gopkg.in/sourcemap.v1 v1.0.5
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.13
go: downloading github.com/google/go-querystring v1.1.0
# github.com/chifflier/nfqueue-go/nfqueue
/go/pkg/mod/github.com/chifflier/nfqueue-go@v0.0.0-20170228160439-61ca646babef/nfqueue/nfqueue.go:187:29: could not determine kind of name for C.u_int16_t
/go/pkg/mod/github.com/chifflier/nfqueue-go@v0.0.0-20170228160439-61ca646babef/nfqueue/nfqueue.go:269:35: could not determine kind of name for C.u_int32_t
/go/pkg/mod/github.com/chifflier/nfqueue-go@v0.0.0-20170228160439-61ca646babef/nfqueue/nfqueue.go:257:27: could not determine kind of name for C.u_int8_t
make: *** [Makefile:9: build] Error 2
The command '/bin/sh -c make V=1 build' returned a non-zero code: 2
make: *** [Makefile:24: docker] Error 2

**Comment by tranzmatt** [comment]
Looks like it built ok when I forced the docker to golang:1.16-alpine3.15  Not sure why it builds on Ubuntu 22.04 with 1.18.5, but not under alpine's

**Comment by evilsocket** [comment]
fixed in 2.33.0
