### ISSUE TITLE
Can you use bettercap as an evil router ?

### ISSUE THREAD

**Issue by 0xfalafel** [bettercap/bettercap#989]
I was wondering if it is possible to use bettercap to do a **"physical" man in the middle**.
You plug the **device** you want to attack on **one interface**, and you have your default wifi / **network interface** on the **other**.

![mitm_evil_router](https://user-images.githubusercontent.com/4268373/195846572-56cfb903-325e-4007-b15f-6707a6761b09.png)

From what I have read in the documentation. You can only attack a router, and do an arp cache poisoning, etc.
Is there a way to **turn** your **Linux laptop** into an **evil router** ?

**Comment by ChillVibesMushroom** [comment]
Airgeddon helps you build a fake so that you can use bettercap with but honestly you wouldn’t need too

**Comment by ChillVibesMushroom** [comment]
I go a question do I have to disable firewall before dns spoofing my windows victim on bettercap2
