### ISSUE TITLE
bettercap ui not working as expected

### ISSUE THREAD

**Issue by unknownvmdk** [bettercap/bettercap#992]
bettercap version v2.32

when I log in to bettercap UI I got an empty page with 2 words Time and Type 
![Screenshot 2022-11-05 at 5 07 24 PM](https://user-images.githubusercontent.com/117523016/200123885-9c1f2817-b5e5-4f28-b68c-4424e8f4d5d4.png)

When I inspect the page I got an error on the console
**`ERROR TypeError: n.ble is undefined`**

Any suggestion to fix this issue

**Comment by konsumer** [comment]
Not sure where you got it, but I noticed kali repos seem to have a bad old version.

You can use [latest release](https://github.com/bettercap/bettercap/releases), and it should work. On a pi4 (64bit) I did this:

```
wget https://github.com/bettercap/bettercap/releases/download/v2.31.1/bettercap_linux_aarch64_v2.31.1.zip
unzip bettercap_linux_aarch64_v2.31.1.zip
sudo ./bettercap -eval "caplets.update; ui.update; q"
sudo ./bettercap -caplet https-ui
```
