### ISSUE TITLE
Internal connections (to router or other devices on the network) blocked while external requests are forwarded properly when arp spoofing

### ISSUE THREAD

**Issue by Overthrowing** [bettercap/bettercap#996]
*Description of the bug or feature request*

### Environment

* Bettercap version: v2.31.1 (built for windows amd64 with go1.16.4)
* Windows 11
* Options: -iface \<mymacaddress>
* Commands:
 ```
http-ui on
set arp.spoof.targets <target>
set arp.spoof.fullduplex true
set arp.spoof.internal true
set net.sniff.output <output pcap file>
arp.spoof on
net.sniff on
 ```

### Steps to Reproduce

1. Start bettercap with the interface set to your mac address
2. Run commands found above
3. Visit router login page (192.168.0.1 for netgear router) on victim device

**Expected behavior:** The page loads and the password is stolen when the victim inputs it

**Actual behavior:** The page never loads and the request times out. This seems to happen with all connections to internal ips but external connections are forwarded so I am able to visit other websites. I have tested with all combinations of fullduplex and internal being true or false but the issue persists. I had a few extremely rare instances when the request went through and I was able to intercept the request containing the credentials but I was unable to identify any pattern in these nor recreate them.

**Comment by evilsocket** [comment]
no logs
