### ISSUE TITLE
No 5 GHz networks are shown

### ISSUE THREAD

**Issue by HarryWindsor** [bettercap/bettercap#997]
### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
  *  `bettercap v2.32.0 (built for darwin arm64 with go1.17.2)`
* OS version and architecture you are using.
  *  `macOS 12.6 21G115 arm64`
* Go version if building from sources.
* Command line arguments you are using.  
* `-iface en0 -debug`
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

Run `bettercap` as usual.

1. `sudo bettercap -iface en0 -debug`
```
bettercap v2.32.0 (built for darwin arm64 with go1.17.2) [type 'help' for a list of commands]

 en0  » [12:14:51] [sys.log] [dbg] arp.spoof arp cache restoration after spoofing enabled
 en0  » [12:14:51] [sys.log] [dbg] Could not find mac for
 en0  » [12:14:51] [session.started] {session.started 2022-11-26 12:14:51.164536 +0800 WITA m=+0.044660709 <nil>}
 en0  » [12:14:51] [mod.started] events.stream
 en0  » wifi.recon on
[12:14:55] [sys.log] [inf] wifi using interface en0 (bc:d0:74:10:f0:df)
[12:14:55] [sys.log] [dbg] wifi interface en0 txpower set to 30
[12:14:55] [sys.log] [dbg] creating capture for 'en0' with options: {Monitor:true Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:500ms}
[12:14:55] [sys.log] [dbg] wifi new frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 5745 5765 5785 5805]
[12:14:55] [sys.log] [dbg] wifi wifi supported frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 5745 5765 5785 5805]
[12:14:55] [sys.log] [inf] wifi started (min rssi: -200 dBm)
[12:14:55] [mod.started] wifi
 en0  » [12:14:55] [sys.log] [inf] wifi channel hopper started.
 en0  » [12:14:55] [sys.log] [dbg] wifi wifi stations pruner started (ap.ttl:5m0s sta.ttl:5m0s).
```
**Expected behavior:** *What you expected to happen*

I expect to see all 5 GHz networks.

**Actual behavior:** *What actually happened*

Only 2.4 GHz networks are shown.

EDIT: I saw this https://github.com/bettercap/bettercap/issues/361 and that there was a pull request that was already merged but it still does not work for me.

**Comment by 1r0** [comment]
Same issue here, no 5GHz channels are scanned. 

A difference I noted with the discussion on #361 is the output from `system_profiler SPAirPortDataType` adds (2 GHz) or (5GHz) to the channel number, see below.

`Supported Channels: 1 (2GHz), 2 (2GHz), 3 (2GHz), 4 (2GHz), 5 (2GHz), 6 (2GHz), 7 (2GHz), 8 (2GHz), 9 (2GHz), 10 (2GHz), 11 (2GHz), 12 (2GHz), 13 (2GHz), 36 (5GHz), 40 (5GHz), 44 (5GHz), 48 (5GHz), 52 (5GHz), 56 (5GHz), 60 (5GHz), 64 (5GHz), 100 (5GHz), 104 (5GHz), 108 (5GHz), 112 (5GHz), 116 (5GHz), 132 (5GHz), 136 (5GHz), 140 (5GHz), 144 (5GHz), 149 (5GHz), 153 (5GHz), 157 (5GHz), 161 (5GHz), 165 (5GHz)`

Can't figure out if this is the problem as I can't code, but I imagine this could mess with the parsing and channel detection on the previous fix in [/network/net_darwin.go](https://github.com/bettercap/bettercap/blob/master/network/net_darwin.go)

**Comment by apertureless** [comment]
Have you tried to set the channels manually? 

```
wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13,36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128,132,136,140,149,153,157,161,165
```

**Comment by evilsocket** [comment]
Fixed by https://github.com/bettercap/bettercap/releases/tag/v2.33.0
