### ISSUE TITLE
Issue with Wifi.Show (MacOS)

### ISSUE THREAD

**Issue by snakysnake** [bettercap/bettercap#998]
⭐️ I got some unexpected behaviour when running wifi.show

```
sudo bettercap -iface en0
> wifi.recon on 
> set wifi.show.sort clients desc
> set ticker.commands 'clear; wifi.show'
> ticker on
```

Running this on macOs leads to just the following output "en0 (ch. 1) / ↑ 0 B / ↓ 3.0 MB / 23650 pkts" - no table as expected..

Info:

MacOS 13 (Ventura)
Macbook Pro M1 2020

after running wifi.recon on its def. working at leat a bit, im new to this so let me know what the issue could be please, sorry if i did something wrong..

**Comment by YKPCLN** [comment]
Hi everyone,

I have same problem too. bettercap not show wifi networks on darwin.

set wifi.interface en0
wifi.recon on
wifi.show

en0 (ch. 1) / ↑ 0 B / ↓ 0 B / 0 pkts

Could you help to solve this problem.

Tnx so much &

**Comment by madeddie** [comment]
Same here, wifi.recon on outputs all the APs around (obfuscated identifying info), but wifi.show doesn't list anything.

Apple M1 Max
MacOS 13.0.1 (22A400)
bettercap v2.32.0 (built for darwin arm64 with go1.19.2)

```
en0  » wifi.recon on
[19:25:57] [sys.log] [inf] wifi using interface en0 (xx:xx:xx:xx:xx:xx)
 en0  » [19:25:57] [sys.log] [inf] wifi started (min rssi: -200 dBm)
 en0  » [19:26:02] [wifi.client.new] new station xx:xx:xx:xx:xx:xx (Samsung Electronics Co.,Ltd) detected for XXXXX (xx:xx:xx:xx:xx:xx)
 en0  » [19:26:04] [wifi.client.probe] station xx:xx:xx:xx:xx:xx is probing for SSID XYX (-93 dBm)
 en0  » [19:26:05] [wifi.client.new] new station xx:xx:xx:xx:xx:xx (Apple, Inc.) detected for ABC (xx:xx:xx:xx:xx:xx)
 en0  » [19:26:06] [wifi.client.new] new station xx:xx:xx:xx:xx:xx (Samsung Electronics Co.,Ltd) detected for abc123 (xx:xx:xx:xx:xx:xx)
 en0  » wifi.show

en0 (ch. 1) / ↑ 0 B / ↓ 2.4 MB / 11191 pkts
```

**Comment by patrvvvk** [comment]
I have the same issue 
`macbook intel 2019`
`Ventura 13.0`
`bettercap v2.32.0 (built for darwin amd64 with go1.19.4)`

**Comment by julienbordet** [comment]
I have the same issue.

```
MacBook Pro Apple M2
Ventura 13.1
bettercap v2.32.0 (built for darwin arm64 with go1.19.2)
```

**Comment by arkeane** [comment]
I have the same issue but it seems to work if i manually select channels with
`wifi.recon.channel CHANNEL`
Multiple channels can be selected and then wifi.show seems to work fine

**Comment by 555Russich** [comment]
looks like i have the same. Also after running `wifi.recon.channel clear` wasn't possible to run any command, long loading and mac's fans was furious...

In my case, it's possible to run `wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13` to set adapter on possible channels as @arkeane mentioned above

**Comment by jedai47** [comment]
same here with ventura 13.2.1

**Comment by gsavelev** [comment]
Same issue on
```
MacBook Air M1 2020
macOS Ventura 13.4
bettercap v2.32.0 (built for darwin arm64 with go1.19.2)
```

**Comment by STvegas** [comment]
I have the same issue.

```
Apple M1 Pro
macOS 13.4.1
bettercap v2.32.0 (built for darwin arm64 with go1.19.2)
```

**Comment by sofakng** [comment]
Same issue here.  Apple M1 Pro, macOS 14.0 (beta), bettercap v2.32.0.

**Comment by tolikkostin** [comment]
Same issue here. Apple M1 Pro, macOS 14.1.2, bettercap v2.32.0.

**Comment by evilsocket** [comment]
disconnect the interface from the wifi networks and deassociate so it doesn't connect automatically back again. you need the wifi interface free and disconnected for this to work

**Comment by tolikkostin** [comment]
@evilsocket your advice doesn't work. My wifi adapter is in monitor mode but I don't see a table with Wi-Fi APs.

**Comment by lrosario** [comment]
same issue here

**Comment by shehackedyou** [comment]
M1 same issue, brew install bettercap, Sonoma

**Comment by S-Ali-Zaidi** [comment]
Same issue here -- I thought I was perhaps doing something wrong

**Comment by tenpester** [comment]
Quick work around:

1.) Launch Wireless Diagnostics: Press Command + Space, type "Wireless Diag.."
2.) Go to Window > Sniffer; start the sniffer, any channel
3.) Wifi icon should have an eye
4.) Launch bettercap, will start scanning all channels
