### ISSUE TITLE
Build error on FreeBSD: packet_proxy: build constraints exclude all Go files

### ISSUE THREAD

**Issue by yonas** [bettercap/bettercap#999]
```
$ make build
...
package github.com/bettercap/bettercap
        imports github.com/bettercap/bettercap/modules
        imports github.com/bettercap/bettercap/modules/packet_proxy: build constraints exclude all Go files in /git/bettercap/modules/packet_proxy
```

### Environment

* Bettercap version you are using ( `bettercap -version` ).
24a5dfe

* OS version and architecture you are using.
`FreeBSD 13.1-RELEASE-p5 amd64`

* Go version if building from sources.
`go1.19.3`

* Command line arguments you are using.
`make build`

* Caplet code you are using or the interactive session commands.
n/a

* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
n/a

### Steps to Reproduce

1. Run `make build`

**Comment by evilsocket** [comment]
fixed upstream
